### ISSUE TITLE
Slashing design flaw

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1000]
Currently, a slashing proposition from the council w.r.t. a working group lead, or even the lead w.r.t. a worker can be intercepted by the relevant target, and they can submit a `leave_role` request which may preempt this first proposition. In this case, the role representation will be removed, and the fact that the stake still persists will still not allow the slashing intended. This is a serious design flaw which basically renders slashing impotent.

The remedy will have to be deployed in a later release after Nicaea, and it may be fixed a few different ways, e.g.

1. Introduce a chilling period for every request to leave. For leads, the period must be longer than the time it takes for the corresponding slashing proposal to get executed, and for workers, it must be long enough to not interrupt a competing extrinsic for the same block, so quite short really.

2. Introduce some sort of general role freezing functionality, which also may be required for other purposes, such as to avoid a destructive exit scenario when someone is not disciplined by the prospect of slashing.

3. Perhaps the refactoring of stake management in the new council&election system will automatically deal with this, at least for leads.

**Comment by traumschule** [comment]
Has this been fixed?

**Comment by bedeho** [comment]
@shamil-gadelshin is this fixed in Olympia?

**Comment by shamil-gadelshin** [comment]
We have an unstaking period for workers. It could be defined by the job opening, and it starts on worker leaving (leave_role extrinsic). There are no connections with proposals.

So, we have a way (close to 1.)  to deal with it, but it's not bulletproof.
