### ISSUE TITLE
Network testing: execution time reduction

### ISSUE THREAD

**Issue by gleb-urvanov** [Joystream/joystream#1006]
Refactor tests to reduce execution time. This could be done by calling setup fixtures, like council election, only once and reusing the environment where applicable.

**Comment by gleb-urvanov** [comment]
https://github.com/Joystream/joystream/pull/1166

**Comment by mnaamani** [comment]
This has worked quite well and reduced the test run (with the 2sec block production time) to roughly 20minutes (down from 45min)
