### ISSUE TITLE
Network testing: state transfer between scenarios

### ISSUE THREAD

**Issue by gleb-urvanov** [Joystream/joystream#1007]
Introduce mechanism to share keys (and other possibly required state) between testing scenarios. Required by https://github.com/Joystream/joystream/issues/1006
Currently there are two proposed approaches:
- persistence layer, existing during tests execution, to store any shared state;
- derivation of the keys (which are only known data required to be shared) in a deterministic way.

**Comment by gleb-urvanov** [comment]
https://github.com/Joystream/joystream/pull/1166

**Comment by mnaamani** [comment]
The approach taken is to have a lowdb database which persists some state (council member keys, general members, account nonces)
https://github.com/Joystream/joystream/pull/1225

The way our test runner runs a set of tests like so:

`tap --files src/iznik/tests/councilSetup.ts src/iznik/tests/proposals/*Test.ts src/iznik/tests/leaderSetup.ts src/iznik/tests/workingGroup/*Test.ts -T`

Each 'set' of .ts files run in a separate child process. So the database is needed to persist state. This avoids the need for example to create a new council or elect a new lead for each subset of tests.

There is too much information however stored in this db which I think is not necessary. Only values that really need to be persisted are the keys and the member ids of members generated by the tests themselves. All other information can be read from the chain state?
