### ISSUE TITLE
Network testing: ansible playbook to build a node with reduced block creation time

### ISSUE THREAD

**Issue by gleb-urvanov** [Joystream/joystream#1008]
Create ansible playbook to build a node with reduced block creation time

**Comment by mnaamani** [comment]
Done in https://github.com/Joystream/joystream/pull/1225

**Comment by mnaamani** [comment]
Its done by modifying the source code by running a script: https://github.com/Joystream/joystream/blob/master/scripts/alter-block-creation-time.sh

Not the ideal way. In future we want to make some of the runtime constants configurable at build time somehow.
