### ISSUE TITLE
Network testing: make triggerable in CI

### ISSUE THREAD

**Issue by gleb-urvanov** [Joystream/joystream#1011]
Make network tests triggerable using github labels or similar mechanism

**Comment by gleb-urvanov** [comment]
https://github.com/Joystream/joystream/pull/1181

**Comment by mnaamani** [comment]
The github workflow files here implements it
https://github.com/Joystream/joystream/blob/master/.github/workflows/run-network-tests.yml#L9

This is slightly improved in https://github.com/Joystream/joystream/pull/1461/files#diff-d26fbcdc2a937ec1f56fe2986d382cdbR8
So we can re-run the action when the PR is synced. Previously it had to either be triggered manually (for a branch) or by removing the label and adding it again.
