### ISSUE TITLE
Proposal: Redirect Joystream.co to Joystream.org?

### ISSUE THREAD

**Issue by blrhc** [Joystream/joystream#105]
I may be misunderstanding the purpose of Joystream.co, but for the meantime, wouldn't it be better to forward/redirect it to Joystream.org (seems to be the preferred version)?

![joystreamco](https://user-images.githubusercontent.com/4144334/63218141-e44b6400-c119-11e9-8f1f-673838a21c83.jpeg)
![joystreamorg](https://user-images.githubusercontent.com/4144334/63218142-e7deeb00-c119-11e9-8a34-6cd90ba75210.jpeg)

Probably not a priority on account of Rome development, but I'd argue that the current set-up has the potential to confuse search engines somewhat.

**Comment by bwhm** [comment]
I'd forgotten to redirect after we re-deployed the site...

Thanks @blrhc, done!
