### ISSUE TITLE
How to do data fetching in Joystream applications

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1096]
# Background

I have been thinking about this looming issue we have of: how to we make it easy to have application developers make apps on top of our system when there is no one single canonical hosted API that binds it all together (say the way  Facebook probably is able to give on API to access everything in their system). This will lead us to have applications needing to fetch things from N distinct sources, of which any single one can fail or take different amounts of time to complete (e.g. query node, stats servers, storage servers with images, backend personalized storage, etc.), and then having to stitch these all together in a way that is convenient to use with our front-end components, tests and so on, would be very involved and brittle.

How should we attack this?

# Proposal

Apparently, something like running a GraphQL on the client-side (without a client-side server that is), is a thing that people have started doing, and it's been referenced specifically in the context of the new data fetching requirements that Dapps will impose. Could this be the path forward?

See 
- https://hasura.io/blog/client-side-graphql-schema-resolving-and-schema-stitching-f4d8bccc42d2/
- https://github.com/slightlytyler/graphql-outside-the-box
- https://youtu.be/rb8ccqm7R_8?t=706

> With the advent of blockchain technology and the concept of “dapps” we must reconsider the role of the application that runs on the end user’s device. By running GraphQL on the client we can consume remote GraphQL services, interact directly with the blockchain, browser / native APIs, and more through GraphQL.

This is _one_ idea, it may not be the best approach, we should consider also researching what other blockchain projects are doing their SDKs.

**Comment by bedeho** [comment]
# Note

Perhaps we should try to think about making requests and subscribing to events in the same context, not just fetcing data?

**Comment by kdembler** [comment]
I'm not sure if you've talked with @Gamaranto about this, but that's something we've already discussed and had both come to this idea on our own. This concept sounds really interesting. That would allow us to actually stitch different APIs and interconnected resources together but also potentially to do some data translation. In the context of Atlas we were thinking about using something like this to for example convert timestamps to Date objects.

Definitely worth researching and considering.
