### ISSUE TITLE
Faucet improvement: stepping faucet

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1097]
There are many new users asking for testnet tokens which is great! The issue is that we are using Telegram as our method of onboarding new users and the requirements for a Telegram account are such that it is possible for users to create dozens of accounts and manipulate the faucet.

The technical knowledge to use Joystream is still quite significant for first time users and there hasn't been a great amount of videos uploaded or forum posts made just yet.

shubidooo in the Telegram suggested a "stepping faucet" where users are required to go through a number of steps. The tokens they are initially given should be enough to complete the steps, but the additional amounts would be for taking extra steps.

1. New user asks for tokens in Telegram and is given `n` amount of tokens.
1. User signs up for membership and is given an additional amount of tokens.
1. User creates a forum post in the "new users / introductions" thread and is given tokens based on their introduction.
1. User is given a link to some public domain content and uploads a video that fulfills some requirements and are given more tokens.
1. User uploads an original video and is awarded more tokens.

Ideally, since the token requirement for certain actions (like creating a spending proposal) is quite high, the amount the user has at the end of this process should be enough to create a spending proposal. In this way new users have a clear way to obtain tokens that would allow them to engage in more significant actions on the platform and also learn about the platform + provide value to the platform.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703603360391) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
This is a really interesting idea. The fact that doing these steps now is actually kind of hard almost makes it like an anti-Sybill mechanism in of itself. 

I think this is something the growth team (@bwhm, @blrhc ) should think of how to do.

One could start off with a really simple manual approach, where a human would have to confirm each attempt and confirm that someone had gone through the right steps. The stepping guide could also just be a simple document linked to on various blog posts and also provided as an answer when people come and ask. A later version could be really well done with smooth branded igraphics and deep integration into the project website, and automation at different steps.

**Comment by mochet** [comment]
In order to deincentivize sybil attacks, we could add a multiplier for one of the steps, probably the public domain content one.
example:
- upload 1st video = 100 tokens
- upload 2nd video = 120 tokens
- upload 3rd video = 140 tokens

This multiplier would be one of the last steps available, so it would require the most work to be able to apply for. If there was some limit of a video per day and a maximum multiplier applied, it could be a good way of getting a constant stream of uploads happening. Having a per day limit would also ensure actors have to be present every day rather than just obtaining faucet tokens and never interacting on the platform again.

**Comment by mochet** [comment]
This is very out of date and no longer really relevant, so closing.
A stepping faucet could still be utilized in some form, but it probably needs a complete rewrite and wouldn't really be solved via the runtime.
