### ISSUE TITLE
Possible bug for reusing the staked balance from the last council round

### ISSUE THREAD

**Issue by kek-mex** [Joystream/joystream#111]
I found this weird thing while reusing the staked joy from the last council round.
I will here show and describe the steps to produce this.

Here is the stake from my last round, which I have used for the council:

![stake](https://user-images.githubusercontent.com/50080006/71250576-a7da7f80-2328-11ea-8737-725cae58f62e.png)

A new round has now started, and I want to reuse my stake. However even though I can use it, I had to get more tokens to stake, so I could reuse it. I did already stake most of the tokens from the last round but had just enough to produce this "issue".

I had 200 balance before getting new tokens, and I tried writing 1000 (I had tokens staked on the current round), but I could not stake them before I had at least 1000 JOY on the current balance.
Here is a GIF showing, that you can only stake tokens from the last round if you have at least 1000 JOY on the current balance:

![application](https://user-images.githubusercontent.com/50080006/71250582-ac9f3380-2328-11ea-8101-337430e41590.gif)

As you can see, I had 1200~ on the current balance, and I could not stake 2000, but I could stake 1000 JOY two times in a row.

I think that this should be changed so that you could stake tokens from the last round, even if you did not have any balance. I consider it to be essential, as this method can be very inconvenient if you have for example 100k JOY from the last round, but you need to re-stake it in small portions such as 1000 JOY 100 times.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703511705609) by [Unito](https://www.unito.io)

**Comment by blrhc** [comment]
Thanks for the report, will try to reproduce this behaviour and get back to you!

**Comment by kek-mex** [comment]
I've also noticed that the voting page allows you to enter unlimited balance to vote but of course, it fails when broadcasted. I think that it should be grayed out if you enter an amount bigger than your current usable balance.

![pinta](https://user-images.githubusercontent.com/50080006/74611583-d648c100-5105-11ea-9b8c-226e2529fca4.png)

**Comment by blrhc** [comment]
> I've also noticed that the voting page allows you to enter unlimited balance to vote but of course, it fails when broadcasted. I think that it should be grayed out if you enter an amount bigger than your current usable balance.
> 
> ![pinta](https://user-images.githubusercontent.com/50080006/74611583-d648c100-5105-11ea-9b8c-226e2529fca4.png)

Good idea, will see if this can be implemented before Rome!
