### ISSUE TITLE
Remove Types That Use Partial To Use Optional Fields instead

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#1119]
Currently some components are not correctly typed. They look like this:

```javascript
type ComponentProps = {
// some type
}

const Component: React.FC<Partial<ComponentProps>> = () => {
// some component 
}

```

This makes all the properties optional and nullifies type safety.
Change this by properly annotating fields that might be undefined in the type declaration and by removing `Partial` if not all fields are optional.

**Comment by kdembler** [comment]
Closing in favor of #1263
