### ISSUE TITLE
Intermediate runtime proposal upgrade

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#1121]
As this doesn't really fit inside any project, I will just make a quick writeup now for review before I proceed and ask for assistance. As we've discussed loosely, there are some arguments to make a small runtime upgrade that fixes some or all of the following issues:

## Validator and Node count
Our validator (and Node) count has dropped further and further. The increase in rewards made for Constantinople has proven to be insufficient for the "Tokenomics" scheme, as the amount of tJOY earned struggles to cover costs. Although the rewards are a *a little* higher, they are still insignificant due to low stake of the validator set. A more thorough guide to understanding the validator rewards can be found [here](https://github.com/Joystream/helpdesk/tree/master/roles/validators#rewards), but a rough TL;DR on the current status:

- Max/min slots: 4/12 `*`
- Occupied slots: 9
- `slotstake`: ~95k (the total stake, as in validator stake+nominator stakes, with the LEAST stake)
- Issuance: ~136M
- Active stake ratio: 95k × 9/136000k ~0.006 -> 0.6%
- Ideal active stake ratio: 30% `**`
- Reward if 30% of tokens was "actively staked" by the validator set: 4,667tJOY
- Last reward: 477tJOY -> 53tJOY per validator per hour.
`*` can be changed by `sudo` or Council
`**` requires runtime upgrade

This means that if we currently had 9 validators, with a `slotstake` of ~15,100,000tJOY they would earn ~87k a week. Which is still little. Factor in the risk of slashing, there is simply not strong enough incentives to take that role.
For those interested, one can play around with the numbers [here](https://docs.google.com/spreadsheets/d/13Bf7VQ7-W4CEdTQ5LQQWWC7ef3qDU4qRKbnsYtgibGU/edit?usp=sharing)

### Solution
In order to make validating more profitable, we need to reconsider some paramaters that can only be changed via a runtime upgrade:
- Lower the "ideal active stake ratio"
- Increase the minimum inflation (regardless of the number and stake of the validator)
- Increase the maximum inflation (will depend on the "Ideal active stake ratio")
- Lower the frequency and/or magnitude of slashings.

If we decide this is worth doing, I will look more in to the numbers, and propose them to the council. Note that although I understand the reward side - and believe it's very easy to implement once the numbers are settled - I don't know if the same is true for the slashing part of it.

## Forum
As seen [here](https://testnet.joystream.org/#/proposals/11), the Council requested a change in the limit of posts on the forum. It has also been annoying for us.

### Solution
This should be very easy to fix with a few lines of code. There are plenty features that have been requested informally or formally that are not practical to address now, so I think we should be accommodating when we can.

## Proposal Voting Bug 
I couldn't find "our" issue for this, so I'll link to the [issue](https://github.com/Joystream/joystream/issues/828) made by a community member. An overly simplified summary:
When a new Council is elected while a proposal is active, the proposal does not expire, and the votes of re-elected council members are not reset. Under certain circumstances, this can lead to a proposal expiring despite it appearing to have more than enough votes to get approved/rejected/slashed.

I am not as sure this should be fixed now, simply because I don't know how much work it will require. It is a serious bug though, so it needs to be fixed at some point.

## Discussion
I don't have a conclusion here, but I think we should consider these fixes. Excluding the Proposal Voting Bug, may rough estimate of the workload:
- Setting the new values for validator rewards and slashing:  Martin ~ `4`h
- Implementing the fixes: Mokhtar (+ Martin) ~`4`h
- Integration Testing `*`: Gleb ~`n`h
- Upgrade and deploy testing: Martin ~3h

`*`I am not sure we need a full integration test, and have no idea of the time needed.

Any thoughts on this @bedeho and @mnaamani?

**Comment by bwhm** [comment]
@bedeho @shamil-gadelshin 
I'm just pinging you guys about this.


I guess Shamil has gained some knowledge about the changes in the staking module (validators) at this point, so in the event we try to fix this, maybe you are able to find out:
- what are the changes needed to reduce the magnitude of a slashing?
- confirm that changing these through a runtime upgrade will not break anything (changing the rewards side did not previously)
- check that these changes will be compatible with substrate RC4/6

**Comment by bedeho** [comment]
There were so many issues here, cant be processed all at once, also not sufficient context to evaluate urgency. Lets discuss internally next week.
