### ISSUE TITLE
Idea: multiple council mints

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1145]
This is a bit of an accounting question and whether the council mints could eventually receive profit generated by original content it invests in. This may be just something that could be implemented in the way the council works with reports rather than a technical change.

To see this idea a bit in practice, Telefilm Canada has several financing programs, each with different requirements: https://telefilm.ca/en/financing

An example might be having separate mints for:

* R&D
* Original Content
* Short form content
* Marketing & User Growth

When a user creates a spending proposal and selects a particular mint, they would ideally see the requirements/conditions for submitting a spending proposal for that specific mint. 

Questions:

* If the council invests in content and there is some form of profit returned to the council, would it be technically possible to have the funds sent to a mint? So they can be invested back into more content or different areas of focus?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703464272503) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
This is an interesting idea.

1. The core questions seems to be: can we have separate mints with separate purposes and budgets?

Here I think we certainly could, the problem is just tha the runtime cannot check that spending out of each mint is following its purpose, this has to be enforced in terms of incentives. I still think that may have some value, and I am noting it for that.

2. As per investments in content, that is not something we have had a plan to incorporate as a separate feature, at least so far. Now the council can of course finance creation of new content, and then it can be published under a licensing regime that generated value for the platform, which is effectively equivalent to what you are describing I think, however, this would not be its own feature beyond this.

**Comment by mochet** [comment]
1. Yes. I think having separate mints would generate more directed spending from the council. If its all just one big mint, it would end up being quite convoluted, especially if one area is getting far more spending than it should realistically have.
Let's say the council mint is 10 million tokens per month, and localization/translation spending proposals end up getting 40% of the budget. Without separate mints it would be hard to communicate that there's been enough spent on that area. You would have to wait for a report to be issued that shows what was spent and where.
The other bonus of multiple mints is that you can probably implement it on the tokenomics page/report with essentially a "live" view. This is especially the case if the cycle of the mint means it only ends up being refilled once or twice per month. Without some separation of spending, it would be hard to communicate a "live" view of accounts to users of the platform.
Seeing something like the following, that is consistent with the current block height:
![image](https://user-images.githubusercontent.com/50830161/89739456-dfea2a80-da91-11ea-86bc-7dbd30044a36.png)

If you didn't have multiple mints, I would guess that you would have to wait for new council and/or tokenomics reports to be issues, which effectively means having to wait multiple days or weeks for up to date information.

You could also effectively separate what proposals were funded by specific mints which would hopefully bolster what kind of proposals have been approved in the past in that area (ex. for a user interested in marketing, they can more easily see what projects were previously done for marketing & user growth--and also start to form a pattern of what amounts are appropriate for that kind of spending proposal).

The other benefit I could see is that in the event of the council disagreeing on certain things being financed, you would hopefully still have agreement to refill more essential mints and what those amounts should be.

2. Understood.

**Comment by bedeho** [comment]
On the reporting, this something that we will get for free in Pioneer 2, which is live up to date reports on all financial metrics. If the funding proposal text complied with some template for how to describe the funding, then even having one mint could easily allow us to have rich granular reports. The benefit of this approach is that you could easily expand the number of spending categories over time, or retire old ones, without having to do a runtime upgrade.

**Comment by mochet** [comment]
Considering it would require a runtime upgrade, it would probably be best to have the template model you described.
I still think that besides that it would be good to have mints covering 3-4 major areas of spending though, just to create some form of separation and to ensure that spending doesn't become problematically biased towards certain areas. It would also mean that on mainnet you wouldn't have a theoretical situation where someone doing work on a runtime upgrade or something mission critical is competing for funding alongside proposals that aren't as critical.
I could also imagine that if some major upgrade needs doing, it would allow the council to increase the specific mint relating to that work and not be mixed with funds meant for other purposes.

**Comment by bedeho** [comment]
Thanks for the feedback, will bare it in mind!

Love the graphic btw. Thats def. the sort of presentation we need!

**Comment by mochet** [comment]
There is some discussion about how to make this happen on the current testnet: https://testnet.joystream.org/#/forum/threads/263
Maybe the spending proposals system needs some sort of admin role who can tag each spending proposal in the UI? For now we can build another system, but ideally it should be more straightforward than that and let the council have a better way of categorizing spending proposals.
