### ISSUE TITLE
Sideproject: Tokenomics page

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#1154]
# Background

Pioneer is explained [here](https://github.com/Joystream/joystream/issues/377). Although there has been some changes since this, it should add some context.

# Problem

As stated in #489 and #485, and plenty of other issues and discussions really, there is a big problem for council members and others interested in the networks economics really, to get information. Some of this is sprinkled in various tabs here and there, but without using a series of chain state queries, it's still not possible.

# Goal

Working on a page like this is a good way to get to know the network, the API and pioneer as it stands. Although the presentation of data needs some serious thinking, and thus outside the scope of this issue, creating a rough draft is a good place to start.

# Deliverable

Fork pioneer, and a new page that provides and overview of the current state of affairs, and it's tokenomics.

Some pages suffer a bit from the amount of data that has to be read, and this could easily be one of them. Although we can worry about that later, it should be kept in mind, and the biggest problems identified.

For this first iteration, I'll rather add too much than too little. Note that although I tried to keep the constraints we are under without an indexing node, there may be some data that can't really be presented at the moment.

As stated, the structure and design of the page is secondary at this point. The structure below is first and primarily for keeping the issue somewhat organized. It may well be more practical for the final page to include a mix of everything, especially the overview(s).

## Tokenomics
"Tokenomics" (a portmanteau of token and economics) refers to the networks economy.

Ideally, the dollar equivalents should also be available for each of the token amounts addressed.

### Overview
The top level should just have the bare minimum needed.
- Current `totalIssuance`
- Current Fiat Pool
- Current Exchange Rate
- Current `spending` rate pr hour/day/week. This is the sum of:
  - Recurring rewards for:
    - Content Curators
    - Storage Providers
    - Council Members
  - Estimate of Validator rewards
- Total funds `staked`. The sum of the tokens locked in by:
  - Content Curators (+ application stakes)
  - Storage Providers (+ application stakes)
  - Council Members (+ voters)
  - Validators (+ nominators)

- Pie chart displaying each groups share of `spending` and `stake`

### Council
Each working group has a designated `mint`. For the `council`:
- Status of the `mint`
  - Current `capacity`
  - Total `minted`
  - Current (recurring) `spending` pr hour/day/week
    - There are some nuances here, as the Council members stops getting paid when a new election starts.
  - Expected `blockHeigth` when mint will be drained
  - Average `spending` pr hour/day/week since inception
  - Number of Spending Proposals approved, and successfully executed
  - Total amount spent on Spending Proposals
  - Percentage of mint spent on Spending Proposals vs `rewards`
- Election and council status:
  - Current term
  - Number of Council Members
  - Total stake for all Council Members
  - Own stake for all Council Members
  - Backers/voters stake for all Council Members
  - Term started at `blockHeight`
  - Term ends at `blockHeight`
- Council Members stats list:
  - `MemberID/handle`
  - `timestamp/blockHeight` they became members
  - `Address`?
  - Voting stake - `total,own,backers/voters`
  - Number of `backers`
  - Share

### Content Curators
Each working group has a designated `mint`. For the `contentWorkingGroup`:
- Status of the `mint`
  - Current `capacity`
  - Total `minted`
  - Current `spending` pr hour/day/week
  - Expected `blockHeigth` when mint will be drained
  - Average `spending` pr hour/day/week since inception
- Number of current Content Curators.
- Number of previous Content Curators.
- Total `stake` for group
- Current Curator Lead
  - `WorkerID`
  - `MemberID/handle`
  - `Blockheight/time` hired
  - Amount `staked`
  - `recurringRewards` (x tJOY/n blocks)
  - Lifetime `rewards` earned
  - Lifetime `rewards` missed
- Current Content Curators list
  - `WorkerID`
  - `MemberID/handle`
  - `Blockheight/time` hired
  - Amount `staked`
  - `recurringRewards` (x tJOY/n blocks)
  - Lifetime `rewards` earned
  - Lifetime `rewards` missed

### Storage Providers
Each working group has a designated `mint`. For the `storageWorkingGroup`:
- Status of the `mint`
  - Current `capacity`
  - Total `minted`
  - Current `spending` pr hour/day/week
  - Expected `blockHeigth` when mint will be drained
  - Average `spending` pr hour/day/week since inception
- Number of current Storage Providers.
- Number of previous Storage Providers.
- Total `stake` for group
- Current Storage Lead
  - `WorkerID`
  - `MemberID/handle`
  - `Blockheight/time` hired
  - Amount `staked`
  - `recurringRewards` (x tJOY/n blocks)
  - Lifetime `rewards` earned
  - Lifetime `rewards` missed
- Current Storage Providers list
  - `WorkerID`
  - `MemberID/handle`
  - `Blockheight/time` hired
  - Amount `staked`
  - `recurringRewards` (x tJOY/n blocks)
  - Lifetime `rewards` earned
  - Lifetime `rewards` missed

### Validators
For the Validators, this info must be calculated/estimated quite a bit. For info on how to calculate rewards, and terms used below, go [here](https://github.com/Joystream/helpdesk/tree/master/roles/validators#rewards)
- Current data
  - Number of Validators
  - Number of Nominators
  - Max number of Validators
  - Min number of Validators
  - Number of Validators in the "next up" queue
  - Stake required to become a Validator
  - Expected rewards for the Validator set, and each individual, per hour/day/week
  - `total stake` of all Validators (total,own,others)
  - `slotStake`
  - `total active stake`
  - `active stake ratio`
  - staking "efficiency" `total active stake`/`total stake`
- Data assuming Validators rebalance. (Assuming the total stake was distributed perfectly)
  - `slotStake`
  - `total active stake`
  - `active stake ratio`
  - Rebalanced rewards for the Validator set, and each individual, per hour/day/week
  - Difference between rebalanced and current rewards for the Validator set, and each individual, per hour/day/week
  - Rebalanced rewards / Current rewards
- Data assuming the Validator set increases their stake, and distributes it evenly to reach the `ideal stake ratio`
  - `total stake` of all Validators
  - `slotStake`
  - `total active stake`
  - `active stake ratio`
  - Ideal rewards for the Validator set, and each individual, per hour/day/week
  - Difference between ideal and current rewards for the Validator set, and each individual, per hour/day/week
  - Ideal rewards / Current rewards
- As the Validator page contains a sufficiently complex overview, I think we can skip duplicating this.

## General
The stats that is not explicitly tied to the tokenomics.

### Overview
- Brief "get started"?
- Members
  - Link to register
  - Number of members
- Roles and openings:
  - List current openings + links
  - Min stake to become Validator + links
  - Status of Council Election + links
    - If announcing:
      - Current/Max candidates
      - Max Council slots
      - Blocks left to run
    - If voting:
      - Current candidates
      - Blocks left to vote
    - If revealing:  
      - Current candidates
      - Blocks left to vote
    - else:
      - Blocks left to start
      - Max Council slots
    - **This is probably not possible/practical**
- Proposals:
  - Link to page
  - Number of active Proposals
  - List with:
    - ID/Headline as link
    - Type
    - Blocks remaining
    - **Note that this will probably be to slow, combined with the other stuff**

### Forum
- Link to forum page
- Total posts made
- Total categories made
- Latest post(s) preview/link?
- Forum sudo

### Content
- Link to content page
- Number of channels
- Number of videos (entities in `class` 7)
- One embedded video of our choice?
- Files in the `dataDirectory`
- Size of the `dataDirectory`

# Summary
There is a lot of stuff in here, and I'm genuinely not entirely sure what is useful enough to warrant implementing. Not entirely sure how to prioritize either, as the most important stuff IMO the - tokenomics summary - is perhaps the hardest, and will require almost everything else under tokenomics.

I will ask for some input from the community sooner rather than later, but in any case, it's valuable experience.

**Comment by bedeho** [comment]
Done
