### ISSUE TITLE
Idea: Proposal vote reasoning

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1157]
Currently a proposal is made, and discussion takes place either within the proposal itself or elsewhere. Council members can vote to approve, deny, slash or abstain.

In the distant future, when an interested user is looking through hundreds of prior proposals, they would basically have to read through many pages of discussion, possibly in multiple areas of the platform in order to understand why a proposal failed or passed. This still would not directly answer why a council member voted a certain way unless that council member specifically created a post explaining why they voted the way they did.

I would suggest that a field (~120-500 characters) is added to the vote option which allows for a council member to fill in a brief reasoning for their vote. Having this would improve readability of the voting process.

The reasoning could be hidden by a collapse/expand system for each proposal in the proposal overview and for things like council reports, the vote reasoning could be used directly.
This also means that possibly a system is implemented where a user can see the voting history of a specific council member, and quickly digest what kind of reasoning they have employed while a member of the council.

**Comment by bedeho** [comment]
This is brilliant! This is easy and a must-have!

**Comment by mochet** [comment]
Thanks.
One other use of this system would be for council members and users to establish the reputation more clearly of users who have a history of very successful or very unsuccessful proposals.
example: A user has submitted 12 spending proposals in recent history, the first 3 of these were successful and the subsequent 9 were rejected or slashed. A user would be able to see all of these proposals with council member reasoning and quickly be able to digest that council members began rejecting this users proposals because they can rapidly see reasoning like _"Voted to reject as user failed to deliver on previous proposals"_ without having to read through likely a combined hundreds of pages of discussion spanning all of these proposals.

**Comment by bedeho** [comment]
Very true indeed, this is exactly the sort of way we should be building our products: making it easy for participants to evaluate the credibility and effectivness of their peers.

**Comment by mochet** [comment]
This issue could perhaps be expanded to include two additional types of reasoning.
Firstly an incoming reasoning, where a user applying to be a council member can state their mission and goals for the particular election cycle they are applying for. We currently have a thread where a potential council member can state their interests in the platform, but this is an overly broad piece of information and won't relate to specific election cycles unless they continuously update their post.
Secondly an outgoing reasoning, where a CM having completed an election cycle, can provide feedback on the election cycle.

I discussed this a bit here, in relation to how we currently solicit feedback from council members manually, but if this were included in the election process it would hopefully be a great way to standardize the input of this information and this would hopefully mean you could create almost entirely automated council reports.
https://github.com/Joystream/community-repo/issues/9#issuecomment-674771580

This also means that users can look through potential CMs and see their history of incoming reasoning, outgoing reasoning, vote reasoning and build a clearer picture of how viable the candidate would be to stake with tokens. If these reasonings became indexable, you would be able to search for specific issues like "storage rewards" or "validator stake" and it would help to identify past, current and future issues worth looking into.

**Comment by bedeho** [comment]
> Firstly an incoming reasoning, where a user applying to be a council member can state their mission and goals for the particular election cycle they are applying for. We currently have a thread where a potential council member can state their interests in the platform, but this is an overly broad piece of information and won't relate to specific election cycles unless they continuously update their post.

This is already planned, here

https://github.com/Joystream/joystream/issues/895

> Secondly an outgoing reasoning, where a CM having completed an election cycle, can provide feedback on the election cycle.

Just to be clear, this is just an opportunity for each council member to leave a statement associated with their reign in that period? If so, I could see some value in that, and it is trivial to implement.

**Comment by mochet** [comment]
> Just to be clear, this is just an opportunity for each council member to leave a statement associated with their reign in that period? If so, I could see some value in that, and it is trivial to implement.

Yes and if its trivial to implement it would be great to have!

**Comment by bedeho** [comment]
Added => https://github.com/Joystream/joystream/issues/1183

We are reimplementing the council as we speak, so this will get implemented within a matter of days... deployment is another matter.

**Comment by bedeho** [comment]
# Important Addendum

https://testnet.joystream.org/#/forum/threads/101

**Comment by bedeho** [comment]
Another benefit of rationales is that it reduces the risk of inputting an incorrect vote.

**Comment by bedeho** [comment]
Done

**Comment by mochet** [comment]
Although this is done, I have realized now that it can be used as a form of multiple choice proposal.

Example: "How much should we pay for this bounty? Options are A/B/C, fill in when you vote"
