### ISSUE TITLE
A "user governed" or "user-governed" video platform?

### ISSUE THREAD

**Issue by blrhc** [Joystream/joystream#116]
This might seem trivial, but I think we should decide early on whether it should be hyphenated or not.

As a native English speaker, I feel it should be "user-governed".

**Comment by bwhm** [comment]
Didn't consider that. I assume the Brits and Americans use the same style?

**Comment by bedeho** [comment]
I think we should go with hyphenated when you pointed it out it made immediate sense to me. Perhaps you can compile a list of all the places we are using the old style?

**Comment by blrhc** [comment]
Here is a list of all the places where I found the unhyphenated version.
I've made pull requests where possible.

1) https://www.joystream.org home page
2) Website title and metadata
3) joystream/design README ([PR](https://github.com/Joystream/design/pull/12))
4) In whitepaper `Joystream: A Protocol for User Governed Content Platforms` vs `Joystream: A Protocol for User-Governed Content Platforms`
5) GitHub organization description (https://github.com/Joystream)
6) Introducing Jsgenesis Blog Post (https://blog.joystream.org/jsgenesis/)

**Comment by bedeho** [comment]
@bwhm can we deal with this as part of the brand identity rollout?
