### ISSUE TITLE
Idea: Membership referral system

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1173]
# Background

While we have an idea for how to lower the barrier for people without coins to get involved in https://github.com/Joystream/joystream/issues/296, this mechanism provides no real incentive for anyone to go out of their way to seek out and onboarding lots of new members at scale. For this, an explicit incentive is required.

# Proposal

When someone buys a membership, they can list some other member as the referrer and this results in some portion of their membership due being transferred to this referrer, rather than being burned. 

When we incorporate buying periodic access to content, a similar referral scheme can also be very potent.

**Comment by mochet** [comment]
I've seen a similar system before, however they would put a lot of emphasis on inviting good actors. If someone is invited and misbehaves, there were consequences for the user who invited that person.
This would be especially prudent if some user is sending out say 20 invites per week, and 60% of them end up being bad actors.

Not sure how that could be effectively policed, but something to consider.

**Comment by bedeho** [comment]
This is not actually an invitation system, its a referral system, or an affiliate system if you will. A bad actor showing up has actually paid their way on to the platform and has a right to participate. 

I think you may be thinking of this
https://github.com/Joystream/joystream/issues/296

**Comment by bedeho** [comment]
Done in `Olympia`.
