### ISSUE TITLE
Error: No Storage Providers Found?

### ISSUE THREAD

**Issue by blrhc** [Joystream/joystream#118]
![No Storage Providers found?](https://user-images.githubusercontent.com/4144334/64913073-db40b900-d6fe-11e9-963b-348635822a28.jpeg)

I have never seen this error before, is it normal?

**Comment by bwhm** [comment]
No, but I think I've seen it happen before. Did you try refreshing? Do you remember what you were trying to play?

**Comment by blrhc** [comment]
Moved to https://github.com/Joystream/storage-node-joystream/issues/94
