### ISSUE TITLE
Idea: Biweekly community update

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1180]
# Idea: biweekly community update

## Background

@ondratra mentioned in a recent conversation that it could be a good idea to publish more regular incremental updates about how we are doing and where we are going. We are making a lot of progress on a lot of different fronts simultaneously, and the social and community side of the project is also evolving quickly. Only relying on releases as communication milestones may be too infrequent, and also does not give us a chance to present the overall progress of the project more coherently, beyond what is occurring in individual releases. This more overall view of what is going on can also help alleviate the fact that we don't have a public roadmap, something people have asked for.

A nice community which has such updates is the Radicle community, see record here

https://radicle.community/c/announcements/6

## Proposal

We start publishing regular, and specifically biweekly, community updates. This could be in the form of a blog post, which we could also promote on various mailing lists and social channels.

- Key dev metrics: PRs closed, #lines code changed, etc.
- Screenshots of new designs/mockups being worked on.
- Important bugs fixed.
- New founding members inducted.
- Highlight events w.r.t leaderboard.
- Mini GIF demos of new product features, like CLI or.
- Highlighting a new interesting channel or piece of content published.
- Highlighting important proposals or ideas.
- Presenting a new Jsgenesis hire.
- Community member portrait: presenting a person in the community, for example as a 3-5 question mini interview with some key information, like membership handle, location, etc.
- New releases planned, with reference to release plans.
- Changes or updates to launch deadlines.

## Requirements

- A standardized format.
- Basic assets
  - announcement twitter cover
  - blog post cover
- A cheap process of accumulating content for the update as we work.

**Comment by freakstatic** [comment]
This seems like an amazing idea! 
I would love to see more about the ongoing development of the Joystream project

**Comment by mochet** [comment]
I think this would be great, some additions/suggestions:
- Make these posts/updates via the on-chain forum feature _almost_ exclusively. Blog posts are more flexible off-chain, but having these updates created on-chain would allow for a way to build up discussion and interactions on-chain. Even if you make announcements of each update, have them only have an excerpt and link directly to the on-chain forum post so people are forced to interact with the project in an on-chain manner, essentially do not replicate the entire posts/updates officially besides the on-chain forum. This also means that over time these posts form a history that users can go through on the forum itself.
- A forum thread for each iteration, allowing users to ask questions and give feedback that can possibly be answered in the next iteration.
- Possibly also create an incentive for the "best responses/questions/suggestions". These should only be available to the on-chain participants, but advertised outside of this venue (ex. on Telegram) (the onus on on-chain participation means the value is being invested directly into the platform itself)
- Highlighting current / future bounties and upcoming role releases, this would help bring attention to there being rewards available (ex. "bandwidth provider is launching next week, discussion of rewards is here: `[link]`")

**Comment by bedeho** [comment]
Loving the feedback! I agree with it all.

So if we are using the forum, we need to solve a few problems
1. Space limit
2. Faithful display of markdown.

@bwhm second one seems like a good project to tackle for the current front-end sideproject?

**Comment by bwhm** [comment]
Yeah, could be on his (growing) todo list :)
