### ISSUE TITLE
Proposal: New testnet model

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#119]
# A more community engaging testnet governance and token economic model

## Background

Our current way of building our testnets and attempting to build, engage and train our community suffers from a number of short comings.

### Problem 1: Unegaged participants.

A number of roles are already active, specifically voters, council members, storage providers and validators.
Unfortunately, the level of genuine collaboration, deliberation and problem solving which observed is extremly low.

This is in in part likely driven by the fact that the scope and incentives for such activity are not present, in particular:

- Voters have no genuine incentive to participate, let alone to select competent council members.

- Council members in turn have no reason to attract interest of voters, and have very little scope for creating value and contributing, a part from simply showing up to approve a runtime upgrade. There is no incentive to accumulate reputatation or credibility over time.

- Storage Providers have very little load, and are policed entirely by us. There is no incentive to accumulate reputatation or credibility over time.

- Other parts of the platform, like the forum, and the curatation, is currently, or will soon be, under our direct supervision exclusively.

This result in a number of secondary problems

- Participation is boring. No connections are made between particpants, and no one gets a realistic experience of how exciting it could be to be part of operating the platform.

- Particpants learn very little, as they are not challenged to solve genuine problems, or to come up with their own solutions or priotizations.

- We get insufficient feedback about how to guide our product development and community building.
Increases risk of building unworkable or broken token economic system and/or inappropriate tooling and products.

### Problem 2: Sybill attacked token economics

In all of our testnets, the testnet token

- has no value

- is minted in genesis and in block rewards

- is distributed to new members through a faucet

- a key requirement for entering staking roles, which subsequently are rewarded in Monero

since the faucet has been successfully Sybil attacked, we have also observed that many roles have inherited this unfortunate concentration (e.g. council, validators), and the token rewards have further contributed to solidifying insiders.

This is harmful in many ways

- limits community growth: new people cannot easily enter these roles.

- limits ability to train community: <same>

- limits our ability to learn how well our products, infrastructure and communication is actually working

## Proposal

The key idea is to focus on building in a way which takes community governance and operational control seriously. We can do this by combinding the following

1. The token is for the duration of a testnet backed by a certain quantity of real value, which can be redeemed for Monero from us. This means all on-chain rewards, minting, burning, staking and slashing are real economic events. The existing off-chain incentive scheme is discontinued, except for the voters (see next). We probably want to reset the balances on each network upgrade. A tiny amount of tokens is still distributed through the faucet, to allow people to create a membership and pay other tx fees, but the redeemable value should be extremly low. Instead, the way newcomers can accumulate a significant token share, which then gives them the chance to impact voting or get into big staked roles, is by either of the following

   - Solve on of the bounties that we have put out. Hence we need to increase the number and diversity of such bounties. The council can also have its own bounty system, but that would be parallel to ours.
   - Have a KPI which has _some_ paid roles that require no staking.
   - Send real value on another chain to charity.
   - Do some sort of manual anti-sybill sceeening check with us.

2. Give voters outcome based incentives based on KPIs that we define. The rationale for this is that the root source of all good governance are the voters, and currently there is no way to incentivise them to care about this directly. We must define success, and pay for it. Each voter would get a share of the total incentive payout based on their voting power share. These outcomes could be outcomes similar to some of our engagement key results, and also additional important constraints which must be respected, but which are not new in the given release. For example

   - Elect council
   - Get runtime upgraded
   - Perform y on benchmark z
   - Fill x positions of type z
   - Add n new stuff to content
   - Respond timely to complaints

The KPIs could shape the final incentive payoff in different ways. KPIs could be binary or graded goal achievement. Some KPIs could be absolute, in that some levle of failure resulted in no total payout at all. Ultimately, jsgenesis team would have to measure and evaluate goal attainement.

3. Build out the proposal system and tooling in a way such that it is actually possible for the chain of actors voters => councilors => leads/participants to generate the desired outcomes. This means no more reliance on SUDO supervision and magic parameters. Hence, the council/leads would decide how much the reward should be for a given role, or how many actors are required in that role, and so on. The proposal system needs to be much more powerful, and needs to decide on who the lead is for a subsystem or what community initatives sohuld be supported. **It could also be radically extended to empower the council to do things that only Jsgenesis team currently can do, like schedule tweets, newsletters, blog posts, website changes, etc. These latetr things are required if the council is to be fully empower to achieve KPIs that depend on communication.**

For clarification: there are basically two funding pools here. One pool which is the total backing of the JOY testnet token over the lifetime of a network. The second is the total max funding that may go to the voters of each council elected.

**Comment by blrhc** [comment]
As far as I'm concerned, this is an extremely accurate description of the problems we face and you also highlight some interesting potential solutions.

I have a couple of thoughts:

1) In terms of building out the proposal system, you're right that it is extremely limited at the moment and only supports runtime upgrades using WASM files. 

One very simple improvement for Rome might be to allow text-based proposals which could then be acted on by Jsgenesis. For example, if a user suggested that 15 council members might be better than 12, they could make that proposal and if voted for by two thirds of the council it could pass and we could promise to develop/introduce that feature as soon as possible.

2) I think in terms of unengaged participants, part of the problem is that we just don't have a very large number of testnet participants. We could start to solve this quite easily by ramping up investment in advertising and marketing.

3) Eliminating or greatly reducing the possibility of Sybil attacks is absolutely essential to recalibrating the economies on our testnets.

4) In terms of incentivising users to create a record of useful contributions, have you considered a points/rank based system? 

Maybe if I am a higher rank I might be entitled to a higher share of a generous pool of Monero which would be distributed at the end of every testnet. I could obtain a higher rank or points by becoming a council member, making forum posts, being a reliable validator, being a storage provider which never goes offline etc.

5) We're going to have to make very clear the distinction between the two funding pools you discuss here, as I think it could be a source of confusion.

**Comment by bedeho** [comment]
> One very simple improvement for Rome might be to allow text-based proposals which could then be acted on by Jsgenesis.

I think we, unfortunately, can't change the scope for Rome this late in the day, I believe we are already quite a bit behind at the current pace.

> We could start to solve this quite easily by ramping up investment in advertising and marketing.

Is that really the main issue though? To me, it seems much more that there just is not a lot of room for rich decision making where the reward you receive depends on the quality of the decisions made. If we just paid for more participants my hunch is that we would just have a much larger number of equally unengaged participants, or more likely, a more motivated Sybill attacker.

> In terms of incentivising users to create a record of useful contributions, have you considered a points/rank based system?

I think we would want to rely on a mechanism which would be what we would use on the main network as soon as possible, that is sort of the spirit of this proposal.

**Comment by blrhc** [comment]
Thank you for taking the time to address my points.

> I think we, unfortunately, can't change the scope for Rome this late in the day, I believe we are already quite a bit behind at the current pace.

Ok, that's completely fair and I understand that all the specs etc. have already been set out for Rome. 

> Is that really the main issue though? To me, it seems much more that there just is not a lot of room for rich decision making where the reward you receive depends on the quality of the decisions made. If we just paid for more participants my hunch is that we would just have a much larger number of equally unengaged participants, or more likely, a more motivated Sybill attacker.

Your hunch may be absolutely right. However, one counter point might be that the lack of social proof generated by the very small quantity of users currently engaging on the network could be a barrier to more people joining and engaging. There may be a threshold after which there are enough engaged users doing interesting stuff (making and voting on proposals, discussing things on the forum, uploading content etc.) to generate interest for new organic users of the platform (in a compounding way). 

My other question would be, what "rich decision making" is possible at all with such a small community of stakeholders? 

> I think we would want to rely on a mechanism which would be what we would use on the main network as soon as possible, that is sort of the spirit of this proposal.

A better way of articulating what I said is to focus on getting people's contribution history visible on the platform. If they were a council member, what did they vote for? If they were a validator or storage provider, what was their uptime? I think this is important public information which the platform needs to publish to make users accountable and calibrate rewards.

**Comment by bedeho** [comment]
> My other question would be, what "rich decision making" is possible at all with such a small community of stakeholders?

Good question. Almost anything is richer than the decisions available now :D, but it would be things like how much in total to spend on each subsystem, when to fire or hire a subsystem lead, picking new concepts to add to the content directory, evolving the forum moderation policies, etc. More broadly, how to achieve the KPIs we set through a variety of means.

>  focus on getting people's contribution history visible on the platform. If they were a council member, what did they vote for?

I could not agree more, this is huge, and the spirit of this is very explicit in the whitepaper. There is no way we could have robust coordination without this.

**Comment by bedeho** [comment]
First draft here https://github.com/Joystream/joystream/issues/171.
