### ISSUE TITLE
UI/UX issue: Election vs Council round

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1196]
Currently the UI in Pioneer shows election round which is presumably taken from `councilElection.round: 21` in chain state.
In the event of not enough council applicants, the election starts again (it actually extends, since applicants are maintained during the new election round) and this number increases, but the "current" council also extends, and no new council is actually elected until the process completes successfully.

This means a council could continue serving for a period of days/weeks if no successful election period happens.

I couldn't find data from chain state which returns the actual "Council Round" which could be a very different number depending on how elections go. The council round number, which currently doesn't exist, should ideally be referring to actual council rounds (ex. an elected set of council members who have served a council term)

This is either a non-issue or an issue depending on how you view things, but I made an issue since if this has an easy fix, it could be implemented to make things easier for users to understand:
* if at mainnet, there are several election failures, this number would become different enough from actual council rounds to cause some level of confusion. (ex. if after a year, there are 14 failed election rounds, then these two numbers would be different).
* If functionality is ever implemented to browse through previous councils, and this was based on the current `councilElection.round` it would mean there would be councils with incomplete information.

The other alternative is that users use the election round number and there is no usage of "council round number" at all.

**Comment by bwhm** [comment]
Yes, this is indeed somewhat confusing.

> If functionality is ever implemented to browse through previous councils, and this was based on the current councilElection.round it would mean there would be councils with incomplete information.

This is definitively something that is needed, and will be added in pioneer 2.0

@bedeho 
I'm not sure whether the `council/councilElection` 2.0 module spec is done, but is this addressed there?

**Comment by bedeho** [comment]
This is being implemented by @ondratra as we speak, but I have not reviewed yet, but yes I believe this core behavior is correct, and the old council remained staked and locked until an election works out. I am going to guess the runtime does not store any information on what number council is currently serving, because I don't think that information would be useful for anything. This would in that case have to exist in the query node.

Perhaps @ondratra can confirm?

**Comment by ondratra** [comment]
In council 2.0 there is a counter for election cycles that can be read from the chain state. No council cycle index is needed in the state (it might change before release, but not likely). But any necessary information for UI should be extractable from the event log.

Substrate event is fired for all important states changes like *new council elected*, *candidacy announcing started*, *candidacy announcing extended*, etc. By reading & filtering these events, we can get extensive information about current and past councils and elections that can be presented in UI.
