### ISSUE TITLE
Runtime Parameter changes for Alexandria

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#1208]
As Alexandria appears to be closer to launch than first anticipated, we will forgo making an "intermediate" runtime upgrade ref #1121. The changes will instead go in Alexandria.

## Validators
We need to "boost" the rewards for the validators. This may still not be enough, but I think it's a big step in the right direction.

For reference, I've included what is used as "default" for Substrate, and Polkadot/Kusama:

**Substrate:**
```
pallet_staking_reward_curve::build! {
	const REWARD_CURVE: PiecewiseLinear<'static> = curve!(
		min_inflation: 0_025_000,
		max_inflation: 0_100_000,
		ideal_stake: 0_500_000,
		falloff: 0_050_000,
		max_piece_count: 40,
		test_precision: 0_005_000,
	);
}
```
**Polkadot/Kusama:**
```
pallet_staking_reward_curve::build! {
	const REWARD_CURVE: PiecewiseLinear<'static> = curve!(
		min_inflation: 0_025_000,
		max_inflation: 0_100_000,
		// 3:2:1 staked : parachains : float.
		// while there's no parachains, then this is 75% staked : 25% float.
		ideal_stake: 0_750_000,
		falloff: 0_050_000,
		max_piece_count: 40,
		test_precision: 0_005_000,
	);
}
```

**Rome/Constantinople:**
Existing:
```
srml_staking_reward_curve::build! {
    const REWARD_CURVE: PiecewiseLinear<'static> = curve!(
        min_inflation: 0_025_000,
        max_inflation: 0_300_000,
        ideal_stake: 0_300_000,
        falloff: 0_050_000,
        max_piece_count: 100,
        test_precision: 0_005_000,
    );
}
```
New:
```
srml_staking_reward_curve::build! {
    const REWARD_CURVE: PiecewiseLinear<'static> = curve!(
        min_inflation: 0_050_000,
        max_inflation: 0_750_000,
        ideal_stake: 0_250_000,
        falloff: 0_050_000,
        max_piece_count: 100,
        test_precision: 0_005_000,
    );
}
```

### Spending
To allow bigger payouts to contributors:

Current:
`const MAX_SPENDING_PROPOSAL_VALUE: u32 = 2_000_000_u32;`
New:
`const MAX_SPENDING_PROPOSAL_VALUE: u32 = 5_000_000_u32;`

### Set Working Group Mint Capacity
Keep:
`const WORKING_GROUP_MINT_CAPACITY_MAX_VALUE: u32 = 5_000_000;`

Only mentioning as it's currently wrong in pioneer (shows 1M, same as for content/curator WG)...

## Council Election
Couldn't find the actual parameters here (chain_spec had "wrong" ones):

Current:
```
announcing_period = 14400   // 1 day
voting_period = 14400            // 1 day
revealing_period = 14400       // 1 day
new_term_duration = 43200   // 4 days
council_size: 12                       // 10 after sudo fix
```
New:
```
announcing_period = 28800   // 2 days
voting_period = 14400            // 1 day
revealing_period = 14400       // 1 day
new_term_duration = 144000 // 10 days
council_size: 6
```

## Forum
A frequently requested feature...

Current:
```
ForumConfig {
        ...
        post_text_constraint: new_validation(10, 990),
        ...
    }
```
New:
```
ForumConfig {
        ...
        post_text_constraint: new_validation(10, 2990),
        ...
    }
```

---

## Slash Validators

This falls out of the "easy" category, so I don't think anything can/should be done for now. We need to fully understand it though, so I think a some research would be nice :)

**Comment by bwhm** [comment]
@mnaamani 
Any comments or questions?

Also, something for you here as well @Lezek123, but apart from the `Set Working Group Mint Capacity`, I think we should await the formers feedback :)

**Comment by bwhm** [comment]
#1217

**Comment by mnaamani** [comment]
The number look reasonable.

I started implementing changes here: https://github.com/Joystream/joystream/pull/1228
