### ISSUE TITLE
UI/UX improvement: surfacing active proposals

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1244]
Currently proposals are shown in chronological order, and there is also the option to sort proposals by status (ex. "active" "cancelled" "approved" etc).

When several proposals are made, older proposals do not receive enough attention. For example if there are 5 active proposals (meaning a proposal requiring votes) and proposals 1-4 have been approved, proposal 5 will be at the bottom of the list. If more proposal are made, then proposal 5 would end up being on the second page of proposals and will not get attention unless someone goes out of their way to only show active proposals. This was an issue most recently with a proposal that never received enough votes and there are a few things that could be done to improve on it.

Potential improvements:

* In default view of proposals, active proposals should always be at the top of the list
* There should ideally be a page break between active and executed/other proposals
* For the council on Pioneer, a small text goes below the button for the Council section, which says something like "announcing" (screenshot below) If there could be a similar feature for the proposal section that says `4 active proposals` it would help to better surface proposals that need attention.
![image](https://user-images.githubusercontent.com/50830161/92322148-96650f00-f040-11ea-8ffc-e316bb09f972.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703512434310) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
This is one of those: do we have time before we actually redesign Pioneer? This is starting in a matter of 1-2 weeks.

I think it depends on how quickly @DzhideX clears his pipeline.

**Comment by mochet** [comment]
closing because no longer relevant
