### ISSUE TITLE
WIP: Pioneer issues for Alexandria

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#1257]
As I think there will be more items here, I'm marking this as WIP for now.
New entries will be added as replies. I've tried to assign most things to @DzhideX, but @mnaamani may be needed if they are more difficult than they appear...

**Note**
When I say "remove", I mean just commenting them out, so it's easy to put back in once we know what they do, and/or need them :)

## General
When typing in a balance, decimal points are mishandled - e.g. 12.91 returns 9112
- [x] This applies to many different situations so I **hope** it's enough to fix once - @DzhideX
- Confirmed to happen when:
   - balance transfers
   - stake/vote on elections
   - staking for validators

## Chain State
**`balances.account(AccountId): AccountData`**
For any address, this returns:
```
{
  free: 0,
  reserved: 0,
  miscFrozen: 0,
  feeFrozen: 0
}
```
Is it something to do with types?
- [x] Investigate, and fix - @mnaamani 

## Accounts
General comment:
- The top right `?` has some info. Not sure we want to keep this.

**Rename back to `My Keys`**
- [x] This has been called `My Keys` on previous network. I suggest we do it again (without changing the URL) - @DzhideX

### My Accounts
**Remove polkadot-js extension "ad"**
- [ ] Although this apparently works, I think we should remove it for now. - @DzhideX

**Remove `Add via QR`**
- [ ] I haven't tried if it works even, but still, remove - @DzhideX

**Remove `Multisig` and `Proxied`**
- [ ] They are greyed out anyway. Remove for now - @DzhideX

**Passwords**
We have always allowed empty passwords, and even generate some ourselves.
- [x] Allow empty passwords - @DzhideX
- creating accounts
- importing jsons
- exporting jsons

## My Memo
**Move to `My keys / Accounts`**
- [x] Add as a new tab - @DzhideX

## Staking
**Question mark**
- [ ] The top right `?` has some info, and it's not really correct anymore. Remove - @DzhideX

**Rename back to `Validators`**
- [x] This has been called `Validators` on previous network. I suggest we do it again (without changing the URL) - @DzhideX

### Account Actions
**`+ Nominator` and `+ Validator` buttons**
What are these buttons meant to do?
- [ ] Investigate and consider removing - @DzhideX

**`Validate->Set validator preferences`**
- [ ] Value > 100 breaks page - @DzhideX

### Payouts
**All `Payout *` buttons greyed out** 
What are these buttons meant to do? 
- I assume it's one of these extrinsics, but not sure:
    - `.staking.payoutStakers(validator_stash, era)`
    - `.staking.unbond(value)`
    - `.staking.withdrawUnbonded()`
- Check against [polkadot](https://polkadot.js.org/apps/)
- [x] Investigate - @mnaamani

### Explore
No assigned tasks here, only general comments:
- Still very slow...
- Clicking on one of the `Featured videos` while playing another takes forever to redirect

---

Any comments are welcome!

**Comment by bwhm** [comment]
Checked off the items that has been made as a separate and assigned issue.

**Comment by mnaamani** [comment]
The reason the Payout buttons are greyed out is because they are disabled as a result of:

`const isDisabled = isInElection || !isFunction(api.tx.utility?.batch);`

The payout are expecting the `Utility` runtime module which has a `batch` method for submitting multiple dispatch call.
So the solution is to add it to the runtime. Will prepare a PR.

And yes the runtime call is PayoutStakers

Payouts All:
```
All the listed validators and all their nominators will receive their rewards.
The UI puts a limit of 40 payouts at a time, where each payout is a single validator for a single era.
```
MAX_BATCH_SIZE == 40 - it can be changed in pioneer but shouldn't be increased too much.

**Comment by mnaamani** [comment]
verified  that it works when added the utility module

<img width="1488" alt="Screen Shot 2020-09-13 at 10 21 33 AM" src="https://user-images.githubusercontent.com/1621012/93012689-54dde200-f5b3-11ea-8acf-8151edcfb4d8.png">

**Comment by mnaamani** [comment]
Regarding: 
```
api.query.balances.account(AccountId): AccountData
For any address, this returns:

{
  free: 0,
  reserved: 0,
  miscFrozen: 0,
  feeFrozen: 0
}

```

The reason is that it is not actually the `Balances` module that is storing the Account Data in our runtime configuration, but the system module.

https://github.com/Joystream/joystream/blob/afd7f8da4c7145e17d96af683d69a2efbf0c9b9c/runtime/src/lib.rs#L214

So the correct way to get account and balance info is with the `api.query.system.account(AccountId)` api

Alternatively `api.derive.balances.*` helper api can be used so you don't need to figure out at runtime where the balances are in-fact stored. Infact that is the main api used in pioneer and our cli for all account and balances related queries.

**Comment by mnaamani** [comment]
`Remove Multisig and Proxied` - FYI those are greyed out also because they depend on the `Multisig` and `Proxy` runtime modules which we haven't added to our runtime.

**Comment by bwhm** [comment]
> Regarding:
> 
> ```
> api.query.balances.account(AccountId): AccountData
> For any address, this returns:
> 
> {
>   free: 0,
>   reserved: 0,
>   miscFrozen: 0,
>   feeFrozen: 0
> }
> ```
> 
> The reason is that it is not actually the `Balances` module that is storing the Account Data in our runtime configuration, but the system module.
> 
> https://github.com/Joystream/joystream/blob/afd7f8da4c7145e17d96af683d69a2efbf0c9b9c/runtime/src/lib.rs#L214
> 
> So the correct way to get account and balance info is with the `api.query.system.account(AccountId)` api
> 
> Alternatively `api.derive.balances.*` helper api can be used so you don't need to figure out at runtime where the balances are in-fact stored. Infact that is the main api used in pioneer and our cli for all account and balances related queries.

I assigned this task to you in #1307 , but I'll reassign to leszek unless you already fixed it?
