### ISSUE TITLE
Orion research and preparation

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#1272]
To offer view counts for videos in Atlas we will need to run our own view count server that will be counting those. This issue aggregates things we need to do _before_ starting to work on that:
- Clearly define the desired functionality and UX
- Figure out the high-level architecture and the API of the service
- Update requirements and estimates for #1276, possibly split into separate tasks for deployment and testing

**Comment by kdembler** [comment]
### Functionality
We keep it bare-bones for now and possibly expand in the future. This means:
- Simple GraphQL API allowing to:
  - Add one view count to a specific video
  - Get a view count for a specific video
  - (Possibly) get a batch view counts for a list of videos
- No authentication of any kind for now

**Comment by kdembler** [comment]
### API
```gql
type VideoInfo {
  id: ID!
  views: Int!
}

type Query {
  # Get views count for a single video
  videoViews(videoID: ID): VideoInfo

  # Get views counts for a list of videos
  batchedVideoViews(videoIDList: [ID!]!): [VideoInfo]!
}

type Mutation {
  # Add a single view to target video's count
  addVideoView(videoID: ID!): VideoInfo!
}
```

**Comment by bedeho** [comment]
This looks good overall, however 

- I don't think most of the non-null constraints work, because the user may provide bad input ID.
- Should the semantics of `addVideoView` perhaps also be that, if there is no `VideoInfo` for the given `ID`, it just makes one and sets `views` to one?. This gives a very simpler interface where you dont need to separately chekc for, create and update videos if they dont exist.

**Comment by kdembler** [comment]
I've chosen the constraints purposely. From the point of Orion, I don't think (at least for now) it will be actually possible to know which IDs are valid and which are not. I don't think we want to need to seed it somehow with existing videos. Our goal for now was to keep it naive, so in my opinion it shouldn't care which ID is valid and which isn't. My idea is that if a video ID record doesn't exist in the DB, we assume it's 0. Once someone adds a view for an ID that doesn't exist yet, we create a record for it. A malicious actor could create invalid records in the DB this way, but they as well may just increase views for a specific video as many times as they want anyway, so I'd say this is to be solved in the next phase.

I don't fully understand your second point but hopefully my explanation address that.

**Comment by bedeho** [comment]
Just so I understand, you are saying that the queries do not change its database when `ID`does not exist, they just return a sort of token 0 views  type `VideoInfo`? I certainly thing its not great to have mutations behind queries, because its not really align with the semantics of what querying is vs. mutating. And then `addVideoView` just adds a new video if the ID is not already in the database?

Is this it?

**Comment by kdembler** [comment]
> you are saying that the queries do not change its database when `ID` does not exist, they just return a sort of token 0 views type `VideoInfo`

Yes, that was my idea, I believe queries should never modify the DB. We can also just return `null` for those and let the client handle that, I don't believe there's a big difference in those behaviours, although `null` potentially may be more future-proof

> I certainly thing its not great to have mutations behind queries

I don't understand what you mean by that

> And then addVideoView just adds a new video if the ID is not already in the database?

Yes

**Comment by bedeho** [comment]
Ok, then we are on the same page, sounds good. I would use native nullability, rather than constructing these empty info objects, but its up to you.

**Comment by kdembler** [comment]
Updated the schema to use nullability

**Comment by kdembler** [comment]
Also updated the return type of the mutation to return `VideoInfo`

**Comment by kdembler** [comment]
Marking this done. Work will carry on in the following tasks:
- #1276 
- #1486 
- #1488
