### ISSUE TITLE
Add Loading, Error and Empty states

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#1289]
Currently, several components are missing proper loading states, error states and empty states. 
For example:

- What should a search page look like if there are no result? What if there is an error? When its loading?

- What should the video page look like when its loading? And when there is an error?

I would also expect us to add a Loader we can use when fetching data.

This would likely require designer input

**Comment by bedeho** [comment]
> What should a search page look like if there are no result? What if there is an error? When its loading?

I think the loading state for search is already covered here
https://www.dropbox.com/s/v1sxsjn67e24vls/Screen%20Recording%202020-06-09%20at%2015.52.04.mov?dl=0

and in general I think we should just stick to the single loading concept that is in that video, and which we already have, of shaded containers. It is simple enough that we could make any genuinely missing loaders ourselves. 

- What do you think?
- What do you mean by error here, just so I understand? would it be that the query node just broke the connection or something? In this case what are we planning to do? try another query node?

> What should the video page look like when its loading? And when there is an error?

I would answer the same here:
- can't we just use the same loading approach?
- what do you mean by error? and what do we want the application to do?

> I would also expect us to add a Loader we can use when fetching data.

How is this distinct from the loading preview we already have?
