### ISSUE TITLE
Polls have no limit on number of alternatives

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1314]
A hardcoded, module configurable parameter, low value should be introduced.

**Comment by iorveth** [comment]
cc @bedeho  The limit for number of alternatives is currently ensured by `PollItemsConstraint` runtime storage value.
Did you mean, we should make it configurable on Trait level and only have lower bound?

**Comment by iorveth** [comment]
Close by https://github.com/Joystream/joystream/pull/1755
