### ISSUE TITLE
Misleading mutation-safe marker in forum extrinsics

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1346]
In quite a few extrinsics, we have this type of a situation

```Rust
//
// == MUTATION SAFE ==
//

/* eeeeeek! what about this space, seems safe to mutate, but is not! */

Self::some_call_with_sideffects_when_OK(...)?;
```

The line with the comment appears like a safe place to mutate, but it is not. The problem is that we have a call which both checks and mutates. This should be avoided when possible, and it almost always is.

Some examples are 
- `create_thread`
- `add_post`

possibly there are more.

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/1756
