### ISSUE TITLE
Content directory schema: define `High Level Derivative Entities`

### ISSUE THREAD

**Issue by metmirr** [Joystream/joystream#1349]
High-level derivate entities:

- `Channel`
- `Category`
- `VideoMedia`
- `Video`
- `JoystreamVideoMediaLocation`
- `HTTPVideoMediaLocation`
- `CreativeCommonsLicense`
- `UserDefinedLicense`

these entity names are taken from https://github.com/Joystream/joystream/issues/824#issuecomment-653150085. Since these entities are defined in the said issue estimated time is mostly for understanding the concept and improving the existing entities.

**Comment by bedeho** [comment]
You probably want to filter this list through the API sketch in the release plan, because there is a lot here we are not shipping in Babylon. The API sketch is the most authoritative source of the required queries.

**Comment by metmirr** [comment]
The entity list is updated according to @bedeho comment.

**Comment by metmirr** [comment]
Done https://github.com/Joystream/joystream/commit/85c719a96cbaeade89ea312e705fb711fcafb53f
