### ISSUE TITLE
Pioneer: Allow exploring old (previous) chain proposals after Alexandria release

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#1354]
The idea is to make all the current testnet proposals (https://testnet.joystream.org/#/proposals) data easily accessible for Pioneer users after the Alexandria release (which requires starting a new chain). Since the old (previous chain) proposals will not be part of this new chain state (migrating them would be quite diffucult), the idea is to fetch all the data expected by the related UI components (`ProposalDetails` etc.) and put it in a JSON file inside Pioneer's codebase. We can then use this data to display the old proposals in a similar fashion as the current ones, but on a separate route (ie. https://testnet.joystream.org/#/proposals/old)

More specifically this can be achieved by:

- Using a transport method (ie. `transport.proposals.proposalsBatch('All', 1, 9999)`) to fetch and parse all proposals data the same way this is currently done by Pioneer
- For each of those proposals using `transport.proposals.votes` to fetch all the votes and `transport.proposals.discussion` to fetch the discussion posts
- Combining those results into an array of objects like: `{ proposal, discussion, votes }`
- Saving it as a json file inside the Pioneer's codebase
- Adjusting the proposals transport so that it can either fetch the data from the chain or use the json file depending on the type of proposals we want to display (old/current)
- Creating a separate tab/route where we only display the old proposals
- Implementing necessary adjustments to components like `ProposalDetails` etc. (ie. disabling block number links for old proposals)

**Comment by bwhm** [comment]
@mnaamani !

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/1381
