### ISSUE TITLE
Deletion vs. Moderation semantics are incoherent.

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1380]
# Preamble

This all refers to the runtime storage model, there is obviously not deletion or moderation from history.

# Problem

Deleting and Moderating a thread is literally identical: it can only be done by a suitable mod or the lead, and involves deleting the thread an all post.

There is no deletion of posts, however there is moderation, which again is only allowed to be done by a suitable mod or the lead AND **ironically thread must be mutable (not-archived an not in archived category or path)**. It involves deleting the post, even if it is the first post with a poll.

This is all very inconsistent.

# Solution proposal

- Threads: 
  - Author can delete as long as there are no replies & not in archived thread/category, this results in removal from storage
  - Mod/Lead can delete at any time, but must provide a rationale, this results in removal from storage.

- Posts:
  - Author can delete any post, as long as its not the first one & not in archived thread/category, this results in removal from storage.
  - Mod/Lead can delete any post, as long as its not the first one, but must provide a rationale, this results in removal from storage.

Moderation per say is not a direct action anymore.

# Query node Policy

I think the most reasonably policy for the query node is just to keep all data at all times, and allow applications to apply local policy about what to show in various cases.

**Comment by mochet** [comment]
If I'm understanding correctly, I can't see any problem with it.

**Comment by iorveth** [comment]
`Author can delete as long as there are no replies & not in archived thread/category, this results in removal from storage`
In current `olympia` implementation author can delete thread at any time as long as it mutable. 
I don`t see any checks to ensure there is no replies in thread. 
Should it be fixed? Did we change a condition? @bedeho

**Comment by bedeho** [comment]
I think this is too old, this is was from before we started with the state bloat bonds, so I think it should just be disregarded.

**Comment by iorveth** [comment]
OK, I think another features have been implemented already. Can we close that issue?
