### ISSUE TITLE
Babylon: Create JSON input files for creating classes/schemas in the new content directory

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#1402]
Create JSON `input` files for generating new content directory classes and schemas based on Atlas API expectations: https://github.com/Joystream/joystream/issues/824
Current (old) inputs reside in: https://github.com/Joystream/versioned-store-js/tree/master/src/inputs

This issue involves creating such JSON schemas for classes and schemas of objects like:
- `Language`
- `Channel`
- `Category`
- `MediaLocation`
- `VideoMediaEncoding`
- `License`
- `VideoMedia`
- `Video`
- etc.

**Comment by bedeho** [comment]
Just remember that you need to take the current mocked API that the Atlas team is assuming will hold as the authoritative guide on the data model. The old schemas will have lots of junk that is not needed (e.g. related to music), and it will be missing other important stuff.

**Comment by Lezek123** [comment]
Closed with https://github.com/Joystream/joystream/pull/1463
