### ISSUE TITLE
Adapt Hydra indexer for Alexandria/Babylon

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/joystream#1409]
This is probably a multi-faceted task which requires attention from @mnaamani @Lezek123 @bedeho @dzhelezov 

Based on a conversation with @Lezek123 it seems that the indexer should have a non-trivial amount of logic to be incorporated due to future runtime upgrades and the Alexandria spin-off release.

My understanding is that Alexandria will start from scratch, with the genesis state imported from the previous testnets. Then Alexandria will be upgraded to Babylon in due time. Based on that the following core components seem to be missing from the Hydra indexer:

- Seeding of the state
- Runtime upgrades with imported type definitions (assuming the indexer can ingest jsonified type definitions)

For both tasks we need to figure out:
- data formats
- distribute the effort of preparing the input files 
- integration testing (including sandboxed Alexandria -> Babylon runtime upgrade)

**Comment by bedeho** [comment]
Babylon involves a new content directory, no state from the old content directory will be migrated to the new one as part of that upgrade. The [release plan](https://github.com/Joystream/joystream/issues/1249) states

> There is no need for any migration. The old versioned store and permissions will be discarded, and likewise all the state in the working group, including channels.

Hence there is no need in Hydra, for this release, to support seeding state, however it will be required in the future. I did not understand this point

> Runtime upgrades with imported type definitions

Let us review this on the next Hydra team meeting.
