### ISSUE TITLE
Reuse staked coins for voting

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#143]
**WIP: This is a hard design problem, needs more thinking**

In this context, voting is not just the direct or delegated voting of members on council candidates, but also the self-voting that council members do as part of the election process.

Currently, voting requires staking, and the stake cannot be used in other roles. Likewise, already staked coins cannot be used in staking. This means that actors have to trade off the goal of voting vs. participating in other activities, this will encourage very low voting rates, even with the delegation, and in particular as long as voters do not receive any reward.

It makes more sense to allow voting reuse staked tokens, and also for staked tokens to be used in voting. I believe this is how it works for Polkadot validators for example.

How do this will be involved.
- What happens if coins are to be slashed in some other context during the voting process, or during the staking process after voting.
- What if one use completed unbonding, while another is still staked?

It may be a good idea to reference check the design choices of other staking systems with multiple uses of stake, such as 
- Polkadot
- Cosmos
- Tezos
- Decred
- etc.

It may also be a good idea to revisit locks and reservations in the Substrate SRML modules, as they have cleared thought of this, as evident in their choice to stack locks.

We may want to implement this as a general idea, perhaps it turns out that not only voting, but other activities, should allow stake reuse, or reuse for specific purposes, and no others.

**Comment by traumschule** [comment]
case described in Joystream/pioneer/pull/3894
