### ISSUE TITLE
Pioneer v1: Show "total" stake pr validator "Staking overview"

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#1454]
For some reason, this tab only shows "own stake" and "other stake".
I checked on Polkadots [UI](https://polkadot.js.org/apps/#/staking), and it's the same there. Seems like adding a new column, should be easy enough, and make it a lot simpler for both existing and aspiring Validators and Nominators to make decisions...

<img width="1492" alt="screenshot" src="https://user-images.githubusercontent.com/35237943/93989935-cb849780-fd8a-11ea-9693-b1b24218bb33.png">

One could even argue the overview below would be appropriate to inject as well:
<img width="1492" alt="screenshot-2" src="https://user-images.githubusercontent.com/35237943/93991421-92e5bd80-fd8c-11ea-87ef-f0070fe9f328.png">

...although I suspect it might cause some issues with responsiveness..?

---

I don't think this should be high on any list of priorities, but just something to keep in mind.

**Comment by DzhideX** [comment]
Are we 100% set on the total stake tab being all the way to the left? It is definitely possible but when we open the nominators on other stake it doesn't look as nice as it pushes them all vertically right underneath instead of also pushing some horizontally. 

Maybe between own stake and commission would be a better place?

**Comment by bwhm** [comment]
> Are we 100% set on the total stake tab being all the way to the left? 

Not at all, but it was easier to inject it there using only screenshots :D

> It is definitely possible but when we open the nominators on other stake it doesn't look as nice as it pushes them all vertically right underneath instead of also pushing some horizontally.

Good point.

> Maybe between own stake and commission would be a better place?

That was actually what I thought would be best as well, so go for it :D
