### ISSUE TITLE
WIP: Integration testing of runtime & full node

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#155]
Our present unit tests only test individual modules in isolation, this is not sufficient to ensure that the runtime is funtionaing properly, in particular because of the interdependency between modules, which is only going to deepen. 

Adding integration tests at both the full node and runtime level is required. Full node tests could for example be done using Polkadotjs. I am not sure how easy it would be to do runtime integration tests in Rust.

**Comment by siman** [comment]
> Full node tests could for example be done using Polkadotjs

This sounds reasonable. Although it's not an easy task.

**Comment by bedeho** [comment]
Described here https://github.com/Joystream/joystream/issues/170
