### ISSUE TITLE
Spending proposal constrained by a token mint

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#158]
It is not sufficient to constrain a funding proposal upper bound _per proposal_, because the council can just keep submitting new proposals to itself, making the bound irrelevant. Instead, something like the token mint abstraction is needed. Hence there would be a dedicated mint for this purpose.

For Constantinople, it should be able to update the configuration of this mint using SUDO.

**Comment by shamil-gadelshin** [comment]
Released.
