### ISSUE TITLE
Idea: token managed video placement

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1585]
Currently, all videos on the platform are considered equal unless they are featured. Featured videos are manual decisions that a curator has to do. Presumably we will also get metrics like view counts, subscriber counts etc.

One interesting way of using tokens are TCRs but these are quite complex, there may be a simpler way to do this and provide a way for the community to highlight videos, content (and maybe also forum posts) that they find to be interesting.

A burner address is made and users send tokens to it (somehow they would need to make a reference to which video the tokens are for, I'm not sure if you can send a memo alongside a transaction?). Then you can search the burner address records and identify which videos have had the most or least amount of tokens burned for them.

To be clear, the tokens submitted can be from any user, but do not go towards anyone, they are burned, so their function is to promote content. Although the video creator is not receiving any tokens from this process, they would stand to benefit from having their video placement higher and which would hopefully foster an environment where users then tip/subscribe to that creator.

A brief example might be something like this:
| Video Name      | Tokens Burned (total) | Tokens Burned / 24h | Tokens Burned / 48h |
|-----------------|---------------|---------------------|---------------------|
| Bob's Video     | 231           | 125                 | 175                 |
| Alice's Video   | 689           | 423                 | 689                 |
| Michael's Video | 4043          | 16                  | 18                |

Because of how the data can be used, it would imaginably be very easy to have a user curated section which shows users of the platform some popular videos using this data (besides relying on view counts and other metrics).

This data can also be used to show users:
- The videos with the most tokens burned (all time)
- How many tokens are burned across Bob's channel
- How many tokens the user Alice has burned for creators videos (which can be included on the user's profile, to show they are an altruistic member of the platform).
- Videos which are getting a lot of tokens burned in the past 10 minutes
- What are the most burned videos on the `cooking` tag?

Obviously users can burn tokens for their own videos, but this is actually a feature as Instagram has started letting normal users promote their content via the platform for money, so users may actually want to burn tokens against their own content to promote it.

**Comment by bedeho** [comment]
This is an interesting idea.

Parts of this, in particular around burning for a specific tag, is very similar to advertising functionality we have had in mind. One of the challenges of all of these models is that the platform really needs to own the user experience, end-to-end, for it to work, because any third part UI has no incentive to honor any such burning mechanism, as it does not capture any of that value. Even when the UI is owned, adblockers and other stuff on the user device still get in the way. I think something like this really would need a web3 native browser or appstore to work properly, as the platform would fully control what application the user resolved.

What do you think about these problems?

**Comment by mochet** [comment]
> This is an interesting idea.
> 
> Parts of this, in particular around burning for a specific tag, is very similar to advertising functionality we have had in mind. One of the challenges of all of these models is that the platform really needs to own the user experience, end-to-end, for it to work, because any third part UI has no incentive to honor any such burning mechanism, as it does not capture any of that value. Even when the UI is owned, adblockers and other stuff on the user device still get in the way. I think something like this really would need a web3 native browser or appstore to work properly, as the platform would fully control what application the user resolved.
> 
> What do you think about these problems?

In this instance, its not really traditional advertising, like a pre-roll ad on YouTube, its more about promoting user content so an adblock probably wouldn't factor too much since the system can't determine what is or isn't an ad. Obviously advertisers could use it to heavily promote their own videos, but I think that would only make sense intermittently. Ideally a passionate userbase would be able to match token burns from advertisers.

Since it is fairly simple in itself, it would be up to the UI on how to use the data, I could see situations where users don't even bother with this kind of data and instead rely on just watching channels they are linked to or already subscribed to. In that way a 3rd party UI could totally ignore the data but having it available as some sort of layer is really just a bonus.

Since it is a token burn, the benefits of participating would be quite unpredictable which would hopefully make it interesting for advertisers, users and content creators to participate. If the system were affected by a 3rd party UI or adblock issues later on, it could just be that the value put behind it lowers, but since there is no fixed cost (as in you're not paying $10 to get your videos listed) to participate it could make for quite an interesting metric on the platform.

In my eyes, it does solve part of the problems associated with human curation in that an English speaking curator is unlikely to know anything about what French users like to see. As each community can participate equally in a system like this, I think use would never be equal by all participants (as an example, if the coding community created their own UI and chose to disregard the token burn data it wouldn't be the end of the world since presumably other communities might choose to use it)

**Comment by bedeho** [comment]
> In my eyes, it does solve part of the problems associated with human curation in that an English speaking curator is unlikely to know anything about what French users like to see. As each community can participate equally in a system like this, I think use would never be equal by all participants (as an example, if the coding community created their own UI and chose to disregard the token burn data it wouldn't be the end of the world since presumably other communities might choose to use it)

This would require that the burning also has some language dimension? so you burn for `english`, or do you mean that by burning on `cooking`, that covers implicitly solves the language issue?

**Comment by mochet** [comment]
> This would require that the burning also has some language dimension? so you burn for `english`, or do you mean that by burning on `cooking`, that covers implicitly solves the language issue?

You would only burn tokens for a video with no other information. However the UI could allow for a user to customize their homescreen to display `french` videos and maybe even `french` + `cooking` as tags on their browser. The language and tag settings would be completely up to the curator team to manage in this case but they would still be useful tools.

As an example:
| Video Name               | Tags                 | Language | Tokens Burned / 24h |
|--------------------------|----------------------|----------|---------------------|
| Bob's Video              | `photography` `art`  | English  | 125                 |
| Alice's Video            | `cooking` `pancakes` | French   | 423                 |
| Michael's Video          | `travel` `Morocco`   | English  | 16                  |
| Frederic's Video         | `talkshow` `drama`   | Russian  | 52                  |
| The Cooking Show's Video | `cooking` `pasta`    | French   | 27                  |
| Francesco's Video        | `chitchat`           | English  | 43                  |
| Ahmed's Video            | `cooking`            | Arabic   | 416                 |

All the videos are 'equal' in that any user can burn tokens against any video on the platform, but by using the `language` as French, a user could just see videos in `French` and utilize the token burned information.

Also if you had some kind of "explore" page on the UI, you could show the most burned tags for videos (meaning just adding up how many tokens were burned across all videos using that tag). If `gaming` has millions of tokens burned against it, it would show prominently, and a user could choose to add that to their home page experience.

In my mind, it would be better for users to burn tokens against tags for a specific video, but I think that would make the system more complex. Having it be this basic would hopefully mean a system where a large number of users are willing to participate.
