### ISSUE TITLE
Finalise Atlas header section

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1627]
Design is found here

https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=2374%3A45800

Here is the description of how it should work

- The top area should first load an image, and then when a background video is loaded, and if the user still lingers in the top area, it should transition into a video playing in the background.
- There is explicit visual handling of loading of the initial top image.
- The top image/video will fill the full width of the browser, hence, since this varies, the height of the image/video must vary proportionally. Since the height may grow quite small when the browser becomes narrower, we should shift the black gradient to  start much lower.
- When the video is playing, there must be a mute button for the audio.
- The content we will feature is this video https://www.youtube.com/watch?v=kjtKrJarrTw. Playback will start at 00:44s
- The cover image is attached (ask internally).
- The brand (SCHISM logo) is attached (ask internally).
- Content brand is displayed above title.

**Comment by kdembler** [comment]
As per https://github.com/Joystream/joystream/issues/1120#issuecomment-720588861, to be further decomposed into doing a static cover video preview first and video playback next
