### ISSUE TITLE
Idea: Exchange rate proposal

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1631]
This could be done via a preformatted text proposal or a new proposal type. There are positives and negatives to both.

This would be a proposal type which includes a number, a user creates the proposal and explains their methodology for the proposed exchange rate.

I think it would solve several issues:

- Avoid council conflict between proposals with differing exchange rate sources. If the platform has its own agreed exchange rate then the conflict shouldn't result in a proposal being rejected because it used some unpopular exchange rate source.
- Add context to current and historical proposals (ex. storage lead reward was changed to 3500 tokens at blockheight n with agreed exchange rate being 0.000423).
- Add context to historical tokenomics data without relying on 3rd party exchange rate sources
- Prevent proposal creators using their own exchange rate source which is maybe more favorable for them
- Avoid potential conflict about what exchange data is used when showing current tokenomics data
- The exchange rate data could obviously just use an API from some external website, but I have seen plenty of conflict on projects about the source of exchange rate data and some exchanges are not considered as being legitimate. By having the council have a mechanism for agreeing on the exchange rate, it would hopefully avoid a lot of those issues.

For example, a user might propose that the exchange rate is 0.004324 based upon data from 3 different exchanges and averaged over a period of 48 hours. The council could set their own expectations of what the exchange rate should be based on (ex. at least 2 exchanges, with `n` volume and averaged over a period of no less than 36 hours) and for how long a given exchange rate is considered valid.

The problem this solves is building consensus over what the exchange rate is at a specific point in time. Since the exchange rate will influence budget and mint decisions, having an agreed value would influence tokenomics data as well as many other budget decisions on the platform.

This is very much a mainnet issue rather than something that would solve any issue currently, but I could foresee a situation in which it would be useful or might be required. This would also hopefully avoid situations where a `spending proposal` is submitted using a certain exchange rate, but a `lead reward` submitted nearly instantly after uses an exchange rate which is different.

It also mainly applies to roles which are centered around the management of hardware, where we can know there is a fixed cost associated with the hardware.

It may also be disadvantageous to have such a rigid definition of the token's value or there are other ways to deal with this issue.

**Comment by bedeho** [comment]
I think know what you are trying to tackle, but could you prepend this with a clear problem statement? what isssue are you trying to solve?

**Comment by mochet** [comment]
> I think know what you are trying to tackle, but could you prepend this with a clear problem statement? what isssue are you trying to solve?

(I'll add to the original issue as well) I think it would solve several issues:
* Avoid council conflict between proposals with differing exchange rate sources. If the platform has its own agreed exchange rate then the conflict shouldn't result in a proposal being rejected because it used some unpopular exchange rate source.
* Add context to current and historical proposals (ex. `storage lead` reward was changed to 3500 tokens at blockheight `n` with `agreed` exchange rate being 0.000423).
* Add context to historical tokenomics data without relying on 3rd party exchange rate sources
* Prevent proposal creators using their own exchange rate source which is maybe more favorable for them
* Avoid potential conflict about what exchange data is used when showing current tokenomics data

The exchange rate data could obviously just use an API from some external website, but I have seen plenty of conflict on projects about the source of exchange rate data and some exchanges are not considered as being legitimate. By having the council have a mechanism for agreeing on the exchange rate, it would hopefully avoid a lot of those issues.

**Comment by bedeho** [comment]
- What determines when new proposal is submitted? wont this need to happen very frequently?
- Are other token quantities denonimanted in this rate? so the reward, amount in spending proposal etc. Would that be in terms of the exchange rate to some fiat currency?

**Comment by mochet** [comment]
> * What determines when new proposal is submitted? wont this need to happen very frequently?
> * Are other token quantities denonimanted in this rate? so the reward, amount in spending proposal etc. Would that be in terms of the exchange rate to some fiat currency?

* The council would have to have an agreement about the validity of the exchange rate. Frequency is obviously an issue and not sure how that would best be tackled. Since it would be a very influential proposal type that affects how many tokens are spent it should probably be an expensive proposal. A lot of that depends on how quickly moving the council would be in a mainnet scenario, which is difficult to predict. The way I could see it working is that the council would only agree to update this value every 24 or 48 hours, which would help to add stability with submitted proposals, maybe even less frequently. It may also be that the council uses an averaged exchange rate from the last few approved exchange proposals, increasing the stability of what they agree on and hopefully avoiding scenarios where the exchange rate jumps sporadically and makes submitted proposals problematic soon after they are submitted. I would also think the council requires that whatever exchange rate submitted abides by certain terms (ex. average over a 3 day period) meaning there is no use of submitting dozens of proposals for very minor exchange rate changes.
* Yes, for example when creating a spending proposal, if the user inputs 100k tokens, it could use the current exchange rate to display on the submitted proposal on what the fiat amount is (or whichever currency the council decides to use) or the user could elect to input a fiat amount which is then uses the agreed exchange rate to populate the token quantity field.

**Comment by mochet** [comment]
To demonstrate visually how much of an effect the exchange rate has, I've updated the council leaderboard and it uses an "approx exchange rate" field but I think it shows well how much of a significant effect the exchange rate can have on many underlying aspects of tokenomics beyond just the rates at which spending proposals are minted at: https://github.com/Joystream/community-repo/blob/efa83f3172c34bab0d257bcbaf1df38f5e280e11/council-reports/alexandria-testnet/Alexandria-Council-Leaderboard.md

**Comment by bedeho** [comment]
This is covered by https://github.com/Joystream/joystream/issues/3626
