### ISSUE TITLE
Add max width to videos on the Search View

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#1651]
Video Previews in the video section of the search view can get quite big if there is only a few of them. Fix this by given them a reasonable max-width

**Comment by kdembler** [comment]
I'm not sure if max-width is the way to go, as we almost for sure want them to grow as big as they need (look #1707).

To fix this, we probably will need something like fixed items per viewport width (a lot of work possibly) or shadow placeholders that would fill the row. The 2nd option may make the most sense for now I guess
