### ISSUE TITLE
How to run on the localhost

### ISSUE THREAD

**Issue by cae1um** [Joystream/joystream#1671]
I've finished setting local dev env on my end but I can't find how to run the server.
Could you let me know how I can do this?

**Comment by kdembler** [comment]
Hey there!

Assuming we're talking about Atlas (Joystream video playback UI), here's what you will need to do:
1. Clone the repo and checkout the `init_atlas` branch - currently Atlas isn't merged into `master` yet and `init_atlas` is the most recent "stable" version
2. All we will be doing here should happen in the `atlas` directory so make sure to `cd atlas`
3. You will need to install all the external dependencies of the frontend app - so run `yarn` or `npm install`, whichever suits you best (we use `yarn` internally)
4. Once the deps are installed, you can use the `dev` script from `package.json` - so run `yarn run dev` or `npm run dev`. The app should build in the dev mode and be available at `http://localhost:3000`

Let me know if you have any questions or run into problems

**Comment by cae1um** [comment]
Thanks, @kdembler
