### ISSUE TITLE
Add weights and benchmarking for the proposals/discussion system

### ISSUE THREAD

**Issue by conectado** [Joystream/joystream#1690]
The goal of this issue is to add benchmarking and weight in the `proposals/discussion` system

The development will be done in the context of [this branch](https://github.com/Joystream/joystream/tree/proposals_update)

### Requirements

* Benchmark implementation for each extrinsic
* Verify for each benchmark
* Run benchmarks and annotate weight for each extrinsic

**Comment by shamil-gadelshin** [comment]
Done
