### ISSUE TITLE
CLI / content-directory-schemas: Featured videos

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#1697]
Add support for featured videos in the content directory schemas and related functionality to CLI.

- add `FeaturedVideo` class and schema inputs. Each entity would contain a reference to `Video`
- add `joystream-cli media:setFeaturedVideos [IDS]` and `joystream-cli media:featuredVideos` (list) commands

**Comment by iorveth** [comment]
> Add support for featured videos in the content directory schemas and related functionality to CLI.
> 
> * add `FeaturedVideo` class and schema inputs. Each entity would contain a reference to `Video`
> * add `joystream-cli media:setFeaturedVideos [IDS]` and `joystream-cli media:featuredVideos` (list) commands

Hey, can we close this issue? cc @Lezek123
