### ISSUE TITLE
Founding member creation extrinsic

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#1737]
# Background

As part of bootstrapping the state of `Carthage` and mainnet, the set of initial members with FM status must be identified on-chain, the purpose of this issue to describe the extrinsic for the creation of such founding members.

# Proposal

- Create a new extrinsic `make_founding_member`.
- It is gated by `Root` origin.
- It otherwise takes the same paramers as `buy_membership`.
- It emits `MadeFoundingMember` on success, which has otherwise same signature as `MembershipBought`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202202227320392) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Done (https://github.com/Joystream/joystream/pull/4014)
