### ISSUE TITLE
Fix use of array into iter

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#179]
https://github.com/Joystream/substrate-runtime-joystream/blob/385a376ed64e565ad410be76a7e424f0de340d66/src/lib.rs#L331

```
this method call currently resolves to `<&[T; N] as IntoIterator>::into_iter` (due to autoref coercions), but that might change in the future when `IntoIterator` impls for arrays are added.

note: `#[warn(array_into_iter)]` on by default
warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
note: for more information, see issue #66145 <https://github.com/rust-lang/rust/issues/66145>rustc(array_into_iter)
```

**Comment by iorveth** [comment]
Most probably this warning originates from srml > staking > reward-curve module. 
Figured out the actual place, where it was introduced. 
![Screenshot from 2020-04-21 19-17-43](https://user-images.githubusercontent.com/18070359/79888365-2f361d80-8405-11ea-8acf-6b9feb515638.png)
I see 2 possible solutions here:

**Comment by iorveth** [comment]
https://github.com/rust-lang/rust/issues/66145
Most probably this warning originates from `srml > staking > reward-curve module`. 
Figured out the actual place, where it was introduced. 
![Screenshot from 2020-04-21 19-17-43](https://user-images.githubusercontent.com/18070359/79888365-2f361d80-8405-11ea-8acf-6b9feb515638.png)
I see 2 possible solutions here:
- Wait for the moment, when we`ll update to the most recent substrate version, where this error is already fixed.
- Fork `reward-curve module`, replacing `into_iter` with `iter`

**Comment by bedeho** [comment]
Def. lets wait, nice work!

**Comment by mnaamani** [comment]
This is most likely resolved in https://github.com/Joystream/joystream/pull/1075 when updating substrate
