### ISSUE TITLE
Idea: tag + area for content funded by platform

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1824]
I'm not sure if this might already be planned but couldn't locate any reference to it.

Content will somehow be funded by the Joystream DAO. This content should be accessible in one place within Atlas so that an end-user can quickly see all of the content the platform has funded, this will help to communicate trust and productivity of the platform.

This would apply to content that is funded and not to content that is just uploaded and later on receives rewards. For example if a user creates a `spending proposal` to fund or partly fund creation of a short video, this video, once uploaded should be added by curators to a specific page that lists these type of projects that have received funding.

Ideally, this page should have some text + links to explain to unfamiliar users the magic of the Proposal + Council system and how they can participate if they want to.

Vimeo has a very good example of this which is `staff picks` rather than content that has been funded, but if `Joystream funded content` had its own area it could be a valuable thing to have: https://vimeo.com/channels/staffpicks

**Comment by bedeho** [comment]
Do you think a dedicated official channel would be sufficient? Atlas can treat that channel differently, if that would enhance things, but there is of course no guarantee another UI would do the same.

**Comment by mochet** [comment]
> Do you think a dedicated official channel would be sufficient? Atlas can treat that channel differently, if that would enhance things, but there is of course no guarantee another UI would do the same.


Yes, in the example from Vimeo however it seems to function more like a playlist. The channel itself doesn't own or upload the videos, so the original video creator gets all traffic from being posted there.
