### ISSUE TITLE
New proposals

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1864]
Codex should have the proposals reflected here, and not any other

https://joystream.gitbook.io/joystream-handbook/governance/proposals#proposals

**Comment by shamil-gadelshin** [comment]
Currently, I see these new proposals:
- Set Membership Price
- Set Referral Cut
- Set Initial Invitation Count
- Set Initial Invitation Balance
- Set Membership Lead Invitation Quota
- Cancel Working Group Leader Opening.

**Comment by bedeho** [comment]
I added two new proposals

- https://joystream.gitbook.io/joystream-handbook/governance/proposals#set-council-budget-increment
- https://joystream.gitbook.io/joystream-handbook/governance/proposals#set-councilor-reward
