### ISSUE TITLE
Include a weight to fee function in pallet_transaction_payment

### ISSUE THREAD

**Issue by conectado** [Joystream/joystream#1867]
For weights to impact in the fees we need to modify the runtime implementation of `pallet_transaction_payment` we are using.

Currently `type WeightToFee = integration::transactions::NoWeights;` which means that there's no cost to weights.
Furthermore, we also need to decide if to include `FeeMultiplierUpdate` which also impacts fee when including weights.

**Comment by conectado** [comment]
The `WeightToFee` defines a polynomial function to transform a weight into balance.
In most cases, it seems to make sense to use a linear function. Inside Substrate there is a function readily prepared called [`IdentityFee`](https://substrate.dev/rustdocs/v2.0.0/frame_support/weights/struct.IdentityFee.html). This functions defines 1 weight = 1 balance.

However, this is not the function that Polkadot uses.

Polkadot uses the [following](https://github.com/paritytech/polkadot/blob/19b88fffbc93b8c47233af4e5c27d1bb95e94e76/runtime/polkadot/src/constants.rs#L71-L85):

```rs
impl WeightToFeePolynomial for WeightToFee {
		type Balance = Balance;
		fn polynomial() -> WeightToFeeCoefficients<Self::Balance> {
			// in Polkadot, extrinsic base weight (smallest non-zero weight) is mapped to 1/10 CENT:
			let p = super::currency::CENTS;
			let q = 10 * Balance::from(ExtrinsicBaseWeight::get());
			smallvec![WeightToFeeCoefficient {
				degree: 1,
				negative: false,
				coeff_frac: Perbill::from_rational_approximation(p % q, q),
				coeff_integer: p / q,
			}]
		}
```

This defines a scale between the `ExtrinsicBaseWeight` (The minimum weight for an extrinsic no matter the computation time, length or storage time) and the minimum balance an extrinsic takes and `MaximumBlockWeight` which is the maximum weight for a block. 

In the case of Polkadot it uses [`ExtrinsicBaseWeight = 1/10th Cent`](https://github.com/paritytech/polkadot/blob/19b88fffbc93b8c47233af4e5c27d1bb95e94e76/runtime/polkadot/src/constants.rs#L104-L112) and [`MaximumBlockWeight = 16 Dollars`](https://github.com/paritytech/polkadot/blob/19b88fffbc93b8c47233af4e5c27d1bb95e94e76/runtime/polkadot/src/constants.rs#L94-L102).

To decide on a `WeightToFee` function basically we need to decide this scale, meaning the mapping from Minimum Weight to Maximum Weight converted to balance

**Comment by conectado** [comment]
The `FeeMultiplierUpdate` is a function that allows adapting the fee for a transaction over time based on demand.

The function should rise the price when demand rise to lower the number of transactions and vice-versa aiming to keep the same number of transactions over time.

[TargetedFeeAdjusment](https://substrate.dev/rustdocs/v2.0.0/pallet_transaction_payment/struct.TargetedFeeAdjustment.html) is the function that is provided by Substrate to deal with this [explained here](https://w3f-research.readthedocs.io/en/latest/polkadot/Token%20Economics.html#adjustment-of-fees-over-time).

There are "2 versions" of this function(which is basically just changing the parameters) either to work in a short time-frame, reacting quickly to "instant" market variation, or adjusting the parameters to react only to longer-term trends.

To adapt to longer-term trends prevents it from sudden spikes in the transaction fee, however, this also means longer inclusion times for a particular transaction, this is dealt with tips. In the document linked previously the trade-offs are explained in detail. Using slow adapting fees is the recommended way.

[Here you can find the Polkadot parameterization of this function](https://github.com/paritytech/polkadot/blob/19b88fffbc93b8c47233af4e5c27d1bb95e94e76/runtime/common/src/lib.rs#L88-L93) we can probably use a very similar version.

**Comment by conectado** [comment]
**Note**: We also need to define `TransactionByteFee` which is the price of 1 byte in a transaction, in polkadot they use [10 Millicent](https://github.com/paritytech/polkadot/blob/v0.8.26/runtime/polkadot/src/lib.rs#L249) and `OnTransactionPayment` which is who gets the transaction fee and in what proportion. 

The recommended way is [%80 to treasury %20 to block producer](https://w3f-research.readthedocs.io/en/latest/polkadot/Token%20Economics.html#setting-transaction-fees). It's very important that the fee is greater than the reward for the block author otherwise it'd incentivize block authors to include garbage empty transactions.

**Comment by conectado** [comment]
While thanks to `FeeMultiplierUpdate` the weight to fee conversion will change over time to be stable if the `WeightToFee` function starts way too far from the ideal value it could take too long(even many years) to reach the ideal value.

To prevent this situation we propose modeling a price/demand curve for the extrinsics, this would give us an idea of what the ideal fee for a given extrinsic would be, and using this we can create a `WeightToFee` that map the weight of the extrinsic to that value.

**Comment by shamil-gadelshin** [comment]
Done
