### ISSUE TITLE
Test benchmark build on PRs

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#1882]
We need to add a different build test for our project after adding benchmarks because they are built using the `runtime-benchmarks` feature.

We need to modify our github actions and add such command:
`cargo build --release --features runtime-benchmarks`

**Comment by shamil-gadelshin** [comment]
Also, it could be helpful to modify and test `./scripts/generate-weights.sh` - to be sure that benchmarking functions are not panicking!

**Comment by mnaamani** [comment]
Implemented in https://github.com/Joystream/joystream/pull/2017
Waiting on checks to see if it needs any tweaks or improvements.

**Comment by shamil-gadelshin** [comment]
Done
