### ISSUE TITLE
Setup compatible lock combinations for StakingHandler in the Runtime

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#1899]
Before releasing Olympia, make sure allowed lock combinations match the description (desired state) in the handbook. https://github.com/Joystream/handbook/blob/master/key-concepts/staking.md#reuse

At the time of writing, all combinations are allowed (see `ALLOWED_LOCK_COMBINATIONS` in https://github.com/Joystream/joystream/blob/e3b84232df9bb1d4e6385b0f237783350136a9b5/runtime/src/constants.rs). Also, present lock types don't correspond to the types described in handbook 1:1.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201745917257300) by [Unito](https://www.unito.io)

**Comment by jodator** [comment]
I did not find this issue earlier, so this might be a duplicate: #2824.
