### ISSUE TITLE
Implement is_council_member in pallet_council for Runtime

### ISSUE THREAD

**Issue by conectado** [Joystream/joystream#1933]
This implementation depends on membership being ready

**Comment by shamil-gadelshin** [comment]
Also, please address this request from the original PR:
> values for council settings are not finally set. Do we have any document with relevant settings? (how often election happens, etc.)

**Comment by ondratra** [comment]
Council settings task was moved to separate issue https://github.com/Joystream/joystream/issues/1929

**Comment by shamil-gadelshin** [comment]
Fixed in  #1981
