### ISSUE TITLE
Allow querying channel and category video count

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#1952]
In Atlas we'd like to display number of videos a given channel has. It'd be nice if we had a `videosCount` field or something similar. Right now, we would need to fetch all the videos from channel with just their IDs and then count them

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703470161872) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
already done
