### ISSUE TITLE
Idea: Rewards Working Group

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1967]
Currently, rewards can be given to users who create a `spending proposal`. This method is problematic in that it doesn't distinguish between large or small amounts and it also takes up the council's time. Based on current statistics (https://joystreamstats.live/proposals) it takes approximately 25 hours on average for any proposal to be voted on by the council.

There is also the mode of creating competitions, but these currently have several limitations:

* Use `spending proposals`
* Require "judgement" of work which is highly subjective
* Difficult to reward winners in competitions using objective metrics
* Labor intensive for both people running the competitions and the users submitting to competitions
* Prone to favoritism

A rewards working group could be created that has the role of distributing rewards to Joystream users. It may be that there is only a requirement to have a lead and no workers (this would be dependent on the workload). This would not be intended to manage rewards entirely, but rather should be considered as one of many potential approaches to rewards that can be used simultaneously--so there could be rewards for views on videos that form 50% of rewards paid out to creators, and the `rewards working group` could be responsible for 20% of reward spending

This working group would answer to the council, and the council could create `spending proposals` sporadically to fund specific subsets of users. These rewards would not be dispersed in a competition manner, but rather reward subsets of work uploaded on Joystream that are within some defined values. For example:

* The Cooking category has had some great videos uploaded recently. We will distribute 2 million tokens amongst all videos in this category uploaded in the past 2 weeks.
* We've had some great new users. We will distribute 2 million tokens to each new channel that has uploaded at least 3 videos in the past 30 days.
* There have been some great videos that are in French. We will distribute 2 million tokens to the past 30 videos that have more than 500 views and are in French.

Since all of these reward examples are for content that has been uploaded, it removes a lot of risk when having to deal with new users of the platform. These new users may be great, valuable contributors but proving their intent and reputation with spending proposals is an inherently labor intensive process.

Effectively, this working group would be funded by the council in singular proposals or mint spends and disperse the tokens to a wide range of uploaders on the platform.

The lead and workers in this group should ideally be savvy to community building techniques and have skills in identifying particular subsets of users and effective ways to reward these users. The amount of tokens paid out to individual users from these rewards would not be substantial and should be in ways that reward a significant number of users rather than a small number of users.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703470386917) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
To try to briefly summarize, you want a dedicated team to focus on paying out publishers, and they do this out of a normal budget they get from the council?

I was actually thinking that the content directory lead would do this, this means he/she is responsible for such payouts +. managing the curators, which seem like related tasks. Nothing prevents some of the workers in that group from being primarily focused on reviewing content for the purpose of rewards, while others are focused on pure curation.

**Comment by mochet** [comment]
> To try to briefly summarize, you want a dedicated team to focus on paying out publishers, and they do this out of a normal budget they get from the council?
> 
> I was actually thinking that the content directory lead would do this, this means he/she is responsible for such payouts +. managing the curators, which seem like related tasks. Nothing prevents some of the workers in that group from being primarily focused on reviewing content for the purpose of rewards, while others are focused on pure curation.

Correct. It might be interesting to have the content group manage such a task, and it would mean that they could perhaps have a distinct mint (if that would be viable) to draw from so that the budgets for workers and rewards aren't influenced/mixed in some negative way.

Whether it is council, curators or a new working group, I do think the biggest benefit to such a system regardless of how its implemented is that it doesn't solely reward based on views, and if the platform can advertise that `518k JOY were distributed in the past week to the following videos/categories` I think that is a much more genuine metric to share with users rather than just the distribution of tokens to videos based upon subscribers or views (which seems like it is much less likely to generate interest).

**Comment by bedeho** [comment]
1. I think having a separate budget could have some benefits, but it would introduce some significant complexity to introduced multiple budgets per working group, and I think we are hitting diminishing return at the same time, so I will say lets hope they can manage with properly spending out of one budget.
2. I certainly see the merits of that, but this is more of a policy choice, its not something we can encode. I expect that them to arrive at a balance informed by community goals, and taking more than past views into account certainly seems plausible.

**Comment by traumschule** [comment]
There might be better ways.
- Rewarding creators for views seems like a task that should be automated. Anybody can fill an account with tokens and use batch transactions to distribute them.
- Thinking in the direction of smart contracts a budget/bounty manager would store code to distribute tokens from an address on-chain and the council would approve a proposal to feed that `mint`.
- Alternatively spending proposals with more than one beneficiary could make a lot of sense.

**Comment by bedeho** [comment]
> Rewarding creators for views seems like a task that should be automated. Anybody can fill an account with tokens and use batch transactions to distribute them.

There are at least two serious problems with this

1. Once you start paying directly _for views_, you are going to see massive abuse and attacks on the system. The ability to counteract this will require on fully dedicated and experienced people and infrastructure to continuously monitor and apply subjective judgement, which will also be wrong at times. This is part of the reason the Gateway role has been planned https://github.com/Joystream/joystream/issues/2089
2. Since the viewer side of the platform is currently entirely underdeveloped, it would be a very hard way to distinguish quality with.

**Comment by bedeho** [comment]
I had totally forgot about this issue when I made the following suggestion in direct communications

> how to pay content creators for creating content, not as Jsgenesis bounties, but as a built in platform level activity. I believe doing this at scale will require something more sophisticated, but how about something very simple where every week the content lead creates a spending proposal that simultaneously pays out the top 20 or 50, or some decent number, for their content the past week? The council votes to pass it. This would require spending proposals that pay out multiple parties, something that currently is not possible in the Sumer runtime, but is easy to add.

To me it seems like compared to just obliging the content directory lead pay out the top X creators based on the lead's subjective evaluation of quality, from the working group budget, is simpler and has no clear disadvantage compared to both

a. a dedicated payout group
b. the council doing a repeating multiway spending payout

To induce the lead to actually do this we need to just make something like this part of the KPIs & fix the broken council member incentives, something we must do for lots of other reasons anyway.

**Comment by mochet** [comment]
> To induce the lead to actually do this we need to just make something like this part of the KPIs & fix the broken council member incentives, something we must do for lots of other reasons anyway.

Yes, agreed. There are multiple ways to do this obviously, but I would suggest we target the simplest to begin with and also begin developing ways of understanding what content is on the platform (https://github.com/Joystream/community-repo/issues/135).

There is also value in targeting this issue with any solution as it will help to make the budget more "realistic". Currently we have no specified on-chain budget for rewarding content (although content creators can apply for funding using spending proposals).

**Comment by bedeho** [comment]
Nothing is actionable in this issue, closing.
