### ISSUE TITLE
After the Babylon runtime update some blocks have invalid EventRecords

### ISSUE THREAD

**Issue by freakstatic** [Joystream/joystream#1978]
Trying to get the EventRecords of some specific blocks is failing.
For instance block number 1277029 or 1277424.
Code example:

```typescript
    const blockHash: Hash = await api.rpc.chain.getBlockHash(1277029);
    let eventRecord = await api.query.system.events.at(blockHash) as Vec<EventRecord>;
    console.log(eventRecord);
```

Error returned:
Unable to decode storage system.events: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x1402/[20,2]
2021-01-05 00:44:43        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x1402/[20,2]
(node:113050) UnhandledPromiseRejectionWarning: Error: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x1402/[20,2]

This also fails when trying to open this blocks from the "explorer" in piooner:
https://testnet.joystream.org/#/explorer/query/1277029
https://testnet.joystream.org/#/explorer/query/1277424

The same error can be found in the DevTools when inspecting the piooner page
![image](https://user-images.githubusercontent.com/7486476/103594220-f0db8280-4eef-11eb-9a4d-2cce6f656e14.png)

**Comment by freakstatic** [comment]
@bwhm can you check this?

**Comment by freakstatic** [comment]
This can also be related with the update of @joystream/types to the 0.14.0 version

**Comment by bwhm** [comment]
Hey @freakstatic,

> This can also be related with the update of @joystream/types to the 0.14.0 version

You are correct! This is due to the runtime upgrade performed on block [#1292265](https://testnet.joystream.org/#/explorer/query/1292265). 

The unfortunate side effect is that you can't (reliably) query older blocks. The old types won't let establish the connection, and new types will fail on certain blocks. 

One thing that does work is to re-sync up until block <1292265, and stop. Then you can use the old types, but this is super annoying to say the least.

@Lezek123 found another way some time back in #1092, which reminds me I should complete my review of that one :)

---

I don't know if backwards compatible types can be expected in the future, but I'd certainly hope so.

**Comment by freakstatic** [comment]
> Hey @freakstatic,
> 
> > This can also be related with the update of @joystream/types to the 0.14.0 version
> 
> You are correct! This is due to the runtime upgrade performed on block [#1292265](https://testnet.joystream.org/#/explorer/query/1292265).
> 
> The unfortunate side effect is that you can't (reliably) query older blocks. The old types won't let establish the connection, and new types will fail on certain blocks.
> 
> One thing that does work is to re-sync up until block <1292265, and stop. Then you can use the old types, but this is super annoying to say the least.
> 
> @Lezek123 found another way some time back in #1092, which reminds me I should complete my review of that one :)
> 
> I don't know if backwards compatible types can be expected in the future, but I'd certainly hope so.

Thanks for explaining this! 
The joystream-node has some argument that one can provide to stop the sync at some block?

**Comment by bwhm** [comment]
> Thanks for explaining this!
> The joystream-node has some argument that one can provide to stop the sync at some block?

I don't think so unfortunately. When I had to do it that way a while back, I "just" scaled back the speed towards the end...
