### ISSUE TITLE
Introduce membership for the referendum voting.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#1986]
We use membership across all the Joystream pallets to reflect user activity and maintain their reputation. The current implementation of the referendum is more abstract and doesn't require membership for usage. We could integrate the referendum pallet with the membership pallet.

#### Pros
- a consistent approach for the pallets - we use membership everywhere without any exceptions
- user reputation benefits from voting 
#### Cons
- lack of privacy 
- more complex solution
- additional dependency for the pallet

**Comment by ondratra** [comment]
The lack of privacy may not be a problem there. As long as the membership can be bought, a user wanting maximum privacy can acquire voting currency from an exchange or privacy-focused tool (like Coinjoin, Tornado cash, etc.), buy a membership, and vote privately. This brings only one extra step (buying membership) in comparison to a referendum without membership.

If we ever want to provide truly anonymous elections, we need to upgrade the voting mechanism with some Zero-Knowledge proofs or similar technology.
