### ISSUE TITLE
Issue: Community asset storage on mainnet

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1997]
Currently, the community repo (https://github.com/Joystream/community-repo) is used to store a variety of content such as:
- Documentation (reports/workflows)
- Assets (media assets that the platform has paid for)
- Code (code for the Telegram bot, code for the external stats website, code for scripts such as the Tokenomics Report Generator)

As time progresses it is likely that more and more of these assets will be created and need to be maintained.
One easy solution for storing documentation is to use the forum, however when it comes to storing code like this (https://github.com/Joystream/community-repo/tree/master/community-contributions/report-generator) it may not work.

I can foresee that more tools will be created in the future and maintained by the community for various tasks like bandwidth measurement of storage nodes and other tasks. Presumably on mainnet, there will be a wide range of tools that leads and workers are required to use in order to easily manage tasks.

Beyond these community created tools, it may be worth looking at this problem when considering where the code for Pioneer/Atlas are stored and how they would be managed.

One solution is to rely on Github or a similar service to manage this aspect of things, but maybe it is possible to have some method of doing this on-chain.

Questions:
- Where and how could code be stored and how could update/revisions be managed?
- Could some things be placed in a compressed file and uploaded using the current media storage system? (ex. in a 7z file)

**Comment by bedeho** [comment]
I would also add all the source, docs and designs for the apps to this list: it's not clear how to preserve those assets in a way that is different to just having someone be responsible for it, which has its own set of problems.

- I do not think on-chain storage is going to work all that well for this purpose unfortunately.
- We are indeed going to start working on sepcs for the 2.0 version of the storage system  in the coming 1-2 weeks, so I will keep this use case in mind.

**Comment by mochet** [comment]
> I would also add all the source, docs and designs for the apps to this list: it's not clear how to preserve those assets in a way that is different to just having someone be responsible for it, which has its own set of problems.
> 
> * I do not think on-chain storage is going to work all that well for this purpose unfortunately.
> * We are indeed going to start working on sepcs for the 2.0 version of the storage system  in the coming 1-2 weeks, so I will keep this use case in mind.

One question for you is if the forum will ever get on-chain storage of attachments (predominant use case would be for embedding images). This may be a related question as image hosting allows to have a lot more functionality without relying on external websites for hosting (as we currently do)

**Comment by bedeho** [comment]
1. There will no be on chain storage for anything except the text I am afraid, it just is not feasible.
2. We may be able to get some attachments, in particular images, stored on the storage system, but I dont think it will likely work well for all kinds of things, in particular things you want to edit over time.

I have been looking closer at [Radicle](http://radicle.xyz) recently, its a p2p github alternative. It may be more suitable than any of the above, and I will possibly open a bounty for having someone try it out, replicate the community repo on it and provide some more information for us.

**Comment by mochet** [comment]
> I have been looking closer at [Radicle](http://radicle.xyz) recently, its a p2p github alternative. It may be more suitable than any of the above, and I will possibly open a bounty for having someone try it out, replicate the community repo on it and provide some more information for us.

Hadn't heard of it before, but that sounds like a solution that could maybe work.

**Comment by mochet** [comment]
I believe this was already implemented with the new storage system so closing
