### ISSUE TITLE
Make spending proposals multiway

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1999]
Allow spending proposals to split funds among different beneficiaries with distinct accounts, up to some max limit.
Also update handbook with PR!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703470788531) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Is this done? is handbook updated?

**Comment by iorveth** [comment]
> Is this done? is handbook updated?

I guess, it's done. Are we waiting for the release to perform `olympia` issues clean-up, @bedeho ?
