### ISSUE TITLE
Sumer Release Progress Tracking

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2002]
This issue will track the weekly progress of the `Sumer` release, which has the following plan

https://github.com/Joystream/joystream/issues/2045

# Estimation Methodology

Only issues in `TODO` and `In progress` stages are counted. ...

**Comment by mnaamani** [comment]
## Date

`26th January 2021`

## Estimated Remaining Work

| Person | Hours | Weeks |
|:---|:---:|:---:|
| Arsen |  12 | 1 |
| Mokhtar |  120 | 3 |
| Klaudiusz |  0 | 0 |
| Metin |  69 | 2 |
| Dmitrii |  189 | 5 |
| Andy |  0 | 0 |
| Edvin | 0 | 0 |
| Ben |  0 | 0 |
| Ben [tests] |  0 | 0 |
| Martin |  112 | 3 |
| **Total** |  502 | 14 |

## New Estimated Release Date

### `March 30th 2021`

## Detected Overruns & Corrections

This is the first tracking issue, several team members still need to provide their estimates.

## Updated Milestones

### Production

| Person | Date |
|:---|:---:|
| Arsen |  Feb. 2 |
| Mokhtar |  Feb 16. |
| Klaudiusz |  - |
| Metin |  Feb. 9 | 
| Dmitrii |  March 2 | 
| Andy |  - |
| Edvin | - | 
| Ben |  - | 
| **Total** | March 2 |

### Testing & Fixes

| Person | Date |
|:---|:---:|
| Ben [tests] |  March 2 |
| Martin |  March 23 | 
| **Total** |  March 23 |

### Release (1 week buffer)

`March 30th`

**Comment by mnaamani** [comment]
## Date

`1st February 2021`

## Estimated Remaining Work

| Person | Hours | Weeks | Notes |
|:---|:---:|:---:|:---|
| Arsen |  12 | 1 | - |
| Mokhtar |  105 | 3 | - |
| Atlas Team |  171 | 5 |  (512h / 3 members) |
| Metin |  48 | 2 | - |
| Dmitrii |  153 | 4 | - |
| Andy |  9 | 1 | - |
| Edvin | 0 | 0 | - |
| Ben |  51 | 2 | - |
| Ben [tests] |  24 | 1 | - |
| Martin |  112 | 3 | - |
| **Total** |  502 | 14 | - |

## New Estimated Release Date

### `April 6th 2021`

## Detected Overruns & Corrections

- More detailed estimates from Andy and Arsen needed. For more accurate estimate.
- New estimates for Atlas has pushed the release by additional week. Consider adding one more team member?

## Updated Milestones

### Production

| Person | Date |
|:---|:---:|
| Arsen |  Feb. 9 |
| Mokhtar |  Feb 23. |
| Atlas Team |  Mar 9 |
| Metin |  Feb. 16 | 
| Dmitrii |  Mar. 2 | 
| Andy |  Feb. 9 |
| Edvin | - | 
| Ben |  Feb 16. | 
| **Total** | March 9 |

### Testing & Fixes

| Person | Date |
|:---|:---:|
| Ben [tests] |  March 16 |
| Martin |  March 30 | 
| **Total** |  March 30 |

### Release (1 week buffer)

`April 6th`

**Comment by mnaamani** [comment]
Quick Update - Mon Feb 15

This is still rough as we need to create tasks for all CLI, Query-Node mappings/input-schemas and integration work.

![Screen Shot 2021-02-15 at 10 24 21 AM](https://user-images.githubusercontent.com/1621012/107921987-c8cc4e00-6f88-11eb-89f2-8b47dfa95705.png)

**Comment by mnaamani** [comment]
## Date

`1st March 2021`

## Estimated Remaining Work

| Person | Hours | Weeks | Notes |
|:---|:---:|:---:|:---|
| Arsen |  31 | 1 |  |
| Mokhtar |  36 | 1 | - |
| Atlas Team |  73 | 2 |  (291h / 4 members) |
| Metin |  12 | 1 | - |
| Dmitrii |  0 | 0 | - |
| Andy |  18 | 1 | - |
| Edvin | 0 | 0 | - |
| Ben |  51 | 2 | - |
| Ben [tests] |  24 | 1 | - |
| Martin |  112 | 3 | - |
| **Total** |  363 | 12 | - |

## New Estimated Release Date

### `April 12th 2021` 

## Detected Overruns & Corrections
- pushed backed by an additional week. ( 2 weeks behind initial estimate )
- More detailed estimates from Edvin needed for more accurate estimate.
- Additional developer joined Atlas team - now team size = 4 which so far having a positive impact on progress.
- Query node we still don't have a fully working implementation in Sumer branch - PR pending test and review

## Updated Milestones

### Production

| Person | Date |
|:---|:---:|
| Arsen | Mar. 8 |
| Mokhtar |  Mar. 8 |
| Atlas Team |  Mar. 15 |
| Metin |  Mar. 8 | 
| Dmitrii |  complete | 
| Andy |  Mar. 8 |
| Edvin | n/a | 
| Ben |  Mar. 15 | 
| **Total** | March 15 |

### Testing & Fixes

| Person | Date |
|:---|:---:|
| Ben [tests] |  March 22 |
| Martin |  April 5 | 
| **Total** |  April 5 |

### Release (1 week buffer)

April 12th 2021
