### ISSUE TITLE
Content directory smart contract broken upgrade handling

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2025]
While #1921 focuses on the smart contract upgrade mechanism, this issue's aim is to prepare mechanisms that will limit possibilities of bad upgrades that could cause loss of data, service unavailability, death locks, stealing funds, etc. The initial discussion on the topic started at #1925.

Think about possible scenarios when the council approves upgrades for the content directory's smart contracts that contain a bug or malicious code and how to prevent them.

Preemptive measures could be required for the new smart contracts to fulfill a well-known interface (that is not part of the upgrade), testing some basic interactions by another smart contract (it could try if content can be added, listed, etc.). There could also be a monetary incentive for auditors to look for problems in the smart contract upgrades (and maybe penalize the council member for approving code containing critical bugs?).

In case a bad upgrade was already approved and executed, the council could have, for example, the power to rollback to the last version of the smart contract (and data when possible) during the first X days after an upgrade. Maybe there could be a way of how to have multiple content directory instances that couldn't be upgraded all at once - this wouldn't protect against malicious code, but it could prevent critical bugs making the content directory services unavailable.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703470995313) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
This is interesting, but focusing on upgradability is much less important for us now that only the financialization of channels will be in the EVM, and not all the content related stuff itself. Also, I am moving this out of Sumer, as its out of scope for that release.
