### ISSUE TITLE
Atomic multi upload

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2030]
A atomic version of `add_content` in the `DataDirectory` pallet, so something like

```Rust
struct ContentParameters {
            content_id: T::ContentId,
            type_id: <T as data_object_type_registry::Trait>::DataObjectTypeId,
            size: u64,
            ipfs_content_id: Vec<u8>
}

pub fn multi_add_content(
    origin,
    member_id: MemberId<T>,
    content: Vec<ContentParameters>
)       
```

which only has side-effects if adding everything in `content` will suceed, and if so emits a new event `ContentMultiAdded(ContentId, MemberId, Vec<ContentParameters>)`.

This is unfortunately temporary, as we will redo the storage system in a later release, however having this now allows other parts of the infra+apps to behave as they ultimately should.

**Comment by mnaamani** [comment]
This looks reasonable.
The event will more likely be: `ContentMultiAdded(StorageObjectOwner, Vec<ContentParameters>)` to reflect the ownership as per https://github.com/Joystream/joystream/issues/2044

**Comment by iorveth** [comment]
Is there any reason to have both versions similar to https://github.com/Joystream/joystream/issues/2044

// auth using origin using normal checks
```
fn multi_add_content_as_member(
    origin,
    member_id: MemberId<T>,
    content: Vec<ContentParameters>
);
```

// auth using Root origin check
```
fn multi_add_content(
  origin,  
  abstract_owner:  AbstractStorageObjectOwner , 
  content:: Vec<ContentParameters>
)
```

**Comment by iorveth** [comment]
cc @bedeho @mnaamani

**Comment by bedeho** [comment]
Yes I think so, because these groups should be able to just directly upload to the storage system for purposes outside of teh content directory.

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2103
