### ISSUE TITLE
Updated media asset location representation

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2033]
For assets living on native Joystream infrastructure, we must capture the fact that

- when first being uploaded, there is no asset to display for the content until at least the liason confirms the upload was successful, something which may itself be perpetually delayed if the upload first fails.
- when editing the asset, the old asset should keep getting used until the new asset has been confirmed by the liason. Notice that this resets on the assumption that the old asset will not be deleted in the interim, which is true, as deletion is not even possible in the current storage system, and the future it will be impossible if the asset is use. Notice that an edit can interrupt another in flight edit, for example if the first edit failed to complete.

The current representation looks like this

```graphql
  "Id of the data object in the Joystream runtime dataDirectory module"
  dataObjectId: String! @unique

  happenedIn: Block!
```

and it needs to be replaced by something in this spirit

```graphql

enum UploadStage {
  IncompleteFirstUpload
  IncompleteLaterUpload
  ConfirmedUploaded
}

...

   "Stage of an upload."
   upload_stage: UploadStage!

  "Id of last initiated upload of data object."
  lastDataObjectAttemptedUploaded: String!
  
   "Id of last initiated upload of data object."
  lastDataObjectConfirmedUploaded: String

  "Block where last upload attempt was initiated on-chain."
  lastUploadInitiatedInBlock: Block!
  
```

This is just a sketch of something capturing the intended functionality, it is not confirmed to work well in the broader content directory data model refactoring for `Sumer`.

**Comment by bedeho** [comment]
Or with variants somethign like this

```Rust 
enum StorageAssetStatus {
  PendingFirstUpload(DataObjectId),
  CompletedUpload(DataObjectId),
  WaitingForReplacementUpload(/* old */ DataObjectId, /* new */ DataObjectId )
}
```

**Comment by bedeho** [comment]
I am working on schemas for Pioneer that also need some sort of representation of assets being uploaded, so I gave it a crack, ended up with something like this

```graphql


# Below, the term upload life-cycle basically refers to
# semantics of the following enum from the chain
# pub enum LiaisonJudgement {
#    /// Content awaits for a judgment.
#    Pending,
#
#   /// Content accepted.
#    Accepted,
#
#    /// Content rejected.
#    Rejected,
# }

# Asset is missing
type NeverProvided @variant {
}

# Asset was deleted
type Deleted @variant {
}

# Status of an upload
type UploadStatus @variant {

  "Data object in upload life-cycle.
  If this is deleted, then set oldDataObject in its place if it is set and not rejected, otherwise union goes to Deleted."
  dataObject: DataObject!

  "Possible prior data object which was in some stage of upload life-cycle when new one was initiated.
  If accepted, then apps may chose to use old in place of new before it is accepted.
  If this is deleted, then set to null."
  oldDataObject: DataObject

}

# The status of a storage asset
union StorageAssetStatus = NeverProvided | Deleted | UploadStatus

type DataObject @entity {
  /* fill in, most importantly liaison_judgement and dates */
}

```

What do you guys think? is it clear, too complex? It certainly gives Atlas & Pioneer a lot of flexibility in how to treat published things (channels, videos, memberships, forum posts) which have assets in various stages of maturity, even when there is deletion.

**Comment by kdembler** [comment]
I think I'm not familiar with this format, is this the input schema?

I wouldn't expect `UploadStatus` to be a type containing `dataObject`, rather the other way around.

Also, `union StorageAssetStatus = NeverProvided | Deleted | UploadStatus`, my guess is that it will be `NeverProvided` till the first upload is _finished_?

**Comment by metmirr** [comment]
It looks good to me but there are some limitations with `variant` types. You can not define a variant without any field, when you do hydra-cli will fail during code generation.

Also, I think will be better if we name variants as follows: `AssetNeverProvided`, `AssetDeleted`, `AssetUploadStatus` it may be more descriptive when you have many entities in the same input schema.

**Comment by bedeho** [comment]
> It looks good to me but there are some limitations with variant types. You can not define a variant without any field, when you do hydra-cli will fail during code generation.

can we fix this? made issue https://github.com/Joystream/hydra/issues/186

>  I think will be better if we name variants

Agree.

> I think I'm not familiar with this format, is this the input schema?

Yes.

> I wouldn't expect UploadStatus to be a type containing dataObject, rather the other way around.

Ok, well think about it some more ;)

> my guess is that it will be NeverProvided till the first upload is finished?

No this is only the initial state when something is published without a specific asset. So think creating a channel without a cover. We allow this at the blockhchain level, but it is up to ATlas and other products to decide what to do in these cases.

**Comment by kdembler** [comment]
> I wouldn't expect UploadStatus to be a type containing dataObject, rather the other way around.

Okay yeah, that makes sense. I think `UploadStatus` name thew me off, that's more like an `Asset` in my mind, it doesn't really contain any upload status by itself, right? Then my other guess is that `DataObject` would actually contain some kind of upload status?

**Comment by bedeho** [comment]
Yes `DataObject` has model of full life cycle of a data object, names can probably be improved indeed.
