### ISSUE TITLE
Storage for all

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2044]
Currently storage objects are directly owned by members, this has at least two problems

1. when you transfer ownership of a channel to someone else, the runtime will need to enumerate and update storage object ownership to that new member, if its even a member... see next point.
2. non-member ownership is required, such as a particular curator group, or a DAO in the future.

Meanwhile, we still want members to also directly own storage assets, so basically we get.

```Rust

enum WorkinGroupType {
 Builders,
 Marketers,
 Membership,
 ...
}

enum AbstractStorageObjectOwner {
 Channel(ChannelId), // acts through content directory module, where again DAOs can own channels for example
 DAO(DAOId), // acts through upcoming `content_finance` module
 Council, // acts through proposal system
 WorkingGroup(WorkinGroupType) // acts through new extrinsic in working group
 }

// new owner type for storage object struct
enum StorageObjectOwner {
 Member(MemberId), 
 AbstractStorageObjectOwner(AbstractStorageObjectOwner)
}
```

and the extrinsics would be

```Rust

// auth using origin using normal checks
fn upload_as_member(origin, member_id: MemberId, content: ...);

// auth using Root origin check
fn upload(origin,  abstract_owner:  AbstractStorageObjectOwner , content: ...)
```

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2099
