### ISSUE TITLE
Sumer Release Plan

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2045]
# Name

`Sumer`

# Brand

![brand](https://user-images.githubusercontent.com/437292/105067865-79c1f480-5a80-11eb-8c17-b95ca18db603.png)

# Goals

### 3. `Enable builders and gateway roles.`

# Runtime Base

`Babylon`

# Overview

# Background

This release is a synthesis of distinct strands of improvement which became most practical to plan and execute in one release due to the interdependencies involved:

1. A publishing UI for WYSIWYG publication and management of content.
2. A storage system that allows the publishing experience we are building will be able reflect, as closely as possible, the properties of the storage system in the long term. In particular being able to do a single on-chain operation for simultaneously uploading an unlimited number of assets and editing the content directory.
3. A content directory query node API which is aware of upload latencies or interruptions for media assets.
4. A new content directory which resolves long standing tradeoffs.
5. Unlocking some new roles which will allow community members to learn more about running the platform.

In what follows we will dive more deeply into each release goal, which then touches upon the

## A `simple` content directory.

We have gone through a number of iterations on the content directory, and the ongoing concern has been how to facilitate more rapid upgrade&migration free evolution. At the end of the day, considerable effort has been spent exploring alternatives, but overall the other technical complexities and tradeoffs arrived at have not bee acceptable. As a result, we are now going to go with a simple native runtime module.

https://github.com/Joystream/joystream/issues/2070

### Publishing Today

Current it is not possible to publish in atlas, in fact the only way to create and manage channels and videos is using a CLI, which is extremely cumbersome, as it requires learning about and correctly doing the following
1. Manually getting tokens and a membership
2. Downloadig & installing Node & NPM.
3. Installing CLI.
4. Importing membership account into CLI.
5. Manually preparing json metadata files and assets for a channel.
6. Doing command (hopefully works).
7. ...then a bunch of magic steps like 5+6 this per video publication.

### Publishing in Atlas

A full onboarding, membership creation, channel creation, dashboard, video publishing and management experience has been designed, see here

https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=3079%3A30013

Importantly, a broader set of features have been designed than we should aspire to build in this release, so we are focusing on a core subset of features related to publishing, without accumulating tech debt. It was originally done under the following design brief,

https://github.com/Joystream/atlas/issues/31

which itself is not in synch with the final designed product, because we decided to change some of the constraints in process - most importantly having Joystream hosted media assets.

However, mistakes were made on the part of Bedeho when directing this effort, hence some mismatches have been identified between what the design presumes and the behaviour of the system, and some other more minor areas of improvement, see here

https://github.com/Joystream/atlas/issues/215

Work has started to analyse the required changes, and the final results should be reflected in the final release plan.

## New roles

There are a few roles we can unlock which require next to no change in the runtime beyond adding corresponding working groups, specifically _builders_ and _gateway operators_.

### Builders

See `Builder` under https://www.joystream.org/roles.

### Gateway

This role has not yet been described, but an _almost complete_ specification is about to be completed describing this role in detail. The short story is that these are people who make a business model out of operating user facing applications, for example websites, apps in app stores and so on. They will be able to onboard and monetize users with substantial flexibility while relying on the core Joystream infrastructure, like bandwidth and content.

In this release what these operators will do is simply to run an instance of Atlas running on a top level domain, along with a query node. We will route visits from our main site to different instances randomly.

### Team

- **Mokhtar**
- **Arsen**

### Work Scope

**Make life easier for query node side by replicating all extrinsic parameters in events + sideffect values.** https://github.com/Joystream/hydra/issues/164

#### Storage system changes

- Introduce multi-uploads: https://github.com/Joystream/joystream/issues/2030
- Non-membership storage object ownership: https://github.com/Joystream/joystream/issues/2044
- Introduce deletion of storage objects, we allow deleting anything even if its used. Actions happen with same auth scheme as uploading, as described in https://github.com/Joystream/joystream/issues/2044.
- Introduce quota limits utilisation tracking for all actors: same fixed number for everyone to begin with, lead can adjust.

#### Content Directory

Make a new module use this as a base https://github.com/Joystream/joystream/issues/2070 but some important changes.

- Channels are owned by members, curator groups or DAOs.
- Channels must have a JOY treasury which receives revenues from content later.
- Update representations to use opaque metadata blobs not stored in storage, or validated for parts of the metadata that can be validated statelessly. Bedeho can help with review here.
- All image assets, which are light, must live on Joystream infra, while heavy video assets can also live on web, however there must be mutually exclusive storage locations for assets, in old schemas assets could simultaneously live on web and Joystream infra.
- Some representations are clearly bad, because they make it hard to make trivial changes in the future, such as language enum hard coded, find workarounds.
  - use opaque values in metadata, such a language codes, country codes, license codes, etc. We can have our own.
  - for properties that belong to more perpetually dynamic spaces curated by roles, such as categories, introduce new maps.
- There is no need to have any sort of auto deletion when replacement uploads are completed. We instead require users to manually delete at a later time if they are getting low on free space. This means the entire callback on liason confirmation and storage object index can be dropped, and data objects need not be represented in any way on content (`StorageAssetStatus`).
- Define encoding standard for metadata blobs for both creation and update operations in content directory, use protocol buffers. So for channels for example, there would be `ChannelCreationMetadata` and `ChannelUpdatingMetadata`. Use this to build typescript library for doing serialization/deserialization. It may be the case that some versioning model could make sense, and protocol buffers have explicit support for this, but I suggest we stick to a simple model for now, given the number of moving parts in this release. **It would be highly desirable if part of the output here is a document that can go into the handbook, and which can be read by the query node developers who will write the query node input schema and implement the message processing.**

#### Working group

- Add raw storage field to working group roles that they can update as they please. This can be used to find hosts or other information associated with a subsystem role, and it the reason to put it straight in storage like this is to avoid reliance on query node for such a fundamental lookup. Depending on our experience here we may port this forward to Olympia working group.
  - Add required new upload action for non-membership storage ownership.
- Remove the existing content directory and working group _integration_.
- Introduce support for builder working group.
- Introduce support for gateway working group.

#### Proposal System

- Introduce support for builder working group in proposal system.
- Introduce support for gateway working group in proposal system.

### Current Status

Just an early sketch outline.

### Initial Division of labour

Team can figure it out internally.

### Team

- **Mokhtar**

### Work Scope

- Update to work with new storage system: superficial changes?
  - check upload hash.
  - check upload size, since we are doing quotas.

### Current Status

None.

### Initial Division of labour

Only **Mokhtar**.

### Team

- **Metin**
- **Dmitrii**

### Work Scope

- Get Hydra working with native typegen setup as smoothly as possible.
- Filtering in search results: https://github.com/Joystream/hydra/issues/127 Does this allow filtering union type fields?
- Subscription for what block has been processed: https://github.com/Joystream/hydra/issues/166

### Current Status

Nothing is done here.

### Initial Division of labour

**Metin** only.

### Team

- **Metin**
- **Andy**
- **Atlas Team**

### Work Scope

- New input schema:
  - Mirror new content directory developed, use early API drafts to unlock Atlas development.
  - Asset Location Representation https://github.com/Joystream/joystream/issues/2033
  - Add account and membership awareness required to power the onboarding flow in Atlas.
- (big task) Write new mappings.

### Current Status

Nothing is done here.

### Initial Division of labour

- **Atlas Team** does content directory part of input schema
- **Metin** does membership and account side of input schema.
- Split mapping work evenly among **Metin** and **Andy** until its done.

### Team

- **Edvin**

### Work Scope

- Introduce support for builder working group.
- Introduce support for gateway working group.
- Show new raw note field on working group overview.

### Initial Division of labour

None.

### Current Status

Nothing is done here.

### Team

- Atlas Team
  - **Francesco**
  - **Klaudiusz**
  - **Maciej**
  - **Bartosz**
  - **possible newcomers**
- **Moktar**

### Work Scope

- As mentioned above there is a full design for the publisher side, however, it needs to be restricted in the following way
 - No channel dashboard.
- Update or create faucet server for powering the onboarding flow.
- Introduce light weight client side image clipping in the image editor prior to upload. **Important: only apply operation when transaction initiation is done, because user may want to multiple times before comitting.**
- Ability to enforce filtering away of upload not fully uploaded in free-text search: https://github.com/Joystream/hydra/issues/127
- Develop library for interacting with content directory, and storage system which can be reused in Atlas, integration tests and CLI. There is already some library code developed for this used in existing CLI, but its not clear how useful it is to build on it given the deep changes. Also see this issue about getting results, it may be in scope. https://github.com/Joystream/joystream/issues/2018.
- Package Atlas + the query node in some setup where it is relatively easy to someone to fire up an instance of Atlas using their query node. This is needed for the gateway role. Faucet can still be centralised pointing at Jsgenesis.

### Initial Division of labour

Klaudiusz will allocate tasks internally in Atlas team, with help from Mokhtar here.

### Team

- **Arsen**
- **Andy**

### Work Scope

- Polkadotjs library & examples
- Update CLI to work with new content directory
  - publishing
  - curation
- Update CLI to work with new storage system
  - delete as member.
  - delete as channel owner, owned by member or owned by curator group member.
- Update mass-uploading script to populate using old seed content. There is no need to migrate over anything.
- Introduce support for builder working group.
- Introduce support for gateway working group.

### Current Status

Nothing is done here.

### Initial Division of labour

Decide internally.

### Team

- **Mokhtar**
- **Metin**
- **Arsen**

### Work Scope

- Updated to work with runtime upgrade.
- Add a simple scenario to integration tests for multi-upload.

### Current Status

Nothing has been done.

### Initial Division of labour

**Mokhtar** does everything.

### Team

- **Martin**
- **Ben**

### Work Scope

- Write testing plan in advance and share with Bedeho.
- Conduct test in accordance with plan. The testing here should be targeting CLI, Query Node and Atlas working well together. There are very minor new features, but they are of trivial significance, its mostly about confirming that existing functionality still works. CLI should be a bit more involved, as there will be some new non-trivial features. Part of the rationale for the testing is also to help get informed for updating tutorials.

### Current Status

Nothing has been done.

### Initial Division of labour

Not determined.

### Team

- **Martin**
- **Ben**
- **Edvin**

### Work Scope

- Update status server.
- Make KPIs about gateways, or something else to make sure that there is reason for people to do it.
- Make KPIs about builders, or something else to make sure that there is reason for people to do it.
- Update website to dynamically send people towards gateway instances of Atlas.
- Update website for announcement.
- Update website for release.
- Update roles section of mailinglist to reflect new roles: add gateways.
- Update tutorials.
- Announcement and release communications: blog + newsletter

### Current Status

Nothing has been done.

### Initial Division of labour

Not determined.

# Dependencies

![Dependencies2](https://user-images.githubusercontent.com/437292/105067924-8d6d5b00-5a80-11eb-8bdf-62e351bfe0f1.png)

# Project Management

## Release Manager

`Mokhtar`

The release manager is responsible for tracking overall progress, detecting delays and course-correcting. Tracking will be done weekly in this issue

https://github.com/Joystream/joystream/issues/2002

as described by the following methodology

https://github.com/Joystream/joystream/issues/474

## Release Branch

https://github.com/Joystream/joystream/tree/sumer

## Github Project(s)

We are doing everything in one project.

https://github.com/orgs/Joystream/projects/32

### Biweekly(ish) Release Meetings

A release wide meeting will be organised semi-regularly, we could start at a pace of once ever 2 weeks to begin with. Experience has shown that, even when there is no obvious issues that need tackling, discussions often reveal issues and corner cases that have not been accounted for. We can aim for one team rep. being present, so as not to distract everyone. Log will be kept here:

https://github.com/Joystream/joystream/issues/1241

**Comment by bwhm** [comment]
Edited some minor typo fixes.

> #### Content Directory
> ...
> - Remove the existing content directory and working group _integration_.

I assume you mean both here? We didn't remove the old content directory modules when adding the new ones.

> #### Colossus
> ...
> - Update to work with new storage system: superficial changes?

If it's correct that we can't do non-video assets, this must be enabled as well. 

> #### Pioneer, CLI & Tooling, Network Testing
> ##### Team(s)

I would suggest:
- Pioneer: Edvin
- CLI: Edvin. Some can also be bounties, spec'd by me.
- Network Testing: Status server and Telegram bots can also be assigned to Edvin/bounties/me.

**Comment by mnaamani** [comment]
Gateways
- Will operators need to configure Atlas must to use one common Orion service to preserve the personalization experience?

- "We will route visits from our main site to different instances randomly." This will need some thought. Where will the list of active gateway operators to Url mapping be maintained? To have a good UX when 'directing' to different instances our landing page needs to have some way to select a 'working' atlas instance.


Storage and Colossus:
- The impact on Colossus is not substantial as the public facing API is will not change. We just have to add some routines to unpin ipfs objects to relieve the storage burden on the node
- When doing multi uploads we need to consider whether the runtime should select multiple providers (liaisons) to distribute the upload burden or just dump all the assets on a single provider.

Content Directory:
- Define encoding standard for metadata blobs: Protocol buffers are great, but we might be able to just use parity-codec encoding. We can define the formats using familiar way which we do for joystream/types in the types library and get Typescript type definition generation.

**Comment by bedeho** [comment]
> When doing multi uploads we need to consider whether the runtime should select multiple providers (liaisons) to distribute the upload burden or just dump all the assets on a single provider.

Yeah, I thought we keep it simple, so they are totally separate uploads, we can do something different later.

> Protocol buffers are great, but we might be able to just use parity-codec encoding. We can define the formats using familiar way which we do for joystream/types in the types library and get Typescript type definition generation.

I do not know exactly what this looks like, but protobuffers separate the description from the code, and has bindings in basically any language, would we get the same benefit?
