### ISSUE TITLE
bootstrap QueryNode member information

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#2073]
Indexing from block zero will not be an option
Export Initial state of Members and Accounts to bootstrap querynode database.

**Comment by ondratra** [comment]
Bootstrapping of both members and accounts has been merged into master. Related PRs are #2384 and https://github.com/Joystream/runtime-state-export-tools/pull/6 . Use `export_members.ts` and `export_workers.ts` scripts from https://github.com/Joystream/runtime-state-export-tools to export bootstrap able data from an existing chain.
