### ISSUE TITLE
Content Directory: Videos

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#2080]
Implement Videos as described in https://github.com/Joystream/joystream/issues/2070

Build on https://github.com/Joystream/joystream/pull/2158

For sumer we only need to implement the following extrinsics:

```
create_video()
update_video()
delete_video()
set_featured_videos()
create_video_category()
update_video_category()
delete_video_category()
censor_video()
uncensor_video()
```

**Comment by mnaamani** [comment]
cc: @iorveth

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2194
