### ISSUE TITLE
Add raw storage field to working group roles

### ISSUE THREAD

**Issue by iorveth** [Joystream/joystream#2086]
Add raw storage field to working group roles that they can update as they please.

**Comment by iorveth** [comment]
cc @bedeho, should i introduce a length constraint for the raw storage field?

**Comment by bedeho** [comment]
Yes, sorry for the late reply. Only upper bound is strictly needed, but its fine either way.

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2180
