### ISSUE TITLE
Query node: data storage entity and events

### ISSUE THREAD

**Issue by metmirr** [Joystream/joystream#2090]
Query node will make sure the content is accepted/rejected in the storage to do that:

- Add an entity to the input schema
- Create event handlers for:
```rust
ContentAdded(ContentId,
ContentAccepted(ContentId, StorageProviderId),
ContentRejected(ContentId, StorageProviderId),

**Comment by bedeho** [comment]
There will also be deletion now, be aware, new event - presumably `ContentDeleted` will be added.

**Comment by bedeho** [comment]
This new post is relevant to how to process these events https://github.com/Joystream/joystream/issues/2033#issuecomment-769263294

**Comment by ondratra** [comment]
Storage-related mappings for the Sumer release have been merged into master. Related PR's were #2361, #2283, #2225, #2159, and maybe others.
