### ISSUE TITLE
Define shared proposal parameters

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#210]
Define the parameters for proposals to vote for in Constantinople.

May be an iterative process...

**Comment by bwhm** [comment]
Engine parameters:
```
/// Set temporarily, but might get revisited:
    pub const ProposalCancellationFee: u64 = 5000;
    pub const ProposalRejectionFee: u64 = 0;
/// Set now:
    pub const ProposalTitleMaxLength: u32 = 40;
    pub const ProposalDescriptionMaxLength: u32 = 3000;
    pub const ProposalMaxActiveProposalLimit: u32 = 5;
```

Rationale:
- Assuming `ProposalCancellationFee` is the fee the proposer has to pay for cancelling their own proposal while in voting, I think there are a quite some things to consider:
  - It should cost enough to avoid users making proposals just for "fun"
  - It should cost enough to ensure users will ensure their proposal is accurate and well articulated (if applicable)
  - On one hand, it makes sense to have a discount for withdrawing rather than getting slashed, so one could argue it should be cheaper than making the proposal in the first place. Simultaneously, it could lead to users just checking whether it looks like the Council is leaning towards slashing, and then withdrawing in time.
  - One could argue that if circumstances change, it should be rather cheap to withdraw, but the Council shouldn't punish the proposer by slashing anyway if that is the case.
  - Summary: Landing on 5000 here, but will most likely get revisited.
- Assuming `ProposalRejectionFee` means a fee withdrawn from the stake of the proposer if the proposal gets rejected, I'm not even sure we want this. If a proposal is bad/malicious, the Council should slash anyway. To me, it seems better to reward a proposal voted in rather than punishing a proposal voted down despite being made in good faith.
  - Setting this to 0.
- `ProposalTitleMaxLength` can be as low as 40 IMO. The proposal type already indicates a lot, and there shouldn't be a need to add an address/account in the title.
- Assuming `ProposalDescriptionMaxLength` is the "rationale" that applies to all proposals, I think we need to allow a relatively high number.
   - Pro: 
     - If one needs to paste in chat logs, etc. a low limit (such as 1k) would make it impossible to paste logs (eg. `Evict Storage Provider`)
     - Hard properly articulate ones arguments (most of them, really)
     - Proposals most likely won't be made that often, so load on the chain shouldn't be that bad.
   - Con:
     - If one needs 10k chars (the equivalent of 36 tweets) to state their argument, it probably needs to be presented more concisely.
     - People have a tendency not to read long blocks of text properly
     - Although chain size might not be affected, propagation and validation may suffer more
     - The same _may_ apply to pioneer, which is already quite heavy
     - Links to the forum, and the proposal discussion allows one to better
  - Summary: Landing on 3000 here as a starting point.
- Assuming the`ProposalMaxActiveProposalLimit` are the highest number proposals in `voting_stage` simultaneously, this number must be reasonably low. With the absence of valuable state parameters such as max number of proposal type `x`, and priority to proposals with higher stake, there is only so much the council can have an informed opinion on at the same time.
   - I think 5 is a high enough number, as long as proposals in `grace_period` don't count.
   - ~~If proposals in `grace_period` counts, I think 10 is needed.~~


Discussion parameters:
```
    pub const ProposalMaxPostEditionNumber: u32 = 0;
    pub const ProposalMaxThreadInARowNumber: u32 = NA;
    pub const ProposalThreadTitleLengthLimit: u32 = 40;
    pub const ProposalPostLengthLimit: u32 = 1000;
```

Rationale:
- Assuming `ProposalMaxPostEditionNumber` means the number of times one can *update* a comment/reply, and the module (unlike the forum) has no timer for when a reply is finalized, I think this should be 0.
- Assuming a new comment starts a new discussion thread by default:
   - ~~Not sure what `ProposalMaxThreadInARowNumber` this means.~~ Not applicable
   - `ProposalThreadTitleLengthLimit` should be the same as the `ProposalTitleMaxLength` -> 40
   - `ProposalPostLengthLimit` could be quite short. 1000 is more than enough imo.

Codex:
```
    pub const TextProposalMaxLength: u32 = HOLD;
    pub const RuntimeUpgradeWasmProposalMaxLength: u32 = NA;
```

Rationale:
- `TextProposalMaxLength` only applies to `Text/signal proposal`, and not in characters, but  bytes: This needs to be calculated based on:
   - `ProposalTitleMaxLength>=40`
   - `ProposalDescriptionMaxLength>=3000`
   - Max length of the third input field, set to 5000 in #235.
   - Take the size of an extrinsic where all of these are maxed out, and round up?
- `RuntimeUpgradeWasmProposalMaxLength` - should match the extrinsic, currently set to 2_000_000

**Comment by bwhm** [comment]
Instead of updating the comment, I'm making a new comment. Won't elaborate here, just numbers:

```
    pub const ProposalCancellationFee: u64 = 10000;
    pub const ProposalRejectionFee: u64 = 5000;
    pub const ProposalTitleMaxLength: u32 = 40;
    pub const ProposalDescriptionMaxLength: u32 = 3000;
    pub const ProposalMaxActiveProposalLimit: u32 = 5;
--
    pub const ProposalMaxPostEditionNumber: u32 = 0;
    pub const ProposalMaxThreadInARowNumber: u32 = NA;
    pub const ProposalThreadTitleLengthLimit: u32 = 40;
    pub const ProposalPostLengthLimit: u32 = 1000;
--
    pub const TextProposalMaxLength: u32 = *;
    pub const RuntimeUpgradeWasmProposalMaxLength: u32 = **;
```

- `*` Still not really sure how this works, but if it's the size of the signed extrinsic, it should be slightly greater whatever the signed extrinsic size is with all fields populated fully, multiplied by 1.5 for safety...?
- `**` Still not really sure how this works, but if it's the size of the signed extrinsic, it should be slightly greater whatever the extrinsic size is with both text fields populated fully, and a wasm blob of `=2_000_000` signed, multiplied by 1.5 for safety...?

**Comment by shamil-gadelshin** [comment]
Released.
