### ISSUE TITLE
Draft: Mokhtar's Tasks Constantinople

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#211]
## Runtime

**Evicting a storage provider** Proposal
available call:
[`remove_actor(origin, actor_account: T::AccountId)`](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/roles/src/actors.rs#L409)

**Proposals for Storage Providers** staking and rewards
  - Storage provider count.  - `max_actors: u32`
  - Storage provider reward.  - `reward: Balance, reward_period: BlockNumber`
  - Storage provider staking limit.  - `min_stake: Balance`

Existing sudo dispatchable: `set_role_parameters()` is available:

**Call:**
https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/roles/src/actors.rs#L378

**Parameters:**

role: [`membership::members::Role::StorageProvider`](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/membership/src/role_types.rs#L7)

params: [RoleParameters](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/roles/src/actors.rs#L16)

Alternatively add new dispatchables for changing individual parameters:?

  - `set_storage_role_min_stake_param(min_stake: Balance)`
  - `set_storage_role_max_actors_param(max_num_actors: u32)`
  -  `set_storage_role_reward_param(amount: Balance, period: BlockNumber)`

setting the values have immediate effect and:

 `now % params.reward_period == T::BlockNumber::zero()` in `on_finalize` determines when payout is made.

Test already exists for `set_role_parameters()`

**Proposals for Curators**

  * Content Curator reward. 
  * Content Curator staking limits. (Range, or just min or max ?)
  * Content Curator Hiring Constraint fields limits. (Range, or just min or max ?)

**Creating Openings** - staking and hiring constraints
add new state storage values:
  - CuratorApplicationStakingRange: range of values for role staking policy: min and max
  - CuratorRoleStakingRange: range of values for app staking policy: min and max
  - UnstakingPeriods...?
  - SlashingPolicy/Slashable Terms ...?

we either need to add migration during runtime upgrade to give the new state storage values initial values or make them "Option"al default of 0 might work as well.

  - modify `add_curator_opening()` (called by lead) takes an [`OpeningPolicyCommitment`](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/content-working-group/src/lib.rs#L707)
    to validate commitment values are in acceptable ranges (defined above)

  - add sudo dispatchable for each new state storage value to set a new value/range

To simplify do we want proposal to just set one state value: `CuratorOpeningPolicyCommitment` of type `OpeningPolicyCommitment` which is applied when lead creates a new opening?

**Question**: When changing staking parameters do we want to retroactively apply them to active curators?

**Rewards:**
add new state storage values:
  - CuratorRewardPerPayoutAndPayoutInterval: `Option<(Balance, BlockNumber)>`

  - [`fill_curator_opening()`](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/content-working-group/src/lib.rs#L1447) (called by lead) takes an [`Option<RewardPolicy>`](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/content-working-group/src/lib.rs#L979) : 
Drop the option argument and use `CuratorRewardPerPayoutAndPayoutInterval`, can only set when first payment will be

  - add sudo dispatchable `set_curator_reward_policy(policy: Option<(Balance, BlockNumber)>)` to set CuratorRewardPerPayoutAndPayoutInterval.

**Question**
should we iterate over recurring rewards of current active curators, and update? In other words does the proposal only set the reward for next hired curator or all active curators?

  - Add Tests
  
**Validator count** Proposal

srml-staking module already has sudo dispatchable: [`fn set_validator_count(origin, new: u32)`](https://github.com/paritytech/substrate/blob/c37bb08535c49a12320af7facfd555ce05cce2e8/srml/staking/src/lib.rs#L963)

**Suggested additional proposal?**
  * Add to  capacity of Content Working Group Mint. 

`pub fn increase_mint_capacity(origin, additional_capacity: minting::BalanceOf<T>)`

**Migration logic from Rome:** 
We need to reset all, or some balances, however, this will disrupt all the stakes of people involved in various roles (council, validation, storage, curators, etc.) and also stakes of voters currently staking. A strategy is needed:
 
Split into two tasks:
- research:
   -  investigate if its safe to modify stash and controller balances of validators, 
   - we can iterate all "known" accounts with positive balance (from members, roles, validators etc)
      but can we iterate other accounts? balances maps are not `linked_map` maps and we do not use the account indexing feature.
    - Can the migration be completed within target block production interval of 6s? or does it need to be split over multiple blocks...?
- implement (if possible)

If not possible, what is alternative? 
  1. Artificially increase total issuance to make existing balances insignificant..
  2. make the conversion rate reflect insignificant value of issued balances.

### Storage bench-marking tool
  - Review current state of tool
  - Determine what KPI to be measured
  - Implement changes in existing tool
  - Implement changes in Colossus to support benchmarking

### Validator bench-marking tool
   -  Research how to go about this.
   -  Implement tool

**Comment by bwhm** [comment]
A couple of comments and questions here regarding the proposals only:

> **Proposals for Storage Providers** staking and rewards
> 
>     * Storage provider count.    - `max_actors: u32`
> 
>     * Storage provider reward.    - `reward: Balance, reward_period: BlockNumber`
> 
>     * Storage provider staking limit.    - `min_stake: Balance`

I seem to recall a couple of these parameterss are not actually read, but it still seems _easier_ to only allow proposing a new set. It will require a little more documentation perhaps, but implementation is far easier?

 
> Existing sudo dispatchable: `set_role_parameters()` is available:
> 
> **Call:**
> 
> https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/roles/src/actors.rs#L378
> 
> **Parameters:**
> 
> role: [`membership::members::Role::StorageProvider`](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/membership/src/role_types.rs#L7)
> 
> params: [RoleParameters](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/roles/src/actors.rs#L16)
 
> Alternatively add new dispatchables for changing individual parameters:?

See comment above
 
>     * `set_storage_role_min_stake_param(min_stake: Balance)`
> 
>     * `set_storage_role_max_actors_param(max_num_actors: u32)`
> 
>     * `set_storage_role_reward_param(amount: Balance, period: BlockNumber)`
> 
> 
> setting the values have immediate effect and:
> 
> `now % params.reward_period == T::BlockNumber::zero()` in `on_finalize` determines when payout is made.
> 
> Test already exists for `set_role_parameters()`
>

---
 
> **Proposals for Curators**
> 
>     * Content Curator reward.
> 
>     * Content Curator staking limits. (Range, or just min or max ?)
> 
>     * Content Curator Hiring Constraint fields limits. (Range, or just min or max ?)

This one requires some thinking, as I'm fairly sure the following are not possible:

**Change reward for existing curator(s)**
This means the early hires could see their rewards get inflated away, but that should be resolved with properly functioning governance. It could still be an issue though, if the only solution is to fire -> re-hire.

**Slash curator**
For a functioning governance system, the ability to slash is needed. Currently, it has to be done by `sudo`->`setBalance`/`forceTransfer`. We _could_ add one of those as a proposal, but it would require a loooong voting period to avoid other uses, which would defeat the purpose...

> **Creating Openings** - staking and hiring constraints
> add new state storage values:
> 
>     * CuratorApplicationStakingRange: range of values for role staking policy: min and max

I assume this wouldn't change active curators? Regardless, I'm not sure how useful this one really is...
 
>     * CuratorRoleStakingRange: range of values for app staking policy: min and max

Same as above.
 
>     * UnstakingPeriods...?

Same as above.

>     * SlashingPolicy/Slashable Terms ...?

Currently, the runtime only allows a text field, `Rationale` for firing/quitting. Not sure how this would work.

> *`modify add_curator_opening()`...

I think regardless of the rest, the rewards for the role needs to be defined when an opening is made, and enforced by the runtime. Currently, the lead can set whatever rewards he wants to when hiring.

> **Question**: When changing staking parameters do we want to retroactively apply them to active curators?

Yeah, that needs some thinking. You applied for the job with a specific set of conditions, so might not be fair to change in flight.

> **Rewards:**
> add new state storage values:
> 
>     * CuratorRewardPerPayoutAndPayoutInterval: `Option<(Balance, BlockNumber)>`
> 
>     * [`fill_curator_opening()`](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/content-working-group/src/lib.rs#L1447) (called by lead) takes an [`Option<RewardPolicy>`](https://github.com/Joystream/substrate-runtime-joystream/blob/251840fee6c8f29792dec6b1e11dc0406132d176/runtime-modules/content-working-group/src/lib.rs#L979) :
>       Drop the option argument and use `CuratorRewardPerPayoutAndPayoutInterval`, can only set when first payment will be

See comment above.

>     * add sudo dispatchable `set_curator_reward_policy(policy: Option<(Balance, BlockNumber)>)` to set CuratorRewardPerPayoutAndPayoutInterval.
> 
> 
> **Question**
> should we iterate over recurring rewards of current active curators, and update? In other words does the proposal only set the reward for next hired curator or all active curators?

As mentioned above, it's a mixed bag here. On one hand, it's nice to be able to change this in-flight, but it could also mean a pay cut that would not be acceptable. Something like this would mean (at least for the final product) that curators (and for other working groups) should be allowed to quit without repercussions. I'm leaning towards no for simplicity, as it will be more trouble than it's worth perhaps. Arguably, it makes more sense to propose a specific change for a specific worker or subset of workers.

> **Validator count** Proposal
> 
> srml-staking module already has sudo dispatchable: [`fn set_validator_count(origin, new: u32)`](https://github.com/paritytech/substrate/blob/c37bb08535c49a12320af7facfd555ce05cce2e8/srml/staking/src/lib.rs#L963)
> 
> **Suggested additional proposal?**
> 
>     * Add to capacity of Content Working Group Mint.
> 
> 
> `pub fn increase_mint_capacity(origin, additional_capacity: minting::BalanceOf<T>)`
> 
> **Migration logic from Rome:**
> We need to reset all, or some balances, however, this will disrupt all the stakes of people involved in various roles (council, validation, storage, curators, etc.) and also stakes of voters currently staking. A strategy is needed:

Not sure I understand this completely.

> Split into two tasks:
> 
>     * research:
>       
>       * investigate if its safe to modify stash and controller balances of validators,
>       * we can iterate all "known" accounts with positive balance (from members, roles, validators etc)
>         but can we iterate other accounts? balances maps are not `linked_map` maps and we do not use the account indexing feature.
>       * Can the migration be completed within target block production interval of 6s? or does it need to be split over multiple blocks...?
> 
>     * implement (if possible)
> 
> 
> If not possible, what is alternative?
> 
>     1. Artificially increase total issuance to make existing balances insignificant..
> 
>     2. make the conversion rate reflect insignificant value of issued balances.

These are clearly the easiest approaches. 
We can also try adjusting stake for an active validator and see what happens :)

**Comment by mnaamani** [comment]
> I seem to recall a couple of these parameterss are not actually read, but it still seems _easier_ to only allow proposing a new set. It will require a little more documentation perhaps, but implementation is far easier?

Correct, the following fields of the RoleParameters are not honored
```
min_actors
bonding_period
min_service_period
startup_grace_period
```
Leaving only these fields that have any affect:
```
min_stake
max_actors
reward
reward_period
unbonding_period
entry_request_fee
```
When you say easier, easier on who? Code wise its not an issue wether to update the whole set or one field at a time. The question is really on the proposer and council who need to evaluate the proposal. Is it easier to think and evaluate the change of all values together, or if there were perhaps multiple proposals each changing different fields.

I guess I would also lean towards a single proposal that updates multiple fields atomically (together).

**Comment by mnaamani** [comment]
Regarding slashing, Yes in our runtime we are not making use of the slashing terms or expose any functionality of the slashing mechanism offered by the staking module. `sudo->setBalance/forceTransfer` could work and can be turned into a proposal yes, but effectively you can only slash the member account or role account, the amount at stake which is what we would really want to slash is in the stake pool and transferring balance from it with this method is actually dangerous without updating the active stakes managed by the staking module.

So the proposal would actually need to call directly into the staking module slash() methods

**Comment by mnaamani** [comment]
> I think regardless of the rest, the rewards for the role needs to be defined when an opening is made, and enforced by the runtime. Currently, the lead can set whatever rewards he wants to when hiring.

Correct. The Lead actually sets the reward at the time of filling the roles (this is not reflected in the UI however). So if we want to set the reward at the time of hiring we will need a few changes in UI and runtime.

Regarding retro-actively updating rewards and other policy and parameter for active curators I think you raised some good points. Lets not do it, so when a curator applies they are confident the terms they are offered are not changed. So it is more like a real contract, and only a proposal targeting a specific curator to change the terms of the contract could be added later.

**Comment by mnaamani** [comment]
Regarding the minting capacity proposal, the working group has a mint with a fixed capacity at genesis. Rewards are paid out from this mint. When its capacity goes to zero rewards can no longer be paid out, so it has to be updated by adding more capacity when needed.

**Comment by mnaamani** [comment]
> `sudo->setBalance/forceTransfer` could work and can be turned into a proposal yes,

Might not be a good idea to use this, it resets the account nonce to zero, and that might open room for replay of older transactions, I would have to double check though on the latter it depends on what is covered by the transaction signature.

**Comment by mnaamani** [comment]
During my discussion with @bwhm it was suggested that the lead should also be set by the council through a proposal. The only constraint here is that the lead would have to be selected from the currently active curators, if we don't want to add a new hiring process for leads. The constraint is there if we want the lead to be a staked role, and the council shouldn't be allowed to arbitrarily pick any account and force it to stake and be the lead.

If we want this, given the current design that only the lead can open hiring positions for curators, it means we also need to add a proposal to give the council the ability to hire curators.

**Comment by mnaamani** [comment]
The simpler approach is for lead to not be staked role, and we then only need to provide two proposals to set lead and unset lead, and leaving the responsibility of hiring to the lead. The only way to punish the lead then is by firing them. For the lead to stake and earn rewards they would do it by hiring themselves in one of the curator roles.

**Comment by mnaamani** [comment]
So here is what I propose, we should discuss:
Proposals:
  - Set Lead + optionally a recurring reward
  - Unset Lead
  - Slash Curator
  - Set Curator Reward - has no side effects on active curators
  - Set Curator Staking Policies - has no side effects on active curators

Required working group changes:
update add_curator_opening()
   - lead doesn't set reward or staking policies
   - reward and staking policies are captured from values set by council into the opening

update fill_opening()
    - does not accept a reward argument
    - creates recurring reward based on value stored in the opening

- add proper method for slashing a curator's stake
- add slashing events handler to remove curator from role if stake goes to zero?
