### ISSUE TITLE
Fee model verification methodology

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2124]
Take a benchmarked runtime and any other required information as given,

1. For a specific proposed weight price `w` (s/JOY) and byte price `f` (bytes/JOY), by what methodology to classify this combination as acceptable or not acceptable.
2. For two such combinations`(w_1,f_1)` and `(w_2,f_2)`, by what methodology can we order them to say `(w_1,f_1) >=(w_2,f_2)` in terms of desirability.

Without this it seems hard to come up with suitable tools of analysis for determining such prices.

**Comment by conectado** [comment]
I assume that there is a function `p: Fee -> Price` which converts a fee in JOY to a real price and a function `d: Price -> Saturation` that takes a real price for an extrinsic and converts it to saturation(a number between 0 and 1 representing the block saturation, 0 completely empty and 1 with no more weight to add another extrinsic). This assumes that we can calculate the saturation of a block given the price of a single extrinsic(every other extrinsic would logically follow)

1. With these functions we want a `w` and `f` such that `d(p(f + w))=0.25` and this function(as long as `d` and `p` are bijective) would fully determine `f + w` which would give us the range of acceptable `w` and `f`.
2. Then we need to check the different prices for our extrinsics given all `w` and `f` valid combinations to see which makes more sense. But I think that a way to choose an acceptable `f` would be for it to be as small as it could possibly be still accomplishing an anti-spam mechanism. And with that `f` chosen `w` would be fully determined.

**Comment by bedeho** [comment]
Here is what I wrote down today as a way to addressing 1 and 2, but I think it can be generalized to support multiple extrinsics and non-base fees by introducing incidence distributions, and then optimizing over expectations. So you would need a probability distribution for each extrinsic, which is parametrised in some cost parmeters, to reflect how many such calls one gets in a single block.

**What do you think?**

## Premise

- Constant block weight (s): `MaximumBlockLength`.
- Constant block length (bytes): `MaximumBlockWeight`.
- Constant fees (JOY): `NextFeeMultiplier = 1`
- Only one extrinsic: consant weight `W` (s) and length `L` (bytes).
- JOY supply at genesis: `BASE`
- USD value of JOY supply: `CAP`
- Fee `final_fee` of extrinsic `tx` is computed by

```
final_fee = [L * LENGTH_FEE + WeightToFee(W)] * NextFeeMultiplier
```

where 
- `LENGTH_FEE` is the constant price (JOY) of a byte of block space.
- `WeightToFee` is the homgenous linear mapping of weight to fees (JOY), so `WeightToFee(x) = W_C*x`, where `W_C` is called the weight coefficient.

## How to set `W_C`,`LENGTH_FEE`

### Methodology

Our ideal `W_C`,`LENGTH_FEE` minimizes the squared error between actual block weight and `0.2*MaximumBlockWeight`, subject to 

a) the block length constraint, and 
b)`W_C, LENGTH_FEE > 1` (nominal price floor of blockchains).

### Analysis

Let `BW(w,l)` denote the actual block weight, as a result of user behaviour facing system constraints & costs, when the weight coefficient is `w` and the length fee is `l`. We have that

`BW(w, l) = D(w,l)*W`

where `D(w,l)` denotes the number of transactions users will want to submit in one block period when the weight coefficient is `w` and the length fee is `l`.

Hence we are trying to find `w,l > 0` minizing


`[BW(w, l) - 0.2*MaximumBlockWeight]^2 = [D(w,l)*W - 0.2*MaximumBlockWeight]^2` 

subject to 

`D(w,l) <= MaximumBlockLength/L`

Plugging in specific parametric forms for `D` should allow analytical solution using Lagrange multiplier or similar. Empirical `D` can be solved using numerical solution. `D` should at any rate be parametric in `BASE` and `CAP` so as to allow adjustment to satisfy (b) independently of all other concerns.

**Comment by bedeho** [comment]
I meant to call `f` byte price, which would make `b` a better name, not fee price :sweat_smile:.

**Comment by bedeho** [comment]
Actually `D` is clearly not smooth or even continous here, as its #transactions, so the only solution method will be numerical....or I guess, perhaps its ok, 1.5 transactions? it sort of make sense? may be easier to just allow it.

**Comment by bedeho** [comment]
> With these functions we want a w and f such that d(p(f + w))=0.25 and this function(as long as d and p are bijective) would fully determine f + w which would give us the range of acceptable w and f.

Perhaps I am missing something, but how would I extend this method to work for a case where I have two distinct extrinsics, with distinct weights and expected usage frequencies? In this case, it would seem one needs two distinct demand functions, and no singular w,f combination should be expected to yield a solution that yields 0.25 utilization. As the number of extrinsics grows, it shuold be even less the case. So one would need to try to minimize the error. 

Is this correct?

**Comment by conectado** [comment]
> Here is what I wrote down today as a way to addressing 1 and 2, but I think it can be generalized to support multiple extrinsics and non-base fees by introducing incidence distributions, and then optimizing over expectations. So you would need a probability distribution for each extrinsic, which is parametrised in some cost parmeters, to reflect how many such calls one gets in a single block.
> ...

Amazing analysis 🤯 I have a few questions.

When you say 

> subject to
> 
> `D(w,l) <= MaximumBlockWeight/L`

That would be  `D(w,l) <= MaximumBlockWeight/W` right?

Also, I agree regarding this :
> Actually D is clearly not smooth or even continous here, as its #transactions, so the only solution method will be numerical....or I guess, perhaps its ok, 1.5 transactions? it sort of make sense? may be easier to just allow it.

I think it's better to allow fractional number of transactions, specially since  with the dynamic part of the weight we just need a sensible approximation to `w` and `l`. 

~~And having this we could re-write the problem as an equation instead of a minimization:~~

This was wrong as now thinking it through if we have multiple extrinsics this wouldn't work

**Comment by bedeho** [comment]
> That would be D(w,l) <= MaximumBlockWeight/W right?

No it was actually meant to be `D(w,l) <= MaximumBlockLength/L`, sorry! will fix.

> is there a reason why it should be better to leave it as a minimization

I think I was thinking that its not going to work with multiple extrinsics, see this https://github.com/Joystream/joystream/issues/2124#issuecomment-770990401

**Comment by conectado** [comment]
> > With these functions we want a w and f such that d(p(f + w))=0.25 and this function(as long as d and p are bijective) would fully determine f + w which would give us the range of acceptable w and f.
> 
> Perhaps I am missing something, but how would I extend this method to work for a case where I have two distinct extrinsics, with distinct weights and expected usage frequencies? In this case, it would seem one needs two distinct demand functions, and no singular w,f combination should be expected to yield a solution that yields 0.25 utilization. As the number of extrinsics grows, it shuold be even less the case. So one would need to try to minimize the error.
> 
> Is this correct?

I think the way to generalize this to multiple extrinsics would be considering `d` to be a function over the price of the whole block instead of a single extrinsic so the equation would be 
`d(E[x_1]*p_1(f + w) + ... + E[x_n]*p_n(f+w))=0.25` 
where `x_i` is the random variable that is related to the incidence distribution of the ith extrinsic and `p_i` is the price of the ith extrinsic. (`x_i` would also depend on f and w, so I think it would be a little more complicated and we should also have a probability distribution over the length of the parameters)

The only advantage I see of working like this is that the "ideal" price could be worked out with root-finding algorithms instead of minimization and then we could use minimization for finding the solution for the equation `E[x_1]*p_1(f, w) + ... + E[x_n]*p_n(f, w)` = ideal price. Where at least we know that `p_i` is a sum of 2 linear functions. But I'm not sure this is much of an advantage.

**Comment by bedeho** [comment]
It seems the semantics of `d:USD -> [0,1]` has changed in some non-backwards compatible way from the first post to the one above? Above `d` maps the USD cost of doing a single given transaction, which makes sense to me, but in this prior post its input seems to be something like "the expected total expenditure from the transaction mix that users are willing to make from these prices", however, that itself is something that comes from demand? So it seems to presume some underlying demand analysis. Is this right?

One thing that just looks very suspicious is that this analysis seems to guarantee that there is always a singular `w,l` combination that will give the exact desired saturation rate even if you have millions of heterogenous transactions, in terms of length and weight, this seems wrong.

**Comment by bedeho** [comment]
> One thing that just looks very suspicious is that this analysis seems to guarantee that there is always a singular w,l combination that will give the exact desired saturation rate even if you have millions of heterogenous transactions, in terms of length and weight, this seems wrong.

I think this suspion is actually misplaced if we assume, as we agreed, that `w,l` are continous inputs to continous functions, then there should always be solutions as long as those functions are (monotonically) increasing and start sufficiently low.

> E[x_1]*p_1(f + w) + ... + E[x_n]*p_n(f+w)

Shouldn't the spending on the ith extrinsic be something like `E(x_i [w_i*w + f_i*f])` where

- `x_i`: random variable for number of times the ith extrinsic will occur in a block.
- `w_i`: (base) weight of ith extrinsic
- `f_i`: length of ith extrinsic in block

and `x_i` will itself depend on `w_i,f_i,w,f` and other inherent properties about utility of this transactioin type.

**Comment by conectado** [comment]
> It seems the semantics of `d:USD -> [0,1]` has changed in some non-backwards compatible way from the first post to the one above? Above `d` maps the USD cost of doing a single given transaction, which makes sense to me, but in this prior post its input seems to be something like "the expected total expenditure from the transaction mix that users are willing to make from these prices", however, that itself is something that comes from demand? So it seems to presume some underlying demand analysis. Is this right?

Yes, you're right, the semantics of the function changed in that way and it assumes that the demand can be a function of the price of the block which in turn depends on the a previous demand analysis.

So I think this generalization wouldn't work.

**Comment by conectado** [comment]
> > E[x_1]*p_1(f + w) + ... + E[x_n]*p_n(f+w)
> 
> Shouldn't the spending on the ith extrinsic be something like `E(x_i [w_i*w + f_i*f])` where
> 
>     * `x_i`: random variable for number of times the ith extrinsic will occur in a block.
> 
>     * `w_i`: (base) weight of ith extrinsic
> 
>     * `f_i`: length of ith extrinsic in block
> 
> 
> and `x_i` will itself depend on `w_i,f_i,w,f` and other inherent properties about utility of this transactioin type.

Yes, but I was assuming that `w_i`, `f_i`, `w` and `f` are independent in the sample space of `x_i`, then the cost in tokens of the ith  extrinsic should be 
```
E[x_i * (f_i * f + w_i * w)] = E[x_i] * E[f_i * f + w_i * w] = E[x_i] * (f_i * f + w_i * w)
```
And I'm assuming that the price function is a linear mapping:
```
p(E[x_i] * (f_i * f + w_i * w)) = E[x_i] * p(f_i * f + w_i * w)
```

**Comment by bedeho** [comment]
> E[x_i * (f_i * f + w_i * w)] = E[x_i] * E[f_i * f + w_i * w] = E[x_i] * (f_i * f + w_i * w)

Certainly this holds, because w_i, f_i, w and f are just non-stochastic constants, and expectation is linear operator. My point is rather that I am not sure how your formulation `p_i(f + w)` relates to `(f_i * f + w_i * w)` here?

> And I'm assuming that the price function is a linear mapping:

This price function is just converting between fiat and JOY, so p(amount_of_JOY) = amount_of_JOY * JOY_to_USD_exchangerate ?

**Comment by conectado** [comment]
> > E[x_i * (f_i * f + w_i * w)] = E[x_i] * E[f_i * f + w_i * w] = E[x_i] * (f_i * f + w_i * w)
> 
> Certainly this holds, because w_i, f_i, w and f are just non-stochastic constants, and expectation is linear operator. My point is rather that I am not sure how your formulation `p_i(f + w)` relates to `(f_i * f + w_i * w)` here?

That was a mistake I meant to write `p_i(f_i * f + w_i * w)`

> > And I'm assuming that the price function is a linear mapping:
> 
> This price function is just converting between fiat and JOY, so p(amount_of_JOY) = amount_of_JOY * JOY_to_USD_exchangerate ?

Yes.

**Comment by bedeho** [comment]
Is `p_i` the same function `p`, or alternatively scaling factor `amount_of_JOY`, for all `i`?

**Comment by conectado** [comment]
Yes, that too, I don't know why I wrote `p_i`

**Comment by conectado** [comment]
> Let `BW(w,l)` denote the actual block weight, as a result of user behaviour facing system constraints & costs, when the weight coefficient is `w` and the length fee is `l`. We have that
> 
> `BW(w, l) = D(w,l)*W`
> 
> where `D(w,l)` denotes the number of transactions users will want to submit in one block period when the weight coefficient is `w` and the length fee is `l`.
> 
> Hence we are trying to find `w,l > 0` minizing
> 
> `[BW(w, l) - 0.2*MaximumBlockWeight]^2 = [D(w,l)*W - 0.2*MaximumBlockWeight]^2`
> 
> subject to
> 
> `D(w,l) <= MaximumBlockLength/L`

Trying to put things together and generalize the quoted analysis.

We could have random variables `D_i` that denote the number of transactions users will want to submit in one block period for the ith extrinsic and constants `W_i` being weight for the corresponding extrinsic(assuming weight is constant).

Also, the distribution function related to `D_i` depends on `w` and `l`

And to abbreviate I will use `MaximumBlockWeight = MBW`

We could minimize the following expression to find `w` and `l`:

```
(E[D_0 * W_0 + ... + D_n * W_n] -  0.2*MBW)^2 = (E[D_0] * W_0 + .. + E[D_n] * W_n - 0.2 * MBW)^2 
```
Also, since it seems that as `w` and `l` limits to 0 `E[D_0 * W_0 + ... + D_n * W_n]` goes up to MBW(when bounded) and as `w` and `l` limits to infinite `E[D_0 * W_0 + ... + D_n * W_n]` goes to 0. And assuming that the distribution functions are continuous in `w` and `l` we can assert that the minimums for `(E[D_0] * W_0 + .. + E[D_n] * W_n - 0.2 * MBW)^2 ` are the roots of

```
f(w, l) = E[D_0] * W_0 + .. + E[D_n] * W_n - 0.2 * MBW
```

So, if we have some distribution function for the random variables `D_i` we can find the roots of that function to determine all possible `w`s and `l`s

Do you think this would work?

**Comment by conectado** [comment]
> ...
> ```
> f(w, l) = E[D_0] * W_0 + .. + E[D_n] * W_n - 0.2 * MBW
> ```
> 
> So, if we have some distribution function for the random variables `D_i` we can find the roots of that function to determine all possible `w`s and `l`s
> 
> Do you think this would work?

Maybe to simplify the minimization we could start by adding this assumption: 

The distribution function`d_i(x, w, l)` for `D_i` has the form `g_i(x) * h_i(w, l)` meaning that the price of the extrinsic is just a scaling factor to the occurrence distribution. With that `E[D_i] = G_i * h_i(w, l)` where `G_i` is a constant.
