### ISSUE TITLE
Feature request: CLI cancelOpening

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2136]
Currently when someone makes a duplicate opening or an opening with a mistake, or for some other reason the opening needs to be cancelled they have to use the CLI and then perform the command `working-groups:startReviewPeriod` and then `working-groups:fillOpening` and then select no workers to "cancel" the opening.

To make cancelling an opening easier, it would make sense to have a `cancelOpening` command available that simply cancels an opening (with confirmation Y/N) rather than going through several steps.

**Comment by bedeho** [comment]
Very interesting, what do you think @shamil-gadelshin how much complexity does this add?

**Comment by shamil-gadelshin** [comment]
Not much, and it should be relatively easy. The runtime already supports this operation. And the CLI has all the necessary infrastructure code to implement this new command.

**Comment by bedeho** [comment]
Great, thanks, made an issue to add it here https://github.com/Joystream/joystream/issues/2142.
