### ISSUE TITLE
Idea: Burn tokens proposal

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2137]
For some reason or another, there may be cases where users want to burn tokens for symbolic or other reasons such as being overpaid for a role, or having received payments for a role which they were unable to fulfill for some reason. For reasons of reputation users might want to elect to burn the tokens they had received.

For this proposal type, a user would submit some amount of tokens, which the council can then vote to accept or reject and the tokens held in the proposal would be burned from issuance if the proposal were accepted.

One other solution for this is to send tokens to a "burn address" but these tokens are never actually burned from issuance (see Bitcoin's null address for reference: https://www.blockchain.com/btc/address/1111111111111111111114oLvT2).

Other possible scenarios for use:

* Tokens issued for competitions that never worked out or had to be cancelled for some reason
* Tokens issued for a spending proposal that the recipient wasn't able to deliver on

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202171856803418) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
A proposal seems very for this, no need to get the council involved. Simply sending to a made up address is a bit rough, as it does not update the underlying issuance of the token, and people can end up using different burn addresses, so you cant even keep track of who burned what, when.

An explicit `burn`type of extrinsic which also updates the issuance seems like the right fit.

I am not totally solved by the urgency or severity of need for this, but its also likely quite easy to add. The question is where to add it. Seems like you should not really require someone to have a membership to do this even. We could add a new module for just this, but that seems like serious overkill.

Any ideas @shamil-gadelshin ? also, am I right that something like `Currency::slash` does update the issuance?

**Comment by mochet** [comment]
> I am not totally solved by the urgency or severity of need for this, but its also likely quite easy to add. The question is where to add it. Seems like you should not really require someone to have a membership to do this even. We could add a new module for just this, but that seems like serious overkill.

I don't really think it is urgent, but maybe it is something that can be solved on mainnet if it isn't feasible right now. I do think there are some interesting use cases for it, particularly for users who want to maintain their reputation if they fail for some unforeseen reason to achieve what they had initially promised or been paid to do.

The idea for this came about because of the huge blur between users being paid for work they promise to do versus what they have already done, and having a feature to factually burn tokens would hopefully promote a system where users who are honest with the community are rewarded for their integrity.

Since almost every role on the platform involves some form of reputational stake at play (besides tokens) having a function to allow users to burn tokens might prove to be useful in some scenarios.

The idea that it could be solved via extrinsic instead of involving the council sounds a lot more sensible!

**Comment by shamil-gadelshin** [comment]
Yes, the `Currency::slash()` function affects the total issuance.

Possible implementation of the proposed `burn()` extrinsic :
1. We could add it to the `membership` module (with or without requiring actual membership to invoke it).
2. We could also promote `common` code module to the pallet and introduce the extrinsic there. 
3. Add it to a new `misc` pallet (or joystream-system).
4. We could introduce the first [custom RPC-call](https://substrate.dev/recipes/custom-rpc.html) in our system. This API looks stable enough to survive multiple runtime upgrades without a need for a hard fork.

**Comment by bedeho** [comment]
Great  clarificatoin @shamil-gadelshin. Number 3 seems most attractive, but do we have more we could put in this sort of `joystream-utility` pallet? Does anything come to mind?

**Comment by shamil-gadelshin** [comment]
We could move "alien extrinsics" from the `codex` pallet:
- execute_signal_proposal
- execute_runtime_upgrade_proposal
- update_working_group_budget

**Comment by bedeho** [comment]
Ok, thats not a bad idea, lets do it! Can you create an isssue for all of this and assign to @conectado  ?

**Comment by shamil-gadelshin** [comment]
Here it is: https://github.com/Joystream/joystream/issues/2168

**Comment by shamil-gadelshin** [comment]
Merged in Olympia branch.

**Comment by mochet** [comment]
Wasn't this already solved via extrinsic `joystreamUtility.TokensBurned`?
It's on Olympia and I just tested it and it seemed to work:
https://polkadot.js.org/apps/#/explorer/query/0x0bc463f00ff050a09b83aeb41e79abb4f57a316e3f3786194aec98f110cb8851

**Comment by mochet** [comment]
Closed as this was implemented via extrinsic `joystreamUtility.TokensBurned`

**Comment by bedeho** [comment]
That is not correct, that is not a proposal, trying to achieve the same outcome using this would require a minting of the tokens, placing them in account of custodian, and then burning. This is not equivalent, and in particular destroys integrity of tokenomics history.

**Comment by mochet** [comment]
closed because this is already being done in `luxor` with this issue: https://github.com/Joystream/joystream/issues/3494
