### ISSUE TITLE
Add support for validator payout to the CLI

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#2146]
Since pioneer seems to limit payouts to 20k being able to automate payouts for example with a cronjob saves validators time.

**Comment by mochet** [comment]
Not sure if you're aware, but you can actually do the payouts via extrinsic submission: https://github.com/Joystream/helpdesk/tree/master/roles/validators#claiming-one-era-at-the-time

But this is limited to one era at a time, which would probably result in many transactions being used for this. I'm not sure how to do bulk claims via extrinsics, but it may be possible.

**Comment by traumschule** [comment]
Yes, there is a better tool: https://git.joystreamstats.live/Operations/substrate-auto-payout

Closing this as WONTFIX.
