### ISSUE TITLE
CLI UX/UI issue: Opening issues with spacebar vs enter

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2150]
Example: https://testnet.joystream.org/#/forum/threads/205?replyIdx=2

I've run into the same issue myself previously. The instructions do mention to use spacebar to select worker(s), but the CLI really needs some form of confirmation of which workers were selected (ex. "WARNING: you have selected no workers for this opening") before extrinsic submission.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703611565816) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
Thanks @mochet,
Will add this to the list!
