### ISSUE TITLE
Idea: Hashtags as payment channels

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2163]
There are starting to be a lot of interesting new ways being developed on Joystream in which users can contribute funding or spending towards other users, channels or groups.

This includes:
* Runtime DAOs
* Bounties

For example, rather than just letting users browse through parts of Joystream and finding bounties or DAOs they are interested in funding which may require navigating many areas of the platform, content creators, forum users and user profile pages could freely utilize hashtags, which can link to a small page describing the purpose of the funding (even validators could modify their validator names and council members could raise awareness of specific hashtags)

Maybe something like #fundtheforumupgrade -- when a user clicks this, they would not only see other tagged content, but have an option for contributing finance towards the bounty address for the forum upgrade.

This would make it very easy for runtime DAOs and bounties in particular to target widespread awareness of pressing finance requirements. If users can place hashtags, and also use them as payment channels across a broad range of areas on Joystream it would allow "needy" users to very easily attract recognition of the project they're hoping to get funding for.

If it is possible to then measure how many tokens flow through each hashtag, then you get some very interesting data and can essentially build a hashtag marketplace.

To be clear, users are not paying to list content or to post to a hashtag, they are just using it to freely advertise a payment channel.

Besides this there are numerous social and charitable causes that exclusively employ the usage of hashtags. If users can send tokens to "causes" or "projects" rather than just other users like typical P2P transactions, there could be some very interesting use cases.

If this was ever implemented, alongside something like Sprocket (https://github.com/Joystream/joystream/issues/1966) it would easily turbocharge the usage of hashtags on the platform.

**Comment by bedeho** [comment]
Closing as out of scope.
