### ISSUE TITLE
Init new working group configs on runtime upgrade

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#2164]
I overlooked one issue in https://github.com/Joystream/joystream/pull/2153 with respect to introducing new working groups.
Since `Sumer` is a runtime upgrade the initial config settings for the new working groups needs to be set in the `OnRuntimeUpgrade` implementation, see example here for when we introduced new content working group in babylon runtime: https://github.com/Joystream/joystream/blob/master/runtime/src/runtime_api.rs#L62

So we need to add initialization for Gateway and Builders groups here: https://github.com/Joystream/joystream/blob/sumer/runtime/src/runtime_api.rs#L61

**Comment by iorveth** [comment]
closed by https://github.com/Joystream/joystream/pull/2170
