### ISSUE TITLE
Customise Curator groups permission model for sumer

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#2165]
## CuratorGroups permission model

The current CuratorGroups permissions model in the new content directory is as follows:

- The content working group lead can create and delete curator groups.
- The lead can add workers from the content working group into one or more curator groups.
- Once a worker is in a group they have permission to censor and uncensor Channels and Videos.
- A CuratorGroup can own a channel. Any curator from that group can create a new channel for the group, and subsequently update it.
- A curator in one group cannot censor channels or videos owned by other curator groups.
- Lead can manage curatorgroup owned channels. (need to double check this one!)

This is decent but a bit limited. The grouping is really only for the purpose of managing ownership of channels. 

## Proposal
Give the lead more flexibility in organizing their workers responsibilities.

#### Each curator group will have a set of explicit permission which can only be updated by the lead:

- can_create_channel_categories
- can_create_video_categories
- can_censor_in_channel_categories: [ ... array or category ids ...]
- can_censor_in_any_channel (except other curatorgroup owned channels)
- can_move_channels_between_categories
- can_delete_channel_categories? - or restrict to lead
- can_delete_video_categories? - or restrict to lead
- can_create_group_channel

**Comment by bwhm** [comment]
Some questions here:
- what does `can_censor_in_channel_categories` and `can_censor_in_any_channel` mean?
- can the lead (and/or other curators) gain the permission to delete channels and videos not owned by the group?
- can he lead (and/or other curators) gain the permission to delete or update assets?
- my two cents on `can_delete_video_categories` and `can_delete_channel_categories` is that it should probably be restricted to lead, but wouldn't be a big problem if it's not.

I guess I could check the implementation for these, but:
- is channel/video category required? If so, what happens if that category gets deleted?
- can a channel/video have more than one category?
- will the curator pass their group id in the extrinsic, or does the runtime check all the groups for their `curatorId`?

In general, I like the idea that curators have no permissions by default. It would be _nicer_ if it could be set by `fill_opening`, but not important enough to make the change.

**Comment by mnaamani** [comment]
> Some questions here:
> 
>     * what does `can_censor_in_channel_categories` and `can_censor_in_any_channel` mean?
`can_censor_in_any_channel: boolean` if set to true would allow curators to censor any channel in what-ever ChannelCategory it is in (and all videos under that channel individually)

`can_censor_in_channel_categories` if latter permission is set to false, censoring would be restricted to channels under this list of categories.

>     * can the lead (and/or other curators) gain the permission to delete channels and videos not owned by the group?
> 
Currently No.
>     * can he lead (and/or other curators) gain the permission to delete or update assets?
> 
Currently only the channel owner can update and delete channels, including their assets.
However sudo and lead can delete assets of a channel which the owner has deleted.

>     * my two cents on `can_delete_video_categories` and `can_delete_channel_categories` is that it should probably be restricted to lead, but wouldn't be a big problem if it's not.
> 
That does make sense we can update it easily in https://github.com/Joystream/joystream/pull/2158
> 
> I guess I could check the implementation for these, but:
> 
>     * is channel/video category required? If so, what happens if that category gets deleted?
> 
When channels and videos are created or updated, the category is specified in the protobuf metadata, so it is not validated by the runtime. So this of course means that one could set an incorrect or non-existent category and it is upto the UI to handle it. However this allows the lead to create and delete categories freely. ie. they will not be blocked from deleting a category just because a video or channel is in that category.

>     * can a channel/video have more than one category?
> 
Currently No. This can be easily changed.

>     * will the curator pass their group id in the extrinsic, or does the runtime check all the groups for their `curatorId`?
> 
Currently the "actor" argument in the extrinsic requires to specify the GroupId and CuratorId. This is important because the curator could be in more than one group.

> 
> In general, I like the idea that curators have no permissions by default. It would be _nicer_ if it could be set by `fill_opening`, but not important enough to make the change.

Yes it does seem good to allow some buffer time between hiring and deciding which group to add the worker into.

Nice idea to have a post fill_opening hook to do some work like that. I agree we should avoid making any such changes to working group pallet.

**Comment by mnaamani** [comment]
A simpler representation for censoring permissions would be:
```rust
enum CanCensor {
     No,
     InSpecificCategories(Vec<ChannelCategoryId>),
     Any,
}
```

Finally, does the lead really need to delete curator groups? ref https://github.com/Joystream/joystream/pull/2158#issuecomment-781960074

**Comment by bwhm** [comment]
> Currently only the channel owner can update and delete channels, including their assets.
> However sudo and lead can delete assets of a channel which the owner has deleted.

I think deleting an entire video (thereby also all the assets associated with it) and a channel (deleting all content and assets) _should_ be possible somehow. I don't know if it should be allowed by lead, or the council, but one of them seems required? Is that what happens when the owner deletes? If so, it's enough to add more allowed origins. Could be added later as well.

> - can a channel/video have more than one category?
> > Currently No. This can be easily changed.

It seems pretty reasonable to assume a channel especially, but also a playlist and perhaps single video should be able to set more than one. I'd support making this an array with max 3 or something!

> Currently the "actor" argument in the extrinsic requires to specify the GroupId and CuratorId. This is important because the curator could be in more than one group.

I asked because of the CLI, so good to know!

> Finally, does the lead really need to delete curator groups?

Probably not, as they can change the `curators` and permissions instead. Is a curator that gets fired is removed from the group, or are they simply not able to use that ID anymore?


Thanks for the other replies, that clarifies things :)

**Comment by mnaamani** [comment]
> I think deleting an entire video (thereby also all the assets associated with it) and a channel (deleting all content and assets) _should_ be possible somehow. I don't know if it should be allowed by lead, or the council, but one of them seems required? Is that what happens when the owner deletes? If so, it's enough to add more allowed origins. Could be added later as well.

Deleting of a channel does not automatically delete the assets in storage. The reasons are 
1. I decided against tracking assets in the content directory just because it made the code overly complicated and the channel owner is incentivized to manually delete assets they no longer use because of the Quota/Limits per channel.
2. We don't support iteration of the content in the data_directory and we decided against making further changes.. ref: https://github.com/Joystream/joystream/issues/2172

For this reason the lead and sudo have an extrinsic available to delete assets but only after a channel has been deleted where the owner didn't already delete assets. (To get list of assets that can be deleted this way will done by a query to the query-node)

> It seems pretty reasonable to assume a channel especially, but also a playlist and perhaps single video should be able to set more than one. I'd support making this an array with max 3 or something!

Can add for Channels and Videos. In current design for playlists there is no separate category, since a playlist lives in a channel it effectively inherits that same category.

> Is a curator that gets fired is removed from the group, or are they simply not able to use that ID anymore?
I don't think they are removed from group automatically (I will double check) but their id becomes in-effective because the `Worker` is removed from the working group.

I also think its not necessary for lead to be able to delete a group. And if we are good with this then I will also remove ability to delete channels at all.

**Comment by mnaamani** [comment]
I think this was a great discussion.
For Sumer shall we keep it simple for now?

Apply following changes:
 - update the metadata to support multiple categories
 - remove support for deleting curator groups (and in turn remove support for deleting channels ~and videos~)

**Comment by bedeho** [comment]
We decided to review more complex curation permissions for a later release with more data at hand.

**Comment by bedeho** [comment]
Superceeded by https://github.com/Joystream/joystream/issues/2760
