### ISSUE TITLE
Init data_rectory on runtime upgrade

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#2171]
Similar to https://github.com/Joystream/joystream/pull/2170 the new storage values for the data_directory:

```
Quotas
QuotaSizeLimitUpperBound
QuotaObjectsLimitUpperBound
GlobalQuota
UploadingBlocked
```
need to be initialized on runtime upgrade.

The `DataObjectByContentId` map also needs to be migrated or all its elements deleted since the `struct DataObject` has been augmented (`owner` field has been changed from a `MemberId` to a `StorageObjectOwner`).

`DataObjectByContentId`  ->  `T::ContentId => Option<DataObject<T>>`

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2170
