### ISSUE TITLE
There is no stored relation between an opening and an application in the working group

### ISSUE THREAD

**Issue by conectado** [Joystream/joystream#2216]
## The problem
When a member applies for a given opening the [application doesn't store any information about the opening originally applied to](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/working-group/src/lib.rs#L454-L460).

This means, that later on, when [filling the opening](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/working-group/src/lib.rs#L489-L493) there is no way to check if a given application is related to the opening that is being filled. **This also means that an opening can be filled by someone with less or no stakes than the required for the opening**

## Possible solutions
* Store in `Opening` the current applicants. This would make it easier(`O(number_of_applicants_for_opening)`) to check that a member isn't applying twice to the same opening as expected [here](https://github.com/Joystream/joystream/issues/2196#issuecomment-784189158). However, it would also be harder (`O(number_of_applicants_for_opening)`) to check if a set of applications are valid for a given opening.

* Store in the `Application` the corresponding opening. This would make it easier(`O(size_of_set)`) to check if a set of applications are valid for a given opening. But harder(`O(number_of_applications_in_storage)`) to check that a member isn't applying to the same opening twice.

**Comment by bedeho** [comment]
1. Very nice observation, I wonder how we could have missed this. I think @bwhm even checked for this a long time ago.
2. We must not limit the number of applicants that can apply, hence add `Application::opening_id`.
3. As for preventing a member for applying more than once, no need when we directly deal with making leaving applications idle costly for everyone.

**Comment by shamil-gadelshin** [comment]
Our first design contained this relation, but we decided to remove it during the migration from the `bureaucracy` pallet. We thought that there is no harm with several applications from the same user.

**Comment by bwhm** [comment]
>     1. Very nice observation, I wonder how we could have missed this. I think @bwhm even checked for this a long time ago.

I believe I found that (at least that you could hire applicants that had withdrawn their application), but I can't find an issue about it.

I think this goes all the way back to when we launched the first working group (Content Curators only), but as we already then knew we would replace that with a Working Group 2.0, I forgot about it :(

Great find @conectado!

If we are making changes to the working group, I'd say that we should decide on whether #2197 should be dealt with on the runtime. Not urgent, and perhaps not needed, @bedeho?

**Comment by bedeho** [comment]
> If we are making changes to the working group, I'd say that we should decide on whether #2197 should be dealt with on the runtime. Not urgent, and perhaps not needed

This work is for a much different runtime, so its unrelated.
