### ISSUE TITLE
Storage provider host metadata for Sumer

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2252]
# Background

In `Sumer` the working group workers have a raw storage fields for putting metadata

https://github.com/Joystream/joystream/blob/sumer/runtime-modules/working-group/src/lib.rs#L322

using new extrinsic `update_role_storage`

https://github.com/Joystream/joystream/blob/sumer/runtime-modules/working-group/src/lib.rs#L404

This will be used for two purposes

1. Storage provider workers will hold the URL for their storage nodes.
2. Gateway operators will hold the URL for their Atlas instance.

We want Atlas to be able to use 1 in order to lookup storage providers to interact with, rather than the current extremely complex IPNS based solution, however, Atlas current is not well equipped to directly read storage state, hence they need the query node to support this. 

This is a temporary requirement, as the new storage system will surely require revising this.

The gateway operator information is not relevant to the proposal below.

# Proposal

Introduce a simple standalone entity for storage providers, something like this in the input schema

```graphql
@entity StorageProvider {
 id: ID!
 metadata: String!
 }
 ```
 
 Mappings create and destroy instance by looking at workers getting hired & fired from the storage working group, and `metadata` field is updated by looking at `WorkerStorageUpdated`.

**Comment by ondratra** [comment]
Watching for metadata update as well as a user entering/leaving storage working group has been implemented. `DataObject` entity, which is basically an asset representation in query node, now has a relation with a new `StorageProvider` entity.

A question remains, what should happen when a storage provider is leaving the storage working group (either voluntarily or is kicked out) with `DataObject`s that are associated with a provider. Should all data objects provided be deleted and an asset availability set to `INVALID`, or is there an algorithm for selecting the next storage provider hosting the content (if there exists one)? Or something entirely else should happen?

**Comment by kdembler** [comment]
I think that other storage providers should have the data object repliacated so I certainly wouldn't go as far as deleting the data object. I guess the query node could just keep the status as `ACCEPTED` but not provide a storage provider relationship. In that case Atlas can just try some random provider

**Comment by ondratra** [comment]
I suspect there might be an edge-case situation when a storage provider accepts content, but he leaves the storage working group before it can be fully replicated to others. That is likely the only situation when complete invalidation of `DataObject`s might be needed.

**Comment by bedeho** [comment]
It is quite right that storage providers may leave, and so we probably want to reflect that in the corresponding entity, for example by having a field `is_present: Boolean`. This will allow anyone to only fetch providers that are still around. Its not a problem that there will be a reference to such a provider, with `is_present == false`, from some `DataObjects`, because all stroage providers are supposed to replicate all objects, not just the liaison. Hope that answers the question.

**Comment by kdembler** [comment]
I think we can close this @ondratra?

**Comment by ondratra** [comment]
Yes, we can.
