### ISSUE TITLE
The `memberIdByHandleHash` storage query returns `0` for not-matched handle

### ISSUE THREAD

**Issue by jodator** [Joystream/joystream#2257]
To implement a transaction for creating a member I wanted to query the node to check if a member `handle` was already registered.

The first approach was to query for a member id by handle hash: `api.query.members.memberIdByHandleHash`. But this is always returning `0`. Taking that member id starts from `0` I can't check using the above query if the member exists or not.

Instead I must issue another query to get the existing member details and compare the member hash. The example steps, should be as follows:

```javascript
import { blake2AsHex } from '@polkadot/util-crypto'

const handle = 'alice'
const handleHash = blake2AsHex(handle)

// The potentialMemberId is 0 even though there's no 'alice' member
const potentialMemberId = await api.query.members.memberIdByHandleHash(handleHash)

const existingMember = await useObservable(api.query.members.membershipById(potentialMemberId || 0)

// Final check
const isHandleRegistered = existingMember?.handle_hash === handleHash
```

I'm running the joystream node from the `olympia` branch. The node was built from cf694391840a97251dd6e1980681a05cbb1b9a30 commit.

I'm running the node in development mode:

```shell
./target/release/joystream-node --dev --tmp
```

**Comment by Lezek123** [comment]
As a workaround you could use `.size()` query instead, ie.:
```
const size = await api.query.members.memberIdByHandleHash.size(handleHash)
const isHandleRegistered = size > 0
```

The `.size()` query will return the actual size of the stored object, which will always be `> 0` if there is a value under given key in the mapping, while the standard query will in that case just return a default value (in this case `MemberId(0)`)

**Comment by jodator** [comment]
> The `.size()` query will return the actual size of the stored object, which will always be `> 0` if there is a value under given key in the mapping, while the standard query will in that case just return a default value (in this case `MemberId(0)`)

Thanks! It's sufficient for my needs.

**Comment by bedeho** [comment]
Great, closing.
