### ISSUE TITLE
Bug: Pioneer v1 text wrapping

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2264]
In certain situations, the forums do not wrap text (such as on bullet points)
ex: https://testnet.joystream.org/#/forum/threads/333?replyIdx=3

It would be useful if this is a small fix to have it looked at

**Comment by traumschule** [comment]
This could be mainly a markdown issue which joins lines with only one newline. To start a new paragraph two consecutive newlines are necessary.
