### ISSUE TITLE
Idea/improvement: WG "job title"

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2273]
Currently, workers are hired by a lead and presented in a flat format on Pioneer.

There have been use cases recently that have surfaced that might benefit from some distinction. One use case is in the storage provider network, where we might want to have massive, slow providers as a form of added redundancy for the network (and importantly to allow for surge capacity in the event of many new users in a timespan so short the council/WG cannot reasonably react to it). Although the Storage lead can specify different payment terms for openings, I don't think there is any way to have distinction between the different workers (https://testnet.joystream.org/#/forum/threads/319?replyIdx=9)

So in this example, the WG lead might have two different server specifications:
* `Server Type A` = Min requirements: SSD storage (6 TB), gigabit uplink (payment = 3600 JOY/6h)
* `Server Type B` = Min requirements: HDD storage (50 TB), gigabit uplink (payment = 2500 JOY/6h)

This would also have a use case in the curator WG, where a worker might want to perform standard curation work while also being hired separately to perform other tasks such as rewarding uploaded content or generating reports. 

In this example we might have these specifications on the `Curator WG`:
* `Standard Curator Worker` = Job Desc. Assigned curation work (payment = 2300 JOY/6h)
* `Report Worker` = Job Desc. Produce periodic reports on worker activity as described in `forum thread` (payment = 5400 JOY/6h)
* `Reward Worker` = Job Desc. Compile periodic reports on content to reward, and file `spending proposals` as described in `forum thread` (payment = 6800 JOY/6h)

Questions:
- Can the same worker be hired to perform `Server Type A` AND `Server Type B` or would they have to apply using different membership keys?

**Comment by bedeho** [comment]
> Can the same worker be hired to perform Server Type A AND Server Type B or would they have to apply using different membership keys?

I assume you mean in the storage system? If so, then yes, the same worker can have multiple distinct storage providers/distributor obligations.

**Comment by mochet** [comment]
I don't think this issue is relevant anymore, the worker's job title can and should be inferred via the opening that they applied through.
