### ISSUE TITLE
Antioch Parameter Changes [Draft]

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#2294]
Some parameter changes needed for the new testnet. Max Validators is changed as this was done by the community, whereas the Council Election parameters are made to improve the onboarding of new users. The spending proposals is simply to accommodate larger bounties etc.

#### Validators
- Max Validators: 100

#### Council Elections
**Starting defaults**
- Candidacy limit: 50
- Council size: 16
- New term duration: 14,400 (one day)
- Announcing: 57,600 (four days)
- Voting: 14,400 (one day)
- Revealing: 14,400 (one day)
"Full term": 100,800 (one week)

Because of these changes, we also need to modify the proposal parameters:
**Set Election Parameters**
- Candidacy limit
  - min: 50
  - max: 200
- Council size
  - min: 5
  - max: 40
- New term duration
  - min: 1 (one block)
  - max: 144,000 (ten days)
- Announcing
  - min: 14,400 (one day)
  - max: 144,000 (ten days)
- Voting (unchanged)
  - min: 14,400 (one day)
  - max: 28,800 (two days)
- Revealing (unchanged)
  - min: 14,400 (one day)
  - max: 28,800 (two days)

#### Spending Proposals
- Grace Period: 0 (None)
- Amount of Tokens
  - min: 0
  - max: 50,000,000

**Comment by traumschule** [comment]
With proposal 140 (#2184) the council approved some parameter changes, including a higher maximum validator count.
