### ISSUE TITLE
Constantinople Proposals List

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#234]
| Proposal | Dispatchable | Proposal Terms |Ready|
|----------|--------------|-----------------------|-|
| [Evict Storage Provider](https://github.com/Joystream/substrate-runtime-joystream/issues/206) |    `roles::actors::remove_actor(origin, actor_account: T::AccountId)` | |
| [Set Storage Role Params](https://github.com/Joystream/substrate-runtime-joystream/issues/241) | `roles::actors::set_role_parameters(origin, role: Role, params: RoleParameters<BalanceOf<T>, T::BlockNumber>)` |  |
| [Set Max Validator Count](https://github.com/Joystream/substrate-runtime-joystream/issues/200)| `staking::set_validator_count(origin, new: u32)` | |
| [Set Lead](https://github.com/Joystream/substrate-runtime-joystream/issues/245) | to be coded: `replace_lead(...)`  https://github.com/Joystream/substrate-runtime-joystream/issues/243  | |
| [Set WG Mint Capacity](https://github.com/Joystream/substrate-runtime-joystream/issues/240) | to be coded:  `set_mint_capacity(Balance)`  https://github.com/Joystream/substrate-runtime-joystream/issues/237 | |
|~~[Set Council Mint Capacity](https://github.com/Joystream/substrate-runtime-joystream/issues/246)~~ | ~~to be coded:  `set_mint_capacity(Balance)`  https://github.com/Joystream/substrate-runtime-joystream/issues/242~~ | |
| Runtime Upgrade |  |  |:heavy_check_mark:|
| [Set Council Parameters](https://github.com/Joystream/substrate-runtime-joystream/issues/247) | to be coded: `set_council_parameters(...)` https://github.com/Joystream/substrate-runtime-joystream/issues/238 |  |
| [Spending Proposal](https://github.com/Joystream/substrate-runtime-joystream/issues/207) |  to be coded `spend_from_mint(amount: Balance, destination: AccountId)`  https://github.com/Joystream/substrate-runtime-joystream/issues/244|  |
| Text/signal Proposal |  |  | :heavy_check_mark:|

**Comment by bwhm** [comment]
@siman @shamil-gadelshin 
Below is a list of the proposals, ranked in order of priority, based on both importance and my expectation of workload:

# Key

1. `Text/signal Proposal`
    - I'll keep this at the top, as it can be used by `sudo` to manually perform whatever proposals we don't manage to apply, or haven't considered important enough to add to the list in the first place.
    - Because of this, I'd say this is really quite far above the others.
2. `Spending Proposal`
    - This is arguably not the easiest, and arguably the easiest to use for breaking the incentive system, but I think it's a key proposal to give the council some actual power.
3. `Runtime Upgrade`
    - Although it will require some changes to existing proposal, I think this shouldn't be the most difficult. As above, I think it's a key proposal to give the council some actual power.

# Important

4. `Set Council Mint Capacity`
    - Assuming it's not that difficult, I think it's a good one that complements `2.`
5. `Set Lead`
    - Not really sure about this one, but as it's the only actual working group, it makes sense to add it.
6. `Set WG Mint Capacity`
   - Assuming it's not that difficult after implementing `4.`, I think it's a good one that complements `5.`
7. `Evict Storage Provider`
   - Should be fairly easy, and will take some of the workload off of us.

# Nice to have

8. `Set Storage Role Params`
    - Can be a source of confusion, and will require a lot of frontend work to work well.
9.  `Set Max Validator Count`
    - Looks easy at first, but can cause disruption if a bad proposal is voted in.
10. `Set Council Parameters`
    - Maybe the most difficult one (?), and the least important one.

---

Does this seem reasonable? Let me know if any of my assumptions are wrong!

**Comment by shamil-gadelshin** [comment]
Released.
