### ISSUE TITLE
Add handle as a unique filter for Membership query

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#2346]
We currently have:
```graphql
input MembershipWhereUniqueInput {
  id: ID
}
```
It'd be great if we were able to add `handle` here as well. Then this could be used by Atlas to verify whether a given handle is already taken.

**Comment by metmirr** [comment]
By using `unique directive one can achieve this but AFAIK runtime doesn't do unique checks so in that case what atlas will do if it is taken already? Of course, atlas will not allow this but anyone can create this without atlas.

**Comment by kdembler** [comment]
Oh okay, then that's mistake on my part, I was sure that runtime actually validates this. If not, then I guess we can just ignore the fact and skip validation on Atlas side altogether. Thanks

**Comment by metmirr** [comment]
> Oh okay, then that's mistake on my part, I was sure that runtime actually validates this. If not, then I guess we can just ignore the fact and skip validation on Atlas side altogether. Thanks

Maybe would be better to get confirmation from @ondratra or @mnaamani

**Comment by kdembler** [comment]
I checked the runtime code and haven't found any kind of check for that so you're probably right. But yeah, confirmation from @mnaamani would be great
