### ISSUE TITLE
Sumer query node issues sync

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#2349]
Currently existing issues:

- [x] `StorageProvider.metadata` not decoded into utf-8

- [x] Query node not exposing info about storage providers. Basically https://github.com/Joystream/joystream/issues/2252 - with ability to fetch both storage provider details along with the assets request and fetch all the available storage providers

- [x] `DataObject.joystreamContentId` should be returned in the `encode` format

- [x] `Channel.ownerMember` is empty (this is expected as a workaround to another problem)

- [x] `DataObject.ipfsContentId` seems to not be decoded from it bytes representation. Example value returned from the query node: `0x6261666b7265696437756e3237377063347077776d686f7a3470336e687263623536616a676a6336377634736c3264656d6970647437356f636371`. It's possible Atlas isn't encoding those properly but it remains to be seen unless decoding happens. Atlas does the following:
```ts
const ipfsContentId = 'bafkreicwqidpbtyu4w2mwiszunvkgmu4bbxodqjfrqf42usvtqitoa4c34'
const asset = {
  // ...
  ipfs_content_id: new Bytes(this.api.registry, ipfsContentId)
}
```

**Comment by ondratra** [comment]
- [x] Replace usage of `BN` by `Int`/`number`. The only thing that doesn't fit into JS `number` are balances, and `BN` brings some issues
- [x] Re-enable DataObject owner
- [x] default state for `coverPhotoAvailability` and others should be `INVALID` when no asset was provided
- [ ] Int fields in database has only 4 bytes, but we expect it to be 32 bytes long. Ensure `dataType: 'bigint',` in `@IntField` definitions (partially solved - consider reintroducing BigInts)
- [ ] Fix video media metadata update - workaround for not all relations loading now
- [ ] Remove `FeaturedVideo` entity from query node
- [ ] Remove `FeaturedVideo` usage from Atlas

**Comment by ondratra** [comment]
`ipfsContentId` was mistakenly saved via `ipfsContentId.toHex()` instead of `ipfsContentId.toString`. That should be fixed now. THe owner should be preset as well.

**Comment by ondratra** [comment]
`DataObject.joystreamContentId` format has been fixed (using `encode`).

**Comment by ondratra** [comment]
`StorageProvider` and ``StorageProviderType` has been renamed and slightly changed:
```
enum WorkerType {
  GATEWAY
  STORAGE
}

type Worker @entity {
  "Unique identifier"
  id: ID!

  "Sign of worker still being active"
  isActive: Boolean!

  "Runtime identifier"
  workerId: String!

  "Associated working group"
  type: WorkerType!

  "Custom metadata set by provider"
  metadata: String

  dataObjects: [DataObject!]! @derivedFrom(field: "liaison")
}

...
type DataObject @entity {
   // ...
  liaison: Worker 
}
```

Multiple working groups share the same `Worker` entity. For getting the proper storage provider one has to query the woker like this:
```
query {
   workers(where: {workerId_eq: "1", type_eq: STORAGE }) {id, workerId type}
}
```
Notice that you should use `workerId`(together with `type_eq`) instead of `id`.
