### ISSUE TITLE
Define the limits (if any) for each proposal 

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#235]
For each item in #234 , define whether or not there should be limits for the value(s) proposed.

**Comment by bwhm** [comment]
# Limits and restrictions for each proposal type

Assumptions:
- From what I understand, this refers to limits set and enforced by the runtime, thus can only be changed by a runtime upgrade.
- If some/all of these can be changed by `sudo`, a note regarding this will be added.
- `sudo` can kill a proposal during until it is executed - ie. after it has been approved, as long as the `grace_period` is not over.
- The possible limits that needs to be clarified are:
   - If there should be any ranges for values submitted
   - If there should be any restrictions as to whom can make a proposal (apart from being a member)
   - Others?

#### `Evict Storage Provider`
I don't think there needs to be any limits on this, unless we want to enforce that the proposed actor is, in fact, a `storage provider`.

#### `Set Storage Role Params`
Values:
- "min_stake" - apart from the obvious `>=0`, no
- "min_actors" - AFAIK, this isn't enforced anyway. I guess it could be set to `1` to avoid confusion? 
- "max_actors" - `>=1`
- "reward" - Any restrictions would have to be a % of total supply. Can this be done? If not, I suggest avoiding it entirely.
- "reward_period" - I think this should be locked at current value - `600`.
- "bonding_period" - AFAIK, this isn't enforced anyway, so let's keep it at `600`. "unbonding_period"- AFAIK, this isn't enforced anyway, so let's keep it at `600`. 
- "min_service_period":- AFAIK, this isn't enforced anyway, so let's keep it at `600`. 
- "startup_grace_period"- If I'm not mistaken, this is the time (in blocks) for storage providers to confirm their role application stake in the UI. Should be kept as `>=600`
- "entry_request_fee" - apart from the obvious `>=0`, no

#### `Set Max Validator Count`
Currently, there is a `minimumValidatorCount()` set to `4`. I don't see a reason to allow the maximum to be lower :)

#### `Set Lead`
If a new lead is included in the proposal, I think it makes sense to add the following restrictions:
- Don't allow proposing a non-member new lead. (Already in the extrinsic)
- Don't allow a current `council member` to be proposed.
If the latter is a lot of work, I'm not sure it's worth it.

#### `Set WG Mint Capacity`
Any restrictions would have to be a % of total supply. Can this be done? If not, I suggest avoiding it entirely.

#### `Set CM Mint Capacity`
Any restrictions would have to be a % of total supply. Can this be done? If not, I suggest avoiding it entirely.

#### `Runtime Upgrade`
Bedeho proposed that only `sudo` could make this proposal. As long as the assumption wrt to killing a proposal is true, I think we can skip it. If not, it is needed.

#### `Set Council Parameters`
- "AnnouncingPeriod" - `>=14400`
- "VotingPeriod"  - `>=14400`
- "RevealingPeriod" - `>=14400`
- "MinCouncilStake" - `>=1`
- "NewTermDuration" `>=14400`
- "CouncilSize" - `>=3`
- "CandidacyLimit" - `>=25`
- "MinVotingStake" - `>=1`

#### `Spending Proposal`
As the `set_mint_capacity` will restrict the harm here, I don't see a reason to add any restrictions.

#### `Text\signal Proposal`
No

**Comment by bwhm** [comment]
Instead of updating the comment, I'm making a new comment. Won't elaborate here, just numbers:

#### Evict Storage Provider
NA


#### Set Storage Role Params

| Value                    | min         | max         | notes           |
|:------------------------:|-------------|-------------|---------------|
| `min_stake` [tJOY]        | `>0`            | `10000000`          | NA                  |
| `min_actors` [-].             | `>=0`           | `<2`            |  `*`                 |
| `max_actors`  [-]          | `>=2`           | `<100`        | NA                   |
| `reward` [tJOY]               | `>0`              | `<1000`       | NA                  |
| `reward_period` [b]        | `>=600`       | `<=3600`   |  `**`                |
| `bonding_period` [b]       | `>=600`      | `<=28800`  |   `*`                |
| `unbonding_period` [b]   | `>=600`      | `<=28800`  |  NA                 |
| `min_service_period` [b]  | `>=600`      | `<=28800`  |   `*`                |
| `startup_grace_period` [b]| `>=600`      | `<=28800`  |   `*`                |
| `entry_request_fee` [tJOY] | `>0`            | `100000`          | NA                  |

`*` Not enforced by runtime. Should not be displayed in the UI, or at least grayed out.
`**` Should not be displayed in the UI, or at least grayed out.


#### Set Max Validator Count

Value [-]:
- must be integer
- `min>=4`
- `max<=100`

#### `Set Lead`

NA

#### Set WG Mint Capacity

Values [tJOY]:
- `min>=0`
- `max<=1000000`

#### Runtime Upgrade

I guess value for min should be applied so [bytes]:
- `min>=0`
- `max<=2_000_000`

#### Set Election Parameters

| Value                               | min              | max              | notes              |
|:------------------------:|-------------|-------------|---------------|
| `AnnouncingPeriod`      | `>=14400`  | `<=43200`  | NA                  |
| `VotingPeriod`               | `>=14400`  | `<=28800`  | NA                  |
| `RevealingPeriod`          | `>=14400`  | `<=28800`  | NA                  |
| `MinCouncilStake`         | `>0`            | `<=100000`  | `**`              |
| `NewTermDuration`      | `>=14400`   | `<=432000` | NA                  |
| `CouncilSize`                | `>=4`           | `<=20`         | `*`                  |
| `CandidacyLimit`          | `>=25`         | `<=100`       | `*`                  |
| `MinVotingStake`          | `>0`            | `<=100000`  | `**`              |

`*` The minimum CandidacyLimit must be greater or equal to maximum CouncilSize
`**` Should not be displayed in the UI, or at least grayed out.

#### `Spending Proposal`

Values [tJOY]:
- `min>=0`
- `max<=2000000`

#### `Text/signal Proposal`

Values [string length]
 - `min>=0`
- `max<=5000`

**Comment by shamil-gadelshin** [comment]
Runtime upgrade, text, spending proposals: min limit should be greater than zero

**Comment by shamil-gadelshin** [comment]
Released.
