### ISSUE TITLE
Q: Hiring/Firing proposals and replacing lead workers

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2358]
Currently, if a lead is already hired and there is an attempt to hire another lead the hiring will fail (example proposal: https://testnet.joystream.org/#/proposals/24). So if a lead is hired they are 

On the current testnet, this is not a big issue but supposing we have a far more active DAO it is reasonable to expect that having the same lead hired for an extended period of time is undesirable. The current system involves a high level of friction as multiple proposals need to be completed for a new lead to be hired when there is already a lead.

Some examples:
* 1: Someone creates a "fire" proposal for some `WG Lead` due to the lead going AFK. This is easy to deal with and a new hiring can be opened around the same time.
* 2: Someone creates a "hire" proposal for some `WG lead` that is already filled, just to see which applicants step up and because the current lead has been in place for 4 months. An obviously better applicant is found so someone has to create a "fire" proposal, this has to be approved and only then can a "fill" proposal be made. In this situation there is no malice or requirement to fire, it is just that the previous lead has been replaced by a "better" applicant.
* If we extend example 2 and say that the council doesn't approve the "firing" proposal then all of the time and effort put into the hiring proposals has been for nothing.
* If we extend example 2 and say that the council does approve the "firing" proposal but then for some reason doesn't approve the "hiring" proposal then we are left with no lead for an unknown amount of time.

The question is: should an approved "hire" proposal simply override the existing lead without them having to be fired first?

Ties in with this issue: https://github.com/Joystream/community-repo/issues/140

**Comment by mochet** [comment]
Related to this, on the current testnet there are 3x simultaneous proposals to hire different leads for the same position. If one proposal overrode the current lead then the lead would change 3x.

**Comment by bedeho** [comment]
> The question is: should an approved "hire" proposal simply override the existing lead without them having to be fired first?

We can def. do this yes, seems reasonable, added this issue to implement

https://github.com/Joystream/joystream/issues/2368

**Comment by mochet** [comment]
> > The question is: should an approved "hire" proposal simply override the existing lead without them having to be fired first?
> 
> We can def. do this yes, seems reasonable, added this issue to implement
> 
> #2368

I just wanted to check one thing. Does this mean that there will still be only one hiring per opening, which if approved would override the previous lead without requiring a fire proposal?

Example: A lead (`leader_A`) already exists and is hired. An opening is made with 3 applicants (`leader B, C + D`). 2 proposals are made to hire a new lead (`leader_B` + `leader_C`). The `leader_C` proposal passes, executes and replaces `leader_A`. Some time after the `leader_B` proposal is approved and fails as `leader_C` was approved first?

**Comment by bedeho** [comment]
>  Does this mean that there will still be only one hiring per opening

Yes, is this not what you suggested?

> Example: ...

This is correct.

**Comment by mochet** [comment]
This was already implemented.
