### ISSUE TITLE
Joystream CLI not running on Mac M1 (ARM)

### ISSUE THREAD

**Issue by oiclid** [Joystream/joystream#2360]
While the joystream-cli installs on Mac M1 and even runs basic tasks like creating accounts and channels, it crashes when one tries to upload videos giving the following error:
```
Error: Unsupported platform/architecture: darwin-arm64
```
It doesn't matter whether one uses the c and i flags or not, or whether one adds the ```confirm``` flag either. The same error occurs in both global and local installations.

**Comment by bwhm** [comment]
Assigned @mnaamani here, as he owns a one himself :)

However, @Lezek123 may also be able to assist!

**Comment by bwhm** [comment]
(FYI, installed with `npm install @joystream/cli` - not compiled)

**Comment by mnaamani** [comment]
I believe this has been resolved in newer versions of cli.
