### ISSUE TITLE
Forum Issues

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2363]
A list of problems with Pioneer V1 forums

Problems
- I can't find forum threads via tags (such as `governance` `budget` `bounties` would be useful).
- I can't see the newest threads (only most recent posts)
- I can't see the most recent post or thread in a category or subcategory
- Threads aren't shown in chronological order (only by when they are created, not by when the most recent post was made)
- Threads show the date of creation, not the date of last post (both should be shown)
- I can't see subcategories under a category (don't need to see them all, just the most populated top 3-5 subs)
- I can't see how many posts are in each category
- I can't @ people / notification system is missing
- I can't tell once a thread has been closed (there is no lock feature but this is important)
- The markdown doesn't work accurately (the table view is especially poor: https://testnet.joystream.org/#/forum/threads/358?page=2&replyIdx=19). There are other markdown issues such as wrapping that don't work.
- I can't see if someone is a WG lead from when they post (example of lead posting, but no identification showing this: https://testnet.joystream.org/#/forum/threads/371?replyIdx=3)
- I can't discern who are active or new users (post count next to profile) 
- Thread count for categories does not include their subcategories (example: governance cat shows 31 threads from forum view, but actually has more than 100 threads: https://testnet.joystream.org/#/forum/categories/12)
- A lot of the forum view when navigating categories and threads is text only, it would be nice to have an emoji you can set with a thread title or category (Example would be using 🗳️ for the governance category, or 💰 for a budget thread)
- No way to see threads created by a user (should be shown on user profile)
- No way to see the last post made by a user (should be shown on user profile, incl. date + time so I can tell when they were last active)

Other problems:
- Slow/unresponsive loading
- No search
- No usertagging

**Comment by freakstatic** [comment]
- There is no way of subscribing to threads, or "watch" like github does for repos, so that I can receive notification if someone posted in that thread
- I don't get notified if someone answers something I asked in a post

**Comment by oiclid** [comment]
- Mobile view is especially poor.

**Comment by mochet** [comment]
- Can't pin threads so they stay at the top of a forum category
- Can't sort threads by title, author, reply count, date of creation, date of last reply

**Comment by zubastik096** [comment]
Everything works great. But I would be glad if the information was loaded faster.

**Comment by mochet** [comment]
* The text input field has no memory. Sometimes the endpoint connection drops out and the field refreshes, erasing any post that was in draft format.

**Comment by mochet** [comment]
Relevant thread: https://testnet.joystream.org/#/forum/threads/457

Users are reporting that the slow speed of Pioneer v1 forum is making them not to want to use it much as accessing posts takes so long compared to a normal forum.
