### ISSUE TITLE
Checkout component container captures mouse clicks

### ISSUE THREAD

**Issue by eldiegod** [Joystream/joystream#2378]
As seen in the image the yellow zone has a form below and it's not clickable because the container it's capturing the mouse clicks

<img width="1786" alt="Screenshot 2021-05-03 at 21 07 42" src="https://user-images.githubusercontent.com/10615263/116921749-b8a54000-ac54-11eb-9604-4120eb009560.png">

**Comment by mikkio-j** [comment]
<img width="530" alt="Screenshot 2021-05-04 at 10 26 11" src="https://user-images.githubusercontent.com/59691518/116978130-9b5b8a80-acc3-11eb-9e2f-daf82fd24295.png">

Also the actionbar's covering the part of video form. Maybe it should be a part of this fix?

**Comment by eldiegod** [comment]
I already have some other Action bar things that should be fixed so maybe we keep them separate and I fix the one you mention there

**Comment by mikkio-j** [comment]
> I already have some other Action bar things that should be fixed so maybe we keep them separate and I fix the one you mention there

Mentioned that because `Checkout` is part of Action bar, I thought that those issues may have same origin

**Comment by eldiegod** [comment]
ohh then it might make sense yeah
