### ISSUE TITLE
Missing feature: Setting forum thread archival status

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2391]
A forum category can currently be archived (via `update_category_archival_status`), but a single thread cannot. Pioneer v2 wireframes indicate it should be possible:

![image](https://user-images.githubusercontent.com/19978260/117828802-742c2c80-b272-11eb-9482-8d62f1ca6d15.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711074075667) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Yeah, then this is a mistake in the design. Lets not introduce unless we know we must, will update designer.

**Comment by natiwa** [comment]
Improved.
