### ISSUE TITLE
Non-accessible runtime constants

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2395]
There are quite a few constants in the Olympia runtime that are assumed to be known by the frontend, but are not exposed by the runtime (ie. through `api.consts`), which means they have to be hardcoded somewhere and changed with each runtime upgrade that affects them. Some examples of such constants include:
- Forum's `PostDeposit`
- Forum's `ThreadDeposit`
- Working group's `MinUnstakingPeriodLimit`
- Working group's `MinimumApplicationStake`
- Working group's `LeaderOpeningStake`
- Working group's `RewardPeriod`
- Membership's `CandidateStake`
- Lock ids (ie. `StorageWorkingGroupLockId`, `ProposalsLockId` etc.)

I noticed that it is possible to make those constants accessible through `api.consts` by listing them directly inside `decl_module` macro in the runtime, like for example: https://github.com/Joystream/joystream/blob/master/runtime-modules/working-group/src/lib.rs#L360

**Comment by iorveth** [comment]
`Lock ids (ie. StorageWorkingGroupLockId, ProposalsLockId etc.)`
Seems, that with current implementation we can`t expose them as constants of specific runtime pallet. Why do we need them? Appreciate any example.

**Comment by iorveth** [comment]
cc @Lezek123

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2536
https://github.com/Joystream/joystream/pull/2526
