### ISSUE TITLE
Olympia forum: create_thread extrinsic should take poll description, not description_hash, as arg

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2396]
Currently forum's `create_thread` extrinsic takes `Poll` struct as argument, which includes `description_hash` instead of `description` itself. This makes query node unable to retrieve this data.

`create_thread` should take poll `description` as one of the arguments and then hash it before committing to runtime state, same way that, for example, `create_category` takes the category description as arg and hashes it.

The same also applies to poll alternatives texts

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2531
