### ISSUE TITLE
Forum: create_thread should emit PostAdded event (or at least created post_id)

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2403]
Currently the `create_thread` extrinsic in the Olympia forum runtime module actually executes 2 separate actions:
- Creates a new thread in given category
- Creates the initial post in the thread

The issue is that only `ThreadCreated` event is emitted, which doesn't include the `post_id`. This means:
- The created post id cannot be retrieved by the query node mappings
- A post can origin from 2 different source events (`ThreadCreated` / `PostAdded`) which complicates the query node mappings implementation

My suggestion would be to emit `PostAdded` event both during new thread creation and when another post is added to an already existing thread. The `PostAdded` event can include additional `bool` parameter, signaling whether the post was thread's root/initial post or not.

Alternatively, the `ThreadCreated` event can include `new_post_id` as part of the event data.

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/issues/2403
