### ISSUE TITLE
WIP: Sumer feedback for the CLI 

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#2418]
As with the atlas issues, these are all rather small. I don't think any of these must be fixed before release, but if we do, I'd start with these:

1. `setFeaturedVideos` does not confirm with `(y/N)` before sending extrinsic
2. CLI doesn't tell you what storage node is being for uploading videos. This isn't just nice for testing purposes, but would also make it easier for users to report on errors.
3. As you mentioned yourself, it would be nice to be able to set the vouchers in the CLI. I don't know how often (if ever) this will _need_ to be done, now that we've [raised them](#2417), but it's quite cumbersome to use extrinsics.

Longer term stuff:
1. CLI is **slow** for commands that don't even require network activity. On Windows it prints out locally stored commands (like `--help`) in <1s, on linux it takes 5-6 seconds.
   - This comment was from one of the testers. I have to say it's a very good point. Any idea what could be done here?
2. No command to delete a video. Not in scope, but still "nice to have".
3. Connecting the CLI to the QN, so that you can get some information about channels and videos. This has already been discussed, and it's already supported for Olympia. The main beneficiaries of this now are the curators, as they'll have to use the query node to find information as it is now.

**Comment by singulart** [comment]
VideoByID command returns very few data points. No title or description or anything like that. 
`~ » joystream-cli api:inspect -t=query -M=content -m=videoById -e -a309                                               {"in_channel":71,"in_series":null,"is_censored":false} `

**Comment by traumschule** [comment]
Not sure if this is worth a separate issue:
`working-groups:overview` should show the current reward relationship (JOY / X blocks)
