### ISSUE TITLE
Olympia: Support for forum thread labels/tags

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2422]
List of changes needed for Olympia in order to support forum thread tags functionality:

### Runtime

- `create_thread` extrinsic - change `title` argument name to `metadata`, as it will become the encoded thread metadata which includes both thread title and tags
- `edit_thread_title` extrinsic and `ThreadTitleUpdated` event - change names to `edit_thread_metadata` and `ThreadMetadataUpdated`, as this extrinsic will be used to update both forum title and tags.

### Protobuf messages

We need a new protobuf message to represent the thread metadata:
```protobuf
message ForumThreadMetadata {
  optional string title = 1;
  repeated string tags = 2;
}
```

It will be used both when creating a new thread and updating a thread, as described in the __Query node mappings__ section below.

### Query node input schema

We need a new entity like `ForumThreadTag`, with many-to-many relationship to `ForumThread`, ie.:
```graphql
type ForumThreadTag @entity {
  "Tag name"
  name: String! @unique

  "Threads that use this tag"
  threads: [ForumThread!] @derivedFrom(field: "tags")

  "Number of threads that use this tag"
  threadsCount: Int!
}

type ForumThread @entity {
  "Runtime thread id"
  id: ID!

  "Related thread tags"
  tags: [ForumThreadTag!]

  # ...
}
```
_Notice that currently we need a separate `threadsCount` field in ForumThreadTag, because aggregate queries are not yet supported (https://github.com/Joystream/hydra/issues/195)_

### Query node mappings

After deserializing the `tags` from `ForumThreadMetadata`, the query node will:
- `slice` the array so that only the max. allowed number of tags per thread remains (ie. `4`)
- iterate over remaining tags and insert a new `ForumThreadTag` into the database for each tag that doesn't yet have a matching entry in the database (we could additionaly normalize all tags with, for example, `toLowerCase()` and `trim()`, in order to avoid duplications).

When handling `ThreadMetadataUpdated` event:
- no value for `tags` would mean we leave current thread tags unaffected
- any value (including empty array) means we override all existing tags relationships with the new ones (we don't support atomically adding / removing just a single tag)
- we must update `threadCount` accordingly in all unset / set tags.

### Pioneer v2

The input schema menioned above should be enough to support all the queries required by Pioneer, for example:

```graphql
query forumThreadTags(orderBy: name_DESC, limit: 50) {
  name
  threadsCount
} 
```
_Listing tags alphabetically_

```graphql
query forumThreadTags(orderBy: threadsCount_DESC, limit: 10) {
  name
  threadsCount
} 
```
_Listing 10 most popular tags_

```graphql
query forumThreadTags(where:{ name_startsWith: "Pr" ) {
  name
} 
```
_Listing all existing tags starting with characters entered by the user_

**Related tags**

In order to find tags that are related to a tag, Pioneer can execute a query like:
```graphql
query forumThreads(where: { tags_some: { name_eq: "SomeTag" } }) {
  tags {
    name
  }
}
```
Then count how many times each unique tag appears in the result. The tags that appear most often are most related to the tag that's beeing searched for (`SomeTag` in this example), meaning, they most often appear together with `SomeTag`.

**Comment by iorveth** [comment]
is closed by https://github.com/Joystream/joystream/pull/2537 & https://github.com/Joystream/joystream/pull/2547
