### ISSUE TITLE
Idea: On chain comments in the content directory

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2424]
Subject says it all, I think its time.

For a long time it was not clear how to do this, as most viewers will initially not have JOY tokens, and thus they cannot really pay for on-chain comments. I think that, rather than have no comments, it would be better to have a comment system reserved for JOY holders, that way its also an added incentive for people to engage more deeply with the Web3 dimension of being a consumer. Ultimately, doing things like buying creator tokens and NFTs will require that the user gets JOY+a wallet anyway. There could also be a way for gateways to pay for the comments of their users who do not have JOY, if we wanted to, but thats a bridge too far far now.

Another important design question is whether all the comments should be stored in the ledger, or whether we just use hashes/dataobjects, and store them in the native storage system. There is a strong case that the forum has content that has a much stronger claim to needing availability compared to the content comments, so here its more clear that using the ledger is fine, but what about content comments? Not clear.

As far as moderation goes, I think it makes sense to allow the owner of the content to moderate, but should the curators also be able to? Unclear.

**Added:**
- Comments should be nested
- Comments should have anti-state bloat bonds.
- Comments should have reactions.
- Support some richer encoding, for example with @mentions.

Looking at the blog module is probably a good reference.

**Comment by mochet** [comment]
> As far as moderation goes, I think it makes sense to allow the owner of the content to moderate, but should the curators also be able to? Unclear.

I would think that having a separate group to moderate comments would make sense depending on the scale. Whether that's the same WG as the forum moderation I'm not sure, but video comments seem like a distinct area of the platform compared to video curation.
