### ISSUE TITLE
Observation: Worker reward set at 10x the rate (human error)

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2426]
On the current testnet, one of the workers had payments set at 10x the regular rate (almost certainly the result of a typo). This meant the mint was cleared out very quickly as the WG was paying for the equivelant of 14 workers instead of 5.

If simple typos like these can cause dramatic consequences maybe there is some sort of protection required to prevent situations like these (OTOH, it would limit flexibility for the lead to freely set rates). In this case the issue was not major (about $40 extra was minted) but on mainnet simple typos could cause much bigger problems.

**Comment by bedeho** [comment]
Best tradeoff for retaining flexibility but protecting against fat thumbs would be a UI level defense, however, its not clear how the UI would determine possibly fat finger errors like these? Any ideas?

**Comment by mochet** [comment]
> Best tradeoff for retaining flexibility but protecting against fat thumbs would be a UI level defense, however, its not clear how the UI would determine possibly fat finger errors like these? Any ideas?

I suppose the easiest would be to look at other worker rewards, if you're setting it above/below by a dramatic amount it would make sense that its likely to be an error.

Or, combine the current sum of all worker rewards + what you're changing the workers reward to and calculate how long it would take to finish the mint. If the time is very low/very high it would make sense that it could be an error.

Or, there could be a "base level reward" set, say we agree the base level reward is 1k JOY / 3600 blocks. When setting rewards a multiplier is used instead of an exact figure. That way if you're initializing a new worker, or adjusting an already hired worker to anything above 3x the base level reward, it should trigger a serious warning.

Having said that, I am curious how a WG lead will manage hundreds of worker's rates at the same time, one way to deal with it may be this: https://github.com/Joystream/joystream/issues/2273 Since the lead may want to adjust only some subset of worker rewards at any given time, there maybe needs to be a way to organize them.

**Comment by traumschule** [comment]
> these can cause dramatic consequence

If lead fails to check their own actions worst can happen is emptying their mint fast and they have to ask for refill. Then it's council;s job to verify amount, frequency and possibly worker rewards. Maybe even workers have an interest to compare each other's salary.

Since AFAIK also pioneer2 (sadly) will not offer an UI for that and the CLI (sadly) does not show current reward just tokens earned and staked (in overview) 3rd party tools like https://joystreamstats.live/tokenomics is what have to use and improve to verify, maybe even bots (with automatic warnings if someone suggests a clever heuristic).

**Comment by mochet** [comment]
This doesn't really seem to have been an issue, and isn't that actionable. There is improved tooling available on joyutils.org that can help with this.
Most workers are paid using discretionary WG payments anyway, so this doesn't seem important at all anymore.
