### ISSUE TITLE
Query node - sudo calls support

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2431]
Currently, when sudo command is used to execute some extrinsic that is covered in query node mappings, the event parameters deconstruction will fail.

For example, this extrinsic call object creation 
```
const {actor: contentActor} = new Content.CreateChannelCategoryCall(event).args
```

will fail with error
```
Error: Cannot map Enum JSON, unable to find '5HcjY6tMuGk...' in curator, member, lead
```
because `event.extrinsic` is 
```
{
  method: 'sudoAs',
  section: 'sudo',
  ...
}
```
and that causes error in event object creation.

Wrap all event object creation in a wrapper that can accept both possible variants or create a different solution to the problem.

**Comment by ondratra** [comment]
As mentioned by @dzhelezov in private chat, there are other types of calls that should be handled:
1) utility.batch 
2) utility.batch_all 
3) mutlisig.as_multi 
and in general any kind of delegated calls.

But we will likely not support them all but rather make events more verbose in the future (so there will be no reason to 'touch' extrinsic parameters).

**Comment by dzhelezov** [comment]
Perhaps it can be integrated into typegen? One can try to locate an argument by name + type (name: 'call', type: 'Call'), but in general we can even have a chain of delegated calls, e.g. multisig.as_multi -> sudo.sudoAs -> actualCall

**Comment by ondratra** [comment]
Obviously, reading data from extrinsic parameters brings extra complexity beyond my initial expectation. 

Another issue with reading extrinsic parameters is a need to select a proper `*Call` object in cases when an event can be emitted from multiple different extrinsic. It's not much of a problem on its own, but when combined with a lookup for parameters in sudo calls (and other situations you mentioned), it multiplies the number of possibilities.

Also, I haven't found a way how to pair sudo call parameters to extrinsic parameters automatically. The types generated by typegen generally has this structure:
```
export class ChangeMemberAboutTextCall {
    public readonly extrinsic: SubstrateExtrinsic;
    public readonly expectedArgTypes = ["MemberId", "Bytes"];

    ...

    get args(): ChangeMemberAboutText_Args {
        ...
    }
}

class ChangeMemberAboutText_Args {
    get memberId(): MemberId {
      return createTypeUnsafe<MemberId & Codec>(typeRegistry, "MemberId", [
        this.extrinsic.args[0].value
      ]);
    }

    ...
}
```
Since sudo call parameters gives a key-value pair like this:
```
{
  member_id: 1,
  text: '0x...', // bytes string that needs to be decoded
}
```
There is no way to connect all the pieces and get decoded parameters. 

I solved it in mappings by providing `parameter name -> parameter index` map (see https://github.com/Joystream/joystream/pull/2441/files#diff-9af242945476363410a798a87c9d22b687aeeea210b9b1bbc4d0697fde116b04R23). Such solution is not ideal and creates an opportunity for errors.

I expect Joystream events to be improved in future releases, and this whole reading from extrinsic to be gone. Hydra could (should?) theoretically adopt the current code regarding the matter and improve it. Reading from extrinsic may still be useful when working with other blockchains that have not-ideal events as we do now in the membership module right now.

**Comment by dzhelezov** [comment]
Is it always the case that the key is a snake_cased version of the parameter name? Then one can automate lookups. But indeed the whole things looks tricky

**Comment by ondratra** [comment]
> Is it always the case that the key is a snake_cased version of the parameter name? Then one can automate lookups. But indeed the whole things looks tricky

Yes, I think it is.
