### ISSUE TITLE
Membership module - more verbose events

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2439]
Some information important to query node is not emitted in runtime events. Because of that query node needs to read some information from extrinsic call parameters, which creates unnecessary complexity in some cases (see #2435). 

In Sumer, the membership module seems to be less verbose than desired. `handle`, `avatar_uri`, and `about` are extrinsic parameters but are not emitted in the event. Other modules in Olympia may be affected as well.
 https://github.com/Joystream/joystream/blob/a5e804d347c6db63b5c7bee30092c7a7988a64a5/runtime-modules/membership/src/lib.rs#L301 Other membership module extrinsics are affected as well.

Expose all data required by query node to events.

**Comment by iorveth** [comment]
> Some information important to query node is not emitted in runtime events. Because of that query node needs to read some information from extrinsic call parameters, which creates unnecessary complexity in some cases (see #2435).
> 
> In Sumer, the membership module seems to be less verbose than desired. `handle`, `avatar_uri`, and `about` are extrinsic parameters but are not emitted in the event. Other modules in Olympia may be affected as well.
> https://github.com/Joystream/joystream/blob/a5e804d347c6db63b5c7bee30092c7a7988a64a5/runtime-modules/membership/src/lib.rs#L301
> 
> Other membership module extrinsics are affected as well.
> Expose all data required by query node to events.

I see, events in `olympia` are already reworked to include all the data passed via extrinsic parameters. 
Did you mean, we need to rework them for `sumer` or potential `sumer` based release branch?

**Comment by iorveth** [comment]
cc @ondratra

**Comment by ondratra** [comment]
No, it was meant only for Olympia - there is a fix for the lack of events in Sumer. I checked the Olympia code and the troubles are solved there indeed.
