### ISSUE TITLE
Problem: Lead opening not cancellable

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2446]
Currently, a lead opening is created and people can apply if they fulfill certain stake requirements. It is expected that the council should only approve `good` openings but this can never be guaranteed.

There is no feature to cancel an opening, either through proposals or by the creator of the opening. The only way this can be achieved is by creating a proposal to review applicants (which would take 24h or more) or letting the proposal naturally expire.

In both cases, users can still apply to the opening which makes it a bit of a wasted effort situation.

Situations where this feature may be useful:
* the application / role stake requirements are not set at a realistic amount but the opening is still approved
* due to an extremely high number of applicants, it is decided that creating an opening which limits applications is a better approach
* due to a low number of applicants, it is decided that extending the opening's duration is a better approach.

This is not a critical problem and it may be that with enough time + experience the council can vote on opening proposals with a far more critical approach. The only reason it is an issue, is that if the DAO wants to change course for some reason it will take at minimum 24 hours (beyond the problem of communicating to people they shouldn't apply to a certain opening, which may also not be an issue)

**Comment by traumschule** [comment]
of course @mochet had thought of that before!

Currently lead opening 23 (!) is in review with 0 applicants. It can neither be filled nor cancelled because there is no `Cancel Working Group Leader Opening` proposal type.
>WG Opening ID     Type       Stage                                 Applications     
> 24                Worker     Complete (#4095747)                   14               
> 23                Leader     In Review (#3964934)                  0

https://pioneer.joystreamstats.live/#/working-groups/opportunities/operationsGroupAlpha/23
The actual problem however is minimal and temporary because of the built-in timeout:
> Candidates will be selected by block 4,396,934 (expected on Feb 09, 2022 14:20:18) at the latest.

**Comment by mochet** [comment]
This is now implemented within `olympia` in the form of a proposal.
