### ISSUE TITLE
Channel categories missing

### ISSUE THREAD

**Issue by igrexac** [Joystream/joystream#2454]
**Problem**
- In the new CLI version _@joystream/cli/0.5.0 win32-x64 node-v14.16.0_ (Windows) there is no way to add categories for videos and channels. Error:
![image](https://user-images.githubusercontent.com/83884918/120433720-43787800-c384-11eb-829a-09c5649021c0.png)

- Added channel categories with _@joystream/cli/0.5.1 linux-x64 node-v14.16.1_ are not displayed on the JoyStream Studio platform. When creating a channel, there is no way to select a category. 
![image](https://user-images.githubusercontent.com/83884918/120434183-cc8faf00-c384-11eb-9cfb-bdf101efb845.png)

![image](https://user-images.githubusercontent.com/83884918/120435071-f39ab080-c385-11eb-91bd-e2e0aa5a3472.png)

- Previously, it was possible to update channel data using CLI (`media:updateChannel` or `content:updateChannel`), now this command does not work (both CLI Win & Linux), so I check only through the portal.

**Comment by Lezek123** [comment]
Thank you for creating the issue @igrexac

> In the new CLI version @joystream/cli/0.5.0 win32-x64 node-v14.16.0 (Windows) there is no way to add categories for videos and channels

This is a known issue with version `0.5.0` that has been patched in `0.5.1` (which should be the default `@joystream/cli` version installed with `npm install -g @joystream/cli`now)

> Previously, it was possible to update channel data using CLI (media:updateChannel or content:updateChannel), now this command does not work (both CLI Win & Linux), so I check only through the portal.

Those commands have been replaced with `content:updateChannel` and `content:updateVideo`.
You can run `joystream-cli content` to see the list of supported commands.
The json format of the update is the same as for the channel/video creation: https://github.com/Joystream/joystream/blob/master/cli/examples/content/CreateChannel.json (only the provided fields will be updated)

**Comment by kdembler** [comment]
Channel categories have been removed on `carthage` branch, closing
