### ISSUE TITLE
Limit peers flag does not work as intended

### ISSUE THREAD

**Issue by kakashi0x0** [Joystream/joystream#2456]
`--in-peers 50 --out-peers 50` does not limit number of peers

Tested on two different VPS, one with peer limit of 30 and another with peer limit of 50.

On both nodes peer exceeded the indicated peer numbers.

![image](https://user-images.githubusercontent.com/38396843/120529984-d229db00-c3fe-11eb-999d-7c6c3d56ca6d.png)

![image](https://user-images.githubusercontent.com/38396843/120541933-53d43580-c40c-11eb-9f49-96f763b48043.png)
![image](https://user-images.githubusercontent.com/38396843/120542031-71090400-c40c-11eb-846b-5e8cd0bbcdb0.png)

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```

**Comment by mnaamani** [comment]
The peer count you see in telemetry is the sum of in and out so for a configuration of `--in-peers 50 --out-peers 50` I would expect the peer count to reach 100.

**Comment by kakashi0x0** [comment]
> The peer count you see in telemetry is the sum of in and out so for a configuration of `--in-peers 50 --out-peers 50` I would expect the peer count to reach 100.

oh, ok! Didn't know that. I'll close this issue now.

**Comment by kakashi0x0** [comment]
@mnaamani reopening this issue as either I am doing it wrong or it is not working the way you mentioned. 

With the below flags this node should not exceed 70 peers whereas at the time of writing it currently has 133.

Systemd script:
![image](https://user-images.githubusercontent.com/38396843/120985015-043f9200-c79d-11eb-9441-32e965026cf8.png)

![image](https://user-images.githubusercontent.com/38396843/120984640-ac089000-c79c-11eb-974e-59565aee35d2.png)

Current telemetry: 133 peers
![image](https://user-images.githubusercontent.com/38396843/120984158-2f75b180-c79c-11eb-93fb-6734432b8b84.png)

**Comment by mnaamani** [comment]
Perhaps it is just best effort on part of the node. Its good to be well connected, but I understand it does put more demand and cost on bandwidth. Perhaps future versions of substrate with newer versions of libp2p perform better with regards to handling connection limits.
