### ISSUE TITLE
ProposalCreated event - unifying the data source

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2457]
In the current Olympia runtime there are 2 events emitted when proposal is created:
```
proposalsEngine.ProposalCreated(MemberId, ProposalId)
proposalsCodex.ProposalCreated(GeneralProposalParameters, ProposalDetailsOf)
```
As you can notice, one of those events contains `ProposalId`, while the other one contains the proposal details.
Because the query-node requires both of those is order to create a `Proposal` entity, it needs to either:
- cache the `ProposalId` during `proposalsEngine.ProposalCreated` event and then use it when handling `proposalsCodex.ProposalCreated`
- use `proposalsCodex.createProposal` call data when handling `proposalsEngine.ProposalCreated` and ignoring `proposalsCodex.ProposalCreated` event (I think using call data should probably be avoided if possible due to issues with `sudo`, `sudoAs`, `batch`, `multisigAs` and other "wrapping" calls that can trigger the same event)

Another issue is that there is no single, clear "origin" event for the proposal (it became a practice for the query node to provide this data about entities through fields like `proposal.createdInEvent`)

My proposition would be to update `proposalsCodex.ProposalCreated` event to include `ProposalId`.
Looking at the runtime code, this should be a quite trivial change, since the `proposalId` is already assigned to variable just before the event is emitted:
```
            let proposal_id =
                <proposals_engine::Module<T>>::create_proposal(proposal_creation_params)?;

            <ThreadIdByProposalId<T>>::insert(proposal_id, discussion_thread_id);

            Self::deposit_event(RawEvent::ProposalCreated(general_proposal_parameters, proposal_details));
```

Not sure if `proposalEngine.proposalCreated` event has any value in that case, so perhaps it can also be removed along the way.

**Comment by bedeho** [comment]
I agree, this is a good fix, engine events or not useful when triggered by code paths external to the module, because they do not know all the contextual inputs.

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2539
