### ISSUE TITLE
Channel deletion

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2465]
This should be possible, I keep stacking up lots of dead channels when playing around. Probably should require channel to be empty of all content.

**Comment by bedeho** [comment]
A review needs to be done about deleting the channel assets, like the cover photo and the avatar, from the storage modules. We presume that all videos and their assets are not present.

**Comment by iorveth** [comment]
Can we close this in favour of https://github.com/Joystream/joystream/issues/2572 ?
