### ISSUE TITLE
Idea: WG simple proposal system

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2477]
In the Runtime DAO issue a `Proposal System` is described: https://github.com/Joystream/joystream/issues/2068

Working Groups might benefit from a very simple text proposal/poll system (maybe with multiple choice options) for internal decision making, these proposals would ideally only allow voting by WG members (+ lead) and could maybe be restricted to being created by the lead. The proposals/polls should be shown in the working group view so that all users can see what the WG is currently working on or how (or if) they are navigating current issues.

Although the forums will have a poll feature, it is not clear how flexible it is (ex. to limit voting to a certain group) it would also mean that all of these decisions are hidden away in the forums and probably be difficult to access.

If WGs had this system it would likely allow them a greater deal of autonomy from the council and offload some decision making from the council.

## Use Cases + Benefits
* I can imagine the curator group will encounter certain situations regarding rules and how to implement them.
* The operations group (as it is open ended) doesn't have a predefined structure, so this feature would be useful to allow this group to make decisions on workload and other things.
* The storage group has to install certain 3rd party software on nodes (for bandwidth monitoring), and also has to make decisions regarding back ups, so this system would be valuable
* Anything to do with rewarding users or creators or discretionary spending would benefit from this.
* It would greatly increase transparency and readability of each WG's decision making progress. It would also remove some of the reliance on using 3rd party communication platforms and show users what the lead of a group is doing and their situational awareness.

**Comment by bedeho** [comment]
I of course buy that the WGs will need to decide on complex matters, but I am not sure it makes sense to use a voting system for this? Why could they not deliberate on this off-chain, but ultimately the lead is both the final decision maker and the source of truth for the chain? Leads are ultimately sort of subsystem dictators that are only accountable to the council, similar to political bureaucrats or to department heads in companies.

**Comment by mochet** [comment]
> I of course buy that the WGs will need to decide on complex matters, but I am not sure it makes sense to use a voting system for this? Why could they not deliberate on this off-chain, but ultimately the lead is both the final decision maker and the source of truth for the chain? Leads are ultimately sort of subsystem dictators that are only accountable to the council, similar to political bureaucrats or to department heads in companies.

The reason a voting system would work is that I imagine this system being used to primarily discuss/decide on matters concerning each WG, by having their own place with on-chain identities, there is a big benefit in terms of transparency and value. Currently when we look at each WG the decision making process is invisible unless a user goes searching for it on the forums or even worse, if it is located off-chain they may not be able to access it at all.

This is exactly what the council has with the proposal system, a clear picture to anyone of what decisions are made, what things are being worked on or implemented and it clearly signals value as well as activity. If such a system existed for WGs, just like the council's proposal system, every single proposal that is added creates more value and trust in how things are going. It also explains to anyone and everyone what each WG does.

If we had a WG lead who made only one or two of these "simple proposals" in the span of a month, it shouldn't signal confidence in that persons capabilities to the council.

While the lead is the final decision maker, they are essentially implementing what the council has decided, there are many different ways for leads to interpret tasks, budgets and also to "fairly" divvy up work among workers in their group. This could be as simple as deciding how many days per week curators are expected to work, or whether the WG lead will pay a bonus from discretionary spending to a worker for a job well done. Or the council may push some decisions onto the WG's themselves such as coming up with their own definition of reasonable downtime for a storage node, then the lead can transparently provide a few options and the actual workers and no one else can have some say in deciding this.

Another clear benefit to me is that with highly unstructered WGs like `operations` this can help to build some form of structure and regularity; decisions like "we have just had a new budget approved which allows us 10% more spending, should we focus it on hiring more workers, increasing our marketing budget or increasing the payments for workers".

What I have written originally just talks about `text proposals` with polls, `spending proposals` for the WGs could also be highly interesting and add some form of safety net in how discretionary funding is utilized.

Another way of putting this all is that the council has a way of talking to working groups, but working groups do not have a way of talking to the council that is structured or quiet (in this context, a noisy way of talking would be the forums where everyone can have a say - even those who have nothing at all to do with the working group - whereas a proposal system would be quiet as it requires voting)
