### ISSUE TITLE
Vesting

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2478]
We need the ability for vesting which interoperates with general use of the native token for use, i.e. working groups, voting, council candidacy, proposals, validation, nomination, etc. By vesting we specifically mean that the share of tokens in an account which can be transferred to another account is increasing, likely just linearly, in block height. 

I think there are some built in features for this in the `balances` module, but it must be looked into.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201974552034407) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
Could we use the original Parity's pallet?

https://github.com/paritytech/substrate/blob/master/frame/vesting/src/lib.rs

**Comment by bedeho** [comment]
I don't have any principled objection, but not sure if its needed, doesn't balances have this? does it imply replacing balances? checking other chains like Acala & Moonbeam could be instructive.

**Comment by shamil-gadelshin** [comment]
Acala uses a similar implementation from ORML: 
https://github.com/open-web3-stack/open-runtime-module-library/blob/master/vesting/src/lib.rs

**Comment by shamil-gadelshin** [comment]
Moonbeam doesn't seem to use vesting: 
https://github.com/PureStake/moonbeam/blob/866a06a5c84675586e4d0b98799b4c79e8345958/runtime/moonbeam/src/lib.rs#L1588

**Comment by shamil-gadelshin** [comment]
> ....  doesn't balances have this? does it imply replacing balances?

It's just a container for vesting schedule with an additional account lock ID. It locks account balance for some block time with several options. It would be good if we could reuse the existing pallet rather than create one from the scratch.

**Comment by bedeho** [comment]
Agreed, lets go with that then ;)
