### ISSUE TITLE
storage-node: Colossus / IPFS latency issues

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2479]
Using `autocannon` we have begun testing storage providers for speed and latency (https://testnet.joystream.org/#/proposals/157).
![image](https://user-images.githubusercontent.com/50830161/121843755-ea013900-ccf3-11eb-8b03-2e65b7b7ca36.png)

During further testing it has become apparent that there is something with storage providers (including Jsgenesis' provider) that causes an unusual amount of latency compared to a normal file.

Latency was measured at between 2162 up to 6127 ms on Jsgenesis' provider.

A test was also performed by a storage provider using localhost and these are the results: 
![image](https://user-images.githubusercontent.com/50830161/121843656-bcb48b00-ccf3-11eb-8fa2-4822cd25ef67.png)

![image](https://user-images.githubusercontent.com/50830161/121843694-cc33d400-ccf3-11eb-88d2-8dfde207cf01.png)

This issue seems to happen with both thumbnails and video files. The results were also shown in two tests using an alternative tool to `autocannon` and also using Chrome's network log there are delays with many of the thumbnails.

**Comment by mnaamani** [comment]
Thanks for @mochet for conducting these tests.
They are very useful to help provide insight into where the storage node performance can be improved :+1: 
Will try to go through them in detail and share some ideas.

**Comment by freakstatic** [comment]
Flags used: `-c 3 -d 60`

**Comment by mochet** [comment]
I believe this has been solved
