### ISSUE TITLE
Olympia runtime upgrade proposal - unexpected post-upgrade proposal status

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2480]
I'm running into some unexpected behavior when running runtime upgrade proposal tests on Olympia branch.

Steps I've taken:

1. I created 2 RuntimeUpgradeProposals - one that I expected to be succesfully executed (`proposal2`) and one I expected to be `CanceledByRuntime` later (`proposal1`). _Here I'm assuming that when a proposal is in `Deciding`/`Active` state during the runtime upgrade - it should become `CanceledByRuntime` once the upgrade is executed: [see related code](https://github.com/Joystream/joystream/blob/olympia/runtime/src/runtime_api.rs#L90)_
1. Because for my tests I'm using `constitutionality===2` for runtime upgrade proposals, I approve both of them and I elect a new council
1. Now the second round of voting begins and both proposals are in `Deciding` state 
1. I approve `proposal2`
1. `proposal2` executes succesfully and the runtime is upgraded
1. I would expect `proposal1` to now be `CanceledByRuntime`, but no related event is emitted. The query node still sees it as beeing in `Deciding` state, but `api.query.proposalsEngine.proposals()` returns empty result.

Query node query:

```graphql
{
  proposals(where:{ id_in: ["1", "2"] }) {
    id
    details {
      __typename
    }
    status {
      __typename
      ... on ProposalStatusExecutionFailed {
        errorMessage
      }
    }
    statusSetAtBlock
    proposalStatusUpdates {
      id
      newStatus {
        __typename
      }
    }
  }
}
```

Query node result:

```graphql
{
  "data": {
    "proposals": [
      {
        "id": "1",
        "details": {
          "__typename": "RuntimeUpgradeProposalDetails"
        },
        "status": {
          "__typename": "ProposalStatusDeciding"
        },
        "statusSetAtBlock": 216,
        "proposalStatusUpdates": [
          {
            "id": "OLYMPIA-136-1",
            "newStatus": {
              "__typename": "ProposalStatusDormant"
            }
          },
          {
            "id": "OLYMPIA-216-5",
            "newStatus": {
              "__typename": "ProposalStatusDeciding"
            }
          }
        ]
      },
      {
        "id": "2",
        "details": {
          "__typename": "RuntimeUpgradeProposalDetails"
        },
        "status": {
          "__typename": "ProposalStatusExecuted"
        },
        "statusSetAtBlock": 239,
        "proposalStatusUpdates": [
          {
            "id": "OLYMPIA-175-2",
            "newStatus": {
              "__typename": "ProposalStatusDormant"
            }
          },
          {
            "id": "OLYMPIA-216-4",
            "newStatus": {
              "__typename": "ProposalStatusDeciding"
            }
          },
          {
            "id": "OLYMPIA-219-1",
            "newStatus": {
              "__typename": "ProposalStatusGracing"
            }
          }
        ]
      }
    ]
  }
}
```

Chain state after runtime upgrade:
![proposals-s1](https://user-images.githubusercontent.com/19978260/121934352-8143ac00-cd47-11eb-872c-87e8661e77fd.png)

Events emitted in block 239 (during runtime upgrade):
![proposals-s2](https://user-images.githubusercontent.com/19978260/121934323-78eb7100-cd47-11eb-9d67-b2c99fdd46b1.png)

_Notice no events related to updating the status of `proposal1`_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711096503717) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
How did you upgrade the runtime? 1. Did you compile a newer version changing both Cargo.toml and lib.rs of the runtime?  or 2. Did you pick already compiled unchanged wasm from the target/release folder? @Lezek123

**Comment by Lezek123** [comment]
## How to reproduce

You can use https://github.com/Lezek123/substrate-runtime-joystream/tree/olympia-staging branch to reproduce this issue.

### 1. Test node images

Build test node docker images (test node images have modified blocktime of `1s` and custom proposal parameters (voting period, gracing period etc.):
```
            docker build .\
              --file joystream-node.Dockerfile\
              --tag joystream/node\
              --build-arg TEST_NODE=true
```

2 images are needed: one standard test image and one with updated spec version (Initially I only updated `runtime/src/lib.rs`) 
The first image needs to be tagged as `joystream/node:latest`, the second one can be, for example, `joystream/node:olympia-test-runtime-upgrade`

### 2. Build query node
```
docker-compose up -d joystream-node
yarn && yarn workspace query-node-root build
```

### 3. Run the tests

First I would recommend commenting `docker-compose down -v` line in `function cleanup() {` in `/query-node/run-tests.sh` to make sure the infrastructure is kept alive after the tests are finished:

```
function cleanup() {
    # Show tail end of logs for the processor and indexer containers to
    # see any possible errors
    (echo "\n\n## Processor Logs ##" && docker logs joystream_processor-mnt_1 --tail 50) || :
    (echo "\n\n## Indexer Logs ##" && docker logs joystream_indexer_1 --tail 50) || :
    (echo "\n\n## Indexer API Gateway Logs ##" && docker logs joystream_hydra-indexer-gateway_1 --tail 50) || :
    (echo "\n\n## Graphql Server Logs ##" && docker logs joystream_graphql-server-mnt_1 --tail 50) || :
    # docker-compose down -v
}
```

Then run the tests with:

```
RUNTIME_UPGRADE_TARGET_IMAGE_TAG=olympia-test-runtime-upgrade query-node/run-tests.sh proposals
```

It may be useful to redirect the debug output to a file for further investigation, ie: with ` &> out.log`

**Comment by mnaamani** [comment]
Some Notes from my testing so far:

So the runtime behavior is such that on runtime upgrade `proposals:engine:finalize_proposal(id, proposal, CanceledByRuntime)` is invoked, an the event that will be emitted in this case is: `ProposalDecisionMade(proposal_id, CanceledByRuntime)` I did not see that event in the block of the runtime upgrade.

![Screen Shot 2022-03-01 at 5 21 37 PM](https://user-images.githubusercontent.com/1621012/156176722-d1a5827b-4871-424a-9605-8f9629516679.png)

The tests logs after runtime upgrade was completed successful (at block 740):
```
 integration-tests:awaiting:blocknumber 740 Current block: 740 +1s
  integration-tests:awaiting:blocknumber 740 Condition satisfied! +1ms
  integration-tests:query-node-api:query getProposalsByIds({"ids":["2"]}) +37s
2022-03-01 17:10:02        API/INIT: Runtime version updated to spec=1, tx=1
  integration-tests:query-node-api:try:getProposalsByIds([this.params[i].proposalId]) Unexpected query result (expected 'ProposalStatusGracing' to equal 'ProposalStatusExecuted') +0ms
  integration-tests:query-node-api:try:getProposalsByIds([this.params[i].proposalId]) Retrying query in 3000ms... +1ms

.
.
.

  integration-tests:job:runtime upgrade proposal flow 0 failed: +4m
AssertionError: expected 'ProposalStatusGracing' to equal 'ProposalStatusExecuted'
    at DecideOnProposalStatusFixture.assertProposalExecutedAsExpected (/Users/mokhtar/joystream/joystream/tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:151:12)
    at /Users/mokhtar/joystream/joystream/tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:207:27
    at QueryNodeApi.tryQueryWithTimeout (/Users/mokhtar/joystream/joystream/tests/network-tests/src/QueryNodeApi.ts:363:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/mokhtar/joystream/joystream/tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:205:26
    at async Promise.all (index 0)
    at async DecideOnProposalStatusFixture.runQueryNodeChecks (/Users/mokhtar/joystream/joystream/tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:197:5)
    at async FixtureRunner.runQueryNodeChecks (/Users/mokhtar/joystream/joystream/tests/network-tests/src/Fixture.ts:198:5)
    at async FixtureRunner.runWithQueryNodeChecks (/Users/mokhtar/joystream/joystream/tests/network-tests/src/Fixture.ts:203:5) {
  showDiff: true,
  actual: 'ProposalStatusGracing',
  expected: 'ProposalStatusExecuted',
```

Now the joystream-node got some problems after the upgrade:
```
Mar 01 13:09:57.019  INFO ✨ Imported #739 (0xf762…6dba)    
Mar 01 13:09:58.005  INFO 🙌 Starting consensus session on top of parent 0xf76212d72efdf8b8de61d545f8c58a91c255ce43ce390fb402f9c7af54c26dba    
Mar 01 13:09:58.901 DEBUG Runtime upgrade proposal execution started.    
Mar 01 13:09:59.003  INFO ⌛️ Discarding proposal for slot 1646140198; block production took too long    
Mar 01 13:09:59.003  WARN Encountered consensus error: ClientImport("Timeout in the Slots proposer")    
Mar 01 13:09:59.008  INFO 🙌 Starting consensus session on top of parent 0xf76212d72efdf8b8de61d545f8c58a91c255ce43ce390fb402f9c7af54c26dba    
Mar 01 13:09:59.214 DEBUG Runtime upgrade proposal execution finished.    
Mar 01 13:09:59.566  INFO 💤 Idle (0 peers), best: #739 (0xf762…6dba), finalized #737 (0x90ec…7491), ⬇ 0 ⬆ 0    
Mar 01 13:09:59.587  INFO 🎁 Prepared block for proposing at 740 [hash: 0x2ca1862cb78e11fc8772098c4d06aaf9807bc76066a747620e27b6cbf8d9f940; parent_hash: 0xf762…6dba; extrinsics (2): [0x54bc…8a87, 0xc5ad…6af5]]    
Mar 01 13:09:59.904 DEBUG Runtime upgrade proposal execution started.    
Mar 01 13:10:00.225 DEBUG Runtime upgrade proposal execution finished.    
Mar 01 13:10:00.606  INFO 🎁 Prepared block for proposing at 740 [hash: 0xaeaae5a80347a78fc4ab75e429a9c8373310fd21e800e8f87e998d9010d7c47a; parent_hash: 0xf762…6dba; extrinsics (2): [0x6da4…80f9, 0x2dca…bc81]]    
Mar 01 13:10:00.608  INFO 🔖 Pre-sealed block for proposal at 740. Hash now 0x2a937ef8bdb05813f3c52bcc221a55cd9be7aad550ce4b98571829037682b5ed, previously 0xaeaae5a80347a78fc4ab75e429a9c8373310fd21e800e8f87e998d9010d7c47a.    
Mar 01 13:10:00.819  INFO ✨ Imported #740 (0x2a93…b5ed)    
Mar 01 13:10:00.820  INFO 🙌 Starting consensus session on top of parent 0x2a937ef8bdb05813f3c52bcc221a55cd9be7aad550ce4b98571829037682b5ed    
Mar 01 13:10:00.890  INFO 🎁 Prepared block for proposing at 741 [hash: 0x82419a48428f5decb23cdfdf4734c596c251d87ac844a025c2968f09b545636f; parent_hash: 0x2a93…b5ed; extrinsics (1): [0xc42e…6c58]]    
Mar 01 13:10:00.899  INFO 🔖 Pre-sealed block for proposal at 741. Hash now 0xcd6847e8219e499f173188b969b489a139ef687b6221985e894101e6c76eaf26, previously 0x82419a48428f5decb23cdfdf4734c596c251d87ac844a025c2968f09b545636f.    
Mar 01 13:10:00.899  WARN Error with block built on 0x2a937ef8bdb05813f3c52bcc221a55cd9be7aad550ce4b98571829037682b5ed: ClientImport("Unexpected epoch change")    
```

I suspect it is because the WASM I used to upgrade had block interval of 6s while the running test node had 1s.

The indexer stopped receiving blocks obviously
```
2022-03-01T13:09:58.641Z index-builder:indexer Done block #737
2022-03-01 13:10:09        API/INIT: Runtime version updated to spec=1, tx=1
2022-03-01T13:10:13.879Z index-builder:indexer Processing block #738
2022-03-01T13:10:14.133Z index-builder:redis-relayer Relaying to redis: hydra:indexer:started:block {"height":738}
2022-03-01T13:10:28.849Z index-builder:indexer Saving block data
2022-03-01T13:10:28.943Z index-builder:indexer Saved block data
2022-03-01T13:10:28.943Z index-builder:indexer Saving extrinsics
2022-03-01T13:10:28.998Z index-builder:indexer Saved 2 extrinsics
2022-03-01T13:10:28.998Z index-builder:indexer Saving event entities
2022-03-01T13:10:28.999Z index-builder:indexer Read 3 events; saving in 1 batches
2022-03-01T13:10:29.023Z index-builder:indexer Saved 3 events
2022-03-01T13:10:29.050Z index-builder:redis-relayer Relaying to redis: hydra:indexer:complete:block {"events":[{"id":"0000000738-000000-4df44","name":"council.NotEnoughCandidates","extrinsic":"none"},{"id":"0000000738-000001-4df44","name":"system.ExtrinsicSuccess","extrinsic":"timestamp.set"},{"id":"0000000738-000002-4df44","name":"system.ExtrinsicSuccess","extrinsic":"finalityTracker.finalHint"}],"extrinsics":[{"id":"0000000738-000000-4df44","name":"timestamp.set"},{"id":"0000000738-000001-4df44","name":"finalityTracker.finalHint"}],"hash":"0x4df44f6cec39ed67f2ba558b29458001e1453e10ef44e68153973c8cd11ff23c","parentHash":"0x90ec93504fe9222fc29a062165884f4ca2989a7d057fc42f1bac065bceea7491","height":738,"runtimeVersion":{"specVersion":0},"ts":1646140196000}
```

Processor would never have seen the event anyway even if it had been emitted.
```
INFO: Processing block: 0000000736-f2482, events count: 3 
INFO: Last block: 736 	: 0 blocks behind
INFO: Processing block: 0000000738-4df44, events count: 1 
INFO: Last block: 738 	: 0 blocks behind
```
I will try again with a WASM file with same block interval.

In the back of my mind I have a question..  will events emitted in `on_runtime_upgrade()` actually show up. (Similar situation as block 0) - will look up docs.

**Comment by mnaamani** [comment]
So reading through substrate docs about [OnRuntimeUpgrade](https://docs.substrate.io/rustdocs/latest/frame_support/traits/trait.OnRuntimeUpgrade.html#warning) and [Events](https://docs.substrate.io/v3/runtime/events-and-errors/#depositing-an-event) leads me to believe that any events deposited in on_runtime_upgrade() are being reset.

To confirm this I inspected the executive for the version of substrate we are using v2.0.1, in particular the block construction logic [initialize_block_impl()](https://github.com/paritytech/substrate/blob/2cd20966cc09b059817c3ebe12fc130cdd850d62/frame/executive/src/lib.rs#L231)

code snippet from `initialize_block_impl`:

```rust
if Self::runtime_upgraded() { 
  // System is not part of `AllModules`, so we need to call this manually.
  let mut weight = <frame_system::Module::<System> as OnRuntimeUpgrade>::on_runtime_upgrade();
  weight = weight.saturating_add(COnRuntimeUpgrade::on_runtime_upgrade());
  weight = weight.saturating_add(<AllModules as OnRuntimeUpgrade>::on_runtime_upgrade());
  <frame_system::Module<System>>::register_extra_weight_unchecked(weight, DispatchClass::Mandatory);
}

<frame_system::Module<System>>::initialize(
  block_number,
  parent_hash,
  extrinsics_root,
  digest,
  frame_system::InitKind::Full, // <-- this kills events
);
```

You will note that the `on_runtime_upgrade()` is invoked before [system::initialize()](https://github.com/paritytech/substrate/blob/2cd20966cc09b059817c3ebe12fc130cdd850d62/frame/system/src/lib.rs#L1029), and the latter resets the events with `InitKind::Full` as final argument:

So we cannot rely on any events being deposited in on_runtime_upgrade() in the query-node.

With newer version of substrate 3 [executive::initialize_block_imp()l](https://github.com/paritytech/substrate/blob/e75de5f0ed73e87f626d69d1479f3abee1aa6892/frame/executive/src/lib.rs#L292)  and [system::initialize()](https://github.com/paritytech/substrate/blob/e75de5f0ed73e87f626d69d1479f3abee1aa6892/frame/system/src/lib.rs#L1259) this "bad design" seems to have been fixed.

Going forward it seems to me that there is only one straight forward solution, which is for the query-node to handle the RuntimeUpgraded event but we would need to have that event be deposited after the ProposalExecuted event.

Alternatively we can have a mechanism similar to the system events, in the proposals engine storing events to be deposited. effectively deferring them to be deposited in proposal_engine:on_initialize.

**Comment by mnaamani** [comment]
Simpler solution:
query-node upon handling the ProposalExecuted event, and determining it was of type runtime upgrade, will update status of all other proposals to CancelledByRuntime.

**Comment by Lezek123** [comment]
Thank you @mnaamani, awsome work debugging the issue and finding a nice solution for the query node!
I'll create a new issue to implement it.

**Comment by bedeho** [comment]
Awesome work @mnaamani 🚀
