### ISSUE TITLE
Improve forum deletion extrinsic signature

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2482]
Currently it has the [following signature](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L1441) and initial processing

```Rust 
      fn delete_posts(
            origin,
            forum_user_id: ForumUserId,
            posts: Vec<(T::CategoryId, T::ThreadId, T::PostId, bool)>,
            rationale: Vec<u8>
            ) -> DispatchResult {
      
             // Check only unique post instances.
             let unique_posts: BTreeSet<_> = posts.into_iter().collect();
```

The computation of `unique_posts` is key for the security of this extrinsic, so we may as well update and make

```Rust 
 posts: BTreeMap<(T::CategoryId, T::ThreadId, T::PostId), bool>
 ```
 
 In fact, this appears to solve the current bug which allows a forum post deletor to delete the same post twice by varying the `bool` dimension.

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/issues/2482
