### ISSUE TITLE
Rendering of openings

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#2489]
Some of the openings won't render properly in pioneer, as shown in the screenshot below:

<img width="1228" alt="Screen Shot 2021-06-21 at 13 37 30" src="https://user-images.githubusercontent.com/35237943/122755809-d4f94c80-d295-11eb-886f-ef15a58cc54e.png">

There may be other reasons for other openings, but in this case, it's because the [schema pioneer uses](https://github.com/Joystream/joystream/blob/c5a8bbaf4e4aa19de435278c22fd3530bacedfc9/types/src/hiring/schemas/role.schema.json) doesn't allow `null` for `application.sections`. I'm not sure if it's the CLI or pioneer that should be updated, but one of them should!

**Comment by traumschule** [comment]
There is another inconvenience: The [default value](/Joystream/joystream/blob/master/cli/src/commands/working-groups/createOpening.ts#L70) for `reward` is `"10k JOY per 3600 blocks"` with the effect that no reward relationship is created. It seems to me that in any case neither a string nor null would be a desirable setting and it should be set to at least 1 if no useful value is entered. See `#operations` on discord for details.

Edit: This has already been reported as #2197

**Comment by traumschule** [comment]
Noticed another (minor) issue: After applying to a role and clicking `close` in the final application screen it is closed and the openings are visible again. The opening could be updated to reflect the correct number of applications (+1).

**Comment by Lezek123** [comment]
Pioneer v1, no longer relevant
