### ISSUE TITLE
Comments to videos

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#2492]
# Proposal
### T.O.C.

1.  [Goal](#org9251648)
2.  [Post structure](#orgb3b03a1)
    1.  [Post](#orgbc6c8d2)
    2.  [Replies / Comments](#org681f854)
3.  [Storage Elements](#org6d95e2f)
    1.  [Posts](#orgce6142b)
    2.  [Replies](#org00bfbc6)
4.  [Extrinsics](#orgfa3c3ab)
        1.  [Create Post](#org2899cba)
        2.  [Create Reply](#org110c126)
        3.  [Edit Post](#org02c809a)
        4.  [Edit Reply](#orgf52b304)
        5.  [Delete Post](#org0a108f4)
        6.  [Delete Reply](#org6a11afc)
        7.  [React to Post](#org1a6d6b2)
5.  [Questions & precisations](#org6c2952c)

**Target Branch**: `new_channel_features`

**Module**: `content`

<a id="org9251648"></a>

# Goal

Enrich each video with features for express a rating and comments, something similar to a
Youtube/Vimeo page.
`Basic idea` A video should start a <del>thread</del> post (since in a thread all the posted 
elements tends to be threated as simple posts/replies). Instead what we want
is a post that starts with a video and thereafter there are only replies (to 
the post or to other replies).
 Effectively it should be something along 
the lines of:

<a id="orgb3b03a1"></a>

# Post structure

<span class="underline">Basic idea</span>: A video that lives in a channel should start a  post. Once the post is set up only <span class="underline">text</span> replies are allowed by post owner and other users
We also want the video to be in the channel owned by the post owner

<a id="orgbc6c8d2"></a>

## Post

We want the video to be in the channel owner by the post owner

      pub struct Post<ChannelOwner,
    		  Hash,
    		  Balance,
    		  BlockNumber,
    		  ReplyId, 
    		  VideoCategoryId
    		  > {
          /// Id of thread to which this post corresponds.
    n
          /// Hash of current text
          pub title_hash: Hash,
    
          /// Author of post.
          pub author: ChannelOwner,
    
          /// Cleanup pay off
          pub cleanup_pay_off: Balance,
    
          /// When it was created or last edited
          pub last_edited: BlockNumber,
    
          /// Overall replies counter
          pub replies_count: ReplyId,
    
          /// video associated to the post (instead of the body hash as in the blog module)
          pub video: VideoId,
    
          /// category for this video
          pub category: CategoryId
      }

The `category` field allows to use the same structure for moderation 
(Moderators, Lead &#x2026;) as in the forum module.

<a id="org681f854"></a>

## Replies / Comments

Reply is analogous to a Youtube comment, so
every post (video)  will have zero or more replies, and also a reply can have zero or more
reply to it. It makes sense therefore to identify as a Parent a Post | Reply that 
can have zero or more replies to it.

    pub enum ParentId<ReplyId, PostId: Default> {
        Reply(ReplyId),
        Post(PostId),
    }

And a reply `struct` will be something like

    pub struct Reply<BlockNumber,
    		 ReplyId,
    		 PostId,
    		 UserId,
    		 Balance,
    		 Hash> {
        /// Reply text hash
        text_hash: Hash,
        /// Associated with reply owner
        owner: UserId, 
        /// Reply`s parent id
        parent_id: ParentId<T::ReplyId, PostId>,
        /// Pay off by deleting post
        cleanup_pay_off: Balance,
        /// Last time reply was edited
        last_edited: BlockNumber,
    }

<a id="org6d95e2f"></a>

# Storage Elements

<a id="orgce6142b"></a>

## Posts

Stored by means of a single map

    pub PostById get(fn post_by_id) config() : map
        hasher(blake2_128_concat) PostId => Post;

<a id="org00bfbc6"></a>

## Replies

Stored by means of a double map (PostId, 

    ReplyById get (fn reply_by_id): double_map hasher(blake2_128_concat) PostId, hasher(blake2_128_concat) ReplyId => Reply>;

<a id="orgfa3c3ab"></a>

# Extrinsics

<a id="org2899cba"></a>

### Create Post

We have to make sure that the post owner is the owner of the channel that the video belongs to.

      pub fn create_post(origin,
    		     title: Hash,
    		     video: VideoId,
    		     category: CategoryId
      ) -> DispatchResult 
    {
        ...
    	let post_owner = <ChannelById>::get(
    	    <VideoById>::get(video)
    		.in_channel)
    	.channel_owner;
        ...
    }

<a id="org110c126"></a>

### Create Reply

    pub fn create_reply(
        origin,
        owner: UserId,
        post_id: PostId,
        reply_id: Option<ReplyId>,
        text: Hash,
    ) -> DispatchResult {

`reply_id` will be different from `None` in case of nested replies.

<a id="org02c809a"></a>

### Edit Post

    pub fn edit_post(
        origin,
        post_id: PostId,
        new_title: Option<Hash>
        new_video: Option<VideoId>
    ) -> DispatchResult {

We must make sure that origin is signed by the post owner.
If `new_title` (resp. `new_video`) are none title (video) stays the same.

<a id="orgf52b304"></a>

### Edit Reply

    pub fn edit_reply(
        origin,
        owner: UserId,
        post_id: PostId,
        reply_id: T::ReplyId,
        new_text: Hash
    ) -> DispatchResult

Replace the reply `[ReplyId,PostId]` (if it exists) in the `ReplyById` map using
 the new parameters, after ensuring that `origin` is signed by the owner of the reply
in question.

<a id="org0a108f4"></a>

### Delete Post

    pub fn delete_post(
        origin,
        owner: ChannelOwner,
        post: PostId,
    ) -> DispatchResult

After making sure that `origin` is signed by the `post` owner, delete the post and
`possibly` all the replies to it.

<a id="org6a11afc"></a>

### Delete Reply

    pub fn delete_replies(
        origin,
        owner: UserId,
        reply: ReplyId,
    ) -> DispatchResult

After ensuring that `origin` is signed by the owner of `reply`, delete the reply in question
and `possibly` all the replies to it.

<a id="org1a6d6b2"></a>

### React to Post

    fn react_post(origin,
    	      post: PostId,
    	      react: PostReactionId
    ) -> DispatchResult

Add a reaction to the post

<a id="org6c2952c"></a>

# Questions & precisations

1.  Should I write the code in a new file and in a new pallet
2.  When I delete a reply should also delete all the replies to it? Same thing when deleting a post?
3.  I used `UserId` to represent a reply owner different from `ChannelOwner` on purpouse:
    you can reply even if you don't own a channel. Effectively `UserId` will be
    `common::MemberId` (that is the member of the system).
4.  Should I add a `reaction_score` field to the `Post` data structure in order to keep
    track of the reaction? It appears that in the forum module a reaction causes only an 
    Event deposit

**Comment by dobertRowneySr** [comment]
@bedeho  tell me what you think

**Comment by dobertRowneySr** [comment]
### Progress:
- [X] Outline 
- [x] Data structure implementation
- [x] Storage Items Implementation
- Extrinsics Implementation
    - [x] `create_post`
    - [x] `delete_post`
    - [x] `edit_post`
    - [x] `create_reply`
    - [x] `edit_reply`
    - [x] `delete_reply`
    - [x] `react_to_post`
- [x] Testing

**Comment by bedeho** [comment]
Nice work, here are some comments.

- Lets drop all hash fields, they have never turned out to be useful.
- Why is `Post::category` needed? this information already lives in the parent video.

# Answers to questions

> Should I write the code in a new file and in a new pallet

A pallet and a file are two unrelated units of organization, you can have something in the same pallet but different files, because one pallet can be made up of multiple files. The new code should stay in the same content pallet now, but one of the challenges we are facing over time is that we are starting to have an increasingly large number of very similar discussion/commenting systems in the runtime. So it may be a good idea to think about how we possibly could try to abstract this functionality into a standalone module that could be re-used.

If you have any thoughts here, then let me know. But we don't need to figure it out right now. Refactoring late is often a good idea.

> When I delete a reply should also delete all the replies to it? Same thing when deleting a post?

No, you cannot do that, as there could be a possibly very large number of replies, and users could attack the chain my first making many replies, and then triggreing a delete operation that cannot finish within the require time constraints. When you delete, you only delete that object.

> Effectively UserId will be common::MemberId (that is the member of the system).

Correct.

> It appears that in the forum module a reaction causes only an
Event deposit

This is fine, the runtime does not have any need to maintain such a score, the indexing infrastructure (called a query node) can build such higher level representations itself based on such reaction events.

**Comment by dobertRowneySr** [comment]
> Why is Post::category needed?

Oversight by me. It's actually redundant as you pointed out

**Comment by dobertRowneySr** [comment]
It appears that there is a rust problem where the generic parameters need to comply with the bounds instead of the associated traits (https://github.com/rust-lang/rust/issues/26925).
For example this
``` rust
#[derive(Encode, Decode, Clone, Debug)]
pub struct Post<T: Trait> {
    ...
    pub video: T::VideoId,
    ...
}
```
forces `T` to implement the `Debug` trait.
 I have seen two possible solutions:
1. Implements traits (such as `Debug`) for `Post` by hand
2. Use type aliasing:
``` rust
#[derive(Encode, Decode, Clone, Debug)]
pub struct Post_<VideoId, ...> {
    ...
    pub video: VideoId,
    ...
}
pub type Post<T> = Post_<T::VideoId, ...>;
```
@bedeho  Do you have any preferences/suggestions?

**Comment by dobertRowneySr** [comment]
The `olympia` runtime uses the `MemberOriginValidator::is_member_controller_account` from `common::membership::MemberOriginValidator` to ensure that a member account for the given member id exists. This function is missing from the `sumer` runtime. Should I add it here too?

**Comment by bedeho** [comment]
> Should I add it here too?

No just use whatever is alrady being used for this purpose in `sumer`, membership authentication is already present in the content directory pallet, is it not?

> Do you have any preferences/suggestions?

Sorry for the late reply, I asked @iorveth to answer, but I guess he lost track. This is not a new issue, what are you seeing being done in the rest of the runtime, or just in this pallet, for this issue?

**Comment by dobertRowneySr** [comment]
It appears that in the Sumer runtime the 2nd approach is used as `Channel` is aliased from`ChannelRecord`.
In the olympia runtime (where this issue is explicitly recognized) the first approach is used as the `Debug` trait is implemented by hand

**Comment by iorveth** [comment]
> It appears that there is a rust problem where the generic parameters need to comply with the bounds instead of the associated traits (https://github.com/rust-lang/rust/issues/26925).
> For example this
> ``` rust
> #[derive(Encode, Decode, Clone, Debug)]
> pub struct Post<T: Trait> {
>     ...
>     pub video: T::VideoId,
>     ...
> }
> ```
> forces `T` to implement the `Debug` trait.
>  I have seen two possible solutions:
> 1. Implements traits (such as `Debug`) for `Post` by hand
> 2. Use type aliasing:
> ``` rust
> #[derive(Encode, Decode, Clone, Debug)]
> pub struct Post_<VideoId, ...> {
>     ...
>     pub video: VideoId,
>     ...
> }
> pub type Post<T> = Post_<T::VideoId, ...>;
> ```
> @bedeho  Do you have any preferences/suggestions?

Hey. Sure, this approach looks like a good idea to deal with aforementioned issue and store runtime structures. 
I have been rework content-directory runtime structures implementation in a similar way a while ago. 

Sorry for delay, @bedeho :)

**Comment by iorveth** [comment]
I should say that it's very bad approach for `trait` abstraction in cases like that.

Just wanted to save some editor space, avoiding to write few generic arguments with separate `Trait` bounds for each in my early days here :)

**Comment by iorveth** [comment]
> MemberOriginValidator::is_member_controller_account

No need to add any new features to `sumer` runtime. @shamil-gadelshin and @Lezek123  are already working on merging both branches.

**Comment by iorveth** [comment]
When I delete a reply should also delete all the replies to it? Same thing when deleting a post?

`No, you cannot do that, as there could be a possibly very large number of replies, and users could attack the chain my first making many replies, and then triggreing a delete operation that cannot finish within the require time constraints. When you delete, you only delete that object.`

I think it's possible to deal with this issue by providing `DestroyWitness` structure, which have to contain the same number of replies to a post (reply), as you actually have.
If you'll provide a wrong number, extrinsic would just return after counters mismatch error.
It would allow us to properly benchmark such cases and set very high fee to punish such a behaviour, as you always know the number of replies to the specific post. 

Please, have a look at https://github.com/paritytech/substrate/blob/e6cd6b1240ce741f06b05ad1c59f5399e52e717a/frame/uniques/src/lib.rs#L402

What do you think about it, @bedeho ?

**Comment by dobertRowneySr** [comment]
> I should say that it's very bad approach for `trait` abstraction in cases like that.
> 
> Just wanted to save some editor space, avoiding to write few generic arguments with separate `Trait` bounds for each in my early days here :)

Are you referring to the first approach I discussed (implementation by hand)? @iorveth

**Comment by iorveth** [comment]
> > I should say that it's very bad approach for `trait` abstraction in cases like that.
> > 
> > Just wanted to save some editor space, avoiding to write few generic arguments with separate `Trait` bounds for each in my early days here :)
> 
> Are you referring to the first approach I discussed (implementation by hand)? @iorveth 

Yes, multiple generics with trait implementation by hand, where necessary is right approach here, we should avoid direct `Trait` inheritance, you mentioned. 

```r
#[derive(Encode, Decode, Clone, Debug)] pub struct Post<T: Trait> { ... pub video: T::VideoId, ... }
```

**Comment by dobertRowneySr** [comment]
> > MemberOriginValidator::is_member_controller_account
> 
> No need to add any new features to `sumer` runtime. @shamil-gadelshin and @Lezek123 are already working on merging both branches.

Do this means that I should live this aside for now and wait for both branches to be merged?

**Comment by iorveth** [comment]
> > > MemberOriginValidator::is_member_controller_account
> > 
> > 
> > No need to add any new features to `sumer` runtime. @shamil-gadelshin and @Lezek123 are already working on merging both branches.
> 
> Do this means that I should live this aside for now and wait for both branches to be merged?

Oh, i see. To not make the same changes twice, I hope it would be a good idea to base your work on `olympia-master` runtime branch,  https://github.com/shamil-gadelshin/substrate-runtime-joystream/tree/olympia-master-runtime-merge 
It`s not merged, but looks good to me.

**Comment by dobertRowneySr** [comment]
# Unit Tests plan
## Extrinsic specifications:
1.`create_post(origin, video_id, actor)` 
*Preconditions*:  `video_id` is a valid existing video AND `actor` is an existing actor Account AND such account is the owner of the channel for the video 
*Effect*: Post is added to the storage AND `NextPostId` storage item is is increased by exactly 1 AND appropriate event is deposited
2. `edit_post(origin, post_id, new_video_id, actor)`:
*Preconditions*: `post_id` represent an existing post AND `actor` is a valid actor Account AND 'actor' is also owner of the channel which the post belongs to, 
*Effect*: update the post video with `new_video` AND appropriate event is deposited
3.  `delete_post(origin, post_id, actor)`:
*Preconditions*: `post_id` represent an existing post AND `actor` is a valid actor Account AND 'actor' is also owner of the channel which the post belongs to, 
*Effect*: post is removed from storage AND appropriate event is deposited
4.`create_reply(origin, post_id, participant_id, reply_id)` 
*Preconditions*:  when post_id is a valid existing reply id AND (`reply_id` is None OR It refers to a valid reply for `post_id` ).
*Effects*: Reply is added to storage AND the reply number for the parent Post is incremented by exactly 1 AND appropriate event is deposited
5. `edit_reply(origin, post_id, participant_id, reply_id, new_text)`
*Preconditions*: `reply_id` together with `post_id` indicates a valid reply AND `participant_id` is a valid member AND `participant_id` is the owner of the channel which the post belongs to.
*Effects*: modify the hash text of the reply with `new_text` AND appropriate event is deposited
6.  `delete_reply(origin, post_id, reply_id, participant_id)` 
*Preconditions*:  `reply_id` together with `post_id` indicates a valid reply AND `participant_id` is a valid member AND `participant_id` is the owner of the channel which the post belongs to.
*Effects*: removes the reply from storage AND decrements the `replies_count` for `post_id` by exactly 1 AND appropriate event is deposited
7. `react_to_post (origin, participant_id, post_id, reaction_id)` 
*Preconditions*: `post_id` refers to an existing post AND `participant_id` is a valid member account
*Effects*: appropriate event is deposited

## Testing
I would add an assert failure for every precondition violation. 
When preconditions are respected desired effects should be verified

**Comment by dobertRowneySr** [comment]
## Test Progress 
- [x] `create_post`
- [x] `edit_post`
- [x] `delete_post`
- [x] `create_reply`
- [x] `edit_reply`
- [x] `delete_reply`
- [x] `react_to_post`
