### ISSUE TITLE
Query node: ability to remove video/channel assets on update

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2496]
There is no easy way to remove an asset while updating the channel or video.

Right now, for unsetting channel/video asset (thumbnail, avatar photo, etc.), there is a need to execute a batch transaction in applications as Atlas. 
```
api.tx.utility.batch([
    api.tx.content.updateChannel(..),
    api.tx.removeChannelAssets(..)
])
```

If only `updateChannel` is called, an asset may be unset, but it will not be deleted from the content directory. Repeting that will eventually result in user running out of data quota.

For Olympia, we can improve `update_channel` and `update_video` extrinsic and protobuf used in them to provide the ability to request asset delete.

For Sumer, we should ensure that the batch transaction shown above is always used. If forgotten ex-channel-asset becomes an issue and quota depletion will become a problem for many users, we should ensure a GUI will allow users to call `remove_channel_assets` extrinsic to get rid of those assets.

This is not a high priority issue and there might be a better solution(s).

**Comment by bedeho** [comment]
Is this still an issue?

**Comment by kdembler** [comment]
If I'm not mistaken, after Giza this would be done automatically - update extrinsic contains `assets_to_remove` array so if I'm interpreting this correctly, we don't need this anymore
