### ISSUE TITLE
MemberProfileUpdated event only emitted when handle is modified

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2503]
During some tests related to `master`->`olympia` merge I noticed that `MemberProfileUpdated` event is only emitted when new handle is provided:
https://github.com/Joystream/joystream/blob/olympia/runtime-modules/membership/src/lib.rs#L507

This prevents the query node from parsing any metadata updates if the `newHandle` is set to `null`.

**Comment by shamil-gadelshin** [comment]
Done.
