### ISSUE TITLE
Can't upload videos via CLI on MacOS ARM64

### ISSUE THREAD

**Issue by elif42** [Joystream/joystream#2517]
Due to the [problems](https://github.com/Joystream/atlas/issues/985) I have been having uploading videos via the browser, I decided to try using the CLI. Unfortunately, I keep on getting the following error message 

``Error: Unsupported platform/architecture: darwin-arm64``.

**Comment by mnaamani** [comment]
Could you share more of the output from the cli when you tried to upload the video

**Comment by elif42** [comment]
@mnaamani ```Error: Unsupported platform/architecture: darwin-arm64```

**Comment by ghost** [comment]
@mnaamani  It seems to be an issue related to the new Apple M1 processors.

**Comment by traumschule** [comment]
duplicate of #2360

**Comment by mnaamani** [comment]
This was resolved in newer version of cli
