### ISSUE TITLE
Compress on-chain text

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2554]
We store lots of different kinds of text data in our ledger, for example content metadata, proposal texts, forum texts, etc. It could be worth exploring making the metdata standard for such text include compression for such texts. This can compress size of data down to anywhere from 30%-2% of original size. The most aggressive forms of compression require committing the user to some dictionary, in which case we would probably need to have a few standard ones in our standard to support multiple languages. There is also special kinds of compression that work very well for short texts. So all in all there is a big design space here, and it could really reduce the cost for users, and reduce the cost of synching and maintaining a node long term. The complexity seems low, as it would only require front-ends to follow the convention, as well as the query node when it processes the raw data and exposes it in compressed form.

Am I missing something here?

**Comment by traumschule** [comment]
Still a good idea but a bit late. Frontend tools would need to be able to support both versions and decrypt newer content on demand. Or you loose access to already submitted content without compression.

**Comment by bedeho** [comment]
Yes you are right, dual support is needed, but this will be the case with virtually all metaprotocol standards, they will exist in multiple parallel versions, and different people will make new standards to incoprate additional things, this is also why JIP processs is needed for visibility and coordination.

**Comment by bedeho** [comment]
Superceeded by https://github.com/Joystream/joystream/issues/4703
