### ISSUE TITLE
Bug: Pioneer v1 - Loading proposal votes/comments takes very long

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2556]
Problem: loading the votes/comments of a proposal as a CM takes up to 2.5 minutes. The proposal text/description will load at an expected speed (15-20 seconds) but once the page requests the comments + votes, and a user is logged on as a CM it will take an extremely long time.

Some points worth noting:
- If not logged on as a CM, this issue is not present (credit: freakstatic for this)
- While loading as a CM, the blockheight will not increase (the page is not frozen, but something weird happens with it)

**Comment by mochet** [comment]
related: https://github.com/Joystream/pioneer/issues/867

**Comment by bedeho** [comment]
# Hard solution

Would it be totally nuts to have the operations working group try to add query node support for the proposal system and actually update Pioneer v1 to use it? They will be able to look at the example code on the query node side and Pioneer side in our work on Pioneer v2, which has both updated?

It would make the system work fast and smooth, but it would require time for the developer to understand what is going on and build it out. Pioneer is still 2+ months away, so it may have some value both in use and for the developers to get some practice with the query node.

# Hacky solution

We change Pioneer v1 to only load pending proposals from the chain, everything else is stored as static data inside Pioneer v1 itself! This is kind of nuts, but may be a super fast hack.

**Comment by mochet** [comment]
I've passed the task to Operations to see what they think about.

In the meantime some other information on this bug:
- A proposal accessed with a CM key, but the CM never voted and the proposal is finalized = 2.5 minutes to load
- A proposal accessed with a CM key, but the CM has already voted and the proposal is finalized = seconds to load
- This appears to be a UI issue, as when this bug triggers, the blockheight will freeze. If the user switches to the `explorer` view when encountering this error, the UI will suddenly process all of the blocks that were produced almost instantly.

The only changes I have found in recent time, were the introduction of the FM banners on Pioneer v1 and also a spelling correction on the actual voting form: https://github.com/Joystream/joystream/pull/2519/commits/f5c740858661e2cc89b8bc6e4b9960da7ba7ce32

**Comment by freakstatic** [comment]
It seems that the problem can be seen debugging this lines:
https://github.com/Joystream/joystream/blob/b43d9e1737c741ea9cb6ae8e14b85fdbe7c4b4d2/pioneer/packages/joy-utils/src/transport/proposals.ts#L205

and by openning the proposal: 378 with the endpoint:
wss://rome-rpc-endpoint.joystream.org:9944

this testnet URL can be used as well:
https://testnet.joystream.org/#/proposals/378

I'm getting this times:
![image](https://user-images.githubusercontent.com/7486476/128384324-2c783cff-bd71-42b8-8476-9e5e766a660d.png)

by checking the API connection I saw this:
![image](https://user-images.githubusercontent.com/7486476/128384686-512e75f9-7f9a-4c1c-a1bd-7325a0faf5d7.png)

the first request is a `api.query.members.membershipById` call

**Comment by freakstatic** [comment]
I was able to find what was taking so long to fetch. It's when checking if the council member has voted.
in this line: https://github.com/Joystream/joystream/blob/b43d9e1737c741ea9cb6ae8e14b85fdbe7c4b4d2/pioneer/packages/joy-utils/src/transport/proposals.ts#L191

**Comment by mochet** [comment]
I believe this has basically been solved by @freakstatic so closing the issue
