### ISSUE TITLE
Yarn version 3

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2563]
There has been a release of Yarn v3 recently that can bring a lot of new features that Joystream projects could benefit from. Currently, we are using Yarn v1 installed via `volta`. Volta is not supporting Yarn v3 yet, but it is possible it will happen in the near future (https://github.com/volta-cli/volta/issues/651), and even if not, the v3 should be installable by manually calling

```
yarn set version berry
yarn set version 3.x
```

Among other things, the new version could improve performance, simplify the development of multiple dependent projects (e.g. Warthog -> Hydra -> Joystream monorepo), improve workspaces support, etc. See https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#300 for more info.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711169249465) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Covered this issue https://github.com/Joystream/joystream/issues/3017
