### ISSUE TITLE
Channel deletion

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2572]
We should introduce channel deletion, but it should only be possible when 

- the channel is has no assets (old or in use data objects)
- videos or corresponding assets

and it has to result in the bag for the channel getting dropped as well.

Currently we have a channel representation like this

```Rust 
pub struct ChannelRecord<MemberId, CuratorGroupId, DAOId, AccountId, VideoId, PlaylistId, SeriesId>
{
    /// The owner of a channel
    owner: ChannelOwner<MemberId, CuratorGroupId, DAOId>,
    /// The videos under this channel
    pub videos: Vec<VideoId>,
    /// The playlists under this channel
    playlists: Vec<PlaylistId>,
    /// The series under this channel
    series: Vec<SeriesId>,
    /// If curators have censored this channel or not
    is_censored: bool,
    /// Reward account where revenue is sent if set.
    reward_account: Option<AccountId>,
}
```

However, the collections `videos`, `playlists` and `series` are not needed, they are remnants of a time where were we imagined channel deletion implied automated deletion of all content in the channel. 

All we need now is reference counting of then number of videos in each channel to block deletion of non-empty channels, as well as a way to ask the storage module whether there are any existing data objects owned by this channel. 

For convenience we should probably add the ability for the user to make an atomic call to both delete channel assets and the channel in one go, similar to when creating the channel or a video, so something like

```Rust

pub fn delete_channel(
 ...
 atomically_drop: BTreeSet<DataObjectId>
)
```

**Comment by dobertRowneySr** [comment]
For Personal reference:
### Preconditions:
- actor must be channel Owner
- ensure number of videos in the channel == 0
- ensure number of assets owned by the channel == 0
### Postconditions:
- channel information removed from on-chain state
