### ISSUE TITLE
Improve video deletion

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2574]
Lets make it easier to simultaneously delete a video and its associated assets by making the `delete_video` extrinsic able to atomically also delete a list of corresponding data objects. We do not try to check that this is an exhaustive list of all the assets used by the video, this would require very invasive changes with limited upside, and it is still possible to manually delete those assets later using `delete_channel_assets`.

**Comment by iorveth** [comment]
@bedeho Good idea, but i think about recently introduced video nfts. 
Do we plan to include video nfts into Giza release? 
If so, how would we handle a case, when video has an nft issued already?

**Comment by bedeho** [comment]
This is a fantastic question, very good points. I don't think we should introduce NFTs in Giza, however, the core issue still stands. I can only think of both the NFT and the video living together, thats the only thing that makes sense. Do you see another option?

**Comment by iorveth** [comment]
Agree, i can't come with any reasonable idea except of forbidding both videos & channels deletion if any related video nft exists for now.

**Comment by bedeho** [comment]
Hmm, yes, interesting.

**Comment by iorveth** [comment]
> Hmm, yes, interesting.

I think that we can represent video data as 

```rust
decl_storage! {
    trait Store for Module<T: Trait> as Content {
        pub VideoById get(fn video_by_id): map hasher(blake2_128_concat) T::VideoId => VideoData<T>;
}

pub enum VideoData<AccountId, ChannelId, SeriesId, BlockNumber, MemberId, CuratorGroupId, DAOId, Balance> {
        Video(Video<AccountId, ChannelId, SeriesId, BlockNumber, MemberId, CuratorGroupId, DAOId, Balance>), 
        StandaloneNFT(OwnedNFT<AccountId, BlockNumber, MemberId, CuratorGroupId, DAOId, Balance>),
}
```
After we delete a video, we can still hold `OwnedNFT`.
We can consider hosting vNFTs on decentralized storage platforms (filecoin, arwave, etc.) after the video deletion.

What do you think about it?

**Comment by bedeho** [comment]
Something like this would def. work, but what would we do with the actual assets, like the video, images, .etc? It's not clear who owns them, who can delete them, or are they deleted with the original video? Also, it's not clear how to treat them in the product UX, as they would just exist as standalone videos without a channel? Perhaps there is a way to address all of these questions, but it is not trivial when considering everything outside the runtime.
