### ISSUE TITLE
Giza Releas Plan

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2580]
# Note

This is a preliminary document, it must be checked by key contributors to give input on expected full costs of various intended changes, and also whether goals in one area are fully reflected in requirements of dependant areas.

# Name

`Giza`

# Brand

![129342535-d7272868-c8c3-41e0-86d7-36f92a15a284](https://user-images.githubusercontent.com/437292/132538348-65435d65-7683-4bfe-96c1-ed45d29b2774.png)

# Goals

### 3. `New operations working groups.`

# Overview

## V2 Storage and distribution system

We are finally introducing the v2 iteration of our storage and distribution system. It is the implementation introduced in this release which will be the base of what we use on mainnet. The major new properties of this system are

- Distinct roles for storage and distributing data: this implies two distinct nodes being introduced, `Colossus` and `Argus`, respectively.
- Storage system with redundancy and only partial replication in nodes.
- Distribution system with flexible policy space, allowing for CDN like organisation.
- On-chain host resolution metadata.

A more detailed design can be found here

https://github.com/Joystream/joystream/issues/2224

## Content directory enhancements

Here the goal is to basically do smaller changes to

- Cleanup technical debt
- Unlock some new community initiatives we have planned.
- Integration with new storage system

## New operations working groups

The operations working group has been a big success, but one of the limits is that each group is a single decision making hierarchy is where one lead is a bottleneck of decision making and knowledge. In order to facilitate work on a few different orthogonal areas, or even to just scale up efforts within the same vertical, we are going to add two new generic operations working groups. From this release on we will be identifying the working groups with a letter, so in total we will now have operations working groups `A`, `B` and `C`. It will be the task of the council, with possible input from the KPI incentives, to decide the scope for should be the scope of each group at any given time.

### Team

- **Shamil**
- **Ignazio**

#### Storage & Distribution System

- Basic implementation the runtime module for storage & distribution system: https://github.com/Joystream/joystream/issues/2224
- Update representation to facilitate integration with content directory.
- Remove all references to DAOs, this has implications for removal in other places, then lets remove from there also.

#### Content Directory

- Cleanup channel representation & introduce deletion: https://github.com/Joystream/joystream/issues/2572
- Simplify video deletion: https://github.com/Joystream/joystream/issues/2574
- Temporary content directory god mode: https://github.com/Joystream/joystream/issues/2577
- Integration with new storage system in
  - channel creation
  - channel asset updating
  - channel deletion
  - video creation
  - video deletion
- Remove all references to DAOs, this has implications for removal in other places, then lets remove from there also.

#### Working group

- Introduce storage working group.
- Introduce distributor working group.

#### Proposal System

- Introduce support for storage working group in proposal system.
- Introduce support for distributor working group in proposal system.

#### Events Decoration

Add rich events with full parmeter payload for all of the following extrinsics to address https://github.com/Joystream/joystream/issues/2617

- `members.MemberRegistered`
- `members.MemberUpdatedAboutText`
- `members.MemberUpdatedAvatar`
- `members.MemberUpdatedHandle`
- `members.MemberSetRootAccount`
- `members.MemberSetControllerAccount`

### Current Status

- Most of the work on the storage and distribution system is done.
- No work done on the working groups, proposal system and content directory.

### Initial Division of labour

- **Ignazio** does everything else
- **Shamil** does storage system, working groups and proposals.

### Team

- **Shamil**

### Work Scope

- Build a new node.
- CLI based control of the node and the lead role.
- Service API for sharing state of node.
- Connection with query node.
- Synchronisation with current state of chain.
- Logging of all major events.
- Deployment using Docker.
- Integration tests.

### Current Status

- Substantial work has been completed on the node side as indicated here:https://github.com/Joystream/joystream/issues/2573#issue-968349914
- Major outstanding work is on synchronisation, testing & benchmarking.

### Initial Division of labour

- **Shamil** only.
- **Mokhtar** on testing & benchmarking.

### Team

- **Leszek**

### Work Scope

- Build a new node.
- CLI based control of the node and the lead role.
- Service API for sharing state of node.
- Connection with query node.
- Synchronisation with current state of chain.
- Cache based storage policy.
- Logging of all major events.
- Deployment using Docker.

### Current Status

- Substantial work has been completed on the node side as indicated here:https://github.com/Joystream/joystream/issues/2553
- Major outstanding work is on synchronisation, testing & benchmarking.

### Initial Division of labour

- **Leszek** only.
- **Mokhtar** on testing & benchmarking.

### Team

- **Andy**
- **Leszek**

### Work Scope

Update to work with new business logic introduce in content directory, possibly involving changing input schema.

### Current Status

- Basic modelling of the new storage system is there, but its not complete.
- Content directory needs significant updating.
- Update mappings to use hydra v3, or even v4 if feasible?
- Update mappings to use protobufjs

### Initial Division of labour

Team figures it out internally.

### Team

- **Bedeho**

### Work Scope

Provide a sufficiently detailed overview of the storage system, as it works in this release, to allow other developers and the community, in particular the Atlas developers, and later Pioneer 2, to conceptually understand how it works.

### Current Status

Not started.

### Initial Division of labour

- **Bedeho** does everything.

### Team

- Atlas Team

### Work Scope

- Update to use new query node schema
- Update to use new extrinsics.
- Introduce ability to delete channels.
- Deal with local storage of users holding identifiers that refer to content that no longer exists after upload.

### Initial Division of labour

Klaudiusz will allocate tasks internally in Atlas team.

### Team

- **Edvin**

### Work Scope

- Incorporate new distributor and storage working groups into working groups section.
- Incorporate new distributor and storage working groups into proposals.
- Incorporate two new operations working groups.

### Initial Division of labour

**Edvin** does it all.

### Team

- **Mokhtar**

### Work Scope

- Export content and assets from snapshot of `Sumer` to be used for mass uploading
- Update mass uploading script to populate after upgrade with channels and videos.
- CLI: Incorporate two new operations working groups.

### Current Status

Nothing is done here.

### Initial Division of labour

**Mokhtar**

### Team

- **Shamil**
- **Leszek**
- **Mokhtar**

### Work Scope

- Updated to work with runtime upgrade.
- https://github.com/Joystream/joystream/issues/2551

### Current Status

Nothing has been done.

### Initial Division of labour

Unclear.

### Team

- **Mokhtar**

### Work Scope

1. Status server
2. Telegram bots
3. Storage system
4. Polkadotjs library & examples: update to use Polkadotjs 5.2+ (or just newest 5.7)
5. Query node instance

### Current Status

Nothing has been done.

### Initial Division of labour

Unclear.

### Team

- **Martin**
- **Ben**

### Work Scope

- Write testing plan in advance and share with Bedeho.
- Conduct test in accordance with plan. The testing here should be targeting CLI, Query Node and Atlas working well together. There are very minor new features, but they are of trivial significance, its mostly about confirming that existing functionality still works. CLI should be a bit more involved, as there will be some new non-trivial features. Part of the rationale for the testing is also to help get informed for updating tutorials.

### Current Status

Nothing has been done.

### Initial Division of labour

Not determined.

### Team

- **Martin**
- **Ben**

### Work Scope

- Update website for announcement.
- Update website for release.
- Update tutorials.
- Update KPIs
- Announcement and release communications: blog + newsletter

### Current Status

Nothing has been done.

### Initial Division of labour

Not determined.

# Project Management

## Release Manager

`Bedeho`

The release manager is responsible for tracking overall progress, detecting delays and course-correcting. Tracking will be done weekly in this issue

https://github.com/Joystream/joystream/issues/2002

as described by the following methodology

https://github.com/Joystream/joystream/issues/474

## Release Branch

https://github.com/Joystream/joystream/tree/giza

## Github Project(s)

We are doing everything in one project.

https://github.com/orgs/Joystream/projects/43

### Biweekly(ish) Release Meetings

A release wide meeting will be organised semi-regularly, we could start at a pace of once ever 2 weeks to begin with. Experience has shown that, even when there is no obvious issues that need tackling, discussions often reveal issues and corner cases that have not been accounted for. We can aim for one team rep. being present, so as not to distract everyone. Log will be kept here:

https://github.com/Joystream/joystream/issues/2579

**Comment by Lezek123** [comment]
> Atlas

I think a lot of work will be related to dealing with the new distribution system, as that would require finiding the most approperiate endpoint for each asset, possibly based on geolocation (see `Distribution bucket families` section under `Metadata standards` at https://github.com/Joystream/joystream/issues/2553). This could be a non-trivial task, due to complex `family`->`buckets`->`operators` and `bucket`->`bags`->`objects` relationships. I think this part may require some rethinking.

> Manual QA
> CLI should be a bit more involved, as there will be some new non-trivial features.

Just pointing out that, as we agreed, a lol of the new features will not be part of `@joystream/cli`, but rather separate `distributor-node` and `storage-node` CLIs. The `@joystream/cli` will probably only include some changes related to content-directory and uploading.

> Query Node

I did some refactorization of content directory mappings during `master`->`olympia` merge, which also involved the upgrade to Hydra `v3`. Perhaps it would be a good idea to make use of this work and also update all other mappings to Hydra v3, which shouldn't take very long time but will have many befenits in terms of relationship filtering, variant relationships, block ranges (which will be required in some form anyway, since we'll be doing a runtime upgrade) etc.

It may be challanging to introduce full integration tests coverage, but if we'll have a script that exports all `Sumer` content, initializes the content directory and batch-uploads all the data, this would be a pretty good test in itself.

Probably some new bootstrap scripts will also be needed

**Comment by traumschule** [comment]
Goals 1-3 achieved without major issues. Great work!

**Comment by bedeho** [comment]
Indeed :)
