### ISSUE TITLE
Research: Proposal Abstain fix suggestions + research

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2589]
During the testnet phase there have been a few peculiar proposals that highlight the issue of both `Abstain votes` and `Reject votes`. These can either lead to situations where a proposal with a 1/16 reject votes can be `rejected` or lead to situations that often require up to 95%+ voter participation for something as simple as a `text proposal`.

I will be researching a few other DAOs and trying to come up with an alternative system or a proposal for changing the influence of `Abstain votes` in particular. Currently, it is understood that `abstain` votes are equally treated to `reject` votes, which causes a problem as an abstain vote is not a rejection of the proposal but can be used for other reasons (lack of knowledge, conflict of interest and other reasons)

These are detailed here:
* https://github.com/Joystream/joystream/issues/2383
* https://github.com/Joystream/joystream/issues/1958

### Current Issues
* Abstain vote influence on outcome (requiring a higher number of approval votes than without an abstain vote)--this can raise voter participation requirements up to 93.75% which is extremely high.
* Early abstain/reject votes can make a proposal not pass, whereas if approvals are cast first the result can be different.
* The current system does not differentiate between a real `rejected` proposal and just one that failed to reach quorum. These are two distinct things. This is explained here: https://github.com/Joystream/joystream/issues/1958#issue-772670650. The outcome of this problem is that we end up with proposals that will **never** pass regardless of the remaining votes that take up valuable council time/attention.

### Basic reading (concerning traditional, non-crypto voting systems)
* https://robertsrules.com/frequently-asked-questions/ - Robert's Rules of Order 
```The phrase “abstention votes” is an oxymoron, an abstention being a refusal to vote. To abstain means to refrain from voting, and, as a consequence, there can be no such thing as an “abstention vote.”```

```In the usual situation, where the rules require either a “majority vote” or a “two-thirds vote,” abstentions have absolutely no effect on the outcome of the vote since what is required is either a majority or two thirds of the votes cast. On the other hand, if the rules explicitly require a majority or two thirds of the members present, or a majority or two thirds of the entire membership, an abstention will have the same effect as a “no” vote. Even in such a case, however, an abstention is not a vote and is not counted as a vote. [RONR (12th ed.) 44:1, 44:3, 44:9(a); see also p. 66 of RONR In Brief.]```
* https://www.boardeffect.com/blog/roberts-rules-of-order-cheat-sheet/ - Robert's Rules of Order
* https://en.wikipedia.org/wiki/Robert's_Rules_of_Order - Robert's Rules of Order

### Other DAOs / Governance systems / Research
* https://www.sputnik.fund/#/dao/createbase.sputnikdao.near - Only has approve or reject votes
* https://wiki.polkadot.network/docs/learn-governance - Polkadot - Doesn't look like it has any option to cast an abstain vote. Only options are approve, reject or to not vote.
* https://medium.com/daostack/voting-options-in-daos-b86e5c69a3e3 - `In quorum-based voting, people against a proposal often abstain since they are more likely to prevent a proposal from passing this way than to vote no.`
* https://medium.com/coinmonks/the-voting-game-in-daos-7f989ff68712
* https://academy.horizen.io/horizen/expert/dao-decentralized-autonomous-organization/ - `Approval voting with a Yes-No-Abstain scheme simplifies the decision making the process a lot and is the option the team around Bingsheng, Roman, and Hamed chose for the treasury system. A score for each proposal can easily be calculated from the difference in Yes and No votes at the end of the voting period. The highest scoring proposals will receive funding in turns until the treasury pool is depleted for the month.`
* https://gov.rarible.com/t/rr-2-draft-rarible-dao-structure-community-treasury-staking-for-voting-power/ - `There should be an “abstain” option for all governance votes, to ensure that people aren’t forced into arbitrary decisions to claim rewards. If certain voters are indifferent to a proposal’s outcome, it’s healthy for governance to allow them to abstain and let more opinionated community members take the lead.`
* https://www.sec.gov/litigation/investreport/34-81207.pdf (concerning "The DAO" which was run very differently to the Joystream governance system) - `any DAO Tokens not submitted for a vote could be withdrawn or transferred at any time.
As a result, DAO Token holders were incentivized either to vote yes or to abstain from voting`
* https://docs.elasticdao.org/start-with/fair-governance - `Before a proposal can pass, at least 50% of eligible EGT must vote. A proposal which has reached quorum is considered to have passed if 60% or more of the voting EGT votes to approve it. Both of these values are subject to change by proposal.`
* https://hackernoon.com/i-built-an-ethereum-based-fully-decentralized-voting-system-5x8t34gz - No implementation of abstain votes
* https://makerdao.world/en/search?query=abstain - 0 results for abstain/abstention
* https://blog.makerdao.com/governance-polls-april-5-2021/ - `Alternatively, if you would accept any of the listed options and have no preference as to which, you should vote 'Abstain' as your first choice and rank no other choices.` 
* https://blog.makerdao.com/governance-polls-april-5-2021/ -  `If a non-'Abstain' option receives more votes than each other option (excluding 'Abstain') and the support for that option exceeds 50% of the total votes cast (excluding 'Abstain' votes), then the following actions will be taken: If the result requires a change to the current setting, the change will be included in a weekly Executive Vote on a Friday within the next 30 days. If the Friday executive passes, then this change will become active in the Maker Protocol after the GSM Pause Delay has expired.`
* https://www.horizen.io/zendao/ - Has an `abstain` option but.. `The proposal score is the number of “yes” votes minus the number of “no” votes. The Proposal to pass has to have at least a predetermined percentage of all votes.`
* https://github.com/pie-dao/docs/blob/master/papers/piedao.md - `Approved members must vote on questions raised by members of the PieDAO community. They may vote YES, NO, or ABSTAIN. Failure to vote results in the slashing of a portion of that member's stake.`
* https://bzx.network/blog/bzx-dao-vote - Unclear how abstain votes are counted, but they seem to have no influence on the outcome - `Enter the support value for the vote: 0 = Against, 1 = For, 2 = Abstain` + `A total of 41.2m votes are needed to pass.`
* https://www.navexplorer.com/dao/proposals/accepted - Has abstain option, but due to token voting system it has minimal impact even if it is counted.
* http://v1.carbonvote.com/ - The DAO Hard Fork - `If voters who after voting, decide to abstain from this vote, they can move the ETH to an address that has not yet participated in this vote.` - Abstain votes have no impact on outcome, since they are changed before the final result is called. - `So you can change your mind, you can overwrite your vote by resending your message or move the ETH from the addresses that have participated so as to suggest that you are abstaining from the vote as the ETH won’t be able to be counted as votes anymore.`
* https://uploads-ssl.webflow.com/5f7c7046bdd6dc4b7b83be0d/5f8432c64fe84c33172a7979_Spider%20Whitepaper%20(Version%200.1).pdf - `The voting state lasts 2 weeks. Rather than depositing SPDR, participants in this governance stage are actually voting Yes, No, No(With Veto) or Abstain. If a proposal reaches quorum or the minimum threshold defined by the protocol of votes,
it will pass to the next stage for tallying. Only members satisfying the voting eligibility criteria (see previous) are eligible to partake at this stage. Each hardware router is allocated a maximum of one vote assuming the voting eligibility criteria have been met. Voters can also change their vote right up until the closing period` + `Quorum: more than 40% of the total staked tokens at the end of the voting period need to have voted` + `Threshold: More than 50% or a majority of the tokens that participated in the vote, excluding “Abstain” votes must have voted “Yes”` + `Veto: Less than 33.4% of the tokens that participated in the vote, not counting “Abstain” votes, have vetoed the decision “No (With Veto)”.`
* https://docs.celo.org/celo-codebase/protocol/governance - Abstain votes exist, but no mention of their influence - `Once the Approval phase is over, approved proposals graduate to the referendum phase. Any user may vote yes, no, or abstain on these proposals. Their vote's weight is determined by the weight of their Locked Gold. After the Referendum phase is over, which lasts five days, each proposal is marked as passed or failed as a function of the votes and the corresponding passing function parameters.`
* https://blog.coinfund.io/digixdao-divorce-story-6ed74b00e2bd - `Thus, the top four voters, if treated as a coalition of 440K stake, completely controlled the vote by both (a) establishing or preventing quorum by voting or abstaining, respectively, and (b) controlling the quota and thus single-handedly being able to determine the proposal outcome. (In voting theory, such a critical voter is known as a dictator.)`
* https://daotalk.org/t/increasing-voter-participation-rates-in-genesis/584/7 - `I’d like to see a third option (Abstain) to the Yes/No vote, to capture the Recuse, Undecided, Postpone opinions, so a proposal could be allowed to fail without signaling ardent opposition.`
* https://blog.synthetix.io/synthetix-grantsdao/ - `There will be a two day ‘grace period,’ in which no votes are taken, in which the DAO members and community members can discuss the viability of the proposal. At the completion of the grace period, DAO members can vote Yes, No or abstain. If four members vote ‘Yes,’ the proposal is approved`

### Conclusions from research
* The majority of DAOs researched do not have a 1 member : 1 vote system. They have a 1 token : 1 vote system.
* Some do not have any `abstain` option at all
* Most that do have an `abstain` option, it doesn't influence the outcome of a proposal. They are either specifically excluded, or their influence isn't mentioned.
* Many do not seem like they have any `slash` mechanism as Joystream has.
* The particular example here (https://blog.coinfund.io/digixdao-divorce-story-6ed74b00e2bd) shows that abstain votes can be abused to prevent proposals from passing.
* This example is also highly interesting (https://medium.com/daostack/voting-options-in-daos-b86e5c69a3e3) - ``In quorum-based voting, people against a proposal often abstain since they are more likely to prevent a proposal from passing this way than to vote no.``

### Proposed ideas for improving Joystream Proposal Voting System
* Do not count Abstain votes in quorum and possibly vote threshold
* Reduce how Abstain votes are counted in comparison to Reject votes (for example, 1 abstain vote is only worth `0.25x` what a reject vote is worth when it comes to quorum)
* Entirely remove the Abstain vote option (obviously not a preferable option)
* Require a fixed number of `approve` votes, ignoring the reject, abstain and slash votes (for example, a `text proposal` may require 10/16, or a majority of approval votes and the reject/abstain/slash votes, while counted do not influence the outcome)
* Instead of an `approval threshold` we could just have an `outcome threshold`--if more than `n%` of votes are of a certain type, then that is the outcome of the vote.
* We could have a scoring system, rather than a quorum system. This would mean that if too many rejections/slashes are cast, the proposal could be automatically slashed instead of requiring a majority of slash votes.

**Comment by mochet** [comment]
This is an example of how I believe the current voting system works:

(Approve = +1, Abstain/Reject/Slash = -1)
Using the example of a text proposal, which requires `60% voter quorum` and an `80% approval threshold` this would not pass. There is no differentiation between abstain, reject and slash, since that is how the current system works. So the `-1` votes may be either an abstain, reject or slash. Therefore we will assume 4 of the `-1` votes are actually abstain votes.


| Proposal / CM | 1 | 2 | 3 | 4 | 5 | 6 | 7  | 8  | 9  | 10 | 11 | 12 | 13 | 14 | 15 | 16 | SUM |
|---------------|---|---|---|---|---|---|----|----|----|----|----|----|----|----|----|----|-----|
| Proposal A    | 1 | 1 | 1 | 1 | 1 | 1 | -1 | -1 | -1 | 1  | 1  | -1 | 1  | -1 | 1  | 1  | 6   |


This is an example of a system where Abstain votes are not counted (not the current system):
(Approve = +1, Abstain = 0, Reject/Slash = -1)
Using the example of a text proposal, which requires `60% voter quorum` and an `80% approval threshold` this would pass.

| Proposal / CM | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | SUM |
|---------------|---|---|---|---|---|---|---|---|---|----|----|----|----|----|----|----|-----|
| Proposal A    | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 1  | 1  | 0  | 1  | -1 | 1  | 1  | 10  |

@bedeho does this seem accurate to how the current system works?

**Comment by mochet** [comment]
A real life example of the influence of `abstain` votes:

`Of the 349 members of the Riksdag, 174 voted against her. But on top of the 117 MPs who backed Ms Andersson, a further 57 abstained, giving her victory by a single vote.`

https://www.bbc.com/news/world-europe-59400539

**Comment by bedeho** [comment]
I don't think this is describing the system as it is in `Olympia`, in the example you give, quorum would be satisfied, because 16 = 100% > 60% of council is voting _something_, however threshold is not satisfied, as only 11/16=68%<80% are voting `approve`. I don't see this as a problem, we should not count ignorance as approval, it isn't, it is rejection, its just a different way of rejecting, its saying `I have not clue what this is, so I can't support it`. If someone wants to say `I dont know what this is, but I do support it`, then they can just vote accept.

**Comment by singulart** [comment]
@bedeho I think @mochet was referring to the fact that in the [current design](https://github.com/Joystream/joystream/blob/f9502953701cf06b391c252d28c6f375acf12377/runtime-modules/proposals/engine/src/types/mod.rs#L115) `abstain` votes literally count as `reject`. I see this as an issue, because as per [developer's comment](https://github.com/Joystream/joystream/blob/f9502953701cf06b391c252d28c6f375acf12377/runtime-modules/proposals/engine/src/types/mod.rs#L48), the purpose and intent behind `Abstain` was to `Signal presence, but unwillingness to cast judgment on substance of vote`. 

So, if a CM was unwilling to cast judgement, why is `Abstain` part of the approvals threshold check? I guess it should be removed from there... WDYT?

**Comment by swasilenko** [comment]
@bedeho hi, we already have precedent when decides minority, not majority. example here: https://pioneer.joystreamstats.live/#/proposals/929. there are 13 approves in this proposal. but it will not be approved even if 2 more council members will vote. because now abstains = rejects. so if 15/20 council members approve some proposal, it will not be enough for approving it. looks strange... if abstain = reject, why do we need such a variant? we can just leave only approve and reject. if someone doesn't want to vote, he will just not vote. otherwise, abstain should affect only on quorum but not on the voting result

**Comment by bedeho** [comment]
Ok then folks, adding this to `Olympia` scope

https://github.com/Joystream/joystream/issues/2953
