### ISSUE TITLE
Mainnet Idea: Operations 1 + 2 + 3

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2595]
This depends on the technical costs, but I think if there are low costs involved there is no good reason why we shouldn't have `operations-1`, `operations-2` and `operations-3`. The 2 + 3 would be identical to 1, just with a different budget/lead.

The reasoning for this is as follows:
- R&D spending will be an extremely valuable thing for the platform. And not all R&D will just be programming tasks, the 2nd and 3rd groups could cover advertising and other elements that are maybe too much scope for a single WG to deal with.
- In some major companies, R&D spending is proportional to sales/revenue and is a consistently significant amount (https://www.wired.com/1994/10/canon/). Having a well oiled, well financed and highly creative R&D effort on the platform is going to be crucial to make it valuable.
- Joystream is not a normal company, there may be "job titles" which don't exist yet--having the ready to use, built in availability of paying these extra roles in a flexible manner and a flexible structure (compared to what I would imagine `operations-1` has) could be extremely invaluable.
- `Spending Proposals` involve a lot of friction--there may be subsets of people that are extremely valuable to the platform who are better paid on a continuous basis. They may not fall into the regular reporting requirements that other groups have, but these individuals may be creative/special enough that keeping them paid regularly ensures they are active contributors. These may be individuals that are capable of vetting creative projects that are presented to the platform in a highly industrious manner, and their unique skills may be a huge money maker for the platform. These could also potentially be people who are involved in legal or contract aspects who are useful to have.
- There may be various roles that are well worth funding, but simply do not fit into the structure of the normal Operations group and may hugely benefit from being able to run separately to `operations-1`.
- These groups may or may not be used depending on the council. It may be that one of the extra groups could be tasked with a runtime upgrade, or investigating some specific aspect of development that would simply be too convoluted for the main operations group.
- The council may decide to fund projects that are outside the scope of the platform's immediate concerns (such as creating and funding a high quality, free and open source video editor or charitable endeavours, or paying other DAOs for partnerships--and instead of doing these via spending proposals which take up council time/throughput, instead just choose to have these projects be paid via "employees".

**Comment by bedeho** [comment]
This is ... _brilliant_ , so easy, so obvious (in hindsight) and possibly hugely valuable. The only question is, why only 3? Why not just make it like 10?

Def. adding this to the next release, `Giza`.

**Comment by mochet** [comment]
> This is ... _brilliant_ , so easy, so obvious (in hindsight) and possibly hugely valuable. The only question is, why only 3? Why not just make it like 10?
> 
> Def. adding this to the next release, `Giza`.

The only reason is that I don't understand how the scaling works, or if we have limits to consider. But basically whatever number works above 1 would be ideal

**Comment by bedeho** [comment]
> The only reason is that I don't understand how the scaling works, or if we have limits to consider. But basically whatever number works above 1 would be ideal

I think there actually is some limit in Substrate, where we can't have more than 16 pallets in total or something, which is kind of low, not sure how close we are to that limit now, and also not sure if that limit has been lifted now, will check.

**Comment by traumschule** [comment]
Good idea except for the unfortunate ([re](https://github.com/Joystream/joystream/commit/95137935502b138514dc582dbc55d68149d3cb2b))[naming](https://github.com/Joystream/joystream/blob/master/runtime-modules/common/src/working_group.rs) and ripple effects (#3198 https://github.com/Joystream/pioneer/issues/2502 https://github.com/Joystream/pioneer/commit/8e51d81d465401afe0a4b4af8eafdddb9284cc58 etc.).

A conclusion could be to not rename existing groups unless absolutely necessary to spare workload for everyone. However contradicting myself instantly post-Rhodes it would be great to overcome to mix of historic (contentDirectorySomethingSomething) and generic names (Alpha Beta Gamma) that require unreliable mapping in (3rd-party) tools ([cli](https://github.com/Joystream/joystream/tree/master/cli/src/Api.ts#L49) [pioneer](https://github.com/Joystream/pioneer/blob/olympia/packages/ui/src/working-groups/types/locks.ts) [joystream-org](https://github.com/Joystream/joystream-org/blob/master/src/utils/pages/onboarding/usePioneerData.js) [tokenomics report](https://github.com/traumschule/community-repo/blob/bot-giza/scripts/report-generator/src/tokenomics.ts#L106) [jsstats](https://git.joystreamstats.live/Operations/jsstats/src/frontend/src/lib/groups.ts#L6)) not to mention all kinds of tests. With either just `group1` .. `group10` or to find a smart way to export [aliases](https://github.com/Joystream/joystream/blob/master/runtime/src/runtime_api.rs#L62) on runtime level somehow.

For example [joystream-lib](https://git.joystreamstats.live/Operations/joystream-lib/src/master/groups.ts) expects group to be passed as string without hard-coding any names.

(cc @bedeho @mnaamani @shamil-gadelshin)

**Comment by mochet** [comment]
This was implemented already so closing issue
