### ISSUE TITLE
Change needed: Pioneer v1 - WG Lead payment caps

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2601]
Currently, the UI limits payments to 100k for leads:
![image](https://user-images.githubusercontent.com/50830161/131468299-8d46fe63-9f6a-4871-ba97-2df6718ca373.png)
https://testnet.joystream.org/#/proposals/new/set-working-group-leader-reward

Due to inflation, we now are facing situations where we need to pay more than 100k. The runtime appears to accept values of up to 500k via extrinsics - https://testnet.joystream.org/#/proposals/508

Request: to change the Pioneer v1 UI to support up to 500k in the reward field.

**Comment by igrexac** [comment]
Yes. Now I had to ask for rewards less than required by about 2.5%
