### ISSUE TITLE
post-mainnet idea: more than one WG lead

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2614]
Currently, each working group has a single lead. This lead has to manage the workers of the group, and make decisions on hiring, firing and slashing workers.

The most significant limitation of this design are:
- At some scale, a single person managing everyone would be infeasible. The lead could hire people specifically to be "assistants" to help with this, but it is not perfect.
- A single person making decisions seems like it has some flaws. We will be providing services that need to guarantee some form of stability. If there are significant interpersonal differences within working groups, it may cause the valuation of the DAO to fluctuate wildly (especially if a mass of workers are fired/hired/slashed in a short duration). Interpersonal differences have been rare so far on the testnet, but when they do happen, it is immensely difficult (time consuming) to quickly comprehend what is going on without someone making an unbiased, well detailed assessment.

It would seem that having 3 leads for each working group may be a good option to explore eventually. This way rather than just one person being able to fire everyone, they would need approval from at least one of the other leads (2/3 approval votes).

There are flaws to this idea as well, since if two of the leads are biased they can effectively take over the group. However, it may work extremely well depending on how the council decides to hire each lead.

(it may also be that this idea is biased because it is based on the current testnet, maybe with singificant scale this problem wouldn't be as big of an issue)

**Comment by bedeho** [comment]
Third parties have also raised this idea actually. Another value add is simple fault tolerance: if someone goes to the hospital, or vacation or whatever, there is no really graceful way to delegate that power currently.

Introducing a voting system would basically require introducing something like a proposal system, which would be way to heavy, the consequences of that sort of change would be very large (runtime, tests, P2, query node support, CLI, ...). Simply allowing more than one worker to act as leads could be a minor tweak which would at least unlock the fault tolerance, but not the scalability or the safety.

Not sure exactly how to prioritise thia t this time, so just labling as idea.

**Comment by bedeho** [comment]
Superseded by https://github.com/Joystream/joystream/issues/2870.
