### ISSUE TITLE
vNFT idea: Advanced Offers

### ISSUE THREAD

**Issue by iorveth** [Joystream/joystream#2615]
## Motivation
- Current vNFT offer implementation allows us to only exchange single vNFT for an arbitrary amount of JOY at a time.
- Current vNFT offer implementation allows us to only make an offer in one direction (sender offers vNFT to receiver).

- Advanced offers are meant to introduce an ability to offer a p2p exchange of arbitrary amount of vNFTs and JOYs for an arbitrary amount of vNFTs and JOYs.

### Advanced vNFT offer concept is very similar to how steam offers work, but we also have an ability to include additional cost in JOY tokens (either sending or receiving part).

- Make offer flow on steam platform https://www.youtube.com/watch?v=8YrE5TV4B2E
- Accept offer flow on steam platform https://www.youtube.com/watch?v=WqqxafDzAg8

![687474703a2f2f692e696d6775722e636f6d2f366e68463639582e706e67](https://user-images.githubusercontent.com/18070359/132106542-961ff29a-deac-460e-8201-7984c163d879.png)

## Requirements

1. As member i would like to be able to offer an exchange of arbitrary amount of vNFTs and JOYs for an arbitrary amount of vNFTs and JOYs to another member.
2. As receiver member i would like to be able to accept any incoming vNFT offer.
3. As receiver member i would like to reject any incoming vNFT offer.
4. As sender member i would like to cancel any active vNFT offer, i previously initiated.

### Constraints
- When someone makes an offer, all vNFTs from `send` part should be locked for any further operations until order is active.
- We should have an upper bound constraint for the amount of vNFTs in the same offer (both `send` and `receive` parts).

## Rough runtime design

```rust

/// vNFT offer details
pub struct OfferDetails<MemberId, VideoId, Balance> {
       sender: MemberId,
       recipient: MemberId,
       send: BtreeSet<VideoId>,
       receive:  BtreeSet<VideoId>,
       cost: Cost<Balance>,
}

/// Used to determine how much JOY sender/receiver should pay for offer completion.
pub enum Cost<Balance> {
    Send(Balance),
    Receive(Balance),
}

decl_storage! {
    trait Store for Module<T: Trait> as Content {

        pub OfferById get(fn offer_by_id): map hasher(blake2_128_concat) T::OfferId => OfferDetails<MemberId, VideoId, Balance>;

        pub NextOfferId get(fn next_offer_id) config(): T::OfferId;
}

decl_module! {
    pub struct Module<T: Trait> for enum Call where origin: T::Origin {

      /// Offer vNFT
      pub fn offer_vnft(
                  origin,
                  offer_details: OfferDetails<T::VideoId, BalanceOf<T>>,
      ) {

      // authorize participant. 

      // perform all needed checks to ensure all nfts exist and belong to given participants.
      
      // ensure  length constraints for nft sets (both send and receive part) satisfied.
      
      // ensure participant have enough balance if required.
      
      // ensure all nfts from `send` part available for transfer 

      // set  transactional status for send part of nfts to `TransactionalStatus::InitiatedOfferToMember`
      
      // create and add offer under given id to the storage.
      
      // update offer_id counter

     }

      /// Accept incoming vNFT offer
      pub fn accept_incoming_offer(
                  origin,
                  offer_id: T::OfferId,
                  participant_id: MemberId<T>,
      ) {

      // authorize participant 

      // perform all needed checks to ensure all nfts from `receive` part exist, available for transfer (`TransactionalStatus::Idle`)  and belong to participant under given id.
      
      // ensure participant have enough balance if required.
      
      // perform exchange and set  `TransactionalStatus` of all nfts from `send` part, to `TransactionalStatus::Idle`
      
      // remove offer under given id from the storage.

      }

      /// Cancel vNFT offer
      pub fn cancel_offer(
                  origin,
                  offer_id: T::OfferId,
                  participant_id: MemberId<T>,
      ) {

      // authorize participant (should either match sender or recipient).

      // ensure offer under given id exist and 
      
      // set  `TransactionalStatus` of all nfts from `send` part, to `TransactionalStatus::Idle`
      
      // remove offer under given id from the storage.

      }
}
```

**Comment by bedeho** [comment]
Perhaps you could add a description of what this is, and what it unlocks compared to how our normal offers work now? I am not familiar with this type of offer mode.

**Comment by iorveth** [comment]
> Perhaps you could add a description of what this is, and what it unlocks compared to how our normal offers work now? I am not familiar with this type of offer mode.

Updated issue with `Motivation` and `Requirements` sections. Should be clearer now.
