### ISSUE TITLE
Query node: utility.asDerivative, utility.batch, sudo.sudo, sudo.sudoAs calls

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2617]
In the current query node mappings, if we want to access extrinsic call data inside the event handler function (which is, in some cases, necessary) we have to take into accounts all the possible calls that may invoke given event.

For example, in order to access the updated `about` text in `members_MemberUpdatedAboutText` handler we would need to be able to extract it from:
- direct `members.updateMembership` call
- `members.updateMembership` as part of `utility.batch` call (in which case we need to exactly map which call in the `batch` invoked the event)
- `members.updateMembership` as part of `sudo.sudoAs` call
- `members.updateMembership` as part of `utility.asDerivative` call (?)
- any combination of the above

This turns out to be quite complicated to implement and the current version of Hydra is not very well suited for handling those different types of possible calls ([example](https://github.com/Joystream/joystream/pull/2547/commits/923591b9c2131097a88d6660ce9fc9217face518))

**Proposed solution:**

Make sure all data expected by the query node event handler functions is available in the events.

For `Sumer`/`Giza` this means changing some membership events:
- `members.MemberRegistered`
- `members.MemberUpdatedAboutText`
- `members.MemberUpdatedAvatar`
- `members.MemberUpdatedHandle`
- `members.MemberSetRootAccount`
- `members.MemberSetControllerAccount`

For Olympia there is only one missing piece of data:
- `proposalsDiscussion.PostCreated` (the `editable` flag)

**Comment by bedeho** [comment]
First off, you are 100% correct, this has been an issue since a while back, this is why we started making events really "bloated" for all new modules, it's just easier.

Second, do we actually care about the `members` module in `Giza/Sumer` ? this is an old module, the `Olympia` module is way better, is it currently causing any problems for us that this is not properly dealth with in `Giza/Sumer` ?

I will assign someone to work on this, so lets conclude with a final decision here about what should be fixed.

**Comment by Lezek123** [comment]
> Second, do we actually care about the members module in Giza/Sumer ?

I think Atlas relies on membership mappings (for example, in order to get `controllerKey` for signing transactions), so removing them now may add some implementation cost there. Maybe @kdembler can comment further on that.

> Is it currently causing any problems for us that this is not properly dealth with in Giza/Sumer ?

I think `buyMembership` inside `batch` transaction will pretty much just kill the query node now, it just didn't happen yet(?)

> lets conclude with a final decision here about what should be fixed.

I would say adding data to the events on the runtime side is probably the easiest way to go about it.

**Comment by kdembler** [comment]
Yep, we use membership-related queries in a couple of ways in Atlas.

**Comment by bedeho** [comment]
Ok, so we have three options when it comes to the membership issue on `Sumer/Giza`

1. Drop the `Utility` module from the runtime in the `Giza` upgrade.
2. Actually fix the membership module events + mappings in the `Giza` upgrade.
3. Do nothing, and bet that no one will trigger these calls before we have `Olympia` go live.

I would rank these in that order in term so preferrability, but I am not sure 1 is actually ok, do we need that module for something?
