### ISSUE TITLE
Upload parameters during video creation

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#2618]
@bedeho
In order to create a video we need to upload it to storage and therefore the `UploadParameters` have to be set properly. So my question is: is the following configuration correct?
``` rust
let upload_parameters = UploadParametersRecord {
   authentication_key: auth_key, 
   bag_id: BagIdType::<T::MemberId, T::ChannelId>
                                ::DynamicBagIdType::<T::MemberId,T::ChannelId>
                                ::Channel(channel_id),
  object_creation_list: vec![DataObjectCreationParameters{video_size, video_ipfs}],
  deletion_prize_source_account_id: treasury_account,
  expected_data_size_fee: cleanup_cost,   
};
```
with: 
- `channel_id` is the channel the video is being added to
- `treasury_account` is the account where the reward in `JOY`s is stored (such account is obtained as in https://github.com/Joystream/joystream/blob/b046dd7535baf3e0495b0f2e8c871f3143e10bbb/runtime-modules/forum/src/lib.rs#L1546)
- `video_size` & `video_ipfs` are the size and ipfs hash for the video being uploaded provided to the `create_video` extr.
- `auth_key`provided to the `create_video` extrinsics
- `cleanup_cost` is the reward in `JOY`s computed as `byte_price x video_size` (similar to #2545 )

**Comment by bedeho** [comment]
This is largely right, here are some corrections

1. It seems that either way, the signature for the given module routine needs better documentation, so after you have figured this out, please open a PR that @shamil-gadelshin can review with more detailed documentation for any user of the api.
2. The best way to find the answer is to trace the code path directly, you may have already done that, but just reminding you in case not.
https://github.com/Joystream/joystream/blob/storage_v2/runtime-modules/storage/src/lib.rs#L2523
3. You are are on the right track, here are some tweaks
   - `deletion_prize_source_account_id`: this is the account from which funding for deletion should happen, this should controller account of member. If its a curator, I think its easiest to still follow this policy, as they can later get reimbursed,  or it can be a fixed part of their wage. So it should not be any kind of treasury.
   - `expected_data_size_fee`: This is a per byte fee associated with the variable, off-chain, cost of accommodating the new upload. The reason it is provided by the extrinsic author, when the real value also exists in the chain, is to prevent an attack, or just a misunderstanding, where the price is adjusted on-chain after the time at which an extrinsic is sent.

**Comment by dobertRowneySr** [comment]
> It seems that either way, the signature for the given module routine needs better documentation, so after you have figured this out, please open a PR that @shamil-gadelshin can review with more detailed documentation for any user of the api.

Which is the module routine in question? `upload_data_objects`?

**Comment by bedeho** [comment]
Link is in prior reply.
