### ISSUE TITLE
Decorate proposal discussion system event

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2622]
Address last point here 

https://github.com/Joystream/joystream/issues/2617

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711174141494) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Runtime part fixed in: https://github.com/Joystream/joystream/pull/2679
Query node part: https://github.com/Joystream/joystream/pull/3113
Closing, since this issue refers to `runtime`
