### ISSUE TITLE
Giza release plan, Ignazio

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#2626]
| **Task** | **Status** | **ETA**| **Target Branch**| **Comments** | 
|----|----|----|---|---|
| [Improve video deletion](https://github.com/Joystream/joystream/issues/2574 ) | `BEING REVIEWED` |- |`storage_v2` | PR @ https://github.com/Joystream/joystream/pull/2625 |
| Storage v2 integration | `BEING REVIEWED` | _ | `storage_v2` | PR @ https://github.com/Joystream/joystream/pull/2625 |
| [Channel Deletion](https://github.com/Joystream/joystream/issues/2572) | `TO BE REVIEWED` | - | `storage_v2` |-|
| Remove DAO References | `IN PROGRESS` | 1h  | `master` | - |
| [Temporary God Mode](https://github.com/Joystream/joystream/issues/2577) | `TO DO` | 3h | `master` | I need to check that implementation satisfies request in the last comment|
| [Events Decoration](https://github.com/Joystream/joystream/issues/2617) | `TO DO` | 40h |`master` |  the ETA is very likely an overestimation, but I am not very familiar with the query node yet|

### Statuses
- `TO DO`
- `TO BE REVIEWED`
- `BEING REVIEWED`
- `FIXING PR COMMENTS`
- `DONE`

**Comment by ignazio-bovo** [comment]
I saw on #2580 that the target Branch is `giza`, should I rebase my work on that when the target branch differs?
