### ISSUE TITLE
NFT: Set creator royalty

### ISSUE THREAD

**Issue by iorveth** [Joystream/joystream#2654]
Introduce an ability to set creator royalty after initial video nft issuance. 
Extrinsic actor should be current nft owner & initial creator.

**Comment by bedeho** [comment]
This should only be allowed if the owner is the channel owner, another owner should not be able to do this, because the royalty goes to the channel owner/issuer, not nft owner. NFT owner should not be able to set it to 0 to avoid this royalty.
