### ISSUE TITLE
NFT: destroy_nft

### ISSUE THREAD

**Issue by iorveth** [Joystream/joystream#2655]
Introduce an ability to destroy nft
Extrinsic caller should be current nft owner ~& initial creator~.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201837557047920) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
I also just realized that the spec is a bit misleading, its not allowed that the channel owner can destroy an NFT for a video in their channel. Its only the genuine owner who can do it, so it is either when the NFT is owned by the channel owner, i.e. `NftOwner::ChannelOwner` or when its the explicit member owning the NFT, so `NftOwner::Member`.

**Comment by mnaamani** [comment]
Completed in #3547
