### ISSUE TITLE
vNFT:  forbid Actor to participate in his own transactions

### ISSUE THREAD

**Issue by iorveth** [Joystream/joystream#2685]
Should we forbid `Actor` to participate in his own transactions ( buy back his own sells, participate in his own auctions, make offers to himself, etc.) ?

**Comment by bedeho** [comment]
LOL, I guess so :D It does not really prevent this, as they could use a Sybill membership.

Just to clarify, when you say "his own", do you mean an NFT they own, or that the NFT is on a video where they own the channel, but not the NFT? I think the latter should be ok.

**Comment by iorveth** [comment]
> LOL, I guess so :D It does not really prevent this, as they could use a Sybill membership.
> 
> Just to clarify, when you say "his own", do you mean an NFT they own, or that the NFT is on a video where they own the channel, but not the NFT? I think the latter should be ok.

Yep, i meant NFT "they" own.

**Comment by bedeho** [comment]
I think for simplicty, lets just avoid this, it really does not solve a problem, and we should try to keep the module simple, its already getting quite complex.
