### ISSUE TITLE
Giza: Distributor node: no-longer distributed data objects cleanup

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2690]
Currently there is no mechnism to cleanup the data no longer distributed by the distributor node until the node restarted. This means that technically the node can store the no-longer assigned data forever, if it keep beeing frequently requested (doesn't drop off the cache).

There are two possible approaches to fix it, that need to be evaluated in terms of complexity and efficiency:
- perform a full cleanup, similar to the one that happens on startup, but periodically (with `setInterval`)
- remove the no-longer distributed data object when requested (otherwise it will just drop off the cache at some point)

**Comment by bedeho** [comment]
> This means that technically the node can store the no-longer assigned data forever, if it keep beeing frequently requested

Are you saying the ndoe currently blindly grabs, stores and distrbutes whatever anyone requests? Isn't there some representation of what it is supposed to distribute or not somewhere locally?

> remove the no-longer distributed data object when requested

Requested by whom and how?

> There are two possible approaches to fix it

Wouldn't another option be to just delete on-demand when you detect that your set of distributor buckets has changed? I guess you actually also need to be aware of when individual objects are removed from bags you should also distribute, which brings back the question of how these obligations are being represented on the distributor side to begin with.

**Comment by Lezek123** [comment]
> Are you saying the ndoe currently blindly grabs, stores and distrbutes whatever anyone requests?

If it doesnt have the requested object in the cache it checks whether it's supposed to distribute it and fetches and stores it only in that case.

If it does have the requested object in the cache it "blindly" serves it.

The problem is that objects may stay in the cache for too long even if technically they are no longer supposed to be served by the node.

> Requested by whom and how?

When there is a standard request made by anyone for an asset (so someone goes to `http://distributor-node-uri/assets/1`, but turns out asset is no longer  supposed to be distributed - in that case it's removed)

> Wouldn't another option be to just delete on-demand when you detect that your set of distributor buckets has changed? I guess you actually also need to be aware of when individual objects are removed from bags you should also distribute, which brings back the question of how these obligations are being represented on the distributor side to begin with.

There is no state kept about current obligations in the distributor node. The obligations are checked (using query-node) on per-data-object basis in case of cache miss, as described in detail in https://github.com/Joystream/joystream/issues/2553 under _Distributor node API_ section.

**Comment by bedeho** [comment]
> If it doesnt have the requested object in the cache it checks whether it's supposed to distribute it and fetches and stores it only in that case. If it does have the requested object in the cache it "blindly" serves it.

Ok, I see. I hope this check does not involve an API call to the query node? Otherwise it seems that oculd get super slow for cache misses, or be an attack vector perhaps? I think we could get away with it now, but at least something to improve in the future. So seems the need for cleanup may be only one of multiple reasons to maintain some state on this in the future.

> When there is a standard request made by anyone for an asset (so someone goes to http://distributor-node-uri/assets/1, but turns out asset is no longer supposed to be distributed - in that case it's removed)

Ah ok. Would you here only remove the object? or would you remove the whole bag as well, if oyu find that the object was no longer a responsibility, not because it was deleted, but because the bag was deleted, or not longer in that distributor bucket.

Either way, seems a bit "sloppy", not sure how much of a penalty one takes on wasted cache space.

> There is no state kept about current obligations in the distributor node. The obligations are checked (using query-node) on per-data-object basis in case of cache miss, as described in detail in #2553 under Distributor node API section.

Ok, good to know. Do you see this as a temporary thing, or still possibly viable medium-long term?

**Comment by Lezek123** [comment]
> perform a full cleanup, similar to the one that happens on startup, but periodically (with setInterval)

Implemented as part of https://github.com/Joystream/joystream/pull/2582
