### ISSUE TITLE
Giza: Channel/Video creation requires providing assets

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2709]
After https://github.com/Joystream/joystream/pull/2625 it became impossible to create a channel or video without providing assets as this results in `NoObjectsOnUpload` runtime error.

It should be possible to provide no assets when sending those extrinsics (ie. `NewAssets` arg can be changed to `Option<NewAssets>`)

**Comment by dobertRowneySr** [comment]
fixed in `giza`
