### ISSUE TITLE
Start stop container from test framework

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#2711]
Add ability to start and stop storage service and distributor service from test framework, passing required arguments for the instances (keys, id etc..)

This primarily avoids the need for make too many assumptions about state of the test network, and depending on correct "init scripts" to be executed on the test network.

If we choose to go with simpler approach of initializing state of chain before tests with pre-defined workers then tests should not include working group related tests, and all that is required would be to "inject" worker keys for tests to use if required.

**Comment by ahhda** [comment]
We've got a couple of options here.

1. We continue using the current process i.e. write a bash script that starts & configures the containers using `docker-compose`, runs the tests and stops the containers once done. Similar to `tests/network-tests/run-tests.sh`
2. We could create a Pulumi stack, configure a K8 cluster on minikube local and run the tests. This stack would be configurable using Pulumi stack inputs. We could automate this process using Github actions or a bash script.
