### ISSUE TITLE
Giza: Channel video counter is incremented on video update

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2713]
See: https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L1081

This prevents channel from beeing removed if one of its videos was updated at some point, as the video counter is then broken:
https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L781

**Comment by dobertRowneySr** [comment]
fixed in `giza` release
