### ISSUE TITLE
Giza: Channel.num_assets incorrectly counted in the runtime

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2714]
The `remove_channel_assets` extrinsic allows removing any assets that belong to channel's dynamic bag, which also includes video assets.

However video assets are not counted in `Channel.num_assets`, which make it possible to break this rule:
- Create channel with 2 assets
- Create videos with 2 assets inside the channel
- Call `remove_channel_assets` providing video assets ids
- The channel still has 2 associated assets, but `Channel.num_assets` in the runtime state equals `0`

This means:
- It's possible to delete a channel that still has some associated assets
- It's possible to "block" the removal of channel assets even though there are still assets that can be removed

**Comment by dobertRowneySr** [comment]
fixed in `giza`
