### ISSUE TITLE
Giza Runtime constants for storage pallet.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#2722]
[Utilisation model](https://github.com/Joystream/joystream/issues/2359)

  | Constant | Value | Comment
-- | -- | -- | --
  | MaxDistributionBucketNumberPerFamily | 500 | 
  | MaxDistributionBucketFamilyNumber | 200 | 
  | DataObjectDeletionPrize | 1 | We don’t have anti spam protection and tx cost analysis for Giza. We should go back to this value during the Olympia. Setting minimum value = 1.
  | BlacklistSizeLimit | 10000 | BlacklistSizeLimit comment|
  | MaxRandomIterationNumber | 10 | 3 x DefaultXBagNumberOfStorageBuckets
  | MaxNumberOfPendingInvitationsPerDistributionBucket | 20 | From utilisation model
  | StorageBucketsPerBagValueConstraint | 5-15 | min: Replication factor - max: 5x Replication factor
  | DefaultMemberDynamicBagNumberOfStorageBuckets | 5 | 
  | DefaultChannelDynamicBagNumberOfStorageBuckets | 5 | 
  | DistributionBucketsPerBagValueConstraint | 1-100 | 
  | MaxDataObjectSize | 10GB | Consulted with Mokhtar

#### BlacklistSizeLimit
As some reference point, I took youtube's deleted content statistics for 2017: https://www.statista.com/statistics/1132890/number-removed-youtube-videos-worldwide/ https://www.statista.com/statistics/259477/hours-of-video-uploaded-to-youtube-every-minute/ https://www.statista.com/statistics/1026923/youtube-video-category-average-length/#:~:text=According%20to%20the%20report%2C%20the,of%206.8%20minutes%20per%20video 
Depending on the calculation method we can deduce that youtube deleted less than 1% of their video as inappropriate content. We have 500K as the first target of total videos.   Let's take 2% of the content as a possible blacklist size = 10000

**Comment by bedeho** [comment]
Hey, I think this looks like a sound starting point, but perhaps bumping these from 3 to 5 could make sense just to reduce chance catastropic data loss

- DefaultMemberDynamicBagNumberOfStorageBuckets
-  DefaultChannelDynamicBagNumberOfStorageBuckets

I guess this will generate new values for other parameters possibly?

Did you actually check if the utlisation model made sense? I dont think anyone has evaluated it.

**Comment by shamil-gadelshin** [comment]
Done
