### ISSUE TITLE
Minor fixes agreed upon for Giza

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2726]
- Drop data object id association in video: `maybe_data_objects_id_set`
- Drop incrementing `ChannelRecord::num_videos` in `update_video`.
- introduce atomic data object deletion in: for all of these, user provides `objects: BTreeSet<DataObjectId>`, for all each, they will check that deletion is feasible (by checking bag membership of all objects), and then this is done as first side-effect after mutation barrier.
  - update_video
  - update_channel
  - delete_video
  - delete_channel

**Comment by dobertRowneySr** [comment]
Maybe I didn't realized during the call: why do we need to need to feed the `delete_channel` extrinsic
with a `BTreeSet` containing all the data obj.s? Don't we need to delete the storage bag for a channel
upon channel deletion? @bedeho

**Comment by bedeho** [comment]
> Maybe I didn't realized during the call: why do we need to need to feed the delete_channel extrinsic
with a BTreeSet containing all the data obj.s? Don't we need to delete the storage bag for a channel
upon channel deletion? @bedeho

We do need to delete the bag, but this means it must be empty, which means all objects must be deleted first, and there is no way (that I recall), of enumerating all objects in a bag, is there? I am also not 100% sure about whether a weight function can access storage to compute weight, which would be required in order to recover the counter of how many data objects live in the bag.  @shamil-gadelshin @iorveth

**Comment by iorveth** [comment]
> > Maybe I didn't realized during the call: why do we need to need to feed the delete_channel extrinsic
> > with a BTreeSet containing all the data obj.s? Don't we need to delete the storage bag for a channel
> > upon channel deletion? @bedeho
> 
> We do need to delete the bag, but this means it must be empty, which means all objects must be deleted first, and there is no way (that I recall), of enumerating all objects in a bag, is there? I am also not 100% sure about whether a weight function can access storage to compute weight, which would be required in order to recover the counter of how many data objects live in the bag. @shamil-gadelshin @iorveth

Weight function cannot access storage directly, but we can provide witness if applicable, which would be used to calculate weight. Afterwards we check whether witness is correct during extrinsic execution. https://github.com/Joystream/joystream/issues/2541

**Comment by bedeho** [comment]
Ok, so if the enumeration was possible, the only input required would the number of data objects in the channel bag, but alas, I believe it is not? I don't recall 100%

**Comment by iorveth** [comment]
> Ok, so if the enumeration was possible, the only input required would the number of data objects in the channel bag, but alas, I believe it is not? I don't recall 100%

Yes, if enumeration is safe and possible, we can provide the correct number of data objects in the specific channel bag, witness is the only required input, needed for benchmarking adjustment. https://github.com/paritytech/substrate/blob/e6cd6b1240ce741f06b05ad1c59f5399e52e717a/frame/uniques/src/lib.rs#L402

**Comment by iorveth** [comment]
Not sure whether we can enumerate  all objects in a bag though..

**Comment by shamil-gadelshin** [comment]
The `DataObjectsById` is a double map (by bag_id, by data_object_id). The enumeration is possible (by [prefix](https://substrate.dev/rustdocs/latest/frame_support/storage/trait.StorageDoubleMap.html#tymethod.iter_prefix_values)).

**Comment by bedeho** [comment]
Ok, if each bag also has a counter for the number of data objects currently in the bag, then providing an explicit list of objects is not required for `delete_channel`.  Is this the case @ignazio-bovo ?

**Comment by dobertRowneySr** [comment]
Yes, it should not be needed, **if** we drop the channel bag upon deletion

**Comment by bedeho** [comment]
Why would `drop the channel bag upon deletion`  be a condition for doing this auto-deletion without a user specified object set?

**Comment by dobertRowneySr** [comment]
If I want to delete a channel does not implies deletion of *all* associated assets (which are in the bag)?
This will imply:
- first remove all assets from the bag in storage
- we drop the bag

**Comment by bedeho** [comment]
It does, but remember that this is distinct from deleting the bag itself, but we also want to do that. Regardless, I was understanding your prior remark to be saying something else, but perhaps it was just a misunderstanding.

**Comment by dobertRowneySr** [comment]
So (in order to be on the same page) I would update `delete_channel` as follow
- remove `assets` as a parameter
- remove all channel assets from storage first
- drop the bag

That works @bedeho ?

**Comment by bedeho** [comment]
Yes, but you still need the user to provide the size of the bag as a parameter, which can be used by weight function to charge for cleanup in advance, and then this value must be validated before any cleanup is done.

**Comment by dobertRowneySr** [comment]
Actually I am having trouble to collecting the `DataObjectsId` needed for the deletion, which are not possible to retrieve starting from the dynamic bag id. I believe it is best that we keep the current design and delegate to the user the responsibility to empty the bag first @bedeho

**Comment by bedeho** [comment]
Can you be specific? @shamil-gadelshin has clarified that it is possible.

**Comment by dobertRowneySr** [comment]
yes, it is possible to prefix-iterate throught the double map. Iteration yields an object of type `DataObject`.
In order to remove the objects from storage via a `remove_data_objects` call, however, I need to pass a collection of `DataObjectsId`s. Each is not retrievable starting from neither the bag id nor the `DataObject` itself. @bedeho

**Comment by bedeho** [comment]
What is the status of this?
