### ISSUE TITLE
Troublesome UX when crating some entities

### ISSUE THREAD

**Issue by jodator** [Joystream/joystream#2727]
In order to make Pioneer UX as accessible as possible, we tend to batch multiple transactions into one flow.

The problematic transactions that we identified so far:

*   [creating proposal](https://joystream.gitbook.io/joystream-handbook/governance/proposals#submit-proposal) + [set discussion mode](https://joystream.gitbook.io/joystream-handbook/governance/proposals#change-thread-mode)
*   [announce candidacy](https://joystream.gitbook.io/joystream-handbook/governance/council#announce-candidacy) + [set candidacy note](https://joystream.gitbook.io/joystream-handbook/governance/council#submit-candidacy-note)
*   ... there might be similar for other modules as well

I think that having 2 transactions gives the flexibility to change something after the initial entity creation. So I think that this should stay. However, it would be convenient for the API consumers to also include those optional actions in the extrinsic that create an entity.

- - -
## UX Details
For instance, creating a proposal flow ([figma design](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=1%3A1704)) gathers all required information before asking the user to sign any transaction. This involves:

*   staking account (whether bound to a member or not)
*   proposal parameters (general & specific)
*   discussion mode: open or closed

The bounding account process already involves two separate signers (one for staking candidate and one for confirming that account). So there's nothing that we could do here. However, it is convenient (UX-wise) to batch all transactions that are signed with the same account. However, setting discussion mode requires `id` of a proposal and this creates an optional 3rd transaction to create a proposal using a single UI flow:

![](https://user-images.githubusercontent.com/247363/135600609-21a36d03-8005-42c9-a435-2fd2318d8daa.png)

For that flow the transactions are:

1\. Bind account for staking

```typescript
api.tx.members.addStakingAccountCandidate()
```

2\. Create a proposal

```typescript
api.tx.utility.batch([
  api.tx.members.confirmStakingAccount(),
  api.tx.proposalsCodex.createProposal(),
])
```

3\. Set discussion mode

```typescript
api.tx.proposalsDiscussion.changeThreadMode()
```

The problem here is that we can't batch the third transaction as it needs a proposal ID.

A similar case is for updating membership details – we have two separate extrinsics ([one for updating accounts](https://joystream.gitbook.io/joystream-handbook/subsystems/membership#update-accounts), and [the other for member metadata](https://joystream.gitbook.io/joystream-handbook/subsystems/membership#update-profile)) but we present one UI for both. Depending on the changes we either submit one or batch both – but there's only one signing process. Which is completely fine.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202171963549191) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Here we need to reduce the stages from 3 to 2..

**Comment by traumschule** [comment]
=> pioneer
