### ISSUE TITLE
Content Migration to Giza

### ISSUE THREAD

**Issue by blrhc** [Joystream/joystream#2732]
### Background
The introduction as part of Giza of the new storage and distribution system, alongside the associated content directory enhancements means that now is the perfect time to prune some of the content which has built up in the directory over the course of the current testnet.

### Whitelist
I will prepare a whitelist of channels which have been created by community members and contain particularly high-quality (in most cases original) content which deserves to be migrated over to the new network. Jsgenesis-produced content such as our community update videos will also fall into this category. In addition, the default "seed" channels which we make available at the beginning of every network will also need to be made available.

### Blacklist
For a variety of reasons, some content uploaded over the course of the current testnet has contained incorrect metadata or for whatever other reason would probably not warrant being migrated over to the new network (in some cases entire channels  contain "dead" content as a result of these metadata issues), and some channels are themselves empty and therefore probably don't justify being migrated over.

Where there is some doubt over whether a network participant may want to retain their channel or content for Giza, I will contact the channel owner via Discord or Telegram if their key is linked to a public identity to ask whether their channel or video should be included in the whitelist for migration.

For the avoidance of doubt, anything not placed on the whitelist before the script is run will be automatically purged.
There is a possibility some of the data from the last testnet will be preserved for a short time in order to offer participants the chance to recover any lost content not previously captured in this content migration scheme.

#### Progress
I am already perhaps 75% of the way through determining the status of videos and channels currently available.
I need to discuss some further details with @mnaamani regarding how the bootstrapping script for whitelisted content will work (in terms of preserving assets and metadata).

**Comment by blrhc** [comment]
@mnaamani One thing that I have just realised is that it would be quite good to preserve video IDs if there is some way of doing that, as we often link to the testnet in our public communications about community update videos etc.

<img width="551" alt="Screenshot 2021-10-06 at 11 49 16" src="https://user-images.githubusercontent.com/4144334/136189075-981c5c0f-ffc5-4794-a27b-0a5270bbd7db.png">

Obviously if it's extremely difficult it may not be worth the effort!

**Comment by blrhc** [comment]
Or we could at least set up some sort of redirect through atlas for these reserved IDs.

**Comment by bedeho** [comment]
> One thing that I have just realised is that it would be quite good to preserve video IDs if there is some way of doing that, as we often link to the testnet in our public communications about community update videos etc.

This is really useful, not entirely clear how we can easily achieve it though :(

> Or we could at least set up some sort of redirect through atlas for these reserved IDs.

Rough, but yeah, creative last resort! I dont think that would work, because eventually there would be new videos in the new system that actually had the ID of these redirects.

**Comment by blrhc** [comment]
@mnaamani Just to be absolutely clear, all you need from me for this to work are the IDs of the channels from Sumer which are to be migrated?

**Comment by mnaamani** [comment]
> @mnaamani Just to be absolutely clear, all you need from me for this to work are the IDs of the channels from Sumer which are to be migrated?

Yes the channel IDs, and if there is any list of videos (from those channels that should be excluded)

**Comment by mnaamani** [comment]
The script to perform the migration has been implemented ref: https://github.com/Joystream/joystream/pull/2819

Here is sample output (annotated with some comments) which will be provided to Atlas team.

Note in this test run the target chain started with starting indices = 1 but on sumer to giza live network the new ids will be gt the old ids.

Channel migration artifact file (json):
```json
{
  "idsMapEntries": [
    [
      2,  // the old channel Id
      1   // new channel id
    ]
  ],
  "failedMigrations": []
}
```

Video migration artifact (json file):
```json
{
  "idsMapEntries": [
    [
      1,   // old video id
      1   // new video id
    ],
    [
      2,
      2
    ],
    [
      3,
      3
    ],
    [
      4,
      4
    ],
    [
      5,
      5
    ]
  ],
  "failedMigrations": []
}
```

cc: @kdembler
