### ISSUE TITLE
Set Election Parameters Proposal - Hard to execute successfully

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#2740]
For the current implementation, the council params can only be set when there is no election ongoing. If the election is in any of the `announcing`, `voting` or `reveal` stages, the extrinsic will fail.

This is easy enough to "time" if done with `sudo` (although it still applies), but for proposals, it means that the voters will need to organize themselves in such a way that the "deciding" approval vote occurs at the right time.

---

Currently, we have a grace period of 14 days for the proposal, and election params with:
- term duration: 1 day
- announcing: 4 days
- voting: 1 day
- reveal: 1 day

As the votes are reset at the end of each council term, the voters has to approve the proposal within the first of the 7 days they are seated..

**Comment by Ilichhh** [comment]
When you will use `sudo`, adjust the parameters that were in the proposal https://testnet.joystream.org/#/proposals/600 . I mean `New term duration: 28800 blocks` . Then we will have 2 days to vote in the future.

**Comment by bedeho** [comment]
No longer applies post-Olympia.
