### ISSUE TITLE
Channel cannot be deleted if there were no channel assets ever uploaded

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2743]
**How to reproduce:**
- Create a channel without any assets using `create_channel` extrinsic
- Try to delete the channel using `delete_channel` extrinsic

**Expected result:**
Channel is deleted

**Actual result:**
`DynamicBagDoesntExist` runtime error is thrown

**Most likely cause:**
Because there are no assets provided during channel creation, no channel bag is created (https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L648), but during channel deletion the runtime still tries to delete the non-existing channel bag (https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L768), which causes an error.

**Comment by bedeho** [comment]
Excellent find, @ignazio-bovo can you add test coverage for this? I guess that we should either

a)  stick to the policy of _always_ creating a bag whenever a channel or member is created, regardless of whether it is initially empty or not.
b) deletion checks that bag exists before attempting to delete.
