### ISSUE TITLE
Giza Staging Network Initial State

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#2747]
A new staging network will be started for Giza testing as follows:

1. Create a new network with latest Sumer runtime from master with 3 Validators. initial members (exported from  existing sumer staging network)
2. Deploy an rpc node
3. Create a council.
3. Create Workers in both Storage and Content working groups (lead and one worker)
4. Add curator group and curators to Content module
5. Create categories in content module
5. Create 500 channels and 8000 videos in content module. (No need to upload content)
6. Export runtime state (for query-node bootsrapping)
6. Sudo set code (Giza runtime)
7. Deploy Query-Node and bootstrap

Note:
Is there any runtime integration that requires storage workers be created again after runtime upgrade? (ie. is there any state in storage module that is triggered by worker creation or deletion?)

**Comment by mnaamani** [comment]
What should be performed on runtime upgrade and issues to lookout for.

* Operations Group Modules
3 New working group modules' config parameters need to be initialized on upgrade

* Content Module
If we rename the module (resetting all state),  maybe setting next channel_id, next_video_id to last known value before runtime to allow for https://github.com/Joystream/joystream/issues/2732#issuecomment-935958495
If we do not rename the module, remove all channles from `ChannelById` map

* Storage Module
Nothing?

Pre-Upgrade:
The old OperationsGroup module is removed in Giza so we need to ensure all workers are un-staked (fire all workers including lead) -> If we do not want to do that, perhaps reconsider keeping the module name intact instead of renaming it to OperationsGroupAlpha. 

Content Working group is also renamed. We should drop curators post update

**Comment by dobertRowneySr** [comment]
### List of migration operations
- `OperationsWorkingGroup` 's workers are fired
- `OperationsWorkingGroup{Alpha, Beta, Gamma}` are initialized
- `VideoById` clearing is unrolled over multiple blocks
- `ChannelById`clearing is unrolled over multiple blocks

### Progress status
- [X] `OperationsWorkingGroup{Alpha, Beta, Gamma}` are initialized on `on_runtime_upgrade`
- [x] `VideoById` clearing is unrolled over multiple blocks
- [x] `ChannelById`clearing is unrolled over multiple blocks
- [x] migration tests are performed for the working group
- [x] migration tests are performed fro the map clearings
