### ISSUE TITLE
Question: Does accept_incoming_offer need recipient

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2770]
Signature of acceptance extrinsic looks as follows

```Rust
/// Accept incoming NFT offer
#[weight = 10_000_000] // TODO: adjust weight
pub fn accept_incoming_offer(
    origin,
    video_id: T::VideoId,
    recipient_id: MemberId<T>,
) 
```

But it seems `recipient_id` should not be required, as the appropriate id should already be part of the `Auction`.

**Comment by iorveth** [comment]
i think it's a redundant parameter, will rework an extrinsic.

**Comment by iorveth** [comment]
Closed https://github.com/Joystream/joystream/pull/2671
