### ISSUE TITLE
Clarify NFT extrinsics

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2772]
I was getting quite confused about the distinction between 

- `complete_nft_auction` 
- `settle_open_auction`

Both the comments and names left me confused about why we need both, and who calls each.

I think we are better of doing
- `complete_nft_auction` => `claim_won_english_auction`
- `settle_open_auction` => `pick_open_auction_winner`

and adding a bit more clarity in the documentation of each about who is supposed to call when.

**Comment by bedeho** [comment]
Even `cancel_transaction` is not great, I know what it is, but its too obscure, it would be better to have three distinct extrinsics,

- `cancel_auction`
- `cancel_offer`
- `cancel_buynow`

and instead factor out the code into some internal shared `cancel` method to avoid repeatnig ourselves.

**Comment by iorveth** [comment]
> I know what it is, but its too obscure, it would be better to have three distinct extrinsics,

Ok, great

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2782
