### ISSUE TITLE
Robust open auction settlement

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2773]
Right now, only the winner of an open auction can actually settle it, by calling `complete_nft_auction`, but we should allow anyone to call this, or really at least the owner should be able to. Its pointless to limit this, and just risks things getting stuck if the person forgets, or loses access to keys or something.

**Comment by iorveth** [comment]
> Right now, only the winner of an open auction can actually settle it, by calling `complete_nft_auction`, but we should allow anyone to call this, or really at least the owner should be able to. Its pointless to limit this, and just risks things getting stuck if the person forgets, or loses access to keys or something.

It feels like you meant `English` auctions here, don't you? 
Because open auctions do not expire and can only be settled by it's auctioneer (`pick_open_auction_winner`) or through by now feature currently.

**Comment by bedeho** [comment]
Yes, sorry!

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/2782
