### ISSUE TITLE
Storage & Bandwidth System Review

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2793]
# Background

The v2 version of the storage and bandwidth system of the Joystream network is in the final stages before having it's MVP launched, and a reasonably accurate description of the system can be found in the Joystream handbook

https://joystream.gitbook.io/joystream-handbook/subsystems/storage

Understanding the system, as it currently is, requires developing a basic understanding of some key parts of the on-chain business logic of blockchain, including working groups and memberships, and then the data directory, and also the functioning of two standalone pieces of node software that provide the network level storage and bandwidth services. Everything about this is covered in the handbook.

This is not the final form of the system before mainnet, however major parts of the overall architecture of the system reflect our current long term plan, hence this release is a worthy milestone for doing a review.

# Review Goals

This review has the following goals

1. Identify low hanging fruit improvements.
2. Identify possible critical feasibility barriers.
3. Develop a quantitative model of how the system should be organised to reach quantified performance objectives, and what the cost structure and total cost of this such performance would be.
4. Identify opportunities for deeper and more fundamental improvements over the long term.

How these goals should be achieved is described in precise terms below.

# Actor Model

**Importantly, the analysis should disregard the possibility of different actors inside the system, or users of the system, acting possibly adversarially to maximise profits at the expense of system goals, unless otherwise explicitly stated. Assume for analytical simplicity that all actors will act as if directed by a social planner with perfect information on behalf of the system goals.**

# Modeling Methodology

## Service Constraints

Loosely stated, the goal of the system is to provide a given level of service at minimal cost. In order to make the loose idea of _service_ precise, we need to develop a list of parametrised constraints, called _service constraints_, which each define some fully quantified requirement the system must satisfy at all times.

Below there is a list of example service constraints that have been provided in order to make the idea more concrete.

### Example 1: Upload Throughput

- **Parameters:**
 - `X_1`: Number of videos
 - `X_2`: Video size in bytes
- **Constraint:** Over 24 hour period of time it is possible for `X_1` videos of average size `X_2` to be successfully uploaded and fully replicated by all storage providers.
- **Comment:** This is the sort of constraint that will, together with other assumptions, have implications for the lower bound ingress speed and capacity of individual storage providers. More deeply, it will also have implications for the growth rate of the total storage burden of the system, and thus implications for the pace at which new storage providers have to be able to synch and get online to handle the increasing load.

### Example 2: Data Loss Risk

- **Parameters:**
 - `X_1`: Number of videos
 - `X_2`: Probability that a given storage bucket has an operator that permanently faults, independently of everything else.
- **Constraint:** Over a 6 month period of time there is no more than a `X_1` percentage chance that any piece of data is permanently lost as a result of all storage buckets for a bag failing, given that the daily failure probability of each storage bucket is independent from the others and is `X_2`.
- **Comment:** This is the sort of constraint that will, together with other assumptions about the size of the data directory, have implications for how much storage redundancy is required for bags.

### Example 3: Playback Latency

- **Parameters:**
 - `X_1`: ms time.
- **Constraint:** For all videos, the time from which a user initiates playback to the time playback can commence client side must be no longer than `X_1` so long as the user is located in or "near" a city with more than 1M residence and has internet.

###  Example 4:  Generic Viral Content

- **Parameters:**
 - `X_1`: % of videos.
 - `X_2`: virality percentage.
 - `X_3`: virality period duration.
 - `X_4`: playback latency upper bound.
 - `X_5`: average video bitrate.
 - `X_6`: average video duration.
- **Constraint:** On any given day, `X_1` percent of the videos go viral. This means that it is accessed at an hourly compounding rate of `X_2` download requests per second for the next `X_3` days, and then declines at . This demand is uniformly distributed across across all geographies on a per capita basis. The system must be able to do on-demand streaming deliver on-demand, with latency no greater than `X_4`, from start to finish, of videos that have average bitrate of `X_5`, and last an average of `X_6` seconds.

### Model

A collection of such constraints can be integrated into unified mode, called a _service model_, which can generate conclusions about how to organise the internals of the system in a cost minimising way in order to satisfy parameter values for all service constraints. Specifically, it predicts

- **Optimal Organisation:** These refer to values for policy variables that are under the control of the system. So for example, how many storage providers are needed, how many buckets, what their storage, ingress & egress capacity, and so on. Some values may be for built in technical parameters of the blockchain side, others may simply be policy variables.
- **Minimal Cost:** This is basically a cost estimate of what it would in total cost to allow the system to operate optimally.

Importantly, the model may require a collection of separate parameter values that are needed to provide sufficient information to generate final conclusions, these are called _model parameter values_. Lastly, the model also needs to be able detect when inputs fundamentally not able to reconcile into any feasible service arrangement.

![methodology_model](https://user-images.githubusercontent.com/437292/138730407-11dbcbe7-e2d8-46eb-8c73-ee5ab5683703.png)

It is obvious that there could be a variety of different service models that could work for a given set of constraints, as they would reflect different fundamental ways of trying to achieve all of the stated goals. Different models may constitute fundamentally different tradeoffs that are not directly reflected in any of the constraint. It is up to the reviewer to come up with a model which balances simplicity, maintainability and cost efficiency of the most relevant input values.

### Model Variables: Exogenous vs Endogenous

Notice that in none of the examples above is it specified what the replication factor of a data object has to be, despite the fact that conclusion on that question will have a critical impact on the output of a service model. This would mean that in the context of a service model, this value would either have to be provided as a model parameter (exogenous), or in a much more useful scenario, be determined as a function of all the inputs and built in assumptions in the model. The reason this would be more useful in most cases is that the value to this question is precisely something one is looking to learn in production and during development, hence having a model that provides it is of greater utility than a model that allows you to specify it.

### Model Form Factor

The most important requirements of the model form factor are that it

- is implemented using open source tools
- is easy to maintain over time by distinct people
- can be used by non-developers to make predictions
- can be committed to a Git repo

A very rough example, which used `Numbers` and does not follow the rigorous definition provided here, but which was trying to do something much less systematic in order to reason about the on-chain state, can be found here

https://github.com/Joystream/joystream/issues/2359

# Review

The purpose of this review is to identify rooms for improvement in our current architecture and node implementations, as well as develop a more accurate understanding of what sort of policies will need to be implemented, along with what a realistic cost structure looks like.

For the purposes of tractability and more graceful onboarding of a third party reviewer, it is suggested that the review be split into the following stages.

## 1. Low-hanging Fruit

In this stage we are looking to identify a range of adjustments or changes that can be made to the different components of the system which move us closer to the system goals, but which still take the overall system architecture as given. These adjustments are very likely to be related to the implementation and architecture of the individual nodes, their APIs and how they interact with uploaders, downloaders and each other. It's not going to be obvious in all cases what sort of changes genuinely can be considered taking the current overall architecture as given, vs. constituting fundamental or changes, but this question can be addressed on an ongoing basis with developers.

If there are obvious changes that are needed, in the sense that without them the system is not likely to be feasible at almost any level of service, for example in the face of Denial-of-service risks, then they should also be introduced in this analysis.

## 2. A Service Model: Feasibility, and Optimal Organisation and Cost

Herein we assume a system which incorporates whatever changes were concluded to be advisable in the analysis of the prior step. The goal is to define a full set of service constraints and model, as described above. The constraints must in some way cover the following topics:

- updating on-chain policies can happen fast enough with changing circumstances.
- uploads generally can happen at the pace that they max out the egress capacity of a consumer connection.
- permanently loosing data is unlikely.
- latency from the user pressing the `play` button in their apps, so to speak, to when the video starts, must be predictably low.
- the capacity to deal with some content going viral
- some geographic areas are more interested in some creators and some content than others.
- denial of service attacks are costly, if not infeasible.

## 3. Major Changes

In this stage we are looking to identify a must broader range of adjustments or changes than in the first stage, in particular if they unlock significant benefits in terms of cost saving, reliability, performance or maintainability.

## 4. An Updated Model

In this stage we looking to redo the constraints and model based on the updates made in the prior stage.

**Comment by vreddhi** [comment]
@bedeho Some review comments on low hanging fruits regarding Colossus. A few points may relate to Argus as well, but i will comment on it in a while:

1. The Authorization server needs to be scalable, as this might be a bottleneck to upload contents. OAuth is a proven open-source mechanism, and I would tend towards leveraging the same.
2. We need rate limits in place for upload operations.
3. I would imagine the storage node to leverage a system like Apache Zookeeper to ensure the validity of data replication (https://zookeeper.apache.org/doc/current/zookeeperOver.html)
4. The platform should have the capability to expose the format and other characteristics of the media via some metadata
5. The platform in future maybe used to build applications on top of it, for which it is important to consider:
    a. To design some kind of mechanism where in the platform has the capability to allow and comprehend some kind of configurable features like:
        i. Adaptive bitrates while uploading, and as well as streaming via Argus
        ii. Allow application to dictate the streaming formats like HLS, HDS, MPEG etc.,
6. It is important to define where or who is expected to implement the media format conversions.
    a. The applications that may be built on top of joystream platform may expect some kind of metadata information either from Colossus or Argus to enable it to convert the ingest stream of data to desired formatted output.
7. Is there any thoughts on ad insertion? Applications in future may want to insert ads to incentivize their users.
    a. The platform should have a mechanism to validate the streaming request to continue playback immediately after ads. A simple timeout mechanism would give a bad experience.

Tagging @shamil-gadelshin here as well.
