### ISSUE TITLE
CLI: Allowing easy api inspection and specifying a custom api uri

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#281]
While working on the CLI I had an idea for a command that would allow me to easily check and test, for example, the node's available `api.query` methods (something like "Chain state" in Pioneer, but from within the CLI). I figured it may be a good idea to introduce the `api:` commands family, that will, among others, allow this lower-level interactions with the api.

The basic idea is to include commads such as:

- `api:setUri WS_API_URI` - used to specify the custom uri that the CLI will then use by default to establish an api connection
- `api:getUri` - used to retrieve currently used api uri
- `api:inspect TYPE --module=module --method=method --execute --callArgs=args` - this will be a little bit more complex command that would allow to either display all the available `api.{TYPE}` modules/methods (along with available descriptions), or execute given method (optionally, with some additional arguments) based on provided flags. In the example I provided each flag from left to right depends on all the flags specified before it (ie. both `--module` and `--method` must be specified in order to use `--execute` etc.) I think such command structure will allow users to be able to quickly "scan" the api, call the methods they'd like to test, easily switch between modules etc. - all of that just my slightly modifying the last command they've used.

Some more examples of how I imagine the usage of `api:inspect`:

- `api:inspect query` - lists all available `api.query` modules (ie. `system`, `staking`, `members` etc.)
- `api:inspect query --module=staking` - lists all available `api.query.staking` methods along with the descriptions
- `api:inspect query --module=staking --method=validators` - describes the `api.query.staking.validators` method
- `api:inspect query --module=staking --method=validators --execute --callArgs=5DEL7NKTWv3DvfwLfUpuPFt4MwiCuyDihGrNDxSLvmDMwMXw` - executes the `api.query.staking.validators` method with the provided address as argument and displays the result. This will also have to support multiple arguments and more complex input types (instead of just simple strings)

**Comment by bedeho** [comment]
Done in #286
