### ISSUE TITLE
Metadata for external resources for members

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2813]
# Background

Often it is useful to be able to identify how to connect directly with a channel or a member, outside of Joystream, for purposes of collaboration, ideation, business propositions, research, etc. Currently we do not have a metadata standard for this.

# Proposal

For both members and channels, add decorations to the metadata standard for each entity, to support adding one or more of the following

- Email
- Handle on one among a standardized, and easily extensible, set of services: the following seem sufficient for starters
  - Twitter 
  - Telegram
  - Discord
  - Facebook
  - YouTube
  - Matrix
  - IRC
  - Wechat
  - WhatsApp
- Raw link

Obviously only one value per category.

**Comment by dmtrjsg** [comment]
External resources for channels are covered here:
- https://github.com/Joystream/joystream/issues/3930

**Comment by dmtrjsg** [comment]
To be addressed after carthage work is done on Pioneer
<img width="451" alt="Screenshot 2022-07-19 at 09 10 57" src="https://user-images.githubusercontent.com/93924525/179700945-f7cc4455-bca3-4022-9119-b1ef8ecf9b31.png">
