### ISSUE TITLE
Channel ownership transfer (or swap with payment)

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2816]
# Background
Primary use case so far has been in order to facilitate setting up channels for creators, who do not have tJOY/JOY, with the goal of being able to auto synch content from YT on their behalf. Importantly, this should be in a context where any `sudo` or `sudoAs` features are not available.

The steps would be

1. Creator signs up and authenticates ownership of channel `X` on YT.
1. Creator provides raw account `A_X` to infra.
1. Infra creates a new channel `Y` on Joystream under robot member `infra`.
1. Infra adds `infra` as a collaborator to `Y`: this could possibly be one extrinsic if we enhance creation parameters.
1. Infra creates member `member_X` on-chain, controlled by controller account `A_X`.
1. Infra transfers ownerhsip from `infra` to  `member_X`

At this point  `infra` can keep synching & uploading videos to `Y`, but creator can opt out unilaterally at any time.

# Proposal
Add simple transfer ownership feature to channels, should def. be double-opt in, and we may as well throw in a side-payment condition feature, like for NFTs, in order for members to do trustless sales of channels if they want.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958578530831) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Actually, no reason this can't be across all possible channel owner types, can should ahve double opt-in with side-payment feature, just like we have for NFTs.

**Comment by shamil-gadelshin** [comment]
> 5. Infra creates member member_X on-chain,

Do we use existing member invitation infrastructure or we need to create a third way to introduce a member (assuming 'buying the membership' is a second way)?

> 6. Infra transfers ownerhsip from infra to member_X

This the only step that requires the runtime changes, correct? 

We will introduce an extrinsic in the content pallet with ownership transfer and reward account change. 

> At this point infra can keep synching & uploading videos to Y, but creator can opt out unilaterally at any time.

Does it require the runtime change?

> Add simple transfer ownership feature to channels, should def. be double-opt in, and we may as well throw in a side-payment condition feature, like for NFTs, in order for members to do trustless sales of channels if they want.

Does it mean that we need creating the ownership transfer in two steps (extrinsics)? The first one would be an actual transfer and the second one would be a new owner confirmation.

**Comment by bedeho** [comment]
> Do we use existing member invitation infrastructure or we need to create a third way to introduce a member (assuming 'buying the membership' is a second way)?

So you should actually just disregard everything except the channel swap, I only described this part as a motivation for the feature. But to just answer the question: we would use what we already have.

> Infra transfers ownerhsip from infra to member_X

Correct, however, you dont need to do anything with reward accounts, because those will be changed to module accounts imminently, to unlock creator tokens. However, one thing that you probably also should add is to clear out any existing collaborators on the channel. I don't actually remember if collaborators have been implemented yet, if not, then just disregard.

> At this point infra can keep synching & uploading videos to Y, but creator can opt out unilaterally at any time.

No.

> Does it mean that we need creating the ownership transfer in two steps (extrinsics)? The first one would be an actual transfer and the second one would be a new owner confirmation.

Yes.

**Comment by shamil-gadelshin** [comment]
> However, one thing that you probably also should add is to clear out any existing collaborators on the channel. I don't actually remember if collaborators have been implemented yet, if not, then just disregard.

Collaborators were implemented but how would we keep `infra` as a collaborator then? We could introduce a boolean flag to erase collaborators conditionally though.

Should we erase `moderators` and `cumulative_payout_earned` as well? 
Here is the full struct:
```
pub struct ChannelRecord<MemberId: Ord, CuratorGroupId, AccountId, Balance> {
    /// The owner of a channel
    pub owner: ChannelOwner<MemberId, CuratorGroupId>,
    /// The videos under this channel
    pub num_videos: u64,
    /// If curators have censored this channel or not
    pub is_censored: bool,
    /// Reward account where revenue is sent if set.
    pub reward_account: Option<AccountId>,
    /// collaborator set
    pub collaborators: BTreeSet<MemberId>,
    /// moderator set
    pub moderators: BTreeSet<MemberId>,
    /// Cumulative cashout
    pub cumulative_payout_earned: Balance,
}
```

Implementation detail - I'm going to introduce a `ownership_confirmed` field in the `ChannelRecord` and I will prohibit most operations with channels when it's false. Or should I skip those checks for other extrinsics (like `create_video`) and create a separate task for it?

**Comment by bedeho** [comment]
> Collaborators were implemented but how would we keep infra as a collaborator then? We could introduce a boolean flag to erase collaborators conditionally though.

Ah yes, ok, lol - forgot about the original use case now. So cleanest is then to bundle it in with the transfer offer, so that the new owner is accepting it transparently as part of the deal.

> Should we erase moderators

Yes we can, this is going away, but until it is, this is the correct approach.

> Should we erase ... cumulative_payout_earned as well?

Def. not.

> Implementation detail 

- Great observation on the blocking, I agree blocking most owner actions make sense, possibly all, except cancelling the transfer request, or it being accepted.
- I don't think you need a separate `ownership_confirmed: bool` field from the core state that just represents the transfer itself? Something like

```Rust

pub struct ChannelRecord<MemberId: Ord, CuratorGroupId, AccountId, Balance> {
    /// The owner of a channel
    pub owner: ChannelOwner<MemberId, CuratorGroupId>,
    
    pub transfer_status: ChannelTransferSatus
}

enum ChannelTransferStatus {
 NoActiveTranser,
 PendingTransfer(PendingTransfer)
}

struct PendingTransfer { 
  pub new_owner: ChannelOwner<MemberId, CuratorGroupId>,
  pub new_collaborators: BTreeSet<MemberId>,
  pub price: Balance /// <-- can be 0, which means free
}

```

this representation requires no other state. The extrincs needed would be

- `update_channel_transfer`: updates channel transfer status to whatever the current owner wants.
- `accept_channel_transfer`: `new_owner` accepts ownership, provides payment, and ownership is updated. **Remember to include commitments to new_collaborators and price to avoid current owner racing to update terms**

**Comment by shamil-gadelshin** [comment]
The code was merged.
