### ISSUE TITLE
List of query node issues from Atlas perspective

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#2818]
This can be a long-living issue where we track any problems that Atlas runs into w.r.t. the query node.

- [ ] _A lot_ of issues with the search query. It's barely usable at this point and will provide very poor user experience. More details in https://github.com/Joystream/joystream/issues/2800
- [ ] Poor performance on several queries. If you open the main deployment of Atlas today, a lot of queries will take >2.5s to resolve which creates long loading experience:
<img width="674" alt="Screenshot 2021-11-05 at 11 48 58" src="https://user-images.githubusercontent.com/12646744/140499384-87a17b3a-63aa-41ce-ad0d-6bc8aa6758af.png">

- [x] Separated `Availability` fields - back when working on Sumer we introduced this simple hack that creates asset availability fields directly on channel/video objects. For example `Video.thumbnailPhotoAvailability`. This should be exactly the same as `Video.thumbnailPhotoDataObject.liaisonJudgement`. Worked well for some time but recently this bit us back because we started hitting some inconsistencies in the cache when we fetch `dataObject` directly (the "shortcut" field on Video don't get updated automatically). Ideally, we'd remove that and just replace with nested filtering

**Comment by bedeho** [comment]
> inconsistencies in the cache when we fetch dataObject directly (the "shortcut" field on Video don't get updated automatically). Ideally, we'd remove that and just replace with nested filtering

What cache is this? and where is the `shortcut` field not updated as it should, and why?

**Comment by kdembler** [comment]
It's our in-app GraphQL cache. Specific case here is when we are polling the query node to see whether an upload was finished. We do that by querying a given `dataObject` until the `liaisonJudgement` is `ACCEPTED`. So once that happens, our cache entry for this data object contains an updated `liaisonJudgement` but the `thumbnailPhotoDataObject` on video object will have an old value and we need to do a small workaround to handle this. It's not a biggie but just an example that duplicating fields may not be the best approach in the long term
