### ISSUE TITLE
Built-in reward for bounty oracles

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2821]
Bounty creator should be able to specify a fixed reward, as part of creating bounty, which is diverted towards the oracle, at least if its not the council, which is dispersed in scenarios where the oracle submits a judgement, otherwise it should be returned to bounty creator.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958578817342) by [Unito](https://www.unito.io)

**Comment by L3pereira** [comment]
I have fixed this in commit: d3d9e2ed3cfe0b86a9f5b51bd49f412b2421ac18

**Comment by bedeho** [comment]
Done.
