### ISSUE TITLE
Bounties locks reuse excludes invitation lock

### ISSUE THREAD

**Issue by jodator** [Joystream/joystream#2824]
Hi, quick question about Bounties locks on the Olympia runtime: is this intentional that `Bounties` lock can't be set when there's `Invitation` lock set. All other locks allow `Invitation`. Please compare it with a lock above (or any other):

[https://github.com/Joystream/joystream/blob/db3885858a7812377a19390968bdbf65221f0270/runtime/src/constants.rs#L214-L223](https://github.com/Joystream/joystream/blob/db3885858a7812377a19390968bdbf65221f0270/runtime/src/constants.rs#L214-L223)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711118061747) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
It should be allowed.

**Comment by shamil-gadelshin** [comment]
Fixed.
