### ISSUE TITLE
Olympia Release

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2855]
# Note
This is a preliminary document, it must be checked by key contributors to give input on expected full costs of various intended changes, and also whether goals in one area are fully reflected in requirements of dependent areas.

# Name
`Olympia`

# Brand
![](https://user-images.githubusercontent.com/437292/143074743-0ec4f541-520b-4c81-9c1d-c2472c9bd0aa.png)

# Goals
### 2. `Launch new major runtime.`
# Overview
## Launch V2 of Pioneer
This is it folks! :rocket:

The, by far, most developed governance product in the entire space is launching, this is the future, I will just leave it at that.

## Launch new major runtime
We are rolling out a new

* proposal system
* council and election system
* membership system: p2p invitations, referrals cuts, etc.
* staking system: reuse your stake in elections)
* a constitution
* a crowdfunded bounty module: Gitcoin + Kickstarter inside of your blockchain
* a new on-chain forum with reactions and polls

and probably more that I just can't even remember. Now, importantly, not everything here is surfaced in Pioneer! no time, hopefully community+Pioneer team can work hard to bring all of this to the Pioneer users soon. Everything is reasonably well explained in the handbook, which has targeted `Olympia` runtime

https://joystream.gitbook.io/joystream-handbook/

### Team
* **Shamil**
* **Ignazio**

### Work Scope
* Reconcile oustanding content director features and `Giza`: https://github.com/Joystream/joystream/issues/2890
* The runtime above into existing `Olympia` runtime: https://github.com/Joystream/joystream/issues/2891
* Fix locking problems with bounties
  * https://github.com/Joystream/joystream/issues/2824
  * https://github.com/Joystream/joystream/issues/1899
* On-chain migration of memberships: https://github.com/Joystream/joystream/issues/2892

### Current Status
Nothing has been done.

### Initial Division of labour
**Shamil** decides.

### Team
* **Shamil**

### Work Scope
* Unclear, possibly nothing, possibly issues identified during `Giza`.

### Current Status
Nothing started.

### Initial Division of labour
**Shamil** only.

### Team
* **Leszek**

### Work Scope
* Unclear, possibly nothing, possibly issues identified during `Giza`.

### Current Status
Nothing started.

### Initial Division of labour
**Leszek** only.

### Team
* **Andy**
* (**Leszek**)

### Work Scope
* Reconcile `Giza` and `Olympia` query node, Leszek remarked: "I imagine it won't be that difficult compared to other parts like integration tests or CLI. It may take a day or two."
* Explore Subsquid v5: https://github.com/Joystream/joystream/issues/2893

### Current Status
Nothing started.

### Initial Division of labour
Team availability determines, unclear what **Andy** status will be.

### Team
* Atlas Team

### Work Scope
* Update to use new membership system module, should be very mild change.
* Possibly query node related if Subsquid upgrade is executed.

### Initial Division of labour
**Klaudiusz** decides.

### Team
* Pioneer Front-End engineering team.
* Mateusz
* Dmitry
* Bedeho

### Work Scope
* Complete Pioneer v2
  * Kanban: https://github.com/orgs/Joystream/projects/44
  * Plan: https://github.com/Joystream/pioneer/issues/1475
* Add FM program integration: https://github.com/Joystream/pioneer/issues/1888
* Make tooltips content: https://github.com/Joystream/pioneer/issues/1785
* Make content for videos: https://github.com/Joystream/pioneer/issues/1787
* Add _some kind_ of analytics.

### Initial Division of labour
* Pioneer team on Pioneer.
* Bedeho on onboarding videos.
* Dmitry on analytics & tooltips content.

### Team
* **Leszek**

### Work Scope
* Reconcile `Giza` and `Olympia` CLIs

### Current Status
Nothing is done here.

### Initial Division of labour
**Leszek** only.

### Team
* **Anuj**
* **Mokhtar**

### Work Scope
* Reconcile `Giza` and `Olympia` changes.

### Current Status
Nothing is done here.

### Initial Division of labour
Unclear.

### Team
* **Mokhtar**
* **Shamil**
* **Leszek**
* **Ignazio**

### Work Scope
* Review current discrepancy between tests
* Plan reconciliation process
* Plan possible extensions or new tests.

### Current Status
Comment from Leszek

> In Olympia we moved integration tests to completely different directory to avoid conflicts, because there were substantial changes in the framework, api, setup etc. I suspect it may take a considerable amount of time to merge those (probably over a week?)

### Initial Division of labour
Unclear.

### Team
* **Mokhtar**

### Work Scope
* Update faucet server: https://github.com/Joystream/atlas/issues/1596
* Update status server.
* Update Polkadotjs library & examples.

### Current Status
Nothing has been done.

### Initial Division of labour
**Mokhtar** only.

### Team
* **Martin**
* **Ben**

### Work Scope
* Write testing plan in advance and share with Bedeho.
* Conduct test in accordance with plan. The testing here should be targeting CLI, Query Node and Atlas working well together. There are very minor new features, but they are of trivial significance, its mostly about confirming that existing functionality still works. CLI should be a bit more involved, as there will be some new non-trivial features. Part of the rationale for the testing is also to help get informed for updating tutorials.

### Current Status
Nothing has been done.

### Initial Division of labour
Unclear.

### Team
* **Robert**
* **Ben**
* **Martin**
* **Edvin**

### Work Scope
* Tokenomics page: currently https://testnet.joystream.org/#/tokenomics
  * We should as the easiest possible solution, first just move this page into a standalone page, for example on `www.joystream.org/testnet_tokenomics`, and perhaps add link in the footer of the site, that way, if we have no time for anything else.
  * Another alternative is to create a new standalone page which is much more comprehensive and useful than the current page, informed by this feedback page https://github.com/Joystream/joystream-org/issues/411.
* Update website for announcement.
* Update website for release.
* Update tutorials: this will be very comprehensive, as both system properties and CLI has been radically changed.
* Update KPIs
* Announcement and release communications: blog + newsletter

### Current Status
Nothing has been done.

### Initial Division of labour
**Robert** decides.

# Project Management
## Release Manager
`Mokhtar`

The release manager is responsible for tracking overall progress, detecting delays and course-correcting. Tracking will be done weekly in this issue

https://github.com/Joystream/joystream/issues/2852

as described by the following methodology

https://github.com/Joystream/joystream/issues/474

## Release Branch
https://github.com/Joystream/joystream/tree/olympia

## Github Project(s)
We are doing everything in one project.

https://github.com/orgs/Joystream/projects/44

### Biweekly(ish) Release Meetings
A release wide meeting will be organised semi-regularly, we could start at a pace of once ever 2 weeks to begin with. Experience has shown that, even when there is no obvious issues that need tackling, discussions often reveal issues and corner cases that have not been accounted for. We can aim for one team rep. being present, so as not to distract everyone. Log will be kept here:

https://github.com/Joystream/joystream/issues/2579

# Question
* What update, if any, is required to our version of Polkadotjs?
* Leszek has aired the possibility transitioning to Subsquid (v5) from Hydra, but the timing of this seems risky to me, as it introduced unpredictable delay consequences into both Atlas, CLI, integration tests, Colossus, Storage and Pioneer itself, and we already know it is missing a host of features that are needed. The biggest upside of the transition is solving some outstanding problems with query speed and relationship handling, but it's not clear that there is enough urgency to warrant taking the risk.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711120430917) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
Re "Unclear, possibly nothing if no query node transition is initiated." in Atlas scope: I'm not sure what the exact changes to memberships are introduced in Olympia but won't the onboarding flow in Atlas be affected?

**Comment by mochet** [comment]
(not directly related to the Release Plan, but hopefully a relevant/important point to raise nonetheless)
Since to the best of my knowledge we will lose all proposals + forum posts, I think it is important to back up this data and either/and/or:
* Back it up on the `community-repo`
* Have a few nodes/query node (basic infrastructure) to keep `sumer`/`giza` running, so people can access this data if they need to (on a separate URL)
* Have the `operations` group have a KPI for managing/archiving/hosting this data

The importance of this data can not be understated, our community has existed for a significant amount of time and there are numerous proposals/forum posts that are invaluable considering our current governance structure. Many things have already been agreed upon on the current testnet and losing access to all of this would be disastorous.

**Comment by bedeho** [comment]
> Re "Unclear, possibly nothing if no query node transition is initiated." in Atlas scope: I'm not sure what the exact changes to memberships are introduced in Olympia but won't the onboarding flow in Atlas be affected?

Ah yes, you are right, this may have implications for Atlas, forgot that, but probably extremely mild, but will update plan.

**Comment by bedeho** [comment]
# Adding Bounty Module

It seems like it may make sense to include bounty module in this release, given that Pioneer support is a few weeks away, if that is the case, the following trivial expansions of runtime scope make sense to make the bounty module more usable with the HR working group

- **Allow an HR worker to relinquish control of a bounty if they need to leave the group, or just cannot fulfil their duties:** https://github.com/Joystream/joystream/issues/2947
- **Allow council to change the oracle if an HR worker is not willing to unilateraly surrender control of a bounty, e.g. if fired:** https://github.com/Joystream/joystream/issues/2975
- **Allow HR worker who funded bounty to refund working group if bounty failed**: https://github.com/Joystream/joystream/issues/2977

and if there is a lot of time, this would be a stretch goal: https://github.com/Joystream/joystream/issues/2979
