### ISSUE TITLE
Scaleable distribution bucket & family data model

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2865]
# Background

In the original on-chain data model for distribution bucket families and their distribution buckets, an entire such family, and corresponding buckets, were stored as one single storage value.

```Rust
pub struct DistributionBucketFamilyRecord<DistributionBucketId: Ord, WorkerId: Ord> {
    pub distribution_buckets: BTreeMap<DistributionBucketId, DistributionBucketRecord<WorkerId>>,
}
```

This model means that one only needs a single database operation, reading this record, when one, during bag creation, is trying to establish what distribution buckets should be responsible for a bag. This is nice. The problem is however that one has to constrain the size of this object, in particular `distribution_buckets`, as the read/write time is eventually going to start rising as well. 

https://github.com/Joystream/joystream/issues/2234

Each byte contributes `0.0003838545018007194` and `0.002405831452581034` seconds to read and write times on reference hardware, respectively. It also tradeoff between complex+brittle or wasteful+expensive fees for impacted extrinsics, as they will either need to have the user commit to a map size as a way to charge precise fees, or to just always charge as if the object has max size, respectively.

The most fundamental problem is that any limit we impose on size of `distribution_buckets` will impact the ability of the system to scale, and it is very hard to make reliable predictions about what what limits we will need into the future on mainnet. What compounds this is that if our utilization runs into this limit, then trying to move away from a limit based model will cause the need for a in-production runtime upgrade+migration of the most epic proportions.

# Possible Solution

The easiest solution is to go for a standard model where `DistributionBucketRecord` are not stored inline like this, but in a separate double map with key space `DistributionBucketFamilyIdxDistributionBucketId´. The bag creation process will now try to find a suitable buckets subset of buckets, in each family, just like storage buckets are found, using a combination of random sampling of the key space + a fallback linear method. The number of database operations will go up, but they will each be small, and the number of operations does not scale with size of the system. This will imply

1. introducing a double map.
2. distributor buckets are identified by combination of family and bucket id.

# Preliminary Work

Before we make any change, it would be useful to map out what the full range of consequences would be on trying to update this now, meaning

- runtime
  - extrinsics
  - events
  - storage
  - unit tests
- colossus
- query node: mapping & schemas
- argus
- cli
- integration tests
- anything else?

Can each party assigned here comment on how much time it require them to update the part of the surface area for this change? 
Can each party also comment on whether it would be of significant disadvantage to do this at the very end of the release work, vs. now, w.r.t. time required and risks of new bugs?

**Comment by shamil-gadelshin** [comment]
This change affects the `runtime` and doesn't affect `Colossus`. The runtime part change (with new random bucket algorithm) estimation: 2-3 days.

**Comment by dobertRowneySr** [comment]
if this does not change:
- declaration of  `storage::Module::<T>::upload_data_objects`
- declaration of  `storage::Module::<T>::delete_dynamic_bag`
- declaration of `storage::Module::<T>::DataObjectCreationParameters`
- declaration of `storage::Module::<T>::UploadParametersRecord`
- declaration of `storage::Module::<T>::ChannelId`
- declaration of `storage::Traits::DataObjectId`

Then the `runtime_modules/content` is not affected
Integration test migration scenarios do not rely on assets upload/removal, so they also are not affected

**Comment by Lezek123** [comment]
Based on what I estabilshed by asking @shamil-gadelshin: 
```
leszek: Am I understanding correctly that this means that DistributionBucketId in going to be a Tuple/Struct like [FamilyId, BucketIndex], and we could have, for example, values like: [1, 1], [1, 2], [2, 1], [2, 2]?

shamil: Looks like current plan. Yes
```

**@joystream/types:**
- Changes related to new `DistributionBucketId` representation
**Estimated time:** < 30m (not counting review)

**Query node mappings:**
- Change the format of `DistributionBucket` `id` field
- Small changes in all mappings that rely on `DistributionBucketId`
**Estimated time:** ~1-2h (not counting review)

**Argus:**
- Changes related to custom `buckets` configuration (which allows distributing buckets of specified ids): config schema, api (`api/v1/buckets`, `/operator/api/v1/set-buckets`), types, `node:set-buckets` command
- Small changes in (almost?) all CLI commands (change format of the extrinsic params)
**Estimated time:** ~2-3h (not counting review)

**CLI:**
- No changes

**Integration tests:**
- Changes in `initializeDistribution` flow (https://github.com/Joystream/joystream/pull/2849)
**Estimated time:** ~2h (not counting review)

**Total estimated time:** ~1 day of work + possibly ~1 day of reviews

**Comment by bedeho** [comment]
Thank you for this excellent information everyone, but noone commented upon this

 `Can each party also comment on whether it would be of significant disadvantage to do this at the very end of the release work, vs. now, w.r.t. time required and risks of new bugs?`

**Comment by Lezek123** [comment]
> Can each party also comment on whether it would be of significant disadvantage to do this at the very end of the release work, vs. now, w.r.t. time required and risks of new bugs?

The further we push it the more code (mostly in integration tests) is going to rely on the current model, but I think it's mostly going to be an issue of how `BucketId` is represented, so most likely not a major one.

We will also have more limited feedback about the new model from the staging network tests. We may not have a good integration tests coverage for more complex scenarios with multiple distribution buckets, familieis etc. before the release either (unless we prioritize those kind of scenarios), so I think in that regard it may be a considerable risk to do it at the very end.
