### ISSUE TITLE
Giza: Storage bucket to bag assignment runtime bug

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2882]
During recent tests a major bug in the Giza runtime related to storage-buckets-to-storage-bag assignments was discovered

**Bug description**

1. When we try to create a new channel with 2 assets and one of the storage buckets assigned to store the channel's bag has `voucher.objectsLimit < voucher.objectsUsed + 2`, the runtime will throw `StorageBucketObjectNumberLimitReached` error
2. At this point something will "get stuck" in the runtime and no matter how we change the replication factor for channel bags (`update-dynamic-bag-policy`) or how many other valid buckets we have (we can also try creating new ones), any attempt to create the channel (as mentioned in step 1) will always result in `StorageBucketObjectNumberLimitReached`
3. The only way to break out of the situation described in step 2 seems to be increasing the `objectsLimit` of the bucket mentioned in step 1. If we make the limits high enough for the bucket to be able to accept 2 new assets, we should be able to finally create the channel, but the current status of the buckets (`acceptingNewBags` flag) and `DynamicBagPolicy` of `Channel` will have **no effect** on the new bag's assignment. The runtime will assign the new channel bag to the buckets it has "already chosen" in step 1. For example: If in step 1 we had `dynamicBagCreationPolicies(Channel).numberOfStorageBuckets == 3` and all buckets were accepting new bags and now we have `dynamicBagCreationPolicies(Channel).numberOfStorageBuckets == 1` and none of the buckets are accepting new bags, the new channel bag will still be assigned to 3 buckets (one of them beeing the bucket which limits we just increased).
4. Any channel created after step 3 will have its bag correctly assigned according to current policy and bucket statuses.

_**Edit:** It turned out that the channel's dynamic bag is actually created and assigned to buckets in step `1.` (unsafe mutation) even though the extrinsic fails and the channel itself it not created. See discussion below._

**How to reproduce**

The easiest way is to use the script I created on my `giza-integration-tests` branch: https://github.com/Lezek123/substrate-runtime-joystream/blob/giza-integration-tests/reproduce-giza-issue.sh

**Comment by bedeho** [comment]
- Really great find, how was this found?
- I would the initial extrinsic invoked in the content directory for channel creation should just fail because the checks before the `mutation safe` barrier should prevent any side-effects when it asks the data directory whether the imminent addition of data objects is feasible. Is this not what is happening? Seems to not be the case, as behavior of the system seems to change, i.e. there has been some side-effect.

**Comment by Lezek123** [comment]
Ad 1. I noticed it during my local tests (related to storage node PR) when I tried to see what happens when one of the storage buckets reaches the objects / size limit.

Ad 2. This actually made me realize I missed quite an obvious cause of this issue. The channel bag is beeing created even though `createChannel` extrinsic fails (so it's actually created in step 1, even though the channel itself is not created):

![image](https://user-images.githubusercontent.com/19978260/144491533-21bc46aa-72a1-406f-9614-cebbf9487677.png)

I think this makes things much more clear, thank you.

**Comment by bedeho** [comment]
> Ad 2. This actually made me realize I missed quite an obvious cause of this issue. The channel bag is beeing created even though createChannel extrinsic fails (so it's actually created in step 1, even though the channel itself is not created):

This is disastrous if true, this means the integration has not been done properly.

**Comment by mnaamani** [comment]
Its it a good idea to review all the extrinsics in content module that invoke storage module methods to look for similar cases, when creating/updating videos (of course that doesn't involve creating new bags but still..)

**Comment by dobertRowneySr** [comment]
explanation at #2895
