### ISSUE TITLE
Giza: Auto-assigning buckets on channel creation is an unsafe operation.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#2883]
From the `storage` pallet perspective, the dynamic bag creation with storage bucket auto-assigning and data uploading are independent processes. But the `content` pallet uses both processes together on channel creation (`create_channel` extrinsic). Having at least one bucket with exhausted resources (that will prevent it from accepting new objects), we run into a situation when the dynamic bag could be created, but data uploading would fail randomly (depends on the random bucket choice on the dynamic bag creation) and the `create_channel` extrinsic would also fail randomly as a result.

Possible mitigation:
- we prevent uploading data objects on channel creation
- we introduce the 'free resources' constraint for the random bucket selection on dynamic bag creation

Relates to https://github.com/Joystream/joystream/issues/2882

Example: 
We have 2 storage buckets - one has a lot of resources left (100 GB and 100 objects in the bucket voucher), and another one is almost full (1 GB left and 1 object in the voucher). Our dynamic bag creation policy is set to 1 storage bucket per channel. We try to create a channel with a single object attached to the creation request (`create_channel` extrinsic) with 2 GB. Now, our random bucket selection gives us 50% for the success of the `create_channel` extrinsic. The first part of the extrinsic will successfully and randomly pick a full or normal bucket and the second part (uploading the assets)  will either succeed or fail on exceeding the bucket resources.

**Comment by mnaamani** [comment]
Just a comment on the suggested solutions:
> Possible mitigation:
> 
>     * we prevent uploading data objects on channel creation

From user experience perspective I think this is not an option. Channel creation and storing initial assets should be atomic.
> 
>     * we introduce the 'free resources' constraint for the random bucket selection on dynamic bag creation

Yes, this is the most sensible solution. 

`storage:create_dynamic_bag()` should take additional parameters (num_objects, size) and the storage picker can filter out buckets with vouchers that cannot accommodate.

Additionally perhaps the `DynamicBagCreationPolicy` can have  new parameters: `minimum_free_objects` and `minimum_free_size` as constraints when selecting buckets, and the storage operator can set these to reasonable values.

edit:
A more general solution would be to pass a predicate to the create_dynamic_bag() so each client module of the storage system could have additional opinion about weather it wants the bag to be created based on the set of buckets selected by the storage system?

**Comment by mnaamani** [comment]
After discussion we decided to proceed with the most general fix.

Simply storage:create_dynamic_bag() will take additional optional parameters that specifies how much storage capacity needs to be guaranteed. That allows for creating a bag with an initial set of data objects. If the storage system cannot guarantee the required capacity the storage system should not create the bag.

This enables the content module to safely make the channel creation with initial set of assets be atomic.

With this added capability of selecting buckets with some guarantee of capacity availability it might be worth asking:
 - Should the initial requested capacity for a channel be a policy value managed by the content lead? So it can be more than just the initial assets for the channel. Effectively giving the content lead a way to give a better initial experience for creators. It would still be a bad experience if all you were able to do was create a channel and its cover photo and avatar and immediately run out of storage capacity in the allocated buckets.

**Comment by mnaamani** [comment]
Maybe selecting buckets only based on desired capacity is too limited. If we can pass a predicate to the create_dynamic_bag() different client modules can have a more diverse set of requirements for the selection.

**Comment by mnaamani** [comment]
> After discussion we decided to proceed with the most general fix.
> 
> Simply storage:create_dynamic_bag() will take additional optional parameters that specifies how much storage capacity needs to be guaranteed. That allows for creating a bag with an initial set of data objects. If the storage system cannot guarantee the required capacity the storage system should not create the bag.
> 
> This enables the content module to safely make the channel creation with initial set of assets be atomic.
> 
> With this added capability of selecting buckets with some guarantee of capacity availability it might be worth asking:
> 
>     * Should the initial requested capacity for a channel be a policy value managed by the content lead? So it can be more than just the initial assets for the channel. Effectively giving the content lead a way to give a better initial experience for creators. It would still be a bad experience if all you were able to do was create a channel and its cover photo and avatar and immediately run out of storage capacity in the allocated buckets.

This fix is incomplete. It is not sufficient to pass size and total objects. The storage system also has to ensure that the assets to upload pass all the validation rules with `validate_upload_data_objects_parameters()`.

So here is the final suggested solution:

Add two methods in storage module:
- `can_create_dynamic_bag_with_objects(bag_id, deletion_prize, upload_params)`
- `create_dynamic_bag_with_objects(bag_id, deletion_prize, upload_params)`

refactor in storage module:
- `validate_upload_data_objects_parameters()` to work with a bag that hasn't been created yet.
- the storage bucket picker to select buckets with required free capacity.

refactor in content module:
- create_channel to use two new methods in storage module can/create_dynamic_bag_with_objects(..)

**Comment by shamil-gadelshin** [comment]
Fixed
