### ISSUE TITLE
Idea: per-member proposal limit

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2884]
I saw a similar feature on BitCountry (https://github.com/bit-country/)  which is also Substrate based.

The only real purpose of something like this would be to prevent someone abusing the governance system, or introducing so many different/conflicting proposals in an attempt to confuse the governance system (or simply because having one person create all proposals isn't really an ideal thing to have).

It would also possibly help to have some balance with "interests" that are presented to the DAO--if there is too much focus on one singular area it could leave other areas of the platform not gaining enough attention.

**Comment by bedeho** [comment]
I don't think this remedy really has the intended effect, if someone wants to be abusive, they can just do it across multiple memberships, and memberships really have to be quite cheap to create, so its not really a deterrent to this kind of attack.
