### ISSUE TITLE
On-chain membership migration into Olympia

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2892]
We really have to preserve this (memberships), everything else goes, not least in order to retain ownership of channels. The difficulty is doing this in a way which does not break the query node? How do you not break the possibly existing memberships and relationships to other entities, like channels and so on, in the query node? If we just start the query node from the +1 upgrade block, being totally empty, how do we get the channels in there? as they already live there from `Giza`? This is a hard one.

Input from @Lezek123 could be useful.

**Comment by dmtrjsg** [comment]
Closing in favour of membership migration in context of new chain
