### ISSUE TITLE
Exploration of transition to Subsquid from Hydra for Olympia

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2893]
We have been promised support from Subsquid team that they would be willing to upgrade our query node to work with Subsquid v5, but before we do this we should probably make sure our schemas for Olympia are stable, otherwise we will have lots of pain reconciling changes to our original schemas with the new upgraded schemas from Subsquid. None the less, it seems some initial testing trying to map out the transition really should start already as part of Olympia.

Now actually testing whether the transition really worked will be a monumental task, we will need to _somehow_ figure out if all of the following are still working, despite the fact that we largely still do not have good integration test coverage

- Colossus
- Argus
- CLI
- Pioneer
- Atlas

**Comment by kdembler** [comment]
Oh how I wish we did this at that time. Closing :)
