### ISSUE TITLE
Questions/Suggestion: Discretionary WG lead spending needs a text field 

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2899]
### Description & Questions
Discretionary spending from WG leads is described in several places, but no single issue (that I can locate) covers it: 
* https://github.com/Joystream/joystream/issues/1094
* https://github.com/Joystream/joystream/issues/1487
* https://github.com/Joystream/joystream/issues/2477

`discretionary spending` has been described as the `lead` of any `Working Group` being able to send funds from that WG's `mint` to any user (presumably only within the group) for any purpose they want to. This is obviously a great feature that allows a lot of flexibility for the lead to deal with atypical situations.

The question is: how is this mechanism being implemented? It is simply a regular transaction from the mint? Or is the `lead` able to add some form of on-chain `description` for why this transaction was made?

`spending proposals` will supposedly have `labels` (as described here: https://github.com/Joystream/pioneer/issues/577 -- I haven't found any issue describing how this would work on the `runtime` side though). These labels will be vital to organizing proposals, and in particular act as a great way of categorizing `spending proposals` and allowing platform users to understand how spending (outside of `working groups`) is utilized.

### Relevance:
On the current testnet, we manually categorize all `spending proposals`. This data allows us to understand how the `council` is spending and what things it has allocated funds to.

![image](https://user-images.githubusercontent.com/50830161/145021617-044edee8-2949-4e81-a9d3-9739dd98c36e.png)
(this chart, which is very outdated, shows the current categorization of spending)

As shown in this proposal (https://pioneer.joystreamstats.live/#/proposals/893) due to the way the testnet currently works, it is difficult to link `WG  payments` to specific projects/tasks (for example, paying 500k JOY for a single task, like adding a UI improvement to Pioneer on mainnet). Depending on how the lead chooses to structure their group, they may be more in favor of utilizing `discretionary spending` for some things instead of hiring more workers.

### Suggestion:
Assuming this functionality doesn't already exist, add some `text field` that can be filled by `WG leads` when using `discretionary spending` allowing this usage of spending from the WG's mint to be categorized and monitored. This is highly important from a value perspective as if this spending doesn't include any data, it would become highly difficult for the Council and other platform users to understand why a WG lead is spending as much as they are (without the requirement of extensive reports, which is a less desirable option as it involves more paperwork and monitoring from all concerned parties)

Furthermore, due to there being the Council's mint and several other mints on the platform--having a way to categorize all of this spending in a single place (which can be implemented much later on, I am just asking about the core function right now) would be very useful in understanding the entire platform's spending--especially when combined with `bounty module` spending.

**Comment by bedeho** [comment]
1. Excellent writeup, really well organised and easy to process.
2. Yes this exists, check out handbook: https://joystream.gitbook.io/joystream-handbook/governance/working-groups#leader-spending
3. I don't believe this feature is actually implemented in Pioneer 2, because almost no leader actions are part of Pioneer 2 design, just because we had to prioritize, and the leaders are a very small audience, so they have to do it through the CLI.
4. Regardless of whether through the CLI or Pioneer 2, what you are describing is to have some sort of tagging system or other way of associating metadata to these spends, and currently there is no such standard, so this will need to be done, I think its a very good idea, and easy to do, relatively speaking.

**Comment by mochet** [comment]
>Excellent writeup, really well organised and easy to process. 

Thanks (: I have been working on improving how I create issues!

>Regardless of whether through the CLI or Pioneer 2, what you are describing is to have some sort of tagging system or other way of associating metadata to these spends, and currently there is no such standard, so this will need to be done, I think its a very good idea, and easy to do, relatively speaking.

I am curious to know whether the proposal system, WG discretionary spending and bounty module should all share the same tagging system? I could see some benefit in that--but it would really depend on how complex such a thing would be to implement.

**Comment by bedeho** [comment]
What would it mean for the tagging systems to be shared or not? I think tags are basically permissionless, so people can make new tags as needed.

**Comment by mochet** [comment]
> What would it mean for the tagging systems to be shared or not? I think tags are basically permissionless, so people can make new tags as needed.

Is that the best approach? What if a malicious person decides to just arbitrarily tag everything with some tag?

I don't think they necessarily need to be shared in any case, that part of the system I'm still be a bit unsure of how it will work.

**Comment by bedeho** [comment]
> Is that the best approach? What if a malicious person decides to just arbitrarily tag everything with some tag?

Obviously you can only tag your own content, but if you add lots of incorrect tags, sure that could be annoying, but not that serious of an issue.

**Comment by mochet** [comment]
> > Is that the best approach? What if a malicious person decides to just arbitrarily tag everything with some tag?
> 
> Obviously you can only tag your own content, but if you add lots of incorrect tags, sure that could be annoying, but not that serious of an issue.

IMHO that is problematic (not necessarily from an abuse standpoint, but more because of organization). It would make sense to me that maybe one of the WGs has permission to add (or remove) tags so that proposals can be more fully organized.

For example if 2-3 proposals are made pertaining to a single issue, and action only takes place some time after those proposals (maybe a runtime upgrade)--the first person to create the proposal would have to make a tag that is logical to all subsequent proposals. It would seem to make more sense that someone can retroactively "connect" all relevant proposals by adding the tags (whether they're the author or not)

**Comment by mochet** [comment]
this has now been implemented
