### ISSUE TITLE
Content Refactoring

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#2901]
# Motivations
1. First off we left behind an old PR aiming to remove unused code in the content directory, https://github.com/Joystream/joystream/pull/2680 (which was approved but never merged). This is a good moment to settle this once for all I think.
2. I would think it would be good to refactor the code used in the unit testing, in particular much of code for testing in channels & videos
extrinsics is still as it was when I started looking into the Joystream codebase. Right now the technique I used so far is the 
`mock_extrinsics` technique which call the extrinsics to be tested with an additional `DispatchResult` in order to verify assertions.
This makes setting up a testing scenario a bit cumbersome at times, expecially when I would like to set just a few parameters and 
leave all the other parameters to some default values.
The fixture approach used for example in storage module provides an elegant solution to the above problem. Plus refactoring
the testing code would allow for better test coverage
3. I already refactored the code in permissions mod to a satisfactory level, however new PRs such as the Video comments one are still based on the old permission module
4. Misc small changes that could improve code readability

*These are the main reasons, but I am sure that there could be more than those that come to my mind*

**Comment by bedeho** [comment]
Sounds good, go for it!

What branch will you base this work off, and what will you merge it into?

**Comment by dobertRowneySr** [comment]
Branch off `giza` (which has already all the collaborator feature built in)
