### ISSUE TITLE
Metaprotocol message extrinsic for all roles

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2919]
# Background
We already have generalized messages in many part of the runtime which are supposed to be interpreted off-chain by query infra, however, we don't have this systematically everywhere. These are extrinsic which don't have any side-effects, they just do actor authentication and then have an opqaue `message: vec<u8>` payload , which is also emitted in an event.

# Proposal
Add a general message broadcast extrinsic for every role in the system, making it very easy for query infrastructure to process and very clear for developers how to add their own new message semantics in any part of the system. So we should add it to

* lead or worker in a working group
* member
* council member
* candidate in an election
* proposal proposer
* channel owner
* video NFT owner
* subsystem specific worker roles that the runtime can see and validate
  * ~forum moderator~
  * ~forum moderator lead~
  * content curator
  * content curator lead
  * storage bucket operator
  * distribution bucket operator
* etc.

An idea driving why there are so many different message channels, rather than for example just having one per member, is that by having a role specific channel where the runtime has handled authentication, then it makes it super easy for anyone who wants to process a message log to first off just focus on a specific stream of messages relevant to their domain, and also not have to maintain full up date state about what member genuinely holds what role at any time in their processing logic, which would be very heavy for many use cases.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958627129537) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
Let's see if I understood it properly:
I should add for every pallet eg `content`:
```rust
pub fn role_message_broadcast(actor: ContentActor, msg: Vec<u8>) -> DispatchResult;
```
Now for the query node to be able to obtain the data I should emit event like
```rust
MessageBroadcast(actor, ...)
```
with `...` predefined `types/enums` used by the query infra to parse the message.
So all in all in the above extrinsic should expect `msg` to be some byte-string following a predefined syntax and the extrinsic should
1. check that `msg` syntax is correct
2. parse `msg`  into some predefined record/enum and decorate `MessageBroadcast` with that.

Am I on the right track? @bedeho

**Comment by bedeho** [comment]
Yes you are on the right track, but read this

https://github.com/Joystream/joystream/issues/3255

and then prepare a full list of extrinsics, with signatures, that you think you need, and then I can sign off ✅ .

**Comment by dobertRowneySr** [comment]
Here's an attempt. notation is `[Role]::[Extrinsics](params*)-> [Event]`.
## Content System
- ContentWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> ContentWorkingGroup::LeadRemarked(origin, message)
- ContentWorkingGroup::curator_remark(origin, curator_id: CuratorId, msg: Vec<u8>) -> ContentWorkingGroup::CuratorRemarked(origin,curator_id, message)
- ContentWorkingGroup::curator_group_member_remark(origin, curator_id: CuratorId, curator_group: CuratorGroupId, msg: Vec<u8>) -> ContentWorkingGroup::CuratorGroupMemberRemarked(origin,curator_id, curator_group_id, message)    
- ContentWorkingGroup::member_remark(origin, member_id: MemberId, msg: Vec<u8>) -> ContentWorkingGroup::MemberRemarked(origin, member_id, msg) =?=
## Forum System
- ForumWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> ForumWorkingGroup::LeadRemarked(origin, message)
- ForumWorkingGroup::moderator_remark(origin, moderator_id: WorkerId, msg: Vec<u8>) -> ForumWorkingGroup::WorkerRemarked(origin, moderator_id, message)
- ForumWorkingGroup::user_remark(origin, member_id: MemberId, msg: Vec<u8>) -> ForumWorkingGroup::MemberRemarked(origin, member_id, message)  
## Storage System
- StorageWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> StorageWorkingGroup::LeadRemarked(origin, message)
- StorageWorkingGroup::worker_remark(origin, worker_id: WorkerId, msg: Vec<u8>) -> StorageWorkingGroup::WorkerRemarked(origin,worker_id, message)
## Distribution System
- DistributionWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> DistributionWorkingGroup::LeadRemarked(origin, message)
- DistributionWorkingGroup::worker_remark(origin, worker_id: WorkerId, msg: Vec<u8>) -> DistributionWorkingGroup::WorkerRemarked(origin,worker_id, message)
## Gateway System
- GatewayWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> GatewayWorkingGroup::LeadRemarked(origin, message)
- GatewayWorkingGroup::worker_remark(origin, worker_id: WorkerId, msg: Vec<u8>) -> GatewayWorkingGroup::WorkerRemarked(origin,worker_id, message)
## Membership System
- MembershipWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> MembershipWorkingGroup::LeadRemarked(origin, message)
- MembershipWorkingGroup::worker_remark(origin, worker_id: WorkerId, msg: Vec<u8>) -> MembershipWorkingGroup::WorkerRemarked(origin,worker_id, message)
- MembershipWorkingGroup::member(origin, worker_id: WorkerId, msg: Vec<u8>) -> MembershipWorkingGroup::MemberRemarked(origin,member_id, message)  
## Operation System
- OperationAlphaWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> OperationAlphaWorkingGroup::LeadRemarked(origin, message)
- OperationAlphaWorkingGroup::worker_remark(origin, worker_id: WorkerId, msg: Vec<u8>) -> OperationAlphaWorkingGroup::WorkerRemarked(origin,worker_id, message)
- OperationBetaWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> OperationBetaWorkingGroup::LeadRemarked(origin, message)
- OperationBetaWorkingGroup::worker_remark(origin, worker_id: WorkerId, msg: Vec<u8>) -> OperationBetaWorkingGroup::WorkerRemarked(origin,worker_id, message)
- OperationGammaWorkingGroup::lead_remark(origin, msg: Vec<u8>) -> OperationGammaWorkingGroup::LeadRemarked(origin, message)
- OperationGammaWorkingGroup::worker_remark(origin, worker_id: WorkerId, msg: Vec<u8>) -> OperationGammaWorkingGroup::WorkerRemarked(origin,worker_id, message)
## Proposal System
- Council::councilor_remark(origin, member_id: MemberId, msg: Vec<u8>) -> Council::CouncilorRemarked(origin, member_id, message)
- Council::member_remark(origin, member_id: MemberId, msg: Vec<u8>) -> Council::MemberRemarked(origin, member_id, message)    
## Council Blog System
- Council::councilor_remark(origin, member_id: MemberId, msg: Vec<u8>) -> Council::CouncilorRemarked(origin, member_id, message)
- Council::member_remark(origin, member_id: MemberId, msg: Vec<u8>) -> Council::MemberRemarked(origin, member_id, message)    
  
I am not 100% sure however that for Operations*, Storage, Distribution, Gateway there's the need for metaprotocol specficiation

**Comment by bedeho** [comment]
1. Keep in mind that all working groups are _instance modules_, hence you would only implement the worker and lead remarks on the one singular working group module, and all working groups would have it. So every single *WorkingGroup you have does not exist, make sure you understand this.
2. Drop the council blog.
3. There is a genuine question as to how much redundancy is needed. For example, a member can use normal remark on membership module to discuss a proposal, or, we could have a dedicated remark on the proposal module - at least for the proposal proposer, since the runtime can provide extra validation of this, but even this is not strictly needed. Same with a separate membership remark on the content directory, say to build video comments. Is it needed? or do we just use normal membership remark? One benefit of adding separate redundant extrinsics is that it perhaps make it easier to write mappings, since they will have more narrow focus. For example membership module remark handler does not need to care about so many different areas at once.

With this I see the following extrinsics (omitting corresponding events for readability):

# Working Group

- `WorkingGroup::lead_remark`
- `WorkingGroup::worker_remark`

# ContentDirectory

- `ContentDirectory::channel_owner_remark`
- `ContentDirectory::channel_collaborator_remark`
- `ContentDirectory::content_curator_group_member_remark`: the only reason to have this is because the runtime can validate that a given worker is actually part of a given on-chain group
- `ContentDirectory::nft_owner_remark`
- `ContentDirectory::member_remark(... , side_payment: Option<Amount, Account>)`: here is can be useful to add sidepayment field, which must go through, and be funded by member controller account. This can be useful for various creative tipping and payment schemes for content that people want to build on top later.

# Storage/Data Directory

- `Storage::storage_bucket_operator_remark`: the only reason to have this is because the runtime can validate that a given worker is actually operating a given on-chain storage bucket.
- `Storage::distribution_bucket_operator_remark`: the only reason to have this is because the runtime can validate that a given worker is actually operating a given on-chain distribution bucket.

# Membership

- `Membership::member_remark`

# Council

- `Council::councilor_remark`

# Proposal

Here I suggest that we don't add a redundant membership remark, because 
1. We want discussion to be able to continue even after a proposal has been executed, and then this extrinsic will not work.
2. We want to accomodate random third party members to participate anyway.

# Election

- `Election::candidate_remark`

# Bounties

- `Bounties::creator_remark`
- `Bounties::oracle_remark`
- `Bounties::entrant_remark`

# Forum 

This pallet will likely be dropped, no on-chain footprint will be required, normal worker (for moderator) and membership extrinsics are sufficient to broadcast.

**Comment by dobertRowneySr** [comment]
Ok, I will add then for 
# Content Directory
This two roles add an extra layer of authentication. I can see probably some forms of coordination also needed between them
- `ContentDirectory::moderator_remark(origin, member_id: MemberId, msg: Vec<u8>)`. This member role is used to moderate posts
- `ContentDirectory::collaborator_remark(origin, member_id: MemberId, msg: Vec<u8>)`. This member role is used to moderate channel assets. 
# Bounty
- `Bounty::contributor_remark(origin, member_id: MemberId, msg: Vec<u8>)` ~~(apparently redundant, as confirmed by Luis)~~

# Election
- ~~`Referendum::voter_remark(origin, msg: Vec<u8>)`~~ probably redundant 

# Proposal
- `Proposal::proposer_remark(origin, proposer_id: MemberId, msg: Vec<u8>)`  I think the main benefit of this is having the runtime to check that a member is actually bound to a proposal.

@bedeho

**Comment by bedeho** [comment]
- Why do we need `ContentDirectory::moderator_remark` when we have the worker remark for the corresponding working group?
- Why is it redundant, not obvious? `Bounty::contributor_remark`?
- Yes this is redundant, because voters are just raw accounts, nothing more, hence normal system_remark is sufficient => `Referendum::voter_remark`.
- Ok sure => `Proposal::proposer_remark`

**Comment by dobertRowneySr** [comment]
> * Why do we need `ContentDirectory::moderator_remark` when we have the worker remark for the corresponding working group?

`ContentDirectory::moderator` is the authorization to moderate comments to videos. This an extra authorization beyond the canonical `origin, member_id` authentication.

>     * Why is it redundant, not obvious? `Bounty::contributor_remark`?

Albeit there this is an extra role which requires runtime authentication, @L3pereira thinks that no relevant interaction should be required between bounty funders. Maybe I misunderstood. @L3pereira feel free to weight in

**Comment by dobertRowneySr** [comment]
> There is a genuine question as to how much redundancy is needed. For example, a member can use normal remark on membership module to discuss a proposal, or, we could have a dedicated remark on the proposal module - at least for the proposal proposer, since the runtime can provide extra validation of this, but even this is not strictly needed. Same with a separate membership remark on the content directory, say to build video comments. Is it needed? or do we just use normal membership remark? One benefit of adding separate redundant extrinsics is that it perhaps make it easier to write mappings, since they will have more narrow focus. For example membership module remark handler does not need to care about so many different areas at once.

I would follow this principle:
> if a member has his `id` associated to some runtime identity that requires extra verification / authentication then there is the need for a separate `*-remark` extrinsic

## Example
In the proposal system we can have a `ProposerId` which is effectively a `MemberId` but it is tied to an `ProposalOf<T>` entity stored on-chain.   
Contrast this (A) in the membership pallet

```rust
pub fn member_remark(origin, member_id: MemberId, msg: Vec<u8>) -> DispatchResult {
    T::Membership::ensure_member_controller_account_origin(origin, member_id)?;
     Self::deposit_event(RawEvent::MemberRemarked(origin, member_id, msg: Vec<u8>);
     Ok(())
}
```
with this (B) in the proposal pallet

```rust
pub fn proposer_remark(origin, proposer_id: MemberId, proposal_id: ProposalId, msg: Vec<u8>) {
    T::Membership::ensure_member_controller_account_origin(origin.clone(), member_id.clone())?;
    let proposal = Self::ensure_proposal_exists(&proposal_id)?;
    ensure!(proposal.proposer_id == proposer_id, Error::<T>::NotAuthor);
    Self::deposit_event(RawEvent::ProposerRemarked(origin, proposer_id, proposal_id, msg);
    Ok(())
}
```
If (A) is used everywhere the Query node cannot effectively verify the validity of `(proposer_id, proposal_id)` pair, so (B) is needed.
This reasoning also carries on with the `(moderator, channel_id)` pair when I require that a `moderator: MemberId` is a designated moderator for the comment sections for channel `channel_id`.
Hope I expressed the idea clearly @bedeho. 
If we respect this we should have 3 layer architecture for the metaprotocol infrastructure:
| Layer | Task | Responsibility of |
|---|----|---|
| 1 | Transaction ordering | consensus algorithm (Substrate runtime) |
| 2 | Role authentication | Joystream Runtime |
| 3 | metaprotocol metadata operation | Joystream Query infra structure + Atlas |

**Comment by bedeho** [comment]
1. I think your framework makes a lot of sense, love the table, crystal clear.
2. I totally forgot about video comment moderators, was thinking of forum moderators, excuse me.
3. The proposer discussion thing is a bit of an edge case, because direct members also will be able to participate, but you may be right that we still could need it for when the discussion mode is closed.

**Comment by ignazio-bovo** [comment]
# Background

If this Metaprotocol framework architecture is desired

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-right" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">Layer</th>
<th scope="col" class="org-left">Task</th>
<th scope="col" class="org-left">Responsibility of</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-right">1</td>
<td class="org-left">Transaction ordering</td>
<td class="org-left">Substrate Runtime Consensus Algorithm</td>
</tr>


<tr>
<td class="org-right">2</td>
<td class="org-left">Role authentication</td>
<td class="org-left">Joystream Runtime</td>
</tr>


<tr>
<td class="org-right">3</td>
<td class="org-left">Metadata processing</td>
<td class="org-left">Query node infra &amp; Atlas</td>
</tr>
</tbody>
</table>

Then the joystream runtime layer should just verify role authentication. Hence the list of `*-remark` extrinsic with
respective **Authentication** routines, **Signature** and **Event** emitted.

1.  Notation

    -   && = logical and operator
    -   || = logical or operator
    -   `element` @ `ModuleInstance::StarageElement(index1, index2, ..)` = element `element` chain state is located in module instance `ModuleInstance` at storage element `StorageElement`
        which can be either a variable or a map with indices `(index1, index2, ...)` specified
    -   == = logical equality operator
    -   `variable` = `Variant(elem1, elem2, ..)` = variable is matched against enum variant `Variant` which migth have optional tuple containing elements `elem1, elem2,...`
    -   `collection.contains(element)`: boolean info on whether `collection` (either a `Vec` or a `BTreeSet`) actually contains `element`


<a id="orgbbd3185"></a>

# Metaprotocol \*-remark extrinsics list


<a id="org36bca5f"></a>

## Working Group - Lead

-   **Signature**: `lead_remark(origin, msg: Vec<u8>)`
-   **Event:** `LeadRemarked(origin, msg)`
-   **Authentication**: `LEAD_AUTH(origin)`


<a id="orgf075c91"></a>

## Working Group - Worker

-   **Signature**: `worker_remark(origin, worker_id: WorkerId,  msg: Vec<u8>)`
-   **Event:** `LeadRemarked(origin, msg)`
-   **Authentication**: `WORKER_AUTH(origin, worker_id)`


<a id="orgb8a2974"></a>

## Content - Channel Owner

-   **Signature**: `channel_owner_remark(origin, owner: ChannelOwner, channel_id: ChannelId, msg: Vec<u8>)`
-   **Event:** `ChannelOwnerRemarked(origin, actor,channel_id,  msg)`
-   **Authentication**: `CHANNEL_OWNER_AUTH(origin, channel_id, owner)`


<a id="orgd6bbb85"></a>

## Content - Channel Collaborator

-   **Signature**: `channel_collaborator_remark(origin, collaborator_id: MemberId, channel_id: ChannelId, msg: Vec<u8>)`
-   **Event:** `ChannelCollaboratorRemarked(origin, collaborator_id, channel_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, collaborator_id)` && `CONTENT_COLLABORATOR(channel_id, collaborator_id)`


<a id="org5befad2"></a>

## Content - Channel Moderator

-   **Signature**: `channel_moderator_remark(origin, moderator_id: MemberId, channel_id: ChannelId, msg: Vec<u8>)`
-   **Event:** `ChannelModeratorRemarked(origin, moderator_id, channel_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, moderator_id)` && `CONTENT_MODERATOR(channel_id, moderator_id)`


<a id="orge883fb3"></a>

## Content - Curator Group

-   **Signature**: `content_curator_group_remark(origin, curator_id: MemberId, curator_group_id: CuratorGroupId, msg: Vec<u8>)`
-   **Event:** `CuratorGroupRemarked(origin, curator_id, channel_id,  msg)`
-   **Authentication**: `CURATOR_GROUP_AUTH(origin, curator_id, curator_group_id)`


<a id="org217e760"></a>

## Content - NFT Owner

-   **Signature**: `nft_owner_remark(origin, owner: NftOwner, video_id: VideoId, msg: Vec<u8>)`
-   **Event:** `NFTOwnerRemarked(origin, collaborator_id, channel_id,  msg)`
-   **Authentication**: `NFT_OWNER_AUTH(video_id, owner)` && ((`owner` = `Member(member_id)` && `MEMBER_AUTH(origin, member_id)`) || (`owner` = `ChannelOwner(owner, channel_id)` && `CHANNEL_OWNER_AUTH(origin, channel_id, owner)`))


<a id="orgadae18b"></a>

## Storage - Operator

-   **Signature**: `storage_operator_remark(origin, worker_id: WorkerId, storage_bucket_id: StorageBucketId, msg: Vec<u8>)`
-   **Event:** `StorageOperatorRemarked(origin, worker_id, storage_bucket_id,  msg)`
-   **Authentication**: `STORAGE_OPERATOR_AUTH(bucket_id, operator_id)` && `WORKER_AUTH(origin, worker_id)`


<a id="org36b538f"></a>

## Distribution - Operator

-   **Signature**: `distribution_operator_remark(origin, worker_id: WorkerId, distribution_bucket_id: DistributionBucketId, msg: Vec<u8>)`
-   **Event:** `DistributionOperatorRemarked(origin, worker_id, distribution_bucket_id,  msg)`
-   **Authentication**: `DISTRIBUTION_OPERATOR_AUTH(bucket_id, operator_id)` && `WORKER_AUTH(origin, worker_id)`


<a id="orgc630f2e"></a>

## Membership - member

-   **Signature**: `member_remark(origin, member_id: MemberId, msg: Vec<u8>)`
-   **Event:** `MemberRemarked(origin, member_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, member_id)`


<a id="orgb2d9449"></a>

## Bounty - Contributor

-   **Signature**: `contributor_remark(origin, contributor_id: MemberId, msg: Vec<u8>)`
-   **Event:** `ContributorRemarked(origin, member_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, contributor_id)` && `BOUNTY_CONTRIBUTOR(bounty_id, contributor_id)`


<a id="org7749d00"></a>

## Bounty - Entrant

-   **Signature**: `entrant_remark(origin, bounty_id: BountyId, entry_id: EntryId, entrant_id: MemberId, msg: Vec<u8>)`
-   **Event:** `EntrantRemarked(origin, member_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, entrant_id)` && `ENTRANT_AUTH(bounty_id, entry_id, entrant_id)`


<a id="orgbad2e1b"></a>

## Bounty - Oracle

-   **Signature**: `oracle_remark(origin, bounty_id: BountyId, oracle_id: MemberId msg: Vec<u8>)`
-   **Event:** `OracleRemarked(origin, member_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, entrant_id)` && `ORACLE_AUTH(bounty_id, entry_id, entrant_id)`


<a id="orgf719396"></a>

## Council - Candidate

-   **Signature**: `candidate_remark(origin, candidate_id: MemberId, msg: Vec<u8>)`
-   **Event:** `CandidateRemarked(origin, candidate_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, candidate_id)` && `CANDIDATE_AUTH(candidate_id)`


<a id="orgb613fc4"></a>

## Council - Councilor

-   **Signature**: `councilor_remark(origin, councilor_id: MemberId, msg: Vec<u8>)`
-   **Event:** `CouncilorRemarked(origin, candidate_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, councilor_id)` && `COUNCILOR_AUTH(councilor_id)`


<a id="org9b5e190"></a>

## Proposal - Proposer

-   **Signature**: `proposer_remark(origin, proposer_id: MemberId, proposal_id: ProposalId, msg: Vec<u8>)`
-   **Event:** `ProposerRemarked(origin, proposer_id,  msg)`
-   **Authentication**: `MEMBER_AUTH(origin, proposer_id)` && `PROPOSER_AUTH(proposal_id, proposer_id)`


<a id="org942b81c"></a>

## Proposal - Councilor

same as Council - Councilor


<a id="orgc474fdd"></a>

# Authentication routines

-   `LEAD_AUTH(origin)`: `origin` signed by `account_id` && `working_group::<I>::WorkerById(working_group<I>::CurrentLead()).role_account_id` `= =account_id`
-   `WORKER_AUTH(origin, worker_id)`: `origin` signed by `account_id` && `worker` at `working_group::<I>::WorkerById(worker_id)` exists && `worker.role_account` `= =account_id`
-   `MEMBER_AUTH(origin, member_id)`: `origin` signed by `account_id` && `member` @ `pallet_membership::MembershipById(member_id)` && `member.controller_account` `= =account_id`
-   `CONTENT_COLLABORATOR(channel_id, member_id)`: `channel` @ `Content::ChannelById(channel_id)` exists && `channel.collaborator_set.contains(member_id)`
-   `CONTENT_MODERATOR(channel_id, member_id)`: `channel` @ `Content::ChannelById(channel_id)` exists && `channel.moderator_set.contains(member_id)`
-   `CURATOR_GROUP_AUTH(origin, curator_id, curator_group_id)`: `WORKER_AUTH(origin, curator_id)` && `curator_group` @ `Content::CuratorGroupById(curator_group)` exists && `group.curators.contains(curator_id)`
-   `CHANNEL_OWNER_AUTH(origin, channel_id, owner)`: `channel` @ `Content::ChannelById(channel_id)` exists && `channel.owner` `= =owner`
-   `NFT_OWNER_AUTH(nft_id, owner)`: `video` @ `Content::VideoById(video_id)` && `video.nft_status` `= =Some(nft_owner)` && `nft_owner` `= =owner`
-   `STORAGE_OPERATOR_AUTH(bucket_id, operator_id)`: `storage bucket` @ `Storage::StorageBucketById(storage_bucket_id)` exists && `storage_bucket.operator_status` `= =Accepted(worker_id)`
-   `DISTRIBUTION_OPERATOR_AUTH(bucket_id, operator_id)`: `distribution bucket` @ `Distribution::DistributionBucketByFamilyIdById(distribution_bucket_family_id, distribution_bucket_id)` exists && `distribution_bucket.operators.contains(worker_id)`
-   `BOUNTY_CONTRIBUTOR(bounty_id, contributor_id)`: `contributor` @ `Bounty::Contributions(bounty_id, contributor_id))` exists
-   `ENTRANT_AUTH(bounty_id, entry_id, entrant_id)`: `entry` @ `Bounty::Entries(bounty_id, entry_id)` exists && `entry.member_id` `= =entrant_id` && `entry.work_submitted` #to<sub>define</sub>
-   `ORACLE_AUTH(bounty_id, oracle_id)`: `bounty` @ `Bounty::Bounties(bounty_id)` exists && `bounty.parameters.oracle` `= =oracle_id`
-   `CANDIDATE_AUTH(candidate_id)`: `candidate` @ `Council::Candidates(candidate_id)` exists && `candidate.cycle_id` `= =Council::AnnouncmentPeriodNr`
-   `COUNCILOR_AUTH(councilor_id)`: `Council::CouncilMembers.contains(councilor_id)`
-   `PROPOSER_AUTH(proposal_id, proposer_id)`: `proposal` @ `Proposal::Proposals(proposal_id)` exists && `proposal.creation_params.proposer_id` `= =proposer_id`
