### ISSUE TITLE
Finalize runtime fees: weight to fee 

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2920]
Set weight to fee function

Relevant location in code base:
- [runtime/src/lib.rs](https://github.com/Joystream/joystream/blob/60c8e6c11020d49b272c105abaa073ee833d7d1e/runtime/src/lib.rs#L346)
- [runtime/src/constants.rs](https://github.com/Joystream/joystream/blob/60c8e6c11020d49b272c105abaa073ee833d7d1e/runtime/src/constants.rs#L58)
- [runtime/src/tests/fee_tests.rs](https://github.com/Joystream/joystream/blob/60c8e6c11020d49b272c105abaa073ee833d7d1e/runtime/src/tests/fee_tests.rs#L7)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202171666786009) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
I added links in the opening comment to the relevant code sections related to fees and weight to fee configuration.

**Comment by bedeho** [comment]
Covered by https://github.com/Joystream/joystream/issues/2914
