### ISSUE TITLE
Unbonding parameters for validators

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#293]
For Rome, unbonding of stake for Validators appears to be set to:

`pub const BondingDuration: staking::EraIndex = 24 * 28;`, [ref](https://github.com/Joystream/joystream/blob/eb6e37043b37ef4e2ae8c18d5c2acaf2b3fd304a/runtime/src/lib.rs#L342)

This mimics Polkadot which has 28 days. (However, they target 600 blocks in a `sessions` (we target 100), and both target 6 `sessions` in an `era`.)

This should equal 403200 blocks, from the end of the current era. I tested a couple of times, and the UI returns ~550000k:
<img width="397" alt="Screen Shot 2020-04-17 at 14 24 04" src="https://user-images.githubusercontent.com/35237943/79574513-8fa12400-80c0-11ea-881d-36088e39cea1.png">

A chain state query returns the correct value (672 eras from now), so it seems correct there.

In any event, I think we should target a more dynamic system, where token holders can respond to incentives and allocate resources more quickly. I propose adjusting this to 24 `eras` ( 24h).

Thoughts @bedeho?

**Comment by mnaamani** [comment]
This is explained in more detail in https://github.com/Joystream/joystream/issues/388
