### ISSUE TITLE
Video metadata and assets immutable when NFT

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2936]
- user metadata on videos cannot be updated
- problem: it is still possible to delete a dataobject on-chain, which would be an asset for the video. Trying to prevent this would require starting to introduce content directory level information about what data objects exist, it quickly will get complicated to manage this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201837747825058) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Resolved in https://github.com/Joystream/joystream/pull/3454
