### ISSUE TITLE
Creator payout data format Requirements

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2943]
WIP: We need a way to represent creator payout data payload which 

* is space efficient (although will not be stored in ledger, but in storage system)
* includes precomputed merkle brances for eache entrant
* allows easy indexing into precomputed proofs to allow creator to only fetch specific proofs by knowing what part of data object to read from.
* allows computation of actual proofs from main raw payload also
* obviosuly => identifies creators by id, not any account!
* includes rationales or other record of explanation for payout, in particular if balance is getting reduced.

# Resources
* **Initial runtime spec:** https://github.com/Joystream/joystream/issues/2365
* **Claiming code:** https://github.com/Joystream/joystream/blob/olympia/runtime-modules/content/src/lib.rs#L1412

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958580458220) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
- fix block height `t` (= time `t`)
- `C` commitment stored on the content module chain state at `t`
- `payouts`  payout set at `t` i.e. all the *cumulative* payout amounts entitled to each channel up to `t`
- `channel`  existing channel that wants to claim some reward
- `hash` cryptograhic hash function (Blake2-256 it is used in runtime if I am not wrong)

Extrinsic of interest reads as:
``` rust
pub fn claim_channel_reward(
            origin,
            actor: ContentActor<T::CuratorGroupId, T::CuratorId, T::MemberId>,
            proof: Vec<ProofElement<T>>,
            item: PullPayment<T>,
        ) -> DispatchResult ;
```
`PullPayment` is a record consisting of:
- `channel id` id for `channel`
- `cumulative_payout_claimed` that channel wants to claim
- `reason` hash commit of some human readable string explaing the rationale

The field in the `Channel<T>` record contains a `cumulative_payout_earned` representing the amount the channel has effectively cashed out up to  `t`, hence at `t` `channel` is entitled to `cashout` amount:
``` rust
// establish cashout amount
cashout = max(item.umulative_payout_claimed - channel.umulative_payout_earned,0);
// update earned amount afterwards
channel.cumulative_payout_earned += cashout;
```
For the channel to do that it is necessary however that the `PullPayment` `p` in question belongs to the `payouts` set. To verify
set membership proof in `O(log N)` time  (with `N` is the number of elements in `payouts` at `t`) the channel claiming the amount must provide a list `Vec<ProofElement<T>>` consisting of the following data struct:
``` rust
struct ProofElement { hash_value: Hash, side: Side}

enum Side { Right, Left }
```
Proof verification is carried as follows:
1. `h = hash(item)` hash of the Pull payment element is computed
2. loop for every element `el` in the list above updating `h` to 
    - `h = hash([el, h)]` if `el.side` is `Left`
    - `h = hash([h, el])` if `el.side` is `Right`
3. After the loop we check for equality `h == C` to ensure the resulting hash is effectively the commit value stored in the content chain state

@zeeshanakram3 

PS: In `runtime-modules/content/src/tests/merkle.rs` there is also the code how to construct a proof compliant with the required specs
