### ISSUE TITLE
Bounty oracle switch

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2947]
An oracle may not be able to complete the work on managing a bounty, for any reason, and thus transfer role to someone else. The assumption is that this happens through some trust relationship, just as the initial choice of oracle, so no reason for double opt-in. This is only possible before judgement period is over.

**This only applies bounties where oracle is currently member, not council oracles, or coming working group oracles, however member oracles can change oracle to any other type:** https://github.com/Joystream/joystream/issues/2979

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703510692257) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
This should also be possible to do through a proposal from the council, in case an oracle goes truly MiA, however, the bounty creator gets to set a flag during bounty creation which can block this sort of switch.

**Comment by L3pereira** [comment]
@shamil-gadelshin when I add a new dispatch function in bounties (switch_oracle), I also need to add that function in runtime/src/weights/bounty.rs.
 
My question is how did you calculate these weights, so I can apply to my function
for eg: 
```rust
   fn create_bounty_by_council(i: u32, j: u32) -> Weight {
        (0 as Weight)
            .saturating_add((194_000 as Weight).saturating_mul(i as Weight))
            .saturating_add((28_742_000 as Weight).saturating_mul(j as Weight))
            .saturating_add(DbWeight::get().reads(3 as Weight))
            .saturating_add(DbWeight::get().writes(4 as Weight))
   }
```

**Comment by shamil-gadelshin** [comment]
Try using the `./scripts/generate_weights.sh`.

**Comment by L3pereira** [comment]
@shamil-gadelshin when I create a bounty with `origin: RawOrigin::Root` and  `creator: BountyActor::Council`,
how this membership is created, I can't find it in the unit tests?
What does `RawOrigin::Root` really mean? 
By inspecting the code I found an ensure_root validation, is `RawOrigin::Root` associated with an `account_id`? 
Where is this account_id set?
And the BountyActor::Council, what is his account_id and member_id?
As a member of the council, I must be registered as a `CouncilMember<AccountId, MemberId, Balance, BlockNumber>`, so I must have a membership and an account.
For example in the bounty benchmark tests, you buy membership and you associate the `membership_id` with the `controller_account_id`, that makes sense.
Could you clarify better these relationships, please

**Comment by shamil-gadelshin** [comment]
Start with these links:
- https://docs.rs/frame-system/2.0.0/frame_system/enum.RawOrigin.html- 
- https://github.com/Joystream/joystream/blob/5920eaeedf19aaf868970657c1536b17f9a8eeb3/runtime-modules/common/src/membership.rs#L46
- https://github.com/Joystream/joystream/blob/5920eaeedf19aaf868970657c1536b17f9a8eeb3/runtime-modules/common/src/council.rs#L13
- https://github.com/Joystream/joystream/blob/5920eaeedf19aaf868970657c1536b17f9a8eeb3/runtime-modules/bounty/src/lib.rs#L120

Please, let me know if you have more questions and we could have a call.

**Comment by L3pereira** [comment]
I had looked at the code in those links before, So let's see if I understand, 
origin: RawOrigin::Root means "The system itself ordained this dispatch to happen" 
So if I call a dispatch function 1, for eg: inside another dispatch function 2, I can use Root because the call is made by the system
and I can call ensure_root to validate
```rust
    fn dispatch_function_1(origin: T::Origin) -> DispatchResult {
        ensure_root(origin)?;
        Ok(())
    }

    fn dispatch_function_2(origin: T::Origin, member_id: T::MemberId) -> DispatchResult {
        EnsureChecks::<T>::ensure_user_membership(origin, &member_id)?;
        //The caller in case this case is the system itself
        dispatch_function_1(RawOrigin::Root, 10)?;
        Ok(())
    }

   dispatch_function_2(RawOrigin::Signed(account_id), 10)?;

```
But that doesn't explain how a Council can be root since you can't extract any acount_id.

```rust
impl CreateBountyFixture {
    pub fn default() -> Self {
        Self {
            origin: RawOrigin::Root,
            creator: BountyActor::Council,
    ...
        }
    }
}
```
