### ISSUE TITLE
Joystream.js library

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#295]
We are writing an increasing number of javascript (typescript) codebases that interact with the chain:
- Benchmarking tools
- Pioneer
- Storage node
- Query node
- Testing infrastructure tool
- CLI
- Atlas

More is coming, and we are seeing that code+tests+docs+examples are being duplicated. It may therefore be time to consolidate this into a unified library. Some of the code is not Joystream specific, but rather involves various workarounds due the complexities of interacting with Substrate. In increasing amount of code will however also be Joystream specific.

Here is an initial list of Joystream specific code that can be consolidated.

- Workflows across node types: e.g. uploading/downloading involves doing stuff with both storage system and blockchain
- Includes all Polkadot.js types.
- Client for using query node
- ORM for working with content directory in type safe way (currently some beginning of this is in vs.js)

**Please add your own suggestions below as they occur.**

**Comment by bedeho** [comment]
Note: There is a lot of js code due to  with the lack of proper query infrastructure, and its not clear whether such code is appropriate for this library. Time will tell.

**Comment by traumschule** [comment]
FTR https://git.joystreamstats.live/Operations/joystream-lib
