### ISSUE TITLE
Current Problem with storage v2

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#2950]
# Collaborators OR channel owner accounts exposed for storage operations
During the most recent work on giza content/storage integration there is a subtle issue with the collaborator role:
There are basically 4 storage related operations to be performed from the content directory:
- create dynamic bag for a channel (with assets): with a deletion prize that is taken from the channel creator (i.e. owner):
`dynamic_bag_total_balance= bag_deletion_prize + objecs_upload_fee(s)`. with `bag_deletion_prize >= 0` and `objects_total_size_fee > 0`.
- upload assets: which can be performed either by collaborators and channel owner, in any of the cases we have that the  `objects_total_size_fee > 0` is taken from the signer account in any of the two context (channel owner *or* collaborator)
- remove assets: which works analogously as upload asset and the size fee proportional to the objects removed is assigned to the sender account (channel owner *or* collaborator)
- delete dynamic bag for the channel: (which happens when a channel is deleted for example). This method remove all the assets & the dynamic bag for the channel with a prize of `dynamic_bag_total_balance = objects_total_size_fee + bag_deletion_prize` awarded to the channel owner.

This can happen:
a. when a channel owner deletes his channel and so a non-empty bag he gets all the `total_bag_prize` (this is not nice for the collaborators viewpoint which put their fees in order to upload assets for the channel). A similar scenario can happen when a collaborators removes assets from the channel, this allows him to withdraw funds from the bag treasury account (indirectly stealing funds from other collaborators for example)
b. we allow the collaborator to upload assets using the channel owner account as a source of fee. But this exposes the owner account to a possibly arbitrary amount of fees withdrawal.

As we already discussed in the RC chat option b. seems to be the less dangerous so I initially kept a. However during the channel collaborators PR review @bedeho also asked why option a. wasn't feasible. I didnt' realize these implications.

## Context
I need to delete the dynamic bag for the channel upon channel deletion, clearly. Current implementation of `delete_dynamic_bag` and his guard method `can_delete_dynamic_bag` throw if the bag is non-empty. Hence I need to empty the bag first. The prize for object deletion (objects_total_size_fee) as mentioned goes to the channel owner together with `bag_deletion_prize` 

# Storage design
Buckets designated for storing a dynamic bag may have not enough resources in order not to store all assets for a bag hence content module must somehow deal with this problem. Two approaches:
a. channel creation creates and eventually deletes a bag in case uploading fails due to bucket resources exhaustion. The major drawback with this was that this series of events would have been emitted: `DynamicBagCreated(...)` -> upload assets fails -> `DynamicBagDeleted(...)` -> content modules throws error in response.
b. Add method for checking if a bag can be created passing `objects total size` as constraint. This forces first to check that the upload parameters are valid at least twice (both in the `can_create_dynamic_bag_with_object_constraints` and in the 
`can_upload_data_objects` methods. 
`can_*` guard before bag creation checks if a *random* (I don't understand yet if bucket picking is actually random now or it will be random in subsequent releases) bucket with sufficient capacity can be used. A successive call to the picking algorithm during actual bag creating may find that the random bucket (at this round) selected is not large enough.To sidestep the above problem however I implemented all the checks for uploading data inside `can_create_dynamic_bag_with_objects_constraints` which also returns the (distribution, storage) bucket pair in order to be used for subsequent object storing, since the `*_with_objects_constraints` method are meant to be used by the content module.

I think that the storage module should be slightly redesigned (not entirely of course) in order to accomodate the new demands from the content side.

**Comment by dobertRowneySr** [comment]
There might be some imprecisions due to my still not complete understanding of the content pallet

**Comment by bedeho** [comment]
I had a hard time parsing what was being said here, is there a problem? if so what is it exactly?

What is the link between the two sections `Storage design` and `Collaborators OR channel owner accounts exposed for storage operations`?

The most tangible thing I could extract is that you are concerned about a different actor capturing the funds in the deletion prize from the one who contributed them, is this the problem? If so, I don't think this is a problem. These quantities will be very small, they are there to discourage storage bloat by discouraging an attack and incentivizing cleanup even among non-hostile users, nothing more. Even if these quantities were substantial, the  channel owner and collaborators obviously have a high trust arrangement, by assumption, hence they can settle up whatever they would need outside of these operations anyway, but anyway, it's a non-issue.

**Comment by dobertRowneySr** [comment]
ok thanks for the reply.
the problem(s) are two:
- different actor capturing the funds in the deletion prize from the one who contributed them -> you already replied
- storage module interface might need some small re-design (but this is best for another issue)
