### ISSUE TITLE
Change effect of abstention

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2953]
# Background
There is considerable dissatisfaction with the fact that abstentions count towards quorum, but do not count towards the threshold, hence being effectively counted as a reject in terms of effect. See here

https://github.com/Joystream/joystream/issues/2589

There is even a outside PR to fix this, but I am not sure if it is the right fix

https://github.com/Joystream/joystream/pull/2952

# Proposal
Abstention is supposed to be there as a way to allow a councilor to be able to signal awareness of a proposal, unlike if they just don't vote, but not being able or willing to take a position on the question. To me, it seems like either this should be treated as today, which means it counts towards quorum, and it counts as a reject, or, it just does not count towards the quorum at all, and thus also not threshold. Since people are unhappy about the former, seems the latter would be better.

I don't believe this change has any effect on anything outside the runtime, be it CLI, query node, Pioneer, etc. Some documentation needs to be updated though.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710200291876) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
Wouldn't `lowering the threshold for troubling proposal types` be a safer and easier option for dealing with the problem? Those values are just runtime constants that could be changed back and forth during experiments (runtime upgrade is required though).

As an alternative, some changes variants could lead to a single `Approve` that will decide the outcome of a major proposal. Thanks @singulart for highlighting it in the [PR test](https://github.com/singulart/joystream/blob/169ae70d097a388db2c354346dbac68d2597d021/runtime-modules/proposals/engine/src/types/mod.rs#L589). Do we want this behavior?

**Comment by bedeho** [comment]
> Wouldn't lowering the threshold for troubling proposal types be a safer and easier option for dealing with the problem?

I don't think this has anything to do with some proposal types being problematic, so I am not sure exactly what your understanding of the problem is.

> As an alternative, some changes variants could lead to a single Approve that will decide the outcome of a major proposal.  

This would not be the case if we did as I suggested above 

> or, it just does not count towards the quorum at all, and thus also not threshold

**Comment by shamil-gadelshin** [comment]
I referred to such quotes from the original issue: `voter participation requirements up to 93.75%` . We could change the required voter participation percent by changing the threshold value.

Let's introduce an example:
Council size = 20
Approval quorum = 51%
Approval threshold = 51%

Voting results:
- Abstain = 19
- Approve = 1

Current algorithm:
Quorum value= 20/20 = 100%
Approval threshold = 1/20 < 51%
Verdict = rejected

Proposed algorithm (don't count abstains in quorum and threshold):
Quorum value = 1/1 = 100%
Approval threshold = 1/1 = 100%
Verdict = approved

Please, correct my calculations.

**Comment by bedeho** [comment]
> Proposed algorithm (don't count abstains in quorum and threshold):

This was wrong, I here meant

Quorum value = 1/(1 + 19) = 5% < 51% 
Verdict = rejected

**Comment by shamil-gadelshin** [comment]
> Quorum value = 1/(1 + 19) = 5% < 51%

I assume that the threshold value is still `1/1 = 100%` even if we don't reach the quorum in the given example.

**Comment by shamil-gadelshin** [comment]
Fixed.
