### ISSUE TITLE
idea: App tokens

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2976]
# Background
Gateways will generate revenue from revenue that creators they onboard generate, see here

https://github.com/Joystream/joystream/issues/2913

# Proposal
Allow apps to issue their own 

This would require the following on the runtime

* actually introducing a app module, which has these social tokens
* introducing https://github.com/Joystream/joystream/issues/2913, where apps are a new kind of onboarding actor.

I think this only really would make sense after creator social tokens have been introduced, as it would be very similar.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703601262962) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
I have some interesting ideas for this that could make it quite a bit more valuable of a prospect (most likely post-mainnet of course). But I want to understand a lot more of how Gateway tokens would `currently` have value.

* Let's say a user joins via a gateway and gets some tokens from that gateway, are they getting the gateway's token or Joystream's token or both?
* If a Gateway is incentivized by generating revenue from creators they onboard, how does this exactly work when it comes to the Gateway's token? I have read the linked issue, but what I am really trying to understand is why one Gateway's token would have more or less value than another Gateway's token? Who is incentivized to own the Gateway token?
* What power does holding a Gateway token give?

**Comment by bedeho** [comment]
Already here : https://github.com/Joystream/joystream/issues/4158
