### ISSUE TITLE
Sending funds to a working group budget

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2977]
It may be needed to send funds from an arbitrary member account to the budget of a working group, for example to refund something. The result should be that the funds are burned, and the value is credited to the relevant working group. Should include metadata field with rationale.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202171961969388) by [Unito](https://www.unito.io)

**Comment by singulart** [comment]
A useful feature! Can protect from mistakes like https://dao.joystream.org/#/proposals/preview/81

**Comment by bedeho** [comment]
Done in https://github.com/Joystream/joystream/pull/3068
