### ISSUE TITLE
Working groups as bounty actors

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2979]
Allow any working group to 

# Create a bounty funded out of its own budget
* The lead can set budget for how much a given worker can fund bounties with, which is depleted whenever the worker creates a bounty, and is only replenished if the lead raises the budget again. 
* All workers, except lead, start with implicit 0 budget, lead has no bounty budget per say, and is only constrained by group budget.
* Lead can also reduce budget of any worker at any time.

This new state and extrinsics around budgets should be baked into working group module. Bounty creation extrinsic in bounty module should be changed to accomodate new actor type for creation and being oracle (next). Refund logic in bounty module also needs to work with wg budgets, but refunds _do not_ replenish a possible bounty creator workers budget.

# Be the oracle of a bounty.
* a working group is a new kind of viable oracle, and any bounty creator can select any working group as the oracle.
* beyond the working group, specific workers in the working group can be set as the oracle, in which case only those workers and the lead can act as oracles, otherwise _everyone_ in that group can act as oracles.
* the lead can update this set of workers at any time, noone else in the group can.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703601671976) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
This brings to mind whether or not discretionary spending should be canned if this functionality is enabled?

Although I can think of possible scenarios where discretionary spending would still make sense (like reimbursing unexpected server costs or something of that nature)

**Comment by bedeho** [comment]
I see tons of example where a bounty does not make sense, random example: Builder lead needs to pay server or SaaS subscription of some kind. Would be totally cumbersome and artificial to try to turn that into a bounty.

**Comment by L3pereira** [comment]
Does a worker have the capability of not only create a bounty, but also funding it?

**Comment by L3pereira** [comment]
What is specifically a working group, e.g.: A council as a whole is the root,
a working group has workers, one of them is the leader (hired by council), is there a specific origin for a working group as a whole?

**Comment by bedeho** [comment]
> What is specifically a working group, e.g.: A council as a whole is the root,
a working group has workers, one of them is the leader (hired by council), is there a specific origin for a working group as a whole?

https://joystream.gitbook.io/joystream-handbook/governance/working-groups

**Comment by bedeho** [comment]
After reviewing this, I think this actually seems like quite deep changes to do at this time, so I suggest we actually pause work on this for now, hopfully you have not spent too much time on it already?

**Comment by L3pereira** [comment]
I already read the doc, but I didn't found anything, I suppose (at least by the code) there is no working group entity, is only workers and lead worker.

I have spent some time and I already start changing the BountyActor, it changes some files in other modules, that depend on work-group module.

**Comment by bedeho** [comment]
This is considered out of scope without more information.
