### ISSUE TITLE
Giza Unit testing plan

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#2983]
# Background
Extra unit tests are required due to recent changes to both content.
The aim of this task PR is two fold: 
- test changes required by the [recent storage integration fix](https://github.com/Joystream/joystream/pull/2907)
- refactor (some) of the content module tests. [Full refactoring is scheduled for the Olympia release anyways](https://github.com/Joystream/joystream/issues/2901)
### Content module
`{u(nsuccessful), s(uccessful)}`**.**
`{c(hannel),v(ideo)}`**.**
`{c(reation),u(pdate),d(eletion)}`**.**
 so for example
- u.c.c = unsuccessful channel creation
- s.v.d = successful video deletion 
## Storage module
`{u(nsuccessful), s(uccessful)}`**.**
`{b(ag)}`**.**
`{c(reation),d(eletion)}`**.**
and so on..
# Content module unit testing
## Create channel
  - [X] u.c.c. w/ Lead context
  - [X] u.c.c. w/ Collaborator context
  - [X] s.c.c. w/ Member context
  - [X] s.c.c. w/ Curator context
  - [X] u.c.c. w/ uncorresponding member id and origin
  - [X] u.c.c. w/ uncorresponding curator id and origin
  - [X] s.c.c. w/ storage upload and member context
  - [X] s.c.c. w/ storage upload and curator context
  - [X] u.c.c. w/ invalid expected data size fee
  - [X] u.c.c. w/ not enough balance
  - [X] u.c.c. w/ with no bucket available due to object size
  - [X] u.c.c. w/ with no bucket available due to object number
  - [X] u.c.c. w/ with assets exceeding max object size voucher limits
  - [X] u.c.c. w/ with assets exceeding max object number voucher limits
  - [X] s.c.c. w/ collaborator set
  - [X] u.c.c. w/ invalid set
  - [X] s.c.c. w/ reward account
 ## Update channel
  - [X] u.c.u. w/ uncorresponding member id and origin
  - [X] s.c.u. w/ uncorresponding collaborator member id and origin
  - [X] u.c.u. w/ uncorresponding curator id and origin
  - [X] s.c.u. w/ assets uploaded by collaborator
  - [X] s.c.u. w/ assets removal by collaborator
  - [X] s.c.u. w/ assets uploaded by Lead
  - [X] s.c.u. w/ assets removal by Lead
  - [X] s.c.u. w/ assets uploaded by member
  - [X] s.c.u. w/ assets removal by member
  - [X] s.c.u. w/ assets uploaded by curator
  - [X] s.c.u. w/ assets removal by curator
  - [X] u.c.u. w/ assets uploaded by non authorized collaborator
  - [X] u.c.u. w/ assets removed by non authorized collaborator
  - [X] u.c.u. w/ assets uploaded by non authorized member
  - [X] u.c.u. w/ assets uploaded by non authorized curator
  - [X] u.c.u. w/ assets removed by non authorized member
  - [X] u.c.u. w/ assets removed by non authorized curator
  - [X] u.c.u. w/ assets uploaded by Lead
  - [X] u.c.u. w/ assets removed by Lead
  - [X] s.c.u. w/ collaborator set updated by member owner
  - [X] u.c.u. w/ collaborator set updated by non authorized member
  - [X] s.c.u. w/ collaborator set updated by curator owner
  - [X] u.c.u. w/ collaborator set updated by non authorized curator
  - [X] u.c.u. w/ collaborator set updated by collaborator member
  - [X] u.c.u. w/ collaborator set updated by Lead and member owner
  - [X] s.c.u. w/ collaborator set updated by Lead and curator owner
  - [X] s.c.u. w/ reward account updated by member owner
  - [X] s.c.u. w/ reward account updated by curator owner
  - [X] u.c.u. w/ reward account updated by unauthorized member
  - [X] u.c.u. w/ reward account updated by unauthorized curator
  - [X] u.c.u. w/ reward account updated by collaborator member
  - [X] u.c.u. w/ reward account updated by Lead and member owner
  - [X] u.c.u. w/ reward account updated by Lead and curator owner
  - [X] u.c.u. w/ invalid data objects to remove
  - [X] u.c.u. w/ invalid expected data size fee
  - [X] u.c.u. w/ not enough balance
  - [X] u.c.u. w/ with no bucket available due to object size
  - [X] u.c.u. w/ with no bucket available due to object number
  - [X] u.c.u. w/ with assets exceeding data limits
  - [X] u.c.u. w/ invalid collaborator set
  - [X] u.c.u. w/ invalid channel id
## Delete channel 
  - [X] u.c.d. w/ Lead context member owner
  - [X] s.c.d. w/ Lead context curator owner
  - [X] u.c.d. w/ Collaborator context
  - [X] s.c.d. w/ Member context
  - [X] s.c.d. w/ Curator context
  - [X] u.c.d. w/ uncorresponding member id and origin
  - [X] u.c.d. w/ uncorresponding curator id and origin
  - [X] u.c.d. w/ unauthorized member
  - [X] u.c.d. w/ unauthorized curator
  - [X] u.c.d. w/ invalid channel id
  - [X] u.c.d. w/ uncorresponding num objects to delete
## Create video
  - [X] s.v.c. w/ Lead context w/ assets
- [X] s.v.c. w/ Collaborator context w/ assets
- [X] s.v.c. w/ Member context w/ assets
- [X] s.v.c. w/ Curator context w/ assets
- [X] u.v.c. w/ with lead auth failure (uncorresponding id and origin)
- [X] u.v.c. w/ with collaborator auth failure (uncorresponding id and origin)
- [X] u.v.c. w/ with member auth failure (uncorresponding id and origin)
- [X] u.v.c. w/ with curator auth failure (uncorresponding id and origin)
- [X] u.v.c. w/ with valid but unauth member 
- [X] u.v.c. w/ with valid but unauth curator
- [X] u.v.c. w/ with valid but unauth collaborator
- [X] u.v.c. w/ lead but member owned channel
- [X] u.v.c. w/ invalid channel id
- [X] u.v.c. w/ invalid expected data size fee
- [X] u.v.c. w/ not enough balance
- [X] u.v.c. w/ with no bucket available due to object size
- [X] u.v.c. w/ with no bucket available due to object number
- [X] u.v.c. w/ with assets exceeding max object size voucher limits
## Update video
- [X] s.v.u. w/ Lead context w/ assets upload
- [X] s.v.u. w/ Collaborator context w/ assets upload
- [X] s.v.u. w/ Member context w/ assets upload
- [X] s.v.u. w/ Curator context w/ assets upload 
- [X] s.v.u. w/ Lead context w/ assets removal
- [X] s.v.u. w/ Collaborator context w/ assets removal
- [X] s.v.u. w/ Member context w/ assets removal
- [X] s.v.u. w/ Curator context w/ assets removal 
- [X] u.v.u. w/ with lead auth failure (uncorresponding id and origin)
- [X] u.v.u. w/ with collaborator auth failure (uncorresponding id and origin)
- [X] u.v.u. w/ with member auth failure (uncorresponding id and origin)
- [X] u.v.u. w/ with curator auth failure (uncorresponding id and origin)
- [X] u.v.u. w/ with valid but unauth member 
- [X] u.v.u. w/ with valid but unauth curator
- [X] u.v.u. w/ with valid but unauth collaborator
- [X] u.v.u. w/ lead but member owned channel
- [X] u.v.u. w/ invalid expected data size fee
- [X] u.v.u. w/ not enough balance
- [X] u.v.u. w/ with no bucket available due to object size
- [X] u.v.u. w/ with no bucket available due to object number
- [X] u.v.u. w/ with assets exceeding max data object size limits
- [X] u.v.u. w/ with invalid video id
- [X] u.v.u. w/ with invalid object ids
## Delete video 
- [X] s.v.u. w/ Member context w/ assets removal
- [X] s.v.u. w/ Curator context w/ assets removal
- [X] u.v.u. w/ Lead context w/ member owned channel
- [X] s.v.u. w/ Lead context w/ curator owned channel
- [X] u.v.u. w/ Collaborator context
- [X] u.v.u. w/ with member auth failure (uncorresponding id and origin)
- [X] u.v.u. w/ with curator auth failure (uncorresponding id and origin)
- [X] u.v.u. w/ with lead auth failure
- [X] u.v.u. w/ with valid but unauth member
- [X] u.v.u. w/ with valid but unauth curator
- [X] u.v.u. w/ with invalid video id
- [X] u.v.u. w/ with invalid object ids
# Storage module unit testing
## create dynamic bag with object constraints
- [X] u.b.c. w/ existing bag id
- [X] u.b.c. w/ insufficient balance for bag prize and total upload fee
- [X] u.b.c. w/ different accounts for deletion prize and params
- [X] u.b.c. w/ different dynamic bag id and params bag id specified
- [X] u.b.c. w/ zero object size
- [X] u.b.c. w/ size exceeding max data object size
- [X] u.b.c. w/ insufficient bucket size availability
- [X] u.b.c. w/ insufficient bucket objects num availability
- [X] u.b.c. w/ no bucket accepting bags
- [X] u.b.c. w/ empty ipfs id
- [X] u.b.c. w/ empty objects list
- [X] u.b.c. w/ ipfs id blacklisted
- [X] u.b.c. w/ invalid expected data size fee
- [X] u.b.c. w/ global upload block
- [X] s.b.c. w/ no deletion prize but with objects upload
- [X] s.b.c. w/ with full specification
# Issues found
([X] = fixed, [ ] = not fixed yet)
## Content
- [X] on update channel assets permission there wasn't member authentication for collaboator 
## Storage
- [X] on `verify_create_dynamic_bag_parameters` deletion prize account was used to as account for both accounting for both objects and bag deletion prize. This gave a problem when `deletion_prize == None` but `upload_params != None` and some balance was required.
- [X] Error was not produced when `upload_parametrs.bag_id` and `dynamic_bag_id` weren't the same on `verify_create_dynamic_bag_parameters`

**Comment by bedeho** [comment]
Looks great, really comprehensive!
