### ISSUE TITLE
Olympia: Post-merge adjustments (types, cli, query-node, metadata-protobuf, docker setup etc.)

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3004]
Follow-up work after conflict resolution in https://github.com/Joystream/joystream/issues/3002, this will include making any more complex updates (if needed) and making sure everything works as exprected after the runtime is ready:

* `@joystream/types` - auto-generating the files, double-check against runtime, testing (through CLI / query-node etc.)
* `query-node` - possible adjustments related to runtime changes introduced in NFT / `new_content_features`, making sure it fully builds / starts, some basic testing (probably together with the CLI)
* `cli` - possible adjustments related to runtime changes introduced in NFT / `new_content_features`, testing the commands (ie. running`content-test` script)
* docker setup - testing the services and most of the bash scripts work as intended (the ones not related to integration tests, as updating them will be a more complex, separate task)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710242915526) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Why is this all combined into one issue, seems like a gigantic task with many subcomponents? Are there other issue that cover the detailed items within this?

**Comment by Lezek123** [comment]
> Why is this all combined into one issue, seems like a gigantic task with many subcomponents? Are there other issue that cover the detailed items within this?

Initially I wanted to create separate issues, but from my experience it's easier to update and test everything together. The scope of the changes is not that huge, as this is basically just about making sure everything works as expected after the merge.

For some of the packages (ie. `@joystream/types`, `@joystream/metadata-protobuf` and even most part of the `query-node`) this is already the case, because those were upadated _during_ the merge (at the conflicts resolutions stage + a few following commits).

For `query-node` it's hard to test any mappings unless there is some set of the working integration tests and a working CLI.

The CLI also partiallly relies on a working query-node.

Bash scripts, docker setup adjustments etc. are mostly related to things like building / starting the query-node, running the integration tests, starting the full local infrastructure etc., so they are also quite essential for doing any reasonable testing.

All of those updates will be covered in https://github.com/Joystream/joystream/pull/3131

The remaining integration tests updates will be done as part of https://github.com/Joystream/joystream/issues/3015

**Comment by Lezek123** [comment]
Merged (https://github.com/Joystream/joystream/pull/3131)
