### ISSUE TITLE
Key Mainnet content transfer questions

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3012]
* These are questions relating to mainnet launch, they do not require an immediate answer and are asking which parts (if any) of the testnet will be migrated to the mainnet launch. This means that whenever mainnet is, what can we expect/not to see on the genesis block (or added in somehow shortly afterwards)
* My interest in these is listed in order of priority and because of my interests in community building, cohesion and trying to work towards this in antiicipation of mainnet--it is a deliberately short list because of this.

# List
1. Forums (categories, threads, posts)
1. Memberships (kind of shared with 1.)
1. Channels / vNFTs

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703461582603) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
> Forums (categories, threads, posts)

Almost certainly everything post Olympia.

> Memberships (kind of shared with 1.)

100%, even from pre Olympia, we never kill memberships.

> Channels / vNFTs

Almost certainly everything from after Sumer.
