### ISSUE TITLE
Olympia Balances

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3014]
Olympia will almost certainly be a fresh chain, and the question has arisen of what to do with balances! It could be a nice time to reset balances of everyone, input?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710119731474) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
I think maybe an easier way of dealing with this is introducing a cap and telling users if they do not cash out enough tokens to fall below this cap by some date, their balances will be set at the cap.
There are probably very large considerations with this though that I'm not aware of.

**Comment by freakstatic** [comment]
> I think maybe an easier way of dealing with this is introducing a cap and telling users if they do not cash out enough tokens to fall below this cap by some date, their balances will be set at the cap. There are probably very large considerations with this though that I'm not aware of.

Yeah that sounds a good idea so that users can keep enough tokens to keep the testnet running

**Comment by freakstatic** [comment]
> Olympia will almost certainly be a fresh chain, and the question has arisen of what to do with balances! It could be a nice time to reset balances of everyone, input?

I think it's a good idea to reset the balances so it's easier for new users to compete with previous ones in the available roles but this wasn't really be a real problem for some time now... The validators were the ones that had some competition and since they don't get FM points anymore the roles haven't been very crowded recently

**Comment by bedeho** [comment]
> I think maybe an easier way of dealing with this is introducing a cap and telling users if they do not cash out enough tokens to fall below this cap by some date, their balances will be set at the cap.
There are probably very large considerations with this though that I'm not aware of.

I really like this idea.
