### ISSUE TITLE
Olympia conflicts resolution plan

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3021]
_**Updated 20.01.2022 11:00 AM CET**_

* Base branch: https://github.com/ignazio-bovo/joystream/tree/giza_feature_NewContentFeaturesAndNFT (commit: https://github.com/ignazio-bovo/joystream/commit/c67c5e15f495dc20ffa8dd85bd2fa48696d3c758)
* Olympia branch: https://github.com/Joystream/joystream/tree/olympia (commit: https://github.com/Joystream/joystream/commit/2d970a177ee2acbc1063eede7116b87c8994a659)

Below is the list of current conflicts between `giza_feature_NewContentFeaturesAndNFT` and `olympia`

I used `I/S` to mark conflicts to be resolved by Ignazio/Shamil and `L` to mark conflicts to be resolved by me.
The way I divided the work was by going through the conflicts and determining which ones I should be able to resolve myself. All other conflicts were assigned to `I/S`. I'm assuming 2 people should be capable of to resolving all of the conflicts. There could obviously be additional collaboration "outside" of the process described here, but adding more collaboratos that need to create their own respective branches would probably only complicate the process.

```
	L   both modified:   .dockerignore
	L   both modified:   .github/workflows/integration-tests.yml
	L   both modified:   .github/workflows/joystream-cli.yml
	I/S both modified:   .github/workflows/joystream-node-benchmarks.yml
	L   deleted by us:   .github/workflows/run-network-tests.yml
	I/S both modified:   Cargo.lock
	I/S both modified:   Cargo.toml
	L   both modified:   README.md
	L   both modified:   apps.Dockerfile
	L   deleted by them: build-docker-images.sh
	L   both modified:   build-packages.sh
	L   both added:      chain-metadata.json
	L   both modified:   cli/README.md
	L   both modified:   cli/package.json
	L   both modified:   cli/src/Api.ts
	L   both modified:   cli/src/Types.ts
	L   both modified:   cli/src/base/AccountsCommandBase.ts
	L   both modified:   cli/src/base/ApiCommandBase.ts
	L   both modified:   cli/src/base/ContentDirectoryCommandBase.ts
	L   both modified:   cli/src/base/StateAwareCommandBase.ts
	L   both modified:   cli/src/base/UploadCommandBase.ts
	L   both modified:   cli/src/base/WorkingGroupsCommandBase.ts
	L   both modified:   cli/src/commands/account/create.ts
	L   both modified:   cli/src/commands/account/export.ts
	L   both modified:   cli/src/commands/account/forget.ts
	L   both modified:   cli/src/commands/account/import.ts
	L   both added:      cli/src/commands/account/info.ts
	L   both added:      cli/src/commands/account/list.ts
	L   both modified:   cli/src/commands/account/transferTokens.ts
	L   both added:      cli/src/commands/api/getQueryNodeEndpoint.ts
	L   both modified:   cli/src/commands/api/inspect.ts
	L   both added:      cli/src/commands/api/setQueryNodeEndpoint.ts
	L   both modified:   cli/src/commands/content/addCuratorToGroup.ts
	L   both modified:   cli/src/commands/content/createChannel.ts
	L   both modified:   cli/src/commands/content/createCuratorGroup.ts
	L   both modified:   cli/src/commands/content/createVideo.ts
	L   both modified:   cli/src/commands/content/removeCuratorFromGroup.ts
	L   both modified:   cli/src/commands/content/reuploadAssets.ts
	L   both modified:   cli/src/commands/content/setCuratorGroupStatus.ts
	L   both modified:   cli/src/commands/content/updateChannel.ts
	L   both modified:   cli/src/commands/content/updateChannelCategory.ts
	L   both modified:   cli/src/commands/content/updateVideo.ts
	L   both modified:   cli/src/commands/content/updateVideoCategory.ts
	L   deleted by us:   cli/src/commands/council/info.ts
	L   both modified:   cli/src/commands/working-groups/createOpening.ts
	L   both modified:   cli/src/commands/working-groups/decreaseWorkerStake.ts
	L   both modified:   cli/src/commands/working-groups/evictWorker.ts
	L   both modified:   cli/src/commands/working-groups/fillOpening.ts
	L   both modified:   cli/src/commands/working-groups/increaseStake.ts
	L   both modified:   cli/src/commands/working-groups/leaveRole.ts
	L   both modified:   cli/src/commands/working-groups/slashWorker.ts
	L   deleted by us:   cli/src/commands/working-groups/startAcceptingApplications.ts
	L   deleted by us:   cli/src/commands/working-groups/startReviewPeriod.ts
	L   deleted by us:   cli/src/commands/working-groups/terminateApplication.ts
	L   both modified:   cli/src/commands/working-groups/updateRewardAccount.ts
	L   both modified:   cli/src/commands/working-groups/updateRoleAccount.ts
	L   both modified:   cli/src/commands/working-groups/updateRoleStorage.ts
	L   both modified:   cli/src/commands/working-groups/updateWorkerReward.ts
	L   both added:      cli/src/graphql/generated/queries.ts
	L   both added:      cli/src/graphql/generated/schema.ts
	L   both modified:   cli/src/helpers/validation.ts
	L   both modified:   docker-compose.yml
	L   both modified:   joystream-node.Dockerfile
	L   both modified:   metadata-protobuf/package.json
	L   both added:      metadata-protobuf/scripts/compile.ts
	L   both added:      metadata-protobuf/src/types.ts
	L   both added:      metadata-protobuf/src/utils.ts
	I/S both modified:   node/Cargo.toml
	I/S deleted by them: node/src/chain_spec/content_config.rs
	I/S both modified:   node/src/chain_spec/mod.rs
	L   both modified:   package.json
	L   both modified:   pioneer/packages/react-api/package.json
	L   both modified:   query-node/.gitignore
	L   both modified:   query-node/README.md
	L   both modified:   query-node/build.sh
	L   both added:      query-node/codegen/package.json
	L   both added:      query-node/codegen/yarn.lock
	L   both added:      query-node/kill.sh
	L   both modified:   query-node/manifest.yml
	L   both added:      query-node/mappings/.eslintrc.js
	L   added by them:   query-node/mappings/bootstrap-data/data/channelCategories.json
	L   both deleted:    query-node/mappings/bootstrap/data/members.json
	L   both modified:   query-node/mappings/index.ts
	L   both modified:   query-node/mappings/membership.ts
	L   both modified:   query-node/mappings/package.json
	L   deleted by them: query-node/mappings/src/common.ts
	L   deleted by them: query-node/mappings/src/content/curatorGroup.ts
	L   added by us:     query-node/mappings/src/genesis-data/members.json
	L   deleted by them: query-node/mappings/src/storage.ts
	L   both modified:   query-node/mappings/sumer/content/channel.ts
	L   both modified:   query-node/mappings/sumer/content/utils.ts
	L   both modified:   query-node/mappings/sumer/content/video.ts
	L   both modified:   query-node/mappings/tsconfig.json
	L   both modified:   query-node/package.json
	L   deleted by them: query-node/run-tests.sh
	L   both added:      query-node/schemas/common.graphql
	L   both added:      query-node/schemas/content.graphql
	L   both added:      query-node/schemas/membership.graphql
	L   both added:      query-node/schemas/storage.graphql
	L   both added:      query-node/schemas/workingGroups.graphql
	L   both added:      query-node/start.sh
	I/S both modified:   runtime-modules/blog/Cargo.toml
	I/S both modified:   runtime-modules/common/Cargo.toml
	I/S both modified:   runtime-modules/common/src/working_group.rs
	I/S both modified:   runtime-modules/constitution/Cargo.toml
	I/S both modified:   runtime-modules/content/Cargo.toml
	I/S both modified:   runtime-modules/content/src/lib.rs
	I/S both modified:   runtime-modules/content/src/permissions/mod.rs
	I/S both modified:   runtime-modules/content/src/tests/mock.rs
	I/S both modified:   runtime-modules/forum/Cargo.toml
	I/S both modified:   runtime-modules/forum/src/lib.rs
	I/S deleted by us:   runtime-modules/governance/src/council.rs
	I/S deleted by us:   runtime-modules/governance/src/election.rs
	I/S deleted by us:   runtime-modules/governance/src/mock.rs
	I/S deleted by us:   runtime-modules/hiring/src/hiring/mod.rs
	I/S both modified:   runtime-modules/membership/Cargo.toml
	I/S both modified:   runtime-modules/membership/src/lib.rs
	I/S deleted by us:   runtime-modules/membership/src/mock.rs
	I/S both modified:   runtime-modules/memo/Cargo.toml
	I/S both modified:   runtime-modules/proposals/codex/src/lib.rs
	I/S both modified:   runtime-modules/proposals/codex/src/tests/mock.rs
	I/S both modified:   runtime-modules/proposals/discussion/Cargo.toml
	I/S both modified:   runtime-modules/proposals/discussion/src/lib.rs
	I/S both modified:   runtime-modules/proposals/discussion/src/tests/mock.rs
	I/S both modified:   runtime-modules/proposals/engine/Cargo.toml
	I/S both modified:   runtime-modules/proposals/engine/src/lib.rs
	I/S both modified:   runtime-modules/proposals/engine/src/tests/mock/mod.rs
	I/S deleted by us:   runtime-modules/recurring-reward/Cargo.toml
	I/S both modified:   runtime-modules/staking-handler/Cargo.toml
	I/S both modified:   runtime-modules/storage/Cargo.toml
	I/S deleted by them: runtime-modules/storage/src/data_directory.rs
	I/S deleted by them: runtime-modules/storage/src/data_object_storage_registry.rs
	I/S deleted by them: runtime-modules/storage/src/data_object_type_registry.rs
	I/S both modified:   runtime-modules/storage/src/lib.rs
	I/S deleted by them: runtime-modules/storage/src/tests/data_directory.rs
	I/S deleted by them: runtime-modules/storage/src/tests/data_object_storage_registry.rs
	I/S deleted by them: runtime-modules/storage/src/tests/data_object_type_registry.rs
	I/S deleted by them: runtime-modules/storage/src/tests/mock.rs
	I/S deleted by us:   runtime-modules/token-minting/Cargo.toml
	I/S both modified:   runtime-modules/working-group/Cargo.toml
	I/S both modified:   runtime-modules/working-group/src/lib.rs
	I/S both modified:   runtime-modules/working-group/src/tests/mock.rs
	I/S both modified:   runtime-modules/working-group/src/tests/mod.rs
	I/S both modified:   runtime/Cargo.toml
	I/S deleted by us:   runtime/src/integration/content_directory.rs
	I/S deleted by us:   runtime/src/integration/proposals/membership_origin_validator.rs
	I/S both modified:   runtime/src/integration/proposals/proposal_encoder.rs
	I/S deleted by us:   runtime/src/integration/working_group.rs
	I/S both modified:   runtime/src/lib.rs
	I/S both modified:   runtime/src/primitives.rs
	I/S both modified:   runtime/src/runtime_api.rs
	I/S both modified:   runtime/src/tests/proposals_integration/working_group_proposals.rs
	I/S both added:      scripts/generate-weights.sh
	I/S both modified:   scripts/run-dev-chain.sh
	L   both modified:   scripts/runtime-code-shasum.sh
	L   both modified:   start.sh
	L   both modified:   storage-node/package.json
	L   deleted by them: storage-node/packages/cli/package.json
	L   deleted by them: storage-node/packages/cli/src/commands/dev.ts
	L   deleted by them: storage-node/packages/runtime-api/identities.js
	L   deleted by them: storage-node/packages/runtime-api/package.json
	L   deleted by them: storage-node/packages/runtime-api/workers.js
	L   both modified:   types/augment-codec/all.ts
	L   deleted by them: types/augment-codec/augment-api-consts.ts
	L   both modified:   types/augment-codec/augment-api-errors.ts
	L   deleted by them: types/augment-codec/augment-api-events.ts
	L   deleted by them: types/augment-codec/augment-api-query.ts
	L   deleted by them: types/augment-codec/augment-api-rpc.ts
	L   deleted by them: types/augment-codec/augment-api-tx.ts
	L   deleted by them: types/augment-codec/augment-types.ts
	L   both modified:   types/augment/all/defs.json
	L   both modified:   types/augment/all/types.ts
	L   deleted by them: types/augment/augment-api-consts.ts
	L   both modified:   types/augment/augment-api-errors.ts
	L   deleted by them: types/augment/augment-api-events.ts
	L   deleted by them: types/augment/augment-api-query.ts
	L   deleted by them: types/augment/augment-api-rpc.ts
	L   deleted by them: types/augment/augment-api-tx.ts
	L   deleted by them: types/augment/augment-types.ts
	L   both modified:   types/package.json
	L   both modified:   types/src/common.ts
	L   both modified:   types/src/content/index.ts
	L   deleted by us:   types/src/hiring/index.ts
	L   both modified:   types/src/index.ts
	L   deleted by us:   types/src/legacy.ts
	L   both modified:   types/src/proposals.ts
	L   both modified:   types/src/storage.ts
	L   both modified:   types/src/working-group/index.ts
	L   both modified:   utils/api-scripts/package.json
	L   deleted by us:   utils/api-scripts/src/initialize-content-lead.ts
	I/S both modified:   utils/chain-spec-builder/Cargo.toml
	I/S both modified:   utils/chain-spec-builder/src/main.rs
	L   both modified:   yarn.lock
```

### Conflicts resolution process
The process is based on https://github.com/Joystream/joystream/issues/2475 which was followed during the `master` -> `olympia_dev` merge and resulted in https://github.com/Joystream/joystream/pull/2491

Variables:

* `{collaborator_name}` is `leszek` / `ignazio` / `shamil`
* `{files}` is the list of all files / directories the collaborator is **not** resolving the conflicts in:
  * for Ignazio/Shamil this means:
    ```
    # :!: means "does not match", so all files/directories except those listed below will be matched
    # Note that for files there is additional '_' at the end of the path (ie.: ':!:Cargo.toml_')
    # It's not entirely clear to me why it is needed, but otherwise git will not recognize that those files need to be excluded

    ':!:runtime' ':!:runtime-modules' ':!:node' ':!:utils/chain-spec-builder' ':!:Cargo.lock*' ':!:Cargo.toml*' ':!:scripts/generate-weights.sh*' ':!:scripts/run-dev-chain.sh*' ':!:.github/workflows/joystream-node-benchmarks.yml*'
    ```* for Leszek this means:
    ```
    # The exact opposite of the above
    'runtime' 'runtime-modules' 'node' 'utils/chain-spec-builder' 'Cargo.lock' 'Cargo.toml' 'scripts/generate-weights.sh' 'scripts/run-dev-chain.sh' '.github/workflows/joystream-node-benchmarks.yml'```Each collaborator executes the following flow:    # 1. Checkout the target branch
    git checkout olympia
    
    # 2. Create conflict resolution branch
    git checkout -b giza-olympia-{collaborator_name}
    
    # 3. Initialize the merge
    git merge giza_feature_NewContentFeaturesAndNFT
    
    # 4. Force-remove all files other than the ones the collaborator is resolving the conflicts in
    git rm {files} --force -r
    
    # 5. Checkout the `olympia` version of all the removed files / directories
    git checkout HEAD {files}
    
    # Resolve remaining conflicts...
    # Commit the result
    git commit
    
        **Important considerations:**
        - `giza-olympia-{collaborator_name}` is only a tmp commit resolution branch and its own commit history will not be preserved!
        The only commit should be the conflicts resolution commit, all of the other adjustments should be done later, once the `giza_feature_NewContentFeaturesAndNFT` is merged to `olympia` (see: _Final merge_ below)
        - We need to make sure each collabotor works on the same version of `olympia` and `giza_feature_NewContentFeaturesAndNFT`. Comparing latest commit hash of each branch between collaborators is recommended.
        
        #### Final merge
        In the end one person (in this case it could be me), combines the work from collaborator branches into one merge commit and creates the final PR:# 1. Checkout the target branchgit checkout olympia
    
    # 2. Initialize the merge
    git merge giza_feature_NewContentFeaturesAndNFT
    
    # 3. Clean the working tree
    git rm . --force -r
    
    # 4. Checkout files with resolved conflicts from Ignazio's branch
    git checkout ignazio/giza-olympia-ignazio 'runtime' 'runtime-modules' 'node' 'utils/chain-spec-builder' 'Cargo.lock' 'Cargo.toml' 'scripts/generate-weights.sh' 'scripts/run-dev-chain.sh' '.github/workflows/joystream-node-benchmarks.yml'
    
    # 5. Checkout files with resolved conflicts from Leszek's branch
    git checkout leszek/giza-olympia-leszek ':!:runtime' ':!:runtime-modules' ':!:node' ':!:utils/chain-spec-builder' ':!:Cargo.lock_' ':!:Cargo.toml_' ':!:scripts/generate-weights.sh_' ':!:scripts/run-dev-chain.sh_' ':!:.github/workflows/joystream-node-benchmarks.yml*'
    
    # 6. Commit the mege
    git commit

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710237401888) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
Acknowledged

**Comment by dobertRowneySr** [comment]
***Updated 25 Jan 12:15 AM***:
base branch = [ignazio-bovo@](https://github.com/ignazio-bovo/joystream/tree/giza_feature_NewContentFeaturesAndNFT)f62058bababe3a2bb3022ed4575fceec47fbe003

Due to latest merges on Giza

**Comment by Lezek123** [comment]
**Final update:**
Conflicts resolutions branches:
- [giza-olympia-leszek](https://github.com/Lezek123/substrate-runtime-joystream/commits/giza-olympia-leszek) (commit https://github.com/Lezek123/substrate-runtime-joystream/commit/754102f6a648affc3311269652f7e460ccdfee07)
- [giza-olympia-ignazio](https://github.com/ignazio-bovo/joystream/commits/giza-olympia-ignazio) (commit https://github.com/ignazio-bovo/joystream/commit/4b2bee5bc2fae730d0eb393d4b8b6abbe6e51db8)

Final `olympia` commit that was used during the merge was https://github.com/Joystream/joystream/commit/5920eaeedf19aaf868970657c1536b17f9a8eeb3 (both conflicts resolutions branches were up to date with this commit when https://github.com/Joystream/joystream/pull/3123 was composed)

Final [giza_feature_NewContentFeaturesAndNFT](https://github.com/ignazio-bovo/joystream/commits/giza_feature_NewContentFeaturesAndNFT) (`base_branch`) commit was https://github.com/ignazio-bovo/joystream/commit/f62058bababe3a2bb3022ed4575fceec47fbe003 (both conflicts resolutions branches were up to date with this commit when https://github.com/Joystream/joystream/pull/3123 was composed)

**Additional notes:**
[`giza-olympia-ignazio`](https://github.com/ignazio-bovo/joystream/commits/giza-olympia-ignazio) had 45 other commits after the conflicts resolution commit (https://github.com/ignazio-bovo/joystream/commit/bd369c077b02b8150ebaff0fecc29c4fd5c6b434) at the time when the merge PR (https://github.com/Joystream/joystream/pull/3123 was composed), however the conflicts resolution was initially done against an outdated version of `olympia` (commit https://github.com/Joystream/joystream/commit/e859826b0937f5f6a7a98d7edb1665cd13ff340e), which was later fixed by merging the up-to-date version of `olympia` to `giza-olympia-ignazio` (in https://github.com/ignazio-bovo/joystream/commit/4b2bee5bc2fae730d0eb393d4b8b6abbe6e51db8). To avoid complex rebasing, the 45 commits were "squashed" into one conflicts resolution commit in the PR https://github.com/Joystream/joystream/pull/3123 (commit https://github.com/Joystream/joystream/pull/3123/commits/8cd0d2d8501061a1d48fb185a0c487f6f15fab3c)

**Comment by Lezek123** [comment]
Merge done in https://github.com/Joystream/joystream/pull/3123
