### ISSUE TITLE
Membership migration Giza -> Olympia. 

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#3029]
We need to preserve membership during the giza-to-olympia network upgrade. We're starting the new chain so we use export/import tools (https://github.com/Joystream/runtime-state-export-tools) to address the issue. 

#### Scope
* use export tools (modify if needed) to export JSON file for members
* change node/chain-spec code to support exported JSON for genesis block
* change the query-node mappings to support bootstrapping via the same JSON file

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710237065745) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment]
Done.
