### ISSUE TITLE
Bounties: Add the work description to the `announce_work_entry` extrinsic. 

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#3038]
Add the `description` field to the extrinsic and its event only (no storage change).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201810432142171) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
After having another chat with Theo, we've made a decision to park this for the time being if not cancel. Moving to sandbox and assigned to myself.
