### ISSUE TITLE
Test Env for Bounties: QN

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#3039]
**Context:**

Runtime has some Bounties support, with a few follow up tasks in the pipeline (Councils proposals, Work entry announcement extrinsics)
There are independent strands of QN (Giza, Olympia, Bounties)
There are 2 versions of Pioneer deployed (one for Olympia and one Olympia + Bounties)

**Objective:**

Create a testable environment for Bounties module, without impacting work on Olympia release.

**To-do:**

Create env (network in Pioneer terms) with Olympia version of Runtime and Bounties version of QN

**DOD:**

User can select Bounties-TestNet from drop down in the networks >
![Screenshot 2022-01-13 at 14.34.55.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/ae780d64-b656-4dc6-b310-bfd75e76164e)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703600667556) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Making use of playground deployments and adding feature to pioneer to configurable it through network-config query in url we can now point pioneer to different networks:

Implemented in https://github.com/Joystream/pioneer/pull/2193 and https://github.com/Joystream/pioneer/pull/2532
