### ISSUE TITLE
Investigate LOCK_ID used for Nomination

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3057]
SSIA

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710181823474) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
There is only one staking lock ID used in the `staking pallet v2.0.1`.
```
const STAKING_ID: LockIdentifier = *b"staking ";
```

**Comment by bedeho** [comment]
Great, noted.
