### ISSUE TITLE
Bag assignment to buckets not registered during bag creation

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3069]
# Background
The launch of Giza had to be postponed due to an apparent critical bug in the `storage` pallet module, in particular in the `create_dynamic_bag` call done from the content directory

https://github.com/Joystream/joystream/blob/giza/runtime-modules/storage/src/lib.rs#L2666

# Proposal
It seems `create_dynamic_bag_inner` forgets to 

* iterate the `distribution_buckets` and update `DistributionBucketRecord::assigned_bags`
https://github.com/Joystream/joystream/blob/giza/runtime-modules/storage/src/lib.rs#L920
* iterate the `storage_buckets` and update `StorageBucketRecord::voucher`
https://github.com/Joystream/joystream/blob/giza/runtime-modules/storage/src/lib.rs#L826

There should also be a unit test added to the `create_dynamic_bag_inner` to assert this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703600083371) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
Fixed.
