### ISSUE TITLE
Should caller decide bag deletion prize in storage pallet

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3070]
# Background
From the signature of bag creation and bag creation feasibility checkers, it seems the caller gets to decide what - if any, prize should be used, since it has payload `deletion_prize: &Option<DynamicBagDeletionPrize<T>>,`.

# Question
Is this really sensible, as all bags are effectively equal in terms of what the deletion prize is trying to police: state bloat, regardless of whether its a channel or membership bag, or certainly , whether its channel A or channel B. It seems the simplest approach is to either have a tunable value in `storage` pallet which is indeed universal, or at worst , oner per dynamic bag type, but this feels over-engineered.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201810379947921) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
The code was merged.
