### ISSUE TITLE
Cleaner storage bag creation integration code

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3071]
# Note
No need to change this for Giza, but seems like tech-debt to me, discovered while diagnosing

https://github.com/Joystream/joystream/issues/3069

# Background
We need a clear and crisp example in the runtime of how to plug into the storage system, as it needs to be used from other pallets in the future, but currently the variation we have in the content directory, specifically from `create_channel`,  seems rough to me. Two particularly severe issues is the presence of two error operators post mutation safe boundary:

* https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L763
* https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L769

# Proposal
1. More comments: there are large complex flows of checks and calls which have 0 explanation., in particular around bag creation.
1. Drop bag existence check: this is effectively is a runtime check of a broken chain, as the only way there could exist a bag for a new channel which exceeds the prior max id for channels, is if the content pallet or some other pallet in the chain, unwittingly already created it. If any thing, the _can_create_ call can subsume this by returning false if the bag already exists, and this is already the case it seems
https://github.com/Joystream/joystream/blob/giza/runtime-modules/storage/src/lib.rs#L2849
1. There is no reason to have two distinct calls `can_create_dynamic_bag_with_objects_constraints` and `can_create_dynamic_bag`, these are semantically indistinguishable, and infact the implementations clearly show how easy it would be to just have a single `can_create_dynamic_bag` which takes an additional `Option<UploadParameters<T>>`. Hence this should be fixed in the `storage` pallet as well.
1. Same for actual creation, so drop `create_dynamic_bag_with_objects_constraints`.
1. There should not be a second call to `uplaod_data_objects`, 
https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L769
the upload should be bundled with the bag creation, as it will have access to upload params. This probably will also open door for reducing # reads & writes and simplifying interface for storage pallet users, but more importantly, it is super clear what it means to create a bag including references to uploads yet to be initiated. Clearly some sort of `BagUpdate` is being computed based off these parameters, which means that vouchers and deletion prizes already reflect an impending upload. This begs the question of how this currently is not compounded by call to `upload_data_objects`, but in the end it takes too much work to get to the bottom of this.
1. In `can_create_dynamic_bag` signature, rename `deletion_prize` to `account_deletion_prize`.
1. Review this: https://github.com/Joystream/joystream/issues/3070
1. It should not be possible to specify distinct deletion prize account for the channel and each individual asset upload during dynamic bag creation. This is currently statically possible, and thus we have had to introduce awkward `Error::<T>::AccountsNotCoherent`, but this is all a side-effect of reusing `UploadParameters` across both pure uploads and uploads combined with bag creation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958711456195) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201958687417145/1201958711456195

**Comment by bedeho** [comment]
# Addendum

Further investigation on point 3 by @ignazio-bovo  :

1. `create_dynamic_bag_with_object_constraints`
2. `create_dynamic_bag`

Showed that both have identical side-effects when they succeed, its just that the 1 does extra integrity checks equivalent to `can_create_dynamic_bag_with_objects_constraints`, but does in fact not update the voucher or fee related state in any way as I was worried about in point 5 in the prior post. This gives extra support to the recommendation that thre is no need to have two distinct invocations here after the mutation safe barrier, as they are not different as long as the firs check has been done.

# Conclusion

There is a fundamental issue here that the "check" done into another pallet is still not a static guarantee that the "create" call will work, hence we may as well bite the bullet and not-separate them, but rather have a singular check+side-effect call, which will be _fine_, since this check is the last one needed before mutation is safe anyway. This allows us to go from this

```Rust
if Storage::<T>::ensure_bag_exists(&channel_bag_id).is_err() {
    if let Some(params) = upload_params.clone() {
        Storage::<T>::can_create_dynamic_bag_with_objects_constraints(
            &DynamicBagIdType::<T::MemberId, T::ChannelId>::Channel(channel_id),
            &Some(deletion_prize.clone()),
            &params
        )?;
    } else {
        Storage::<T>::can_create_dynamic_bag(
            &DynamicBagIdType::<T::MemberId, T::ChannelId>::Channel(channel_id),
            &Some(deletion_prize.clone()),
        )?;
    }
}

//
// == MUTATION SAFE ==
//

if Storage::<T>::ensure_bag_exists(&channel_bag_id).is_err() {
    if let Some(params) = upload_params.clone() {
        Storage::<T>::create_dynamic_bag_with_objects_constraints(
            DynamicBagIdType::<T::MemberId, T::ChannelId>::Channel(channel_id),
            Some(deletion_prize),
            params,
    )?;
    // create_dynamic_bag_with_objects with its can* guard ensures that this invocation succeds
    } else {
        Storage::<T>::create_dynamic_bag(
            DynamicBagIdType::<T::MemberId, T::ChannelId>::Channel(channel_id),
            Some(deletion_prize),
        )?;
    }
}

 // this will not fail because can_create_dynamic_bag_with_objects_constraints will check also for successful upload conditions
if let Some(params) = upload_params.clone() {
    Storage::<T>::upload_data_objects(params)?;
}
```

to this

```Rust
Storage::<T>::create_dynamic_bag(
                        &DynamicBagIdType::<T::MemberId, T::ChannelId>::Channel(channel_id),
                        &Some(deletion_prize.clone()),
                        &params
                    )?;
//
// == MUTATION SAFE ==
//
```

No need for
- explicit bag existence check
- upload params destructuring condition
- differential bag vs bag with constraints check
- differential bag vs bag with constraints creation call

If we incorporate this https://github.com/Joystream/joystream/issues/3070 we can even drop the `&Some(deletion_prize.clone())`.

**Comment by bedeho** [comment]
Ironically, we appear to already by taking this approach in  `create_video`

https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L1096

**Comment by ignazio-bovo** [comment]
Are the `can` counterpart really needed, since for example, `create_dynamic_bag` will always validate parameters before the mutation safe mark and so `upload_data_objects`

**Comment by ignazio-bovo** [comment]
@shamil-gadelshin﻿

**Comment by bedeho** [comment]
Done.
