### ISSUE TITLE
Allow to filter entity by WorkingGroup id directly 

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3095]
Fix https://github.com/Joystream/pioneer/issues/857 by allowing to replace:

```gql
memberships( where: { roles_some: { group: { id_in: [ ... ] } } } ) { ... } # Fails
```

by:

```gql
memberships( where: { roles_some: { groupId_in: [ ... ] } } ) { ... } # Works
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711376366604) by [Unito](https://www.unito.io)

**Comment by thesan** [comment]
@ondratra I think there has been a misunderstanding there. I originally wrote this on this PR: #3043 (I just requested your review there). So this should be done already...
