### ISSUE TITLE
Olympia membership migration

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3096]
Import membership data during the Olympia release. Giza data export was made by [joystream data exporting tools](https://github.com/Joystream/runtime-state-export-tools). Exporting tools are up-to-date and didn't require modification.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711376647103) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Implemented in https://github.com/Joystream/joystream/pull/3055
