### ISSUE TITLE
Compute new Olympia balances

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3097]
As described here https://github.com/Joystream/joystream/issues/3014#issuecomment-1009207887

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711292992660) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Export tool will enumerate all accounts and cap balances as suggested in https://github.com/Joystream/joystream/issues/3014#issuecomment-1009207887

Implementation will be in https://github.com/Joystream/joystream/issues/3223
