### ISSUE TITLE
Make indexer fault proof

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#310]
Requires 

- information in the database about what the last processed event was
- all mappers to be executed transactionally, and developer should not have to think of this.

**Comment by metmirr** [comment]
Done in https://github.com/Joystream/joystream/pull/283/commits/4471243bcc48295b6e245d8f16541dca10a590c1 and https://github.com/Joystream/joystream/pull/283/commits/d482fe598c258f03c540fdc4bff48f4e56ffd72f
