### ISSUE TITLE
Allow indexer and API server to run on separate hosts.

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#311]
While retaining easy deployment.

**Comment by metmirr** [comment]
Done in https://github.com/Joystream/joystream/pull/309/commits/fa775389c2b5bbf87e9051393e8dd616df47481e

During the code generation process configurations for both API server and indexer are updated. After the code generation is completed it's possible to run indexer and API server on different hosts.

**Comment by bedeho** [comment]
With the current approach, how would the developer actually deploy on separate hosts?
