### ISSUE TITLE
Giza type issues

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#3121]
1. jsstats using `@joystream/types": "^0.17.1`
```
$ yarn
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.

$ yarn build
./node_modules/@joystream/types/JoyEnum.js
SyntaxError: /home/joystream/jsstats/node_modules/@joystream/types/JoyEnum.js: Missing class properties transform.
   6 | function JoyEnum(types) {
   7 |     return class JoyEnumObject extends codec_1.Enum.with(types) {
>  8 |         static typeDefinitions = types;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   9 |         typeDefinitions = JoyEnumObject.typeDefinitions; // Non-static version
  10 |         static create(registry, typeKey, value) {
  11 |             return new JoyEnumObject(registry, { [typeKey]: value });
```

2. The cli has issues too: `Unable to resolve type StorageBucketsPerBagValueConstraint`
```
Compiling joystream-node v5.14.0 (/home/joystream/joystream/node)                                                                                           
    Finished release [optimized] target(s) in 5m 04s

joystream$ cd cli
joystream/cli$ ./bin/run working-groups:openings -g operationsAlpha
(node:14465) [MODULE_NOT_FOUND] Error Plugin: @joystream/cli: Cannot find module '/home/joystream/joystream/node_modules/@joystream/metadata-protobuf/lib/utils.js'
module: @oclif/config@1.17.0
task: toCached
plugin: @joystream/cli
root: /home/joystream/joystream/cli
See more details with DEBUG=*
(repeated like five million times)
2022-01-27 09:30:17        REGISTRY: Unable to resolve type StorageBucketsPerBagValueConstraint, it will fail on construction
2022-01-27 09:30:17        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageBucketsPerBagValueConstraint):: DoNotConstruct: Cannot construct unknown type StorageBucketsPerBagValueConstraint
    at EventEmitter.value (/home/joystream/joystream/node_modules/@polkadot/api/base/Init.cjs:82:25)                                                          
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    Error: FATAL: Unable to initialize the API: createType(StorageBucketsPerBagValueConstraint):: DoNotConstruct: Cannot construct unknown type               
    StorageBucketsPerBagValueConstraint

version: @joystream/cli/0.6.0 linux-x64 node-v14.16.1
```
3. Installing cli as root
```
joystream/cli # npm install -g @joystream/cli
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/local/bin/joystream-cli -> /usr/local/lib/node_modules/@joystream/cli/bin/run                                                                                                                    
> iso-constants@0.1.2 install /usr/local/lib/node_modules/@joystream/cli/node_modules/iso-constants                                                            > node build.js > index.browser.js    
                                                                                                                                                               sh: 1: cannot create index.browser.js: Permission denied

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iso-constants@0.1.2 install: `node build.js > index.browser.js`
npm ERR! Exit status 2

# unusual for root?
```
4. report-generator used `@joystream/types/media` which has been moved to [`legacy`](https://github.com/Joystream/joystream/blob/master/types/src/legacy.ts) and renamed too. is there some [documentation](#2534), an announcement for developers would be lovely :)
```
node_modules/@polkadot/types/create/registry.d.ts:7:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

7 export declare class TypeRegistry implements Registry {
                       ~~~~~~~~~~~~

src/lib/api.ts:29:34 - error TS2307: Cannot find module '@joystream/types/content-directory' or its corresponding type declarations.

29 import { Entity, EntityId } from "@joystream/types/content-directory";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/lib/api.ts:30:39 - error TS2307: Cannot find module '@joystream/types/media' or its corresponding type declarations.

30 import { ContentId, DataObject } from "@joystream/types/media";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~
---
src/lib/api.ts:29:18 - error TS2614: Module '"@joystream/types/legacy"' has no exported member 'EntityId'. Did you mean to use 'import EntityId from "@joystre\
am/types/legacy"' instead?

29 import { Entity, EntityId } from "@joystream/types/legacy";
                    ~~~~~~~~

src/lib/api.ts:30:21 - error TS2614: Module '"@joystream/types/legacy"' has no exported member 'DataObject'. Did you mean to use 'import DataObject from "@joy\
stream/types/legacy"' instead?

30 import { ContentId, DataObject } from "@joystream/types/legacy";
                       ~~~~~~~~~~
```
Which dependencies are redundant?
```
    node_modules/@polkadot/types/create/registry.d.ts:7:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

7 export declare class TypeRegistry implements Registry {
                       ~~~~~~~~~~~~

    "@joystream/content-metadata-protobuf": "^1.1.0",
    "@joystream/types": "^0.16.1",
    "@polkadot/api": "4.2.1",
    "@polkadot/api-contract": "4.2.1",
    "@polkadot/keyring": "^6.0.5",
    "@polkadot/types": "4.2.1",
    "@polkadot/util": "^6.0.5",
    "@polkadot/util-crypto": "^6.0.5",
    "@polkadot/wasm-crypto": "^4.0.2",
    "@types/bn.js": "^4.11.6",
    "bn.js": "^5.1.2",
    "@polkadot/ts": "^0.3.62",
    "typescript": "^3.9.7"
```

**Comment by mnaamani** [comment]
Latest types version is `v0.17.2` for giza.
https://www.npmjs.com/package/@joystream/types/v/0.17.2

Also the giza cli is now `v0.6.0`
https://www.npmjs.com/package/@joystream/cli/v/0.6.0

Does that resolve issues 1, 2 and 3?

**Comment by mnaamani** [comment]
As for point 4, you probably want to look at `@joystream/types/content` and `@joystream/types/storage` and best reference code on use would be the joystream cli.

Regarding redundant dependencies:
change:
    "@joystream/content-metadata-protobuf": "^1.1.0",
    "@joystream/types": "^0.16.1",
to:
    "@joystream/metadata-protobuf": "^1.0.0",
    "@joystream/types": "^0.17.2,

for the remaining package version, best reference would be our cli:
https://github.com/Joystream/joystream/blob/master/cli/package.json

cc: @Lezek123

**Comment by traumschule** [comment]
Thanks a lot for the quick reply!
1. no change
2. no, the cli on `master` uses 0.17.2  already and shows version 0.6.0.
3. same. would need to investigate what `iso-constants@0.1.2` is trying to do.
4. will try!

**Comment by Lezek123** [comment]
1. Could you provide a link to the repository? What is the `node` and `typescript` version that you're using?
2. Make sure to `yarn build:packages` before running the cli commands through `./cli/bin/run`
3. Did you try installing it as non-root? In my case using my usual system account worked, but for `root` it failed with the same error. I'll try to investigate it more.

**Comment by traumschule** [comment]
1. `14.18` and `4.4.3` https://git.joystreamstats.live/Operations/jsstats/src/frontend-giza/package.json#L60
2. That worked! The script is not available in `cli` but in root, created a PR: #3122
3. That too except on systems without `sudo` privileges:
```
$ npm install -g @joystream/cli
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

$ npm -v
6.14.15
```

**Comment by Lezek123** [comment]
1. See: https://github.com/Joystream/joystream/pull/3134.

    A temporary solution (before the new version of `@joystream/types` is published) is to checkout this branch and then:
    ```
    yarn
    cd types
    yarn pack
    ```
    Copy `joystream-types-v0.17.3.tgz` to the root of your project and change the `@joystream/types` dependency in `package.json` to:
    ```
        "@joystream/types": "file:./joystream-types-v0.17.3.tgz",
    ```

**Comment by traumschule** [comment]
Thousand thanks for making this work! I thought it could be easily fixed by targeting `esnext` but it failed with `0.17.2` too.

**Comment by traumschule** [comment]
for 4, this is still unsolved:
```
$ tsc --build tsconfig.json
node_modules/@polkadot/types/create/registry.d.ts:7:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

7 export declare class TypeRegistry implements Registry {
                       ~~~~~~~~~~~~
```
https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#tailrec-conditional
If the fix is non-trivial maybe best in a separate issue?

**Comment by mnaamani** [comment]
> 1. See: [Types and metadata-protobuf: Patch to target es2017 #3134](https://github.com/Joystream/joystream/pull/3134).
>        A temporary solution (before the new version of `@joystream/types` is published) is to checkout this branch and then:
>        ```
>        yarn
>        cd types
>        yarn pack
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        Copy `joystream-types-v0.17.3.tgz` to the root of your project and change the `@joystream/types` dependency in `package.json` to:
>        ```
>            "@joystream/types": "file:./joystream-types-v0.17.3.tgz",
>        ```

types v0.17.3 and metadata-protobuf v1.0.1 have been published
