### ISSUE TITLE
Better query specification format

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#313]
This is the current example in JSON

```json
[
	{
		"name": "MemberRegistered",
		"fields": [
			{ "name": "memberId", "type": "int!" },
			{
				"name": "accountId",
				"type": "string!"
			}
		]
	}
]
```

is quite a bit heavier than using something GraphQL inspired

```graphql
MemberRegistered {
	memberId: int!,
	accountId: string!
}
```

This latter format also has the benefit of being much more compatible with The Graph.

**Comment by metmirr** [comment]
Done in https://github.com/Joystream/joystream/pull/418/commits/064eac5d2f41f05ff655b02c6e05929676ee8065
