### ISSUE TITLE
Give all lock IDs human readable names in Rust codebase

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3139]
Similar to staking and vesting modules. Can help with manual inspection of accounts without needing a lookup table.

As an extension of https://github.com/Joystream/joystream/issues/1899.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201746667644408) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
Fixed
