### ISSUE TITLE
Simplify lock combinatino representation ALLOWED_LOCK_COMBINATIONS

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3149]
# Background

Currently, `ALLOWED_LOCK_COMBINATIONS`, which is supposed to be the source of truth for account locking attempts, has representation `BTreeSet<(LockIdentifier, LockIdentifier)>`. This means assymetric locking relationships are in principle allowed, namely that lock x can be applied when lock y is already present, but not vice versa. This is however not how the locking rules actually work in Joystream, and so this is too expressive, and opens the door for sloppy initilization, which indeed appears to already be present.

https://github.com/Joystream/joystream/blob/5920eaeedf19aaf868970657c1536b17f9a8eeb3/runtime/src/constants.rs#L126

# Proposal

Come up with a succinct and restrictive representation of locking rules that mirrors what we actually want to enforce in Joystream.

**Comment by shamil-gadelshin** [comment]
The [current implementation](https://joystream.gitbook.io/joystream-handbook/key-concepts/staking) of the staking mechanism seems to have only two types (or classes) of compatible lock combinations: `all` and `regular`(for 0, 10, *b"vesting " IDs) with a single exception for the invitation locks. 

It makes sense to take advantage of this fact and move away from the table structure of the lock combinations (up to N^2 combinations) to a much simpler class-based representation.

**Comment by bedeho** [comment]
I updated the handbook to reflect a very similar model, except invitation locks are just treated as `all`, more or less.

https://joystream.gitbook.io/joystream-handbook/key-concepts/staking#locks-1

So one way to incorporate this would be to have

```Rust

enum Lock {
Vote,
Invitation,
...
}
pub static ref RIVALROUS_LOCKS BTreeSet<Lock>

//alternatively just have 

pub fn is_rivalrous(Lock) -> Boolean {
  // match on type and just return... right value
}
```

and now checking whether there are any locks conflicting with adding some lock `x` to an account `A` you just check
- make sure same lock is not already appliead
- make sure that if `x` is rivalrous, that all existing locks on `A` are not.

its not clear anything really needs to be exported here.

What do you think?
