### ISSUE TITLE
CLI: Allowed lock combinations

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3159]
- [x] Introduce the idea of alllowed lock combinations to CLI (currently it doesn't recognize which locks can be combined)
- [x] Retrieve allowed lock combinations from the runtime once https://github.com/Joystream/joystream/pull/3130 is merged
- [x] Check total balance instead of available/usable balance once https://github.com/Joystream/joystream/issues/3161 is fixed

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201756082874293) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
I don't think we need this for olympia, do we, correct me if I am wrong? if I am correct, could this be turned into a community task?

**Comment by Lezek123** [comment]
1st point addressed by https://github.com/Joystream/joystream/pull/3190
Remaining 2 points addressed by https://github.com/Joystream/joystream/pull/3241 and https://github.com/Joystream/joystream/pull/3257
