### ISSUE TITLE
StakingHandler: is_enough_balance_for_stake check is not taking reusable stakes into account

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3161]
**Issue:**
[`is_enough_balance_for_stake`](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/staking-handler/src/lib.rs#L174) only checks if `usable_balance` of an account is `>= amount`, while `usable_balance` excludes any tokens that are already locked. This is not correct, because we reuse locked tokens for multiple staking purposes, for example [StakingCandidateLock should be compatible with any working group lock](https://github.com/Joystream/joystream/blob/olympia/runtime/src/constants.rs#L148).

**Example 1:**
Let's say we setup a staking account with:

```
lockedBalance: 200
availableBalance: 1800
totalBalance: 2000
```

200 JOY is locked with `StakingCandidateLock`.
If we want to apply to an opening which requires a stake of `2000 JOY`, we'll get `InsufficientBalanceToCoverStake`.

**Example 2:**
Let's take another example and setup a staking account with:

```
lockedBalance: 200
availableBalance: 2000
totalBalance: 2200
```

In this case also 200 JOY is locked with `StakingCandidateLock`.
We can now succesfully apply to an opening which requires a stake of `2000 JOY`, but after applying we still have `200 JOY` available:

```
# Balances after applying:
lockedBalance: 2000
availableBalance: 200
totalBalance: 2200
```

**How to reproduce:**

1. Use https://github.com/Lezek123/substrate-runtime-joystream/tree/olympia-initialize-lead-console-logs branch for improved `console.log` outputs
1. `yarn && yarn workspace @joystream/types build`
1. Start the node
1. Execute `GROUP=distributionWorkingGroup yarn workspace api-scripts initialize-lead`
1. The output should be as follows:

```
Creating distributionWorkingGroup lead opening...
Setting up staking account...
Staking account balances before apply:  { available: 2000, locked: 200, total: 2200 }
Applying to distributionWorkingGroup lead opening...
Staking account balances after apply:  { available: 200, locked: 2000, total: 2200 }
```

1. Now reduce the initial balance of the staking account in the script by chaning [`STAKING_ACCOUNT_CANDIDATE_STAKE`](https://github.com/Lezek123/substrate-runtime-joystream/blob/olympia-initialize-lead-console-logs/utils/api-scripts/src/initialize-lead.ts#L24) const to `new BN(0)`
1. Re-run the script using different working group, ie.: `GROUP=storageWorkingGroup yarn workspace api-scripts initialize-lead`
1. The output should be as follows:

```
Creating storageWorkingGroup lead opening...
Setting up staking account...
Staking account balances before apply:  { available: 1800, locked: 200, total: 2000 }
Applying to storageWorkingGroup lead opening...
Error: Failed to apply on lead opening! - Extrinsic execution error: InsufficientBalanceToCoverStake ( Insufficient balance to cover stake.)
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201758363490308) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
We should update `staking candidate` lock ID name after fixing this issue.
