### ISSUE TITLE
Question: Changing usernames and what happens to the old one?

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3165]
Currently, on the testnet a few people have changed their usernames. It seems like anyone can then take the username from them.

* Is there any protection against this planned or built?
* Is it needed or even worth having any sort of protection against this? (I'm very divided on this)
* Is there a unique cost associated with changing a username? Can this cost be adjusted to prevent spam attacks using it?

**Comment by bedeho** [comment]
1. nothing planned.
2. not sure?
3. not really.

**Comment by mochet** [comment]
Closing as very old and there's no problem/solution
