### ISSUE TITLE
DevOps - deploy-infra.sh and Deploy Network improvements

### ISSUE THREAD

**Issue by ahhda** [Joystream/joystream#3167]
* Have a step to check for duplicate stack names before deleting a stack on error. Prevent deletion of existing stacks.
* Remove Pioneer deployment
* Fixes to make it work with Olympia changes
* Add VolumeSize as an input for CloudFormation

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201765726923592) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Once https://github.com/Joystream/joystream/pull/3055 in merged make sure to update genesis data file for query-node  if deployment includes initial members.

**Comment by mnaamani** [comment]
- Deploy one storage node and one distributor node
- Deploy member faucet
- Similar to suggestion for playground produce artifact with all service endpoints
- Just as the playground uses start.sh and run a setupNewChain scenario, I think we need to have a special scenario suitable for network deployment
- decide what to do about the "build/admin" instance after deployment. terminate it? also there is confusion in the naming across the cf templates and ansible where build and admin are used to refer to the same instance.
- perhaps user deploying needs to supply their own SSH public key to be able to access the instances. ie not a named in the AWS profile account used for deployment. (To be added to ./ssh/authorized_keys)

**Comment by mnaamani** [comment]
Both for deploy network and playground actions, the action should handle the flow being manually cancelled and delete cf stack.

**Comment by ahhda** [comment]
* Add ability to set `ALL_PROPOSALS_PARAMETERS_JSON` as Github Action input

**Comment by mnaamani** [comment]
> * Just as the playground uses start.sh and run a setupNewChain scenario, I think we need to have a special scenario suitable for network deployment

Expanding on this, the scenario run needs access to the sudo key generated for the new chain. This of course is provided in the "secrets" generated by chainspec builder.

For the faucet to function correctly, a couple things are missing in the newChainSetup script:
- ensuring the configured inviting member has enough "invites" granted by the membership working group lead and has sufficient balance as well to send to newly invited members. The inviting member should not be the sudo account btw. Its preferable that a dedicated account be used.

**Comment by mnaamani** [comment]
the network deployment playbook already supports initial members input. However the query-node must be bootsrapped to function correctly when processing membership events. So we need the playbook to copy the same inital members.json to `query-node/mappings/src/bootstrap-data/data/members.json` and rebuild query-node before starting up query-node. (Shortcut would be after query-node is built as part of yarn build:packages would be to copy directly to `query-node/mappings/lib/src/bootstrap-data/data/members.json` but we loose type safety checks which ensures the format of the members.json is valid and as expected) 

The query-node feature to bootstrap members will be merged soon into olympia branch: https://github.com/Joystream/joystream/pull/3192
