### ISSUE TITLE
Storage installation bug: docker & query node issues

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3175]
(I don't fully understand the technical details of this issue, but since it exists and there's no issue for it I made this as a starting point)

The storage working group have encountered an issue with installation and running the Storage Node, while the storage system itself runs fine there is some apparent issue with the query node.

The problem appears to be that due to how the installation is done, or some configuration of it, it is difficult for storage providres to run their own Query Node.

From Discord:
- `IMPORTANT NOTE #1 Please pay attention you can skip Setup Query Node part of the guide . This part has some issues that we are still working on. For now you can use  https://hydra.joystream.org/graphql Graphql server.`
- `I still haven't figured out how to overcome the issue with Query Node (docker container doesn't see localhost), but the root problem seems to be  clear and I just need some more time to fix it.`
- `It doesn't work. Everything is fine when I use external URL like wss://ipfs.joystreamstats.live/endpoint but when it comes to localhost it stops working. I think that I need to adjust docker-compose.yml  as l1dev told me`

@bwhm replied with:
- `No, unfortunately it doesn't. Not because of any mistakes you made, but becuse the QN is running on docker, it doesn't work.`
- `localhost would have to be another docker container AFAIK`

**Comment by 0x2bc** [comment]
@freakstatic from Discord found out, that there are at least three ways how to overcome this issue with Query Nodes

- SP + Validator (validator running in a docker container)
- SP + Host Validator (validator running "natively") + iptables (to secure) + extra joystrem-nodes configs (--unsafe-ws-external)
- SP + Node (cannot be a validator) + extra joystrem-nodes configs (--ws-external )

**Comment by mochet** [comment]
Closing as very out of date
