### ISSUE TITLE
Structure of Joystream javasacipt library - Joystream.js

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/joystream#3183]
This aim of this issue is to discuss the structure of the Joystream javascript library/SDK `joystream.js` in monorepo. 
The current structure of monorepo looks like
```
joystream
├── cli
├── distributor-node
│   └── src
├── metadata-protobuf
├── node
│   └── src
├── query-node
├── runtime
├── runtime-modules
│   ├── blog
│   └── ...
├── scripts
├── storage-node
│   └── src
├── testnets
├── tests
│   ├── integration-tests
│   └── network-tests
├── types
└── utils
```

The structure of monorepo after adding new package `joystream.js` at the root of  repo would be: 

```
joystream
├── distributor-node
│   └── src
├── joystream.js
│   └── packages
│       ├── cli
│       ├── blog
│       ├── content
│       ├── ...
│       ├── working-group
│       ├── metadata-protobuf
│       └── types
├── node
│   └── src
├── query-node
├── runtime
│   └── src
├── runtime-modules
│   ├── blog
│   └── ...
├── scripts
├── storage-node
│   └── src
├── testnets
├── tests
│   ├── integration-tests
│   └── network-tests
└── utils
```

## Changes

- package/directory `cli`, `types` & `metadata-protobuf` will be moved from root of monorepo to `joystream.js` package. All the  TS/JS code to interact with the chain will exist in `joystream.js`. 
- much of the helper code such as account/api management  in `joystream/cli` will be reused in `joystream/joystream.js/packages/*`
- `joystream/joystream.js/packages/cli` would be much compact than `joystream/cli` 

## Benefits

- All JS/TS utilities will exist in one package
- Root level of monorepo will be more structured
- Only executable/functional units of code (and related utilities/integration tests) would exist at root level, e.g., `distributor-node`, `node`, `query-node`, `storage-node` etc.

Also the proposed structure is similar to the Javascript library/SDK of many projects in substrate ecosystem such as [subsocial](https://github.com/dappforce/subsocial-js) and [acala](https://github.com/AcalaNetwork/acala.js)

P.S. I have already added the basic structure in #3182

**Comment by bedeho** [comment]
I would suggest to avoid any broader reorganisation, this touches on so many other parts of the codebase, and despite me having very limited knowledge of many of these parts - I can still see a few problems.
