### ISSUE TITLE
DevOps - Olympia Deploy playground updates 2

### ISSUE THREAD

**Issue by ahhda** [Joystream/joystream#3187]
Some updates required to deploy playground workflow:

* The action should handle the flow being manually cancelled and delete cf stack
* Allow user to specify custom JSON which we will then pass to `yarn build:node:docker` as `ALL_PROPOSALS_PARAMETERS_JSON` while building the image on the instance
* Change endpoint from `{{ nip_domain }}/config.json` -> `{{ nip_domain }}/network/config.json`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201785009927821) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Can we add to the network/config.json file one field "stack_name" to be the cloud formation stack deployed. This will make it easier to identify the stack for admins to maintain on aws.

**Comment by mnaamani** [comment]
> * Allow user to specify custom JSON which we will then pass to `yarn build:node:docker` as `ALL_PROPOSALS_PARAMETERS_JSON` while building the image on the instance

As discussed this should be optional field, and if set the computed shasum for the build -> docker image tag should of `joystream/node` should cover these parameters similarly to how it is computed when `TEST_NODE=true` is set.

It would also be a good idea to save the .json file on the target machine for reference.
