### ISSUE TITLE
Olympia QN: Undeterministic ids

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3188]
A fix similar to https://github.com/Joystream/joystream/pull/3067 will be needed for Olympia due to not all entities having explicitly set, deterministic ids (ie. `UpcomingWorkingGroupOpening`). We may also consider fixing this issue on the [Hydra framework side as originally intended](https://github.com/Joystream/hydra/issues/399).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201785233700068) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Address by @ondratra in playground fix with updated version of hydra.
