### ISSUE TITLE
Olympia - Updates for setupNewChain scenario to support faucet init

### ISSUE THREAD

**Issue by ahhda** [Joystream/joystream#3196]
### Background
The `start.sh` script is used to startup services for a network using docker. It runs the scenario `INIT_CHAIN_SCENARIO` which is passed as an env variable. When the scenario is set to `setupNewChain`, it runs the script `tests/integration-tests/src/scenarios/setupNewChain.ts`. We need to update this to support faucet init in our scripts.

* Initialize membership working group (create a lead)
* Create a membership for a faucet account (get the ID and seed)
* Using that account give permission for faucet account to invite other members
* Faucet should work now (set `SCREENING_AUTHORITY_SEED` and `INVITING_MEMBER_ID` when running `docker-compose`)

Related to #3167

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201813591961948) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
> * Initialize membership working group (create a lead)

just noticed there is already a step in the scenario that sets up all the working group leads..(after the council)
```
const leads = job('Set WorkingGroup Leads', leaderSetup)
```

**Comment by mnaamani** [comment]
Two additional requirement for the invitations to work from the faucet:
- the faucet member accounts needs some funds for extrinsics 
- the membership working group to have a budget allocated.

**Comment by mnaamani** [comment]
Done in https://github.com/Joystream/joystream/pull/3283
