### ISSUE TITLE
Olympia Migration Plan

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#3207]
# Giza to Olympia state migration

## Membership
All members accounts will be migrated. There are three possible approaches:
- A:  Members can be injected in chainspec config file, and query-node bootstrapping. Bootstrapping QN is required because substrate cannot emit events at genesis and we cannot use mappings. (This is already implemented in QN)
- B: If we can configure substrate to emit events at genesis, then we can still use chain config to import users, but we need to update the `add_extra_genesis:build` function of the membership module to emit required events for each member being imported. If we cannot 
- C: Write a script to inject members with sudo/sudoAs extrinsics post launch to remove need to bootstrap query-node.

Approaches B and C simplify deployment of query-node . 
Taks:
- Update members [export script](https://github.com/Joystream/runtime-state-export-tools) to support Giza runtime.
- Look into possibility to configure substrate runtime
- If runtime events at genesis possible
    -  update runtime as per approach B
else
   - write script to inject members using membership.buyMembership with sudoAs, or by using invites. (Former approach preferred)

## Council
No initial council will be configured

## Initial balances
- Ensure weight to fee function -> returns 0 so tx fees will still be 0. (shamil)
- All accounts will be enumerated and total balances clipped at max value to be determined. (leszek or mohktar)

Tasks:
- write script to generate initial-balances.json file as input to chainspec builder.

## Forum data
Forum state will not be migrated.

Similar issue with respect to query-node bootstrapping, we can inject forum state but no events will be triggered and will require to write query-node bootstrapping code.
If we choose to import forum state at a later time we will need to write a script and sudoAs populate it.

Tasks
- [export script](https://github.com/Joystream/runtime-state-export-tools) will be used to export the forum state as a backup, but will not be used to initialize new olympia chain. (mokhtar) 

## Working groups
No genesis state (chain spec file) capability to setup initial working group state.
So new chain will have no initial leads or workers.

## Content
Content will be migrated.
Starting video and channel ids will be last values from giza at point of migration. (mokhtar)
Tasks
- Drop the migration code which deletes channels and videos (ignazio)
- Update content migration script used for sumer->giza (leszek) https://github.com/Joystream/joystream/issues/3181
   -  script will fetch content ahead of release date. 
- Channel and video Categories creation will be part of new content migration script 
video and channel migration .json artifact will be shared with Atlas team to merge with current one (to redirect urls from old ids to new ones on olympia)

## Storage
The storage pallets does not have genesis config option to allow us to have any pre-defined storage infrastructure setup at genesis. So storage lead will setup one storage node and one distributor node initially to migrate content.
   

## Runtime configuration
Most of the [runtime constants](https://github.com/Joystream/joystream/blob/olympia/runtime/src/lib.rs) for the new modules need to be fine tuned (martin)

Review Proposal Parameters [Defaults](https://github.com/Joystream/joystream/blob/olympia/runtime/src/proposals_configuration/defaults.rs)
Review Proposal Runtime Constants
Review Council Elections Parameters
Review Bounty Parameters
Review Membership constants
Review Blog constants
Review Working Group constants
Review Forum

Remember to update Query-Node initial corresponding values in:
- [membershipSystem](https://github.com/Joystream/joystream/blob/olympia/query-node/mappings/src/bootstrap-data/data/membershipSystem.json)
- [storageSystem](https://github.com/Joystream/joystream/blob/olympia/query-node/mappings/src/bootstrap-data/data/storageSystem.json)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201813162856559) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
## Memberships

> All members accounts will be migrated. There are three possible approaches:
>
>    A: Members can be injected in chainspec config file, and query-node bootstrapping. Bootstrapping QN is required because substrate cannot emit events at genesis and we cannot use mappings. (This is already implemented in QN)
>    B: If we can configure substrate to emit events at genesis, then we can still use chain config to import users, but we need to update the add_extra_genesis:build function of the membership module to emit required events for each member being imported. If we cannot
>    C: Write a script to inject members with sudo/sudoAs extrinsics post launch to remove need to bootstrap query-node.
>

I think we will always want to inject some state in the chainspec, which then requires bootstrapping on a new chain, as in A.
The events part seems not worth it to me. To simplify deployment for users:
- Keep all the state that needs to be injected in the "current" testnet in the `master` branch, and add a startup flag to the QN. eg:
```
--chain olympia 
# bootstraps olympia stuff

--chain playground
# bootstraps whatever is practical for our playground

...

--chain clean
# equivalent to omitting the flag, no state bootstrapped
```

## Council

> No initial council will be configured

Are we saying:
1. we'll set the first Council with `sudo`; OR
2. that we'll go through the first election before there are any CMs?

If 2: 
No proposals before a Council is set. We would have to `sudo` in some Leads to even have content.

Without going into too many details, if we assume same params as we currently have on Giza, we're talking ~10 days before a single Lead is hired

## Forum data
> Forum state will not be migrated.

> Similar issue with respect to query-node bootstrapping, we can inject forum state but no events will be triggered and will require to write query-node bootstrapping code.

Although this tool will presumably be needed at some point, I think it's ok to leave it be. However:

> If we choose to import forum state at a later time we will need to write a script and sudoAs populate it.

1. Unless this is injected in before anyone posts there, it's hard to imagine it'll make any sense. You'll get "old" posts after new ones, probably lots of duplicates etc.

2. If we migrate all of it at genesis, a large part of it will be completely irrelevant (such as old KPI discussions). What will be an actual is we'll have lots of "bad links", eg:
  - pioneer proposals from previous chains (not just the current), which would either mean:
    - accept these links not pointing to an actual proposals
    - add images of the proposal they link to
    - carry over Leszeks "old" proposal json files
      - for the latter two, we'd need to guess/calculate whether they point to the proposals in chain A, B or C...
  - videos, with incorrect IDs. **If these were migrated** through the various content resets, we could:
      - guess based on the timestamp which chain, then lookup which video (would only work most of the time)
      - have someone manually guess, or check whether our guesstimate was correct.
      - TL;DR lots of work for videos
  - memberships/handles
    - can be easily scripted, so not a big problem compared to the others

Instead, we could make it a KPI to have the community "choose" what to migrate at some level (by sub-category, category or posts). Won't be perfect, but better than all/nothing. Will still require migration tools, so I'm leaning towards not migrating this time (at least).

## Working groups

> No genesis state (chain spec file) capability to setup initial working group state.
> So new chain will have no initial leads or workers.

Agree, but see Council.

## Content

> Content will be migrated.
> Starting video and channel ids will be last values from giza at point of migration. (mokhtar)

Why not start at 1? For orion?

> script will fetch content ahead of release date.

Much like.

## Storage

> The storage pallets does not have genesis config option to allow us to have any pre-defined storage infrastructure setup at genesis. So storage lead will setup one storage node and one distributor node initially to migrate content.

I assume by `sudo`.

**Comment by mnaamani** [comment]
> > 
> 
> Are we saying:
> 
>     1. we'll set the first Council with `sudo`; OR
> 
>     2. that we'll go through the first election before there are any CMs?

I don't think option 1 is even possible in Olympia. cc: @shamil-gadelshin ?
Which would leave only option 2 yes, and therefore we would need to sudo in initial leads (after we inject initial members).

**Comment by mnaamani** [comment]
> > Content will be migrated.
> > Starting video and channel ids will be last values from giza at point of migration. (mokhtar)
> 
> Why not start at 1? For orion?

Mainly to not break Urls from twitter, discord to important channels and videos.

**Comment by mnaamani** [comment]
> > The storage pallets does not have genesis config option to allow us to have any pre-defined storage infrastructure setup at genesis. So storage lead will setup one storage node and one distributor node initially to migrate content.
> 
> I assume by `sudo`.

Yes @Lezek123 will re-factor the script we used for sumer -> giza

**Comment by mnaamani** [comment]
> * Look into possibility to configure substrate runtime

Shamil shared link to substrate docs stating that it is not possible: https://substrate.recipes/events.html#emitting-events

And its not clear there are any compiler/runtime config settings to change this behavior. For closure on this I will ask in substrate dev channel and update here again.

 cc: @bedeho

**Comment by mnaamani** [comment]
Member and Content migration scripts implemented in https://github.com/Joystream/joystream/pull/3239
