### ISSUE TITLE
Olympia: Util script to inject members with sudoAs

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#3224]
Ref https://github.com/Joystream/joystream/issues/3207
Write a utilily script to buy memberships with sudoAs for all exported members from giza.
Script should produce a simple json output with mapping from old member id to new member id. This will be a required input to the content migration script to correctly assign channels to their original owners.

As input use the exported members json format runtime-sate-export tools (updated for giza in https://github.com/Joystream/runtime-state-export-tools/pull/11)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201813444778425) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
@Lezek123 perhaps you can take this off my hands?

**Comment by Lezek123** [comment]
Done as part of https://github.com/Joystream/joystream/pull/3239
Note that no `sudoAs` is actually needed when buying a membership, as there doesn't need to be any relation between the sender and member controller/root account
