### ISSUE TITLE
Olympia: Drop migration code from content pallet

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#3225]
Drop runtime migration code (deleting channels and videos) from the content pallet.
If we ever need it again it can be added during a runtime upgrade.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201813360409279) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
Which one of the following are you pointing to:
A. Delete all the migration-related code & data structures
B. Just remove `ensure_migraton_done()` in runtime pallet and code in `on_runtime_upgrade` in order to avoid triggering migration

**Comment by mnaamani** [comment]
Both A, and B.
As a general point, for the olympia runtime there should really be nothing in `on_runtime_upgrade` since it is a new chain.
