### ISSUE TITLE
Olympia: BountyCreated and NftIssued event decoding fails 

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3231]
Due to `@polkadot/typegen` not supporting nested `BTreeSet` inside an `enum` type, I temporarly changed the definition of `AssuranceContractType` to:
```typescript
export class AssuranceContractType extends JoyEnum({
  Open: Null,
  Closed: Vec.with(MemberId), // FIXME: @polkadot/typegen Error: Enum: AssuranceContractType: Unhandled nested "BTreeSet"
}) {}
```

This caused issues when decoding `BountyCreated` event, for example:
```
Unable to retrieve the specified block details. Unable to decode storage system.events:: createType(Vec<EventRecord>):: Vec<EventRecord>:: Decoded input doesn't match input, received 0x1c00000000000000482d7c090000000002000000010000000000000000000000…000000000a0000000a000000000000020000000000d8f0e05000000000000000 (349 bytes), created 0x1c00000000000000482d7c090000000002000000010000000000000000000000…0000000000000000102700000000000000000000000000000010270000000000 (312 bytes)
```

### Trying out solutions

As an alternative I tried creating separate type for `AssuranceContractType_Closed`:
```typescript
export class AssuranceContractType_Closed extends BTreeSet.with(MemberId) {}

export class AssuranceContractType extends JoyEnum({
  Open: Null,
  Closed: AssuranceContractType_Closed,
}) {}
```

The type definitions were then correctly generated:
```
    "AssuranceContractType_Closed": "BTreeSet<MemberId>",
    "AssuranceContractType": {
        "_enum": {
            "Open": "Null",
            "Closed": "AssuranceContractType_Closed"
        }
    },
```

However some issues still seem to occur when trying to create a bounty with `AssuranceContractType: Closed`:

![image](https://user-images.githubusercontent.com/19978260/154045517-f15a1e17-4ddc-4144-9411-5588027c72cd.png)

As you can notice - even though the `BountyCreationParameters` seem valid, the actual `bounty.createBounty` call cannot be decoded:

```
Error: createType(Call):: Call: failed decoding bounty.createBounty:: Struct: failed on args: {"params":"BountyCreationParameters","metadata":"Bytes"}:: decodeU8a: failed at 0x010d0000000000000001040c00000000… on params: {"oracle":"BountyActor","contract_type":"AssuranceContractType","creator":"BountyActor","cherry":"u128","entrant_stake":"u128","funding_type":"FundingType","work_period":"u32","judging_period":"u32"}:: decodeU8a: failed at 0x0d000000000000001027000000000000… on creator: {"_enum":{"Council":"Null","Member":"MemberId"}}:: Unable to create Enum via index 13, in Council, Member
    at h (https://polkadot.js.org/apps/polkadot.01.ffe3845b.js:1:153982)
    at F.createTypeUnsafe (https://polkadot.js.org/apps/polkadot.01.ffe3845b.js:1:177655)
    at F.createType (https://polkadot.js.org/apps/polkadot.01.ffe3845b.js:1:177596)
    at Gde.<anonymous> (https://polkadot.js.org/apps/main.37f923a8.js:19:123888)
    at https://polkadot.js.org/apps/main.37f923a8.js:19:109509
    at new Promise (<anonymous>)
    at Gde.signPayload (https://polkadot.js.org/apps/main.37f923a8.js:19:109481)
    at Object.#O (https://polkadot.js.org/apps/polkadot.01.ffe3845b.js:1:85925)
    at https://polkadot.js.org/apps/polkadot.01.ffe3845b.js:1:84935
    at v (https://polkadot.js.org/apps/other.01.debe181d.js:2:127999)
```

This happens even though there is only one value in the `BTreeSet` (so doesn't seem related to ordering)

### Other solutions

Since I couldn't find a solution on the `@joystream/types` side, I suggest changing `AssuranceContractType_Closed` variant to `Vec<MemberId>` in the runtime, which will be consistent with other similar enum: [`ThreadMode`](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/proposals/discussion/src/types.rs#L39)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201829562328817) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Thanks for excellent investigation and write up.
Since there is no clear workaround we don't seem to have a choice.

@shamil-gadelshin as the original author of the bounty module could you make the required changes in the bounty pallet?

Perhaps also worth scanning if there any other enum types with variants enclosing a btreeset?

**Comment by Lezek123** [comment]
Here is a map of types that currently contain/are `BTreeSet`s / `BTreeMap`s:

**Aliases for `BTreeSet`s, not used inside any `Struct` / `Enum`:**
- `DataObjectIdSet`
- `DataObjectIdMap`
- `StorageBucketIdSet`
- `DistributionBucketIndexSet`
- `ContentIdSet`
- `ModeratorSet`
- `ApplicationIdSet`

**Aliases for `BTreeMap`s, not used inside any `Struct` / `Enum`:**
- `PostsToDeleteMap`
- `DataObjectIdMap`
- `DynamicBagCreationPolicyDistributorFamiliesMap`
- `ApplicationIdToWorkerIdMap`

**`BTreeMap`s inside `Struct`:**

- `DynamicBagCreationPolicy.families` (`DynamicBagCreationPolicy` itself is not part of any `Enum` / `Struct`)
- `Entry.oracle_judgment_result` (`OracleJudgment` is alias for `BTreeMap`. `Entry` itself is not part of any `Enum` / `Struct`)

**`BTreeSet` inside `Enum` (directly):**

- _**!!! `AssuranceContractType.Closed`**_

**`BTreeSet` inside `Struct`:**

- `Bag.stored_by`, `Bag.distributed_by` (`Bag` itself is not part of any `Enum` / `Struct`)
- `DistributionBucket.pending_invitations`, `DistributionBucket.operators` (`DistributionBucket` itself is not part of any `Enum` / `Struct`)
- _**!!! `Auction.whitelist` (`Auction` is part of `TransactionalStatus` enum!)**_
- _**!!! `AuctionParams.whitelist` (`AuctionParams` is part of `InitTransactionalStatus` enum)**_
- `CuratorGroup.curators` (`CuratorGroup` itself is not part of any `Enum` / `Struct`)
- `Channel.collaborators`, `Channel.moderators` (`Channel` itself is not part of any `Enum` / `Struct`)
- `ChannelCreationParameters.collaborators`, `ChannelCreationParameters.moderators` (`ChannelCreationParameters` is not part of any `Enum` / `Struct`)
- `ChannelUpdateParameters.assets_to_remove`, `ChannelUpdateParameters.collaborators` (`ChannelUpdateParameters` is not part of any `Enum` / `Struct`)
- `VideoUpdateParameters.assets_to_remove` (`VideoUpdateParameters` is not part of any `Enum` / `Struct`)

**Comment by Lezek123** [comment]
Confirmed that decoding issues also occur for `NftIssued` event, which includes `InitTransactionalStatus`:
```
Unable to retrieve the specified block details. Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x0002000000191f010d00000000000000…: {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x191f010d000000000000000100000000… on event: {"index":"EventId","data":"Null"}:: Struct: failed on data: :: decodeU8a: failed at 0x00000201050000001400000000000000…:: decodeU8a: failed at 0x00000201050000001400000000000000… on magicNumber: u32:: MagicNumber mismatch: expected 0x6174656d, found 0x01020000
```

**Comment by bedeho** [comment]
Amazing work on that enumeration of cases (no pun intended :P) !

**Comment by Lezek123** [comment]
The issue with `NftIssued` seems to be actually something unrelated to `BTreeSet`. It occurs because the [runtime is using `Metadata` alias for `Vec<u8>`](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/content/src/nft/types.rs#L4) and then [as part of `NftIssued` event](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/content/src/lib.rs#L2224).

`Metadata` is a reserved typename in `@polkadot/types` which has a special meaning (it's used do decode chain metadata)

**Comment by Lezek123** [comment]
The issue with `BountyCreated` on the other hand turned out to be caused by `BountyId` type mismatch (`u64` in the runtime vs `u32` in `@joystream/types`) :man_facepalming: 

So even though both events had something to do with `BTreeSet` encoded inside `enum`, in both cases the issue was actually caused by something else.

**Comment by bedeho** [comment]
Awesome, best news we could hope for! Sorry it took you so much time to chase that down. 

How could this have been avoided, or reduced the likelihood of happening in the future, or make easier to find accurate cause?

**Comment by Lezek123** [comment]
> How could this have been avoided or reduced the likelihood of happening in the future or make easier to find accurate cause

Issues related to type mismatches between the runtime and `@joystream/types` will be gone once we upgrate to [Substrate version which includes type definitions in the runtime metadata](https://github.com/paritytech/substrate/releases/tag/monthly-2021-10)

For now I think only extra care should taken when updating `@joystream/types`. Since it is not very complicated task, perhaps it should be a common practice to update types along with the runtime. This way we can examine & compare both within the same PR and we lower the risk of missing some required adjustments to `@joystream/types` once the runtime types change.

In this particular case I was a bit misled by what I assumed to be the most probable cause, but it's true that those issues are not easy to debug, because if one type is not defined correctly it may cause a decoding error way further down the binary line.

Usually what I'd do is check the definitions of all the types beeing part of, for example, an event that caused an error. In that case, however, I found a potential issue in `AssuranceContractType`, while real cause was `BountyId`.

We could make a script that could attempt to check the definitions against the runtime code, but this is a non-trivial task and the further we go down this road the more we re-invent the wheel, given that types are already part of the runtime metadata in the latest version of Substrate (as I mentioned at the beginning)

**Comment by Lezek123** [comment]
Closing the issue, since the fix is already merged (https://github.com/Joystream/joystream/pull/3268)
