### ISSUE TITLE
Storage based constitution proposal

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3232]
# Background
Right now, we have a proposal to update the constitution, and it just stored the data in the ledger directly. If the meaning of the message is just set to `here is the new constitution`, then we may risk running into block weight constraints of what will eventually end up as a very large blob of text, even if compressed.

# Question
Should we just instead have the constitution stored in storage bag of council?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202207160813988) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
update / this can be closed because the constitution pallet is unused and will probably be removed: https://github.com/Joystream/joystream/issues/4247

**Comment by kdembler** [comment]
Closing because of the above
