### ISSUE TITLE
Olympia (staging): Testing Parameters and Configurations

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#3242]
We'll have a "public" network, with two `invuls` and a query-node.
Besides `sudo` and `endowed` key(s), no state imported.

## Parameters
These are needed for the testers.

### Proposal Parameters
From: `runtime/src/proposals_configuration/defaults.rs`

| proposalType                                        | Voting P | Grace P | Appr. Q % | Appr. T % | Slash. Q % | Slash. T % | Req. Stake | Const. |
|-----------------------------------------------------|----------|---------|-----------|-----------|------------|------------|------------|--------|
| set_max_validator_count_proposal                    | 200      | 0       | 66        | 80        | 60         | 80         | 100000     | 1      |
| runtime_upgrade_proposal                            | 200      | 200     | 80        | 100       | 60         | 80         | 1000000    | 1      |
| signal_proposal                                     | 200      | 0       | 60        | 80        | 60         | 80         | 25000      | 1      |
| funding_request_proposal                            | 200      | 100     | 60        | 80        | 60         | 80         | 25000      | 1      |
| create_working_group_lead_opening_proposal          | 200      | 0       | 60        | 80        | 60         | 80         | 100000     | 1      |
| fill_working_group_lead_opening_proposal            | 200      | 0       | 60        | 75        | 60         | 80         | 50000      | 1      |
| update_working_group_budget_proposal                | 200      | 0       | 60        | 75        | 60         | 80         | 50000      | 1      |
| decrease_working_group_lead_stake_proposal          | 200      | 0       | 60        | 75        | 60         | 80         | 50000      | 1      |
| slash_working_group_lead_proposal                   | 200      | 0       | 60        | 75        | 60         | 80         | 50000      | 1      |
| set_working_group_lead_reward_proposal              | 200      | 0       | 60        | 75        | 60         | 80         | 50000      | 1      |
| terminate_working_group_lead_proposal               | 200      | 0       | 66        | 80        | 60         | 80         | 100000     | 1      |
| amend_constitution_proposal                         | 200      | 100     | 80        | 100       | 60         | 80         | 1000000    | 2      |
| cancel_working_group_lead_opening_proposal          | 200      | 0       | 60        | 75        | 60         | 80         | 50000      | 1      |
| set_membership_price_proposal                       | 200      | 100     | 60        | 75        | 60         | 80         | 50000      | 1      |
| set_council_budget_increment_proposal               | 200      | 100     | 66        | 80        | 60         | 80         | 200000     | 1      |
| set_councilor_reward_proposal                       | 200      | 100     | 66        | 80        | 60         | 80         | 200000     | 2      |
| set_initial_invitation_balance_proposal             | 200      | 100     | 60        | 75        | 60         | 80         | 50000      | 1      |
| set_membership_lead_invitation_quota_proposal       | 200      | 100     | 60        | 75        | 60         | 80         | 50000      | 1      |
| set_referral_cut_proposal                           | 200      | 100     | 60        | 75        | 60         | 80         | 50000      | 1      |
| set_invitation_count_proposal                       | 200      | 100     | 60        | 75        | 60         | 80         | 50000      | 1      |
| create_blog_post_proposal                           | 200      | 100     | 60        | 80        | 60         | 80         | 25000      | 1      |
| edit_blog_post_proposal                             | 200      | 100     | 60        | 80        | 60         | 80         | 25000      | 1      |
| lock_blog_post_proposal                             | 200      | 100     | 60        | 80        | 60         | 80         | 25000      | 1      |
| unlock_blog_post_proposal                           | 200      | 100     | 60        | 80        | 60         | 80         | 25000      | 1      |
| veto_proposal_proposal                              | 200      | 0       | 75        | 80        | 60         | 66         | 1000000    | 1      |

Source: `runtime/src/proposals_configuration/defaults.rs`

**Notes**
- All voting periods changed
- Many/most (non-zero) grace periods changed
- `set_councilor_reward_proposal` constitutionality changed

### Council + Referendum
From: `runtime/src/lib.rs`

| Param                      | Type        | Value | Edit |
|----------------------------|-------------|-------|------|
| MaxSaltLength              | u64         | 32    |      |
| VoteStageDuration          | BlockNumber | 100   | x    |
| RevealStageDuration        | BlockNumber | 50    | x    |
| MinimumVotingStake         | u64         | 10000 |      |
| MinNumberOfExtraCandidates | u64         | 1     |      |
| AnnouncingPeriodDuration   | BlockNumber | 200   | x    |
| IdlePeriodDuration         | BlockNumber | 400   | x    |
| CouncilSize                | u64         | 5     | x    |
| MinCandidateStake          | u64         | 11000 |      |
| ElectedMemberRewardPeriod  | BlockNumber | 10    |      |
| DefaultBudgetIncrement     | u64         | 1000  |      |
| BudgetRefillPeriod         | BlockNumber | 1000  |      |
| MaxWinnerTargetCount       | u64         | 10    |      |

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201838271839464) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
For the `veto_proposal_proposal` does it really make sense for the voting period to be longer than the longest grace period of all other proposals?

Updating in https://github.com/Joystream/joystream/pull/3252 needs to fix the tests that have made assumptions about the voting and grace periods.

**Comment by mnaamani** [comment]
Done in https://github.com/Joystream/joystream/pull/3252
