### ISSUE TITLE
QN Channel Payouts

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3264]
Best reference is here 

https://github.com/Joystream/joystream/issues/3263

Will include

* Supprt new council proposals.
* Updating schemas to reflect built in channels, e.g. events and 
* Support claim reward extrinsic on channel
* Support cashout extrinsic on channel

>DM: Issues raised already:
![](https://user-images.githubusercontent.com/93924525/168599690-e602366a-b2a4-469a-92d8-e2f159533ec5.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202453807621332) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@zeeshanakram3

## Atlas
First we will be aiming to implement the MVP version of the Payouts on Atlas, which only has 3 basic widgets and payouts history table, here's the link to the designs:
[FIGMA> ](https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=1580%3A22983)

## Pioneer
☝️  There are several proposals for the payouts, not just one where [payload submitted]([Figma>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9707%3A349318)), but also separate ones for [min/max payouts:]([Figma min/max>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9741%3A372154))

Respective tickets:
- https://github.com/joystream/pioneer/issues/3073
- https://github.com/joystream/pioneer/issues/3208

⚠️  Before the implementation pls see this runtime issue as well:
- https://github.com/Joystream/joystream/issues/3263
