### ISSUE TITLE
Unnecessary duplicated NFT transactional status type?

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3267]
Currently the runtime has 2 separate types representing NFT's transactional status:
a) `InitTransactionalStatus` - used as parameter in `NftIssuanceParameters` type, used in `content.issueNft` extrinsic
a) `TransactionalStatus` - not used in any extrinsic

Those are the types in the `@joystream/types` library:

```tsx
declare const InitTransactionalStatus_base: import("../JoyEnum").ExtendedEnumConstructor<{
    Idle: typeof Null;
    InitiatedOfferToMember: import("@polkadot/types/types").Constructor<Tuple>;
    Auction: typeof AuctionParams;
}>;

declare const TransactionalStatus_base: import("../JoyEnum").ExtendedEnumConstructor<{
    Idle: typeof Null;
    InitiatedOfferToMember: import("@polkadot/types/types").Constructor<Tuple>;
    Auction: typeof Auction;
    BuyNow: typeof Balance;
}>;
```

There are 2 possible issues:
1. `InitTransactionalStatus` lacks an option to use `BuyNow` status
2. Are both of those types really necessary? Seems like the duplication is the cause for the 1. issue, if we manage to use a single type we make sure they are always in sync. The same issue exists for `Auction` and `AuctionParams` type

**Comment by bedeho** [comment]
1. So the BuyNow is just an oversight, should have been there.
2. I can only speak of the runtime, assuming these types are perfect reflections of that. `Auction` is not the same as `AuctionParams`, the former holds all the state of an actual live auction, the latter holds only what you need to _start_ an auction.

Here is an `Auction`

```Rust
pub struct AuctionRecord<...> {
    pub starting_price: Balance,
    pub buy_now_price: Option<Balance>,
    /// Auction type (either english or open)
    pub auction_type: AuctionType<BlockNumber>,
    pub minimal_bid_step: Balance,
    pub last_bid: Option<Bid<MemberId, AccountId, BlockNumber, Balance>>,
    pub starts_at: BlockNumber,
    pub whitelist: BTreeSet<MemberId>,
}
```

this clearly has stuff in there that does not have anything to do with creation, like `last_bid`, and here you have the latter

```Rust
pub struct AuctionParams<BlockNumber, Balance, MemberId: Ord> {
    // Auction type (either english or open)
    pub auction_type: AuctionType<BlockNumber>,
    pub starting_price: Balance,
    pub minimal_bid_step: Balance,
    pub buy_now_price: Option<Balance>,
    pub starts_at: Option<BlockNumber>,
    pub whitelist: BTreeSet<MemberId>,
}
```

so quite similar, but not identical, and for a sound reason: they represent different things.

**Comment by kdembler** [comment]
All right, thanks for a clarification
