### ISSUE TITLE
Question/problem: How to check query node status externally?

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3271]
# Problem

Query Nodes seem to have at least a few reliability issues right now (👷) and it seems like there isn't any way for someone without server access to the QN to check what its sync status is (i.e. what is the most recent blockheight processed). I could be wrong, but just using what I know to describe this!

Via graphql there does seem to be an option for this: https://olympia-staging-a2.joystream.app/server/graphql
```
stateSubscription: ProcessorState!
type ProcessorState {
lastCompleteBlock: Float!
lastProcessedEvent: String!
indexerHead: Float!
chainHead: Float!
}
```

However running this results in the following error:
```
{
  "error": "Could not connect to websocket endpoint ws://localhost:8081/graphql. Please check if the endpoint url is correct."
}
```

Alternatively if I try this via https://3.93.173.102.nip.io/query-node/indexer/graphql I get the following error:
```
{
  "error": "Could not connect to websocket endpoint wss://3.93.173.102.nip.io/graphql. Please check if the endpoint url is correct."
}
```

Via the indexer URL it is possible to run the following (which works), it is just unclear if this can be relied upon when accessing the query node:
```query{
  indexerStatus{head}
}
```

# Questions
1. Is using `indexerStatus` via the indexer URL as good as the Query Node's status? Or would `indexerStatus` be unreliable for determining current sync?

# Solution
1. Either have `stateSubscription` work, or
2. Have some public facing URL from each QN that shows its status (something like https://status.joystream.org/status)

# Reason
Besides the benefits given when troubleshooting, the other benefit with solving this would be that a UI can be made which shows the current "network" of QNs and shows which are currently having issues.

**Comment by bedeho** [comment]
> and it seems like there isn't any way for someone without server access to the QN to check what its sync status is

This def. can't be true, because Atlas already has the behavior that when the user is making a transaction, such as when making a channel, it blocks the user in a modal until it confirms that the query node has processed the block in which this transaction was included. I also believe Pioneer has been built to have a progress indicator type dialogue which shows similar processing information about the query node.

> However running this results in the following error:

Yeah not sure what that is about, but I think this is what should work.

> Is using indexerStatus via the indexer URL as good as the Query Node's status? Or would indexerStatus be unreliable for determining current sync?

The query node has two distinct parts, indexer and processor. The indexer does not know anything about what blocks have been _processed_, and this is what you really care about. It is only when a block has been processed that the GraphQL API will reflect whatever happened in that block. The query

**Comment by traumschule** [comment]
How can i use this on https://orion.joystream.org/graphql or https://hydra.joystream.org/graphql?

https://github.com/Joystream/atlas/blob/master/packages/atlas/src/api/queries/queryNode.graphql
```
subscription GetQueryNodeState {
  stateSubscription {
    chainHead
    indexerHead
    lastCompleteBlock
    lastProcessedEvent
  }
}
```

**Comment by mnaamani** [comment]
> > However running this results in the following error:
> 
> Yeah not sure what that is about, but I think this is what should work.

I think the reason why the subscription endpoints seem wrong in the graphql playground was due to a bug which was fixed for Giza in https://github.com/Joystream/joystream/pull/2986 - I wonder if that got lost in Olympia? cc: @ondratra @Lezek123

**Comment by traumschule** [comment]
> I think the reason why the subscription endpoints seem wrong in the graphql playground was due to a bug which was fixed for Giza in https://github.com/Joystream/joystream/pull/2986

It is also not working in Giza Playgrounds like the ones mentioned [above](#issuecomment-1046090154) and https://joystreamstats.live/graphql (not yet balanced)

**Comment by ondratra** [comment]
> > > However running this results in the following error:
> > 
> > 
> > Yeah not sure what that is about, but I think this is what should work.
> 
> I think the reason why the subscription endpoints seem wrong in the graphql playground was due to a bug which was fixed for Giza in #2986 - I wonder if that got lost in Olympia?

Both issues related to Playground endpoint address will likely be interconnected, and some regression happened for the Playground. 
https://github.com/Joystream/joystream/pull/2986, https://github.com/Joystream/joystream/pull/2967, and maybe others are related to this, and their impact needs further investigation. The problem is not exclusive to Olympia, as @traumschule noted. I'll prepare a fix for that.

**Comment by mochet** [comment]
Closed as solved.
In case anyone stumbles upon this page via Google in many years time, it took me a very long time to find the solution to this:
`subscription
	{stateSubscription
    	{lastCompleteBlock,lastProcessedEvent,indexerHead,chainHead}
  }`

Notes:
* It doesn't work on Query Nodes by default for some reason
* Only JSG's QN appears to be able to run it
* It will put out data like the following:
`{
  "data": {
    "stateSubscription": {
      "lastCompleteBlock": 1311094,
      "lastProcessedEvent": "0001311093-000001-fe11a",
      "indexerHead": 1311094,
      "chainHead": 1311094
    }
  }
}`
* It will update with every block that gets processed
* It can be run directly on the Query Node and doesn't require using the indexer or anything else, i.e. it can be input here: https://query.joystream.org/graphql

**Comment by traumschule** [comment]
> subscription {stateSubscription {lastCompleteBlock,lastProcessedEvent,indexerHead,chainHead} }

@mnaamani is there a trick other QN operators need to apply to make this work?
could just be a caddy/nginx configuration to enable websocket?
```
{
  "error": "Could not connect to websocket endpoint wss://de.joystreamstats.live/graphql. Please check if the endpoint url is correct."
}
```

**Comment by mochet** [comment]
> > subscription {stateSubscription {lastCompleteBlock,lastProcessedEvent,indexerHead,chainHead} }
> 
> @mnaamani is there a trick other QN operators need to apply to make this work? could just be a caddy/nginx configuration to enable websocket?
> 
> ```
> {
>   "error": "Could not connect to websocket endpoint wss://de.joystreamstats.live/graphql. Please check if the endpoint url is correct."
> }
> ```

I believe in the graphql server variables there is some part of the config that stops it from happening, but I never looked deeply into it.

**Comment by Lezek123** [comment]
Do you have `GRAPHQL_PLAYGROUND_SUBSCRIPTION_ENDPOINT=wss://de.joystreamstats.live/graphql`?
It's either about adjusting this variable or reverse proxy configuration.

**Comment by traumschule** [comment]
> Do you have GRAPHQL_PLAYGROUND_SUBSCRIPTION_ENDPOINT=wss://de.joystreamstats.live/graphql?

It was set to localhost, changed to public url and restarted container.
```
joystream@de:~/joystream$ docker-compose logs graphql-server
Attaching to graphql-server
graphql-server           | yarn workspace v1.22.19
graphql-server           | yarn run v1.22.19
graphql-server           | $ yarn workspace query-node start:prod
graphql-server           | $ WARTHOG_ENV=production yarn dotenv:generate && node dist/src/index.js
graphql-server           | $ dotenvi -s ${WARTHOG_ENV:-development}
graphql-server           | Writing output file to /joystream/query-node/generated/graphql-server/.env
graphql-server           | '🚀 Server ready at https://localhost:8081/graphql'
```
.env
```
GRAPHQL_SERVER_PORT=8081

# Query node playground endpoint
# Leave it blank if you want endpoint to be copied from browser's URL
GRAPHQL_PLAYGROUND_ENDPOINT=

# Query node playground subscription endpoint - will be derived from GRAPHQL_PLAYGROUND_ENDPOINT
# when not set
GRAPHQL_PLAYGROUND_SUBSCRIPTION_ENDPOINT="https://de.joystreamstats.live/graphql"

# URL for CDN serving QN Playground's JS/CSS files - set empty string for local file serving
GRAPHQL_PLAYGROUND_CDN_URL=""
```

Are you familiar with these - happens running from inside query-node dir:
```
joystream@de:~/joystream/query-node$ docker-compose logs graphql-server
ERROR: The Compose file './../docker-compose.yml' is invalid because:
services.db.ports contains an invalid type, it should be a number, or an object
services.graphql-server.ports contains an invalid type, it should be a number, or an object
services.hydra-indexer-gateway.ports contains an invalid type, it should be a number, or an object
```

> It's either about adjusting this variable or reverse proxy configuration.

nginx:
```
    location /graphql {
      proxy_pass http://localhost:8081;
      proxy_set_header Access-Control-Allow-Methods "GET, PUT, HEAD, OPTIONS";
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      proxy_set_header    X-Real-IP $remote_addr;
    }
```

> It can be run directly on the Query Node and doesn't require using the indexer or anything else, i.e. it can be input here: https://query.joystream.org/graphql

Just noticed that one fails too  now.
>   "error": "Could not connect to websocket endpoint wss://query.joystream.org/graphql. Please check if the endpoint url is correct."

**Comment by mochet** [comment]
> Just noticed that one fails too now.

That was probably just due to periodic downtime as it works again now.

**Comment by traumschule** [comment]
Not for me, maybe we catch different instances. Also noticed the correct setting is `https` instead of `wss` or normal queries will fail too.
> GRAPHQL_PLAYGROUND_SUBSCRIPTION_ENDPOINT="https://de.joystreamstats.live/graphql"

**Comment by traumschule** [comment]
> {
>   "error": "Could not connect to websocket endpoint wss://de.joystreamstats.live/graphql. Please check if the endpoint url is correct."
> }

The graphql-server log shows:
```
[
  'Unauthorized access on /update-processor-state: 72.1.10.70 (expected: ::1)'
]
```
[Joystream/hydra/blob/master/packages/hydra-cli/src/templates/graphql-server/src/processorStateApp.ts.mst#L63](https://github.com/Joystream/hydra/blob/master/packages/hydra-cli/src/templates/graphql-server/src/processorStateApp.ts.mst#L63)
```
  if (processorHost !== '*') {
    app.use((req, res, next) => {
      lookup(processorHost)
        .then(({ address }) => {
          if (req.ip !== address) {
            Logger.warn(
              `Unauthorized access on /update-processor-state: ${req.ip} (expected: ${address})`
```

Solution:
Set `PROCESSOR_HOST=` to `req.ip` and restart the graphql-server.

<img width="1833" height="1003" alt="Image" src="https://github.com/user-attachments/assets/cb827c71-3668-4e22-b14e-6cb09c42d249" />
cc #5214
