### ISSUE TITLE
Update NFT mappings for initial BuyNow feature

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3278]
Accomodate https://github.com/Joystream/joystream/issues/3277

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201858542017604) by [Unito](https://www.unito.io)

**Comment by ondratra** [comment]
Related to https://github.com/Joystream/joystream/issues/3267 . Requires https://github.com/Joystream/joystream/issues/3277 to be implemented first.
