### ISSUE TITLE
Disable NFT issuance

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3286]
Make it impossible to issue an NFT, this should be both during video creation, or as a separate step, it should just not be possible. All other extrinsics realted to NFTs do not need to be altered, as they all assume an NFT exists.

This is to limit the likelihood of having to do migrations when we do certain changes to how NFTs work on the runtime side in the near future: https://github.com/Joystream/joystream/issues/3285

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201866718179361) by [Unito](https://www.unito.io)

**Comment by ondratra** [comment]
Extrinsics that can issue a NFT are: `create_video()`, `update_video()`, and `issue_nft()`.
