### ISSUE TITLE
NFT query node - use `topBid` instead of `lastBid`

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3305]
Currently there is `Auction.lastBid` field that mirrors what is a last bid in the runtime. However, if you take into account changes to open auction we're making (https://github.com/Joystream/joystream/issues/3285), there will no longer be a single last bid, instead the runtime will have a list of bids (max 1 per member). Once this change happens, I propose we update the QN schema to have a `topBid` field instead, that would represent the highest bid made on this auction. For english auctions, there would still be only a single bid (the winning one).

WDYT @ondratra?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201899831821015) by [Unito](https://www.unito.io)

**Comment by ondratra** [comment]
Ok. I like the `topBid` name better for the use.

**Comment by bedeho** [comment]
This will be tricky to maintain, since bids can disappear, and you have to then find biggest alternative bid, etc. One can also just query the actual bids which are active for a given NFT, as we will need a new entity type for bids, and then pick the biggest one client side. Would that not be sufficient?

**Comment by kdembler** [comment]
Is it tricky to maintain? I think we would only need to update in 2 cases:
- new bid appeared and it's higher than the current `topBid`
- bid was cancelled and it was the current `topBid`

We could do this client side given list of all the bids, but we want to display info on top bid in grids of NFTs (think all NFTs owned by a member) and I would like to avoid fetching all the bids for all those NFTs, it would be much more convenient if the top bid was available directly

**Comment by bedeho** [comment]
Its not super tricky, but any extra state is just a disaster waiting to blow up, but sure, you make a good case.
