### ISSUE TITLE
Question: Council blog feature status

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3308]
According to this: https://github.com/Joystream/joystream/issues/3255#issue-1141138718
The council blog feature may be removed

For clarification on this speecific issue:
- Does this mean the entire feature would be removed? or it would just be an adjustment of it?
- If so, why? Technical or social reasons?

**Comment by bedeho** [comment]
- This does not make sense as a standalone pallet.
- It can be done using metaprotocols, but I don't think we would invest effort in that.
- It also requires UX/UI work to make a functional experience, we def. are not able to invest effort in that.

**Comment by mochet** [comment]
Closed as council blog will not exist anymore.
