### ISSUE TITLE
Missing Bounty type

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3311]
The `treasury` pallet in Substrate already has a `Bounty` type, which is defined in `@polkadot/api`: https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/treasury/definitions.ts#L12

This is why missing `Bounty` type in `@joystream/types` didn't cause any warning, but results in decoding errors (ie. when trying to read `bounty.bounties` map).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201880354001253) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
🤣

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/3328
