### ISSUE TITLE
Update BuyNow price

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3315]
There is no way to update the buy now price if the NFT is already in `BuyNow` state, this is really needed for apps.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201899805689076) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
@bedeho @ignazio-bovo Maybe we should also allow updating fixed price of an ongoing auction? Or do we stick to just `BuyNow`?

**Comment by ignazio-bovo** [comment]
It can be accomodate that, but it is not trivial (i.e. will require some small redesign)

**Comment by dobertRowneySr** [comment]
> @bedeho @ignazio-bovo Maybe we should also allow updating fixed price of an ongoing auction? Or do we stick to just `BuyNow`?

It can be accommodated, but it is not trivial (i.e. will require some small redesign)

**Comment by kdembler** [comment]
Ah, I would skip it then

**Comment by toiletgranny** [comment]
To be sure, @ignazio-bovo and @bedeho, is my understanding correct that for me, as an NFT owner, to change the buy now price would be only possible if the NFT is on sale for a fixed price only? 

For example, when I'm selling my NFT in an open/english auction with an additional fixed price, does it mean that the fixed price can not be changed without me canceling the sale first?

**Comment by bedeho** [comment]
>  Maybe we should also allow updating fixed price of an ongoing auction? Or do we stick to just 

What is this _fixed price_ ? there is _buy now_ price in both kinds of auctions, as described here

https://joystream.gitbook.io/testnet-workspace/system/content-directory/nft#auction-type

but apparently you are not referring to this, so I am not following.

In general I would say we have to draw the line with these very late changes, so I would say _no_. I

> to change the buy now price would be only possible if the NFT is on sale for a fixed price only

I don't think there is. It doesn't immediately seem that hard to add, except for the issue that if you are updating the buy now to some amount lower than a current bid (which sort of counter productive), then you are left in a weird state, because the blockchain is unable to computationally go and search through all existing bids to see if any are lower than the new buy now amount.

Is there any other problem @ignazio-bovo ?

**Comment by kdembler** [comment]
@bedeho We use "buy now price" and "fixed price" interchangeably I think.

So what I meant here:
> @bedeho @ignazio-bovo Maybe we should also allow updating fixed price of an ongoing auction? Or do we stick to just BuyNow?

Is whether we want to allow modifying `buyNowPrice` parameter of an active auction. If it is tricky in any way, I would suggest we skip it to not introduce too many runtime changes at this point.

@toiletgranny 👆 means:
a) if there is no auction, only buy now, you can change your listing price
b) if there is an auction, you can only cancel it and start a new one if you need different params

Sounds good?

**Comment by bedeho** [comment]
> I would suggest we skip it to not introduce too many runtime changes at this point.

Agreed.
