### ISSUE TITLE
Olympia playground: Broken elections/referendum in runtime

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3319]
It appears on the current Olympia playground (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F3.87.51.41.nip.io%2Fws-rpc#) that elections are broken.

I'm a bit exhausted but will try to summarize what I understand right now (I would usually include links to every block but I want to make sure the basic information is recorded):

## Problem
* The initial council was set via a script which had 7 people apply in a single block, 5 succeeded and 2 failed
* Announcing periods keep happening and failing because of no applicants
* Any applicant that applies get discarded as soon as a new announcing period starts
* Many applicants have applied in elections and no election has reached the voting phase. I've applied using dozens of different keys and no election has actually taken place at this stage.
* The CLI returns malformed data when querying certain candidates (people who haven't applied get a working response, people who have applied get a broken response)
 ![image](https://user-images.githubusercontent.com/50830161/155866272-ec68df26-6b23-4b25-898f-8b2545b1744b.png)
* Can't release candidacy on certain accounts
![image](https://user-images.githubusercontent.com/50830161/155866306-bbc5e5b7-1574-4ed2-8d90-dc4b89a082ef.png)
* Votes for applicants from certain accounts do and do not exist depending on blockheight
* 

(some information from the query node)

1. block 3400 - election failed `NOT_ENOUGH_CANDIDATES`
1. block 3600 - election succeed (`"electionProblem": null`)
1. block 3750 - (`"electionProblem": null`) -- this should NOT have happened, there were no candidates!
1. block 4150 - (`"electionProblem": null`) -- this should NOT have happened, there were no candidates!
1. block 3400 - election failed `NOT_ENOUGH_CANDIDATES`

(some other information I think I got from the query node)

1. block 3600 - referendum started
1. block 3700 - revealing stage started
1. block 3750 - referendum finished events
1. block 4150 - announcing period started events
1. another referendum never happened again after the first one

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201892179310814) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
Clarified the issue is simply due to the new design - not a bug.
