### ISSUE TITLE
Proposed NFT parameters

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3326]
For the `rhodes` release we will need to provide a couple of different NFT-related constraints that are kept in storage and atm can only be set during chain init or with runtime upgrade. I think it may be easier to decide on those values before `olympia` and just include them in the chain configuration. Here's my proposal for those values, looking for feedback:

* `MinAuctionDuration` - `300` / 30 minutes
* `MaxAuctionDuration` - `1_296_000` / 90 days
* `MinAuctionExtensionPeriod` - `0` (I think we should allow disabling this feature if not desired)
* `MaxAuctionExtensionPeriod` - `3_600` / 6 hours
* `MinBidLockDuration` - `10` / 1 minute
* `MaxBidLockDuration` - `14_400` / 24 hours
* `MinStartingPrice` - `1` JOY
* `MaxStartingPrice` - Not sure about this one, maybe we just use maximum possible value of `Currency`?
* `MinCreatorRoyalty` - `1%`
* `MaxCreatorRoyalty` - `50%`
* `MinBidStep` - `1` JOY
* `MaxBidStep` - This one is tricky as well, our plan is to use 2% of starting price when user is creating an auction in Atlas. But since starting price can be quite big, this needs to take that into account. So I would suggest to either keep this unbound, same as `MaxStartingPrice` or just 2% of `MaxStartingPrice`
* `PlatfromFeePercentage` - I think we were planning to use `1%`?
* `AuctionStartsAtMaxDelta` _(how far into the future can be auction start date from now?)_ -  `432_000` / 30 days
* `MaxAuctionWhiteListLength` - 100

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201899739164543) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
@kdembler Those values look okay to me with my limited knowledge of the nft implementation details. You mentioned you needed a different set of value for testing in playground. Could you share those as well. So I can add both sets of values (the appropriate ones will be selected based on type of deployment (live, staging, dev) we specify when generating chain spec file (genesis config)

**Comment by kdembler** [comment]
Yes, that'd be fantastic. Values for development:

* `MinAuctionDuration` - `5` / 30 seconds
* `MaxAuctionDuration` - `1_296_000` / 90 days
* `MinAuctionExtensionPeriod` - `0`
* `MaxAuctionExtensionPeriod` - `3_600` / 6 hours
* `MinBidLockDuration` - `5` / 30 seconds
* `MaxBidLockDuration` - `14_400` / 24 hours
* `MinStartingPrice` - `1` JOY
* `MaxStartingPrice` - max value of `Currency`
* `MinCreatorRoyalty` - `1%`
* `MaxCreatorRoyalty` - `50%`
* `MinBidStep` - `1` JOY
* `MaxBidStep` - max value of `Currency`
* `PlatfromFeePercentage` - `1%`
* `AuctionStartsAtMaxDelta` -  `432_000` / 30 days
* `MaxAuctionWhiteListLength` - 100

**Comment by mnaamani** [comment]
Implemented in  #3346
Values can always be revised when rhodes is released, by settings them in `on_runtime_upgrade()`
