### ISSUE TITLE
Make all constants configurable in node

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3330]
Currently there are a number of constants that have inlined values, however, it would be useful to be able to set new values for specific scenarios, such as in testing environments.

**Comment by mnaamani** [comment]
I propose we use conditional compilation using [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) to define 3 sets of runtime configurations/parameters to cater for different environments:

`Production` for production live network (default if no explicit selection is made)
`Staging` for pre-release staging networks and playgrounds
`Testing` for running automated integration tests

move out all parameter declarations and constants from `runtime/src/lib.rs` and `runtime/src/constants.rs` into a "config_production.rs", "config_staging.rs" and "config_testing.rs" modules.
common constants that are not environment specific can be placed in a "config_common.rs"

`runtime/src/lib.rs` will then import conditionally the appropriate parameters from the config_x.rs module

It would also be advisable to have different runtime `spec name` and `authoring version` number for each build type.

For proposals parameters configuration we currently optionally parse a JSON string from the environment at compile time. We should also drop this technique which overly complicates build and deployment in addition to being overly complex in implementation. Further, I think it is sufficient to have different sets of parameters for the different scenarios, and fine grained control seems unnecessary. (At least that has been the experience during pre-release testing)

In the end the different runtime configurations would be producing like so:

`cargo build --release` // production
`cargo build --release --features "staging_env"` // staging
`cargo build --release --features "testing_env"` // testing

**Comment by mnaamani** [comment]
what do you think @shamil-gadelshin about this approach ?

**Comment by shamil-gadelshin** [comment]
It could work! 

If we choose this approach we should implement 'mutual exclusive feature barrier': https://doc.rust-lang.org/cargo/reference/features.html#mutually-exclusive-features

There is a very close alternative: to use environment variable flags only to choose which `constant.rs` file to use (DEV, TEST, etc) to avoid feature clash.

Also, we should run checks&tests for each configuration that could be an additional burden for our CI.

**Comment by bedeho** [comment]
FYI: Whatever scheme we pick, I hope it will be very light weight to add/remove constants, because I suspect many values which currently are constants will actually become storage variables that will be updatable with proposals. Allowing people to easily provide initial values when launching a playground for such configurable storage values would arguably be just as important.

**Comment by mnaamani** [comment]
> FYI: Whatever scheme we pick, I hope it will be very light weight to add/remove constants, because I suspect many values which currently are constants will actually become storage variables that will be updatable with proposals. Allowing people to easily provide initial values when launching a playground for such configurable storage values would arguably be just as important.

It is farily light weight to add remove constants, you just have to remember to do it in 3 files. I think if we decide to have more than 3 environments we might want to consider an alternative way by introducing a macro .. for example `expand_for_build_env!(...)`

```
parameter_types! {
    pub const MyParameter: Type = expand_for_build_env!(Val1, Val2, Val3, Val4)
}
```

But it becomes hard to read and you always have to remember order. 


For parameters that are in storage and initialized at genesis, we have a similar mechanism in our chain-spec builder where you can specify  a `--deployment` argument (dev, staging, live) which will also pick from predefined set of initial values. Giving additional control when deploying a playground for these values is a lot more practical as we can easily script changes to a .json file. Only limiting factor is how easy it is to make it for the user in the github actions UI.

**Comment by mnaamani** [comment]
Implemented in https://github.com/Joystream/joystream/pull/3462
