### ISSUE TITLE
Olympia testing - extrinsics issues on polkadot.js.org

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3331]
### Problem & Solution
* The problem: Some extrinsics don't work! No functionality has been tested, this is purely for the purpose of testing `olympia` as some features are either not working or unsupported within `Pioneer`. This is holding back testing for some areas.
* The solution: update the `defs.json` file (https://github.com/Joystream/joystream/blob/olympia-playground/types/augment/all/defs.json) to fix these problems (this is my understanding of how it would be fixed)

### Screenshot of problem
Below is a screenshot showing what the problem is. In short, a user should be able to enter `text` and is thrown an error and can't submit the extrinsic at all.
![image](https://user-images.githubusercontent.com/50830161/156155963-6cfc90a8-d1e0-4647-844b-e7a3fae0b5ef.png)

### Notes
* NO transactions are actually being sent at part of this testing, it is purely to see the UI issues with polkadot.js.org that are preventing some extrinsics from being submitted at all.
* This is purely a test to indicate boxes where it appears text should be possible to enter. In order to save time I haven't test both `text` and `hex` (`0x616263641`), but I assume both of these fail in all instances.
* Everything has been tested, except for sections that are noted as being out of scope.

### Testing process
1. Types used: https://github.com/Joystream/joystream/blob/olympia-playground/types/augment/all/defs.json
2. Go through each extrinsic and look for any possible boxes for text input
3. Type in random text
4. Record failures

### Common ext issues between WGs
* ALL Working Groups have these issues:
	* leaveRole
		* rationale
			* `createType(Call):: Call: failed decoding contentWorkingGroup.leaveRole:: Struct: failed on args: {"worker_id":"WorkerId","rationale":"Option<Bytes>"}:: Struct: failed on rationale: Option<Bytes>:: Number can only safely store up to 53 bits`
	* setStatusText
		* statusText
			* `createType(Call):: Call: failed decoding contentWorkingGroup.setStatusText:: Struct: failed on args: {"status_text":"Option<Bytes>"}:: Struct: failed on status_text: Option<Bytes>:: Bytes: required length less than remainder, expected at least 7386, found 16`
	* slashStake
		* rationale
			* `createType(Call):: Call: failed decoding contentWorkingGroup.slashStake:: Struct: failed on args: {"worker_id":"WorkerId","penalty":"BalanceOf","rationale":"Option<Bytes>"}:: Struct: failed on rationale: Option<Bytes>:: Bytes: required length less than remainder, expected at least 26, found 9`
	* spendFromBudget
		* rationale
			* `createType(Call):: Call: failed decoding contentWorkingGroup.spendFromBudget:: Struct: failed on args: {"account_id":"AccountId","amount":"BalanceOf","rationale":"Option<Bytes>"}:: Struct: failed on rationale: Option<Bytes>:: Bytes length 437852633 exceeds 10485760`
	* terminateRole
		* rationale
			* `createType(Call):: Call: failed decoding contentWorkingGroup.terminateRole:: Struct: failed on args: {"worker_id":"WorkerId","penalty":"Option<BalanceOf>","rationale":"Option<Bytes>"}:: Struct: failed on rationale: Option<Bytes>:: Number can only safely store up to 53 bits`

#### Other extrinsics
* Balances:
	* No problems
* Blog
	* editPost
		* newBody
			* `createType(Call):: Call: failed decoding blog.editPost:: Struct: failed on args: {"post_id":"PostId","new_title":"Option<Bytes>","new_body":"Option<Bytes>"}:: Struct: failed on new_title: Option<Bytes>:: Number can only safely store up to 53 bits`
* Bounty
	* submitOracleJudgement
		* judgement/rationale
			* not sure if this is actually a bug, because I don't know what is meant to go in `judgement` field--if both are supposed to be text then its not working!
			* `judgement` causes severe UI lag/crashing when text is entered
			* `createType(Call):: Call: failed decoding bounty.submitOracleJudgment:: Struct: failed on args: {"oracle":"BountyActor","bounty_id":"BountyId","judgment":"OracleJudgment","rationale":"Bytes"}:: Struct: failed on judgment: BTreeMap<EntryId,OracleWorkEntryJudgment>:: decodeU8a: failed at 0x64…: {"_enum":{"Winner":"OracleWorkEntryJudgment_Winner","Rejected":"Null"}}:: Unable to create Enum via index 100, in Winner, Rejected`
* Constitution
	* No problems
* Content
	* createChannel
		* meta
			* presumably this should be text input?
			* `createType(Call):: Call: failed decoding content.createChannel:: Struct: failed on args: {"actor":"ContentActor","params":"ChannelCreationParameters"}:: Struct: failed on params: {"assets":"Option<StorageAssets>","meta":"Option<Bytes>","reward_account":"Option<GenericAccountId>","collaborators":"BTreeSet<MemberId>","moderators":"BTreeSet<MemberId>"}:: Struct: failed on meta: Option<Bytes>:: Bytes: required length less than remainder, expected at least 26, found 12`
	* createVideo
		* meta
			* presumably this should be text input?
			* `createType(Call):: Call: failed decoding content.createVideo:: Struct: failed on args: {"actor":"ContentActor","channel_id":"ChannelId","params":"VideoCreationParameters"}:: Struct: failed on params: {"assets":"Option<StorageAssets>","meta":"Option<Bytes>","enable_comments":"bool","auto_issue_nft":"Option<NftIssuanceParameters>"}:: Struct: failed on meta: Option<Bytes>:: Number can only safely store up to 53 bits`
		* auto_issue_nft
			* nft_metadata
				* presumably this should be text input?
				* `createType(Call):: Call: failed decoding content.createVideo:: Struct: failed on args: {"actor":"ContentActor","channel_id":"ChannelId","params":"VideoCreationParameters"}:: Struct: failed on params: {"assets":"Option<StorageAssets>","meta":"Option<Bytes>","enable_comments":"bool","auto_issue_nft":"Option<NftIssuanceParameters>"}:: Struct: failed on meta: Option<Bytes>:: Number can only safely store up to 53 bits`
	* deletePost
		* rationale (without `witness`)
			* `createType(Call):: Call: failed decoding content.deletePost:: Struct: failed on args: {"post_id":"VideoPostId","video_id":"VideoId","actor":"ContentActor","params":"VideoPostDeletionParameters"}:: Struct: failed on params: {"witness":"Option<Hash>","rationale":"Option<Bytes>"}:: Struct: failed on rationale: Option<Bytes>:: Bytes: required length less than remainder, expected at least 7386, found 10`
* distributionWorkingGroup
	* No problems except all WG problems in the first section
* finalityTracker
	* No problems
* forum
	* No problems
* forumWorkingGroup
	* No problems except all WG problems in the first section
* gatewayWorkingGroup
	* No problems except all WG problems in the first section
* grandpa
	* No problems
* imOnline
	* No problems
* joystreamUtility
	* No problems
* members
	* updateProfile
		* handle
			* `createType(Call):: Call: failed decoding members.updateProfile:: Struct: failed on args: {"member_id":"MemberId","handle":"Option<Bytes>","metadata":"Option<Bytes>"}:: Struct: failed on handle: Option<Bytes>:: Bytes: required length less than remainder, expected at least 7386, found 9`
		* metadata
			* `createType(Call):: Call: failed decoding members.updateProfile:: Struct: failed on args: {"member_id":"MemberId","handle":"Option<Bytes>","metadata":"Option<Bytes>"}:: Struct: failed on metadata: Option<Bytes>:: Bytes: required length less than remainder, expected at least 7386, found 15`
* membershipWorkingGroup
	* No problems except all WG problems in the first section
* operationsWorkingGroupAlpha
	* No problems except all WG problems in the first section
* operationsWorkingGroupBeta
	* No problems except all WG problems in the first section
* operationsWorkingGroupGamma
	* No problems except all WG problems in the first section
* proposalsCodex
	* ALL proposal types tested
	* No problems
* proposalsDiscussion
	* No problems
* proposalsEngine
	* No problems
* referendum
	* No problems
* session
	* No problems
* staking
	* This wasn't tested because its not a part of Joystream
* storage
	* No problems
* sudo
	* Out of scope
* system
	* Out of scope
* timestamp
	* Out of scope

**Comment by Lezek123** [comment]
Looks like in case of `Option<Bytes>` you need to provide a valid hex along with length encoding ie. `console.log(util.u8aToHex(api.createType('Bytes', 'text').toU8a(false)))` (this can be pasted in https://polkadot.js.org/apps/#/js), this may be a limitation/bug of `polkadot/apps` interface.

I encourage you to use https://github.com/polkadot-js/apps/pull/7134 for testing, I try to keep this draft PR up-to-date so you won't need to paste `defs.json` manually (they will be automatically injected for Joystream network).

**Comment by mochet** [comment]
Closing as appears to be solved
