### ISSUE TITLE
Create Funding Request Proposal

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#3333]
When creating a "Funding Request Proposal", there are currently 5 checks done at creation.

The three relevant here are:
1. No duplicate destination accounts
2. Each individual amount must be below a limit
3. Max 100 destinations

I would have thought the purpose of having an amount ceiling would be to stop the total amount being excessive, not one particular recipient. Given that a person can have infinite accounts, I don't think this is a meaningful check.

Are there any specific reasons to check for duplicate accounts? In some cases (eg. rewarding multiple groups for different things), there's a reason to include the same account multiple times, instead of summing up, as this removes the need for extra explanations.

**Comment by bedeho** [comment]
>  would have thought the purpose of having an amount ceiling would be to stop the total amount being excessive, not one particular recipient.

Agreed, can be changed later, not urgent.

> Are there any specific reasons to check for duplicate accounts? In some cases (eg. rewarding multiple groups for different things), there's a reason to include the same account multiple times, instead of summing up, as this removes the need for extra explanations.

I am not sure I buy that, but the check is not doing any real work anyway.
