### ISSUE TITLE
NFT query node - Better support for NFT history

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3343]
In Atlas we want to display a given NFT's history, who it was owned by, placed on sale, etc. There is `transactionalStatusUpdates` field on the NFT type that provides some basic info, although we are missing some details that we would want to display in the UI.

Here's the data we can get atm:

```json
        "transactionalStatusUpdates": [
          {
            "transactionalStatus": {
              "__typename": "TransactionalStatusIdle",
              "dummy": null
            }
          },
          {
            "transactionalStatus": {
              "__typename": "TransactionalStatusBuyNow",
              "price": 1000
            }
          },
          {
            "transactionalStatus": {
              "__typename": "TransactionalStatusIdle",
              "dummy": null
            }
          },
          {
            "transactionalStatus": {
              "__typename": "TransactionalStatusAuction",
              "auction": null
            }
          },
          {
            "transactionalStatus": {
              "__typename": "TransactionalStatusIdle",
              "dummy": null
            }
          }
        ]
```

(It seems there's a bug because all the past auctions are `null`, opened separate issue for that: https://github.com/Joystream/joystream/issues/3342)

Not sure what's the feasibility of each of those, so let's discuss. Ideally, following data would be available:

1. Who was the owner at a time of a given update.
1. Whether the auction/buy now was completed or cancelled
1. Who won the auction/buy now if it was completed
1. When a given update happened

ondratra What are your thoughts on this? Possible that some of that is already available although I think mostly not

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201912502857072) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Why can't you just query the event type and filter on the video? This is how Pioneer deals with history queries.
This is of course assuming we have one or more event entities for NFTs/content directory.

**Comment by kdembler** [comment]
`transactionalStatusUpdates` was my first try because it just seems like a high-level wrapper over all the events. If my choice is to run 15 queries and construct history client-side OR get neat history alongside fetching the NFT, you know what my choice will be.

I took a look at the events QN provides and indeed it seems we should be able to extract all the data from there, it just seems it will be a bit harder for client but we can manage

**Comment by bedeho** [comment]
> I took a look at the events QN provides and indeed it seems we should be able to extract all the data from there, it just seems it will be a bit harder for client but we can manage

You may be right, but its not obvious to me that this should be the case. Perhaps checking how Pioneer does this, for example listing events for a specific working group, can be helpful? My naive take is that it should just take a single query basically.

**Comment by bedeho** [comment]
For Rhodes we decided to rely on client side event processing to sidestep this problem for now.
