### ISSUE TITLE
Bounty: Entry withdrawal can lead to bounty invalid progress to Judgment period

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3347]
Steps to reproduce:

* Create a bounty
* Fund the bounty
* Announce entry
* Submit work
* Withdraw the entry

Because `submit_work` [changes the bounty milestone to `BountyMilestone::WorkSubmitted`](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/bounty/src/lib.rs#L1105) and withdrawing an entry has no effect on the `bounty.milestone`, after the `WorkSubmission` stage the bounty will progress to `Judgement` stage with 0 entries.

At this point the bounty is "bound to fail", [`submit_oracle_judgment` even prevents submitting a judgement in case there are no active entries](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/bounty/src/lib.rs#L1145), so one (for example, wanting to withdraw the funds) needs to wait until the end of redundant `Judgment` period, which can have only one outcome at this point.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201913554520401) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Well spotted, but this is not important enough to fix, given how low cost the problem is, and that Luis is working on changes that likely deeply impact this part of the codebase anyway.

**Comment by L3pereira** [comment]
This will not be a problem in the new implementation, since the working period will end when the oracle calls new extrinsic (end_work_period), which checks if there are no entries and change the bounty milestone to the proper state.

**Comment by Lezek123** [comment]
Closing the issue in that case
