### ISSUE TITLE
Bounty: No work submissions by an entrat prevent him from beeing slashed

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3354]
See: https://github.com/Joystream/joystream/blob/olympia/runtime-modules/bounty/src/lib.rs#L1625

When trying to slash a worker that entered a bounty, but didn't submit any work, we're currently getting: `WinnerShouldHasWorkSubmission`. The error name suggests it should only apply when we try to reward this worker, but in reality it's thrown regardless of the judgement type (as it's outside of the `if let OracleWorkEntryJudgment::Winner { reward } = work_entry_judgment {` condition)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201919516235940) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
I guess simplest solution is to just rename `WinnerShouldHasWorkSubmission` to `ShouldHasWorkSubmission`, or to introduce a new error for the slashing case `SlashingCandidateShouldHaveWorkSubmission`.

Does not seem critical either way, so perhaps we should fix it post-oympia?

**Comment by Lezek123** [comment]
So do we indeed want to prevent slashing an entrant that didn't submit any work?

**Comment by bedeho** [comment]
Actually no, that could make sense, as long as we are slashing people who withdraw, slashing people who don't submit should also be feasible, but I don't think this very important, and certainly not now. I have not looked at the

So to summarize, we should
- update event naming
- allow slashing entrants who never submitted any work: this probably also means we can remove state that reflects whether any work was ever submitted or not, like a counter or whatever we are doing.

**Comment by Lezek123** [comment]
> this probably also means we can remove state that reflects whether any work was ever submitted or not, like a counter or whatever we are doing.

We're still using it to prevent rewarding an entrant with no submitted work

> update event naming

Do you mean the error name? As long as we're still preventing rewarding the entrant with no works submitted (we're only allowing slashing), I think `WinnerShouldHasWorkSubmission` is a correct name (perhaps we could just fix `Has` => `Have` typo, but it doesn't seem very important)

**Comment by bedeho** [comment]
> We're still using it to prevent rewarding an entrant with no submitted work

Ok yes, makes sense.

> Do you mean the error name? 

I was referring to the fact that we used the error about _winner_ not having submitted work to also refer to people being _slashed_ who have not submitted work, the latter are not winners.

**Comment by mnaamani** [comment]
Implemented in https://github.com/Joystream/joystream/pull/3361

**Comment by traumschule** [comment]
sounds complicated enough test for Joystream/pioneer/pull/3894
