### ISSUE TITLE
Olympia: `initialInvitationBalance` isn't read

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#3357]
After proposal to `SetInitialInvitationBalance` is approved and executed, the `initialInvitationBalance` gets updated, yet balance of a new invitee will still equal `defaultMembershipPrice`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201924941477015) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Fixed in https://github.com/Joystream/joystream/pull/3363
