### ISSUE TITLE
Olympia: sporadic QN lag spikes (WIP)

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3359]
## Problem
During testing the QN has started to have sporadic lag spikes. When these spiked happen `Pioneer` as well as `polkadot.js.org` can both become inaccessible for some amount of time. I have no server access but will make a few notes here to see if anything may be causing this.

edit: of course, after writing this, it didn't have any lag spikes... will keep open for any further testing where the QN lags

### Test 1 - connecting from two distinct geographies
(this is probably unlikely, but checking anyway)

### Test 2 - Timing
(testing frequency/interval)
* Freeze 1:
	* Duration: about `5 minutes`

**Comment by bedeho** [comment]
What is spiking? 

1. the API response latency?
2. the progress in indexing blocks?
3. the progress in processing blocks?

A more complete description of what is observed is needed.

**Comment by mochet** [comment]
> What is spiking?
> 
> 1. the API response latency?
> 2. the progress in indexing blocks?
> 3. the progress in processing blocks?
> 
> A more complete description of what is observed is needed.

I don't know how to explain it in those exact terms but basically the whole polakdot.js.org interface stops gathering blocks and the pioneer interface sits trying to connect until it comes back online.

It's unlikely to be caused by the user-side because when it dropped out myself and another of the testers experienced the same situation.

**Comment by traumschule** [comment]
- are you able to make requests to the QN playground while this happens or does it appear as offline?
- are you saying no blocks are produced? does the validator log show anything unusual?

**Comment by dmtrjsg** [comment]
@mochet worth investing any effort in this one? Still having the spikes?

**Comment by mochet** [comment]
> @mochet worth investing any effort in this one? Still having the spikes?

No I can't recall any recently, I think this was probably just server issues when this was created so will close
