### ISSUE TITLE
Metaprotocol enhancement: storage+payments

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3367]
# Background
Credit goes to kdembler for this question
https://github.com/Joystream/joystream/issues/3245#issuecomment-1060908766

# Proposal 
We can make the metaprotocol messages even more powerful if we decorate them with two optional extra features with side-effects

* Send someone money: `Option<(Account, Balance)>`, withdrawn from whatever account makes most sense, but be careful here, don't allow spending out of sensitive pools, like a channel account.
* Do something with storage: `Option<StorageAction>`, where `StorageAction` is a new type which captures natural interactions with data objects in whatever bag makes sense, so typically add or delete objects. Metaprotocol message only succeeds if storage action suceeds.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202137217567676) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
One problem that I think you identified in the past is what happens when the transaction fails on meta-protocol level for some reason. Side-effect would still occur though, leaving client in a problematic state to handle

**Comment by bedeho** [comment]
Yep this is a very good point, still seems worth it to have the feature tho. In some cases, the client may even have perfect certainty about whether meta-protocol failure can even happen, in many other it will be exceedingly rare if client is well behaved (like someone incidentally exactly removes a comment that you tipped the moment you did it).

**Comment by kdembler** [comment]
Closing:
1. Payments via remarks are already supported as of spec 2001
2. Don't think we will ever integrate legacy storage into remarks, we will redo storage with metaprotocol sooner
