### ISSUE TITLE
NFT query node - ownedNftsConnection fails

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3381]
If you run a query to `ownedNftsConnection` and include `transactionalStatus` in the requested field, the query will fail. Example query:

```graphql
fragment TransactionalStatus on OwnedNft {
  transactionalStatus {
    __typename
    ... on TransactionalStatusIdle {
      dummy
    }
    ... on TransactionalStatusBuyNow {
      price
    }
    ... on TransactionalStatusAuction {
      auction {
        auctionType {
          __typename
          ... on AuctionTypeEnglish {
            duration
            extensionPeriod
          }
          ... on AuctionTypeOpen {
            bidLockingTime
          }
        }
      }
    }
  }
}


query {
  ownedNftsConnection(where: {
    ownerMember: {
      handle_eq: "0x0"
    }
  }) {
    edges {
      node {
        ...TransactionalStatus
        video {
          id
        }
      }
    }
  }
}
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201943702689043) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Seeing this also in "graphql playground fix" PR https://github.com/Joystream/joystream/pull/3335#issuecomment-1061449936

**Comment by ondratra** [comment]
I've run the query on what I believe is the current Atlas playground https://52.91.200.121.nip.io/query-node/server/graphql and got an empty result for the query. Is that the same result you are getting @kdembler, or is the query crashing with an error?

**Comment by kdembler** [comment]
This isn't the current playground and it doesn't have any NFTs, that's why it's empty. The newest one is https://54.196.132.14.nip.io/orion/graphql . Although you will have to remove the filter from the query since that member doesn't exist. It crashes then, not returns empty results
