### ISSUE TITLE
Question: Can user_a give user_b tokens which are locked for certain purposes?

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3398]
On mainnet, it would be very good to be able to give users tokens that are locked and cannot be used for any purpose other than paying fees, staking and basically cannot be transferred by the user to anyone else. I assume this isn't yet possible, but maybe it is so I am asking if it is?

To be clear, this would be for user>user transactions. `Alice` would send `Bob` tokens and tick some box which `LOCKS` the tokens on `Bob's account`. Then `Bob` can only use these `LOCKED` tokens for paying for video uploads, comments, reactions and not be able to transfer or sell them.

The `invite` system seems to allow for this (although it says `only allows transaction fees` which I don't fully understand) and technically speaking invites should deal with this issue however there are foreseeable problems that would be beyond the scope of the initial invitation balance and if we can address these it would significantly help with dramatically pushing early growth of the platform.

There are multiple issues that could be solved if this were possible:
- As our platform will require fees for uploading content and many other things, it is very predictable that users will beg for tokens using this reasoning. While of course, a discerning person could go through each request this would take hours and if users see tokens being given out freely for certain purposes, then the requests for them will increase. The council could fund one or more trustworthy individuals who give out tokens, but the time required to examine every request would very quickly become unmanageable with very little return on investment. It may be cheaper to give them out without the required due dilligence, but this would quickly become unmanagable and also devalue the platform with thousands of spammy requests for tokens.
- As part of the push for incentivizing new users when the platform launches, ensuring that interested users who may upload long/expensive content have sufficient tokens for this purpose is going to be a critical driver for growth. I have read https://github.com/Joystream/joystream/issues/2365 extensively (and related issues) and if I understand correctly, there may be some lead time involved with channel rewards and not all channels may be eligible, or it may be too expensive for them to obtain their rewards. For this reason, it is preferable to have a way to give these channels sufficient tokens without risking them just dumping/selling them immediately.
- As we have seen during earlier testnets when there was an upload limit, it is undesirable for users. Most users will expect almost unlimited capacity and rather than allow early users to encounter this obstacle, it would be nice to have a way to deal with it.
- If we call the `invite balance` by another name: `free-use tier` then people who want to upload a lot of content will probably resort to using multiple accounts/channels to get around this restriction. This occurs with basically any free-use tier system in existance, and even occurs on ones that have social purposes (so not like getting another Dropbox account, but getting another account on a social media website to escape restrictions and avoid paying--and then just linking to the original account)

For these reasons, specifically trying to ensure new users always have tokens available for fees, it is desirable to have a way to do this and basically be able to give people tokens which they cannot sell or exchange. The invitation initial balance could of course be increased to help with this, but it only deals with the initial moment of invitation and doesn't allow for discretionary locked funding of accounts that are edge cases.

This also allows us to deal with users being able to "know" they'll be able to get tokens with legitimate sounding reasons that can then easily be sold. The time required to deal with this on an ongoing basis after mainnet has launched will be very expensive. If there is a way to accomodate this, it could significantly help with the platform's growth and allow for a risk-averse way of giving new users a leg up on the platform.

This also may open the door to having an off-chain script which can monitor accounts that are approaching a limiting balance, and the metrics of their account (such as how many views their uploads get). This would really help with ensuring a rapid pace of growth, especially early on.

Because of how the new account lock system works, I don't think this would have to have anything to do with working groups or proposals. This would really just be for fees associated with posting on the forum or uploading videos.

In short there are two scenarios:
1. We don't have a way to deal with this, and since we are a social platform there are dozens of people in our chat/twitter/forum who constantly ask for tokens so that they can upload content. I could go request tokens from the `council` via a `spending proposal` or the `Member WG` could try to tackle this, and spend thousands of man hours trying to gauge the credibility of individual requests. This would both cost the platform "real money" as well as result in thousands of users trying to ask for any allocation like this and end up being a perpetual problem.
2. We have a way to deal with this, and anyone who wants tokens for uploading videos has easy ways to get them (maybe a `faucet` in the early stages). The `Member WG` or a trustworthy person could easily approach the `council` for funds for this purpose and give them out to users almost entirely freely since they can't be used for any other purpose. The time requirement to do this is now completely minimized and since the funds are locked they're not technically "real money" and it becomes trivial to give new users a boost beyond their invite.

Obviously at some stage this wouldn't be scalable, but the impact of such a feature in early growth stages would be hugely significant.

**Comment by bedeho** [comment]
> although it says only allows transaction fees which I don't fully understand

It means that you cannot transfer the funds to another account basically, so you cant fund a bounty, or buy an NFT, or tip a creator or any kind of thing like that. This question did however made me think we probably need to make an explicit list, if only to make sure it makes sense, but also so people understand what they will and will not be able to do.

https://github.com/Joystream/joystream/issues/3414

> As our platform will require fees for uploading content and many other things, it is very predictable that users will beg for tokens using this reasoning

I guess the question here is, can invitation funds be used for this? I actually am not sure, because there are state bloat fees in the storage system, and soon the content directory also, and perhaps that mucks it up, so I will check. **This is super important.**

> For this reason, it is preferable to have a way to give these channels sufficient tokens without risking them just dumping/selling them immediately.

What sort of incentive are you talking about? just like, free money they can use for anything, including sell? If so then you need to add more context on how to do this without evaluating the content and traffic the same way that channel payouts will do.

> As we have seen during earlier testnets when there was an upload limit, it is undesirable for users

There has to be _some_ limit. Question is just, how big? you are just saying it should be bigger by default, aren't you.

> The invitation initial balance could of course be increased to help with this, but it only deals with the initial moment of invitation and doesn't allow for discretionary locked funding of accounts that are edge cases.

Not sure what you are saying.

# Conclusion

I don't think I really get your main point here, which is that something is broken with the invitation system _even if it worked for funding content publishing_.

Please restate more clearly.

# Meta point

The title of this issue is very inaccurate, it's not just about giving locked tokens - which we already can do. This issue identified very important questions, but, having an accurate description and title of the message is key for effective triage and collaboration 🙏 .

**Comment by mochet** [comment]
> 

Completely rewritten:

## Scope
The scope here is strictly `social users`. These are users of `social features` on Joystream that will always require `fees` (video uploads, channel creation, forum threads/posts/reactions and video comments etc).

## Problem
1. It is unknown whether `user_a` can send `user_b` tokens which are locked, with the intention of being able to send certain users tokens that can only be used for limited purposes (`social features`) that are only relevant to Joystream and do not allow for them to have any exchangeable value.
2. Most users will probably be funded *Initially* via the `invitation system` (especially during early stages of the platform)
	* Nothing is wrong with the `invitation system` it is just limited. I don't have any suggestions for how to change it, and I don't think it should be changed.
		* It can give locked tokens, only to invited users and it can only do this once based only on what `invited_initial_balance` is defined at that moment.
			* There's a huge world outside of this and addressing it will very quickly become effectively impossible.
		* The time required for the economics of the `invitation system` to stabilize just after launch will take a while. Even adjusting to general token/fee volatility will be also take time.
		* `invited_initial_balance` is a number. Whether it is "realistic", "good" or "bad" is inconsequential, as it will always be the result of governance taking thousands of factors and arguments and boiling it down to a single number.
3. At some point all users will run out of tokens without enough incentives.
	* On many platforms with "free tiers" this eventuates with users `requesting tokens` in spammy, low quality ways across every possible communication channel. CMs, Workers, FMs or users who run prominent channels are going to be hounded with these requests.
		* It also results in people creating new accounts for another "free tier" (even on social platforms this happens)
4. When tokens run out, `requests for tokens` will be posted.
	* In early stages, people start sending tokens to what are mostly `good-faith requests`, and for a while it works. It helps engage new users more and everyone wants to see the community develop.
	* In middle stages, this then results in in frequent `bad-faith requests` (masked as being `good-faith`) because they have seen users get tokens who ask in a certain way.
	* In late stages, the frequency of success of all `requests for tokens` diminishes to zero and the problem of `2.` is never solvable.
5. No present way exists to effectively address this.
	* Even if a WG or some "trusted actor" were given funds by the council to help users in these instances (those needing more tokens for `fees`) they can only send them `unlocked` to users.
		* 1st problem: It allows for them to be sold/exchanged. It would be a disaster to try this just for this reason.
		* 2nd problem: To avoid `bad-faith requests` this allows for bias, favoritism and corruption.

## Use-case / Solution
* Some users may upload content, or participate using other `social features` in a way that can be measured as providing the platform more value than the `fees` they contribute or they may be approaching reaching this point.
	* Be able to send these users funds that can only be used for `social features`
	* During early growth stages, where we may be really wanting to drive engagement, we can also develop bots that can use this same feature to automatically identify people and provide them with additional funds for `social features`
	* Some users may not provide great contributions, but giving them tokens is important if it is viable economically.


## Concepts
All of these concepts are what need to be appreciated to understand the `use-case`
1. `invitation balance decay`
	* A highly variable rate at which initial invitation fees run out. `transactions` always have `fees` so use will result in these running out at some point.
2. `incentives delay`
	* The delay between initial usage of `social features` and receival of the first `incentive` payment (channel payouts or any other incentive)
	* This will vary widely between users, community, topic, `social features` being utilized and what stage the platform is currently at.
3. `sustainable consumption`
	* The point at which a `social user` receives enough `incentives` to cover the fees required for their ongoing utilization of `social features`
4. `contribution benefits`
	* During all stages of the project, users will fall into `2` out of `4` possible categories:
		* **Contribution Cost:** either `low cost` or `high cost`
			* The consumption of `storage & bandwidth` or other resources that their `social feature` activities consume.
		* **Contribution Value:** either `(in)valuable user` or `negligible user`
			* The value that contributions made by users give the platform in terms of activity, engagement, community building and other areas. This value ignores any benefits provided by `fees` that goes towards platform WGs become profitable.
			* It isn't possible to easily measure this compared to `consumption usage` but there are ways to do so.
		* Least desirable: `high cost` + `neglibible user`
		* Most desirable: `low cost` + `invaluble user`
			* `invaluable users` make the platform more valuable just through their presence. Contributions from these users provide *substantially* higher value to the platform by providing the "backbone" of generating continuous discussion, activity, responses and extremely high levels of engagement compared to any other users.

## Summary
* For Everyone
	* Far less spammy requests for tokens.
	* An actual way to help new users requiring more funding for the fees associated with `social features`
		* This means new users do not give up if they encounter obstacles with having enough tokens and this system can be used to address this regardless of what stage the project is at.
* For Users
	* Generous users would be able to give `locked tokens` to users based on their own prerogative. These probably will probably originate from `incentives` they received so they are "real".
* For Governance
	* `locked tokens` are not "free money" if they come from governance budget or spending decisions as they had to be minted.
		* Giving them to users for further usage of `social features` doesn't "pay" for the infrastructure required, however there can be substantial value unlocked with this feature and it allows for far more flexibility in the future.
	* There will be a tradeoff between governance funding of this type of usage which essentially subsidizes the fees involved with certain `social features` and the potential `contribution value` which the platform gains.
		* If this feature can be used to "blanket fund" 1000 "valuable" users per day it may be an extremely "cheap" way of subsidizing further platform use.
		* Even if this feature were used over time to fund 1000s of users that provide `negligible value`, if it managed to reach 20 or even 30 users who are `invaluable users` the benefits would far outweigh the costs involved.

**Comment by bedeho** [comment]
My takeway here is you want some way to perpetually, and as needed, give users the ability to have certain kinds of social feature financed, but only for using platform social features.

So the premise here is that there are quality people who we want to make it very easy to continue to publish. Can't we just use the creator payout system for that? Here everyone with a channel gets some amount of $JOY, as decided by the council, every so often. This can be based on whatever the council wants, including possibly just "this person is running low on $JOY". 

Would that work?

**Comment by MindsGaming** [comment]
https://github.com/Joystream/joystream/issues/3519

**Comment by mochet** [comment]
> My takeway here is you want some way to perpetually, and as needed, give users the ability to have certain kinds of social feature financed, but only for using platform social features.
> 
> So the premise here is that there are quality people who we want to make it very easy to continue to publish. Can't we just use the creator payout system for that? Here everyone with a channel gets some amount of $JOY, as decided by the council, every so often. This can be based on whatever the council wants, including possibly just "this person is running low on $JOY".
> 
> Would that work?

I didn't know the creator payout system could work for something like this. While that is nice to have, it would be nice to have the kind of "give locked tokens" feature since then it isn't reliant on governance. Governance decisions are not only heavily impacted by whatever elected council and reasoning provided within a proposal, but the time delay is significant.

#### Approach A: Using a channel payout proposal
1. Identify user(s) who would benefit from having tokens. This means categorizing users, potentially having to communicate with them to ensure they know they'll be taken care of has to be done which is an unknown in terms of time/effort and especially an unknown when it comes to attention to detail.
2. Submit a proposal
3. Wait 24-72h (presumably) for the proposal to maybe be approved

So the 24-72h gap here for `step 3`, as well as the highly unknown variables of `step 1` make this process very rigid and if we make a reasonable presumption that this would take at least 72h to occur, any `low cost` + `invaluable user` may find somewhere else to participate and we may lose this user.


#### Approach B: Using the `locked tokens` approach
1. Identify user(s) who would benefit. This could be extremely immediate, such as seeing a user who uploads a video that gains a lot of views/attention very rapidly. 
2. Send `locked tokens` and basically `immediately` let them see they've been given a heavy subsidy.

This could also take on a more methodological approach, but in that case it would be easier to use `Approach A`. But the time delay with `Approach B` is essentially entirely removed and lets promising new users gain some form of indirect incentive (a subsidy of sorts) and not risk some unpredictable time frame during which they would have to wait.

#### Bonus of Approach B
Furthermore, `Approach B` actually gives us an added bonus for free. It provides an additional layer of reputational data which could be surfaced or utilized later on. There was prior discussion about the concept of user being able to stake towards channels or videos in order to give them standing--this approach already exists on other platforms and I haven't really seen it gain significant traction (from what I have seen).
If new/promising channels and/or users are given `locked tokens` by users who already have `reputation` on the platform, this can act as a signifier of value.

I still don't know what locked tokens can actually be used for (I know the sanity check is still pending https://github.com/Joystream/joystream/issues/3414) but if they're usable in the ways I anticipate then I think this feature would be tremendously useful and almost indispensible if its not something that would cost a lot to implement.

I also can't think of any other platform that has this kind of feature, despite it having quite a clear use case when it comes to incentivizing new/heavy/valuable users and not just throwing around "real" tokens that would just end up being abused.

**Comment by mochet** [comment]
@bedeho I created this issue with some very different ideas in mind. But I am now curious to know whether this function will be present upon launch--especially in the instance that the DAO decided to run its own form of the FM system and then be able to allocate tokens to inducted users which have the same vesting period as older users?

**Comment by bedeho** [comment]
We already have the notion of inviting people with funds that only work for transaction fees, and we are getting a new one called `gift_membersip` which allows people to give locked funds to people without depending on Membership WG invitation quota limitations, so if an already onboarded creator has depleted all their funds, anyone can just send them some $JOY, and as long as its below the lock limit, what you are describing works fine.
