### ISSUE TITLE
Olympia: Query node showing incorrect WG budgets

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#3401]
Unclear why, but this query:

```
query {
  workingGroups  {
    id
    name
    budget 
   }
}
```

gives very different results depending on the staging network. 

I'd assume it should show the same as `*WorkingGroup.budget`, but that has only been the case for only one of the four we've had running...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201962542974506) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Looks like there are 2 root-origin calls that modify the working group budget:
- `set_budget` in `working-group` pallet, which doesn't enforce any limits and emits `BudgetSet` event
- `update_working_group_budget` in `utility` pallet, which is spending from `Council` budget and emits `UpdatedWorkingGroupBudget` event

Looks like the 1st call is meant to be only executed by sudo, while the 2nd call is meant to be executed through a proposal.
Only the 1st event (`BudgetSet`) is currently recognized by the query node.

**Comment by Lezek123** [comment]
Fixed by https://github.com/Joystream/joystream/pull/3403
