### ISSUE TITLE
Bounty Module: Bugs

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3404]
(this is for @bwhm)

This issue is best explained with the following `Pioneer` screenshot, but it is not a `Pioneer` issue.
I will include a technical explanation after this brief intro--this just shows the problems in the easiest way.
I don't know if these bugs are already known, it is hard to search for something specific like this.

## Screenshot + Explanation
![image](https://user-images.githubusercontent.com/50830161/158288766-f0a48d81-0ba2-4e0f-8254-3f1e7d66e148.png)
Problems in the screenshot:
* The screenshot shows `entrants` for a single bounty
* **Example 2:** One of `tom-71's` bounty entries was created by `tom-71` but another random member (`ID: 180`) submitted work to it before `tom-71` did which changed the `chain state` for that entry to indicate work was successfully submitted.
* **Example 3:** `tom-65` has one `work submission` which is made up of `5` work entries that were contributed by `tom-65` +  `tom-52` + `tom-71` 
* Excluded: * ~~**Example 1:** `tom-71` has `3` different bounty entries (all registered under the same `Member ID`) -- The way this was done by using different Stake accounts.~~  (Upon further thought I think this is either intended or makes perfect sense anyway so that one member can submit multiple `entries` which are distinct from `revisions` or `updated entries`)

## Examples 	
2. Any user can submit work for any other user's `work announcement` before the creator of the announcement can -- `chain state` changes after this!
	* How?
		1. Have `user_a` create an `announcement` with no work submitted
			* initial state: `work_submitted: false`
		2. Have `user_b` submit work to the work `announcement`
			* `work_submitted: false` > `work_submitted: true`
	* Notes about the example shown
		* `oracle` + `creator` for this `bounty` have the same `member ID`
			* This had to be submitted as an extrinsic to happen due to a Pioneer limitation
			* As a result no `forum thread` was created as would typically be the case
	* Example (shown in chronological order)
		* Block 269,450
			* Blockhash: 0x5c893385f58a03c9d4651bb66b77b3ed5a9e773cd750f7ba4604ba4abd9d1134
			* `bounty.WorkEntryAnnounced`:
				* Member: 71
				* Stake: 74
					* https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F3.87.51.41.nip.io%2Fws-rpc#/explorer/query/0x5c893385f58a03c9d4651bb66b77b3ed5a9e773cd750f7ba4604ba4abd9d1134
		* Block 269,698
			* Blockhash: 0x7352a86c24907ce79476c3ad99b159724f6904e0db213c3d50d185a2bb681097
			* Chain State
				* `bounty.entries`
					* `member_id: 71`
					* `staking_account_id: 5DoZyc3UALx6ZjBjFUHtKu8ZmWpE86AV1hFopcthKeF6C4tj`
					* `submitted_at: 269,450`
					* `work_submitted: false` <<< THIS WILL CHANGE
					* `oracle_judgment_result: null`
		* Block 269,699
			* Blockhash: 0x3da15cd2bc12378e435b33cdd76f7628412c3616ac69a0c981305dcf44aac90f
			* `bounty.WorkSubmitted`
				* Member: 180
				* Stake: (no stake required)
					* https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F3.87.51.41.nip.io%2Fws-rpc#/explorer/query/0x3da15cd2bc12378e435b33cdd76f7628412c3616ac69a0c981305dcf44aac90f
		* Block 270,700
			* Blockhash: 0xd72d8ffd249793ede0b7cee561580acd12284daa5e24e7b9fd841135e8aa9bac
			* Chain State
				* `bounty.entries`
					* `member_id: 71`
					* `staking_account_id: 5DoZyc3UALx6ZjBjFUHtKu8ZmWpE86AV1hFopcthKeF6C4tj`
					* `submitted_at: 269,450`
					* `work_submitted: true` <<< THIS CHANGED
					* `oracle_judgment_result: null`

3. Any user can submit work for any other user's `announcement` that already has work submitted to it -- `chain state` doesn't change after this
	* Basically the same as `3` -- this is just an additional footnote on how the same thing can be abused

## Excluded
 (Upon further thought I think this is either intended or makes perfect sense anyway so that one member can submit multiple `entries` which are distinct from `revisions` or `updated entries`)
~~1. A single `member ID` can create multiple distinct `work announcements` for the same bounty by using different `stake accounts`
	* How?
		* Use a different staking account when `announcing`
	* Example
		* `member id: 71` has 3 separate work entries on bounty 4
			* `bounty.entries` 1
				* `member_id: 71`
				* `staking_account_id: 5GETFkA6GY5nryxDDa5c8p98aK6u5bT2kf4LHpRA9ZuSq6VY`
			* `bounty.entries` 3
				* `member_id: 71`
				* `staking_account_id: 5Caf8D9U62DtEBASAmdJbWKaVL3hCM5Gwb5mmPBGVutLcckD`
			* `bounty.entries` 4
				* `member_id: 71`
				* `staking_account_id: 5DoZyc3UALx6ZjBjFUHtKu8ZmWpE86AV1hFopcthKeF6C4tj`~~

**Comment by bedeho** [comment]
Should this be closed?

**Comment by mochet** [comment]
> Should this be closed?

Yes, closing as this was already fixed.
