### ISSUE TITLE
Refactor try_mutating_storage_state 

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3412]
Attempt to separate the different variatins of mutation in `storage::try_mutating_storage_state`

https://github.com/Joystream/joystream/blob/63dcc503cc866e8ba7459da8cf9e8e2fe634f3df/runtime-modules/storage/src/lib.rs#L3740

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202207047056762) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/4082
