### ISSUE TITLE
Invitation system sanity check

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3414]
# Background
Currently, the primary means by which a new member can get onboarded, without having to find some place to purchase $JOY, is the invitation system, which results in crediting them some diminimous amount of $JOY encumbered by a lock which prevents transfers, except for fees. At the same time, there are a range of features which requires one among the following:

1. paying transaction fees: based on tx weight + size
1. reserving funds
1. locking funds: with a range of different locks, however all which are combinable with invitation locks (https://joystream.gitbook.io/testnet-workspace/system/accounts-and-staking#locks-1)
1. crediting module accounts for different pallets
1. slashing funds

# Proposal
1. Make an exhaustive list of all actions a member can do which involves using funds they control in some way, across all pallets.
1. For each action briefly describe what sort of check is done on locks, balances, reservations, being very specific about what calls are made
1. For each action briefly describe how funds are locked/reserved/slashed/transferred/etc.
1. For each action describe whether a user with invited funds can engage in this action _using those funds_. **Later we will use this to evaluate if this should be changed.**
1. For each such case in 4, whether it is possible to leak those funds out as described here: https://github.com/Joystream/joystream/issues/3569

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202170659245432) by [Unito](https://www.unito.io)

**Comment by MindsGaming** [comment]
https://github.com/Joystream/joystream/issues/3519
