### ISSUE TITLE
Carthage genesis block

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3419]
# Background

We are launching `Carthage` which will be a new chain, with a genesis block and launch process as close as possible to the mainnet launch. This issue defines how we set the state of the genesis block.

# Proposal

The genesis block only initialised a set of _account balances_, with possible associated vesting, nothing else, and they are set as follows:

| Stakeholder         | Multisig allowed | Allocation (Hapi & %)  |  Launch Liquidity [2] (Hapi & %) | Vesting [3] (months) |
|:---:               |:---:  |:---:       |:---:           |:---:       |
| Current FMs [1]      |      Yes       |             |                   |           |
| Core Team           |      Yes       |             |                   |           |
| Jsgenesis AS [1]       |      Required       |             |                   |           |
| Current Investors   |      Yes       |             |                   |           |
| Rhodes accounts     |      No       |             |                   |           |
| Sudo account     |      No       |             |                   |           |

- This table will contain some rounding errors.
- The set of founding members will change on mainnet.
- [1] is as of of council period 10 being concluded, **should be updated at [snapshot block](https://github.com/Joystream/joystream/issues/3933)**, as time passes, greater and greater share of $JOY is allocated away from Jsgensis and towards FMs.
- [2] is the initial % share of corresponding stakeholder's allocation which is immediately transferrable at genesis.
- [3] is the number of months it requires for the corresponding stakeholder's allocation to become fully transferrable, not counting the initial launch liquidity. This occurs gradually block by block following a linear schedule.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202171819196259) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
This issue contains quite a few questions that are very relevant to the genesis block also: https://github.com/Joystream/joystream/issues/3400
