### ISSUE TITLE
Convention: Fallible cross pallet calls

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3422]
# Background

Lets say we are in pallet `A` which calls method `do_with_side_effect -> Result<_,_>` in `B`, for example a FRAME pallet like `balances` or a subsystem pallet like `storage`. Often it will look like this

```Rust

/// In pallet A
pub fn foo() {

            B::<T>::do_with_side_effect()?;
 
            //
            // == MUTATION SAFE ==
            //
}
```

This is fine, but often the next person will not know or remember that `do_with_side_effect` actually has side_effects 😱 , because it can easily just look like a normal ensure checks which don't, so the do this

```Rust

/// In pallet A
pub fn foo() {

            B::<T>::do_with_side_effect()?;
            
            new_call_which_can_return_result()?;
 
            //
            // == MUTATION SAFE ==
            //
}
```

Now we are in a situation, which easily can be hard to detect (in particular when changes are done over longer periods of time, and/or by different people), where our state gets corrupted.

# Proposal

Two approaches come to mind, any other ideas?

## 1. Comment

Just add a very loud comment to make it more clear for future you/person. The benefit of this approach is that it works also when we don't control the API of `B`, e.g. when it's a FRAME pallet.

```Rust

/// In pallet A
pub fn foo() {

            // HAS SIDE EFFECT ---
            B::<T>::do_with_side_effect()?;
             // HAS SIDE EFFECT ---
             
            //
            // == MUTATION SAFE ==
            //
}
```

## 2. Silent side effect method

In some cases, if we control pallet `B`, we can try to entirely avoid having such a method

```Rust

/// In pallet A
pub fn foo() {

            // No longer has any side effect, just like all other checks before barrier
            let x = B::<T>::can_do_with_side effect()?;
            
            //
            // == MUTATION SAFE ==
            //
            
            B::<T>::do_with_side_effect(x, ... ); // <-- statically does not fail
}
```

**Importantly, in some cases, it probably will be unavoidable that `do_with_side_effect` actually has some internal check which statically may not hold, in which case, it should just silently have no side effect.**

**Comment by dobertRowneySr** [comment]
Here one elaborate solution that  guarantees that : 
- statically `can-*` guards precede `do-*` mutation functions
- Multiple `can-*` guards can be serialized before any `do-*` operations take effects.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=99b9a67a0bcbe6244092c616f28e7963)

Example from the Multicurrency token pallet required for the creator token. But It can perfectly adapted to storage pallet calls

```rust
trait RequestHandler {
    fn perform(&self);
}

// have a pub struct with PRIVATE fields & NO [derive(Default)]
pub struct MintTokenRequentHandler {
    token_id: u32,
    amount: u64,
    to_who: u64,
}

impl RequestHandler for MintTokenRequentHandler {
            
    fn perform(&self) {
        // infallible
        // use the self.token_id, self.amount, self.to_who
        // already verified to perform the mintintg
        do_mint(self.token_id, self.amount, self.to_who);
    }
}

impl MintTokenRequentHandler {
    
    // public api
    pub fn try_new(token_id: u32, amount: u64, to_who: u64) -> Result<Self, DispatchError> {
        can_mint(token_id, amount, to_who)?;
        Ok(Self{token_id, amount, to_who})
    }

}

// not available outside the pallet        
pub(crate) fn can_mint(_token_id: u32, _amount: u64, _to_who: u64) -> DispatchResult {
    Ok(())
}

// not available outside the pallet        
pub(crate) fn do_mint(_token_id: u32, _amount: u64, _to_who: u64) {
    // mutation sensitive part
}

// in the public extrinsic for the same pallet...
pub fn mint(token_id: u32, amount: u64, to_who: u64) -> DispatchResult {
    let mint_request = MintTokenRequentHandler::try_new(token_id, amount, to_who)?;
    
    // == MUTATION SAFE ==
    
    mint_request.perform();
    Ok(())
}

// in another pallet ...
fn mint_and_do_other_stuff(token_id: u32, amount: u64, to_who: u64) -> DispatchResult {
    // Verification is FORCED because there is no wey to construct an RequestHandler
    // object except by using the try_new constructor
    let mint_request = MintTokenRequentHandler::try_new(token_id, amount, to_who)?;
    
    // possible several other request with their try new constructor, they can FAIL
    // and NO cross pallet state is corrupted:
    // request_1 = ConcreteRequestHandler1::try_new(...)?;
    // request_2 = ConcreteRequestHandler2::try_new(...)?;
    
    // == MUTATION SAFE ==
    
    mint_request.perform();
    
    // other infallible & mutation sensitive perform operation
    // request_1.perform()
    // request_2.perform()
    
    Ok(())
}
```
The idea here is that the `try_new` constructor it is the only way to set up a `RequestHandler` object, and only after that object being set up you can call a `perform` operation at a later time.

**Comment by shamil-gadelshin** [comment]
One of the fundamental issues we have is whether we should silent errors in `do-` methods.

In general, we can't avoid fallible method calls of the Substrate framework like `Balances::transfer`. If we choose to create infallible methods we implicitly choose silenting errors in the unknown set of third party methods. The clarity of the pallet's interface comes with a huge downside of possible *silent* state corruption. When we use fallible `do-` methods we could also get state corruption but it is much easier to detect, debug, and manually resolve later. I see it as the most important choice for our code convention.

**Comment by bedeho** [comment]
> The idea here is that the try_new constructor it is the only way to set up a RequestHandler object, and only after that object being set up you can call a perform operation at a later time.

I think this overall is a very nice approach. Its not 100% bullet proof, for example, perhaps `::perform` can inadverdently get called twice? I guess even this can be silently blocked by just having hidden state which protects against this. 

In general I see this making interactions across pallet boundaries much safer, and its also a clear standard, which we currently are lacking, which leads to problems.

It also reestablishes the very powerful bright line rule of `if you have ? after mutation safe barrier, you made a mistake`, currently this is true only 96% of the time, and that last gap always diminishes our attention when verifying the correctness of such code. I constantly do it myself and ahve to remind myself to double check whether a the fallible method being called actually does have side-effects, and whether the one immediately prior does not.

The downside I see here is that it is quite a bit of extra code to write, but its not _complicated_ code, so it's hardly a big penalty.

> If we choose to create infallible methods we implicitly choose silent errors in the unknown set of third party methods. 

1. Hopefully there are many cross pallet calls where the method does not involve this. This would be interesting to look at more closely.
2. Perhaps we can make it slightly more easier to detect such errors by introducing a events specifically for when there are fallible/panicked steps in the `do_` function fail.
3. Ultimately we are trading off the risk of introducing a runtime bug to begin with (which I believe is lower with this approach) with the ability to detect it, and perhaps even correct the storage.

I think the best way to approach this is for us to just select one or two calls and see how things look in a realistic example in both the client and host pallet.

**Comment by dobertRowneySr** [comment]
Audit report points out use of `#[transactional]` macro
