### ISSUE TITLE
NFT query node - royalties not working

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3426]
As discovered few days ago, setting an NFT royalty will break a query node. We have a hotfix here #3407 but we need a full fix.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201976939841732) by [Unito](https://www.unito.io)

**Comment by ondratra** [comment]
There is support for setting royalty in existing `network-tests`, but it is not actually used in any fixture. Fix the bug in mappings + select one of the fixtures, set royalty there and ensure tests are still passing (thus, mappings for royalty work).
