### ISSUE TITLE
Nft bid reservations vs module account

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3429]
# Background
Currently we are using reservations as the means to encumber bid funds, but this is the only place in our runtime, and it is less clear how they work compared to just having a simple built in module account, for example when thinking about the ability to do multiple reservations and reservations on the same account for distinct bids.

# Proposal
Review whether it would make the code simpler to just use the content directory module account (I assume one exists, if it doesn't, then make one).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201977534522096) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
It seems to me that one can basically extract funds locked for some sort of staking lock, like staking or invitation, by making a bid on the same account (member controller account), because the check involved is `can_reserve`, which does not care about locks. A reservation is then made, which is the way funds are allocated for a unique bid. At this point, you can just win the auction, which results in funds being unreserved and then a slash+deposit combo.

This sidesteps all locks, and hence is a bug.

I think this own is a good enough reason to stop using reservations and instead use module accounts+transfer. It also removes the last lingering use of reservations in our entire system, which helps us to reason more easily about these interactions.

**Comment by Lezek123** [comment]
> the check involved is can_reserve, which does not care about locks

This is not true, [`can_reserve`](https://docs.substrate.io/rustdocs/latest/src/pallet_balances/lib.rs.html#1744) uses [`ensure_can_withdraw`](https://docs.substrate.io/rustdocs/latest/src/pallet_balances/lib.rs.html#1452) under the hood, which does check the locks and makes sure that locked funds are not used as reserve.

I tested this on `rhodes` chain it seems to work properly (I cannot bid for `2000` having `2900 JOY` total balance, including `900 JOY` usable and `2000 JOY` locked)

**Comment by bedeho** [comment]
We agreed, notwithstanding the prior point, to transition to module accounts due to the opacity of using reservation & locking logic together.
