### ISSUE TITLE
Make faucet work with NFTs

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3431]
At least while on testnets, faucet needs to provide startup funds in a way that allows you to actually bid on and buy NFTs, currently this may not be working properly. Check this after this has been finalized in the NFT implementation. Importantly, make sure whatever they are given works with the hard coded minimum bid/buy now constraints in the chain.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201977698729136) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
We decided on the lats Rhodes call that
- We should make the faucet capable of providing more initial $tJOY than the invitation limit, because otherwise they cannot bid on NFTs, as the invitation lock prevents this. 
- The faucet should have some sort of automated alert and daily cap in case abuse starts happening. If abuse occurs, we can reduce the faucet reward to be at or below the invitation lock

**Comment by mnaamani** [comment]
Leaving some points here to keep in min for later:

#### How the faucet currently works
The "membership faucet" is nothing more than web api that uses a regular member account. The api invites new members. That is how funds are provided to the new member.

#### Managing available invites of the faucet:
On a regular basis the working group lead must create a proposal requesting a large number of invites and in turn transfer them to the "faucet member account".

#### The amount of funds new members receive is a runtime storage value (that can be set with sudo or a proposal). The faucet cannot grant new members an arbitrary value. In addition the funds are transferred from the member working group budget. Invitation will fail if budget cannot cover the initial amount.

**Comment by bedeho** [comment]
1. I see, so this basically means we can't fund with an amount that exceeds the baseline invitation lock, just using the invitation feature.
2. Could you perhaps add an extra feature where some funds are just transferred by the faucet from some reserve account in order to overcome this constraint? This amount should obviously be set server-side.
3. Could you add alerts (e.g. on email or whatever) which does track failed attempts due to either invite budget or working group budgets being depleted? basically just pushing out some notification when invite fails, alternatively when reserve account is depleted.
