### ISSUE TITLE
Runtime: add 'pending transfer' checks to the extrinsics in the content pallet.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#3433]
We need to add checks that will cancel extrinsics in the content pallet for the channels with pending transfers.

#### Recommended list of extrinsics to modify
* start_nft_auction
* cancel_nft_auction
* cancel_offer
* cancel_buy_now
* make_bid
* cancel_open_auction_bid
* claim_won_english_auction
* pick_open_auction_winner
* offer_nft
* sling_nft_back
* accept_incoming_offer
* sell_nft
* buy_nft
* channel_owner_remark
* channel_collaborator_remark
* channel_moderator_remark
* nft_owner_remark

[Original issue](https://github.com/Joystream/joystream/issues/2816)

[Related PR](https://github.com/Joystream/joystream/pull/3432)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201978254903846) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Duplicates https://github.com/Joystream/joystream/issues/3428
