### ISSUE TITLE
Constrained worker spending

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3435]
# Background

Currently, only the lead can spend out of the WG budgets, but this is very inflexible, workers may very well benefit from this sort of discretion. One example is curators spending on channel swaps, or for example workers funding bounties. 

# Proposal

For each worker (hence also lead), introduce a field `spending_constraint` s.t.

```Rust

struct GroupWorker {
/* snip */
spending_constraint: SpendingConstraint
}

enum SpendingConstraint {
Unlimited,
CanMint(Balance),
}
```

which can be set to some value when the

1. worker is hired through the lead accepting workers,
2. lead is hired through a hiring proposal,
3. lead updates the value for any other worker at any time.

There is no constraint on the actual value. Moreover,

- Introduce a new extrinsic `update_worker_spending_constraint` which the lead can use to set spending limit on any member, except him/herself. 
- Introduce a new proposal with similar purpose for council w.r.t. leads.
- Generalize leader spending extrinsic to
  - be callable by any active worker (not unstaking)
  - to respect the new `spending_constraint` value: meaning that only spends that fully are within the current `CanMint` are accepted, and reduce the `CanMint` balance after each spend. Obviosuly also budget of the group itself must fully accommodate 
  the spend.
- keep rationale.

**Comment by kdembler** [comment]
Don't think we need this, spending  by lead works fine so far

**Comment by bedeho** [comment]
Agree, there is no near term need for this, if we ever do, someone can repropose, closing.
