### ISSUE TITLE
Add payment swap logic to channel transfer feature

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3437]
# Background
[Original issue](https://github.com/Joystream/joystream/issues/2816)

Initial work was done here https://github.com/Joystream/joystream/pull/3432, but did not include a payment based swap as part of logic, while state was added (`ChannelTransferStatus::PendingTransfer::price`).

# Proposal
When  a non-zero price is set, then accepting the transfer attempt requires that the new `channelOwner` provide such funds to complete the swap. 

* A member _buyer_ funds out of controller account, and member _owner_ receives such funds in the same account. 
* A curator group owner funds, and receives funds, in the budget of the content working group. Hence spending requires that the budget currently allows minting the required quantity of $JOY, receiving just means $JOY is burned and budget of group is increased.

To safely enable the latter features we will later add the following

* Proper curator group permissions: https://github.com/Joystream/joystream/issues/3436
* Worker level spending constraints in the WG module (not a _must_): https://github.com/Joystream/joystream/issues/3435

but we can still implement core feature without these supportive guardrails.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201980015963009) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
Done
