### ISSUE TITLE
Bounty blocked by T::MinFundingLimit in funding period

### ISSUE THREAD

**Issue by L3pereira** [Joystream/joystream#3447]
When a bounty is in funding stage and the funding period ends by eg. target reached, a funder is limited by ```T::MinFundingLimit::get()```, this can block the bounty in funding period.
https://github.com/Joystream/joystream/blob/1c37a713511cfaf35b9577069f78827492324f2c/runtime-modules/bounty/src/lib.rs#L859

This test shows that a bounty can be locked, if a funder contributes with 4951, no other funder can contribute the rest of the amount (49) as this is less than ```T::MinFundingLimit::get()``` (50), causing the target to be unreachable. 

```rust
#[test]
fn fund_bounty_fails_funding_Less_then_minimum_allowed() {
    build_test_externalities().execute_with(|| {
        set_council_budget(500);

        let max_amount = 5000;
        let amount = 100;
        let account_id = 1;
        let member_id = 1;
        let initial_balance = 500;
        let cherry = DEFAULT_BOUNTY_CHERRY;

        increase_total_balance_issuance_using_account_id(account_id, 6000);
        increase_total_balance_issuance_using_account_id(
            COUNCIL_BUDGET_ACCOUNT_ID,
            initial_balance,
        );

        CreateBountyFixture::default()
            .with_perpetual_funding(max_amount)
            .with_cherry(cherry)
            .call_and_assert(Ok(()));

        let bounty_id = 1u64;

        FundBountyFixture::default()
            .with_bounty_id(bounty_id)
            .with_amount(4951)
            .with_member_id(member_id)
            .with_origin(RawOrigin::Signed(account_id))
            .call_and_assert(Ok(()));

        FundBountyFixture::default()
            .with_bounty_id(bounty_id)
            .with_amount(49)
            .with_member_id(member_id)
            .with_origin(RawOrigin::Signed(account_id))
            .call_and_assert(Ok(()));
    });
}
```

**Comment by bedeho** [comment]
I don't think this is a big problem, I suggest we don't do anything about this.

**Comment by L3pereira** [comment]
Okay, I just want to mention, that when a bounty has a funding period that is perpetual (it is necessary to reach a specific fund target), the funder will lose the amount of 4951.
If the funding period is limited, that is, a minimum of funds must be reached before a specific time, the bounty goes to "failed state". Then the funder will have an incentive to finance the bounty in order to block it, making it fail so that it can receive a cherry. He also can enter into collusion with other funders so this tactic is not so obvious

**Comment by bedeho** [comment]
> Then the funder will have an incentive to finance the bounty in order to block it, making it fail so that it can receive a cherry.

This was a phenomenal observation, you changed my mind :)

So can you outline a few alternative fixes?

**Comment by L3pereira** [comment]
Why a minimum funding amount?
I think validating for zero is enough. 

All contributions a funder does, are added into one entry in the BountyContributions storage.
Is not that if a funder makes 1000 contributions of 1 unit, you will have 1000 entries in storage, what you will have is 1 entry with 1000 units

The only reason I see this validation being useful is for restraining a funder to make a fewer number of contributions with higher amounts,

**Comment by bedeho** [comment]
> Why a minimum funding amount?
> I think validating for zero is enough.

I think we needed this before to prevent state bloat attack where some makes a large number of 0 contributions under different memberships. But now, we will have a separate fee for this anyway, which is effectively a minimum barrier, however, this fee does not consume the funding cap, which solves the problem.

**Comment by L3pereira** [comment]
You cannot contribute with 0, there is also a ```amount > Zero::zero()``` validation, but certainly, you can have a large number of, for example, 1Joy contributions under different memberships.
total
I think we can fix it this way:
Imagine 
```max funding```  = 1000,
```MinFundingLimit``` = 100
We can have the validation in such a way, that if ```total funding``` is in the range of 
```]max funding - MinFundingLimit; max funding]```  = ]900; 1000],
```MinFundingLimit``` will be dynamically reduced to accommodate the missing amount.
If total amount is 970, ```MinFundingLimit``` will be ```max funding - total funding``` = 1000-970=30

**Comment by bedeho** [comment]
I think its needlessly complicated, `MinFundingLimit` is not needed. Just require that they have to provide > `StateBloatBond`, so basically greater or equal to `StateBloat + 1`, and in this case only `1` is contributed as funding, which is fine. 

This way we don't even need `MinFundingLimit`, and we avoid complex edge case limit enforcement.

**Comment by L3pereira** [comment]
What do you mean with ```StateBloatBond```?

**Comment by L3pereira** [comment]
A funder can be a member or the council, Should a council have to stake a StateBloatBond in the same way as a member?
He is only one entity and it will represent only one entry in the BountyContibutions storage.

**Comment by bedeho** [comment]
Treat all funders the same.

**Comment by bedeho** [comment]
# Conclusion

- No longer have minimum funding limit, even 0.
- This lack of a minimum removes the original attack.
- Rely on introduction of contribution bloat bonds to pay for stroage of those
