### ISSUE TITLE
Runtime: Add bid being displaced to English auction NFT event

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3472]
# Background
https://github.com/Joystream/joystream/issues/3471

# Proposal
Add bid possibly being displaced in an English auction bid, in content pallet of runtime.

Use and target `Rhodes` branch

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1202006250278703) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/3506
