### ISSUE TITLE
Post-mainnet idea: spending proposal that pays out over multiple events

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3476]
Reference: https://cointelegraph.com/news/coinlist-rally-40k-investors-rush-to-buy-rly-despite-price-pump

Idea:
* A proposal that allows for tokens to be sent to a single address, divided into individual, defined time periods.
* It should be possible to `veto` the proposal after approval, so that in the event of the recieving party not honoring the social agreement in place, the council can cut off any further funding.

Use-case:
* If governance wants to mint tokens for the purpose of public availability in the future for some reason (such as balancing current whales or whatever reason they decide to do so) they could use this proposal type to structure the payments. 
* This could also be used for incentivizing specific communities (such as an external Discord or other type of community) by enabling that community tokens that they can distribute at a subsidized rate or for free.

Downsides / weaknesses:
* Probably would be expensive & complext to implement, besides what other technical impacts it would have that are unknown to me.
* `Working Groups` can basically do this by just having the recieving party become a worker. Payments are already interval-based in this scenario. It also means that there is less need for individual decision making by the council. Discretionary payments could also be used for this purpose.
* The downside of using `Working Groups` would be that the amounts involved could be far more significant than their individual budget and any stake the lead has for the role.
* A `smart contract` (hosted on an external platform) may be able to achieve this and also still enable governance to `veto` and cut-off payments.

**Comment by bedeho** [comment]
> A proposal that allows for tokens to be sent to a single address, divided into individual, defined time periods.

I did not understand what this meant or how its different from a normal spending proposal.

**Comment by mochet** [comment]
> > A proposal that allows for tokens to be sent to a single address, divided into individual, defined time periods.
> 
> I did not understand what this meant or how its different from a normal spending proposal.

A normal spending proposal:
* `1m JOY` to `Bob` at `block 14,900,123`

This would be:
* `1m JOY` to `Alice` organized into `5 payments of 200k JOY`
1. `200k JOY` at `block 16,500,000`
2. `200k JOY` at `block 16,600,000`
3. `200k JOY` at `block 16,700,000`
etc

and at any point prior to the final payment, the proposal could be `vetoed` cutting off any further payments.

**Comment by traumschule** [comment]
Looks like this was just closed, not implemented, and multiple recipient funding requests are postponed: https://github.com/Joystream/joystream/issues/3355
