### ISSUE TITLE
Proposal to terminate a bounty

### ISSUE THREAD

**Issue by L3pereira** [Joystream/joystream#3493]
In certain situations, it may be necessary to terminate the bounty, the council should be able to propose this action.
The respective action will only be executed if the bounty is in the working period or judging period as described in more detail in #3193

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202024908049833) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Remember to add audit label when its part of the audit work, and also add to the audit project.

**Comment by L3pereira** [comment]
Commit f4b418b2e8c2c36a5d034bce2b9d33f786e1ba45 should be merged, after merging PR  Bounty perpetual working period #3485
