### ISSUE TITLE
Directly burn channel account funds

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3495]
When a channel account owned by the platform (i.e. a curator group), owns a channel which generates some kind of revenue in $JOY, then this should be recapturable by the DAO through a token burn. In order to not complicate permissions any further, and since its quite sensitive, and likely quite rare, lets make this a lead only action.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202024733703336) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
This could also be instead sent back to council budget.

**Comment by shamil-gadelshin** [comment]
Done: https://github.com/Joystream/joystream/pull/3562
