### ISSUE TITLE
Factor out budget interaction with council and working groups

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3496]
# Background
There will be an increasing number of places in the runtime where one wants to plug into the budget of the council of a working group. There is already some implementation code for this stuck in the bounty module, but this is not great.

https://github.com/Joystream/joystream/blob/olympia/runtime-modules/bounty/src/actors.rs#L151

# Proposal
Add code for this in the council and wg pallets, and expose it through convenient traits implemented by each pallet that allow:

* Check what the balance is of the budget.
* Spend x amount out of the budget into an account: make fallible if x is too big.
* Spend x amount out of the budget into an account: make infallible, since check can be done up-front. Just skip side-effect
* Credit x amount into budget: should be infallible. Does not need source of funds, just  `deposits`, as there may be caller specific rules about what sort of rules concerning locks/reservations to respect.

In each case, _the budget_ refers to the budget of the council or a specific WG. Hence, if some client pallet wants to interact with the council and 2 WGs in this way, three instances of the trait has to be passed, one for each.

It's probably advisable to to do factoring and updating dependencies which use new refactored code in one PR, I belive the following places are relevant
- content pallet
- storage pallet
- bounty pallet
- anything else?

**NB: Should be based on Rhodes**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202025602080201) by [Unito](https://www.unito.io)

**Comment by shamil-gadelshin** [comment]
Done
