### ISSUE TITLE
Module accounts getting removed from storage

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3497]
# Background

Looking at code which transfers funds from a module account, for example in the bounty module

https://github.com/Joystream/joystream/blob/d8481275bc958c4f3029a12423879eb789009e19/runtime-modules/bounty/src/lib.rs#L1698

it occurred to me that these accounts may frequently get entirely depleted, and this may trigger automated cleanup if they dip below existential limit. If this dip was not itself otherwise going to bring the balance literally to `0`, then it seems the use case has effectively become insolvent because funds have been removed in a way that surrounding business logic has not accounted for.

# Example

- Existential deposit limits is `100`.
- A bounty is created as follows
   1. Funded with `50` by member A
   2. Funded with  `60` by member B
   3. Final balance in bounty account is `110`.
- Bounty fails
- member B withdraws `60` in funding
- bounty module balance dips down, from `110` to `50`, which is below limit `100`, hence remaining  `50` gets auto-dusted, and we are now insolvent.

Notice that for the bounty module, a new account is created per bounty. For these causes, a natural sollution is to have a corresponding state bloat bond for that object which is > exitential deposit limit, which seems to have limited negative side-effets.

But there are also static module accounts, such as for the forum or content directory (so far), which are in essence global to a pallet, and also are not created or destroyed. Here it would be less clear how to deal with the problem.

# Question 

Is this accurate? if so, how should we deal with this in a way which is consistent and robust?

@shamil-gadelshin Lezek123 @ignazio-bovo L3pereira

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202028829466522) by [Unito](https://www.unito.io)

**Comment by L3pereira** [comment]
In the bounty pallet case, one solution would be the creator send a maintenance fee = existential limit (this fee is locked) to the bounty account, this will keep the account alive. Then when executing the last transfer (remove bounty) we unlock the fee and transfer the fee back to the bounty creator, and then the AllowDeath remove the bounty account.

**Comment by dobertRowneySr** [comment]
In the `pallet_token` account I established the rule:
if `free_balance + reserved_balance < existential_deposit` -> account is deleted

**Comment by bedeho** [comment]
> In the pallet_token account I established the rule:
> if free_balance + reserved_balance < existential_deposit -> account is deleted

But this is for $CRT accounts? right? in which case that is not the case I am talking about, I am talking about _module accounts_, for $JOY, only module accounts can become insolvent, as they are the ones which are pooling value for some business process.

**Comment by shamil-gadelshin** [comment]
There could be options to fix it with minimal changes:
- change all operations with such accounts to [Keep alive](https://docs.rs/frame-support/2.0.0/frame_support/traits/enum.ExistenceRequirement.html) having them incapsulated in some common module
- transfer some initial balance (equal to the ExistentialDeposit) to such accounts on the pallets' initialization (runtime upgrade code)

**Comment by bedeho** [comment]
> change all operations with such accounts to [Keep alive](https://docs.rs/frame-support/2.0.0/frame_support/traits/enum.ExistenceRequirement.html) having them incapsulated in some common module

I believe `Keep alive` just has the semantics that the operation will fail if it would result in the account falling below the extential limit, look here

https://paritytech.github.io/substrate/master/src/pallet_balances/lib.rs.html#1505

This would not be a solution for us. It would indeed prevent insolvency of the module account, but it would do it by keeping excess funds stuck. What we really need is a way for module accounts to be entirely exempt from this constraint.

> transfer some initial balance (equal to the ExistentialDeposit) to such accounts on the pallets' initialization (runtime upgrade code)

This feels a bit brittle, but the only real solution I am seeing for static module accounts, like we have for the content directory. For the bounty pallet, where you have module accounts dynamically created per bounty for example, then the state bloat bond for the bounty should in effect solve the problem. As @L3pereira is suggesting.

**Comment by bedeho** [comment]
Question: do we have any examples of module accounts that are static from FRAME pallets, and what they do?

**Comment by shamil-gadelshin** [comment]
Done for https://github.com/Joystream/joystream/issues/3510
