### ISSUE TITLE
Forum: `MaxCategories`

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#3498]
Don't know if this is a bug, or intended behavior, but the category related limits for the forum are:
```
    pub const MaxCategoryDepth: u64 = 6;
    pub const MaxSubcategories: u64 = 20;
    pub const MaxThreadsInCategory: u64 = 20;
    pub const MaxModeratorsForCategory: u64 = 20;
    pub const MaxCategories: u64 = 20;
  ```

Seeing this, I assumed there could be up to 20 top level categories, then 20 subcategories for each, etc. However, the limit appears to be 20 overall.

**Comment by bedeho** [comment]
Yes I think this is indeed as intended, so probably the runtime level constant should have been better documented.
