### ISSUE TITLE
Mainnet. Runtime. Generate benchmarks in proper conditions.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#3517]
We need to run benchmarks using proper conditions and parameters:

* reference hardware
* having set proper 'steps & repeats' parameters
* upgraded Substrate framework
* run benchmarking for the Substrate pallets (like frame_system)

This could solve some strange [issues](https://github.com/Joystream/joystream/pull/3393#discussion_r837536560) in the generated weights files.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202453971807315) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
We have to make sure we also estimate a range of different weight parameters that we for now are just taking as magic values from Substrate itself, things like
- time it takes to execute a no-op extrinsic: `BaseExtrinsicWeight`
- time it takes to execute an empty block: `BaseBlockWeight`
- time it takes to read on rocksdb
- time it takes to write on rocksdb

I believe there are tools for this already, such a this for the first two

https://github.com/paritytech/substrate/blob/f2d5ece14b335504f6ff00ebf3b625c56afbc5e3/utils/frame/benchmarking-cli/src/overhead/README.md

There may be other values we also need to regenerate, I have not done a proper review of all fee related code. We also have to make sure that we don't start mixing parameters because certain implementation related code inside Substrate code we use directly uses Substrate estimates, while we use our own estimates in other parts of the code we directly implement, such as weight-to-fee function.

@Lezek123 points out that there is ambiguity around what is even the actual reference hardware for which current values were generated, as the spec has been removed from documentation.

**Comment by mnaamani** [comment]
Ran weight generation on branch `carthage-weights-gen` on ref hardware AWS [c6id.2xlarge](https://aws.amazon.com/ec2/instance-types/c6i/) instance as recommended by [parity](https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#reference-hardware)

New computed weights can be seen in this diff: 9eb8286369169709e1030c3cb0d5e527b56f826b

The runtime upgrade fee test was adjusted to pass for new computed base weight 2a7b72152841587711370fd5bff5f0cbf445f21d

The [scripts/generate-weights.sh](https://github.com/Joystream/joystream/blob/9eb8286369169709e1030c3cb0d5e527b56f826b/scripts/generate-weights.sh) script ran for ~ 6.5H `(50 steps, 20 repeat)`

These are not the final weights, we need to compute them again once we have finalized runtime parameters https://github.com/Joystream/joystream/issues/4300 in addition to a few more pending runtime PR for carthage.

Interesting observation for the rocksdb weights: https://github.com/Joystream/joystream/commit/9eb8286369169709e1030c3cb0d5e527b56f826b#diff-b978eecce04c86872d71e8bc6650867f7f3941e3d55b16f8eb3bfe15ffc48335

We got lower values than ones found in substrate [codebase](https://github.com/paritytech/substrate/blob/493b58bd4a475080d428ce47193ee9ea9757a808/frame/support/src/weights/rocksdb_weights.rs#L26) which seem to be clearly set manually.
| weight | Substrate | Joystream |
|---------|-----------|-----|
|  read     |   25,000 |  13_282 |
| write | 100_000 | 55_820 |

Should we avoid re-generating them and just stick with "handcrafted" values?

```
time ./generate-weights.sh
Generating storage weights
Storage weights generated successfully
It took 1 seconds
Generating core weights
Core weights generated successfully
It took 30 seconds
Generating weights for frame_system...
Weights generated successfully for frame_system
It took 40 seconds
Generating weights for substrate_utility...
Weights generated successfully for substrate_utility
It took 19 seconds
Generating weights for pallet_session...
Weights generated successfully for pallet_session
It took 3 seconds
Generating weights for pallet_timestamp...
Weights generated successfully for pallet_timestamp
It took 2 seconds
Generating weights for pallet_vesting...
Weights generated successfully for pallet_vesting
It took 46 seconds
Generating weights for pallet_multisig...
Weights generated successfully for pallet_multisig
It took 98 seconds
Generating weights for pallet_staking...
Weights generated successfully for pallet_staking
It took 3243 seconds
Generating weights for pallet_balances...
Weights generated successfully for pallet_balances
It took 3 seconds
Generating weights for pallet_im_online...
Weights generated successfully for pallet_im_online
It took 6542 seconds
Generating weights for proposals_discussion...
Weights generated successfully for proposals_discussion
It took 933 seconds
Generating weights for proposals_engine...
Weights generated successfully for proposals_engine
It took 3567 seconds
Generating weights for proposals_codex...
Weights generated successfully for proposals_codex
It took 403 seconds
Generating weights for pallet_constitution...
Weights generated successfully for pallet_constitution
It took 3 seconds
Generating weights for working_group...
Weights generated successfully for working_group
It took 273 seconds
Generating weights for council...
Weights generated successfully for council
It took 392 seconds
Generating weights for referendum...
Weights generated successfully for referendum
It took 120 seconds
Generating weights for forum...
Weights generated successfully for forum
It took 265 seconds
Generating weights for membership...
Weights generated successfully for membership
It took 16 seconds
Generating weights for bounty...
Weights generated successfully for bounty
It took 1813 seconds
Generating weights for joystream_utility...
Weights generated successfully for joystream_utility
It took 3 seconds
Generating weights for storage...
Weights generated successfully for storage
It took 786 seconds
Generating weights for content...
Weights generated successfully for content
It took 5122 seconds
Generating weights for project_token...
Weights generated successfully for project_token
It took 286 seconds

real    400m9.727s
user    403m55.911s
sys     1m26.165s
```

cc: @bedeho @Lezek123 @ignazio-bovo
