### ISSUE TITLE
New Terminate Bounty extrinsic, veto_bounty removal

### ISSUE THREAD

**Issue by L3pereira** [Joystream/joystream#3523]
A new extrinsic `terminate_bounty` should allow the council to terminate the bounty (as Failed Bounty) in 

- Funding Period w/o contributions
- Working Period
- Judging Period

`Veto_bounty` allows the Council to remove a bounty in the funding period without contributions, this should be removed as its functionality is very similar to terminate_bounty

**Comment by bedeho** [comment]
Done.
