### ISSUE TITLE
Can't apply for a bounty: ConflictingStakes error

### ISSUE THREAD

**Issue by singulart** [Joystream/joystream#3526]
I am trying to apply for a bounty https://dao.joystream.org/#/bounty/preview/5 , the system fails the transaction.
[Error evidence](https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944/#/explorer/query/0x4b3308016c4229c03c1e2697fabc884dea18301a281326425cd43b6805b3ae73)

**Comment by mochet** [comment]
This is likely a Pioneer issue. Still investigating.

**Comment by mochet** [comment]
This is a Pioneer issue (https://github.com/Joystream/pioneer/issues/2739) so can be closed.

**Comment by singulart** [comment]
Closed as per comment above
