### ISSUE TITLE
Question: Why does the forum iterate through threads and subcategories upon category deletion?

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#3534]
Highlighted here: https://github.com/Joystream/community-repo/issues/737#issuecomment-1081884180
Another related issue: https://github.com/Joystream/joystream/issues/3498

Why does the extrinsic need to iterate through all threads?
Doesn't it make more sense for a category to be able to be deleted and just ignore all the threads it contains, since they can be cleaned up/moved after the fact.

I'm asking this because it seems like this whole process of iterating over every thread contained within a category is a massive scaling problem and sounds like its expensive to do for what seems like very little benefit.

What I would suggest instead is that the runtime doesn't care if a category still contains threads. Sure, a category could be accidentally deleted which may contain 100s of threads, but a new one could be created to replace that one in such an instance? and the threads could just be moved?

Without knowing `runtime magic` wouldn't removing this barrier allow for far more categories and allow for significantly increased scale?

**Comment by traumschule** [comment]
See https://github.com/Joystream/joystream/issues/761 and https://github.com/Joystream/joystream/issues/2545

> Doesn't it make more sense for a category to be able to be deleted and just ignore all the threads

It would be highly undesirable to have orphaned threads and categories (keyword [bloat](https://github.com/Joystream/joystream/search?q=bloat&type=issues)).

**Comment by mochet** [comment]
> See #761 and #2545
> 
> > Doesn't it make more sense for a category to be able to be deleted and just ignore all the threads
> 
> It would be highly undesirable to have orphaned threads and categories (keyword [bloat](https://github.com/Joystream/joystream/search?q=bloat&type=issues)).

But couldn't the forum WG lead can just be responsible for running a script or something that identifies orphaned threads?
It seems like this requirement to iterate over every thread/subcategory because the restraints mentioned here: https://github.com/Joystream/joystream/issues/3498
include this note:
> /// Upper bounds for storage maps and double maps. Needed to prevent potential block exhaustion during deletion, etc.
> /// MaxSubcategories, and MaxCategories should be reasonably small because when the category is deleted
> /// all of it's subcategories with their threads and posts will be iterated over and deleted.

So the runtime has to restrict the number of threads, categories and subcategories that exist because of this iteration.

**Comment by mochet** [comment]
I now understand why this is the case! closing
