### ISSUE TITLE
Tune Rhodes runtime parameter values

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3537]
We need to revisit and make sure that these make sense in light of what we have found, in particular its critical that invited members can do certain key things.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1202055944788386) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
This would be one known problem: https://github.com/Joystream/joystream/issues/3519#issuecomment-1083767929

**Comment by bwhm** [comment]
From `runtime/src/lib.rs` unless noted otherwise.

## Validator
```
pallet_staking_reward_curve::build! {
    const REWARD_CURVE: PiecewiseLinear<'static> = curve!(
        min_inflation: 0_050_000,
        max_inflation: 0_750_000,
        ideal_stake: 0_300_000,
        falloff: 0_050_000,
        max_piece_count: 100,
        test_precision: 0_005_000,
    );
}
```
- `max_inflation` from  0_750_000 to 0_180_000

## Forum

```
parameter_types! {
    pub const MaxCategoryDepth: u64 = 6;
    pub const MaxSubcategories: u64 = 20;
    pub const MaxThreadsInCategory: u64 = 20;
    pub const MaxPostsInThread: u64 = 20;
    pub const MaxModeratorsForCategory: u64 = 20;
    pub const MaxCategories: u64 = 20;
    pub const MaxPollAlternativesNumber: u64 = 20;
    pub const ThreadDeposit: u64 = 30;
    pub const PostDeposit: u64 = 10;
    pub const ForumModuleId: ModuleId = ModuleId(*b"mo:forum"); // module : forum
    pub const PostLifeTime: BlockNumber = 3600;
}
```
->
- `MaxCategories` from 20 to 40
  - Shamil sceptical
- `MaxSubcategories` from 20 to 40
  - Not sure if it's actually doing anything

## Proposals
```
pub(crate) fn set_council_budget_increment_proposal() -> ProposalParameters<BlockNumber, Balance> {
    ProposalParameters {
        voting_period: 72000,
        grace_period: 100800,
        approval_quorum_percentage: 66,
        approval_threshold_percentage: 80,
        slashing_quorum_percentage: 60,
        slashing_threshold_percentage: 80,
        required_stake: Some(200_000),
        constitutionality: 1,
    }
}
```
->
- `grace_period` from 100800 to 14400


## NFTs
`node/src/chain_spec/content_config.rs`
- `max_starting_price` - currently 1_000_000_000, let’s change to 1_000_000_000_000
- `max_bid_step` - currently 1_000_000, let’s change to 1_000_000_000_000

**Comment by traumschule** [comment]
*archiving from discord noise to GH noise*

> @l1dev has correctly pointed out that another "inflation curve" might be better, but as it was "approved" (https://dao.joystream.org/#/proposals/preview/124) we think this is so urgent that we'd rather change again following some research.

https://discord.com/channels/811216481340751934/813361923172335648/972201457342357596

> looks ok except ideal stake could be higher.
3500*.18/52 *24.6 /35 = $8.515 per validator week => 12M total / week ($300 + $20k in JOY, 16% / budget)
> The interesting part about very high ideal stake and slightly higher max inflation is that no one has to stop staking (to prevent rewards to drop). https://discord.com/channels/811216481340751934/812344657794301972/971076883678634034

> I don't really - this is one of those (these, really) parameters that we really need to research.
> I think the only good option is to make rewards adjustable with a proposal, because I don't think we, or anyone else, can get it "right".
https://discord.com/channels/811216481340751934/812344657794301972/971538533435203666

for your research: https://dao.joystream.org/#/proposals/preview/143
