### ISSUE TITLE
NFT query node - `auction` empty when querying NFT via `videos` query

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3549]
```
query {
  videos {
    id
    nft {
      transactionalStatus {
        __typename
        ... on TransactionalStatusAuction {
          auction {
            id
          }
        }
      }
    }
  }
}
```

This query will return `auction: null` even if the auction is there

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1202063420120581) by [Unito](https://www.unito.io)

**Comment by ondratra** [comment]
This issue was absorbed by https://github.com/Joystream/joystream/issues/3342. Also, has it's own issue in Hydra tickets https://github.com/Joystream/hydra/issues/396 .
