### ISSUE TITLE
NFT query node - improve finding open auction winner

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3551]
Currently, QN uses this code to find the winner of an open auction: https://github.com/Joystream/joystream/blob/rhodes/query-node/mappings/src/content/nft.ts#L264

This however isn't fully correct, as there can be multiple bids from multiple users for the same amount. If that's the case, there's a chance query node will pick the wrong winner. This depends on runtime event being extended with additional data

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1202063566321770) by [Unito](https://www.unito.io)

**Comment by ondratra** [comment]
This was fixed as part of https://github.com/Joystream/joystream/pull/3552.
