### ISSUE TITLE
NFT query node - querying across different event types

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3571]
### Rationale

Consuming events is important from client's perspective, mostly for constructing history or notification feeds. These types of features will almost always use multiple types of events to present state changes etc. It is also important for those feeds to be:
1. Chronological - so that actions can be traced step by step
2. Paginated - so that we can have a look deep into history without fetching thousands of objects at once
3. Filterable - so that users receive events relevant to them, or matching their specific query

### Problem

QN doesn't currently offer a way to query events that enable all 3 of the above items at the same time. There are 2 approaches that can be taken:

**`events` query:**

```graphql
query {
  events(
    where: { type_in: [AuctionBidMadeEvent, OpenAuctionBidAcceptedEvent] }
    orderBy: [inBlock_DESC]
  ) {
    type
    inBlock
    ... on AuctionBidMadeEvent {
      bidAmount
    }
    ... on OpenAuctionBidAcceptedEvent {
      contentActor {
        __typename
      }
    }
  }
}
```
This query gives us benefit of points 1 and 2 from above - since it's a single feed of items, we can apply sorting to all of them and paginate through this sorted list. However, filtering by event-specific fields (like member who made a bid) is not possible since query will only accept filters for fields shared via `Event` interface

**Separate queries:**
```graphql
query {
  auctionBidMadeEvents(where: { member: { id_eq: "9" } }) {
    bidAmount
  }
  openAuctionBidAcceptedEvents {
    ownerMember {
      handle
    }
  }
}
```
This query supports 1. (although not straightforward since client needs to apply sorting manually across queries) and 3. since filters can be applied to each query separately. Pagination doesn't work since there is no single feed to consume and combining multiple feeds on client will produce problems.

---

So with current queries we cannot fully support all the client's needs. We need a solution that can support all 3 of the features

### Solving it

IMO, it'd be best to use the single feed from `events` query and add filtering capabilities to it. This can be a bit tricky since filters will be different depending on the event type. Some proposals on schema:

```graphql
events(
  where: { type_in: [AuctionBidMadeEvent, OpenAuctionBidAcceptedEvent] }
  where_AuctionBidMadeEvent: { bidAmount_eq: "100" }
)

events(
  where: {
    type_in: [AuctionBidMadeEvent, OpenAuctionBidAcceptedEvent]
    AuctionBidMadeEvent_bidAmount_eq: "100"
  }
)

events(
  where: {
    type_in: [AuctionBidMadeEvent, OpenAuctionBidAcceptedEvent]
    event_json: { bidAmount_eq: "100" }
  }
)
```

Looking for feedback and suggestions

**Comment by bedeho** [comment]
- I understand why you want all of these properties (1-3), but 3 just fundamentally violates the idea of querying through an interface which is supposed to represents some base set of properties
- I think the only practical solution here is to just slightly augment our data model and add  separate event streams that mirror the needs of atlas, so `NFTEvents`, `CreatorToken` events, etc. Each interface represents the common features that you are interested in in each case. My hunch is that either GraphQL or Hydra does not properly support one entity implementing more than one interface properly. If this is the case, then we will just have to duplicate event types that are identical for each stream. The upside of this is that all of this is very _easy_. Mappings for this is trivial, its just adding the right new record to the right table. No later mutation or deletion. In the future Orion solves this, but now this is the only real alternative which is cheap, and does not require what I call Hydra-adventurism, where we try to make big changes to Hydra.

**Comment by kdembler** [comment]
I don't think what you proposed works. Even if you restrict stream's scope to only NFT events, each specific event will still have unique fields that you won't be able to place on an interface level. For example, we want notifications for a situation when user gets outbid, for that we would filter via `previousTopBid` on `AuctionBidMadeEvent`. This field will only exist for this specific event.

**Comment by bedeho** [comment]
Ah I see what you mean now, yeah that won't really be feasible unless we could write custom query logic, which we can't. 

How many of these cases are there?

**Comment by kdembler** [comment]
Depends on which cases you mean. The only "stream" of events we will need this for is NFTs at the moment. However, in this stream we will need to consume a couple of events:
- `AuctionBidMade` with filter for NFT owner OR previous top bid
- `BidMadeCompletingAuction` with filter for NFT owner
- `OpenAuctionBidAccepted` with filter for member whose bid got accepted OR list of specific IDs

**Comment by bedeho** [comment]
Sorry, I should have been much more precise: at this point, the main remedy is restricting scope to sidestep these cases. This however does require just evaluating how negatively this impacts the product in each instance where doing my solution would not work. For example, the case you gave of notifying when _your bid was replaced_, that is useful, but not a launch blocker at this point, I am happy to put that on the chopping block until we can address it properly. What are the other product features that you think cannot be easily solved for?

**Comment by bedeho** [comment]
Here is a list of product features, in particular notifications, that are affected by this limitation

1. someone purchased your NFT
2. you got outbid
3. someone bid on your NFT
4. you won an open auction (English auction was left out of scope, too complex)
5. an open auction where you have participated ended.

**Comment by bedeho** [comment]
For Rhodes we decided to rely on client side event processing to sidestep this problem for now.
