### ISSUE TITLE
Metaprotocol content category system

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3574]
# Background
We are dropping the previous native on-chain category system for videos and channels in favour of a metaprotocol system. Note: doing categories really insightfully will in the future require more thought, but right now we should just target making the least complicating transition w.r.t current Atlas features

# Proposal
Introduce _only_ video categories, drop channel categories, because Atlas does not use the latter, as metaprotocol messages. Specifically

* Only lead can add, remove or update categories.
* Categories can always be removed, even if in use by videos, hence videos must have a _nullable_ category relationship in the API schema.
* Channels are not in categories

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202392501970772) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
Done in #4181
