### ISSUE TITLE
Discussion: Should creator revenue split last forever?

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3586]
# Background

Current requirements

https://github.com/Joystream/joystream/issues/2362#issue-867837174

During a recent product discussion, the point was raised whether creator token issuers should be bound to have a given revenue split % forever, or if they should be able to change it (probably lower if it things worked well) later. This is my attempt to address this.

# Analysis

I think that if we force creators to only be able to offer tokens under the condition that they retain full discretion about updating revenue split in the future, then this is not an efficient arrangement, in the sense that it seems to be worth much less to the creator than what the prospective purchaser will be loosing, hence it being a net welfare loss which makes use of this instrument less prevalent and at a lower scale (i.e. less funds raised).

What I think can be even more efficient than our current design, which is that its set only once, is rather to expand the contracting space for all parties, by allowing the issuer to chose how long, possibly forever, the $CRT is locked into a given split defined at issuance. If the time period expires, then there has to be a final split out (or payout if you please :D), after which the split rate is 0. Now the creator could again, if we want to allow that, commit to a new split for a new period of time, and on we go. Now the parties can use private information about each issuance, which we will not know in advance, to find a better arrangement. This is not overly complicated to explain conceptually either.

Now this does beg the questions of under what circumstances would a non-perpetual split rate be efficient? My best guess would be if the creator

a. correctly anticipates that they have private information about the future, which they either cannot share, or cannot credibly convey, which leads the buyers to undervalue the $CRT.
b. buyers face some sort of financing constraint.

These seem plausible to me, and the added complexity here is not that substantial, technically or product wise, so I would suggest we go with this.

**Comment by kdembler** [comment]
Sounds good and I agree with your reasoning but I think we shouldn't underestimate the effort (product and technical). With NFTs we already had a couple of problematic cases because of async actions (settlement, poor notifications, etc.), I think this also may be a bit complex to explain in the UI so that users understand what will happen. I'm not saying we shouldn't do this, we should just be cautious. Potential simpler alternative would be to only allow decreasing the split %?

**Comment by dobertRowneySr** [comment]
>I think that if we force creators to only be able to offer tokens under the condition that they retain full discretion about updating revenue split in the future, then this is not an efficient arrangement, in the sense that it seems to be worth much less to the creator than what the prospective purchaser will be loosing, hence it being a net welfare loss which makes use of this instrument less prevalent and at a lower scale (i.e. less funds raised).

Can you elaborate on or give a small example, I am not understanding all the nuances...  
And about the proposal:
I am not sure if this is about:
a. allowing the possibility for a revenue split to last forever
b. allowing having a user defined split rate % for each split
c. the two above

**Comment by bedeho** [comment]
> Can you elaborate on or give a small example, I am not understanding all the nuances...

It is about whether the issuer 
A) has to commit to one explicit split percentage _forever_, or
B) can commit to an explicit percentage _for a stated period of time, say 12 months_, and then after this, they are free to commit again to whatever they want.
