### ISSUE TITLE
Issue permissioned CRT with small list of members

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3597]
Make it possible to launch a permissioned CRT with a small (i.e. constrained size `BTreeSet<MemberId>`) set of initial members, not only a merkle root like now. In this case, manually create account for each. In fact, lets allow specifying initial balance+vesting schedule as well for each, each having different one.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202115992837053) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
When creating a token issuer can specify permissioned mode with a merkle root that will contain all the whitelisted accounts.
Initial whitelist will specify at most `N` accounts for which merkle proof *won't be verified*. 
Now can exist accounts for which merkle verification succeeds and are not specified in the initial whitelist passed during issuance?
If so I immagine that such accounts will have to use `join_whitelist` to have their account created...

**Comment by bedeho** [comment]
> Now can exist accounts for which merkle verification succeeds and are not specified in the initial whitelist passed during issuance?

No, here the way the account is created is not using Merkle proof. It is just directly created as a result of the issuer doing it. This is for scenarios where the issuer wants to just get started more easily with a small number of initial accounts.

So there is no use of `join_whitelist`. I think even this extrinsic name is a bit confusing, perhaps we should just have called it `create_account` or something, because there isn't exactly a specific list.

**Comment by Lezek123** [comment]
I added the [`InitialAllocation` type](https://github.com/Lezek123/substrate-runtime-joystream/blob/creator-token-sales/runtime-modules/project-token/src/types.rs#L406) on my `creator-token-sales` branch, which is:
```rust
pub struct InitialAllocation<AddressId, Balance, VestingScheduleParams> {
    pub(crate) address: AddressId,
    pub(crate) amount: Balance,
    pub(crate) vesting_schedule: Option<VestingScheduleParams>,
}
```
And used inside `TokenIssuanceParameters`
```rust
pub struct TokenIssuanceParameters<Balance, Hash, InitialAllocation> {
    pub(crate) initial_allocation: InitialAllocation,
    // ...
```

It could be easily just changed to `initial_allocation: Vec<InitialAllocation>` to support this idea.

**Comment by bedeho** [comment]
@Lezek123 Looks solid.

**Comment by bedeho** [comment]
Captured in https://github.com/Joystream/joystream/pull/3618.
