### ISSUE TITLE
Update NFT limits: integrate moderation action permissioning system.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#3610]
Change updating channel NFT limits permissions from WG leaders to curators using the new permissioning system.

Related links:

* https://github.com/Joystream/joystream/issues/2651
* https://github.com/Joystream/joystream/pull/3609

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202129391558076) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Closed with https://github.com/Joystream/joystream/pull/3716
