### ISSUE TITLE
Enhance NFT minting limits

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3612]
# Background
https://github.com/Joystream/joystream/pull/3609

# Proposal
* Update to be mergable into `audit3`, not `ephesus`.
* Allow unlimited mode for limits, meaning there is no active constraint.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202133808413661) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
#### Background
The record containing all the current nft limits `(global, channel) x (weekly_limit, daily_limit)` is stored in the `content` pallet on chain state.
this is used by the[ `check_nft_limit` ](https://github.com/Joystream/joystream/blob/396df125e0290a2a693e0f398db6d6ac601846fd/runtime-modules/content/src/lib.rs#L2619)helper in the following extrinsics:
- [`create_video`](https://github.com/Joystream/joystream/blob/396df125e0290a2a693e0f398db6d6ac601846fd/runtime-modules/content/src/lib.rs#L848)
- [`update_video`](https://github.com/Joystream/joystream/blob/396df125e0290a2a693e0f398db6d6ac601846fd/runtime-modules/content/src/lib.rs#L939)
- [`issue_nft`](https://github.com/Joystream/joystream/blob/396df125e0290a2a693e0f398db6d6ac601846fd/runtime-modules/content/src/lib.rs#L1234)

Effectively controlling the nft issuance rate.

#### Question
1. Does this feature aims to drop `check_nft_limit`? (effectively removing any issuance rate constraints)
2. What is the purpose of the NFT limit related code now? Should it be also removed?

**Comment by bedeho** [comment]
Not removal, it means that it should be possible to both have unconstrained and constrained minting as two separate modes in the system. Meaning a lead can change this constraint in-flight.

**Comment by bedeho** [comment]
Done in https://github.com/Joystream/joystream/pull/3809
