### ISSUE TITLE
CRT Account Lifecycle

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#3617]
# Creation
Refers to the initialization and adding the `AccountData` record to pallet storage
## Permissioned Mode
Either one or another (see [this](https://github.com/Joystream/joystream/issues/3597#issuecomment-1099975963)).  
! permissioned accounts = all the accounts that are allowed to exists in `Permissioned` mode  
- **`(TO BE CONFIRMED)`**: CRT issuer (owner) will issue token in permissioned mode with a merkle `commit` holding the permissioned accounts (via `issue_token` **pallet method**).  users can then actively create their accounts with `join_whitelist` **extrinsic**, providing the merkle proof verification to assert that they are effectively part of the permissioned account set.  if they are successful at doing so they are expected to pay a **bloat bond** fees.
- CRT issuer (owner) can optionally pass a whitelist containing *all the accounts* during token issuance (via `issue_token` **pallet method**). **`(TO BE CONFIRMED)`**: No **bloat bond** is required in this case?
## Permissionless Mode
 - account `X` is created for CRT when existing account `Y` transfers $CRT to `X` (via `transfer` **extrinsic**). **In this case `Y` is expected to pay the bloat bond for** `X`. (And for all the `X`s in case of multi destination transfer)
 - buying into a sale into a new account
 - buying from the AMM into a new account (probably via a `bond` **extrinsic**)
In either cases an `AccountData` record is added to storage.
# Account Deletion
Refers to the `AccountData` record removal from storage. ([reference](https://github.com/Joystream/joystream/pull/3456#issuecomment-1099405766))
account deletion can happen only by a **user** initiated call to the `dust_account(origin, token_id, account_id)` **extrinsic**:
- if `origin` signer is `account_id` then deletion is successful regardless of the permission mode active or the residual balance in the account. In this case token supply has to be reduced by the residual balance deleted (effectively burning it)
- if `origin` signer is not `account_id` then first `AccountData` for account id has to be **empty** and the mode has to be `Permissionless`
# Bloat Bond Management
`AccountData` will contains also a `bloat_bond: ReserveBalance` field, containing the amount paid (in $JOYs) for the bloat bond.
The bloat bond itself can either be:
a. transferred to an internal module account, with the sole purpose of storing bloat bonds
b. burned from the user creating the account and later minted when user deletes his account

`=>` Based on the latest [PR review](https://github.com/Joystream/joystream/pull/3456#issuecomment-1099405766) **we decided to go with option a**.
When an account gets deleted the bloat bond specified in the `AccountData` record has to be transferred back  to the JOY balance for the account just deleted. 

**`(TO BE CONFIRMED)`**: This means that `BloatBond` **is not a module constant** and can be increased, decreased. This begs the question *how* (and *by whom*?)?

What is left is to establish when an account is considered **empty**, this definition has to take into account:
- `liquditity` (balance that can be freely used for transfer)
- `vesting_schedule` (balance that is distributed for a specified period at every block)
- `staked_balance` (balance staked in order to participate to revenue splits)

**`(TO BE CONFIRMED)`**: So a proper definition for *empty* would be:
- CRT account has `liquidity == 0` (balance that can be transferred)
- CRT is not vested (i.e. no vesting schedules for the account are *active*)
- CRT account `staked_balance == 0` (account has no balance staked)

**Comment by Lezek123** [comment]
> CRT issuer (owner) can optionally pass a whitelist containing all the accounts during token issuance (via issue_token pallet method). (TO BE CONFIRMED): No bloat bond is required in this case?

I added a comment about this [here](https://github.com/Joystream/joystream/issues/3597#issuecomment-1100089419).
I think in that case the issuer should pay the bloat bond for all accounts created.

> account X is created for CRT when existing account Y transfers $CRT to X (via transfer extrinsic). In this case X is expected to pay the bloat bond for Y. (And for all the Ys in case of multi destination transfer)

I think you meant that `Y` is expected to pay for `X` (since `Y` is the transfer sender and `X` is the new account in your example).

> Permissionless Mode:
> - ...
> - buying into a sale into a new account

In my opinion regardless of whether it's `Permissionless` or `Permissioned` token, the buyer should pay the bloat bond if the purchase results in new account beeing created.

You can buy a token on sale even when not beeing part of the `Permissioned` token whitelist, as implied by:
> Sale:
> - ... 
> - optional sale whitelist Merkle committment, payload stored in channel storage if provided. **If the transfer policy is permissioned, then all buyers present in this whitelist are automatically included in the transfer whitelist.**

_Source: https://github.com/Joystream/joystream/issues/2362_

> What is left is to establish when an account is considered empty

I made an attempt to implement it here: https://github.com/Lezek123/substrate-runtime-joystream/blob/creator-token-sales/runtime-modules/project-token/src/types.rs#L512
It requires that:
- `account.vesting_balances` is empty (no balances subject to vesting exist. They get automatically cleaned up once all the vested funds are used)
- `account.base_balance` is empty (basically no tokens that are **not** subject to vesting exist in the account)
- `account.reserved_balance` is empty (no tokens reserved for any reason exist in the account, although this should be already implied by the previous 2 checks)

**Comment by dobertRowneySr** [comment]
> I think you meant that Y is expected to pay for X (since Y is the transfer sender and X is the new account in your example)

Yes, I edited the original post. Thanks for the correction

**Comment by bedeho** [comment]
> vesting_schedule (balance that is distributed for a specified period at every block)

You are separating balances being vested from those involved in split, but we allow people to use unvested balances to get their split as well, I believe we agreed upon this a long while ago. What I don't remember is whether we allowed using only part of the balance, or it had to be the full amount (at the time).

I am seeing we are using many terms now, like vesting schedule, vesting balance, reserved balance, empty, liquid balance, and to me they are  ambiguous. I think we need to land a very strict terminology, and simply not use anything else.

I will need to just review a commit where all of this has been combined, and then we can have a call or something get everything harmonized.

**Comment by dobertRowneySr** [comment]
@bedeho : Do you think it is appropriate that a owner can delete his account even when it is not "empty"?

**Comment by bedeho** [comment]
What is empty though?

**Comment by dobertRowneySr** [comment]
Use this #3633 as reference, independently from the mode (Permissioned / Permissionless) can a user dust his (owned) account even if it is not empty?

**Comment by bedeho** [comment]
Ok, in that case, I suggest we _require_ it to be empty, but we also make sure that burning funds is also possible for funds that are vesting, if we have this new feature, then owner can make it empty is they want by doing a combination of such burning. 

Allow burning everything: https://github.com/Joystream/joystream/issues/3640


Is that ok?
