### ISSUE TITLE
Concept Synch: Project Token Accounts

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3633]
# Background

We are trying to introduce project token accounts which

- have simultanous vesting schedules
- have funds locked for splits, which can also come out of unvested funds
- have normal transferrable funds 

I don't think we need any notion of claiming or claimed amount as I am currently seeing, and since I don't have visibility into what is happening exactly with revenue splits - and how they interact with vesting, I wanted to write up a proposal we all could review and get synched on.

# Proposal

```Rust

struct VestingSchedule{

// NB: All values are immutable except during a live sale when someone can increase amounts by buying more.

  start_block: BlockNumber,
  duration: BlockNumber,
  post_cliff_total_amount: Balance,
  cliff_amount: Balance.
}

impl VestingSchedule {

  // Obvious semantics: how many tokens this schedule is preventing
  // from being transferred at this block
  // First constnat, then declines linearly with each block after cliff, until 0.
  pb fn locks(b: BlockNumber) -> Balance

}

struct StakingStatus {
  split_id: SplitId
  amount: Balance
}

impl StakingStatus {

  // Semantics: if `split_id` corresponds to a live split, then `amount`,
  // otherwise `0`.
  pb fn locks(b: BlockNumber) -> Balance
}

struct AccountData{
  vesting_schedules: BTreeMap<VestingSource, VestingSchedule>,
  split_staking_status: Option<StakingStatus>,
  amount: Balance,
}

impl AccountData {

  // Semantics: SUM[v:vesting_schedules, v.locks(b)]
  pb fn unvested(b: BlockNumber) -> Balance

  // Can be sent to someone or used with AMM.
  // Semantics: amount - split_staking_status.locks(b) - unvested(b)
  pb fn transferrable(b: BlockNumber) -> Balance

}
```

- Issuance goes into `AccountData::amount`.
- Patronage goes into `AccountData::amount`.
- Incoming transfer goes into `AccountData::amount`.
- Staking for splits allows any value up to `AccountData::amount`.
- Transferring `x` funds in block `b` requires `x - AccuntData::transferrable(b) >= 0`, and only side-effect is `AccuntData.amount -= x`
- When trying to participate in the sale in some block `b`, but `vesting_schedules` is full, then try to kick out any schedules that are `VestingSchedule::locks(b) == 0`.
- Dusting an account requires `AccountData::amount == 0`.

# Terminology

- **Empty:** `AccountData::amount == 0`
- **Transferrable Balance:** `AccountData::transferrable(b)`
- **Staked Balance:** `AccountData::split_staking_status::locks(b)`
- **Vesting Balance:** `AccountData::unvested(b)`

No other term is allowed: liquidity, reserved, reservability, free balance, usability... its all banished!

**Comment by Lezek123** [comment]
> Staking for splits allows any value up to AccountData::amount.

Does this mean that _unvested_ tokens can be used during splits? Because that would imply that `transferrable(b)` (which is `amount - split_staking_status.locks(b) - unvested(b)`) could be `< 0` (I assume we'll be using `saturating_sub`, so it just stays at `0` and doesn't underflow).

There is another question that arises from this: If we allow using _unvested_ tokens for splits, shouldn't we actually use a formula like `amount - max(split_staking_status.locks(b) - unvested(b))` (which would work similar to reusable locks - we just take the highest `lock` amount)

**Comment by bedeho** [comment]
> Does this mean that unvested tokens can be used during splits? 

Yes.

> Because that would imply that `transferrable(b) > 0` is possible, ..
> shouldn't we actually use a formula like amount - max(split_staking_status.locks(b) - unvested(b))

Yes I think that is wrong actually, but I think your suggestion is also wrong, shoudln't it be

`transferrable = amount - max(split_staking_status.locks(b), unvested(b))`

**Comment by Lezek123** [comment]
> Yes I think that is wrong actually, but I think your suggestion is also wrong, shoudln't it be
> transferrable = amount - max(split_staking_status.locks(b), unvested(b))

Yes, sorry for the typo.

**Comment by dobertRowneySr** [comment]
About `transferrable(b)`:
- `b` = current block number
- `A = AccountData::amount - AccountData::unvested(b)` (increased whenever new schedules are added)
- `B = StackingStatus::locks(b)` (increased whenever CRT are stacked, decreased when unstacked)

I believe the correct amount that can be transfered is `max(A - B, 0)` with semantics: Any amount greater than zero that is not stacked nor unvested can be transferred. We will be using `saturating_sub` to achieve this so no underflow errors are possible as pointed out by @Lezek123.
Everything else is ok.
Wouldn't it have been easier to specify a rate per block for the Vesting schedule (like https://github.com/paritytech/substrate/blob/9461b2de04210c6c193726a745c3ec6552b4ce9f/frame/vesting/src/vesting_info.rs#L61)? But the effect is the same in the end so ok.

**Comment by bedeho** [comment]
> I believe the correct amount that can be transfered is max(A - B, 0) with semantics:

You are by substracing _both_ unvested and locked for revenue split counting the same tokens twice? We should assume that when applying a revenue split, the tokens being locked will first exhaust possible vesting tokens, before eating into unvested tokens, anything else would be irrational for the user.

I guess we need to synch on this tomorrow.

> We will be using saturating_sub to achieve this so no underflow errors are possible as pointed out by @Lezek123.

We agreed this is to be implemented by @Lezek123 ? you are only to pull in, so you would not be doing any separate approach with `aturating_sub`? 

> Wouldn't it have been easier to specify a rate per block for the Vesting schedule.

I don't mind one way or the other, @Lezek123 can decide what feels more natural when he does the change.

**Comment by ignazio-bovo** [comment]
> You are by substracing both unvested and locked for revenue split counting the same tokens twice? 

No if stacking side effect is only: `StackingStatus::amount += x`. Plus I guess you meant
> transferring x funds in block b requires x - AccuntData::transferrable(b) >= 0
`transferrable(b) - x >= 0` :amount to transfer <= amount available for transfer

**Comment by bedeho** [comment]
# Summary

Here is a good dynamic example of an issuer who does a revenue split during the vesting.

![crt_account_dynamics(1)](https://user-images.githubusercontent.com/437292/165541011-12284385-afa4-41b0-9df5-fdb48bbdc381.png)

**Comment by dmtrjsg** [comment]
@bedeho Does the brown line starting ahead of red line rising up denoting that one can stake tokens that are locked in vesting schedule, or am I misreading this?

**Comment by bedeho** [comment]
> Does the brown line starting ahead of red line rising up denoting that one can stake tokens that are locked in vesting schedule, or am I misreading this?

💯
