### ISSUE TITLE
Project Token Revenue Split Tweaks

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3637]
As a result of product meeting we identified some needs

* All revenue splits must confront a universal lower bound on the time to start and duration, so as to give everyone fair access. These lower bounds can be stored as parameters in storage which will later be updatable with proposals, but not need to worry about those proposals now.
* ~It should be possible for the issuer to start a revenue split and stake their own $CRT holdings in one extrinsic.~
* It should be possible to stake for an ongoing revenue split by simultaneously unstaking for a prior one in one extrinsic.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202156232989995) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
>   All revenue splits must confront a universal lower bound on the time to start and duration, so as to give everyone fair access. These lower bounds can be stored as parameters in storage which will later be updatable with proposals, but not need to worry about those proposals now.

As of current implementation issuer can specify an optional `starting_block` and a duration, your request would be equiv. to:
- `starting_block - current_block >= LOWER_BOUND_ON_START`
- `duration >= LOWER_BOUND_ON_DURATION` (this is already implemented)

**Comment by bedeho** [comment]
Yep ;)

But make these bounds storage variables, not constants, we are going to move away from all constants.

**Comment by dobertRowneySr** [comment]
Ok, and when the optional starting block is **NOT SPECIFIED** should the constraint above be respected anyways, namely:
`starting_block := current_block + LOWER_BOUND_ON_START` in that case

**Comment by bedeho** [comment]
Yep ;)

**Comment by dobertRowneySr** [comment]
Now however we have another problem:
According to [specs](https://github.com/Joystream/joystream/issues/2362):
> During this period, any token holder (not member, token holder!) can claim part of the revenue split by staking the $CRT balance in an account. 

The tweaks would require the issuer to stake **immediately** in the block the revenue split is issued. However the first tweak require user to wait at least `LOWER_BOUND_ON_START` before allowing staking.
Should I break this rule for the token issuer?

**Comment by bedeho** [comment]
> The tweaks would require the issuer to stake immediately in the block the revenue split is issued

Why? Why can't a $CRT staker stake any time during the split being live? so during `[starting_block, starting_block + duration]` ?

**Comment by dobertRowneySr** [comment]
if `issue_revenue_split` happens at `current_block ` this means that `starting_block >= current_block + LOWER_BOUND_ON_START` and users
can only stake during `[starting_block, starting_block + duration)`.
CRT issuer wanting to issue a a revenue split and staking at the same time means issuing and staking at `current_block < starting_block`

**Comment by bedeho** [comment]
Conclusion from quick call:

Yes, if we are to allow instant cashout during split staking AND splits starting in the future, then that conflicts with (2) in the original issue, so we should discard this latter objective.
