### ISSUE TITLE
Allow burning all funds

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3640]
Allow burning funds even if they are subject to vesting or staking. I don't think this should cause any trouble, but double check!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202159598893522) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
No burning extrinsic is currently implemented, needs to be added

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/3782
