### ISSUE TITLE
Revising destination of proceeds in NFT transactions

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3650]
# Background

In `Rhodes`, I reviewed the impact of NFT ownership, reward account status for the destination of funds in both an auction and buy now scenarios for the purpose of harmonizing 

## Auction

This table summarizes destination of revenue (not royalties) when an auction is completed.

| NftOwner vs. Channel Reward Account | Not | Set |
|---------------------------|-----|-----|
| `NftOwner::Member` | member controller account | member controller account |
| `NftOwner::ChannelOwner` who is `Member` | burned | reward account  |
| `NftOwner::ChannelOwner` who is `CuratorGroup` | burned | reward account |

## Buy Now

This table summarizes destination of revenue (not royalties) when buy now (not in an auction) is completed.

| NftOwner vs. Channel Reward Account | Not | Set |
|---------------------------|-----|-----|
| `NftOwner::Member` | follows rules of two rows below: BUG! | reward account: BUG! |
| `NftOwner::ChannelOwner` who is `Member` | member controller account | reward account  |
| `NftOwner::ChannelOwner` who is `CuratorGroup` | _impossible_ * | reward account |

_* its not possible for a curator group owned channel to sell an NFT through channel ownership when there is no reward account._ 

# Proposal

Update payouts to work as follows for both `rhodes`, `ephesus` and `audit3`. Obviously, in the latter two, the channel reward account not set variations automatically go away. The bugs have been isolated in a separate issue

https://github.com/Joystream/joystream/issues/3648

## Auction

This table summarizes what happens with revenue (not royalties) when an auction is completed.

| NftOwner vs. Channel Reward Account | Not | Set |
|---------------------------|-----|-----|
| `NftOwner::Member` | member controller account | member controller account |
| `NftOwner::ChannelOwner` who is `Member` | **member controller account** | reward account  |
| `NftOwner::ChannelOwner` who is `CuratorGroup` | burned | reward account |

## Buy Now

This table summarizes what happens with revenue (not royalties) buy now (not in an auction) is completed.

| NftOwner vs. Channel Reward Account | Not | Set |
|---------------------------|-----|-----|
| `NftOwner::Member` | **member controller account** | **member controller account** |
| `NftOwner::ChannelOwner` who is `Member` | member controller account | reward account  |
| `NftOwner::ChannelOwner` who is `CuratorGroup` | **burned** | reward account |

**Comment by dobertRowneySr** [comment]
There is also a `complete_nft_offer` that probably should require a similar behavior to the above tables: https://github.com/Joystream/joystream/blob/656679a4501114709c5a3b5f88583c3913ad28ec/runtime-modules/content/src/nft/mod.rs#L250
Behavior as of **now**


|NftOwner vs. Channel Reward Account | Not | Set
-- | -- | --
|NftOwner::Member | member controller account | reward account|
|NftOwner::ChannelOwner who is Member | member controller account | reward account|
|NftOwner::ChannelOwner who is CuratorGroup | impossible * | reward account|

**Comment by bedeho** [comment]
- `ensure_owner_account_id` this name really ought to be changed, its not clear what it does, but the name does not seem to capture it. Also, we never do `.map_err(|_| Error::<T>::MemberProfileNotFound)?;` on looking up members which have been already validated, because members are never ever removed. So we just do
- I don't think the table corresponds to what is behaviouir **now**. Basically `ensure_owner_account_id` is the determinant of who is paid, and it's behaviour is basically to pay member if owner, otherwise reward account if set, otherwise reject. This gives table

|NftOwner vs. Channel Reward Account | Not | Set
-- | -- | --
|NftOwner::Member | member controller account | member controller account |
|NftOwner::ChannelOwner who is Member | impossible | reward account|
|NftOwner::ChannelOwner who is CuratorGroup | impossible | reward account|

- **Please confirm that am correct or incorrect.**
- As @kdembler said, I believe it should just be the same table as the other cases above, so perhaps `ensure_owner_account_id` should just be dropped.

**Comment by bedeho** [comment]
Fixed.
