### ISSUE TITLE
Expose bucket selection in content directory extrinsics

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3652]
# Background
`UploadParameters` in storage pallet has fields

```Rust
    /// Chosen storage buckets to assign on the dynamic bag creation.
    pub storage_buckets: BTreeSet<StorageBucketId>,

    /// Chosen distribution buckets to assign on the dynamic bag creation.
    pub distribution_buckets: BTreeSet<DistributionBucketId>,
```

but they seemingly have no purpose, as such buckets are only provided by user during dynamic bag creation, not on subsequent data uploads. Also confirmed by the fact that `content` pallet only passing in default constructed, i.e. empty, sets as parameters upon upload.

# Proposal
1. Remove these fields
1. Update content pallet which passes default values

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202167659515051) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
We have
```rust
/// Alias for the parameter record used in upload data
pub type UploadParameters<T> = UploadParametersRecord<
    BagIdType<MemberId<T>, <T as Trait>::ChannelId>,
    <T as frame_system::Trait>::AccountId,
    BalanceOf<T>,
    <T as Trait>::StorageBucketId,
    DistributionBucketId<T>,
>;

/// Alias for the parameter record used in create bag
pub type DynBagCreationParameters<T> = UploadParametersRecord<
    DynamicBagId<T>,
    <T as frame_system::Trait>::AccountId,
    BalanceOf<T>,
    <T as Trait>::StorageBucketId,
    DistributionBucketId<T>,
>;
```

If we want to remove the buckets fields from the `UploadParameters` system we need should introduce a new `struct` that would be a variation on `UploadParameters`.
Since we are planning to refactor the `try_mutate_storage` function in the future, which will probably have some effect on this,
 I would suggest batching these two task together later on (given that this refactor it's not a urgent priority)

**Comment by bedeho** [comment]
> If we want to remove the buckets fields from the UploadParameters system we need should introduce a new struct that would be a variation on UploadParameters.

I don't understand this reply.

Basically, I don't see any code in the `storage` pallet that actually uses these fields, so they can just be dropped both in that pallet and in the `content` pallet. What am I missing?

**Comment by bedeho** [comment]
From internal convo ,seeing now that I missed `DynBagCreationParameters`, so lets just make two separate structs here, and remove the fields from `UploadParameters`  as planned.

**Comment by bedeho** [comment]
Done in https://github.com/Joystream/joystream/pull/3804
