### ISSUE TITLE
Carthage Release Plan

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3666]
# Name
`Carthage`

# Brand

<img width="400" alt="Neutral" src="https://user-images.githubusercontent.com/437292/174857534-af7841b4-770b-4a84-a180-a683b78dee6c.png">

# Goals

The meta goal here is to do the one final big release which makes us ready for mainnet, to be specific

## Deployment

A new chain: https://github.com/Joystream/joystream/issues/3792

# Overview

The runtime feature scope which is being integrated here is

- Upgrading to Substrate V3.
- Integrating fixes from recent quarkslab audit.
- Creator tokens pallet: not exposed in Atlas.
- Creator payouts features: not exposed in Atlas or Pioneer.
- Bounties V2: not exposed in Pioneer.
- Various improvements and bug fixes.
- Real token issuance.
- Genesis accounts with vesting and multisignature ownership.
- Fully benchmarked runtime on reference hardware.
- Introduction of non-zero fees.
- Rollout with sudo phase which filters non-essential extrinsics while bootstrapping.
- Otherwise same runtime as `Rhodes`

Importantly
- Set of proposals should be same as in `Rhodes`.
- There is range of minor runtime features which we are [disabling](https://github.com/Joystream/joystream/issues/3882) in the interest of making QN work simpler, and also because they are not exposed in any product yet.

## Parameters

Beyond this, a coherently set parameter repertoire, only adapted to make our shorter time scale testnets work.

## Migration

We will only migrate accounts and memberships over.

## Infrastructure

The big challenge outside the runtime is to update QN support for the new content directory, and make storage (Colossus) and distributor (Argus) work with updated content and storage schemas, and also with fees.

## Incentives

This is preliminary

- FM $JOY allocations continue to earnable as before.
- $tJOY will cease to be something people can cashout, mainly because lots of $tJOY stakeholders in `Carthage` just should not be able to cashout.
- if worker incentives are too low, we can choose to supplement $JOY rewards with normal cash payments directly, but not through $tJOY.
- there will be a manual incentive where we encourage select creators to republish on `Carthage`.
- since people cannot cashout $tJOY any longer, there will be some window of time where we allow people to cashout before `Carthage` goes live.

## Apps

The major challenges in Pioneer, Atlas and CLI will be to

- Ensure they work properly with fees
- Use new token issuance and denomination

Everything beyond this will be opportunistic improvements which are synergistic with the launch itself, so there will be much less focus on long term goals, even though they may be very valuable.

## Integration Test

We have a very substantial backlog of broken network integration tests, when the infrastructure team is done with core work, they will immediately transition focus to get all of these to work properly.

## QA

While there are not many new features, the a key objective here will be to make sure people have access to the funds they believe they should, and that they are able to use funds properly, despite being locked by vesting.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202173793424641) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
Regarding `3.` from `Goals`
> 3. Real mainnet genesis bootstrapping
Does real in this instance mean a fully finalized genesis bootstrapping?

Related issue: https://github.com/Joystream/marketing/issues/260

**Comment by bedeho** [comment]
No, real bootstrap means the process of creating members, and in the past also importing content, its not about balances.
