### ISSUE TITLE
Init transactional status doesn't work with Open Auction Id

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#3669]
It checks for NFT existence for setting the initial auction nonce before nft is created -> bug

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202188702226921) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
I did not really understand, restate ?

**Comment by bedeho** [comment]
Now merged in `rhodes`, how do we get this into `ephesus`.

**Comment by dobertRowneySr** [comment]
I will open another PR targeting `ephesus`

**Comment by bedeho** [comment]
Closing, make separate issue with ephesus label, messes up Asana.
