### ISSUE TITLE
commentCreatedEvents error

### ISSUE THREAD

**Issue by rafalpawlow** [Joystream/joystream#3683]
The following query produces an error, probably because of nesting. We should be able to query this event by `channel` or `video`.

```
query GetCommentsNotifications($channelId: ID, $limit: Int!) {
  commentCreatedEvents (
    where: { comment: { video: { channel: { id_eq: $channelId } } } }
    limit: $limit
    orderBy: [createdAt_DESC]
  ) {
    comment {
      id
      createdAt
      video {
        id
        title
      }
    }
  }
}
```
![Zrzut ekranu 2022-04-28 o 10 38 37](https://user-images.githubusercontent.com/13706246/165732591-5edaebfd-3b7d-4b08-92f8-e9c1f34c7e2e.png)

**Comment by kdembler** [comment]
@zeeshanakram3 Could we add `video` directly to this event type?
