### ISSUE TITLE
Update CLI to work in Carthage

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3689]
# Background
We will both be updating the query node and runtime in substantial ways.

# Proposal
Update CLI to work in Carthage, with the priority of just maintaining functionality in the already existing feature set, and perhaps **even disabling things which are not critical for integration testing code or usage**, but which is expensive to fix. Fees will be non-zero, covering both size of extrinsic parameters, and also computational costs. This may warrant even some redesigns to clarify how choices impact fees, but this should be left out of scope in this work, that can be a future enhancement. Work should be done in two stages

1. Map out scope of changes neeeded to be done, write up reply here and share with release team.
1. Do the work.

Note: Ask bwhm about what truly absolute minimal scope is.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202202568644150) by [Unito](https://www.unito.io)

**Comment by zeeshanakram3** [comment]
Addressed in #4084
