### ISSUE TITLE
Bug: Storage pallet charging total storage fee each time

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3697]
It seems the storage pallet is charging the total storage fee each time you do an upload 🤯.
Lets do two things

1. Verify that this is real
1. Determine why tests did not catch this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202210124089773) by [Unito](https://www.unito.io)

**Comment by L3pereira** [comment]
This is not a real bug
https://github.com/Joystream/joystream/blob/656679a4501114709c5a3b5f88583c3913ad28ec/runtime-modules/storage/src/lib.rs#L4523-L4527

When we create a bag, the branch chosen  will be 
`BagOperationParams::<T>::Create(..) => NetDeletionPrize::<T>::Pos(dp),`

So the init_net_prize is positive which means we have to pay, 
protecting the chain from the creation of an infinite amount of empty bags. 

if we update the bag, the default branch is chosen  
`_ => Default::default(),`
In this case, the init_net_prize is zero, which means we pay only once for storing the bag and then we pay an amount related to the size of each object we added to the bag (not the size of all objects in the bag).

If we delete the bag 
`BagOperationParams::<T>::Delete => NetDeletionPrize::<T>::Neg(dp),`

the object init_net_prize is negative which means that the bag creator will receive the dynamic_bag_deletion_prize_value

So we pay 

- one time fee for creating a bag (`dynamic_bag_deletion_prize_value`)

- 1 fee ( `data_object_deletion_prize_value` ) for each object added

- 1 fee (`storage_fee`) for the total size in bytes of objects added

we receive

- 1 fee ( `data_object_deletion_prize_value` ) for each object deleted
- 1 fee ( `dynamic_bag_deletion_prize_value` ) for deleting a bag

**Comment by bedeho** [comment]
But you are disregarding the main point of the issue: the storage fee?

```Rust
let storage_fee = Self::calculate_data_storage_fee(new_voucher_update.objects_total_size);
```

This fee, which I believe is the _total fee_, including both existing and new objects, is _added_ to `net_prize` and returned.
You say its " for the total size in bytes of objects added", but I dont think so. IT is computed from `new_vouched_update.objects_total_size`, and this is new total size, not _increase_ in size.

**Comment by L3pereira** [comment]
I disagree,  this new voucher has the objects i want to upload. Look at `try_mutating_storage_state` called from `upload_data_objects(params: UploadParameters<T>)`
`object_creation_list` is an input parameter, It doesn't have all the bag objects.
https://github.com/Joystream/joystream/blob/656679a4501114709c5a3b5f88583c3913ad28ec/runtime-modules/storage/src/lib.rs#L3264-L3273

then the new voucher is constructed from the BagOperation we previously constructed with the `object_creation_list`
https://github.com/Joystream/joystream/blob/656679a4501114709c5a3b5f88583c3913ad28ec/runtime-modules/storage/src/lib.rs#L4368-L4377

Maybe it's better to run a test with all of this working, maybe I'm missing something

**Comment by L3pereira** [comment]
We have a bug indeed, When reviewing the code I missed this function `retrieve_dynamic_bag`, this is updating the VoucherUpdate with old values, making the storage fee higher than it should be
https://github.com/Joystream/joystream/blob/656679a4501114709c5a3b5f88583c3913ad28ec/runtime-modules/storage/src/lib.rs#L4359-L4365

This might not have been detected in tests since the values tested normally are too small and the calculate_data_storage_fee 
has the following code 
https://github.com/Joystream/joystream/blob/656679a4501114709c5a3b5f88583c3913ad28ec/runtime-modules/storage/src/lib.rs#L3915-L3927

when we check the balance after the tests we can be misslead by 
```rust 
     if bytes % ONE_MB > 0 { 
         megabytes += 1; // rounding to the nearest greater integer 
     } 
```
if we upload  2 objects of 10 bytes each (20bytes) we have a fee of `1Mb (rounded) * fee_per_mb`
if then we upload another one, with this bug we have 30 bytes  which is again -> '1Mb (rounded) * fee_per_mb`
If we didn't have a bug we would have paid for the third object  10bytes but this again is 1Mb (rounded)

Now if we calculate this for Mb objects we have total different result, with this bug we pay `3Mb * fee_per_mb`
and without bug we pay `1Mb * fee_per_mb`
```rust 
fn upload_bug_accumulates_old_objects() {
    build_test_externalities().execute_with(|| {
        let initial_balance = 1000;
        increase_account_balance(&DEFAULT_MEMBER_ACCOUNT_ID, initial_balance);

        increase_account_balance(&OTHER_MEMBER_ACCOUNT_ID, initial_balance);

        let data_object_per_mega_byte_fee = 50;
        set_data_object_per_mega_byte_fee(data_object_per_mega_byte_fee);

        let data_object_deletion_prize = 10;
        set_data_object_deletion_prize_value(data_object_deletion_prize);

        let dynamic_bag_deletion_prize_value = 5;
        set_bag_deletion_prize_value(dynamic_bag_deletion_prize_value);

        let data_object_id_1 = 0_u64;
        let data_object_id_2 = 1_u64;

        let first_upload_data_objects = 
        vec![DataObjectCreationParameters {
                size: ONE_MB,
                ipfs_content_id: create_cid(data_object_id_1 as u32),
            },
            DataObjectCreationParameters {
                size: ONE_MB,
                ipfs_content_id: create_cid(data_object_id_2 as u32),
        }];
        // let storage_buckets = create_storage_buckets(DEFAULT_STORAGE_BUCKETS_NUMBER);

        UpdateStorageBucketsVoucherMaxLimitsFixture::default()
            .with_new_objects_size_limit(5* ONE_MB)
            .with_new_objects_number_limit(10)
            .call_and_assert(Ok(()));

        let storage_buckets = CreateStorageBucketFixture::default()
            .with_origin(RawOrigin::Signed(STORAGE_WG_LEADER_ACCOUNT_ID))
            .with_objects_limit(DEFAULT_STORAGE_BUCKET_OBJECTS_LIMIT)
            .with_size_limit(5* ONE_MB)
            .create_several(DEFAULT_STORAGE_BUCKETS_NUMBER);
        
        let dynamic_bag_id = DynamicBagId::<Test>::Member(DEFAULT_MEMBER_ID);

        CreateDynamicBagFixture::default()
            .with_bag_id(dynamic_bag_id.clone())
            .with_storage_buckets(storage_buckets)
            .with_expected_dynamic_bag_deletion_prize(Storage::dynamic_bag_deletion_prize_value())
            .with_expected_data_object_deletion_prize(Storage::data_object_deletion_prize_value())
            .with_expected_data_size_fee(Storage::data_object_per_mega_byte_fee())
            .call_and_assert(Ok(()));

        let bag_id = BagId::<Test>::Dynamic(dynamic_bag_id.clone());

        let upload_params = UploadParameters::<Test> {
            bag_id: bag_id.clone(),
            deletion_prize_source_account_id: DEFAULT_MEMBER_ACCOUNT_ID,
            object_creation_list: first_upload_data_objects,
            expected_data_size_fee: Storage::data_object_per_mega_byte_fee(),
            expected_data_object_deletion_prize: Storage::data_object_deletion_prize_value(),
            expected_dynamic_bag_deletion_prize: Storage::dynamic_bag_deletion_prize_value(),
            ..Default::default()
        };

        UploadFixture::default()
            .with_params(upload_params.clone())
            .call_and_assert(Ok(()));

        assert!(<crate::DataObjectsById<Test>>::contains_key(
            &bag_id,
            &data_object_id_1
        ));

        assert!(<crate::DataObjectsById<Test>>::contains_key(
            &bag_id,
            &data_object_id_2
        ));

        assert_eq!(
            Balances::usable_balance(&DEFAULT_MEMBER_ACCOUNT_ID),
            initial_balance 
            - dynamic_bag_deletion_prize_value //bag creation fee
            - 2 * data_object_deletion_prize //2 data objects upload fee
            - 2 * data_object_per_mega_byte_fee // 2MB objetcs size fee
        );

        assert_eq!(
            Balances::usable_balance(&<StorageTreasury<Test>>::module_account_id()),
            dynamic_bag_deletion_prize_value
            + 2 * data_object_deletion_prize
        );

        let data_object_id_3 = 2_u64;
        let second_upload_data_objects = 
        vec![DataObjectCreationParameters {
                size: ONE_MB,
                ipfs_content_id: create_cid(data_object_id_3 as u32),
        }];

        let upload_params = UploadParameters::<Test> {
            bag_id: bag_id.clone(),
            deletion_prize_source_account_id: DEFAULT_MEMBER_ACCOUNT_ID,
            object_creation_list: second_upload_data_objects,
            expected_data_size_fee: Storage::data_object_per_mega_byte_fee(),
            expected_data_object_deletion_prize: Storage::data_object_deletion_prize_value(),
            expected_dynamic_bag_deletion_prize: Storage::dynamic_bag_deletion_prize_value(),
            ..Default::default()
        };

        UploadFixture::default()
            .with_params(upload_params.clone())
            .call_and_assert(Ok(()));

       assert!(<crate::DataObjectsById<Test>>::contains_key(
            &bag_id,
            &data_object_id_3
        ));
        //This will fail because in reality we will have
        assert_eq!(
            Balances::usable_balance(&DEFAULT_MEMBER_ACCOUNT_ID),
            initial_balance 
            - dynamic_bag_deletion_prize_value //bag creation fee
            - 3 * data_object_deletion_prize //3 data objects upload fee
            - 2 + (2+ 1) * data_object_per_mega_byte_fee // 5MB objetcs size fee <------------------------------------------------
        );
       we should have
        assert_eq!(
            Balances::usable_balance(&DEFAULT_MEMBER_ACCOUNT_ID),
            initial_balance 
            - dynamic_bag_deletion_prize_value //bag creation fee
            - 3 * data_object_deletion_prize //3 data objects upload fee
            - 3 * data_object_per_mega_byte_fee // 3MB objetcs size fee <------------------------------------------------
        );

        assert_eq!(
            Balances::usable_balance(&<StorageTreasury<Test>>::module_account_id()),
            dynamic_bag_deletion_prize_value
            + 3 * data_object_deletion_prize
        );
    });
}
```
