### ISSUE TITLE
NFT query node - `ownedNftConnection` still not working properly

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#3722]
Check this query (I run it on https://atlas-dev.joystream.org/orion/graphql): 

```graphql
fragment NftFields on OwnedNft {
  id
  transactionalStatus {
    __typename
  }
  transactionalStatusAuction {
    id
  }
}

query {
  ownedNfts(where: { id_eq: "6" }) {
    ...NftFields
  }

  ownedNftsConnection(where: { id_eq: "6" }) {
    edges {
      node {
        ...NftFields
      }
    }
  }
}
```

You can see that for the `ownedNfts` query, NFT's transactional status is returned properly, however for the `ownedNftsConnection` both `transactionalStatus` and `transactionalStatusAuction` are null which should never happen

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1202244712458791) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
I ran the fixed QN against staging network with one NFT unfortunately there is still `null` for `transactionalStatus`. `transactionalStatusAuction`  is not null. 

<img width="911" alt="Screen Shot 2022-05-10 at 11 09 15 PM" src="https://user-images.githubusercontent.com/1621012/167704077-fd6b46c2-2053-4128-a6f1-907d90757f42.png">

**Comment by kdembler** [comment]
That's fine, only one of those should be not null, initially this was a single variant called `transactionalStatus` but we had to "flatten" auction to a separate field because of Hydra issues with variants
