### ISSUE TITLE
Missing event for binding stake account

### ISSUE THREAD

**Issue by RafalPloszka** [Joystream/joystream#3729]
Working on https://github.com/Joystream/pioneer/issues/2521 I was unable to retrieve the lock date (createdAt) for `bind staking account` lock so probably an event for it is needed.

**Comment by thesan** [comment]
@RafalPloszka it looks to me like the event is `StakingAccountAddedEvent`. I'm closing the issue for now, please reopen it if I'm wrong about this event

**Comment by RafalPloszka** [comment]
Of course :man_facepalming: thanks!
