### ISSUE TITLE
Project tokens are owned by members not raw accounts

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3743]
# Background
https://github.com/Joystream/joystream/issues/2362#issuecomment-1088722206

# Proposal
Do that, but probably best to do _after_ both sales and revenue splits have been merged, but before AMM work is started.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202266620134532) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/3755
