### ISSUE TITLE
QN processor: use all available cores (threads)

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#3748]
Processing blocks can be slow (100k per day) although multiple cpu are unused. Either use all -1 available automatically or make it configurable

Related:
- As mentioned in https://github.com/Joystream/hydra/issues/205 it needs a benchmark mode / logging to investigate (without changing code) which operations consume most time. https://github.com/Joystream/hydra/issues/178
- If indexer is the indeed the bottleneck as suggested in https://github.com/Joystream/hydra/issues/205#issuecomment-781985348 requests to indexer and mapping should happen asynchronously / in threads.

**Comment by bedeho** [comment]
> Processing blocks can be slow (100k per day) although multiple cpu are unused. Either use all -1 available automatically or make it configurable

Processing blocks is not a parallelisable activity, really. You would need very very deep changes to unlock this, similar to what Solana does for its core execution layer, where transactions/mappings have to precommit to what part of the database they will touch

> https://github.com/Joystream/hydra/issues/205

Yeah this work really needs much more baseline investigation. I think its not worth investing in doing super complex changes to Hydra to unlock this, while we are still expecting to transition to `Subsquid`. If we ever concluded that that transition was off the table permanently, then yes, such deep changes start to become worth entertaining again.

**Comment by traumschule** [comment]
In that case for future releases to avoid downtime we should inform providers with instructions earlier when QN types are updated and a full re-sync is necessary.
