### ISSUE TITLE
Set Inflation Curve Proposal

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#3749]
The council would be best suited to tune validator rewards on the fly.

This requires a new proposal type on the runtime side, QN, pioneer.

ref https://github.com/Joystream/joystream/issues/3537#issuecomment-1125496229

**Comment by bedeho** [comment]
This seems related

https://github.com/Joystream/joystream/issues/3702

is it basically the same goal?

**Comment by traumschule** [comment]
#3702 looks very similar indeed, closing as duplicate.
