### ISSUE TITLE
Unsafe JOY transfers

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3760]
It seems like the problem mentioned in https://github.com/Joystream/joystream/issues/3759 also occurs in other modules that, for example, use `bloat_bond` refunding.

**Example unsafe scenario (bloat bonds):**

* `bloat_bond < ExistentialDeposit`
* a refund is done by calling `<balances::Module<T> as Currency<T::AccountId>>::transfer` from `module_treasury_account` to some `destination_account`
* there is no check (before `MUTATION SAFE` barrier) if `destination_account`'s balance after the refund would be `>= ExistentialDeposit`, even though this could potentially cause the extrinsic to fail (since `balances.transfer` does `ensure!(to_account.total() >= ed, Error::<T, I>::ExistentialDeposit);`)

Some examples:

* [`blog` module bloat bond refund](https://github.com/Joystream/joystream/blob/master/runtime-modules/blog/src/lib.rs#L712)
* [`bounty` module reward transfer](https://github.com/Joystream/joystream/blob/master/runtime-modules/bounty/src/lib.rs#L1286)
* ...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202316896260077) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Yeah, lets do a full review of this issue for `Carthage`.
