### ISSUE TITLE
AMM User Research for Creator Tokens

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3765]
# Background

Our ongoing creator token work involves building in a possible _Automated Market Maker (AMM)_ to assist in liquidity for very long tail assets. This is a complex feature, which causes complex product implications, and its not going to be easy to change course once live. For this reason, we are well served checking how well such AMMs are working for other systems. We are in particular interested in _DeSo_, which has a very similar _Initial bonding curve offering (IBCO)_ type AMM for its creator tokens, as this is the closest analogue to what we are imagining. The power of this AMM is that it does not require third party _Liquidity Providers (LPs)_.

# Proposal

Try to understand how well the IBCO construct is serving the liquidity and price discovery objectives of creator tokens on DeSo. Primary sources to review are their

- Github
- Reddit
- Discord
- Forums
- Community calls
- YouTube reviews
- Users: 1-1 interviews

Example topics we are interested in are
- How happy purchasers are with the price dynamics that emerge from the AMMs: volatility, fairness, rationality (do they make sense), dilution (under pricing), access (over pricing)
- How happy creators are with the price dynamics that emerge from AMMs: volatility, fairness, rationality (do they make sense), dilution (under pricing), access (over pricing)
- How happy are purchasers with the ease at which they can get exposure to creator assets at a decent price.
- How happy are early purchasers vs. late purchasers, is there any tension being caused by how the AMM operates in that market.
- How happy are creators with the fact that they cannot customize or control any part of their AMM? the bonding curve shape is universal and static.

**Comment by toiletgranny** [comment]
Issue moved to [Joystream/atlas #2728](https://github.com/Joystream/atlas/issues/2728) via [**ZenHub**](https://www.zenhub.com/)
