### ISSUE TITLE
Integration between Channel ownership transfers and Creator token feautures

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3780]
When merging `ephesus` into `audit3` the integration between [Channel ownership transfers](https://github.com/Joystream/joystream/issues/2816) and [Creator tokens](https://github.com/Joystream/joystream/issues/2362) has to be thought through.

* What should happen if there is an active creator token sale / revenue split etc.?
* Which Creator token features should be blocked during the transfer? (related issue: https://github.com/Joystream/joystream/issues/3428)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202381731971922) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
> What should happen if there is an active creator token sale / revenue split etc.?

That should block transfer initiation in my opinion.

> Which Creator token features should be blocked during the transfer? 

This one is more subtle indeed.

**Comment by bedeho** [comment]
> This one is more subtle indeed.

Lets just do the simple thing: block _all_ creator token features if a transfer has already been initiated.

**Comment by bedeho** [comment]
Covered in https://github.com/Joystream/joystream/issues/3732
