### ISSUE TITLE
Project Token -> Content integration: Curator channels

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3784]
Currently it's not entirely clear how to integrate `project_token` pallet w/ `content` pallet on `ephesus` w.r.t. curator channels, since on `ephesus` we don't have any concept of individual curator's permissions and we also don't have creator token accounts that would be owned by other entity than a single `member`.

So far, based on https://github.com/Joystream/joystream/issues/2362#issuecomment-1088720748, there was burning implemented for curator-owned channel creator token sale `JOY` earnings (as part of https://github.com/Joystream/joystream/pull/3771), but there are other questions that remain:

* There will be CRT possibly earned from patronage - should we just block claiming it in case of curator-owned channels?
* Since all curators belonging to a given curator group have the same permissions within a channel owned by this group, currently any of them can initialize a sale of tokens belonging to his/her membership (`worker.member_id`). I think this makes sense, although since there can be only one sale at any given time (per token), the curators would have to "take turns" or collaborate off-chain (for example, send all tokens to a lead that would then initialize the sale) in order to make this process effective.
* When no creator token is issued, one can call `withdraw_from_channel_balance` in order to directly withdraw the funds from a channel account (w/o revenue split). For curator channels it's again a problem, since any curator belonging to a group that owns given channel would be able to do that. On `audit3` we addressed this issue by [allowing curators to only "withdraw" from channel account into council budget](https://github.com/Joystream/joystream/pull/3562). Should we take similar approach on `ephesus`? (or perhaps follow the approach already taken for sales and just burn those fund?)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202331930899191) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Good questions!

> There will be CRT possibly earned from patronage - should we just block claiming it in case of curator-owned channels?

No.

> I think this makes sense, although since there can be only one sale at any given time (per token), the curators would have to "take turns" or collaborate off-chain (for example, send all tokens to a lead that would then initialize the sale) in order to make this process effective.

I think that is fine.

>  Should we take similar approach on ephesus? (or perhaps follow the approach already taken for sales and just burn those fund?)

Lets follow the `audit3` approach, and it would actually be good if sales followed this approach in fact, for consistency, but not sure how easy that is to pull off without leaking concepts relating to council budget into the `project_token` pallet.

**Comment by Lezek123** [comment]
> There will be CRT possibly earned from patronage - should we just block claiming it in case of curator-owned channels?
> No.

Ok, so just to clarify, should any curator in a group that owns a curator group channel be able to claim patronage to his own member account? (so in case there are 3 curators in a group, any of them can claim the patronage at any given time?)

> Lets follow the audit3 approach, and it would actually be good if sales followed this approach in fact, for consistency, but not sure how easy that is to pull off without leaking concepts relating to council budget into the project_token pallet.

We already have `CouncilBudgetManager` as part of `content` module Trait, so if we want to avoid making it part of `project_token` trait also, I think we can:
- Continue to burn tokens earned during curator-owner channel's token sale 
- On `content::finalize_creator_token_sale` we call `project_token::finalize_sale` which returns total number of JOY earned (burned), we then call `CouncilBudgetManager::increase_budget(joy_earned)` in case the channel owner is curator group.

**Comment by bedeho** [comment]
> Ok, so just to clarify, should any curator in a group that owns a curator group channel be able to claim patronage to his own member account? (so in case there are 3 curators in a group, any of them can claim the patronage at any given time?)

No I am basically saying that none of them can, patronage rewards cannot be claimed. We could even go further and set the rate to 0 whenever a swap happens that causes the curator group to become new owner. I guess we could enforce this also if a channel owned by a curator group tries to issue a token also.

> I think we can:

Sounds like a good plan ;)

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/3771
