### ISSUE TITLE
Securely collect & store user accounts for genesis block

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3787]
We need a process for everyone (investors, team, fms) provide their accounts, a means to store these securely, with associated balances and vesting schedule, as well as to easily generate chain specs from it.

Importantly, we need to advice people on how many accounts to split their tokens over. Using multiple accounts is not only good for privacy, but also needed for people to be able to use their full balance across multiple chivalrous (lock-wise) activities during the vesting period.

# Note: we also need users to select controller and root accounts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202333899053063) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
Going to add instructions for polkadot-js once we have a staging network up, so that accounts with the joystream address format can be generated.
