### ISSUE TITLE
Creator tokens: Disallow transfers to non-existing members

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3791]
I think we should disallow transfers to non-existing members in `project_token` pallet, as this has the potential to generate issues on the query-node side (for similar reason we introduced `member_id` validation when adding collaborators to a channel)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202340945444465) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Agreed.

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/3796
