### ISSUE TITLE
Policy for Sudo Keys

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3798]
# Background
Part of `Carthage` rollout will involve a Sudo key being active, as described here 

https://github.com/Joystream/joystream/issues/3792

This key will be created, stored, used and revoked by Jsgenesis team exclusively.

# Proposal
Describe a confidential security policy for

* creation
* storage
* utlization

of a [multisignature](https://wiki.polkadot.network/docs/learn-accounts#multi-signature-accounts) account for usage by Jsgenesis team, obvious objectives are confidentiality, retrievability, rotation, backup. We should seriously consider reviewing using off-the shelf key management services, and also inquire with other Substrate teams about what they have done for Sudo key management.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202345972784100) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
> of a [multisignature](https://wiki.polkadot.network/docs/learn-accounts#multi-signature-accounts) account...

For this to work, we need to add the multisignature pallet!
Is this trivial @mnaamani ?

**Comment by bedeho** [comment]
I wasn't even aware there was a separate pallet for this

https://docs.substrate.io/v3/runtime/frame/#multisig

Perhaps you can check what other prominent chains do for their Sudo? do they use this pallet?
