### ISSUE TITLE
Project_token->Content pallet integration: Allow specifying revenue split %

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3816]
According to https://github.com/Joystream/joystream/issues/2362:
> A channel owner, but not collaborator, can issue a fungible token controlled using normal Substrate accounts, if one does not already exist, with parameters:
> ...
> **Revenue Split %**: what %, S of channel revenue the token holders are entitled to.

This is missing after https://github.com/Joystream/joystream/pull/3771, as the revenue is always split **in full**, proportionally across all token holders (so revenue split % is effectively always 100%)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202381732773800) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
I have already addressed this in #3849 and its PR #3871
