### ISSUE TITLE
Make all cross pallet extrinsics transactional

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3827]
# Background
Substrate now supports `transactional` macro, which means any side-effect in the extrinsic is rolled back if it results in an `Err`. Read more here:

https://substrate.stackexchange.com/questions/1184/whats-the-overhead-associated-with-the-transactional-macro

The computational overhead is no 0, but its quite low. This is a very substantial change, and deeply impacts how one can write extrinsics: in a more care free way without all the validation up front. I don't think we should abandon our prior methodology of having all verifications up front though, because it really encourages clarity of thinking. However, we have some very sensitive cases in our runtime where I think adding a tranactional protection can really be a good long term protection against errors: cross pallet calls.

# Proposal
Identify all cross pallet calls, and make all such extrinsics transactional. This may require benchmarking, as transactionality has some performance implication.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202381399663421) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
Is the default behavior in Substrate v3 now: https://github.com/paritytech/substrate/pull/11431
What we can do instead is:
- remove all storage related checks from content made to ensure that content method won't fail
- add some tests (unit or integration) to check that all cross pallet call scenarios behave as they should

**Comment by bedeho** [comment]
Ok, that is great, but let me ask, if we remove the storage checks, what do we do about the mutation safety barrier? it will be quite misleading I think. Either way, can you make a new issue with this idea, which includes an explicit list of extrinsics, and which also explicitly states that the work is done _after_ benchmark is done.

**Comment by bedeho** [comment]
Is already the case by default in the new version of Substrate.

**Comment by dobertRowneySr** [comment]
> Is already the case by default in the new version of Substrate.

yes
