### ISSUE TITLE
INFO_14: `accept_incoming_offer` dangerous race condition

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3838]
Quote:
> The API of `accept_incoming_offer` extrinsic should be changed to match the API of
`accept_channel_transfer`, both for coherence and prevent future updates to open the possi-
bility of a race condition. If the `offer_nft` function did not check that the status is Idle or if a
function allowed to update the offer, the `accept_incoming_offer` extrinsic would be vulnerable
to a race condition (updating the offer in the same block would make the other user accept a
different price than expected).

The missed-out fact here is that there is **already** a race condition and a serious vulnerability due to the fact that one can execute `cancel_offer` and then `offer_nft` again (with a different price) within the same block or even within the same transaction (using a batch call). Without any `witness` parameter, this puts the accepting user at a serious risk of beeing front-runned by an attacker to accept an offer at a higher-than-expected price.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202414586783951) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
How is this issue related to this: https://github.com/Joystream/joystream/issues/3856

**Comment by Lezek123** [comment]
Addressed by https://github.com/Joystream/joystream/pull/4000
