### ISSUE TITLE
Add revenue split percentage 

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#3849]
#### Current behavior
https://github.com/Joystream/joystream/blob/a2721e5f797f91ad4aadf2320367b3442db4cc4e/runtime-modules/project-token/src/lib.rs#L1082
Currently in the `issue_revenue_split` extr. creator specifies the exact amount for which the split is issued. 

```rust
    fn issue_revenue_split(
        token_id: T::TokenId,
        start: Option<T::BlockNumber>,
        duration: T::BlockNumber,
        allocation_source: T::AccountId,
        allocation_amount, // 100% of which used in the split
```

But in the content directory the `allocation_amount` passed always equals `channel_reward_account_amount - existential_deposit`

#### Desired Behavior
revenue split rate can be added either to a channel or to the token data struct,
so that the correct `allocation_amount = rate * channel_treasury_amount`  can be computed

This should `audit3` for sure and probably `ephesus` too

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202414587000054) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
In order to summarize my DM discussion with @bedeho 
- `x` = amount transferred to the user
- `ed` = existential deposit
- `y` = Nominal amount used for computing the revenue split
- `r` = revenue split rate
- `y + ed` = total reward account balance availability

thus `x = y * r`

On this basis we can directly pass `y` to the `project_token::issue_revenue_split` and after that use the rate `r` stored in `TokenData` inside the project token pallet

**Comment by bedeho** [comment]
Done https://github.com/Joystream/joystream/pull/3871
