### ISSUE TITLE
LOW_3: No check on `transactor_account_id` on `accept_storage_bucket_invitation`

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#3850]
from audit3:

```rust
/// Accept the storage bucket invitation. An invitation must match the worker_id parameter.
        /// It accepts an additional account ID (transactor) for accepting data objects to prevent
        /// transaction nonce collisions.
        /// <weight>
        ///
        /// ## Weight
        /// `O (1)`
        /// - DB:
        ///    - O(1) doesn't depend on the state or parameters
        /// # </weight>
        #[weight = WeightInfoStorage::<T>::accept_storage_bucket_invitation()]
        pub fn accept_storage_bucket_invitation(
            origin,
            worker_id: WorkerId<T>,
            storage_bucket_id: T::StorageBucketId,
            transactor_account_id: T::AccountId,
        ) ;
```

The recommendation is to check that `transactor_account_id == sender`.
But I am not very sure on the role of `transactor_account_id`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202414644873903) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
# Finding

This extrinsic does not check that the transactor_account_id parameter is valid and matches the origin. This parameter is later used in accept_pending_data_objects to check the identity of the sender.

# Analysis

This is just wrong, there is no need to check this.

# Conclusion

Do nothing.
