### ISSUE TITLE
Channel agent permissions

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#3866]
Full description and accurate representation of scope will be provided by ondratra

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202862000428983) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Note https://github.com/Joystream/joystream/issues/3874#issuecomment-1151030225

**Comment by ondratra** [comment]
A description of this issue can be seen in the original issue for the runtime https://github.com/Joystream/joystream/issues/3436 and the implementing PR https://github.com/Joystream/joystream/pull/3561.

**Comment by dmtrjsg** [comment]
@bedeho @ondratra is there a PR corresponding to this issue?

**Comment by ondratra** [comment]
> @bedeho @ondratra is there a PR corresponding to this issue?

https://github.com/Joystream/joystream/pull/4150
