### ISSUE TITLE
Limits on how much minting can occur

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#3868]
Full description and accurate representation of scope will be provided by @zeeshanakram3 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202405912238138) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@zeeshanakram3 as agreed, we are open to moving fwd with something else after your review of full scope, but in the meantime assigning this to you buddy ;)

**Comment by bedeho** [comment]
We no longer have such limit enforcement on Carthage.
