### ISSUE TITLE
Scope of Work in Channel Payouts Feature (Ephesus Release)

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/joystream#3880]
This issue tracks the scope of all work (including completed + remaining) for Channel Payouts Feature (Ephesus Release)

#### Scope
* [x] Renaming stuff (change command names from `creator*` to `channel*`)
* [x] Add CLI support for Channel payouts proposal
* [x] `content:creatorPayoutPayloadHeader` should both take remote URL and file path for fetching header
* [x]  Update Channel Payouts CLI commands docs 

## Query-Node
* #### Tracking PR
* https://github.com/Joystream/joystream/issues/3879

#### Scope (requires updating the old PR )
* [x] Renaming stuff (change function names from `creator*` to `channel*`); also apply the similar change to `metadata-protobuf` schemas
* [x] Update Channel Payouts utility function's usage docs 

#### Tracking PR
* https://github.com/Joystream/joystream/pull/3182

#### Tracking issue
* https://github.com/Joystream/joystream/issues/3828

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202453881030481) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Thanks for this superb summary, hopefully this will make it reasonably easy to pick up the work again.
