### ISSUE TITLE
Merge in disabled bounties v2

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3881]
# Background
We now have a bounty v2 pallet, replacing the old one, but since we don't have time to redesign Pioneer or get solid QN support for `Carthage` or mainnet, we should just introduce it in a disabled state as part of the codebase.

# Proposal
1. remove existing old bounty pallet
1. merge in new bounty pallet
1. disable new pallet, in the sense that its not possible to call `create_bounty` successfully, it should just return an `Err` instantly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202416725517578) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Merged (https://github.com/Joystream/joystream/pull/3840)
PR to disable `create_bounty` created: https://github.com/Joystream/joystream/pull/4258
