### ISSUE TITLE
Freeze runtime features

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3882]
# Background
As part of having a very focused low risk `Carthage` and mainnet scope, we should seek to restrict as many of the newly implement features post `rhodes` to have much of any impact on the QN or downstream Atlas/QN/Pioneer. This can easily be done by selectively disabling extrinsics that hold key code paths for triggering such features. This excellent summary of changes in the content directory was very useful in coming up with this list.

https://github.com/Joystream/joystream/issues/3874#issuecomment-1149869411

# Proposal
Freeze, by which I mean to just return `Err` as first action, the following. We don't even bother with weights being wrong, as long as they are not 0.

## Content Directory
* Initiating a channel transfer, this should block the following events and thus sidestep need for schema support, 
mappings or Atlas having to check this condition as part of all sorts of actions that are not possible in transit,
  * `UpdateChannelTransferStatus(ChannelId, ContentActor, ChannelTransferStatus)`
  * `ChannelTransferAccepted(ChannelId, TransferParameters)`
* **Turn off actual minting limit validation on issuance of NFTs:** `check_nft_limits`
* Everything having to do with updating or setting minting limits, this should block the following events and thus sidestep need for schema support, mappings or Atlas having to check this condition as part of issuing NFTs.
  * `GlobalNftLimitUpdated(NftLimitPeriod, u64)`
  * `ChannelNftLimitUpdated(ContentActor, NftLimitPeriod, ChannelId, u64)`
* Destroying NFTs: `NftDestroyed(ContentActor, VideoId)`
* Moderators pausing channel features.
  * `ChannelPausedFeaturesUpdatedByModerator`
* Updating the privilege level of a channel and also permissions of a curator group
  * `CuratorGroupPermissionsUpdated`
  * `ChannelPrivilegeLevelUpdated` 

## Bounties V2
Block bounty creation, which blocks everything else.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202416807025146) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
> Updating the privilege level of a channel and also permissions of a curator group
> CuratorGroupPermissionsUpdated
> ChannelPrivilegeLevelUpdated

Curator group permissions can also be initially set via `create_curator_group` extrinsic, so there seems to be very little benefit in disabling just the `update_curator_group_permissions` extrinsic. Should we also modify `create_curator_group`?
