### ISSUE TITLE
Proposal for improving network issues, while promoting Joystream

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#39]
## Problem
As documented in Joystream/substrate-node-joystream#68, Joystream/substrate-node-joystream#69, shown in [telemtetry](https://telemetry.polkadot.io/#/Joystream%20Testnet%20v2) and discussed heavily in our community channels, keeping a sustained high peer count has proved difficult. Running the node with default settings and leaving it for a long time will likely result in:

1. A continuous drop in peers (as the "pool" of 25 gets filled with frozen nodes, and nodes from other networks).
2. A tendency for clustering peers (ie. a group of nodes only/mostly connected to each other)
3. High latency, leaving `validators` to get warnings/slashings/banned due to an "unfortunate" order in the queue.
4. This again has lead to forks, either because the one "outside" node in the cluster (ref 2.) has gone offline, and/or because some nodes consider the proposed block to be within the time limit, and others not.

As a side note, there is a clustering of nodes in Europe, but the rest of the world is not as well represented, increasing latency and adding to the problem.

As we don't want to restart our network again (as outlined in Joystream/substrate-node-joystream#69), we have advised users to:

* increase peer count by adding the flags 
`--in-peers n --out peers m`
where n and m > 25.
* restart their node at regular intervals

Both of these improves the situation, but the former increases memory usage, and the latter requires a more hands on approach, or more advanced settings.

## Proposal
Do a marketing campaign, where existing community members are given `Joystream` branded single board computers (raspberry pi's or similar) for free, to run as nodes. They will receive regular monero payments to cover electricity and their time if their nodes have sufficient uptime. They will of course get to keep the RBPs no matter what. These nodes will may or may not be paid for being `validators`.
I believe this can help in the following ways:

1. Increase the node count, which will: 
    * improve the network
    * promote our "position" in the [telemtetry](https://telemetry.polkadot.io/#/Joystream%20Testnet%20v2) hierarchy
2. Further build and encourage the community.
3. Help improve the technical skills of the receiving members (they will of course get support, but we will not ship the nodes with software)

## Cost
A [raspberry pi](https://www.amazon.com/ABOX-Raspberry-Complete-Motherboard-Heatsink/dp/B07D8VXWRY/ref=sr_1_17?crid=18QSSWXWVIHPY&keywords=raspberry+pi+3+b%2B&qid=1557509068&s=gateway&sprefix=raspberry+p%2Caps%2C409&sr=8-17) with all the needed extra equipment costs around ~80$ w/o shipping. By shopping around, buying in bulk, and consider cheaper boards*, a very high end estimate comes to $100 shipped. Getting the cost down to $50 might be possible, but a budget of $100/pr board is simple and conservative.

*currently, boards as simple as the [orange pi zero](https://www.aliexpress.com/item/Orange-Pi-Zero-H2-Quad-Core-Open-source-512MB-Protective-White-Case-development-board-beyond-Raspberry/32799111611.html?spm=a2g0s.9042311.0.0.1ef74c4dAGxDI2) can *currently* run on the network.

We will place a bounty for arranging the whole thing, ie. dealing with suppliers for boards and branding, compiling a list of recipients, and arranging for shipping. SBCs power consumption is close to negligible, so paying $8/month -> $100/year, for uptime >95% seems fair.

Assuming we provide 50 boards, the total cost assuming the boards are powerful enough to support the increasing network load for ~1 year. (We will likely have to start new chains once or twice pr year anyway).

| Item          |    Qty    | Cost          |
|:----------:|:-------:|:----------:|
| Board        |     50    | $100         |
| Payouts     | ~480*  | $8             | 
| Bounty**    | 1          | $250         |
|**TOTAL**  |  **NA** |**$9090**|

*Assuming some loss along the way.
**the bounty cost was chosen by a pseudo-random number generator.

## Thoughs
We have thus far opted for an interactive way of marketing to build the community, as we hope this approach will improve the *quality* rather than just the *quantity* of our members. More on this can be found [here](https://blog.joystream.org/pay-for-play/). This falls in line with that approach, as it requires some of our less technical followers to get familiarized with linux and the command line.

Input on this is more than welcome. Both from the jsgenesis team, contributors, and community members.

**Comment by bwhm** [comment]
As a side note, I've been thinking about setting aside some funds for `JCP` - Joystream Community Proposals. This might be better to implement after the the council/proposal system for the platform has been developed further.

**Comment by bedeho** [comment]
I think this is really promising. What I would like to see is

# 1. Communication

More thinking around is how to actually communicate this clearly so that we find the best 50 members, and also raise general awareness around what we are trying more broadly.  Should we set expectations about this as a first experiment, and that people can sign up for new hardware releases in the future for core Joystream infrastructure?

I more detailed communication plan would be of value, including any possible changes to our site, messaging on blog/newsletter, etc.

# 2. OKRs

A clear OKR for this entire project which allows us to understand what _exactly_ we want as outcomes, and for what purpose.

# 3. Legal

What sort of agreement or disclaimer is required so that we do not take on any liability of any problem which may occur with the device, such as it malfunctioning in some way. One could imagine horror scenarios of power systems being interrupted or some firing starting! 

# 4. Reusability

It would be great if these devices could be reused for other purposes in the future, e.g. to run different infrastructure software than just a full node (index, discovery, etc.). This could be a lot easier if there was some remote administration feature which allowed us to deploy new software over time. Making something from scratch seems hard, perhaps there is something off the shelve we can consider?

**Comment by bwhm** [comment]
My initial thought is for this to be a community organized project. Partially to offload the work, but also to involve new members, and help prepare the platform for its autonomous future. It can be regarded as a test project with real utility. As a consequence, I didn't want to dig to deep in the OP.

## Phase 1

I consider my first post as a loose tender, and would expect interested parties to respond with:
* why them
* improved budget
* rough outline of the selection/screening process
* bounty request
* milestones (with partial bounties for each milestone reached)
* improvements, etc.

This looks a little bit like a hybrid of the monero `FFS` and bitcoin `BIP` process.

## Phase 2

If we get multiple promising applicants, we can then pay them to proceed and produce a detailed proposal. This would cover the same points as in one, only with a complete budget, and in general more details. The best group/person will get the responsibility.

## Phase 3

Carry out the propsal, with reporting requirements etc.

## Future

If this system works well, I want to formalize the process, and start involving the Joystream governance system more and more as the project develops.

---

1. As I consider this somewhat as an experiment, I don't know how much thought we should put into to expectations. Alternatively, see `2.`

The latter part of this could fall under the scope of Phase 2.

2. This could be a [personal or group OKR](https://github.com/Joystream/joystream#okr-system). I think that could make sense, with myself as the `Tracking manager` and the winner of Phase 2 as the assignees.

3. IANAL, but I assume this risk would fall on the hardware manufactorer?

4. I think this may well be the case, but I don't think we should put too much emphasis on it now.

**Comment by sjsqd** [comment]
Hi, I'm currently working on an application for this. I'll post it here once complete, just wanted to make sure I registered my interest.

**Comment by mochet** [comment]
Hi, here's my proposal which has been adapted from the initial proposal on here. Let me know if you have any ideas or feedback on it.

#### Overview - Phase 1
* Campaign duration - 60 days
* Competition method - Users submit ASCII art of Joystream logo within memo field and a voting process during each cycle would determine the winner.
* Prize - VPS server for 30 days capable of running a Joystream node
	* VPS specs - Debian, 20 GB HDD, 1 GB RAM (rough estimate)
	* Financial incentive to maintain node - $200-400 ($5-10 per node per month)
* Maximum campaign winners - 40
* Maximum nodes added to network - 20 per month
* Cost of nodes - $200 (40 nodes)
* Total cost - $4-500

#### VPS vs Physical hardware distribution
I think after looking over all the pros/cons that an initial run of VPS servers would work best for this campaign, with an eventual move to hardware at a later stage.
The main benefit of this approach is that the delivery timeframe for winners is significantly shorter and cuts out numerous issues with shipping, customs and user privacy. I also think user knowledge can be focused at this stage on just Debian or a chosen OS.
I've begun contacting VPS providers to see if they can offer gift codes that can easily be sent to users and will update if there are some that can, what their pricing would be and what geographies they can currently deploy servers within.

#### Competition - Joystream logo as ASCII art
I think a really creative competition could be for users to submit an ASCII art representation of the Joystream within the Joystream memo field.
I've done limited experimentation with this, and as the memo field supports markdown it should be possible and will help to push users to try and be creative with on-chain features.
It would be great to have the competition winner's art showcased when starting a node via terminal, along with their on-chain username. This could be something that loads dynamically from the chain (if that is possible).

Obviously this would require using the voting system so I would be interested to hear feedback and ideas on this front (minimum participants and so on) and also require some help on how to go about implementing this from a design standpoint as it is not within my skillset (it could be given a dedicate page to showcase winners on the website or on Github)

As an extension of this it is possible to maybe have a small subset of the winners of this competition be allowed to recieve a free hardware device at a later stage--maybe a competition at the end of each week where users can vote on the best ASCII submission of that week and the winner can be awarded a very special hardware device at a later date (I'm not sure if there are legal complexities with this)

#### Payout for running node
I believe this can be monitored via telemetry or another method to get a rough idea of whether a winner actually ran a node. If anyone has ideas on how this could be monitored it would be great to hear.

#### Milestones + reporting
If chosen, I would aim to keep a weekly update of the effectiveness of the campaign. This is an example of what it would look like:

* Week 1 (January 1 - 7)
	* Applicants per 36 hour cycle:
		* 6 / 4 / 9 / 12
	* Successful vote cycle + winner decided (yes/no)
		* 1 / 1 / 1 / 1
	* Percentage of winners running nodes:
		* 100% / 90% / 90% / 80%
	* Nodes awarded during this week:
		* 5
	* Nodes nodes remaining at week end:
		* 35

**Comment by bwhm** [comment]
Hey @mochet,
Do you mind posting this [here](https://github.com/Joystream/bounties/issues/5) instead?
