### ISSUE TITLE
Initial QN bootstrap values

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3902]
# Background
We need to set a bunch of values in the QN for it to synch correctly from genesis, as described here 
https://github.com/Joystream/joystream/issues/3228

It's unclear if we can change this, or change it fully, or if it can be done for `Carthage`.

# Proposal

- To the extent we are still doing this, we need to ensure we are using the right values, and the set of such values may expand for `Carthage`, as well as old values changing because we are taking runtime parameters much more seriously now.
- Remove stuff that we don't need: https://github.com/Joystream/joystream/issues/3228: for each value, review what apps truly needed, and how costly it is to not use QN for this, or to have QN capture the value via events.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202453995060056) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/4245
