### ISSUE TITLE
Safer & clearer tunable behaviour of runtime for integration tests

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#391]
While the ability to make timing and other parameters that impact the feasibility of doing live integration tests tunable by adding them as configurable storage variables may have been expedient for launching Constantinople with proper coverage, I do not think we can move forward with this as a convention, as we noted here

https://github.com/Joystream/joystream/issues/374#issuecomment-616448421.

While reading the current state of the codex module, it was not only clear that it was getting awfully crowded in the storage, but more importantly that putting fundamentally immutable static values in mutable storage is much less clear to the reader, and far less safe.
Any accidental writing to these variables would be a disaster, and we have the option to entirely sidestep that possibility, thus I think we should.

An alternative, which requires more initial effort, is that we go back to having such variables as Substrate module parameters, and then we make our runtime possible to build by passing desired values for such constants. The runtime would then feed these into the desired modules.
This is a scalable and safe approach. This would also require that building for and deploying for integration testing needs to be more complex than now, but I suspect this is where we will end up going anyway.

Please provide feedback in terms of
- feasibility of alternative
- possible improvements
- superior approaches

**Comment by gleb-urvanov** [comment]
It makes sense to define the timing parameters as constants using `parameter_types!` macro, making them both immutable and accessible via API.
To change the timing parameters, runtime code alteration will be required.
I am unaware about existing commonly used methods to pass the parameters to `parameter_types!` macro. In Polkadot and Joystream code, the values for the constants are hardcoded.
It makes sense to develop a function or a macro which will take the values for parameters from external configuration file and replace the values in the runtime code, e.g. during runtime building process. Thus testing code will not be required modify the runtime code directly.
