### ISSUE TITLE
Explore: Multisig support

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3910]
# Background
It would be useful to allow `Sudo` and other key user accounts to be controllable with multisig.

# Proposal
Review what it involves introducing multisig support, likely with the use of the `multisig` FRAME pallet, and in particular confirm how invasive the changes are in the runtime and node to allow use of it for example for `Sudo` and user authentication currently guarded by `ensure_signed`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202458082542259) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
`multisig` pallet along with the `sudo` testing scripts introduced in https://github.com/Joystream/joystream/pull/4076
