### ISSUE TITLE
project-token: Test failing - "panicked at 'attempt to subtract with overflow'" 

### ISSUE THREAD

**Issue by L3pereira** [Joystream/joystream#3913]
A test is failing when running tests in audit3

running the following test
`cargo test -p pallet-project-token --lib -- tests::sale::unsuccesful_upcoming_sale_update_when_token_is_idle`

gives the following output

```
running 1 test
test tests::sale::unsuccesful_upcoming_sale_update_when_token_is_idle ... FAILED

failures:

---- tests::sale::unsuccesful_upcoming_sale_update_when_token_is_idle stdout ----
thread 'tests::sale::unsuccesful_upcoming_sale_update_when_token_is_idle' panicked at 'attempt to subtract with overflow', runtime-modules/project-token/src/lib.rs:1006:23
```

The problem is in
https://github.com/Joystream/joystream/blob/0e12e5a8a2dade51960e13fd3f3423c847b9daa4/runtime-modules/project-token/src/lib.rs#L1006

`token_data.next_sale_id` is zero, so we cannot subtract.

One solution would be using `saturating_sub`

```rust
let sale_id = token_data.next_sale_id.saturating_sub(1);
```

There are other places with the same unsafe arithmetic, but tests didn't detect any error

https://github.com/Joystream/joystream/blob/0e12e5a8a2dade51960e13fd3f3423c847b9daa4/runtime-modules/project-token/src/lib.rs#L633

https://github.com/Joystream/joystream/blob/0e12e5a8a2dade51960e13fd3f3423c847b9daa4/runtime-modules/project-token/src/lib.rs#L440

https://github.com/Joystream/joystream/blob/0e12e5a8a2dade51960e13fd3f3423c847b9daa4/runtime-modules/project-token/src/lib.rs#L641

https://github.com/Joystream/joystream/blob/0e12e5a8a2dade51960e13fd3f3423c847b9daa4/runtime-modules/project-token/src/lib.rs#L671

https://github.com/Joystream/joystream/blob/0e12e5a8a2dade51960e13fd3f3423c847b9daa4/runtime-modules/project-token/src/lib.rs#L1198

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202460445586565) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
I have already provided a solution to this PR https://github.com/Joystream/joystream/pull/3871
