### ISSUE TITLE
Implement Carthage genesis block configuration

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3932]
Implement according to this plan: https://github.com/Joystream/joystream/issues/3419

Depends on having worked out how to do multisig #3910

Includes

* fm
* team
* investors
* rhodes
* etc.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202480864922681) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Should probably update the genesis block CLI tool so it automatically outputs a suitable format that can be c&p into chain spec.

**Comment by mnaamani** [comment]
We now support adding vesting config as well as the initial balances in our chainspec config.
Implemented in:
https://github.com/Joystream/joystream/pull/4228 and https://github.com/Joystream/joystream/pull/4251
