### ISSUE TITLE
Filter initial extrinsics for Carthage rollout

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3934]
# Background
While launching `Carthage` and mainnet, we wish to filter out any non-essential user actions, so as to avoid disrupting #3903 and to make relaunches more graceful, if required in a failure scenario.

# Proposal
Using `BaseFilter` we drop all extrinsics unless they are for pallets

* `sudo`: so as to allow bootstrapping by Jsgensis and next runtime update
* `staking`: so as to allow user stake tokens and declare their intent to validate or nominate. **Double check that this actually works and is the correct pallet to filter for this purpose, and nothing else is needed.**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202481649471457) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Implementation in #3986
