### ISSUE TITLE
Update faucet

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3944]
No longer use invitation system as it depends on DAO activity, just pay for memberships straight up. Try to keep API the same.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202487333255650) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
While the invitation system has the constraint of meaning that the invitor has to have a certain number of invites, which is contingent on DAO authorities replenishing them over tim (which then becomes a source of failure when you run out), it still has the virtue of imposing transaction fee only locking, which dramatically lowers the risk of being Sybilled, which is the main obstacle of running a faucet. Perhaps then the best thing to do is to separate these two: allow somehow to invite or create a membership for someone where you endow them with some initial source of funds that are subject to an invitation lock, or some lock with a similar effect. This seems to require a runtime change, and also change to faucet.

**Comment by mnaamani** [comment]
Implemented in #3985 #4098
