### ISSUE TITLE
size_of::<Call> more than 208 bytes

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#3979]
We have a test in the runtime that checks the size of the `Call` type and it is reporting that is is larger than 208

```
---- runtime_api::tests::call_size stdout ----
thread 'runtime_api::tests::call_size' panicked at 'size of Call 352 is more than 208 bytes: some calls
have too big arguments, use Box to reduce the size of Call. If the limit is too strong, maybe consider
increase the limit to 300.', runtime/src/runtime_api.rs:466:9
```

This test is taken from substrate repo. Should we be concerned or is it just something we have to accept. The test does suggest increasing the limit and using `Box` to reduce it's size. What does the latter mean exactly?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202531880923166) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
I've asked for some clarity from https://substrate.stackexchange.com/questions/3566/what-should-be-the-maximum-size-of-call-for-a-runtime

**Comment by bedeho** [comment]
Let us try to 
- get specific numbers on how big the `Call` value was that caused problems for Parity
- produce list of sizes for extrinsics across runtime
