### ISSUE TITLE
Review: Funds leaking through incorrect balance checks

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4002]
There are many places where funds should not count towards some sort of spending, staking, bloat bonds, etc., but where we may not use a balance checker which is sensitive to vesting+locks+reservations, and funds are later moved using slashing or adding locks, reservations, which then does not fail. We need to review all instances in all pallets to make sure checks are correct.

**Note:** We should probably never use `can_slash`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202560992443450) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
I found this to be a good reference about balances in substrate : https://substrate.stackexchange.com/questions/24/what-is-the-difference-between-free-balance-reserved-balance-locked-balance-v
