### ISSUE TITLE
Make Pioneer Modules Consumable 

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#402]
# Problem

As of today, Pioneer modules are not consumable outside of Pioneer, making it hard to share functionalities and reuse code across projects.

For example, it's impossible (or at least very hard) to use `joy-media` to fetch media contents in an external project, even `joy-utils`, which should be reusable by definition, is not importable as a single module has cyclical dependencies with `joy-members`.

![Untitled Diagram](https://user-images.githubusercontent.com/29527327/81328747-b5a55d00-909d-11ea-96b5-0b89b5f46c3e.png)

The example above is true for multiple Pioneer modules like `joy-roles`, `joy-election` etc... which all depend on each other in some way.

# What I propose

I believe the underlying issue to be how runtime interaction are scattered around the codebase and tightly coupled with the UI.

When importing a Pioneer module, you're probably interested in some runtime interaction, and don't care much about the UI components of that specific module.
I propose to extract all runtime interaction functionalities into a unified api, consumable everywhere.

![Proposed](https://user-images.githubusercontent.com/29527327/81329259-93f8a580-909e-11ea-9cc5-ce341078528d.png)

Each Pioneer module would then rely on this api to define its business logic, making each module self contained, even better, external apps wouldn't need to import Pioneer modules since the api covers all runtime interactions.

## Transition
The transition from the current Pioneer could be made of three steps and be relatively painless. 

1. Refactor and expand `joy-utils` to be `joy-api` and cover runtime interactions. The only Pioneer module used here should be `joy-types`

2. Start refactoring each module and make it self contained, with no dependency on other Pioneer modules beside `joy-types` and `joy-api`

3.  Bring up to date external modules with Polkadot apps and prefer NPM modules over forked ones in the repo.

# Feedback

Very interested in hearing comments and discussing other solutions!

**Comment by semeano** [comment]
Just a couple of questions:

- Pioneer would also be an "external app" or would consume it in a different way?
- How do you import class definitions with an API? (e.g. SimpleCache from `joy-utils`)
- Can you transpile your code without a local type/class definition?

I'm not saying it wouldn't work, I'm just asking because I don't know how that would work.

The only thing I would say is, when refactoring the modules (and Pioneer), be sure to follow the [single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle).

**Comment by fcescob** [comment]
Good questions! Let me try to address those in order:

1. Pioneer would live in the same monorepo as `joy-api`, but would consume it like an external module (with `lerna add @joystream/api --scope=my-module` instead of `yarn add @joystream/api`). A good example of this is how `components` is imported by `app` as an external module in Atlas.

2. In this case, you would `import {SimpleCache} from "@joystream/api"` instead of `import {SimpleCache} from "relpath/to/joy-api/src/SimpleCache"` ( Note: `relpath/to/joy-api` might be shorten or aliased with tsconfig paths, but that is just "synthatic sugar" and does not symlink`joy-api` into node_modules)

3. To transpile and package `joy-api` you would need some toolchain like rollup, babel, tsc, etc... just like any other consumable npm package. Type definitions should be included in the bundle. 

I might have misunderstood some questions, so correct me if I did! 

Regarding the single responsibility principle I agree, and it's really for that reason that single Pioneer modules shouldn't each have its own different way of interacting with the runtime.

**Comment by mnaamani** [comment]
Just a note in https://github.com/Joystream/joystream/pull/687  we are using a relative path like:

`"@joystream/types": "./types", ` as dependency in packages in the same workspace. This works only as long as we don't publish those packages to npm. Once we make more components re-usable and potentially outside the monorepo we need figure out the correct way and perhaps with help of lerna to publish packages.
