### ISSUE TITLE
Database transactions in mappings

### ISSUE THREAD

**Issue by metmirr** [Joystream/joystream#403]
Based on my research I found that there are two ways to implement database transactions for mappings:

1. Use typeorm's query runner:

With this approach developer will explicitly call provided `startTransaction()` and `commitTransaction()` methods. Last processed event is updated inside the `commitTransaction()`

```ts
export function handleMembership(db: DB) {

  db.save(entity)             // Throws an error! Database operations are only allowed in transaction
  
  db.startTransaction()
  
  db.save(entity)
  db.remove(entity)
  
  db.commitTransaction()
}
```

2. Use typeorm's entity manager

With this approach, developer will call a provided entity manager to perform operation inside a database transaction and since we don't have any control on the entity manager we can not update last processed event.:

```ts
export function handleMembership(db: DB) {
  
  db.manager(async (manager: EntityManager) => {
    
    manager.save(entity);
    manager.remove(entity)
  
  })
}
```

As proof of work, I implemented the first approach here https://github.com/metmirr/joystream/commit/fba6161d2b59cb672b25f4bd1a8952e0589cdd79. @bedeho when you have time please take a look. I need your feedback here.

**Comment by bedeho** [comment]
How about we do the first approach, however, we make sure to have started the transaction before the mapping is called, and likewise, we call the commit when the handler returns. We do not make these two calls public to the user. Now the user cannot mess up, and there is less boilerplate. This also means we can drop each `save` being its own transaction.

**Comment by metmirr** [comment]
Done in https://github.com/metmirr/joystream/commit/4471243bcc48295b6e245d8f16541dca10a590c1
