### ISSUE TITLE
Review: Avoid slash-only bloat bonds

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4033]
# Background
We have introduced bloat bonds many places now (proposals discussion, forum, content, storage, bounties), however in some of these cases the funds are not credited to some appropriate treasury account, they are simply slashed, and then later minted back upon cleanup. This has a few problems

1. We end up impacting issuance, which should be avoided when possible.
1. Bloat bonds are often needed to protect against existential deposit cleanup mechanism. For hard-coded treasury accounts, we have set this using genesis config, like this https://github.com/Joystream/joystream/issues/3508, however, for dynamic treasury accounts - like for bounties or channels, this does not work.
1. Unless there is appropriate balance check, slashing allows us to ignore locks & reservations:

# Proposal
Review all uses of bloat bonds, and make sure that tokens are actually credited to the treasury account, and also debited on cleanup. Critically

* Think about this in the context of fixing the #3569 
* Think about this in the context of fixing the #4002 
* We need to probably introduce the actual amount of bloat bonds used for a given bond, on the relevant object, otherwise, if the bloat bond magnitude is changed (in particular increased) in the interim, then the treasury may become insolvent.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202608451583004) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment]
pioneer does not test or show recoverable forum / content bloat Joystream/pioneer/pull/3894
