### ISSUE TITLE
Update NFT limits for Carthage

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4042]
Current production config for NFT params on `carthage` (Assuming 1JOY = 0.06USD):

```
max_starting_price: 1_000_000_000_000, (or 100 JOYs) (or ~6 USD)
max_bid_step: 1_000_000_000_000, (or 100 JOYs) (or ~6 USD)
```

Those values are obviously too low for production. Let's change those values to 2e17 if possible (that should translate to roughly 1 million dollars). Let's use the same values for testing config as well.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202613447930286) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Depends on https://github.com/Joystream/joystream/pull/4025
