### ISSUE TITLE
Update amount of funds sent from faucet for Carthage

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4043]
Current Carthage faucet only sends 10 unlocked JOYs and 100 locked JOYs. That will most likely not be enough to send any transaction one fees are involved. We need to adjust that value with something that makes sense.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202613485658655) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
The current faucet on the carthage playground is using the old invite member extrinsic (where the amount of funds given is configured in the runtime)
Once we update it to use new [gift_membership](https://github.com/Joystream/joystream/pull/3985) extrinsic it will be more flexible and allow the faucet to decide/configure this amount independent of the runtime configuration.
