### ISSUE TITLE
Allow querying channel's reward account

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4044]
Probably include channel reward account in the `ChannelCreated` event and then index it in QN

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202613580098008) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Duplicate of https://github.com/Joystream/joystream/issues/4029

**Comment by kdembler** [comment]
Oh thanks, I missed that! 🤦
