### ISSUE TITLE
Update fee parameters for Carthage

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4045]
Currently all types of bloat bonds are zero, and also the fee per MB for storage objects is zero. We need to have those set to some values so we can test out if in-app estimation works fine

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202613713816563) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Depends on https://github.com/Joystream/joystream/pull/4025
