### ISSUE TITLE
Introduce bounds for collections embedded in storage entities in content pallet

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4046]
# Background

Fixes first part of this https://github.com/Joystream/joystream/issues/4041

# Proposal
Added trait values for each collection, consult it in all relevant extrinsics. Look at this also https://github.com/Joystream/joystream/issues/2501.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202620911419955) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
Unbounded user inputs also appears in the new `gift_membership` extr. in the `membership` pallet.

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/4062

> Unbounded user inputs also appears in the new gift_membership extr. in the membership pallet.

Since this issue is about content pallet I'm going to close it now and link to your comment in the general issue: https://github.com/Joystream/joystream/issues/4041
