### ISSUE TITLE
Simplify extrinsics in light of lack of need for guards across pallet calls

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4047]
# Background
https://github.com/Joystream/joystream/issues/4019

# Proposal
Do as planned!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202620926813176) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
I am closing this, the downside of the changes is negligible.
Plus the structure of the code has changed considerably, especially after the payment features added
