### ISSUE TITLE
Remove transferrable tokens granted in faucet

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4048]
On mainnet, we can no longer give away free transferrable tokens.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202621376466253) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
In new faucet implementation https://github.com/Joystream/membership-faucet/pull/17 and https://github.com/Joystream/joystream/pull/4098 It is purely up to the person running the faucet service to configure how many tokens are sent to the gifted member and how much of it will be locked.
