### ISSUE TITLE
WG Application Interchanging of Answers Bug

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#4060]
@Songoku1691 commented on [Sat Jul 16 2022](https://github.com/Joystream/pioneer/issues/3362)

Hello Guys:

I would like to report this bug or error when applying in WG opening. This occurs when you skip questions and return to answer them back. You will notice that answers interchange. I hope this will be fixed. Please watch video below that I made to illustrate the issue.

https://play.joystream.org/video/27072

Thank you

**Comment by WRadoslaw** [comment]
Playground: https://query.joystream.org/graphql
Query to look-up: 
```
query {
 	workingGroupApplications(where: {id_eq: "operationsWorkingGroupBeta-40"}) {
    answers {
      answer 
      question {
        question
      }
    }
  }
}
```

**Comment by thesan** [comment]
This was a Pioneer issue (https://github.com/Joystream/pioneer/issues/3362) but there is a CLI described in #4149
