### ISSUE TITLE
Missing entity existence checks in the runtime

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4074]
There are still a few places in the runtime with issues similar to this one pointed out in the audit: https://github.com/Joystream/joystream/issues/3834

The common pattern is:

* We take an entity identifier(s) as extrinsic parameter(s) (be it `member_id` / `channel_id` / `curator_group_id` etc.)
* We don't validate whether the entity/entities by provided identifier(s) actually exist(s)

There are a few issues that this could cause:

* Query node will often try to create relationship between those entities which will fail and cause the processor to crash
* It may result in some weird states in the runtime, for example, an nft may be issued to a member which doesn't exist, causing it to be effectively frozen forever, as noone will have permissions to manage it.
* No feedback to the user that the provided id(s) are not valid

### Currently identified occurrences:

**Bounty pallet:**
- [x] Oracle member id is not verified
- [x] `AssuranceContractType::Closed` member ids are not verified

**Content pallet:**
- [x] Nft open/english auction whitelist (member ids not verified)
- [x] Nft initiail issuance with `non_channel_owner` (member id is not verified)
- [x] `initialize_channel_transfer`: `new_owner` (`curator_group_id` / `member_id` of the new owner not verified)
- [x] Creating curator channel as lead (`curator_group_id` not verified)

**Project token pallet**
- [x] Initial allocation (member ids are not verified)

**Proposals:**
- worker id not validated when creating:
  - [x] `DecreaseWorkingGroupLeadStake` proposal
  - [x] `SlashWorkingGroupLead` proposal
  - [x] `SetWorkingGroupLeadReward` proposal
  - [x] `TerminateWorkingGroupLead` proposal
- [x] opening id and application id not validated when creating `FillWorkingGroupLeadOpening` proposal
- [x] opening id not validated when creating `CancelWorkingGroupLeadOpening`
- [x] proposal id not validated when creating `VetoProposal`

**Proposal discussion:**
- [x] `change_thread_mode` - `ThreadMode::Closed` whitelist member ids not verified

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202645867210686) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Nice work, yeah lets fix this, wonder what QN mappings are assuming here, whether relationships are presumed nullable perhaps.

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/4091
