### ISSUE TITLE
`try_mutating_storage_state` refactorization plan

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4080]
Original issue: https://github.com/Joystream/joystream/issues/3412

## `try_mutating_storage_state` method

Currently we have 3 separate actions that can be executed using a single `try_mutating_storage_state` method:
```rust
// Create dynamic bag (and upload initial data objects)
try_mutating_storage_state(
    account_id,
    BagOperation::<T> {
        bag_id,
        params: BagOperationParams::<T>::Create(
            objects_to_upload,
            storage_buckets,
            distribution_buckets,
        ),
    },
)

// Update bag (add and/or remove data objects)
try_mutating_storage_state(
  account_id,
  BagOperation::<T> {
    bag_id,
    params: BagOperationParams::<T>::Update(objects_to_upload, objects_to_remove),
  },
)

// Remove bag (and all data objects)
try_mutating_storage_state(
    account_id,
    BagOperation::<T> {
        bag_id,
        params: BagOperationParams::<T>::Delete,
    },
)
```

I suggest removing the `BageOperationParams` enum and `BagOperation` struct and using 3 separate methods instead:
```rust
// Create bag (and upload initial data objects)
try_performing_bag_creation(account, data_objects, storage_buckets, distribution_buckets)

// Update bag (add and/or remove data objects)
try_performing_bag_update(account, objects_to_upload, objects_to_remove)

// Remove bag (and all data objects)
try_performing_bag_removal()
```

All logic specific to a given `BagOperation` should be moved to one of those corresponding methods.

## Other methods that depend on `BagOperation`

There are other functions that execute different logic depending on provided `BagOperation`, which should also be refactored:

### `fn retrieve_dynamic_bag(bag_op: &BagOperation<T>)`
This function creates a new dynamic bag (if already exists - throws an error) and returns it in case if `bag_op.params` is of `BagOperationParams::Create` type.
In all other cases it just returns `Self::ensure_bag_exists(&bag_op.bag_id)`.

**Possible refactorization:** Change it to `new_dynamic_bag(storage_buckets, distribution_buckets)` and only leave the part that's inside:
```rust
if let BagOperationParams::<T>::Create...
```
For other purposes `Self::ensure_bag_exists` can be just used directly.

### `fn construct_objects_to_upload(op: &BagOperation<T>)`
In case of `BagOperationParams::Create` and `BagOperationParams::Update` it just returns `Self::construct_objects_from_list(assets_to_upload)`.
In case of `BagOperationParams::Delete` it returns some empty, non-useful values.

**Possible refactorization:** Drop this function, use `construct_objects_from_list` directly in `try_performing_bag_creation` and `try_performing_bag_update`.

### `fn update_storage_buckets(bucket_ids: &BTreeSet<T::StorageBucketId>, all_objects_with_update_voucher: VoucherUpdate,op: &BagOperationParams<T>)`

This function:
1. Iterates over all provided storage bucket ids
2. Filters out non-existing buckets
3. Updates vouchers of all existing storage buckets according to `VoucherUpdate` (**bug:** it's done incorrectly)
4. Executes some additional logic based on `BagOperationParams`:
  4.1. `BagOperationParams::Create` - also calls `register_bag_assignment` for each bucket
  4.2. `BagOperationParams::Delete` - also calls `unregister_bag_assignment` for each bucket
  4.3. `BagOperationParams::Update` - no additional logic
5. Returns a map of `(storage_bucket_id, storage_bucket)` entries (does not execute any `write` operation directly)

W.r.t. to the bug pointed out in point `3.` - voucher is not updated correctly because the values provided inside `VoucherUpdate` override the values in the existing stroage bucket voucher for all buckets in the set, independently of the current voucher's state. In `try_mutating_storage_state` the `VoucherUpdate.objects_number` is just set to `uploaded_assets.len() + bag.objects_number - removed_assets.len()` and `VoucherUpdate.objects_total_size` is set to `upload_objs_size + bag.objects_total_size - remove_objs_size`, which means the `VoucherUpdate` does not take into accout the size and number of objects in other bags assigned to a given storage bucket that is being updated.

**Possible refactorization:** 
I think this function should be just removed and `try_performing_bag_creation`/`try_performing_bag_update`/`try_performing_bag_removal`
should have their own inner logic of updating the buckets like:
```rust
for bucket_id in storage_bucket_ids {
    StorageBucketById::<T>::mutate(bucket_id, |b| {
        // specific mutation logic
    })
}
```
(alternatively this can be refactored into 3 separate methods)
The bugs mentioned above should be fixed. The voucher update logic should take into account the current voucher, for example:
```rust
for bucket_id in storage_bucket_ids {
    StorageBucketById::<T>::try_mutate(bucket_id, |b| {
        // specific logic for `try_performing_bag_update`
        let new_voucher = Voucher {
            objects_number: b.voucher.objects_number
                .saturating_add(uploaded_objs_num)
                .saturating_sub(removed_objs_num);
            objects_total_size: b.voucher.objects_total_size
                .saturating_add(uploaded_objs_size)
                .saturating_sub(removed_objs_size);
        }
        b.voucher.try_update(new_voucher)
    })
}
```

### `fn update_distribution_buckets(bucket_ids: &BTreeSet<DistributionBucketId<T>>, op: &BagOperationParams<T>)`

This function:
1. Iterates over all provided distribution bucket ids
2. Filters out non-existing buckets
3. Executes either `register_bag_assignment()` (`BagOperationParams::Create`) or `unregister_bag_assignment()` (`BagOperationParams::Delete`) on each distribution bucket. In case of `BagOperationParams::Create` just reads the bucket, but does not modify it in any way.
4. Returns a map of `(distribution_bucket_id, distribution_bucket)` entries (does not execute any `write` operation directly)

**Possible refactorization:** 
Same as in `update_storage_buckets` case - move this logic directly to `try_performing_bag_creation`/`try_performing_bag_removal`

**Comment by bedeho** [comment]
Really nice breakdown. At one point in time I was making the case that we needed to have proper types representing the different error outcomes for the storage pallet API methods (https://github.com/Joystream/joystream/issues/3413), and even the success types should be better, to avoid this kind of stuff https://github.com/Joystream/joystream/pull/3454#discussion_r831387994. However, this was blocked by doing a proper refactoring of `try_mutate_storage`. 
Should we do this? Is this a good idea?

**Comment by Lezek123** [comment]
I think that's a good idea and shouldn't be hard to implement after this refactorization

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/4082
