### ISSUE TITLE
When creating a bounty, a thread is created in the wrong forum category

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#4081]
@adovrodion commented on [Sun Jul 10 2022](https://github.com/Joystream/pioneer/issues/3341)

## Problem

Issue identified to be a Query node issue. Pioneer uses the following query to fetch the "Bounties" forum category: https://raw.githubusercontent.com/Joystream/pioneer/aa9aef7db06cb103257078bee2fc67d2efedc216/packages/ui/src/bounty/hooks/useBountyForumCategory.ts However, this query return random categories :) 

## Implication on Pioneer

![image](https://user-images.githubusercontent.com/84832436/178145327-dd0ce8a1-cdff-4b44-92cd-5ec2c84c88aa.png)
![image](https://user-images.githubusercontent.com/84832436/178145341-53a91140-b524-4a4f-aed0-d740b672df1b.png)
I think this is a pioneer mistake.

![image](https://user-images.githubusercontent.com/84832436/178145370-545347ec-dd8b-4823-9eee-2437b356f818.png)
![image](https://user-images.githubusercontent.com/84832436/178145427-460957f6-868b-4a58-b26b-64fa71bc1edd.png)
Previously, when creating a bounty, a thread on the forum was created in the "Bounties" category - https://dao.joystream.org/#/forum/category/1 

---

@dmtrjsg commented on [Mon Jul 18 2022](https://github.com/Joystream/pioneer/issues/3341#issuecomment-1187562788)

@ignazio-bovo @bedeho do we know if Bounties v2 will have its own discussion engine, like it works for proposals? Or will it still rely on Forum.. 

---

@bedeho commented on [Mon Jul 18 2022](https://github.com/Joystream/pioneer/issues/3341#issuecomment-1187983422)

> do we know if Bounties v2 will have its own discussion engine, like it works for proposals? Or will it still rely on Forum. 

Nothing has been planned changed in this regard, but we may as well fix this also while deploying v2 of bounties, where we go to metaprotocol based discussion, there is already an issue for this here: https://github.com/Joystream/joystream/issues/3287

This will require mapping and message work by QN devs at some point, but I think @thesan should be able to pull it off as well.

---

@singulart commented on [Tue Jul 19 2022](https://github.com/Joystream/pioneer/issues/3341#issuecomment-1188884911)

https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944/#/explorer/query/1667890 wrong category ID is being sent in the extrinsic

---

@singulart commented on [Fri Jul 22 2022](https://github.com/Joystream/pioneer/issues/3341#issuecomment-1192693254)

Issue identified to be a Query node issue. Pioneer uses the following query to fetch the "Bounties" forum category: https://raw.githubusercontent.com/Joystream/pioneer/aa9aef7db06cb103257078bee2fc67d2efedc216/packages/ui/src/bounty/hooks/useBountyForumCategory.ts However, this query return random categories :) 

---

@dmtrjsg commented on [Mon Jul 25 2022](https://github.com/Joystream/pioneer/issues/3341#issuecomment-1194446863)

Moving this issue to QN board.

**Comment by dmtrjsg** [comment]
@L3pereira 

[Not urgent] 

This 

"Issue identified to be a Query node issue. Pioneer uses the following query to fetch the "Bounties" forum category: https://raw.githubusercontent.com/Joystream/pioneer/aa9aef7db06cb103257078bee2fc67d2efedc216/packages/ui/src/bounty/hooks/useBountyForumCategory.ts However, this query return random categories."

was raised wrt bounties v1. I

❓  wonder if that is still a valid issue in context of Bounties v2.

**Comment by bedeho** [comment]
>  wonder if that is still a valid issue in context of Bounties v2.

Unlikely, bounty v2 should not use forum for comments.

**Comment by dmtrjsg** [comment]
Closing this issue based on the above comment and in the light of bounties v1 will be shortly deprecated.

**Comment by dmtrjsg** [comment]
@adovrodion fyi
