### ISSUE TITLE
Query node: Invalid assumption about forum post existence (`forum_PostReacted`)

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4085]
`react_post` extrinsic in the runtime does not validate `post_id`, because the post may be non-editable (which means it doesn't exist in the runtime state)

The query node however assumes that the `postId` emitted in `PostReacted` event belongs to an existing post:

* https://github.com/Joystream/joystream/blob/carthage/query-node/mappings/src/forum.ts#L530
* https://github.com/Joystream/joystream/blob/carthage/query-node/mappings/src/forum.ts#L548

This means that providing invalid post id to `react_post` tx may break the query node processor

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202677862704917) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
covered by https://github.com/Joystream/joystream/issues/4132
