### ISSUE TITLE
Significance of valuations in resource pricing

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4097]
# Background

At the end of the day, the chain has to demand a certain number of nominal currency units, i.e. `hapi`, for a certain level of resource utilization (weight, block spaces). Since the purpose of fees is largely to discourage denial of service attacks, this means this exercise ha to take into account what price of `hapi` is w.r.t. some currency, e.g. like USD. This effectively means the chain has to have some built in sensitivity to the market cap of the chain in question. This need not be precise, and it can be updated over time, but it is at any time a value which is seemingly relevant.

# Question

All of them seem to follow the principle of charging 0.1 cents for the processing associated with an empty transaction, but it seems to me that they are not consistently modelling what 1 cent or dollar is actually worth. So the questions are

1. Am I wrong or misunderstanding what they are doing?
2. Does this not matter? it would seem to be critical to not overcharge or be vulnerable to denial of service

## Acala

`cent(ACA)` is the number of base units needed to be worth a cent, is defined as

https://github.com/AcalaNetwork/Acala/blob/7a1b02961a9d795d1a62e9ab6e43c5735e244e6f/runtime/common/src/lib.rs#L195

where a dollar is defined above as `10^{#decimals in ACA token}` base units, which ultimately comes from

https://github.com/AcalaNetwork/Acala/blob/8f9ba11a6e7280200e4d53e58be86ebedb46e335/primitives/src/currency.rs#L412

through

https://github.com/AcalaNetwork/Acala/blob/7a1b02961a9d795d1a62e9ab6e43c5735e244e6f/runtime/common/src/lib.rs#L191

and thus which is `10^12` base units. Perhaps I am being dense, but I am not sure I understand why the notion of decimals and the dollar value of one unit would be linked in this precise way.

Anyway, since ACA supply is [1,000,000,000](https://coinmarketcap.com/currencies/acala/), and each ACA has `10^12` base units (since this is what decimals mean), this means implied market cap of ACA is `1,000,000,000 x 1 USD`, or **1,000,000,00 USD**. Suffice, that has never been close to being the case, and now it is 300M USD.

## Polkadot

Here a dollar is defined as

```Rust
	pub const UNITS: Balance = 10_000_000_000;
	pub const DOLLARS: Balance = UNITS; // 10_000_000_000
```

in https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/constants/src/lib.rs#L31. This means 10 B base units are assumed worth 1 USD. Now since DOT supply is roughly [1,103,303,471](https://coinmarketcap.com/currencies/polkadot-new/), and each DOT has [10,000,000,000](https://support.polkadot.network/support/solutions/articles/65000168663-how-many-planck-are-in-a-dot-) base units, this means the implied market cap of DOT is **1,103,303,471 USD**.

## Kusama

Here a dollar is defined as

```Rust
  pub const UNITS: Balance = 1_000_000_000_000;
  pub const CENTS: Balance = UNITS / 30_000;
  pub const GRAND: Balance = CENTS * 100_000;
  pub const MILLICENTS: Balance = CENTS / 1_000;
```

in https://github.com/paritytech/polkadot/blob/master/runtime/kusama/constants/src/lib.rs#L31. Following the sematnicsc of thos constants, this means a dollar is equivalent to `100*CENTS=UNITS/30`, hence the total implied value of KSM is `(UNITS)/[UNITS/30]` or **30 USD**. Real market cap of KSM is 620,595,219 USD.

## Reef Finance

Here a dollar is defined as

```Rust
pub const DOLLARS: Balance = 1_000_000_000_000_000_000;
pub const CENTS: Balance = DOLLARS / 100;

pub const REEF: Balance = DOLLARS;
pub const MILLI_REEF: Balance = REEF / 1_000;
```

in https://github.com/reef-defi/reef-chain/blob/5961ec07af2853d4a137bd1dba57eba3ea13d1f0/primitives/src/lib.rs#L46. This basically says that one REEF token is worth 1 USD, and since the token supply is (19,509,853,969)[https://coinmarketcap.com/currencies/reef/], this means implied market cap is **19,509,853,969 USD**. Real market cap of REEF is 83,566,410 USD.

**Comment by mochet** [comment]
If I understand this issue correctly, then this is maybe an idea of how to solve this: https://github.com/Joystream/joystream/issues/1631

**Comment by bedeho** [comment]
> If I understand this issue correctly, then this is maybe an idea of how to solve this: https://github.com/Joystream/joystream/issues/1631

Correct, but we are not able to do that for mainnet, but the goal of this issue is just to verify that we are understanding the approach others are taking, and whether in fact people are indeed quite insensitive about the prospect of mispricing. But warning, the issue is not fully written out yet, will complete later.

**Comment by Lezek123** [comment]
> Here a dollar is defined as
>
>  pub const UNITS: Balance = 1_000_000_000_000;
>  pub const CENTS: Balance = UNITS / 30_000;
>  pub const GRAND: Balance = CENTS * 100_000;
>  pub const MILLICENTS: Balance = CENTS / 1_000;
> in https://github.com/paritytech/polkadot/blob/master/runtime/kusama/constants/src/lib.rs#L31. Following the sematnicsc of  thos constants, this means a dollar is equivalent to 100*CENTS=UNITS/30, hence the total implied value of KSM is (UNITS)/[UNITS/30] or 30 USD. Real market cap of KSM is 620,595,219 USD.

`UNITS` is the number of units (plancks) per `1 KSM`, so we have `1 CENT = UNITS / 30_000`, so `1 KSM = 30_000 CENTS` so `1 KSM = 300 USD`

The total supply of Kusama is `9,651,217` currently, so we get a Fully Diluted Market Cap of **2,895,365,100 USD** (the actual Fully Diluted Market Cap now is **634,566,665 USD**, which means everything should be **~4,5x cheaper** than expected)
