### ISSUE TITLE
Introduce Pioneer into monorepo

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#410]
- Add in new folder `pioneer` in root directory.
- Must preserve Git history, not just as a snapshot,  ask @mnaamani for help if you are unfamiliar with how to do this.
- Transfer over all issues, and tag with `pioneer` label in that repo.
- archive original repo

**Comment by Lezek123** [comment]
Related PRs: https://github.com/Joystream/joystream/pull/469 and https://github.com/Joystream/apps/pull/466
