### ISSUE TITLE
Impossible to create a channel without assets

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4103]
When creating a channel, `assets` param is optional and [here](https://github.com/Joystream/joystream/blob/carthage/runtime-modules/content/src/lib.rs#L486) we will unwrap it or use a default value if not supplied.  Then, when we construct bag creation params, we set `expected_data_size_fee` as `storage_assets.expected_data_size_fee`, but if the `assets` param was not provided, the default value for that will be 0. Then `Storage::<T>::create_dynamic_bag(bag_creation_params)?;` is called and an error is thrown because the real data size fee doesn’t match the supplied expected value (0), so in effect, you’re not able to create a channel without supplying the `assets` parameter.

As a possible solution, if `assets` is not provided, we could not check the `expected_data_size_fee` at all or we could set it to real value of `storage_assets.expected_data_size_fee`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202697310702438) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Fixed in https://github.com/Joystream/joystream/pull/4120
