### ISSUE TITLE
`ExistentialDeposit` not taken into account when checking usable balance before `slash`

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4105]
As discovered in https://github.com/Joystream/joystream/pull/4025, the `account.usable_balance() >= slash_amount` check is insufficient before performing the slash, because the actually slashed amount will never exceed `account.total_balnce - existential_deposit`, see: https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L1568

Because we're often using the combination of `Balances::<T>::slash` and `Balances::<T>::deposit_creating` this can even result in JOYs being created out of thin air in case the cost of executing the affected extrinsics is < ExistentialDeposit.

**An example:**
Let's say the existential deposit is `1 JOY`

1. We issue an nft on sale for `100 JOY` from an account `A`
1. We create an account `B` which has exactly `buy_nft_tx_fee + 100 JOY` usable balance
1. We use the `B` account to buy the nft
1. During `buy_nft` execution the runtime will try to slash `100 JOY` from `B`, but since `B`'s balance is exactly `100 JOY`, it will only slash `100 - existential_deposit` JOY, so `99 JOY`. The `1 JOY` existential deposit will remain in `B`. (the runtime is currently indifferent to the `Balances::<T>::slash` return value)
1. If we assume the `platform_fee` is `0`, the runtime will then mint `100 JOY` to `A` using `deposit_creating`
1. Now `A` has `+ 100 JOY` and `B` has additional `1 JOY`, so we effectively minted `1 JOY` out of thin air to ourselves.

**Scope:**

This issue is quite common in our current Carthage runtime, some features which are affected are:

* Channel bloat bonds
* Channel swap payments
* `fund_council_budget` tx
* `buy_membership` (as spotted in https://github.com/Joystream/joystream/pull/4025)
* ...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202698746626412) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
`membership::gift_membership` might also be affected

**Comment by bedeho** [comment]
To clarify, core issue here is just that `usable_balance` is wrong test for feasibility of slashing, because the two treat existential deposists differently. The `deposit_creating` is just a compounding after-effect?

**Comment by Lezek123** [comment]
> To clarify, core issue here is just that usable_balance is wrong test for feasibility of slashing, because the two treat existential deposists differently.

It all depends on how `usable_balance` is used. `ensure!(usable_balance(acc) >= amount)` is a wrong test to ensure that the entire `amount` will actually be slashed when we call `slash(acc, amount)`. But `ensure!(usable_balance(acc) >= amount + existential_deposit)` would be a sufficient test.

There are a few other checks that can be done instead:
- `Balances::<T>::can_withdraw(acc, amount) == WithdrawConsequence::Success` (this will be `true` only if `acc.free - acc.frozen(AnyReason) - existential_deposit >= amount`)
- After checking the usable balance we can actually check the return value of the `slash` method: `let (_, not_slashed) = Balances::<T>::slash(acc, amount)` and then `ensure!(not_slashed == 0)`

> The deposit_creating is just a compounding after-effect?

I'm not sure if I understand correctly. The problem is we're using `deposit_creating` with the assumption that the entire amount we wanted to slash was actually slashed, but that's not always the case.

**Comment by bedeho** [comment]
> It all depends on how usable_balance is used

Indeed, why don't we introduce a new check in our common library which is called something like `ensure_can_slash`, which just does what you say in terms of making sure balance is `usable balance => safe_add(existential_deposit, amount)`, then just make sure everyone is using this.

> I'm not sure if I understand correctly. 

No problem, we are on the same page.
