### ISSUE TITLE
We need a plan: a bad batch of bloat,tx fee, balance and locking

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4134]
There is no a long list of issues that feel related, but also are quite chaotic and disorganised. Some issues may be partially duplicating concerns of others, and some concerns may not be legitimate. We need a full review of it all, and one plan which coherently deals with it all

* https://github.com/Joystream/joystream/issues/3414
* https://github.com/Joystream/joystream/issues/4002
* https://github.com/Joystream/joystream/issues/3760
* https://github.com/Joystream/joystream/issues/3569
* https://github.com/Joystream/joystream/issues/3653
* https://github.com/Joystream/joystream/issues/4126
* https://github.com/Joystream/joystream/issues/4033
* https://github.com/Joystream/joystream/issues/3509

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202739195283963) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Adding: https://github.com/Joystream/joystream/issues/4105

**Comment by Lezek123** [comment]
Plan created: https://github.com/Joystream/joystream/issues/4162
