### ISSUE TITLE
Query node indexer issues

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/joystream#415]
Used branch `query_node` commit `95a0f29`
- Perhaps it should be mentioned in `cli/README.md` that one should run `yarn install` first to and only then `yarn link` to make it available.

Next, I navigated to `joystream-query-node` and run `cli codegen` as suggested. The folders `generated/indexer` and `generated/graphql-server` were successfully generated.  
- Further, go to `generated/indexer` and run `yarn start` as written on `README.md`. I got the following error:
```
index.ts:38:14 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

38   node.start(providerUri, getProcessingPack(), registerJoystreamTypes);
```
After manually hardcoding the uri in the generated sources, I got another error:
```
$ ts-node index.ts
query: SELECT "SavedEntityEvent"."index" AS "SavedEntityEvent_index", "SavedEntityEvent"."eventName" AS "SavedEntityEvent_eventName", "SavedEntityEvent"."blockNumber" AS "SavedEntityEvent_blockNumber", "SavedEntityEvent"."createdAt" AS "SavedEntityEvent_createdAt" FROM "saved_entity_event" "SavedEntityEvent" LIMIT 1
query failed: SELECT "SavedEntityEvent"."index" AS "SavedEntityEvent_index", "SavedEntityEvent"."eventName" AS "SavedEntityEvent_eventName", "SavedEntityEvent"."blockNumber" AS "SavedEntityEvent_blockNumber", "SavedEntityEvent"."createdAt" AS "SavedEntityEvent_createdAt" FROM "saved_entity_event" "SavedEntityEvent" LIMIT 1
error: error: relation "saved_entity_event" does not exist
    at Connection.parseE (/Users/zhelezov/joystream/query-node/joystream-query-node/generated/indexer/node_modules/pg/lib/connection.js:581:48)
```
@bedeho

**Comment by metmirr** [comment]
- Indexer uses `joystream-query-node/.env` file for configuration and providerUri is set,  so I am confused here, what you changed manually?https://github.com/Joystream/joystream/blob/95a0f29ebb4d3a7628db675d4d0c56c5727d305b/query-node/joystream-query-node/.env#L1 

- It is 'table does not exist' error. Indexer store last processed event on the database. After making changes to indexer code regards to the last processed event I forgot to update CLI.

**Comment by dzhelezov** [comment]
I believe I had the `.env` file present (with `WS_PROVIDER_ENDOINT_URI` set), but I got the ts-compiler error I descriped (`Argument of type 'string | undefined' is not assignable to parameter of type 'string'`). So I simply changed `node.start(providerUri, getProcessingPack(), registerJoystreamTypes);` to `node.start('ws://localhost:9944', getProcessingPack(), registerJoystreamTypes);` just to make it compile and see how it goes further.

**Comment by metmirr** [comment]
It is really interesting :), I have a guard for this https://github.com/Joystream/joystream/blob/95a0f29ebb4d3a7628db675d4d0c56c5727d305b/query-node/substrate-query-framework/cli/src/templates/index-builder-entry.mst#L28

**Comment by dzhelezov** [comment]
> It is really interesting :), I have a guard for this
> 
> https://github.com/Joystream/joystream/blob/95a0f29ebb4d3a7628db675d4d0c56c5727d305b/query-node/substrate-query-framework/cli/src/templates/index-builder-entry.mst#L28

I think the problem is in this line in the generated sources, so providerUri gets `string | undefined` type rather than `string`:
```
const providerUri = process.env.WS_PROVIDER_ENDPOINT_URI;
```

**Comment by dzhelezov** [comment]
I think this issue has gone and can be closed now.

**Comment by metmirr** [comment]
Actually I will do an update here then close:

const providerUri: string = process.env.WS_PROVIDER_ENDPOINT_URI!;

**Comment by metmirr** [comment]
Done in https://github.com/metmirr/joystream/commit/be8d2b99a6213dd1e5ac38d4c1f976f413ddea73
