### ISSUE TITLE
Apps as channels

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4158]
# Background

We are in the process of incorporating applications as metaprotocol level concept, here https://github.com/Joystream/joystream/issues/4307, primarily to unlock attribution that finally enables the council to pay apps for the content and creators they onboard based on accurate information. That proposal made applications owned by _memberships_, which was a natural starting point, it does however have limitations:

1. **Scalable Payments:** a practical and efficient way to reward apps
2. **Financing:** Running an app requires investment of various kinds of front, with uncertain payoffs down the road.
3. **Transferable ownership:** Being able to sell your app to someone else later, so they are the full beneficiary and administrator, generates better incentives for long term stewardship, even if time horizon for personal involvement is uncertain or finite. This is of particular importance, as apps can harm end users.

# Proposal

These could all be implemented by making the metaprotocol more elaborate, adding new proposals and adding new integrations between membership pallet and `project_token` pallet, but _even then_, there would be no functional software that would be able to allow people to use all these features.

Instead, I propose we simply overload the `channel` entity in the `content` pallet to also be to function as an app. By doing that, you get 1,2,3 solved for free, without any work. One could also very easily add a new section to Atlas, or just make a standalone product, which allowed for using all the $CRT features, but only for apps, not creator channels, and very limited extra work would be needed. 

Technically, one could more specifically do something like this:

- The actions `CreateApp`, `UpdateApp` are sent over `content::channel_owner_remark` instead of `membership::member_remark`. I think `DeleteApp` causes more trouble than its worth. 
- Apps have their own ID identifier space, as distinct from the channel IDs
- There can be at most one app per channel.
- In QN/Orionv2
  - Add `Apps` as a new schema entity, it holds all the metadata already defined for an app.
  - Add nullable 1-1 relationship `Channel::app` to `Apps`

This is not the only way to do this, but it is a way which causes minimal change requirements other places. **Feel free to improve!**

Atlas can now choose to either systematically ignore all channels, or videos from channels, which have an app, or they can just be included as normal channels. Notice that its still possible to do all the normal channel stuff with apps. If we wanted, Atlas could also choose to add a flare or other sort of signal to channels which are apps. Most regular users would just be non-the wiser.

_Question: with current QN or coming Orinv2, will it be easy to avoid channels which are apps, and also videos that correspond to channels that are apps, in all places needed? (search, within categories, etc.)_

**Comment by bedeho** [comment]
Was mulling this over in my mind, I want to flesh out some additional thoughts, see what devs think.

_Ducks as shoe is thrown._

# On the other hand

## PROs

Let's revisit the benefits

1. Scalable Payments
2. Financing
3. Transferable ownership
4. No-runtime changes needed: this was not explicitly listed among benefits, but it is liste din the proposal text itself.
5. Atlas support for free: this was not listed among benefits

### 1. Scalable Payments

This is really a bit of a red-herring. Scaleable payments are about... _scale_. Is it really likely that over the next few years we will have so many apps generating real content and traffic that just doing normal council payment transfers won't work? For creators, it obviously was the case, even just thousands of proposals weekly for each creator would not have worked, let alone in terms of execution constraints, but real apps - this will take more time, and there is also much less urgency in having timely payouts to apps compared to creators.

### 2. Financing

Financing is obviously a benefit, but this does not imply that _memberships_ per say cannot own apps, it just means that memberships would need a `project_token` pallet integration, so really this benefit is just restating benefit nr. 4 below.

### 3. Transferable ownership

This is a real benefit, but this does not imply that _memberships_ per say cannot own apps, it just means that no metaprotocol change would be needed to encompass this, so really this benefit is just restating benefit nr. 4 below. 

### 4. No-runtime/metaprotocol changes needed: this was not explicitly listed initially as benefits, but it is liste din the text itself.

Here we are, compared to members as owners, specifically thinking of no 

a. new project_token integration
b. QN level feature for app ownership buying/selling

### 5. Atlas support for free: this was not listed among benefits

The initial treatment contemplated of such channels was to effectively [hide them](https://github.com/Joystream/atlas/issues/3627), but one could argue that by enabling a certain view of them in Atlas, one would unlock the issuer+holder+viewer features for such tokens automatically, as these already work for channel tokens in Atlas.

While this may be possible, it's not the case that this is the only case to get the benefit of all the premade visuals, components and logic, mappings/schemas that powers all the features for creator tokens. Virtually all of this would still work even if the membership driven model worked, it would just need some extra plumbing. The reason is that the same core `project_token` pallet structure would be powering everything, and the user goals are similar. One could go one step further and say that from a product perspective, it would actually just be confusing it have a few dusins or hundreds of channels behave in a totally different way to token purchasers, and Atlas design somehow have to treat htem in a different way, hiding NFTs, videos and all that stuff which has no meaning. Likewise, on the issuer side, having to deal with the whoel studio, where 80-90% of features are irrelevant to a given channel, also is not a big benefit. Perhaps the alternative path of just putting apps in their own standalone product, which largely reuses all the artefacts used in Atlas and Orion, but is itself independent from it, would be better for users. This product would have its own marketplace, with its own data and way of presenting apps, and could evolve into a nice experience for app creators to manage their apps, just like creators manage their channels. I'm not saying this is urgent, I'm saying this is an alternative path which reuses virtually all of the work we have already done, but which keeps Atlas focused on consumers+creators.

## CONs

There is one very obvious con to having apps as channels: it's confusing.

All apps now have to be aware of these two types of channels, for example Atlas having to filter out apps as channels from creator channels in the marketplace feature and in general lots of places where content is relevant. It adds to the complexity of the metaprotocol layer in particular, which is already getting quite complex.

## The alternative

1. Implement apps as member owned, as initially contemplated: https://github.com/Joystream/joystream/issues/4307. This can be launched right away.
2. As part of creator tokens launch, we create a new proper pallet `apps` , where applications are represented properly on-chain, and there is a standalone integration with a clone of `project_token`. This pallet would be bare bones, perhaps only have transferrable ownership (3) if we care. There is no support for apps in any way in UX of Atlas. This new pallet would be a clean slate which is only focused on representing apps on-chain. Importantly, this means there would be two notion of apps available, v1 and v2 apps, as we could call them, where only the latter had support for financing, etc.

My hunch is this is cleaner long term path, and it also keeps options open longer until we actually ship creator tokens, rather than locking into this somewhat convoluted apps as channels path early.

**Comment by WRadoslaw** [comment]
Hmm... Obviously, the pros outweigh the cons. On the other hand, if we really consider making Apps as separate runtime-aware entities, then I'm not sure whether trying to figure out membership vs channel is that important. 

Your hunch is definitely valid, the question is how soon we would want to introduce the such feature. For now, amount of Apps is pretty low and I think most of the owners are deeply familiar with the Joystream ecosystem, so confusion might be not that big, and when the time comes that new members brought by marketing will start considering creating their own gateway. Apps pallet might be already in place.

Lemme know if I'm missing smth... 🙌

**Comment by bedeho** [comment]
> if we really consider making Apps as separate runtime-aware entities

I think this is the best bet, but obviously we don't know for certain still, just trying to keep our options a bit more neutral.

> then I'm not sure whether trying to figure out membership vs channel is that important.

My concern is, once we cross this boundary of muddling up what a channel is, even just for some period, this is permanent debt, and it will permanently need to be dealt with everywhere. That would also be the case if we later do members => native apps, but that just seems much less costly of a debt.
