### ISSUE TITLE
Allow modifying video subtitles after NFT is issued

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4166]
As it is on Carthage, once you mint an NFT for a video, you cannot do any updates to that video. That means whatever was the state of the video before NFT, it will be like this forever. This is suboptimal experience when it comes to subtitles - you may want to correct mistakes or add new languages for your video even though you have an NFT for it already. It would be worth exploring possibilities of making subtitles editable after NFT was issued

**Comment by bedeho** [comment]
Covered by https://github.com/Joystream/joystream/issues/3284.
