### ISSUE TITLE
Emergency pause proposal

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4172]
# Background

Recent Acala hack highlights the utility of community being able to pause operations of chain, so as to contain state corruption. **In fact, simply having such a proposal may serve as a very potent deterrent for any attacker to invest resources in trying to attack the system to begin with**.

A useful reference design from Nodle parachain: https://github.com/NodleCode/chain/issues/657

# Proposal

Introduce a new proposal that blocks all "non-essential" (begs the question what should be in this category though), functionality, which probably should be able to pass instantly if you get 100% quorum and 100% threshold. Perhaps the pause should have limits, like only being feasible to do every so often, and automatic unpausing after some period of time.

This is a complex topic, but probably is needed.

**Comment by Songoku1691** [comment]
I agree with this is important function Sir. There are also additional details that need to be discussed:

1. Will this be single control or multisig one?
2. Who will control this function? (Council? Lead? JSG?)
3. Can that person/group activate this function on his/their own or need community approval first?

Thanks

**Comment by bedeho** [comment]
The answer to all of your questions is that this would be the council which could trigger, and only the council, so no multisig per say, but multiple on-chain actors are needed.

**Comment by bedeho** [comment]
Related: https://github.com/Joystream/joystream/issues/4297

**Comment by bedeho** [comment]
Superseded https://github.com/Joystream/joystream/issues/4897
