### ISSUE TITLE
Forum: Adding non-editable post can prevent a thread from ever being removed

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4175]
1. Adding a post increases `thread.number_of_posts` even if the post being added is non-editable (is not preserved in the state): https://github.com/Joystream/joystream/blob/carthage/runtime-modules/forum/src/lib.rs#L1406
1. Removing/moderating a post is only possible if it exists in the state (https://github.com/Joystream/joystream/blob/carthage/runtime-modules/forum/src/lib.rs#L1491, https://github.com/Joystream/joystream/blob/carthage/runtime-modules/forum/src/lib.rs#L1477)
1. Removing/moderating a thread is only possible if `thread.number_of_posts == 0` (https://github.com/Joystream/joystream/blob/carthage/runtime-modules/forum/src/lib.rs#L1633, https://github.com/Joystream/joystream/blob/carthage/runtime-modules/forum/src/lib.rs#L1655)

This implies:

* If a post is created in non-editbale initial state in a thread, then that thread cannot be removed

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202801705812740) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Is the mistake here that `number_of_posts` should only be counting editable posts? a renaming may be in order. Guess a test should be added also.
