### ISSUE TITLE
No 20% tx fee cut for validators

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4176]
Block author still gets tip, but no inclusion fee cut of 20%, also good for tokenomics, see background
https://github.com/Joystream/joystream/issues/4174

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202802722901316) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Implemented in https://github.com/Joystream/joystream/pull/4199

**Comment by bedeho** [comment]
How to test in QA: verify that validator does not receive any tx inclusion fee revenue at all, they still should be able to receive tips.

**Comment by mnaamani** [comment]
> How to test in QA: verify that validator does not receive any tx inclusion fee revenue at all, they still should be able to receive tips.

I added a basic test for correct implementation of the `DealWithFees` implementation in the runtime as cargo unit tests, but this is by no means a complete test coverage.

We could have simple test scenario in integration tests as follows:
- Setup Account `X` fund it from `Alice` (the block author)
- Record total issuance, and balance of `Alice` and `X`
- execute `N` balances:transfer() calls each with a tip `T`, transferring amount `V` to account `Y`
- At end of the scenario (which should be completed before the end of an Era) the following should hold:
  - Alice Balance should have increased by `(N * T)` only
  - Account X balance decresed by `(N * T + N * V + TotalTxFeesPaid)`
  - Account Y balance equal to `(N * V)`
  - Total Issuance reduced by `TotalTxFeesPaid`

we can derive `TotalTxFeesPaid` by `BalanceOf(X) - (N * T + N * V)`
we can also simplify by transfering to self ie. `X == Y` and transferring `zero` balance, ie `V == 0`
