### ISSUE TITLE
Slash worker doesn't work CLI regression bug

### ISSUE THREAD

**Issue by polikosi** [Joystream/joystream#4177]
in the version (Rhodes) it works like this

joystream-cli working-groups:slashWorker 999 10
Initializing the query node connection (https://query.joystream.org/graphql)...... done
Initializing the api connection (wss://rpc.joystream.org:9944/)...... done
Current Group: builders
 ›   Error: Worker 999 does not exist!

but in Carthage it is different:
![image](https://user-images.githubusercontent.com/80429191/183876593-fe3c2871-5509-48be-a8e8-804e94f6600a.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202805445801806) by [Unito](https://www.unito.io)

**Comment by zeeshanakram3** [comment]
fixed in #4260
