### ISSUE TITLE
Simplify `has_sufficient_balance_for_fees`

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4201]
Update the internal implementation of `has_sufficient_balance_for_fees` to just use `Account::usable_balance(Reason::Misc)` (free balance excluding locks that can pay for fees, i.e. invite lock), since they will both be equivalent when we implement https://github.com/Joystream/joystream/issues/4200.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202847679691548) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Just 2 notes here:
1. `Account::usable_balance` is a private method implemented in `balances` pallet, so we cannot use it. We have to use `account.free - account.fee_frozen`
2. We also need to check existential deposit (ie. `account.total() >= amount + ed`)

**Comment by bedeho** [comment]
Bummer.

**Comment by bedeho** [comment]
Done.
