### ISSUE TITLE
Stop using Substrate fork for vesting pallet

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4218]
Introduced here: https://github.com/Joystream/joystream/pull/4216

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202868857189955) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Done in https://github.com/Joystream/joystream/pull/4244
We updated use joystream fork of substrate dependency from joystream repo.
