### ISSUE TITLE
Argus/Colossus doesn't properly handle text-based assets

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4229]
It seems Argus/Colossus can properly determine `mimeType` only for binary-based formats (video, images, etc.). However, it fails to understand type of text-based assets (like WebVTT video subtitles for example). For those types of assets, when asset is served, fallback of `application/octet-stream` is used as a `Content-Type`, making it impossible to actually use those assets as subtitles (browser rejects the URL because of content-type)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202882754784716) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
What is urgency on this?

**Comment by kdembler** [comment]
We can't release subtitles without this fixed

**Comment by bedeho** [comment]
Ok, adding to `Carthage` then, since it's part of the release timeline.
