### ISSUE TITLE
Add Benchmark to compute "BaseExtrinsicWeight"

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4233]
Since we have added a new SignedExtension to our SignedPayload we should compute a new base extrinsic weight as noted in https://github.com/Joystream/joystream/pull/4213#pullrequestreview-1089253824

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202889239123531) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Although we are dropping the SignedExtension solution it might still make sense to compute the base weight?

**Comment by bedeho** [comment]
There is also a block base weight, and there are also other parameters around read & write weights in RocksDb, is there any reason we should not rebenchmark all of them, but just this?

**Comment by bedeho** [comment]
Made new issue about this: https://github.com/Joystream/joystream/issues/4252
