### ISSUE TITLE
Benchmark new core weight parameters

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4252]
We are relying on the following which comes from the Substrate FRAME system

```Rust

//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-05-24 (Y/M/D)
//!
//! SHORT-NAME: `block`, LONG-NAME: `BlockExecution`, RUNTIME: `Development`
//! WARMUPS: `10`, REPEAT: `100`
//! WEIGHT-PATH: `./frame/support/src/weights/`
//! WEIGHT-METRIC: `Average`, WEIGHT-MUL: `1`, WEIGHT-ADD: `0`

// Executed Command:
//   ./target/production/substrate
//   benchmark
//   overhead
//   --chain=dev
//   --execution=wasm
//   --wasm-execution=compiled
//   --weight-path=./frame/support/src/weights/
//   --warmup=10
//   --repeat=100
pub const BlockExecutionWeight: Weight = 5_346_284 * WEIGHT_PER_NANOS;
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-05-24 (Y/M/D)
//!
//! SHORT-NAME: `extrinsic`, LONG-NAME: `ExtrinsicBase`, RUNTIME: `Development`
//! WARMUPS: `10`, REPEAT: `100`
//! WEIGHT-PATH: `./frame/support/src/weights/`
//! WEIGHT-METRIC: `Average`, WEIGHT-MUL: `1`, WEIGHT-ADD: `0`

// Executed Command:
//   ./target/production/substrate
//   benchmark
//   overhead
//   --chain=dev
//   --execution=wasm
//   --wasm-execution=compiled
//   --weight-path=./frame/support/src/weights/
//   --warmup=10
//   --repeat=100
pub const ExtrinsicBaseWeight: Weight = 86_298 * WEIGHT_PER_NANOS;

//// no infomation about what machine these were generated on
pub const RocksDbWeight: RuntimeDbWeight = RuntimeDbWeight {
	read: 25_000 * constants::WEIGHT_PER_NANOS,
	write: 100_000 * constants::WEIGHT_PER_NANOS,
};
```

These seems to be quite recent, and I am not sure how sensitive they are to machine setup, so I would just presume these are OK.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202919491751656) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
I compared the exact value to the current version of substrate we are using and they are almost identical.
But it will not be too much trouble to recompute `BlockExecutionWeight` and `ExtrinsicBaseWeight` in our `scripts/generate-weights.sh` just in-case our runtime configuration produces different values.

The `WEIGHT_PER_NANOS` comes from `frame/support/src/weights.rs` And seems based on the comment that it looks OK to use them as is, since we are haven't changed the pallets significantly.

```
/// These constants are specific to FRAME, and the current implementation of its various components.
/// For example: FRAME System, FRAME Executive, our FRAME support libraries, etc...
pub mod constants {
	use super::Weight;

	pub const WEIGHT_PER_SECOND: Weight = 1_000_000_000_000;
	pub const WEIGHT_PER_MILLIS: Weight = WEIGHT_PER_SECOND / 1000; // 1_000_000_000
	pub const WEIGHT_PER_MICROS: Weight = WEIGHT_PER_MILLIS / 1000; // 1_000_000
	pub const WEIGHT_PER_NANOS: Weight = WEIGHT_PER_MICROS / 1000; // 1_000

	// Expose the Block and Extrinsic base weights.
	pub use super::{block_weights::BlockExecutionWeight, extrinsic_weights::ExtrinsicBaseWeight};

	// Expose the DB weights.
	pub use super::{
		paritydb_weights::constants::ParityDbWeight, rocksdb_weights::constants::RocksDbWeight,
	};
}
```

**Comment by bedeho** [comment]
> I compared the exact value to the current version of substrate we are using and they are almost identical.
But it will not be too much trouble to recompute BlockExecutionWeight and ExtrinsicBaseWeight in our scripts/generate-weights.sh just in-case our runtime configuration produces different values.

I think this is a good idea, just as a sanity check that somethign weird is not going on.

> The WEIGHT_PER_NANOS comes from frame/support/src/weights.rs And seems based on the comment that it looks OK to use them as is, since we are haven't changed the pallets significantly.

I thought this was a definitional thing really, we should never change that. At the very least, same value has to be used across benchmarking and production!
