### ISSUE TITLE
Question: Simplify CallFilter

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4253]
We are doing this currently for production `CallFilter`

```Rust
// Live Production config
#[cfg(not(any(
    feature = "staging_runtime",
    feature = "testing_runtime",
    feature = "runtime-benchmarks"
)))]
impl Contains<<Runtime as frame_system::Config>::Call> for CallFilter {
    fn contains(call: &<Runtime as frame_system::Config>::Call) -> bool {
        filter_non_essential(call) && filter_content_and_proposals(call)
    }
}
```

but since `filter_non_essential` returns `false` on a non-match, do we need the second & clause?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202919581692922) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Technically we don't, but I left it generalized, just planning ahead so as we rollout and change what is filtered in non_essential, (such as when we enable proposals) we will not mistakenly enable all proposals.

**Comment by bedeho** [comment]
ok, I think its better to keep this remark as a comment or something, as it causes confusion when it actually implemented.
