### ISSUE TITLE
Use generated values for core weights

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4257]
Basically the ones mentioned here: https://github.com/Joystream/joystream/issues/4252

So both generate + use those values in runtime code.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202923096916199) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Done in https://github.com/Joystream/joystream/pull/4264
