### ISSUE TITLE
Fee profile command to CLI

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4266]
# Background
There are a variety of scenarios where it would be useful to be able to guague how a new node/runtime would fare in terms of the cost of certain key usage patterns, they are

* when tweaking some parameter or some core business logic associated with some action, e.g. in development mode.
* when needing to determine the appropriate state bloat bond for key actions, since they must be no less than cleanup transaction fees: _this is already needed for Carthage_
* when wanting to do simulations how the system would work overall, and these costs are important inputs.

# Proposal
Add a new command to the CLI, e.g. call it `fee_profile`, which can ask a node what the cost of a suite of standard extrinsics are at that time. Here are some examples

* Buy a membership
* Make a channel + 2 assets
* Delete a channel.
* Make a video + 2 assets
* Delete a video
* Submit a comment on a video
* Make a , non-editable, forum thread with post of max length.
* Delete a forum thread
 
Now importantly, there are some free variables in all of these which will impact cost, the CLI can either have some hard coded assumptions about this (e.g. how long is a normal but long video title), or they can be imported in a separate JSON file so as to not require updating the CLI itself if you want to play with different values. The script should for each action list some key information, like the 
 
* inclusion fee: useful to have in $USD (if input price is provided to command), hapi & $JOY
* full fee: (including whatever extra deposit etc. is neede)
* total extrinsic size
 
It may also want to output certain chain state values of relevance to these costs, such as the current fee multiplier, but lets keep it minimal for now. Having output in some structure format, like JSON or something, would be beneficial for other downstream tools.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202938088239534) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/4299
