### ISSUE TITLE
Colossus: check worker ID on startup

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4272]
### Problem
With the current Colossus, it's possible to provide wrong worker ID (not associated with you on-chain) and start the node. AFAIK, there's no messaging letting you know that you are using the wrong worker ID. The only indication would be uploads failing if your misconfigured worker ID is not assigned to correct storage buckets. We have experienced this already after one storage worker has changed to lead position and their worker ID has changed

### Solution
Add a startup check to Collosus that verifies that the key you provided is associated with the worker ID you have provided. If that's not the case, the node should exit with an error, making it clear that something is wrong

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202945940410669) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/4283
