### ISSUE TITLE
Trivial forum fixes

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4275]
1. Drop `MaxPostsInThread` in runtime config, appears to not be used. (also, should'nt clippy warn about this?
1. Same with `MaxThreadsInCategory`.
1. Tweak this comment which appears to be incorectly describing automated cleanup as being a reason for constraints. Doubl check!

```Rust
/// Upper bounds for storage maps and double maps. Needed to prevent potential block exhaustion during deletion, etc.
/// MaxSubcategories, and MaxCategories should be reasonably small because when the category is deleted
/// all of it's subcategories with their threads and posts will be iterated over and deleted.
```

1. Rename `MaxCategories` to `MaxTotalCategories`, as people have been confused about meaning => https://github.com/Joystream/joystream/issues/3676
1. Rename `MaxSubcategories` to `MaxDirectSubcategoriesInCategory` for same reason.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202951933347568) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
From my understanding the concern is whether deletion is `O(1)` or not, and in the negative case we might want to bound it by `O(MaxDirectSubcategoriesInCategory)`. I am investigating into this (but I am pretty sure that the concern is well grounded) and constant deletion is not possible.

This answer :https://substrate.stackexchange.com/questions/5257/storage-double-map-key-deletion/5258#5258 confirm that is effectively so
