### ISSUE TITLE
Failed upload - User experience 

### ISSUE THREAD

**Issue by yasiryagi** [Joystream/joystream#4279]
Problem:

- When a user create a channel/bag, the channel/bag get assign x number of bucket/nodes as per the configured storage replication policy.
- When a user tries to upload an object a random bucket/node from the assigned buckets/nodes, and the system proceed to try to upload.
- If the upload to that bucket/node fails the system errors back to the user to manually try to re-upload.
- It seems that the system assumes a reliable storage system which should not in a distributed system.
- Not a lot of logs and metrics is collected about the failure.

Solution:

- If an upload fails to bucket/node, the system automatically resect another random bucket/node from the assigned set and retry the upload till it exhausted all buckets/nodes in the set.
- A rich data of logs and metrics is collected about the failure.

**Comment by bedeho** [comment]
Thank you for this, but it should be clarified at what level you believe there is a problem exactly. It seems you are concerned with how _Atlas_ specifically is dealing with uploads?

> A rich data of logs and metrics is collected about the failure.

Who should do this, or at what technical layers should this be done, please be more clear.

> It seems that the system assumes a reliable storage system which should not in a distributed system.

The system should be much more reliable than it is today, so the vast majority of the space for improvement should not fall on the application layer error handling, it should be that the infrastructure improves, both technically and socially. Remember, many centralized services have distributed systems infastructure, that does not mean it has to be unreliable, in fact overall it should be more reliable. Right now I do think our system is having too many individual node faults, mostly due to operational failures which are not being properly detected and punished.

**Comment by bedeho** [comment]
If this was about Atlas, then I have at least created a corresponding issue just now: https://github.com/Joystream/atlas/issues/3240

**Comment by yasiryagi** [comment]
> A rich data of logs and metrics is collected about the failure. 


The data provided when an upload fails is very little, I expect at least:
- Which node failed.
- What time
- Detail error message i.e. node unreachable, DNS error, HTTP error etc... 

> Who should do this, or at what technical layers should this be done, please be more clear.

Resiliency can be handle at the application level or Joystream storage the backend. This preferably should be handled at Joystream backend storage system. 

>  Remember, many centralized services have distributed systems infrastructure, that does not mean it has to be unreliable, in fact overall it should be more reliable. 

 
Most current centralized services use a combination of technologies to shield users experience from nodes failures, auto detect and remove failed nodes from service:
1. GMT: Global traffic manager.
2. LB : Load balancer.
3. HA : High availability. 


So from Joystream prospective a geolocation implementation would cover most the GMT functionality, and I do not think LB and HA architecturally fit in this case. But I think we need a way to auto detect faulty nodes and set an out of service flag. 


> Right now I do think our system is having too many individual node faults, mostly due to operational failures which are not being properly detected and punished.

- Again any hosting system has to account for failure an automatically take failed nodes out of service, whether it is operational failure or not. Currently we depend on human intervention to detect and mitigate which cause a delay in problem resolution.
It would be cool to see:
1. System auto detect failed node.
2. Upon failure detection:
  - Set an out of service flag
  - disable per block rewards
3. Allow maintenance mode 
  - Set an out of maintenance flag
  - disable per block rewards  after certain amount of time.
  
>  which are not being properly detected and punished.

- Any hosting operation need to stablish Standard operation procedure SOP. Which currently is been discussed in the storage workgroup. 
- Without an agreed on set of rules, it would not make sense to punish. SOP is a social set of rules, which will always be needed in this case. But I think the point above about auto detect and punish will make sense as first layer that will catch 80% of the cases.

**Comment by bedeho** [comment]
Baseline issue has been addressed for now.
