### ISSUE TITLE
Colossus upload diagnostics endpoint

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4285]
# Background

https://github.com/Joystream/atlas/issues/3240#issue-1368620499

# Proposal

A public diagnostics endpoint which allows testing unscheduled uploads, so no chain interaction. Simplest possible behaviour would be to just be able to upload a blob of some fixed size, without any authentication, and then server side should just close endpoint if it gets hit too often, to avoid denial of service abuse.

**Comment by kdembler** [comment]
After some discussion this is superseded by https://github.com/Joystream/joystream/issues/4295
