### ISSUE TITLE
Include abstention votes

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4298]
Currentl works like this

```
    approval_quorum_bar
    This bar indicates the value : ( votes_count - abstentions) /council_size
    
    approval threshold bar
    This bar indicates the value : approves / (votes_count - abstention)
    
    slash quorum bar
    This bar indicates the value : (votes_count - abstentions) /council_size
    
    slash threshold bar
    This bar indicates the value : slashes / (votes_count - abstention)
```

Change to

```
    approval_quorum_bar
    This bar indicates the value : votes_count/council_size
    
    approval threshold bar
    This bar indicates the value : approves/votes_count
    
    slash quorum bar
    This bar indicates the value : votes_count/council_size
    
    slash threshold bar
    This bar indicates the value : slashes/votes_count
```

NB: requires more discussion

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203058397951197) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
This topic originated from the bugfix on Pioneer:
- https://github.com/Joystream/pioneer/issues/2715

While reviewing the PR with the team I personally was surprised that Abstain is not calculated towards Quorum, while considered to still count as vote.  Quick desktop research indicated that a common mechanics would be for Abstain vote to count towards Quorum, and that is in fact is one of the purposes of such a vote.

<img width="789" alt="Screenshot 2022-09-16 at 17 50 34" src="https://user-images.githubusercontent.com/93924525/190654686-e3aba5f2-bb4d-4797-895f-a34f24f98e33.png">

Extrapolating this to a generic user expectations of evaluating likelihood of proposal likelihood to be rejected/ accepted for cases when Abstain votes are casted, `the hypothesis is that most generic users would expect Abstain to count towards quorum.`

The implication of such a decision on voting dynamics, is that council members who vote with "Abstain" would increase the likelihood of proposals to be executed for proposals where Approval Quorum > Approval Threshold. 

NB: Currently runtime proposal consts are set up with vast majority of Approval Quorum < Approval Threshold, so there will be no effect on changing the quorum calculation logic without changing Proposal Consts values for Threshold and/ or Quorum.

Also: now the pioneer [story book](https://pioneer-2-storybook-git-fork-mkbeefcake-fix-ap-443ee9-joystream.vercel.app/?path=/story/proposals-proposalpreview-proposalstatistics--default&args=approve:0;reject:0;abstain:0;councilSize:5;approvalQuorumPercentage:80;approvalThresholdPercentage:100;slashingQuorumPercentage:60;slashingThresholdPercentage:80) for the proposal voting statistics widget reflects the runtime set up described in this issue.

**Comment by bwhm** [comment]
It looks like there are currently cases where it's better to `abstain` (or not vote) than `reject` a proposal, assuming you don't want it to pass. That doesn't sound right to me...

If we subtract abstentions on both the nominator and denominator for quorum, that will not be true anymore. It will still have an impact compared to not casting any vote at all...

**Comment by mochet** [comment]
The original reason abstain votes got changed was the following issues:
* https://github.com/Joystream/joystream/issues/2383
* https://github.com/Joystream/joystream/issues/1958
* https://github.com/Joystream/joystream/issues/2589
(the latter includes research of dozens of DAOs--most DAOs `do not have` abstain voting features, or at least didn't at that time)

**Comment by bedeho** [comment]
Despite reviewing all those links, I can't get a simple story about why we have this alternative abstention treatment, I suggest we just drop this as its just making the system harder to reason about, as evidenced by my own mistake in setting finalized proposal parameters: read `Proposal Parameters` here https://github.com/Joystream/joystream/issues/4300#issuecomment-1251217674.

**Comment by Lezek123** [comment]
> Some people are confused by absention not counting towards quorum, alternative would be to include in both approval quorum, but also to not remove from denominator in threshold.

In that case there will be no difference between `Reject` and `Abstain` (unless we want different behavior w.r.t. slashing quorums/thresholds, but that would again be kind of confusing)

> (the latter includes research of dozens of DAOs--most DAOs do not have abstain voting features, or at least didn't at that time)

I think that makes sense, it's not clear to me what could be a reasonable purpose for `Abstain` votes given that proposals default to rejection if approval/slashing threshold can no longer be reached and given we also have `Reject` votes which main purpose is to prevent any other threshold from being reached.

**Comment by bedeho** [comment]
So, as summarised here https://github.com/Joystream/joystream/issues/4300#issuecomment-1262205691, we going to go with
1. the proposal here
2. requiring thresholds to be no less than quorums

**Comment by mochet** [comment]
> 

I believe the entire problem concerning abstention votes may have just been a byproduct of the testnet phase. The main reasoning was that an an inactive or unknowing council member could effectively stalemate proposals indefinitely, but they can also do this by just rejecting proposals continuously regardless so the distinction seems to matter very little at the end of the day.

I aslo seem to remember there were some situations where we had high numbers of conflicts of interests at play due to the small community size, so people would abstain vote on proposals that impacted them. (for example if the Storage Lead, Distributor Lead, and Forum Lead are all also council members, it can become murky when it comes to approving a new budget). In a real world scenario we will likely have a much larger pool of participants so this is of much less concern.

**Comment by traumschule** [comment]
Abstentions are still counted as rejection: 2 approvals / 0 rejections / 1 abstain => reject for 100% quorum

![abstain-fail](https://user-images.githubusercontent.com/31551045/212334204-9867d517-5339-426c-b7db-d65eb00ce56b.png)
https://pioneerapp.xyz/#/proposals/preview/38

**Comment by thesan** [comment]
In Joystream/pioneer#3669 it was decided that Abstentions should be counted in the quorum, however it looks like the chain rejected this proposal due to the 3 votes quorum not being reach.

@dmtrjsg, @bedeho should the runtime or Pioneer be updated ?

**Comment by thesan** [comment]
The way I see it:
1. Counting the abstentions in the quorum allow councilors to have a lesser impact on the vote and let the others decide.
2. Not counting it allow those who don't intend to vote to have the exact same effect but without stalling the proposal.

**Comment by traumschule** [comment]
Abstaining should count as vote but not towards approval quorum. In this example: 3 votes cast, 100% approval.

**Comment by thesan** [comment]
> Abstaining should count as vote but not towards approval quorum. In this example: 3 votes cast, 100% approval.

@traumschule do you mean "count as vote but not towards approval ~~quorum~~ threshold" ? If not please keep in mind that the approval quorum is is the denominator in the `3 / 3 votes` the numerator is actually the votes count. The approval quorum only dependents on the proposal type and council size. Here it was always 3 from the start to the end of the vote.

So if a vote is included in the votes count it does "count towards the approval quorum".

**Comment by traumschule** [comment]
Yes, and no, sorry for the confusing use of terms.
- it counts towards quorum (to avoid auto reject)
- it does not count towards approval, rejection or slashing threshold

In contrast to the definition I would count abstentions as "blank" meaning it is counted towards the quorum (voter was present but does not intend influence outcome). This can be used to signal conflict of interest, disalignment with public opinion or when feeling insufficiently informed (by the proposal).

As such i might even suggest to rename it to "blank" or "present" (see section "International and national parliamentary procedures").

> [Abstention](https://en.wikipedia.org/wiki/Abstention) must be contrasted with "[blank vote](https://en.wikipedia.org/wiki/None_of_the_above)", in which a voter casts a ballot willfully made invalid by marking it wrongly or by not marking anything at all. A "blank (or white) voter" has voted, although their vote may be considered a [spoilt vote](https://en.wikipedia.org/wiki/Spoilt_vote), depending on each legislation, while an abstaining voter has not voted.

As shown below there is no clear convention among legislations.

> If a majority of members of the [United Nations General Assembly](https://en.wikipedia.org/wiki/United_Nations_General_Assembly) or one of its [committees](https://en.wikipedia.org/wiki/United_Nations_General_Assembly#Subsidiary_organs) abstain on a measure, then the measure fails.
> In the [Council of the European Union](https://en.wikipedia.org/wiki/Council_of_the_European_Union), an abstention on a matter decided by unanimity has the effect of a yes vote; on matters decided by [qualified majority](https://en.wikipedia.org/wiki/Qualified_majority) it has an effect of a no vote.
> In the [Italian Senate](https://en.wikipedia.org/wiki/Senate_of_the_Republic_(Italy)), an abstention used to have the effects of a no vote. This was changed in 2017, when it was established that a measure only needed for the number of yes votes to be higher than the number of no votes in order to pass, with abstentions being counted neither as yes votes nor as no votes.[[6]](https://en.wikipedia.org/wiki/Abstention#cite_note-6)
> In the [United States House of Representatives](https://en.wikipedia.org/wiki/United_States_House_of_Representatives) and many other legislatures, members may vote "present" rather than for or against a bill or resolution, which has the effect of an abstention.
