### ISSUE TITLE
Downscale avatar images during member migration

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4339]
### Problem
When we do migration of memberships from Rhodes to Carthage OR from Carthage to Mainnet, it would be beneficial to take all the existing member avatars and downscale them to some reasonable sizes. Currently, some of the members have huge images associated with their profiles, making both Pioneer's and Atlas' performance degraded.

### Proposal
As all new memberships created with both apps after Carthage will use new Atlas Avatar Service, we will use the same for migrated memberships. Let's create a script, or modify a script that we will be using for migrating the memberships, so that for each member it downloads the avatar image linked via URL, uses some library to convert it to reasonable size and then upload it to Atlas Avatar Service, and update original member profile with URL linking to Atlas Avatar Service.

* These are params Atlas uses for member avatars: 192x192, webp format, 0.8 quality

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203106428528605) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
@kdembler could you share some info / ref code on how to upload images to the avatar server. Is there a special naming convention for file names we should follow?

edit: found it :) https://github.com/Joystream/atlas/blob/master/packages/atlas-avatar-service

**Comment by kdembler** [comment]
@mnaamani Yep, sorry, there aren't really any docs around this feature. Feel free to hit me up for any details that you may not understand from the code itself

**Comment by mnaamani** [comment]
Prepared tools here: https://github.com/mnaamani/avatar-migration
Chose to keep the migration of avatars as a separate step used to prepare the final member.json used by the member bootstrapping script.
