### ISSUE TITLE
Stakes of failed applications are not automatically released

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#4342]
Applicant has to withdraw stake manually via `withdrawApplication` [extrinsic](https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/extrinsics) to be able to recover stake from the respective WG.

Expected behavior when an opening is filled is that stakes for not hired applicants are returned / recoverable.

Related: joystream/pioneer#3665 joystream/pioneer#3663

**Comment by bedeho** [comment]
This is not expected, the lack of automatic release is by design

https://joystream.gitbook.io/testnet-workspace/system/working-groups#effect-3

and this is required if you wish to not constrain the number of applicant for a role.
