### ISSUE TITLE
Query node processor error: "Invalid string length"

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4360]
Investigate error described in https://github.com/Joystream/joystream/pull/4319#pullrequestreview-1135994364, probably caused by too large result when processor queries the indexer to retrieve latest events.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203134411863935) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Fixed in https://github.com/Joystream/joystream/pull/4366
