### ISSUE TITLE
Core Weight Generation Error

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4369]
Running weight generation script on branch https://github.com/Joystream/joystream/tree/carthage-weights-gen (which just combines all the yet unmerged PRs for carthage) I get an error on the reference hardware machine AWS `c6id.2xlarge` EC2 instance type ->  3rd Generation Intel Xeon Scalable processors (code named Ice Lake) https://aws.amazon.com/ec2/instance-types/c6i/

```
uname -m
x86_64

Generating storage weights
Storage weights generated successfully
It took 1 seconds
Generating core weights
Error: Client(ApplyExtrinsicFailed(Validity(TransactionValidityError::Invalid(InvalidTransaction::BadProof))))
Core weights generated successfully
It took 2 seconds
Generating weights for frame_system...
.
.
```

The weight generation is successful however. Is this something to be concerned about?

I cannot reproduce the same error on Mac M1, or other AMD64 machines.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203150191418395) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
No issue on Ubuntu 20.04.4 LTS, Intel Core i5-10400F:
```bash
$ uname -m
x86_64

$ ./scripts/generate-weights.sh 1 1
Generating storage weights
Storage weights generated successfully
It took 2 seconds
Generating core weights
Core weights generated successfully
It took 424 seconds
# ...
```

**Comment by Lezek123** [comment]
However I noticed that this benchmark took very long time to execute, as compared to values shown in the issue description, ie.:

**My local run:**
```
Core weights generated successfully
It took 424 seconds
```

**AWS run (issue desc.):**
```
Core weights generated successfully
It took 2 seconds
```

**Comment by mnaamani** [comment]
> However I noticed that this benchmark took very long time to execute, as compared to values shown in the issue

Great observation, I presume this means the generated weights "block_weights.rs" and "extrinsics_weights.rs" are not reliable. I will generate on Google Cloud ref machine in this case on, AMD Zen3, or newer (EPYC or Ryzen) and report back.

**Comment by mnaamani** [comment]
On the AMD processor the error has gone away, I have generated weights and pushed them 5e68a62bbf2503c7c0d427079cb7aa8429565793

I also ran full integration tests on the amazon machine to confirm no issues appeared.
