### ISSUE TITLE
Problem: Orphaned content

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#4373]
I was exploring a metaverse project and noticed a **significant** amount of `orphaned content`

`Orphaned content` refers to content that is uploaded via a certain gateway and then the gateway provider shuts down, loses access or is down for some reason. 
If we use this example:
- content creator uploads content via gateway and shares the URL or uses it around the place: `www.coolvideos.com/username/vid123.mp4` or even their channel URL `www.coolvideos.com/usersname/channel`
- `coolvideos.com` shuts down or has prolonged downtime
- Now everywhere the URL was shared basically becomes dead

Not sure of the best solution to this, but it is definitely a problem worthy of discussion.

**Comment by bedeho** [comment]
There is no way to solve this really, its a real problem though. I would call this linkrot, more than the content being orphaned, as it still exists in the system.

**Comment by mochet** [comment]
Agreed there is no way to solve this just yet.

(thinking out loud here just to explore)

Even if there is no current solution, I am curious if there is:
- Any services or standards that allow for alternative-URLs to be added manually or automatic detection of these at the time of sharing a link. Maybe there are some sites/standards that can support this.
- Any services/databases/extensions that maintain lists of dead domains and can redirect content (really not sure if such a thing exists) or can automatically direct to archival links
- If the DAO could somehow own a decentralized domain that acts as a URL shortener and by using social agreements or some form of smart contract redirect linkrot to another gateway in the event that a gateway is discontinued

and maybe, depending on how our end-users manage their keys and if wallets become widely accepted enough to viewersr, that a wallet extension/browser could at some point detect a gateway being discontinued and automatically redirect users to an alternative gateway by accessing on-chain data. For example the Opera browser allows a user to specify an IPFS gateway manually.
