### ISSUE TITLE
Note: Restricting mainnet scope

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4376]
I propose we do the following in order to secure mainnet timeline.

1. Feature/tech-debt freeze runtime+node at `Carthage` release, only bugfixes of critical severity are merged after  `Carthage` testing is done, and must be somehow tested by some yet-to-be-proposed testing scheme.
2. Any planned runtime+node issues which were part of `Mainnet` runtime scope must be moved to `Carthage` release if truly unavoidable otherwise.
3. Enhancing `Colossus` and `Argus`, currently, part of `Mainnet`, is not to be part of this release. This also means cascading `Atlas` & `YPP` enhancements to accommodate are not part of the release. They should still be worked on as next items, as planned, but they will not be merged into mainnet branches, they will not be part of mainnet testing, and mainnet release does not wait for their finalization.
4. Exact same point as in 3 for `YPP`+`Gleev` to be released itself. 
5. A new release, under some new name, bundles 3+4 as one release, as soon as is possible post-mainnet. It will not require any runtime upgrade.

The case for this is:
- we absolutely _have to_ launch our chain safely before EOY, and we still don't even know what issue can come from
  - YPP/backend testing
  - Carthage testing
  - Infra testing
- reduce complexity and uncertainty in communication, planning, execution, review, and testing, which are already formidable.
- post-launch there will be a non-trivial rolling out period in various stages, of uncertain length, which means there is significant "dead time" which we are not "paid" to have all this stuff early, so being able to work during this time unlocks value for us.
- while `Gleev` does not technically depend on `YPP`, and technically is not risky (I _believe_), we would currently launch it _totally empty_, it would be nice to have even just a handful of first creators and give it a proper standalone announcement.
- allows us to spend a bit more time on the infra-side, doing things right, getting more input from testnet operators who are standing by for us to meet on this topic.

The new work generated from this proposal would be: 
- to accommodate this is to make sure we have a reasonable variation of our mainnet landing page that works while we are launching, rolling out through the relevant stages, and before `Gleev` is up and running.

**Comment by dmtrjsg** [comment]
## Scope

Marketing website on mainnet launch needs to:

- Have a banner for mainnet launch for marketing website pointing to a blog post. 
- Keep the links to the Gleev app 
- Very likely to include the concept of multiple gateways, based on the issue linked below
- https://github.com/Joystream/atlas/issues/3321 

- YPP is 100% out of scope for mainnet launch, so can remain as "Coming soon" on both marketing and Gleev apps.

### Additional info
__
1. Mainnet launch is independent of Gleev. If Gleev is not ready it still goes forward. 
2. Gleev may be even launched before mainnet, at any time as soon as its ready. 
3. During the first days and weeks after mainnet launch Gleev app will likely be not operational.  Here's the issue to update:
https://github.com/Joystream/atlas/issues/3320#issuecomment-1282179254
NB: Gleev app itself will be under maintenance screen for as long as we choose to.
