### ISSUE TITLE
Patronage interest rate calculation

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#4378]
### Current patronage computation
`patronage_amount = issuance * patronage_rate_per_block * number_of_blocks * blocks_per_year`
### Desired patronage calculation
`patronage_amount = issuance * ( 1 + patronage_rate_per_year)^{number_of_blocks/blocks_per_year} - issuance`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203361526020352) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
1. isnt the patronage rate annual? not per block?
2. why is `issuance` being subtracted?

**Comment by dobertRowneySr** [comment]
> 1. isnt the patronage rate annual? not per block?

`blocks` meant number of blocks in a year (I have renamed it now). The user gets to specified the annual rate, but we store it as per block rate to have easier computations (which is similar to what the pallet vesting is doing)

> 2. why is `issuance` being subtracted?

To obtain the net amount that will be granted to the creator account:
If I put 10 $ into a risk free bond with 3% interest rate in 10 years the amount will be `10 * (1 + 3%)^10` the net gain `10 * (1 + 3%)^10 - 10`

**Comment by bedeho** [comment]
ok, makes sense.

**Comment by ignazio-bovo** [comment]
- $r$ yearly interest rate
- $t$ = number of years
- $n$ = number of blocks in a year 

If we subdivide the years in $n$ compounding periods (corresponding to each block)

$$ I = \bigg(1 + \frac{r}{n} \bigg)^{n t} - 1 \approx e^{rt} - 1 $$

with $n$ large enough (in our case 5 259 487.66) -> ok

$$ I = e^{rt} - 1 \approx rt + \frac{(r t)^2}{2} + \frac{(rt)^3}{6} + \frac{(rt)^4}{24} $$

# Plan
- drop the convertion from yearly rate to block rate
- compute $rt + \frac{(r t)^2}{2} + \frac{(rt)^3}{6} + \frac{(rt)^4}{24} = y$ and then split $y = y_{int} + y_{frac}$ (integer + fractional)
- patronage amount is found by multiplying the `total_supply` value by `y_int` with ordinary `checked_mul` and then after add the value `Perquintill::from_float(y_frac}.mul_floor(total_supply)`

**Comment by ignazio-bovo** [comment]
Addressed in #4516

**Comment by ignazio-bovo** [comment]
Clearly there should be a max value on the patronage to avoid dilution

**Comment by dobertRowneySr** [comment]
Remember to update benchmark if extra computation is required
