### ISSUE TITLE
Integration Tests without Sudo calls

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4401]
After main net is deployed, the sudo pallet will be removed from the runtime.
Many Integration/Network tests depend on sudo pallet for putting the runtime in certain states or bypassing the council. These tests will all break see: https://github.com/Joystream/joystream/pull/4400

The tests need to be updated to work around this limitation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203661753438153) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
We have to decide whether we actually want to keep such Sudo calls as part of testing, @mnaamani suggest this is not a good long term solution.

**Comment by bedeho** [comment]
We concluded
- sudo pallet will be removed
- tests are fixed by making tests sufficiently complex so as to bootstrap council and other steps in order to get to the right milestone for real tests to begin.
