### ISSUE TITLE
Forum benchmarks: Fix worst case scenarios in `*_moderator` benchmarks

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4403]
As discovered in https://github.com/Joystream/joystream/pull/4398#discussion_r1004251819, we have a few benchmarks like:
- `update_category_title_moderator`
- `update_category_description_moderator`
- `delete_category_moderator`
- `move_thread_to_category_moderator`
- ...

For extrinsics that rely on `ensure_can_moderate_category` method.

The problem is that those benchmarks don't account for the worst case scenario correctly.
They all use `generate_categories_tree` helper to generate deeply nested category, but then they assign the moderator directly to this category. Instead, the moderator should be assigned to the root parent category, as this would trigger the largest number of iterations here: https://github.com/Joystream/joystream/blob/carthage/runtime-modules/forum/src/lib.rs#L1874, each iteration constituting an additional `CategoryByModerator` read operation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203238714475714) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Done in https://github.com/Joystream/joystream/pull/4408
