### ISSUE TITLE
Colossus: Use autogenerated types for express request / response data

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4405]
As discovered [here](https://github.com/Joystream/joystream/pull/4381#discussion_r1004399253) there are some discrepancies between Colossus' openapi spec and the types that are used to describe request / response data. This opens up a room for errors, like the one made in the PR linked above.

**Solution:** Those types should be autogenerated from openapi spec, so that they are always in sync. This approach was already successfully implemented in Argus.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203237821910142) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Great idea :)

**Comment by bedeho** [comment]
- What should we do about this inlined API outline in the README? https://github.com/Joystream/joystream/tree/master/storage-node#api
- Does this need a similar fix in Hydra?

**Comment by bedeho** [comment]
Done in #4412
