### ISSUE TITLE
Make `@joystream/types` package hybrid (CJS+ESM)

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/joystream#4433]
Currently `@joystream/types` package is a commonJS module (CJS). However, it's better for the `Atlas` build system if it only uses ES modules (ESM) as its dependencies. 

As Klaudiusz described the context: 

> Our build system can handle CJS dependencies, but there are some issues around it. If we use @joystream/types without patching, it will work, but its dependencies will also be used in CJS versions (so all of @polkadot packages). Then, if we also use those @polkadot packages in our app, we will use ESM versions so the end result is that we have 2 copies of each library, one CJS and one ESM
Doing patching allows us to get rid of this issue and use only ESM versions

The hybrid module setup for Channels Payouts lib was done in https://github.com/Joystream/joystream/pull/4334 so lets do that for the types package too.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203351090466495) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Done in #4435
