### ISSUE TITLE
Idea: Introduce people metadata

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4440]
People, both as standalone entities, and their relationship to content, is part of the design, but its missing from the app and content directory.

**Comment by dmtrjsg** [comment]
Users avatars and names next to the video in addition to channel; or even tagged users (this particular guy is featured in the video)

**Comment by kdembler** [comment]
Transferring to monorepo as it would require QN schema modeling and implementation first

**Comment by bedeho** [comment]
**Warning:** This is a super old issue, and it corresponds to very old designs that no longer are part of Atlas. The idea certainly has some merit, but at this point I'm just going to close this issue because we are literally at level 0 when it comes to what this would mean, how it would get implemented or when. There are so many more important efforts already in the backlog that its not worth cluttering our minds with this at this time.
