### ISSUE TITLE
WASM Verification Error: `wasm trap: wasm unreachable instruction executed` => core::panicking::panic

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#4442]
_This was reported by OptimusAlgo91 in #validator against Carthage runtime._

> Hi i see this error when i try to send the transaction bound and validate:
> i checked the endpoint also updated metadata and polkadot.js is at the last version
> i have enough in stash and controller
```
utility.batchAll
1002: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm unreachable instruction executed WASM backtrace: 0: 0x40fbce - <unknown>!rust_begin_unwind 1: 0x45fb - <unknown>!core::panicking::panic_fmt::h0a20ba97f16cb738 2: 0x2ed5b7 - <unknown>!TaggedTransactionQueue_validate_transaction : RuntimeApi, Execution failed: Execution aborted due to trap: wasm trap: wasm unreachable instruction executed\nWASM backtrace:\n\n 0: 0x40fbce - <unknown>!rust_begin_unwind\n 1: 0x45fb - <unknown>!core::panicking::panic
```
![](https://cdn.discordapp.com/attachments/814958846224236584/1042547633891328000/verification-error.png)

[Related?](https://github.com/search?q=org%3AJoystream+WASM+backtrace%3A&type=issues)

**Comment by mnaamani** [comment]
@traumschule Do you have a ballpark figure around which blocknumber this occurred. So I can take check the logs of the rpc node around that time.

**Comment by traumschule** [comment]
Probably around #89000 (reported Nov 16 8:50pm).

**Comment by mnaamani** [comment]
Thanks, although I can't find a verification error in the logs on the public rpc endpoint, I did come across:

```
Nov 16 18:55:12 localhost joystream-node[637]: 2022-11-16 18:55:12 ✨ Imported #89026 (0x3206…9593)
Nov 16 18:55:13 localhost joystream-node[637]: 2022-11-16 18:55:13 💤 Idle (75 peers), best: #89026 (0x3206…9593), finalized #89024 (0xed97…cf75), ⬇ 7
8.8kiB/s ⬆ 71.0kiB/s
Nov 16 18:55:17 localhost joystream-node[637]: 2022-11-16 18:55:17 Accepting new connection, 27/1000
Nov 16 18:55:17 localhost joystream-node[637]: 2022-11-16 18:55:17 Ran out of free WASM instances
Nov 16 18:55:17 localhost joystream-node[637]: 2022-11-16 18:55:17 Ran out of free WASM instances
Nov 16 18:55:17 localhost joystream-node[637]: 2022-11-16 18:55:17 Ran out of free WASM instances
Nov 16 18:55:17 localhost joystream-node[637]: 2022-11-16 18:55:17 Ran out of free WASM instances
```

I don't think it is [https://github.com/paritytech/polkadot/issues/4275](related) to the main issue, but I will configure the rpc node to handle more WASM instances. ref:

**Comment by bwhm** [comment]
Yeah, I was debugging with the user on discord.

The user was on mac, using chrome and the polkadot-js signer.

Multiple attempts were made, and multiple possible sources of error was addressed, but no success. Examples:
- Metadata was initially not injected (settings -> metadata -> inject -> accept)
- Updating the version of the polkadot-js signer
- Restarting browser (after the above two)

We even tried a regular `balance.transfer`, which also failed. At this point, I was "sure" it was on the users end, and advised to try a different browser, which worked...
