### ISSUE TITLE
Update CI actions to node 16

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#4489]
Noticed this warning for test (14.x, ubuntu-latest)
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2

Requires update of actions defined in 5b6529ff490182cb0e8a97d459b0b0a8a24c4c63

**Comment by mnaamani** [comment]
Addressed in https://github.com/Joystream/joystream/pull/4778
