### ISSUE TITLE
QN returns some `JOY` amount as json `number`

### ISSUE THREAD

**Issue by thesan** [Joystream/joystream#4503]
So this comes from the QN returning the update amount as a `number`. The problem is that the amount is `50000000000000000` which is (one digit) greater than `Number.MAX_SAFE_INTEGER` as a result the `bn.js` throws an error.

Try this on https://atlas-next.joystream.org/query-node/server/graphql:
```gql
query {
  proposals (where: { details_json: { isTypeOf_eq: "UpdateWorkingGroupBudgetProposalDetails" } }) {
    details {
      ...on UpdateWorkingGroupBudgetProposalDetails { amount }
    }
  }
}
```

It's potentially a wide spread issue because although Pioneer expects strings since [this change](https://github.com/Joystream/pioneer/pull/3335/files#diff-b9ca97457feb4162955676ae3378c8338e2be767cd9b7155e018f0c49ee58a6e) all the `Float` values from [`@/common/api/schemas/schema.graphql`](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/common/api/schemas/schema.graphql) are returned from the QN as `number`. For stuff like block numbers it's fine (although `Int` would be more appropriate) but for JOY amount this often might trigger exceptions in `bn.js`. This is actually the bug that @traumschule reported here: https://github.com/Joystream/pioneer/issues/2327#issuecomment-1336443690.

A quick fix here would be to just cast the amount to a `string` and then to a `BN`. However it also means a small precision loss.

I don't think this can be fixed long term on the client. @zeeshanakram3, @Lezek123 can you think of an easy fix on the QN for this ?

_Originally posted by @thesan in https://github.com/Joystream/pioneer/issues/3994#issuecomment-1363203226_

**Comment by traumschule** [comment]
Since this is being worked on i'd like to invite to also think about #4515.

**Comment by Lezek123** [comment]
It seems that when `BigInt` is used as type for `@variant` property, it is converted to `Float` in the output schema (ie. see: https://github.com/Joystream/joystream/blob/master/query-node/schemas/proposals.graphql#L230)

I think a simple solution would be to use `String` type in the input schema instead in those cases (variants), but it may be worth to investigate if we can fix it on the Hydra side

**Comment by thesan** [comment]
@Lezek123 I didn't realized it happens only on `@variant` thanks.

I was hopping this was a one line change somewhere. But otherwise I'll just change the types to `String` when needed in the schemas at some point.

Here's the full list of `type`s with `Float` properties in the output:
```
GeoCoordinates
OwnedNft
AuctionTypeEnglish
BountyEntryStatusWinner
BountyFundingLimited
BountyFundingPerpetual
CouncilStageAnnouncing
CouncilStageElection
CreateWorkingGroupLeadOpeningProposalDetails
DecreaseWorkingGroupLeadStakeProposalDetails
SetCouncilBudgetIncrementProposalDetails
SetCouncilorRewardProposalDetails
SetInitialInvitationBalanceProposalDetails
SetMembershipPriceProposalDetails
SetWorkingGroupLeadRewardProposalDetails
SlashWorkingGroupLeadProposalDetails
TerminateWorkingGroupLeadProposalDetails
TransactionalStatusBuyNow
TransactionalStatusInitiatedOfferToMember
UpdateWorkingGroupBudgetProposalDetails
CommentTextFTSOutput
MembersByHandleFTSOutput
PostsByTextFTSOutput
ProposalsByTitleFTSOutput
SearchFTSOutput
ThreadsByTitleFTSOutput
VideoCategoriesByNameFTSOutput
ProcessorState
NftIssuedEvent
```

But only some of them have the property initially set to `BigInt`. Others have properties explicitly set to `Float`.

**Comment by thesan** [comment]
@traumschule 
> Since this is being worked on i'd like to invite to also think about #4515.

The way I see it #4515 would either require a lot of mapping updates or some clever Hydra changes. Either way it probably shouldn't be worked on in parallel to this one.

**Comment by traumschule** [comment]
Agreed. Just wanted it to be known. :wink:

**Comment by Lezek123** [comment]
Addressed in https://github.com/Joystream/hydra/pull/516 and https://github.com/Joystream/joystream/pull/4616
