### ISSUE TITLE
Add the mechanism to reward channels (App owners) for gateway attribution part of incentives scheme

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#4539]
## Context

https://github.com/Joystream/joystream/issues/4538

## Scope
- [ ] Design mechanism to reward applications as channels

**Comment by bedeho** [comment]
Applications as channels are just paid the same way that channels are paid: channel payput proposal from council.
So the council just has to include channels that are apps i their payout policy and payloads, nothing new has to be built or done.

**Comment by dmtrjsg** [comment]
nice, thank you. I guess then we would just present the rationale field at the point of claiming the reward. Closing.
