### ISSUE TITLE
Publish final changelog and version bump for CLI in `Ephesus`

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4547]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203774781127731) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Please don't forget to also run `yarn workspace @joystream/cli oclif-dev readme`

**Comment by zeeshanakram3** [comment]
Was addressed in #4601
