### ISSUE TITLE
Ensure UpdateChannelPayouts proposal is not filtered

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4552]
In current runtime the `UpdateChannelPayouts` proposal type is not allowed: https://github.com/Joystream/joystream/blob/cd24c5d410d7419daa8608ea48ef523ea726c200/runtime/src/lib.rs#L256

We will be updating ephesus branch from master before release, so we should ensure we drop filtering out of this proposal type. The proposal type allows council to enable/disable channel payouts (globally) and set Min/Max cashout allowed.

Interestingly the genesis config for content module has `channel_cashouts_enabled` set to true. Was this a mistake?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203778822926534) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
> Interestingly the genesis config for content module has channel_cashouts_enabled set to true. Was this a mistake?

I don't think so per say, what harm could come from that?
