### ISSUE TITLE
Running list of changes to runtime in `Ephesus`

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4563]
- https://github.com/Joystream/joystream/issues/4535
- https://github.com/Joystream/joystream/issues/2927
- https://github.com/Joystream/joystream/issues/4524
- https://github.com/Joystream/joystream/issues/4552
- https://github.com/Joystream/joystream/issues/4507
- https://github.com/Joystream/joystream/issues/4556: i.e. dropping Sudo
- https://github.com/Joystream/joystream/issues/4574
- https://github.com/Joystream/joystream/issues/4655
- https://github.com/Joystream/joystream/issues/4643
- https://github.com/Joystream/joystream/pull/4644

**Comment by bwhm** [comment]
Not sure if it's intentionally left out, as it was already prepared for mainnet, but Move to Liberated by removing the `sudo` pallet:
- https://github.com/Joystream/joystream/issues/4556

could be added...

**Comment by ignazio-bovo** [comment]
The Gateway Working Group will be renamed to App. A data migration is needed:
- #4230
