### ISSUE TITLE
Argus: Release (`v1.0.0`)

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/joystream#4567]
## Context
This Argus release adds additional context to `/status` endpoint about the connected Query Node state so that the Argus node can be monitored both by DWG workers & lead.
 
## Dependency
- Depends on
  1. #4256 
  2. #4545
  
## Release estimate 
- Approx. One week (Subject to PR review of #4560 & addressing relevant CRs)

## People to be notified
- Argus maintainers (@mnaamani, @Lezek123, @zeeshanakram3)
- Distribution WG lead
- Distribution WG workers

## How to upgrade
- Since this release doesn't include breaking changes or critical bug fixes, upgrading to the new version is not required. Still, to upgrade the distributor-node follow https://github.com/Joystream/community-repo/blob/master/working-groups/distributors/NodeSteup/Upgrade/README.md

## Release commit on Monorepo
This Argus release is available at ce36724ba5dd024b383f018feed20af48e6dfa98 on monorepo, so make sure to checkout at this commit before doing upgrade.

**Comment by kdembler** [comment]
@zeeshanakram3 Is there any reason for Argus to be still at major version `0` and Colossus already at `3`? It seems to me that both are at a similar level of maturity, I think this versioning makes things slightly confusing.

**Comment by zeeshanakram3** [comment]
Keeping the nature of change in mind, I incremented the minor version from `0.2.0` to `0.3.0` for the next planned release. But you made a good point; there is no reason for keeping Argus major version at `0`, and it should be bumped.

**Q:** Would bumping the major version to `1` would be sufficient, or should we bump it all the way to `3` (skipping lower range), to make it consistent with Colossus? @kdembler

**Comment by kdembler** [comment]
I'm not sure what the answer should be tbh. But I'd guess that Argus and Colossus could introduce breaking changes independently of each other so probably it's not a requirement that they share the same major version
