### ISSUE TITLE
Pioneer v1 UX: Stop using tabs for actions

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#458]
As part of #400:

In many sections, tabs are used to get to screens for initiating actions, this makes no sense, e.g. forum here

<img width="369" alt="Screenshot 2020-05-23 at 12 25 05" src="https://user-images.githubusercontent.com/437292/82728470-8d9a3880-9cf0-11ea-86c4-b01c6f8bfee3.png">

Instead, lift top-level actions out as menu buttons over any possible tabs, if there are still tabs remaining. In many cases I am sure you really would end up with just a single screen, hence there would be no need for tabs.

Make a list of all such places, and fix them.

**Comment by kdembler** [comment]
List of affected tabs:
- Media -> New channel
- Forum -> New category
- My Keys -> Vanity address (potentially rename to "Generate vanity address")
- Address Book -> View memo
- Council -> Reveal a vote
- Proposals -> New proposal

I've excluded tabs that are not exclusively an action, for example Membership -> Edit my profile as this view can also serve as a way to just view current user's profile

I've also skipped views from the "Fully featured" mode, my guess is we don't really care about UX of these, my understanding is they're mostly for internal use
