### ISSUE TITLE
The `referendum.accountsOptedOut` query always returns `null`

### ISSUE THREAD

**Issue by thesan** [Joystream/joystream#4606]
I called the `referendum.optOutOfVoting` extrinsic implemented in #4409, with an account with the address `j4UJj3FvTRLwf3Gdbu2TQGJiybZU5gEhRL8U5mRS2Uookv1kK` on [block #68,962](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x09647b63afc956e681259d3b47c8ff36eb7e7943600db5ff5990af4b7b74f146)
![image](https://user-images.githubusercontent.com/6571453/217201483-f5e95b92-38c7-4321-a2ff-800af39e4e29.png)
[here are the details](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/extrinsics/decode/0xa101848407b752b0d2ecf414df7ff70cb895853a867e24dc3fe17d3dd903911378cb7f01a8c4788d65760e0010b8b61676d27e70b779c0c9dba96a200bdb6bf54053e324338bc90260401659f55748c5b70b58bda6a6fb85825eaddad78bbcb197519d82d50104001503)

But after that `referendum.accountsOptedOut("j4UJj3FvTRLwf3Gdbu2TQGJiybZU5gEhRL8U5mRS2Uookv1kK")` still returns `null`:
![image](https://user-images.githubusercontent.com/6571453/217202571-af651250-667b-4c83-81d9-e2d10ff015ec.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203918222377120) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
The on chain part is defined
``` rust
        pub AccountsOptedOut get(fn accounts_opted_out): map hasher(blake2_128_concat)
            T::AccountId => ();
```
and also from the polkadot-js UI you can see that the mapping returns `Null` hence it works as expected.
The map it is just used as a set to verify which account have been blacklisted through `StorageMap::contains_key(key) -> bool`, and not used for accessing elements.
So this is not a problem/bug.

Do you need to have a list of members that have been blacklisted?

**Comment by dobertRowneySr** [comment]
closing as it is not a bug
