### ISSUE TITLE
QN : WorkingGroup Schema

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/joystream#4614]
It would be good to have a WorkingGroup Schema to retrieve the following data for any blocknumber.

- budget
- workers
- openings

**Comment by bedeho** [comment]
This will require holding state in the QN, and it qill requrie running mappings on every block, it is not advisable, it has gigantic performance penalty. Whatever this is trying to do, this is probably not the way. Until aggregate queries arrive, possibly in Subsquid, ths is not really something we can do.
