### ISSUE TITLE
Community Infrastructure Testing of YPP

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4619]
# Note

This issue should really not be here, as this monorepo is primarily around work on the _codebase_ not the operational side of things. Next best place would really be forums, but without email notifications in Pioneer it is a near certainty that having a timely and dynamic conversation across multiple parties will be near impossible, so I am electing to just put this here for now. 

# Proposal

Test whether the current way infrastructure is organised, so in terms of actual hosts, configruations, on-chain state, whether it is capable of dealing with the load that YPP can bring upon launch. This may require launching a new staging network where all of this is setup to mirror mainnet, and also to get all workers involved setting up their nodes as they have on mainnet. I am not sure whether CDN also should be included in this testing, but storage clearly should. I guess the best first step here is to have the current @yasiryagi storage lead propose a plan. It should address

- what exactly we are testing
- how we will measure testing outcome
- how environment needs to be setup
- who needs to participate at various stages across DAO & Jsgenesis

**Comment by kdembler** [comment]
Closing since YPP has launched months ago and we're good
