### ISSUE TITLE
Pioneer v1 UX: Left adjust proposals in view

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#462]
As part of #400:

Unlike all other sections, content is centered, lets go back to the norm.

<img width="1755" alt="Screenshot 2020-05-23 at 13 56 51" src="https://user-images.githubusercontent.com/437292/82730135-d9071380-9cfd-11ea-9269-99369bf92d44.png">

**Comment by kdembler** [comment]
@bedeho just to make sure, you mean the whole view shouldn't be centered, i.e. getting rid of the padding between proposals and sidebar?
