### ISSUE TITLE
Missing mappings for `WorkingGroupBudgetFunded` event

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4625]
Query node mappings for `WorkingGroupBudgetFunded` aren't implemented, which may result in mismatch between runtime and QN state w.r.t. to current WG budget amount.

**Comment by mochet** [comment]
Not sure if it helps but I've been able to find WG budget increases via the following query:
`query MyQuery {
  budgetUpdatedEvents(limit: 1000) {
    groupId
    budgetChangeAmount
    inBlock
    id
  }
}`

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/4632
