### ISSUE TITLE
Pioneer v1 UX: Proposal text hard to read

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#463]
As part of #400:

Reading the proposal text is really hard, it's super small, and the formatting goes away.

 
<img width="1151" alt="Screenshot 2020-05-22 at 15 24 29" src="https://user-images.githubusercontent.com/437292/82730166-0b187580-9cfe-11ea-88ec-7d5b0fa3a403.png">

Both the content, and the top description are really too small.

**Comment by kdembler** [comment]
Looks like this was partly done as part of #621, the text is now properly formatted and much easier to read:
<img width="1072" alt="Screen Shot 2020-06-09 at 09 32 11" src="https://user-images.githubusercontent.com/12646744/84119136-3efcd600-aa34-11ea-9113-703c34e19020.png">
I'll just increase the font size slightly for the content and description
