### ISSUE TITLE
Add initial invitation balance to `MemberInvited` event

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4643]
Add initial invitation balance to `MemberInvited` event to avoid having to hardcode it in the query node: https://github.com/Joystream/joystream/blob/master/query-node/mappings/src/membership.ts#L74

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203993382260318) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Done in #4646
