### ISSUE TITLE
Proposals: Proposal to burn tokens from council mint

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#4684]
Currently on mainnet we're having our first discussion about the council mint replenishment level: https://pioneerapp.xyz/#/forum/thread/269

One thing that may be interesting to have is a proposal that can be triggered `n` times per council period and can burn some max % of the council mint. 

The problem this solves is that it requires a lot less friction than the budget replenishment amount proposal which has a constitutionality of 3.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205110272553430) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
1. Hard to reply without a proper problem vs. solution distinction here.
2. There is not budget replenishment proposal: https://handbook.joystream.org/system/proposal-system

**Comment by bedeho** [comment]
Covered here: https://github.com/Joystream/joystream/issues/3494
