### ISSUE TITLE
distributor README lacks install section

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#4712]
https://github.com/Joystream/joystream/tree/master/distributor-node

The node does not work out of the box and `yarn` isn't sufficient. Developers familiar with the project could guess `yarn build:packages` run from repo root but that's too implicit.

```
joystream$ yarn && yarn build:packages
Done in 498.15s.
$ cd distributor-node
/joystream/distributor-node$ ./bin/run leader:invite-bucket-operator -B 3:0 -w 10
2023-03-26 21:59:32:5932 CLI info: Inviting distribution bucket operator...
{
    "bucketId": {
        "distributionBucketFamilyId": "3",
        "distributionBucketIndex": "0"
    },
    "workerId": 10
}
? Tx fee of 7.7000 mJOY will be deduced from you account, do you confirm the transfer? (y/N
```

There's also the problem that the distributor config isn't picked up run from repo root.
`yarn distributor-node leader:..` stopped working.

**Comment by bedeho** [comment]
Thank you for reporting.

**Comment by mnaamani** [comment]
Also perhaps readme can point to deployment config and mention using http2 reverse proxy usage ref: https://github.com/Joystream/joystream/issues/3808
