### ISSUE TITLE
Runtime returns incorrect values for constants: `DefaultGlobalWeeklyNftLimit`, `DefaultChannelDailyNftLimit` & `DefaultChannelWeeklyNftLimit`

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/joystream#4726]
When querying these constants by Polkadot js API, each returns `100`, which is the value of `DefaultGlobalDailyNftLimit`. Turns out that there is a bug in correctly exposing these three constants.

see https://github.com/Joystream/joystream/blob/4c8ed8652ba35da9a6ec4f648f7d6a4d45c54c5c/runtime-modules/content/src/lib.rs#L335-L344

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1204404643315743) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Fixed in #4705
