### ISSUE TITLE
Expose information about QN used in core nodes

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4732]
# Background

Multiple different services now are powered by a QN, specifically

- Argus
- Colossus
- YT-synch

It may be useful for leads and others to understand what QN version a given operator is using, as this may be important in preparation for upgrades and debugging. This capability was explicitly requested by a lead around the Ephesus upgrade.

# Proposal

Add some sort of public diagnostics endpoint which describes this, among other possibly useful things. I don't think it is a security or denial of service risk if done properly.

**Comment by 0x2bc** [comment]
let's adjust this requirement in the following way
> It may be useful for leads and others to understand what QN version a given operator is using, **and what's QN URL a given operator is using (localhost or third party one)**

**Comment by traumschule** [comment]
> "queryNodeStatus":{"url":"https://query.joystream.org/graphql","chainHead":1740687,"blocksProcessed":1739709}}

Just need to add the version to the status output.

**Comment by 0x2bc** [comment]
@traumschule this works for DP. 
For SP node we are lack both QN URL and QN version
