### ISSUE TITLE
Review use of synthetic distributor monitoring tool

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4734]
Note: this is an RnD and operational issue, probably should have been on the forums, however, lack of notifications makes it very hard to use productively.
 
# Background

Monitoring the performance of the distributors is a complex task, and it requires combining multiple methods. We are already introducing better active logging through standardising performance and error reporting from app backends to leads, on behalf of app clients. This push based method is however not without its own costs and limitations, hence having a pull based synthetic monitoring method would complement it well. There are many such tools already on the market, hence we should not need to write any new software. A quick chatgpt consultation reveals

**Q:** Please provide a list of open source, automatic synthetic CDN monitoring tools which allow probing from from different geographic locations.
**A:**

> There are several open source tools available for synthetic CDN monitoring, which enable you to probe from different geographic locations. Here's a list of some popular ones:
>
>  - Grafana Synthetic Monitoring (formerly known as WorldPing): Grafana Synthetic Monitoring is an open source tool that provides global coverage for monitoring your CDN performance. It allows you to create checks for uptime, response time, and other metrics from various geographic locations. Website: https://grafana.com/products/synthetic-monitoring/
> - Sitespeed.io: Sitespeed.io is an open source tool that helps you monitor, analyze, and optimize your website's performance. It supports distributed testing, allowing you to collect performance metrics from different geographic locations. Website: https://www.sitespeed.io/
> - Prometheus and Blackbox Exporter: Prometheus is a powerful open source monitoring and alerting toolkit. By using the Blackbox Exporter with Prometheus, you can set up synthetic monitoring for your CDN from various locations. Website: https://prometheus.io/ and https://github.com/prometheus/blackbox_exporter
> - Uptime Kuma: Uptime Kuma is an open source monitoring tool that supports multiple notification methods and enables you to monitor HTTP, TCP, and ICMP endpoints. You can deploy Uptime Kuma instances in different geographic locations to monitor your CDN performance. Website: https://github.com/louislam/uptime-kuma
> - OpenNMS: OpenNMS is an open source, enterprise-grade network management application that provides network monitoring and performance management capabilities. It allows you to monitor your CDN from various locations by setting up remote pollers. Website: https://www.opennms.com/
>
> While these tools allow you to monitor your CDN performance from different geographic locations, you may need to deploy instances of these tools in various regions or utilize cloud providers with global infrastructure to fully leverage their capabilities.

# Proposal

Conduct an initial review of the major alternatives in terms of cost of integration, feature set, easy of use, tooling, size of community and infra, cost of hosted alternatives, etc.

**Comment by kdembler** [comment]
I see you've listed open source tools, but setting them up in a distributed way may be tricky. That is, you would need to maintain some global infrastructure for running the tests from multiple locations. I can recommend Checkly (Atlas team uses it) as possible contender, while you need to pay it for it monthly, all the infra burden is handled by them and you can easily set up automated API checks from tens of locations around the globe

**Comment by bedeho** [comment]
>I see you've listed open source tools, but setting them up in a distributed way may be tricky.

Yeah I was hoping this somehow works out of the box, since all users would need to solve this problem, but perhaps starting with a fully hosted solution is actually better for us either way, because itw ill still be simpler than whatever automation these open source tools provide, and reducing time & complexity for this to be deployed def. has a lot of value.

**Comment by kdembler** [comment]
Closing since:
1. DWG already uses synthetic tests with our custom tool - https://github.com/joyutils/dwg-tools/tree/main/apps/dwg-ping
2. We also have benchmarking app - https://benchmark.joyutils.org/
3. We are working on analyzing user metrics directly from Gleev
