### ISSUE TITLE
[Argus] Automated Docker publishing

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4764]
It would be much more convenient for deployment if Argus was published as a standalone Docker image, with no dependencies on mounted Joystream monorepo. This way upgrade process would be much easier and less error-prone than it is today

**Comment by mnaamani** [comment]
Done in https://github.com/Joystream/joystream/pull/4780
The workflow to publish to docker hub however for now needs to be triggered manually (or with a workflow_dispatch)
