### ISSUE TITLE
Colossus current log file name

### ISSUE THREAD

**Issue by yasiryagi** [Joystream/joystream#4781]
Issue : Current have date attached to it and does not follow Linux logs naming convention .

Example 

```
/joystream # ls -l  /data/joystream-storage/log/
total 124904
-rw-r--r-- 1 root root 17269324 May 28 01:59 colossus-2023-05-27.log
-rw-r--r-- 1 root root 22328029 May 29 01:59 colossus-2023-05-28.log
-rw-r--r-- 1 root root 20447951 May 30 01:59 colossus-2023-05-29.log
-rw-r--r-- 1 root root 23066917 May 31 01:59 colossus-2023-05-30.log
-rw-r--r-- 1 root root 19633662 Jun  1 01:59 colossus-2023-05-31.log
-rw-r--r-- 1 root root 17322281 Jun  2 02:00 colossus-2023-06-01.log
-rw-r--r-- 1 root root  7786316 Jun  2 13:54 colossus-2023-06-02.log
```

Ask: 
can we follow the Linux convention where the current file would not have a date on i.e. colossus.log
This will make easy for the logs parsing tools.

Example of Linux naming:

```
@joystream ~/joystream # ls -la /var/log/syslog.*
-rw-r----- 1 syslog adm 5915 Jun  2 00:00 /var/log/syslog.1
-rw-r----- 1 syslog adm 1607 Jun  1 00:00 /var/log/syslog.2.gz
-rw-r----- 1 syslog adm 1562 May 31 00:00 /var/log/syslog.3.gz
-rw-r----- 1 syslog adm 1566 May 30 00:00 /var/log/syslog.4.gz
-rw-r----- 1 syslog adm 1094 May 29 00:00 /var/log/syslog.5.gz
-rw-r----- 1 syslog adm 1729 May 28 00:00 /var/log/syslog.6.gz
-rw-r----- 1 syslog adm 1439 May 27 00:00 /var/log/syslog.7.gz
```

Also would be good if the history log files are compressed. 

Note: date is not needed as the file have a timestamp.

**Comment by mnaamani** [comment]
I have no objection to this, it is a very reasonable feature request. I think it should be a simple config option for how winston (the logging package we are using) does log file naming and rotation.

Will look into it.

**Comment by mnaamani** [comment]
Note to self: Fix to be done here:

https://github.com/Joystream/joystream/blob/0e1462bed2afd84e8eb613ef718b5455f915e1ca/storage-node/src/services/logger.ts#L251
