### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by chevdor** [Joystream/joystream#48]
Hi there,

I have talk to someone from the team at #sub0 about the need for a docker image for the project. I can help with that. You can ping me on Riot at `@chevdor:matrix.org`.

**Comment by siman** [comment]
> I have talk to someone from the team at #sub0

Hi @chevdor , it was me at [Sub0 conference](https://sub0.parity.io/). You told me that you created a [Docker image for Substate](https://hub.docker.com/r/parity/substrate) (10k downloads) and it should not be hard to create a **proper** docker image for our Joystream blockchain. @bwhm, @mnaamani  do we have a bounty for this type of task?

**Comment by bwhm** [comment]
Hey,

I apologize for the late reply. We have had community members add dockerfiles for the [joystream node](Joystream/substrate-node-joystream#72) and the [storage node](Joystream/storage-node-joystream#48) in the meantime.

We would very much pay a bounty for this is as well, see #54.
