### ISSUE TITLE
[Argus] Improve HEAD Request for asset

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4814]

**Comment by zeeshanakram3** [comment]
Currently, for each `HEAD api/v1/{id}` request, a request to QN is made if the assets does not exists already. This isn't an optimal if distributor-node has to scale to serve hunderds of thousands of req/sec.

## Proposal

Look into `ApolloClient`'s built-in qraphql caching mechanism for avoiding frequent IO bound queryies for each asset. Or develop some custom solution for that.

**Comment by kdembler** [comment]
@zeeshanakram3 I recall that we already introduced some caching of those requests. Do you think we should close this issue or there's still more work to be done here?

**Comment by zeeshanakram3** [comment]
Completed in #4834
