### ISSUE TITLE
Offline signer support: Parity signer

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#4825]
## Problem
We have no hardware wallet support _at all_. The cheapest, fastest way of getting this is to use the Parity signer (https://signer.parity.io) which can use any old Android/iPhone that never connects to the internet again as a signer. The user just points their phone at the screen to update metadata and can then sign transactions on their airgapped device.

We're currently not on the metadata portal and haven't yet received a response about getting added and in the interim it seems like a very fast + cheap option to host our own metadata portal, the below links explain how:
* https://paritytech.github.io/parity-signer/tutorials/Add-New-Network.html
* https://github.com/paritytech/metadata-portal

CC @bedeho

**Comment by bedeho** [comment]
Very interesting.

How is the signed transaction relayed back to online device?

**Comment by mochet** [comment]
> Very interesting.
> 
> How is the signed transaction relayed back to online device?

You scan your phone screen with your laptop/computer webcam, its a QR code generated on the airgapped mobile phone.
Tutorial is here: https://www.youtube.com/watch?v=lHKu6b0Hsk8&t=165s

**Comment by chrlschwb** [comment]
Joystream Metadata Portal is now live.
https://metadata.joyutils.org/#/joystream-node

Tutorial is here.
https://handbook.joystream.org/wallets

**Comment by mochet** [comment]
this is now added so closing
