### ISSUE TITLE
YPP voting system

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#4826]
This has also been posted on the Joystream forum for community feedback: https://pioneerapp.xyz/#/forum/thread/512

## Brief
A https://mirror.xyz/race like "competition" for non-crypto creators to onboard via YPP and receive rewards for their current content library and future videos that is voted on by founding members, or some other subset of currently active DAO participants. This would allow for the YPP program to expand beyond the scope of crypto and also ensure that early video content creators on Joystream are subject to some form of quality or category control that tries to ensure they become valuable, contributing content creators who are actively participating and fall within the notion of "The Joystream Community" that is difficult to carve out by relying on metrics or content category alone.
> *"$WRITE RACE is a weekly showdown between people joining the Mirror DAO. The community votes for who gets DAO membership next. At the end of each 2 hour round, the top 10 people are airdropped one $WRITE token, which can be redeemed for Mirror membership, a subdomain, and future community perks."*

# Problem
* YPP currently allows for basically any channel that makes crypto content to sync and receive rewards. This type of content is quite limited in scope and appeal and at the same time our resources are finite, both in terms of infrastructure as well as how many channels can be rewarded on a continuous basis.
	* It is not viable to blanket approve any channel for sync
	* The DAO and community should ideally be taking some form of ownership about what channels can be accepted. Once JSG's YPP reward program ends--the DAO has to step up in some form and reward the content it considers viable.
* Judging "quality" of a channel is highly subjective and appointing "fair" judges is going to be a never ending problem and accountability is going to be difficult.
	* Crypto content creators are heavily incentivized to use referral links and do giveaways which can lead to engagement on their channels that is not organic. This is difficult to judge through metrics alone but a discerning user can pick the quality of a channel by looking through a few videos.
	* Because we do not have many `viewer` users on our apps, we are beholden to the metrics that are available on YouTube (subscriber count, views etc), but we can also look at other platforms creators use (if they have their own Telegram/Discord with many users)
		* As a result of this, the DAO currently doesn't really have much in the way of assigning "value" to channels.
	* There are many channels which could be considered borderline approved such as EEVblog (https://www.youtube.com/@EEVblog). While this channel predominantly talks about electronics, they are also a user of LBRY/Odysee and have made several videos covering it:
		* https://www.youtube.com/watch?v=cxvKx8f5tas
		* https://www.youtube.com/watch?v=8ajM3kkKwNs
	* We are also currently approving channels which have slowed down on video creation recently or just have a huge catalog of old videos--some types of content are very valuable in a content library (e.g. a video for a recipe for tomato soup will always get views) whereas some content is really only relevant in the moment it was created (e.g. a video about the launch of a crypto project)
	

## Assumptions
* Assume with this idea that the current YPP system where crypto channels are approved by JSG on a regular basis is unchanged.

# Solution
* We have 97 people on Discord with the `"founding member"` and more than 150 people with this role on-chain. These users have already proven their dedication to the platform. They also have an embedded incentive to "better" the platform and define the kind of content creators they consider to be valuable.
* If we allow this specific user set or another defined subset of users to use their judgement about potential new channels that come through YPP we can hopefully expand beyond crypto content and enforce a level of quality control.
	* The expectation here is that FMs (or the assigned subset of users) vote for higher quality, distinct channels and take into account the resource usage of potential channels.

### Option 1 - Website
* A website is developed that allows for a subset of Joystream members (could be FMs or more/less restrictive than this) to send a `system.Remark` to upvote potential YPP users from a list.
	* with some threshold required for the YPP channel to be approved and start syncing
	* Or, the highest voted YPP channel gets approved once per day/week or at some interval
* The list of potential YPP channels includes
	* Channel name/link
	* Subscriber count
	* View count
	* Number of videos
	* Channel size (GB)
### Option 2 - Discord
* Potential channel owner fills out a form/applies
* Dedicated channel only outputs the channel information from application
	* Channel name/link
	* Subscriber count
	* View count
	* Number of videos
	* Channel size (GB)
* FMs vote using a Discord emoticon to rate approve/deny for the channel
* If some approve threshold is reached, the channel gets approved for syncing.

**Comment by bedeho** [comment]
1. the problem statement does not really describe a clear problem, its a mix of different limitations and issues, but I cannot parse what the core issue is here. Are you trying to allow non-crypto content? are you trying to only allow "good" crypto content? it's unclear what the issue is
2. this initiative seems specific to Gleev YPP, not Joystream as a whole, so probably this should be on Gleev repo.

**Comment by mochet** [comment]
will rework this and simplify it a bit in the Gleev repo
