### ISSUE TITLE
runtime: Elections - `voting` and `revealing` stage lengths

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#4827]
## Problem
Currently the `voting` and `revealing` duration are the same. As the mainnet has evolved socially it appears that there is more demand/sense for a longer `voting` period than a `revealing` period as candidates do things like interviews, reply to Discord questions, forum posts etc that may be premature to do while the `announcing` stage is still active. 
I do not currently sense that much valuable information comes from candidates themselves during the `reveal` stage besides for people revealing their votes. It seems that the `reveal` stage has less social value than the `vote` stage.

## Solution
Have the `voting` stage be as long as possible compared to the `revealing` stage. Currently they are both 3 days, and if the current 15 day council term length were to be kept the same, I would suggest `voting` be changed to 4 days and `revealing` to 2 days.
If the council term is extended to 30 days this may not be as much of an issue, depending on the duration of each stage.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205253310843257) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment]
It was also suggested to increase the term to a month. Then having one week to vote and three for revealing would leave 20 days to announce.

**Comment by bedeho** [comment]
Superceeded by https://github.com/Joystream/joystream/issues/4866
