### ISSUE TITLE
Pioneer v1 UX Problem: Landing Page

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#485]
When launching pioneer, a user will currently land on the [validator/staking](https://testnet.joystream.org/#/staking) tab. This leaves the user with a task of figuring out what this is, what they can do, and how to do it for themselves.

This problem has been raised as issues many times before, such as:
- https://github.com/Joystream/apps/issues/235
- https://github.com/Joystream/apps/issues/236
- https://github.com/Joystream/apps/issues/253 
- https://github.com/Joystream/apps/issues/441
- #459
...and discussed in other channels.

What such a landing page should contain, nor when to do it is not clear, as we need to decide on whether to focus on new users, existing users, media, etc. 

What is clear is that what we currently have is bad.

Assigning this to @bedeho for now.

**Comment by mochet** [comment]
My suggestions:
- It would be nice to have a section on the landing page that is like #465 but with more of a focus on new or returning users and directing them to where their skills or time might be most in demand. This could be used to highlight roles that are open or the availability of bounties for uploading videos. If not the same as #465 it could maybe just be a direct embed of posts made to an announcements forum subcategory (that is permissioned to sudo key or appropriate person). This could be used also for announcing upcoming testnets or important changes.
- A link or clear mention of the current testnet name, date/block it was started and a link to upcoming testnet with a countdown.
- If not too technically demanding, a few simple stats detailing the amount of content, number of forum posts, number of validators, number of storage providers, size of storage hosted
- Likewise, it would be great to see a very small section showing thumbnails of most recent uploads (2-3 videos) and recent forum posts (2-3 links).
- If there is particularly good content that has been uploaded, it would be nice to have a way to highlight this on the front page.
- Some links to official site, helpdesk, Telegram + minimal project information. Some limited links to pertinent documentation (How to setup a node/storage provider/validator + How to apply for council/curator + How to create keys)
