### ISSUE TITLE
Increase maximum number of sub categories under a category in Forum

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/joystream#4852]
Hello Guys:

Currently, you can only create a maximum of 5 sub categories in a category in Forum. This limit resulted to having 2 WG categories (Technical and Non-Technical):
1. https://pioneerapp.xyz/#/forum/category/33
2. https://pioneerapp.xyz/#/forum/category/34

Suggestion: Increase this limit of sub-categories. 5 seems to be small.

Discord discussions:
https://discord.com/channels/811216481340751934/956881993449242654/1060529705993912370
https://discord.com/channels/811216481340751934/956881993449242654/1147966665347309629

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205416300143373) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Increase to 10.

**Comment by bedeho** [comment]
# TODO

- [ ] Runtime change
- [ ] Add integration test to check new value

**Comment by freakstatic** [comment]
# TODO

- [x] Runtime change
- [x] Add integration test to check new value
