### ISSUE TITLE
Runtime Upgrade to increase council duration

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/joystream#4866]
We are planning on a runtime upgrade to change the following constants.**Council Term Duration** (https://github.com/Joystream/joystream/blob/d1448236349154afa2c1a725f7144990c37d5042/runtime/src/lib.rs#L935)【 code  】

pub const VoteStageDuration: BlockNumber = days!(6);

pub const RevealStageDuration: BlockNumber = days!(4);

pub const AnnouncingPeriodDuration: BlockNumber = days!(4);

pub const IdlePeriodDuration: BlockNumber = days!(14);

【 end code 】

**Forum Subcategory Limit** 

(https://github.com/Joystream/joystream/blob/d1448236349154afa2c1a725f7144990c37d5042/runtime/src/lib.rs#L1227)

```
MaxDirectSubcategoriesInCategory: u64 = 10;
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205488807612673) by [Unito](https://www.unito.io)

**Comment by chrlschwb** [comment]
Endpoint for the chain testing:

Pioneer:
https://pioneer.joystreamstats.live/?network-config=https://pl.joystreamstats.live/joy/config.json

RPC: 
wss://longer-idle-period.joystreamstats.live/rpc

Graphql: 
https://longer-idle-period.joystreamstats.live/graphql

**Comment by bedeho** [comment]
Actual numbers are not final.

**Comment by freakstatic** [comment]
# TODO
- [x] Define new council/election stages durations
- [x] Runtime change
-  [ ] ~~-Add integration test to check new value~~

**Comment by freakstatic** [comment]
Parameters values voted here:
https://pioneerapp.xyz/#/proposals/preview/547

**Idle Period**:    14 days
**Announcing Period**:    6 days
**Voting Period**:    4 days
**Revealing Period**:    4 days
