### ISSUE TITLE
Pioneer v1 UX Problem: Tokenomics Page

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#489]
In order for the Council and other participants to get an overview of the current state of the network/token economics, it would be nice with a page that provides this information without the need to click through all tabs, and do a number of chain state queries.

Some items it could contain:
(*Note:* items below assumes no indexing node.)

#### Roles Specific
For each role:
- Available/open slots
- Who occupies the role now (member), their stake and (recurring) rewards
- Total recurring rewards pr `n` blocks, days or hours
- etc.
For Validators:
- Current effective stake - (`effectiveStake = staking.slotStake * currentValidators`)
- Validator effective stake ratio - (´stakeRatio = effectiveStake / balances.issuance`)
- Estimation of the rewards, pr `n` blocks, days or hours (needs a hardcoded formulae)
For Storage Providers:
- Current parameters
- etc.
After integrating SPs in the bureaucracy module, this would need to be modified
For Curators:
- Current Lead
- Total job openings
- Open job openings
- Total hires
- Total fires
- Curator Mint Capacity
- etc.
For Council Members:
- Election parameters
- When the next election starts
- Council Mint Capacity
- etc.

#### General Tokenomics
- Total issuance
- Sum of all stake
- Ratio of total stake/issuance
- Total recurring rewards pr `n` blocks, days or hours
- Total proposals
- Open proposals
- Projects funded (spending proposals)
- Council
- etc.

## Other
This may overlap slightly with #485 , depending on what goes in there. However, it would be nice to gather some information on overall activity as well, such as:
- Number of media files
- Some statistics from the versioned store on classes and entities
- Forum posts
- etc.

In a world with a working query node, this could be improved significantly...

I think a light version of page should be added either before, or as part of our next release. It would be nice to get some input from the community on what is missing, and what should be prioritized!

**Comment by bedeho** [comment]
Done in #1154
