### ISSUE TITLE
Update Handbook with all Nara changes

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4896]
magic numbers and all the rest. Seems like a lot is missing in council anyway, so good to set those, and add note about last update date so people will detect values going stale in the future. 

![Screenshot 2023-09-29 at 12 21 00](https://github.com/Joystream/joystream/assets/437292/ceeb50cc-cb24-43f7-8963-12eca0d4a5f8)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205614737858901) by [Unito](https://www.unito.io)

**Comment by freakstatic** [comment]
@bedeho are all the required nara changes included on [#47](https://github.com/Joystream/handbook/pull/47)?

**Comment by bedeho** [comment]
Nice job sir, excellent!
