### ISSUE TITLE
[Cli] Update `advanced-transactions` MultiSig calls

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4903]
Based on https://github.com/Joystream/joystream/issues/4891#issuecomment-1742622794
The current implementation of the [advanced-transactions](https://github.com/Joystream/joystream/tree/nara/cli/src/commands/advanced-transactions) (for creating multi-sig transactions) will not work with nara which has some changes to the multi-sig api.

- Update to correct `@substrate/tx-wrapper` version
- Fix arguments to `asMulti` and `approveAsMulti` calls.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205629388840428) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Take note of : https://github.com/Joystream/joystream/issues/4928 , but we must be extremely conservative with any broader polkadotjs changes.
