### ISSUE TITLE
Max number of transfer recipients

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#4947]
**Context**
We need to choose a max amount of possible transfer recipient number for crt extrinsic related to transferring.
Current value = `256u32` 

_Originally posted by @mnaamani in https://github.com/Joystream/joystream/pull/4871#discussion_r1365225815_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205802471577995) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Lets use 24 for now.

**Comment by mnaamani** [comment]
Addressed in https://github.com/Joystream/joystream/pull/4871
