### ISSUE TITLE
WGs: Discretionary spending with vesting

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#4948]
Similar to: https://github.com/Joystream/joystream/issues/4808

Make WG discretionary spending feature with the ability to apply a vesting schedule. There are many payments that the council entrusts WGs to make that could be made to service providers and similar and vesting payments for these have a use--the current system means the WG lead must withdraw the funds to a personal account and then send them with a vesting schedule to the recipient.

**Comment by dobertRowneySr** [comment]
There shouldn't be much be much complexity here, there's a premade extrinsic called `vested_transfer` which is can be leveraged.
https://github.com/paritytech/substrate/blob/ad5399644aebc54e32a107ac37ae08e6cd1f0cfb/frame/vesting/src/lib.rs#L349

**Comment by kdembler** [comment]
https://github.com/Joystream/joystream/pull/5072
