### ISSUE TITLE
Storage squid support for Argus and Colossus

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4957]
There is a consensus among SWG, DWG and JSG that we should migrate our Colossus and Argus nodes away from QN and create a storage-focused squid to serve those nodes' data needs.

Some quick notes on the current status:
1. We want to create a squid and place it in a new repo.
2. Storage squid should borrow as much code as possible from existing Orion mappings.
3. We should use the latest ArrowSquid release with focus on long-term maintenance.
4. One thing I've recently discovered is missing from QN/Orion mappings is some kind of reference to which storage operator accepted the upload of a given object. It would be nice to include that.
5. @zeeshanakram3 already started work on some basic version

**Comment by kdembler** [comment]
@zeeshanakram3 btw we already have ArrowSquid archive: `https://v2.archive.subsquid.io/network/joystream` or `lookupArchive("joystream", { release: "ArrowSquid" })`

**Comment by bedeho** [comment]
Are we planning to have all infra use this one source of truth as the default policy?

**Comment by kdembler** [comment]
I think that makes sense, yes. But only for archive data, all the new processing would be done with RPC. And we can always fallback to only RPC.
