### ISSUE TITLE
[Argus Node] 500 errors for image fetching

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#5019]
When fetching image `1554542` which is stored on storage nodes:
https://storage.freakstatic.com/storage/api/v1/files/1454542
https://adovrn-joystream.yyagi.cloud/storage/api/v1/files/1454542

We are getting 500 errors on all servers
<img width="1422" alt="image" src="https://github.com/Joystream/joystream/assets/51839739/9719d360-6f10-4735-8f05-090736623278">

**Comment by ignazio-bovo** [comment]
To this it might be related the occasional drop in 200-206 request rate:


![Image](https://github.com/Joystream/joystream/assets/51839739/fdc15248-333d-4ee4-8e29-a959812510de)

**Comment by dobertRowneySr** [comment]
![Image](https://github.com/Joystream/joystream/assets/51839739/adf28189-f390-483e-ace8-2e38268e6d48)

The issue is that for that asset the QN object size is different from the size fetched by Argus
https://github.com/Joystream/joystream/blob/da2f47b00bd85ee39dd20c6f64403d53056820ba/distributor-node/src/services/content/ContentService.ts#L266-L267

**Comment by mnaamani** [comment]
Can we determine which bag this object is in so we can check its size according to the runtime?

**Comment by mnaamani** [comment]
Query Node reports:
```json{
  "data": {
    "storageDataObjects": [
      {
        "id": "1454542",
        "storageBagId": "dynamic:channel:29895",
        "size": "20022",
        "ipfsHash": "gWBKXpt5W4pEtPyyk73rnbkb7zyT1kdD2F7vvn1BFpyB73"
      }
    ]
  }
}
```

Which matches with runtime:
<img width="808" alt="Screenshot 2024-01-09 at 10 53 43 AM" src="https://github.com/Joystream/joystream/assets/1621012/0666e513-2980-4610-88c5-ddff8c08b019">

So at least we know the expected size is correct.

Fetching the file and checking hash:
```
yarn storage-node util:multihash -f ~/tmp/1454542.jpg 
yarn run v1.22.19
$ /Users/mokhtar/joystream/joystream/node_modules/.bin/storage-node util:multihash -f /Users/mokhtar/tmp/1454542
2024-01-09 10:57:02:572 info: Hashing /Users/mokhtar/tmp/1454542 ....
2024-01-09 10:57:02:572 info: Hash: gWCT6Z3stvybLos6f3EzJKtkSM57D6eXiCtCcT5toNUzMQ
```

renamed the file to `1454542.jpg` and it opens as a valid image file.

Files from both sources are the same but do not match runtime/QN.

So there are two problems..
- How did the wrong file make it into the uploads folder (without manual intervention)
- If a node had a corrupt/wrong file.. how did the other nodes sync an invalid object?

**Comment by mnaamani** [comment]
On further investigation it was found that this particular file was manually added by operator onto multiple nodes and it did not match the object created in the runtime.

**Comment by kdembler** [comment]
@ignazio-bovo given that we have found the root of the problem, I think we can close this?
