### ISSUE TITLE
accepting Object storage issues 

### ISSUE THREAD

**Issue by yasiryagi** [Joystream/joystream#5044]
Problems: 
1- No way to find out which bucket accepted the object, as the event is recorded without mentioning the bucket that accepted the object. This make tracing the LiveCycle of an object untraceable, this a valuable information of the lifecycle of the object. 

2- Accept object does not account for upload failure: there are currently objects that have been accepted but then the upload failed. As far as QN these files should exist.

**Comment by kdembler** [comment]
@yasiryagi thank you for creating the issue, but could you explain more what your use cases for this is. Without proposing solutions, just what you want to achieve

**Comment by kdembler** [comment]
Closing since https://github.com/Joystream/storage-squid already has the accepting bucket info
