### ISSUE TITLE
Colossus node issue when storing 2 buckets

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#5067]
My storage node crashed unexpectedly on the following configuration
- bucket 14 assigned but not active
- bucket 1 assigned and active

Furthermore on restarting I noticed the following error

![image](https://github.com/Joystream/joystream/assets/51839739/31c5dc32-5d1d-447f-947c-ca8e519ca893)

**Comment by kdembler** [comment]
Closing for now, doesn't seem actionable. Let's reopen if we have more details
