### ISSUE TITLE
Mega parameter upgrade proposal in luxor

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#5099]
Original issue: https://github.com/Joystream/joystream/issues/3626

There are plans to perhaps put this proposal type in the `luxor` runtime upgrade and start with a very limited set of parameters that can be adjusted. This issue exists to try and define a limited scope of parameters that sound like they are low cost/high impact and that would maybe be practical to implement.

* `constitutionality` of such a proposal type still needs to be decided but it may be that some of these parameters should be adjustable rather quickly 

Things I can think of that would be very nice to adjust via proposal--many of these can help to avoid potential future problems without having to wait for a runtime upgrade:
* NFT minting limits
	* rationale: this has been discussed quite a bit already, but there needs to be a way to raise this limit.
* Cost to create a video
	* rationale: in the event of bad actors uploading videos or the rate of uploads becoming overwhelming for the DAO to handle, this can be increased to ensure the economics make sense
* Cost of bloat bond for a video
	* rationale: this would allow the DAO to have a more reactive "cost" for video uploads in relation to their CDN utilization
* Cost to mint an NFT
	* rationale: this can help to avoid a spammy/low quality NFT marketplace. Although it is of course possible to deploy better curation of minted NFTs this can be extremely expensive and may not fix the problem.
* Cost of `system.remark` / `members.MemberRemarked` extrinsic
	* rationale: like/comment spam is an unknown problem and the DAO has no way to react to this
* Cost forum post/thread creation
	* rationale: spam etc of forums may become an issue, DAO has no way to prevent this and the forums have an incomplete feature set. There is very little social use of the forums currently, so in the event of spam it may disrupt regular DAO operations and it may be cheaper and more effective to just raise the cost of being able to post on the forums to make such an attack unsustainable.
* Council/election duration, size, minimum stake etc parameters
	* rationale: `nara` runtime upgrade will adjust these but it seems extremely high friction to require a runtime upgrade every single time there is a desire to change these and as it stands it is difficult to predict the success of parameter changes. There is some discussion about reducing the council size and other elements of the election process and it would be very nice to have these changes be possible without requiring an entire runtime upgrade.
	* downside 1: I imagine the cost of testing these parameters would be quite high
	* downside 2: a council could vote to change the council parameters to something that is dumb and can cause a failure later down the line--what would "safe" limits be here?
	* other consideration: It may make more sense to make this particular one a different proposal type with its own constitutionality value.

**Comment by kdembler** [comment]
- NFT minting limits are already adjustable. In `Nara` a new proposal was introduced that allows the council to adjust global NFT limits. Limits per channel can be adjusted by CWG lead (for specific channel).
- Costs of video/channel creation (bloat bonds) are also adjustable by CWG lead.
- Costs of storage are adjustable by SWG lead.

**Comment by mochet** [comment]
Closing as I think the main areas were already addressed
