### ISSUE TITLE
runtime: adding `pallet-proxy` to runtime

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#5107]
# Problem
Joystream has many account actions that may be desirable to assign a proxy account to perform, this can reduce the security risk on some accounts and also open up some possibilities for things like possibly allowing election voting delegation.

Link to the pallet: https://marketplace.substrate.io/pallets/pallet-proxy/

# Related issues that this may help to solve
* https://github.com/Joystream/joystream/issues/4809
* https://github.com/Joystream/joystream/issues/140
* It could possibly also allow for emergency/3rd party access to storage/distributor + other WG privileged on-chain actions (this needs to be actually checked)

**Comment by freakstatic** [comment]
More info here:
https://wiki.polkadot.network/docs/learn-proxies

**Comment by mochet** [comment]
This was/will be added in `luxor` runtime upgrade so closing
