### ISSUE TITLE
Fix CI checks

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#5109]
#### TLDR
Fix all CI checks after the Luxor release

#### Background
- Many runtime changes have been added to Luxor runtime but not to Luxor QN, disregarding the `tests/network-tests` checks as a consequence
- We have chosen to forego fixing all the CI checks in the runtime PR adding the desired features, to avoid having complex PRs
- We now need a (possibly unique) PR updating all the network test so that the CI checks are successful

**Comment by mnaamani** [comment]
For the runtime upgrade tests, both the integration test and the cargo unit test we need to filter out the storage state which is huge and the memory is running out on the machine when the test is running.

**Comment by dobertRowneySr** [comment]
- Runtime upgrade integration test ➡️ It's the one using fork-off, right?
- Runtime upgrade unit tests ➡️ is it the one with the `try_runtime` feature?
@mnaamani

**Comment by dobertRowneySr** [comment]
@kdembler 
To sum it up: given that luxor has been released, have the CI checks been updated and fixed ?

**Comment by kdembler** [comment]
@ignazio-bovo Luxor upgrade is happening tomorrow, I don't think CI checks have been fixed
