### ISSUE TITLE
Proposal system query node

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#537]
I did my best to pick a set of schemas that are compatible with what we have available, given our `The Graph` constraints, but there may be room for improvement.

Along with the normal entity queries, we want a single free text search that covers all proposal titles and descriptions. The current proposal system was deployed with a runtime upgrade in the Constantinople network, hence no bootstrapping is needed.

Here are the three runtime modules with business logic for the proposal system:

https://github.com/Joystream/joystream/tree/master/runtime-modules/

- The `engine` is a non-public reusable state manager which is responsible for managing the life cycle of a generic proposal, including the voting, staking and execution.
- The `discussion` module is a public very thin discussion system which allows there to be a threaded contextual discussion for each proposal
-  The `codex` is a public module that understands the business logic and parameter values associated with each specific proposal, and it is the public entry point for creating them.

```graphql

type Council @entity {

  council_id: BigInteger!,

  members: [CouncilMember!]!,

  started_at_block: BigInteger!

  # When not set, then it has not ended yet, its in session.
  ended_at_block: BigInteger

}

type CouncilMember @entity {

  council_member_id: BigInteger!,

  member: Member!,

  stake_balance: BigInteger!,

  council: Council!,
}

enum VoteKind {
    Approve,
    Reject,
    Slash,
    Abstain,
}

type VoteOnProposal @entity {

  vote_id: BigInteger!,

  council_member: CouncilMember!,

  proposal: Proposal!

  vote_kind: VoteKind!
}

enum ProposalType {
  Text,
  RuntimeUpgrade,
  ...
}

enum ProposalState {
  Active,
  Cancelled,
  Vetoed,
  Rejected,
  Slashed,
  Expired,
  Gracing,
  Executed,
}

type Proposal @entity {

  # Notice we are not including any variables from ProposalParameters
  # because it is hard coded in the runtime.

  proposal_id: BigInteger!,

  type: ProposalTyper!,

  proposer: Member!,

  title: String,

  description: String,

  created_at_block: BlockNumber,

  discussion_thread: ProposalDiscussionThread!,

  # This really can only be set when `status` is in one of the finalized states
  # but lack of proper algebraic types in graphql does not allow us to make representation fully
  # safe.
  finalized_at_block. BigInteger,

  # Amount which was staked
  stake_balance: BigInt!,

  status: ProposalState,

  abstention_votes: BigInt!,

  approval_votes: BigInt!,

  rejection_votes: BigInt!,

  slash_votes: BigInt!,

}

type TextProposal @entity {

  proposal: Proposal!,

  text: String!,
}

type RuntimeUpgradeProposal @entity {

  proposal: Proposal!,

  wasm: Bytes!,
}

type ProposalDiscussionThread @entity {

  thread_id: BigInteger!,

  title: String,

  created_at_block: BigInteger,

  proposal: Proposal!,

  posts: [ProposalDiscussionThreadPost!]
}

type ProposalDiscussionThreadPost @entity {

  post_id: BigInteger!,

  thread: ProposalDiscussionThread!,

  # If not set, then it was the proposer who made post.
  # This is a safe representation, until we start other actors,
  # unfortunately the graphql typesystem is likely to weak to keep us safe at that time.
  council_member_when_author: CouncilMember,

  text: String!,

  created_at_block: BigInteger!,

  # Counting creation as an update
  last_updated_at_block: BigInteger,

  edition_number: BigInteger,
̋}

```

**Comment by metmirr** [comment]
@bedeho I couldn't find any information related to the `council_id` field of `Council` entity in runtime. This is possible the event that is emitted after the council is elected  [`CouncilElected`](https://github.com/Joystream/joystream/blob/dc3b7624f3f3ace7aeffa2d25f76af7398d9853f/runtime-modules/governance/src/election.rs#L392)

**Comment by metmirr** [comment]
The latest schema can be found here https://github.com/Joystream/joystream/pull/1212 (Starting to work on content directory schema)
