### ISSUE TITLE
Create storage working group

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#544]
# Required changes to create storage working group

## Storage working group
- Introduce the new module - `storage_working_group` as the instance of the bureaucracy module.

## Data directory module
- add_content() extrinsic - remove association with roles module: `random_account_for_role`.
Create a bureaucracy method for the enumeration of the workers to enable it.

- Change the `ensure_root` to `ensure_lead` in these extrinsics:
	- set_primary_liaison_account_id()
	- unset_primary_liaison_account_id() 
	- remove_known_content_id() 
	- set_known_content_id() 

- Change `ensure_signed` to the `ensure_worker` in these extrinsics:
	- accept_content	
	- reject_content

- For the `add_content()` we should keep its `is_member()` authorization.

## Data object type registry module
- Change the `ensure_root` to `ensure_lead` in these extrinsics:
	- register_data_object_type
	- update_data_object_type
	- activate_data_object_type
	- deactivate_data_object_type

## Data object storage registry module
- Change `ensure_signed` to the `ensure_worker` in these extrinsics:
	- add_relationship
	- set_relationship_ready
	- unset_relationship_ready

## Service discovery module
- Change the authorization from account_id to worker_id:
	- set_ipns_id
	- unset_ipns_id
- Change the state to support worker_id: `AccountInfoByAccountId`

## Roles::actors module
-  ~~When a leader fires a storage provider we will need to run a handler to remove it also from the service discovery (HandleActorRemoved). We should add this handler to the bureaucracy module.~~
- Remove `roles::actors` module as obsolete.

## Bureaucracy module changes
- Add method to enumerate workers - it is required to provide a random storage provider.
- ~~Add handler when terminating worker - it is required because we need to remove the storage provider from the service discovery module~~.
- Initialize mint.

## Runtime
- Data migration
- Remove or replace `LookupRoles` to query the working group.
- ~~Change handler HandleActorRemoved.~~ 
- Bureaucracy mint migration.

## Colossus (preliminary changes)
- Add to the monorepo.
- Autofix linter warnings.
- Fix other linter warnings (or add ignore rules).
- Provide initial migration to the TypeScript using 'allow JS mode' (https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html)
- Elaborate subsequent changes for the colossus to support new runtime version.

## Open questions
- Should we change the runtime extrinsics and the colossus in order to support "the worker authorization" instead of current account based? It looks like we moving toward that direction when we add member authorization in the new code and during the refactoring.

- As part of runtime upgrade migration, we will need to unstake the current storage providers so they can unlock their funds.. or we can simply tell them before the runtime upgrade the go into the roles/app and unstake? (**Updated: We tell them before the runtime upgrade to go unstake.**)

- Maybe we can have an initial set worker to be controlled by us so we can have one working storage provider? (**Updated: No - we hire them as others.**)

- Should we remove the obsolete "cli" project from the colossus packages? (**Updated: Yes. Helios should be migrated similar to the Colussus**)

- Should we clear lints warnings before migrating to the Typescript? (**Updated: Yes.**)

- Do we plan to use recurring rewards for the storage providers (they will become hirable so it is possible)? (**Updated: Yes.**)

- How to initialize mint in the bureaucracy module (using the migration or another way)? (**Updated: using the migration.**)

**Comment by mnaamani** [comment]
```
remove_known_content_id()
set_known_content_id()
```

Do seem to be more appropriate to give the content curators access to rather than the storage providers lead.

`ensure_worker` - Do we imply the dispatchable where we use it also requires the worker_id to be provided or is it just a check against the origin? - I guess this ties to the open question about "worker authorization"

runtime - `Data migration` will only be required if we change the `struct DataObject` type to have a liason of type `WorkerId` instead of `AccountId` (**UPDATED: do not migrate DataObject, delete the old data**)

**Comment by shamil-gadelshin** [comment]
Remove these:
- set_primary_liaison_account_id()
- unset_primary_liaison_account_id()

**Comment by shamil-gadelshin** [comment]
Keep it as ensure_root:
- remove_known_content_id()
- set_known_content_id()

**Comment by shamil-gadelshin** [comment]
Change add_content() from is_member() to ensure_signed_member() - add member_id to the function parameter. Add member_id to Content as owner. Consider the data migration.

**Comment by shamil-gadelshin** [comment]
Do not add a handler on worker termination:
- "Add handler when terminating worker - it is required because we need to remove the storage provider from the service discovery module."

**Comment by shamil-gadelshin** [comment]
Runtime - don't do it:
- "Change handler HandleActorRemoved."

**Comment by shamil-gadelshin** [comment]
Done
