### ISSUE TITLE
Query node API preview feature

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#548]
# Background

In some cases, it may be desirable for the application developers to get a preview of a coming API, before the runtime and query node are ready. This allows them to start updating their applications, for example by mocking API behavior, asynchronously.

# Proposal

Introduce some feature in the query node framework CLI that will just spit out the GraphQL API that would result from a given schema.

**Comment by metmirr** [comment]
Done in https://github.com/Joystream/joystream/pull/633
