### ISSUE TITLE
Forum improvements

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#558]
# Background

One of the biggest pains with the current forum is that it's really hard to keep of track whether there is any new activity in the forum to check in on, you just get this top-level view This is equally the case when you go into a specific category. In addition, there are lots of smaller loose ends in the user experience.

https://testnet.joystream.org/#/forum

# Proposal

- A standard solution that is found in most other forums is to list, in each category (including also the root level), what the N most recent posts are, with a link to jump to it. It probably should be something slightly more sophisticated, like the last N posts in the last N threads which had activity, in order to avoid getting a bunch of posts all from the same thread. This could be shown ab
- The actual top-level display of each category makes little sense, we should
  - drop the "New thread" button
  - drop the "Creator column"
- Drop "New category" and "Forum sudo" buttons.
- Each category should also display its description.
- All posts and threads need a date and time, as requested by the council https://testnet.joystream.org/#/proposals/4.
- Manual line breaks inputted during the composition of a new post is not displayed properly when viewed later.
- Each post should have a post number next to it which is linkable.
- When clicking reply, the user is taken to a new page and cannot see posts on the same page. The reply section should be at the bottom of each page of the thread so that a user can reference current posts without needing two windows open.
- Uppercase title is put to all lowercase on thread view (it shows correctly on subforum view) (shown incorrectly here: https://testnet.joystream.org/#/forum/threads/)
- Posts don't support indented markdown lists
- The default font size of the post content is too small.
- Need the option to reply to or quote previous posts.

Overall, feel free to augment the visual style in any way which supports usability.

**Comment by mochet** [comment]
For Markdown I created a post which shows how it currently renders using **https://markdown-it.github.io/**
https://testnet.joystream.org/#/forum/threads/37

It seems to render many things fine.

**Comment by bedeho** [comment]
There is a way of changing the scope here slightly, which will make it radically simpler to address the underlying discovery problem to a significant extent, but with much less time and effort.

If we instead are happy to just show the last `N` posts globally across the entire forum on only the front-page, then we can do a single read operation that reads exactly the last `N` forum posts from the chain, as they will have identifiers `k, k-1, ... , k - (N-1)`, where `k` is the id of the most recent post.

**Comment by mochet** [comment]
Two features that are missing that would be great to see.
The ability to edit a thread title. You can edit post contents, but not thread titles.
The ability to lock threads.

Didn't want to make a new issue for just these items, so if that needs doing let me know and I'll create one.

**Comment by bedeho** [comment]
Note, I will review the runtime source branch next week

https://github.com/Joystream/substrate-forum-module/tree/development

and see how much extra work that would be.

**Comment by mochet** [comment]
If you're going to review the runtime, there is one more feature that I'd add to that list (just started to use forum sudo, so wasn't aware of it before): the ability to move threads between categories/subcategories. Not sure if that's technically feasible, but would be great to see.

**Comment by bedeho** [comment]
https://github.com/Joystream/joystream/issues/712
