### ISSUE TITLE
Storage Progress Tracking

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#56]
This issue is meant to represent a high level tracking of the progress on the [Storage Node](https://github.com/Joystream/storage-node-joystream) for [Acropolis](https://github.com/Joystream/joystream/tree/master/testnets/acropolis).

### Storage Node
- Build the new IPFS backend
   - [ ] Specs
   - [ ] Storage Node
   - [ ] Runtime
   - [ ] UI
   - [ ] Integration
- Build the new storage discovery module 
   - [ ] Specs
   - [ ] Storage Node
   - [ ] Runtime
   - [ ] UI
   - [ ] Integration

### Time permitting
- New staking module with tranches
   - [ ] Specs
   - [ ] Storage Node
   - [ ] Runtime
   - [ ] UI
   - [ ] Integration

**Comment by jfinkhaeuser** [comment]
Tranches and new staking module would be the same thing, IMHO.

Other than that, makes sense!

**Comment by bwhm** [comment]
Fixed. Cross out where applicable!

**Comment by jfinkhaeuser** [comment]
Thanks - I tried, but seem unable to. I'll just ping you with stuff, in the worst case.
