### ISSUE TITLE
Storage Progress Tracking

### ISSUE THREAD

**Issue by jfinkhaeuser** [Joystream/joystream#57]
This issue is meant to represent a high level tracking of the progress on the [Storage Node](https://github.com/Joystream/storage-node-joystream) for [Acropolis](https://github.com/Joystream/joystream/tree/master/testnets/acropolis).

### Storage Node 
- Build the new IPFS backend
  - [x] Specs
  - [x] Storage Node
  - [x] Runtime
  - [x] UI
  - [x] Integration
- Build the new storage discovery module
  - [x] Specs
  - [x] Storage Node
  - [x] Runtime
  - [x] UI
  - [x] Integration

### Time permitting
- New staking module with tranches
  - [x] Specs
  - [ ] Storage Node
  - [ ] Runtime
  - [ ] UI
  - [ ] Integration

----
Duplicates #56 so I can make changes.

**Comment by bwhm** [comment]
Update, 28.05.19:

- Build the new IPFS backend
    - Specs are more or less finalized for acropolis, so should be checked off tomorrow.
    - Storage Node and Runtime aspects should be complete by the end of the week.

- Build the new storage discovery module 
   - Storage Node and Runtime aspects should be complete by the end of the week.

- New staking module with tranches 
   - Specs are more or less finalized for acropolis, so should be checked off tomorrow.

**Comment by bwhm** [comment]
Update 03.06.19:

- Build the new IPFS backend
   - Specs are ready for review
   - Syncing between nodes should be completed tomorrow
   - Decision to add filtering to the runtime will be made once the rest is ready.

- Build the new storage discovery module
   - Discovery ready
   - @siman will be given the task to change the liason in apps

---

Testing of uploading and syncing on the `reckless-testntet` Friday the 7th. Will test more if possible.

**Comment by bwhm** [comment]
## Sub-system test

Test was performed between 14.06.19 and 17.06.19, in line with the latest [live-milestones](https://github.com/Joystream/joystream/tree/master/testnets/acropolis#live-milestones).

* The new storage system worked well, and only small bugs and enhancements were discovered.
* The setup is more complicated than the previous system, but this will be mediated with a verbose [guide](https://github.com/Joystream/helpdesk/tree/master/roles/storage-providers) and increased incentives.
* No need for changes beyond small bugfixes.

**Comment by bwhm** [comment]
## Final Test

The final test was performed 20.06.19, in line with the latest [live-milestones](https://github.com/Joystream/joystream/tree/master/testnets/acropolis#live-milestones).

In addition to myself and @mnaamani, two community members setup their own storage nodes on the mirrored `staging-lts` testnet.

* Both community members were able to follow the instructions, and with a few pointers here and there, we were able to get it up and running.
* Of the 9 uploads tested, 3 failed:
   1. Why the first one failed is not yet identified. The content was recovered, and became available.
   2. The second was a result of a node announcing it's public URL, was chosen as liason, but was not actually online. There are a couple of ways to avoid this. Can be done in `pioneer`.
   3. The third worked after restarting the node.
* Most of these issues should be resolved in time for release.

**Comment by mnaamani** [comment]
Regarding the failed uploads:
i. The liaison failed to send 3 transactions. Frist to accept content (that is why the liaison judgment for the dataobject is still as `Pending`, followed by creating the dataobjectstorage relationship, and finally setting it to ready. There weren't any clear error in logs to indicate why this happened.
The sync run allowed the node to create the relationship at a later time, but also showed that the storage node is syncing content regardless of the liaison judgment status which should be fixed.


ii. The selection of liaison is done by the runtime, so pioneer doesn't really have a choice to select a different liaison. But even though the upload failed, pioneer still showed a successful upload and user continued to add metadata to created object and it appeared in the content explorer. I think here it is a bit of a failure in UI/UX in pioneer that didn't correctly convey the failure of the upload. (There are improvements on the runtime which can also help, like not allowing content to make it into known content ids if not accepted by the liaison).

**Comment by bedeho** [comment]
This is no longer active.
