### ISSUE TITLE
Remove obsolete roles::actors module

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#570]
Remove obsolete `roles::actors` module because it loses any meaning after the integration with the `bureaucracy` module.

[Root issue is here](https://github.com/Joystream/joystream/issues/544).

**Comment by mnaamani** [comment]
Just a thought, we should allow only ability for existing staked roles to unstake. All other extrinsics can be disabled. And on subsequent runtime update we can totally drop it?
