### ISSUE TITLE
Joystream faucet on third party site

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#58]
https://faucets.blockxlabs.com/

**Comment by bedeho** [comment]
What is the purpose of this issue? Who is to do what, and why, and what does it have to do with Acropolis? Is this a WIP issue?

**Comment by bwhm** [comment]
It's [this](https://faucets.blockxlabs.com/) thing.

I guess I should remove it from the acropolis project, as I agree it's not related.

**Comment by bwhm** [comment]
All done on my end. Should go live later today.
