### ISSUE TITLE
Utility module problem

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#580]
# Background

By utility modules, I mean non-public modules that also have autonomous processing (e.g. `on_finalized`). These modules do not have any events at all. This means that any state updates triggered in such a autonomous processing, for example, unstaking someone when a timer runs out, will not be picked up off-chain through the event system. This is very inconvenient for the query node infrastructure, which critically keys off such events.

There is a workaround: if the query nodes also get the ability to do block-level processing hooks, and if special code is written that knows when the autonomous processing will occur in the runtime, then the query node can have analogous logic to update the query state, even without such events. Suffice to say, this is harder to implement and maintain and will require updating the query node.

# Proposal

There are a few options

1. Update query node to have block processing hooks, and replicate business logic here.
2. Introduce events in utility modules, at least for this processing.
3.  Stop using utility modules altogether.

**Comment by dmtrjsg** [comment]
was already done and working on Bounties v1.

@thesan knows the details. 

Closing
