### ISSUE TITLE
Refactor try_to_initiate_application_deactivation and related methods

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#593]
We should consider to refactor `try_to_initiate_application_deactivation` and related methods (`opt_infallible_unstake`) in order to separate preparation phase (check condition and prepare data) and state changing ('mutation-safe') phase.

`try_to_initiate_application_deactivation` should be without side-effects. This will allow to check conditions and invariants  and return errors before changing state.

Current implementation often leads to 'stale opening-state' bugs.

**Comment by bedeho** [comment]
Done in `Oympia`.
