### ISSUE TITLE
Circular dependencies in @joystream/types

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#639]
Recentlly when solving an issue in [joystream-api-examples](https://github.com/Joystream/joystream-api-examples) that arised after updating the `@joystream/types` to a new version there, I noticed that there are a lot of problematic circular dependencies in `@joystream/types`.

This basically means that files are importing from each other in a very chaotic way, making it almost impossible to predict whether ie. the classes they are trying to import will already be defined when they need to be.

This sometimes results in errors like:
```
Class extends value undefined is not a constructor or null
```

In places where some module imports a class from other module and tries to extend it, ie.:
```
// ApplicationId is imported from "../hiring",
// but not initialized yet because of some circular dependencies

export class WorkerApplicationId extends ApplicationId { }; // Error :(
```

I found an article describing an interesting approach to solve the circular dependency problem:
https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

The solution described here is to create a file called `internal.js` which both imports and exports everything we would like to import between modules. The modules then import __only__ from this file, therefore specifying the correct order in `internal.js` should prevent us from running into this kind of errors once and for all.

I haven't tested this solution yet, but it seems very reasonable and could potentially help us avoid a lot of problems when working with / developing the `@joystream/types` library.

**Comment by mnaamani** [comment]
Sounds like it works, and I think I have seen this pattern used by the polkadot-js/api types package itself.

**Comment by Lezek123** [comment]
Fixed in https://github.com/Joystream/joystream/pull/687
CI checks added in https://github.com/Joystream/joystream/pull/752 and updated in https://github.com/Joystream/joystream/pull/963
