### ISSUE TITLE
CI - Additional Checks for Nicaea

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#664]
- Add github actions to run tests for 
  - cli
  - colossus
- Add check when any file changes in `runtime/` folder, ensure runtime version is incremented and Cargo.toml version matches convention.
- Build checks: https://github.com/Joystream/joystream/pull/687#issuecomment-644097609
- ~after yarn install check that yarn.lock wasn't modified, this indicates it wasn't checked in correctly following dependency changes~ - this is already handled by using the `--frozen-lockfile` argument

**Comment by mnaamani** [comment]
Partial work in https://github.com/Joystream/joystream/pull/752
Covers build checks for cli, types.

**Comment by fcescob** [comment]
Adding this to the `before_install` scripts makes Travis skip the build if no Rust or Cargo files were changed:

```yaml
before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE "(.rs|cargo.(lock|toml))$"
      then
      echo "No changes to Rust or Cargo Files, CI not running."
      travis_terminate 0
    fi

```

It is currently working on the `init_atlas` branch (as soon as #693 is merged). 
Full file here: https://github.com/Gamaranto/joystream/blob/atlas-first-screen/.travis.yml

**Comment by mnaamani** [comment]
@Gamaranto wonderful thank you for adding this. I will try to add the same for nicaea branch, and perhaps also update our git hook scripts to include this logic.

I wonder does the git diff command behave the same for pushes after the PR is actually merged travis runs again for the target branch that was updated.

**Comment by mnaamani** [comment]
update shared eslint config with suggestion from https://github.com/Joystream/joystream/pull/943#issuecomment-658652904

**Comment by mnaamani** [comment]
checks for the types library being added by @Lezek123 in https://github.com/Joystream/joystream/pull/963

**Comment by mnaamani** [comment]
completed in:
https://github.com/Joystream/joystream/pull/1023
https://github.com/Joystream/joystream/pull/1020
https://github.com/Joystream/joystream/pull/973
https://github.com/Joystream/joystream/pull/963
