### ISSUE TITLE
Council term rewards issue

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#670]
Currently, each election "round" is 100,800 blocks
- The council "term" (57,600 blocks)
- Announcing stage (14,400 blocks)
- Voting stage (14,400 blocks)
- Revealing stage (14,400 blocks)

During the "term" the council is able to vote and is rewarded with tokens (currently 20k tokens per 3600 blocks)
During Announcing, Voting & Revealing, the council is able to vote but is not rewarded with tokens

The issue with this:
- The council should be rewarded with tokens for the duration of the "election round". The Tokenomics spreadsheet shared early on calculates rewards for the council based on 100,800 blocks and not 57,600 blocks.

Language issues:
- I feel that the language "council term" on the [council page](https://testnet.joystream.org/#/council) is confusing since it only covers 57,600 blocks while the council is still in session and able to vote for proposals.
- The language results in this situation below where it is implied the council is over, but it is only on the voting stage. It is hard for an average user to understand what the council term means because of this:
![image](https://user-images.githubusercontent.com/50830161/84371664-0ce1a480-abeb-11ea-9a2c-a88a76a8817a.png)

The code relevant to the token rewards is here:
https://github.com/Joystream/joystream/blob/6de9df7ddb0afee216d7c42d5f11b52d2ca4b652/runtime-modules/governance/src/council.rs#L138

**Comment by bedeho** [comment]
Excellent observation, I agree that the runtime behavior is incorrect here. This needs to be fixed, adding runtime specific issue here

https://github.com/Joystream/joystream/issues/689

I am not sure when we can get to this, but tagging it with next release status.

It does not help that Pioneer itself is also very badly constructed here.

**Comment by mochet** [comment]
Thanks.
There is also some confusion about when council rounds start. Looking at the recent election (which just finished) it appears the council round number in the UI (and possible its chain state value) is based on when the announce stage is.
This is a very confusing concept, since a council is "active" for 100,800 blocks but the council round changes for the second half of the blocks.
It would make the most sense that the council round starts and ends whenever the council is paid and able to vote on proposals, which is currently not the case. I'm not sure of what the technicalities of changing something like that would be, but perhaps the terminology and language used to explain it could be adjusted.

**Comment by bedeho** [comment]
The Pioneer scene for the election and council is extremely bad, so I am not surprised people are confused. I don't think anything needs to be done on the runtime side to address the issue you are describing, but I think we should probably run the wireframes for the fixes to this by you before we implement it. Still, even with that, we will not have a great experience until we get v2 of Pioneer.
