### ISSUE TITLE
Enforce migration execution before any other logic.

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#69]
### Question we posted in Substrate Riot chat

We are doing a runtime upgrade which requires running migration logic on the storage as well. This is done by running this logic in the on_initialize handler of a designated migration module.

How do we ensure that the handler for this callback is called first in the given module, in case other of our modules have code in their on_initialize that relies on the migration already having been executed after the runtime upgrade.

**Comment by siman** [comment]
interesting question. Any replies yet?

**Comment by bedeho** [comment]
Indeed, they are called in the order that modules are included in the `construct_runtime` macro call.

**Comment by bedeho** [comment]
Solving this should, apart from simply moving the upgrading module to the first spot in the `construct_runtime` call, should also explore compile, or alternatively, run time checks that enforce that the modules is included first.

**Comment by siman** [comment]
https://stackoverflow.com/questions/56699795/what-order-is-on-initialize-invoked-across-different-modules-in-a-substrate-ru
