### ISSUE TITLE
UI Issue: Spending Proposal submit button not working

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#695]
The UI will not allow for a spending proposal to be sent through, "submit proposal" remains inactive regardless of input. Submitting via extrinsic does work.
![image](https://user-images.githubusercontent.com/50830161/84595818-16793f80-ae6b-11ea-9f02-e395c54b7af6.png)

I think this was working before, so maybe something broke it with a recent Pioneer update

**Comment by bedeho** [comment]
Thanks for reporting, I guess we should fix this ASAP.

**Comment by Lezek123** [comment]
Should be fixed with: https://github.com/Joystream/joystream/pull/696
