### ISSUE TITLE
Fix README hyperlinks and typo

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#700]
I found a couple of problems in the README file:
- unite relative and absolute links (set relative links where possible)
- fix for a typo in `rome-testnet.json` missing **t** (`rome-tesnet.json`)
- fix for invalid hyperlinks to moved files (for example ac5952e)
- file CONTRIBUTORS doesn't even seem to ever exist on git -> change link to GitHub insights

**Comment by ondratra** [comment]
Also, we should consider having a `LICENSE` file in the root directory as it is a de-facto standard. Commit ac5952e moved `LICENSE` file to `pioneer` folder, but I guess there was no reason why not keep a copy of license in the root.

**Comment by bedeho** [comment]
Thanks for pointing this out, really appreciate it, will get som eyes on this ASAP.
