### ISSUE TITLE
Working group: impossible to fill opening with 0 unstaking period

### ISSUE THREAD

**Issue by gleb-urvanov** [Joystream/joystream#703]
Worker opening could be created with 0 as unstaking periods:
```
fill_opening_successful_applicant_application_stake_unstaking_period: 0,
fill_opening_failed_applicant_application_stake_unstaking_period: 0,
fill_opening_failed_applicant_role_stake_unstaking_period: 0,
```
In this case, the opening will be impossible to fill. The following error will appear when trying to fill the opening using valid application:
```
FullWorkerOpeningUnsuccessfulApplicationStakeUnstakingPeriodTooShort
```

**Comment by bedeho** [comment]
Nice work identifying this Gleb.

# Diagnosis

My understanding of what happens is
1. `working-group::add_worker_opening` is called with `commitment` where those values are `Some(0)` which is not checked for, they are just stored in the created opening.
2. `worker-group::fill_worker_opening` is later called, which results in an internal call to `hiring::Module::<T>::fill_opening` where these `Some(0)` values are finally passed, like this

```Rust
                hiring::Module::<T>::fill_opening(
                    worker_opening.opening_id,
                    successful_application_ids,
                    worker_opening.policy_commitment.fill_opening_successful_applicant_application_stake_unstaking_period,
                    worker_opening.policy_commitment.fill_opening_failed_applicant_application_stake_unstaking_period,
                    worker_opening.policy_commitment.fill_opening_failed_applicant_role_stake_unstaking_period
                )
```
3.  `hiring::fill_opening` does an explicit check on all periods it receives, using `ensure_opt_unstaking_period_is_ok`, which is the second layer of wrapping around this macro

```Rust
macro_rules! _ensure_opt_unstaking_period_not_zero {
    ($opt_period:expr, $error:expr) => {{
        if let Some(ref length) = $opt_period {
            let lower_bound = One::one();

            if *length < lower_bound {
                Err($error)
            } else {
                Ok(())
            }
        } else {
            Ok(())
        }
    }};
}
```

Here we see that the values are checked to be `>= 1`.

# Remedy

It seems the appropriate fix is to mirror the checks in the delayed call to `hiring::fill_opening` in the working group itself.
I think this makes sense to include in `Nicaea` already.

# Derivative conclusion

This module nesting is hard to manage.
