### ISSUE TITLE
Polymorphic Queries

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#708]
## Background

Let's say you have `N` different types named `T_1, ... , T_N`, all sharing `K` fields, but each also possibly having additional type-specific fields. Let `N_1,...,N_N` be the total number of fields in each type. Moreover, let

- `FieldName(i,j)` denote the name of the jth field in `T_i`.
- `FieldType_G(i,j), FieldType_D(i,j), FieldType_I(i,j)` denote the type of the same field in the final user facing GraphQL API, underlying database and input schema, respectively.
- WLOG, let the first `K` fields represent the shared fields for each `i`, and let `SharedFieldName(j), SharedFieldType_G(j), SharedFieldType_D(j), SharedFieldType_I(j)` have the obvious semantics for the jth shared field.

We would like to be able to query across all such `N` types, with the ability to

1. Filter and order on the `K` shared fields
2. In each of the `N` cases, sub-select type-specific fields.
3. Get paginated results across all returned objects

Notice here that we are not trying to do any matching on any of the type-specific fields.

## Discussion

There is an obvious way to achieve this with the current query node framework, namely to just make a single entity type

```graphql
enum BigEntityType {
	T_1,
	...
	T_N
}

type BigEntity @entity {
	id: ID!
	type: BigEntityType!

	FieldName(1,1) : FieldName_I(1,1)
	...
	FieldName(1,N_1) : FieldName_I(1,N_1)

	...

	FieldName(N_N,1) : FieldName_I(N_N,1)
	...
	FieldName(N_N,N_N) : FieldName_I(N_N,N_N)

}
```

With this input schema, all requirements (1-3) are satisfied, however as `N_1 + ... + N_N` becomes very large, it becomes next to impossible to manage both in the input schema and probably also in the GraphQL API. Often each `N_{*}` is already quite large because of our lack of algebraic field types, which then has resulted in us having to flatten that representation into multiple related fields with complex names and implied invariants.

## Proposal

Let us explicitly support polymorphism in our input schemas which is easier to write and maintain, and generates more type-safe and comprehensible GraphQL APIs, and lastly safer data model representations for the mapping author.

### Input schema

We make interfaces into queryable types, so based on our initial setup we would set

```graphql
interface PolymorphicEntity @entity {
	id: ID!,
	SharedFieldName(1) : SharedFieldType_I(1)
	...
	SharedFieldName(K) : SharedFieldType_I(K)
}

type T_1 @entity implements PolymorphicEntity {
	FieldName(1,1) : FieldType_I(1,1)
	...
	FieldName(1,N_1) : FieldType_I(1,N_1)
}

...

type T_N @entity implements PolymorphicQuery {
	FieldName(N_N,1) : FieldType_I(N_N,1)
	...
	FieldName(N_N,N_N) : FieldType_I(N_N,N_N)
}
```

Here are some rules to complement the example

- it is _not_ possible to use `PolymorphicEntity` as type field in any other context, such as a type member field.
- `interface` must be used with `@entity`, just like other types.
- implementors can implement only one interface for now.

### GraphQL API

At the API we get generated

```graphql
interface PolymorphicEntity {
	id: String!
	SharedFieldName(1) : SharedFieldType_G(1)
	...
	SharedFieldName(K) : SharedFieldType_G(K)
}

type T_1 implements PolymorphicEntity {
	id: String!
	FieldName(1,1) : FieldName_I(1,1)
	...
	FieldName(1,N_1) : FieldName_I(1,N_1)
}

...

type T_N implements PolymorphicQuery {
	id: String!
	FieldName(N_N,1) : FieldName_I(N_N,1)
	...
	FieldName(N_N,N_N) : FieldName_I(N_N,N_N)
}

# input types for PolymorphicEntity:
#
# Type for where/orderby/paginate etc. for
# SharedFieldName(1), ..., SharedFieldName(K)

type Query {
	PolymorphicEntity(<input types for PolymorphicEntity>): PolymorphicEntity
	T_1(<input types for T_1>): T_1
	...
	T_N(<input types for T_N>): T_N
}
```

Notice here that each type `T_1, ..., T_N` are also queryable on their own, which then would allow for normal filtering and ordering on the type specific fields also.

### Database

At the database level, the type hierarchy is modelled using concrete table inheritance, which is natively supported in TypeORM.

Hence we have one base abstract class for `PolymorphicQuery`, and one subclass for each `T_i`.

```ts
export abstract class PolymorphicQuery {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    SharedFieldName(1): SharedFieldType_D(1);

		...

		@Column()
    SharedFieldName(K): SharedFieldType_D(K);
}

@Entity()
export class T_1 extends PolymorphicQuery {

    @Column()
    FieldName(1,K+1): FieldType_D(1,K+1);

		...

		@Column()
    FieldName(1,N_1): FieldType_D(1,N_1);
}

...

@Entity()
export class T_N extends PolymorphicQuery {

    @Column()
    FieldName(T_N,K+1): FieldType_D(T_N,K+1);

		...

		@Column()
    FieldName(T_N,N_N): FieldType_D(T_N,N_N);
}

```

Using concrete table inheritance allows us to support each entity implementing multiple interfaces in the future, single table inheritance does not. It also gives faster single entity queries, but this is of minor significance.

## Comment

It turns out The Graph actually supports this, its just undocumented... lol.
https://discord.com/channels/438038660412342282/438070183794573313/722476865708883971

**Comment by dzhelezov** [comment]
Do we copy all the fields from the interface to all of its subclasses? Note that in GraphQL the fields are not copied, see e.g. here: https://github.com/MichalLytek/type-graphql/blob/master/examples/interfaces-inheritance/schema.gql

**Comment by bedeho** [comment]
Done
