### ISSUE TITLE
WIP: Deploy forum 2.0

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#712]
TODO
1. Drop the internal representation of the user.
2. Drop the internal representation of the moderator?
3. Wrap in working group.
4. Make migration work.
6. Offload archival state.
7. Make thread titled editable.
8. Lock threads.
9. Move threads between categories.
10. Write query node schemas & mappings
11. New Pioneer screens.
12. CLI mod/lead actions.

**Comment by mochet** [comment]
More requests:
- Manual sorting of categories & subcategories (ex: if there is an announcements category made, forum sudo should be able to put it at the top of the category list)
- Forum poll option

**Comment by bedeho** [comment]
- This sorting probably needs to be enforced at the UI layer, not runtime, sounds useful.
- Polling is already implemented in the runtime.

**Comment by bedeho** [comment]
Superceeded by https://github.com/Joystream/joystream/issues/759.
