### ISSUE TITLE
Pioneer: Proposals updates, handling lead openings and applications

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#714]
General issue describing changes required in Pioneer to handle the process of hiring a lead and other lead-related proposals.

In Nicaea the lead (currently only the storage working group one) will pretty much go through the same process of hiring as worker does, with the one difference beeing that the entity responsible for hiring a lead will be the council (through proposals). Council can also perform other bureaucracy-module actions regarding the lead through proposals, ie.: slashing or terminating a lead role.

## Proposals

**To remove:**
- Evict Storage Provider proposal (will become obsolete)
- Set Storage Role Parameters proposal (will become obsolete)

**To add:**
- Create Lead Opening
- Start Accepting Lead Opening Applications
- Begin Reviewing Lead Applications
- Fill Lead Opening
- Terminate Lead (with `require_slashing` parameter)
- Set Lead Reward
- Slash Lead Stake
- Decrease Lead Stake
- Set Group Mint Capacity

_All of those will currently only work for storage working group and will temporarely co-exist with similar, but separate, proposals regarding content working group, ie. `Set Content Working Group Mint Capacity` or `Set Content Working Group Lead`_

For each of those we'll need to:
- Create a new form component
- Add validation information to `joy-proposals/src/validationSchema.ts` (perhaps some of this, ie. the consts, may be moved to `joy-utils` aka. future `joystream-js`)
- Add hardcoded proposal type metadata to `joy-utils/src/consts/proposals.ts` (description, category, stake, approval/slashing thresholds and quorums)
- Add the approperiate handling of the new proposals' details at `/joy-proposals/src/Proposal/Body.tsx`

**Other related things to sort out:**
- May need to adjust filter categories at `/proposals/new`, so they are better aligned with the new possible types of proposals (ie. add `Working groups` cateogry)

## Working Groups tab
There will be a need to differentiate between `Lead` and `Worker` openings (in case of storage working group):
- Separate message regarding available openings for lead and workers in the overview at `/working-groups` index page
- Separate label, filter (in select dropdown) and routes for lead openings (ie. `/working-groups/opportunities/storageProviders` and `/working-groups/opportunities/storageProvidersLead`)
- Perhaps some minor adjustments in the applying process and `/working-groups/my-roles`, but probably not too many of those will be needed.

Assuming the difference between lead and worker opening will only be signaled by an enum flag, this should not be too hard to implement and perhaps the differentiation between those two types of opening doesn't necessarily need to be so strict (since it would be clearly signaled by the opening header, description etc. anyway).

**Comment by bedeho** [comment]
This needs an estimate.

**Comment by Lezek123** [comment]
This is an issue that I later split into: #716, #717, #718, #719, #720, #724, #725 and #726, it's more of an overall summary.
