### ISSUE TITLE
Properly import graphql-server model files 

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/joystream#723]
Currently the index-builder imports the model files by a direct import from the generated graphql-server sources. It would be desirable to decouple this dependency.

One of the possible solutions is to pack the required model files into a standalone module and import that module (locally) at the index-builder generation stage.

**Comment by metmirr** [comment]
Using warthog models in the indexer requires these two `WARTHOG_APP_HOST` and `WARTHOG_APP_PORT` env variable to be set.
