### ISSUE TITLE
Dangling council parameters

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#745]
There are a few council parameters that appear to need to be adjusted frequently, but which its not that safe to allow the council to adjust, such as

- size of council
- budget of council
- election parameters
- reward of council members
- staking requirements of council
- **runtime upgrades**?
- etc.

How are these set? can council do them with large constitutionality value on proposal?

**Comment by bwhm** [comment]
Some of them can be changed via proposals, some not.
These can only be set by sudo:
- `budget of council`
- `reward of council members`

These can be changed with the `Set Election Parameters` proposal:
- `size of council`
- `election parameters`
- `staking requirements of council (minimum only)`

`Runtime upgrades` is a proposal, and was used to add the proposal discussion system.

These two proposal types are the two most critical, and thus has the highest stake, approval quorum/threshold and the longest grace periods...

**Comment by bedeho** [comment]
So I think the simplest solution here, which still retains some flexibility, is to implement constitutionality, covered by this issue https://github.com/Joystream/joystream/issues/144, and adjust the constitutionality to each proposal appropriately. 

Importantly
a) size of council and and council duration must be hardcoded, because these variables impact robustness of constitutionality itself.
b) all proposals with values, such as budgets, still will need some magic hard coded bounds to catastrophic changes.
