### ISSUE TITLE
Forum tech debt + cleanup

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#766]
# Debt

- Remove internal actor representations: https://github.com/Joystream/joystream/issues/762
- Remove commented out `add_extra_genesis` fragment.
- `CategoryByModerator` models a set, as such it should just map to an empty type, as the `bool` value type has no semantic meaning, and can be misleading.
- Remove all label label semantics in the runtime.
- Drop the concept of `ChildPositionInParentCategory` which is used for `Category.position_in_parent_category`, just use an optional identifier to a parent.

## Removing archival state

Before we had proper query infrastructure (now being built), all the business logic state powering the UIs had to come directly from the blockchain state. This meant we shoved lots of write only data in there for archival purposes, this should be avoided. Here we will attempt to remove all such data.

- We no longer store category names, post/thread titles or texts, or any other text, just the hash.
- We no longer enforce length constraints on any such texts either, hence all such parameters and checks can be removed.
- We no longer store old versions of an edited post.
- We no longer store poll alternative texts: `PollAlternative.alternative_text`, just hash.
- We no longer store write only dates (e.g. encoded by `BlockchainTimestamp`), such as when something was created (e.g. `Poll.start_time`).
- We no longer store `Post.nr_in_thread` and `Thread.nr_in_category`.
- We no longer store `num_unmoderated_posts` and `num_moderated_posts` in `Thread`.
- Drop all deletion indicators (post, threads, categories), see next section for genuine deletion.
- We no longer store title, description, creation date, deletions status in categories. They should however just have a single counter for the number of threads and the number of subcategories in as these are not archival, since they must be read when evaluating whether category deletion is safe. But there is no need to distinguish between number of moderated vs. unmoderated threads.

# Enhancements

- Make thread title editable by author.
- Allow moderators to move threads between categories, if they have power in both source and destination.
- Make maximum category depth parameter getable through runtime trait parameters, remove from storage: `MaxCategoryDepth`
- Efficient thread deletion: https://github.com/Joystream/joystream/issues/760
- Moderation semantics for posts changed to mean that it is deleted by the moderator, and that some accompanying rationale is submitted, but is not itself stored.
- Moderation semantics for threads changed in the same way as posts. This can only be done _after_ efficient thread deletion has been implemented.
- Forum category deletion: https://github.com/Joystream/joystream/issues/761
- Allow both the author and forum moderators to update archival status.
- Generalize PostReaction: https://github.com/Joystream/joystream/issues/763
- Use new type safe error mechanism.
- Address this https://github.com/Joystream/joystream/issues/374#issuecomment-652929808
- There are one or more cases where ensures should be introduced, in line with this https://github.com/Joystream/joystream/issues/404#issuecomment-540536869, for example for categories. Identify all such cases. 
- Drop `set_max_category_depth` and the value in storage, its not safe. Instead make it a parameter in the runtime trait.
- Rename `set_moderator_category` to `update_category_membership_of_moderator`
- I am now seeing a call to `clear_prefix`, but I cannto recall why this happens every time, I think it has something to do with migration, but not sure hwy it keeps running. Please investiagate and check whether it is appropriate.

**Comment by ondratra** [comment]
Additional issues:
- rework post reaction storage #948
- unite lead/moderator privileges #946
- ensure input parameters are not used after `// == MUTATION SAFE ==` comment
- introduce limits on storage maps to prevent block gas exhaustion

**Comment by bedeho** [comment]
Done
