### ISSUE TITLE
Make Font Size Fluid [Atlas]

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#773]
Currently, font size is fixed and things like headers and titles can take up too much space on smaller views. 

Fix this by introducing media queries (or fluid typography) for font size. 

Mentioned here: https://github.com/Joystream/joystream/pull/693#pullrequestreview-432470782

**Comment by fcescob** [comment]
Will be addressed in #1108

**Comment by kdembler** [comment]
@Gamaranto I see you've moved this issue to `Reviewer approved` but the mentioned PR only takes care of the landing page header size and I think there will be more places that will need this change. Would you agree to keep this one open?

**Comment by fcescob** [comment]
Yes, let's keep it open until a PR addresses this on all screens / components

**Comment by kdembler** [comment]
Closing this as we gradually fixed this up. If there are some instances left, let's create specific issues for them
