### ISSUE TITLE
Make Video Preview Responsive. [Atlas]

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#774]
The VideoPreview component currently has a fixed width and height, it should instead resize with his container element while ensuring the poster keeps a fixed aspect ratio. 

Mentioned here: https://github.com/Joystream/joystream/pull/693#pullrequestreview-432470782

**Comment by kdembler** [comment]
I've done some work in this area as part of one of the PRs, currently the video preview has a defined max-width. We probably should add min-width as well and make sure the aspect ratio is kept. We will also need to make `videosPerRow` in infinite video grid responsive as well
