### ISSUE TITLE
Unbonding tokens does not work without manual extrinsic submission

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#783]
A user can select the option "Unbond funds" in the validator section. The funds never appear to actually get unbonded and seem to always require manually using the extrinsic `staking withdrawUnbonded()`
There have been a handful of users who have asked for help with this issue (the UI also does not reflect the unbonding period correctly, but that is a separate issue) and in all cases I have encountered the funds never unbond by themselves and always require manual intervention.

**Comment by bedeho** [comment]
Thanks for this, I think I need input from @bwhm on this, I am not so familiar with this part of Pioneer.
