### ISSUE TITLE
Use better units in the theme [Atlas]

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#788]
Right now, the `theme` has units like `spacing.xs` which are not dense enough to cover all use cases and are to associate with a precise measure. 

Refactor the theme to have a better naming convention and more dense units. 

So for example, instead of `spacing.xl, spacing.xxl, spacing.xxxxl` etc... refactor theme to have `spacing.4, spacing.6. spacing.8, ....`

**Comment by kdembler** [comment]
This is partly taken care of by #1090, I think we can close it with that PR and do any more improvements later on if needed
