### ISSUE TITLE
Refactor React Components To Use Arrow Function Syntax [Atlas]

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#807]
Currently we write all of our React components with regular functions, by rewriting them with Arrow Functions, we would get enhanced typechecking features.

**Comment by kdembler** [comment]
More specifically, by typing the arrow functions with `React.FC<PropsType>` like so:
```js
type Props = {
  test: string;
};

const Comp: React.FC<Props> = ({ test }) => {
  ...
}
```

**Comment by kdembler** [comment]
Closing in favor of #1263
