### ISSUE TITLE
Tweak up ESLint [Atlas]

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#811]
We should consider enabling linting with `eslint` as part of the git hooks (it's worth investigating how long will the linting take, but it should be fine).

There are also some rule tweaks we should consider doing:
- make sure `eqeqeq` is enabled
- potentially disable `react/prop-types` since we are using arrow functions that aren't currently supported by that rule: https://github.com/yannickcr/eslint-plugin-react/issues/2353

**Comment by kdembler** [comment]
Also, I think we probably should disable or tweak `a11y` rules (for now at least). Since we're in the mocked components phase, we will get a lot of errors for non-problematic code.

**Comment by fcescob** [comment]
Covered in #878
