### ISSUE TITLE
Proposal bug (between council sessions)

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#828]
Bug: A proposal was made and the UI indicates sufficient votes for approval, but the proposal has not moved to the approval stage. The chain state shows there are 3 votes, the UI shows there are 8 votes. This proposal was created during a council session that ended and a new council was elected, so it is maybe an issue over a proposal carrying through election terms.

The UI shows 8 approve votes:
![image](https://user-images.githubusercontent.com/50830161/85920287-91872080-b883-11ea-83e1-8390d87b19e9.png)

The proposal type requires only 60% votes:
![image](https://user-images.githubusercontent.com/50830161/85920301-acf22b80-b883-11ea-94aa-68d58816fb23.png)

This is the chain state for the proposal:
`{"parameters":{"votingPeriod":43200,"gracePeriod":0,"approvalQuorumPercentage":60,"approvalThresholdPercentage":75,"slashingQuorumPercentage":60,"slashingThresholdPercentage":80,"requiredStake":50000},"proposerId":432,"title":"Replenishing the Content Curator Mint","description":"The mint needs to be replenished.","createdAt":1423360,"status":{"Active":{"stakeId":51,"sourceAccountId":"5GYWp1NM9J21QZzkouCDKCuBCnu92o921ySEcxdas2s3pUCg"}},"votingResults":{"abstensions":0,"approvals":3,"rejections":0,"slashes":0}}`

Link to proposal: https://testnet.joystream.org/#/proposals/28

**Comment by mochet** [comment]
An update: this proposal reached 10/10 votes on the UI and 5/10 on chain state, it never passed so must have a bug. Here is the most up to date chain state data for it:
`{"parameters":{"votingPeriod":43200,"gracePeriod":0,"approvalQuorumPercentage":60,"approvalThresholdPercentage":75,"slashingQuorumPercentage":60,"slashingThresholdPercentage":80,"requiredStake":50000},"proposerId":432,"title":"Replenishing the Content Curator Mint","description":"The mint needs to be replenished.","createdAt":1423360,"status":{"Active":{"stakeId":51,"sourceAccountId":"5GYWp1NM9J21QZzkouCDKCuBCnu92o921ySEcxdas2s3pUCg"}},"votingResults":{"abstensions":0,"approvals":5,"rejections":0,"slashes":0}}`

We never had a vote fail due to lack of participation so I am quite sure it did actually receive all 10 votes shown in the UI.

**Comment by bedeho** [comment]
Great, this seems urgent.

**Comment by mochet** [comment]
If it helps any with diagnosing this issue, there was another instance of this happening on the current testnet: https://testnet.joystream.org/#/proposals/38
In this instance it was for a runtime proposal, and it reached 11/10 votes.

**Comment by shamil-gadelshin** [comment]
The problem was caused by the `double_map` storage from the Substrate framework. 
The issue disappeared after the transition to the substrate version '2.0.0rc4'.
