### ISSUE TITLE
Content-directory 2.0 high level pallet documentation

### ISSUE THREAD

**Issue by iorveth** [Joystream/joystream#829]
WIP

**Comment by bedeho** [comment]
I am not sure exactly what kind of documentation you have in mind, but there is already some public early high level documentation here which is meant for non-developers

https://joystream.gitbook.io/joystream-handbook/subsystems/content-directory

**Comment by iorveth** [comment]
Thank you for the link. 
Actually, i meant developer high level pallet doc comments, like here https://github.com/Joystream/substrate-blog-module/blob/master/runtime-modules/blog-module/src/lib.rs#L1
Won`t we have such form of documentation for the content-directory pallet?

**Comment by bedeho** [comment]
Ok yes, that is a good idea.

**Comment by iorveth** [comment]
Done https://github.com/Joystream/joystream/pull/1076
