### ISSUE TITLE
Query Node Hackusam Submission

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#880]
# Goal

Hackusama is a 7-week online hackathon focused on Substrate, Polkadot, Kusama and Web3 technology. We are intending to submit some version of our internal query node framework to the `Open Hack` category, described as

>.. will allow hackers to build tools, visualizers, or other creative projects to make it easier for developers to build on Kusama Network. For example, this could be tools for translating from one programming language to another or making it easier to test blockchain functionality on Kusama."

# Submission Deadline

`Friday, August 14, 2020 (09:00am UTC)`

# Prizes

Hackaton has the following prizes relevant to our submission.

## Open Hack Champion - $8000

- $8000 (paid in DAI)
- Expedited pitch session for Substrate Builders Program
- Fast-track to discussion about funding ($30k-$100k) with Web3 Foundations Grants team
- 3 Ledger Nano X devices
- 2 hours of consultative phone calls from Web3 and Parity developers
- Polkadot and Kusama swag
- Feature in Polkadot social media

## Open Hack 2nd Place - $4000

- $4000 (paid in DAI)
- 1 hour of consultative phone calls from Web3 and Parity developers
- Fast-track to discussion about funding ($30k-$100k) with Web3 Foundations Grants team
- Polkadot and Kusama swag
- Feature in Polkadot social media
- 3 Ledger Nano S devices

## Open Hack - 3rd Place - $2000

- $2000 (paid in DAI)
- Polkadot and Kusama swag
- Feature in Polkadot social media

##  Community Choice Winner - $2000

One submission will be selected as a Community Choice winner by the DevPost community after a public vote.
- $2000 (paid in DAI)
- Polkadot and Kusama swag
- Feature in Polkadot social media

# Team

The submitting team will be made out of

- Metin
- Dmitrii

They will be submitting as representatives of the Jsgenesis team building Joystream, and Dmitrii will act as the so called “Representative” in the rules, meaning that he can

> represent, act, and enter a Submission, on their behalf. ... By entering a Submission on the Hackathon Website on behalf of a Team, or Organization you represent and warrant that you are the Representative authorized to act on behalf of your Team, or Organization.

Bedeho will provide support.

# Motivation

- Get more review and feedback on the framework.
- Attract attention of prospective contributors to, and users of, the framework.
- Attract attention of prospective builders and community members on Joystream.
- **Metin & Dmitrii get a chance to split (50/50) whatever cash or goodies are won.**

# Submission Requirements

- **S1** Provide a way to access the project for judging and testing by including a link to a repo hosting the submission's code and any other deployment files and testing instructions.

- **S2** Indicate which challenge you're participating in (all valid submissions will automatically be considered for the Community Choice prize).

- **S3** Create a video that includes footage that clearly explains your App’s features and functionality through a comprehensive demonstration.

- **S4** Please include a project name and 150 word description in your submission’s readme file. Teams entering submissions that existed prior to the start of the Submission Period will be required to explain how their submission has been updated during the Submission Period.

# Judging Criteria

## A. Contribution to Decentralization and Web 3.0 Friendliness (25%)
Includes how useful the blockchain or tooling is in the Kusama, Polkadot, and Web 3.0 ecosystem as a whole.

## B. Originality, Creativity, and Innovation (25%)
Includes how new and novel the submission is versus existing technologies.

## C. Technical Difficulty (25%)
Includes the level of skill or knowledge required to build the blockchain, tools, or other type of submission.

## D. User Experience (25%)
Includes how intuitive and understandable the submission is for potential users.

# Plan

The following is a plan which, based on our current progress, the submission requirements, time remaining until deadline, our current team size & availability, attempts to propose a set of tasks which optimises our chances of doing well.

## Approach

Based on the problem we are tackling, we have to double down on judging criteria A and D. I think we do well in the others as well, but we have to have a laser focus to do well with limited time. The set of features we have now (enum, interfaces, FTS, algebraic types, unique) are more than sufficient for an excellent submission, now we have to double down on having it work properly in a great example, and selling the value add.

This means we have to really have exceptional

a) Presentation of the problem.
b) Presentation of what the framework gives you to solve the problem.
c) Examples showing the framework in action.
d) Documentation and tutorial showing how to go 0->1.
e) Convenience in getting started building locally, and deploying.

## Branding

I think we would benefit from having a clear and simple name, around which there could be a simple visual identity, which would serve as the foundation for a website, logo and documentation styling. Until a better one is suggested, I propose we name the framework

`Hydra`

and we have the following one-liner

`A Substrate query node framework`

## Example Node

For the maximum impact, we should try to have a live running query node pointed at the kurrent Kusama network, which provides query services over some module, that really highlights the value of the query node. We should also have a simple running Apollo client which allows someone to go and submit their own queries against the live system.

### Proposal System

Base on my review of the current Kusama code base, located her

https://github.com/paritytech/polkadot/tree/master/runtime/kusama

and the application presenting the current state of the network

https://polkadot.js.org/apps/#/explorer

I suggest we provide archival access to proposal history, something they currently cannot support in their application since proposals are (correctly so) removed from the state of the system after a certain period of time.

https://polkadot.js.org/apps/#/treasury

Looking at the `Cargo.toml` of the Kusama runtime

https://github.com/paritytech/polkadot/blob/master/runtime/kusama/Cargo.toml

on the current `master` branch (`90d5dbe`), I see

```Rust
treasury = { package = "pallet-treasury", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
```

suggesting that they are just using whatever the most recent `treasury` module is in Substrate. Looking at the implementation of the treasury

https://github.com/paritytech/substrate/blob/master/frame/treasury/src/lib.rs

it appears to be quite simple, and the introduction gives a pretty decent explanation. They have just two kinds of proposals, a general spending proposal (`Proposal`), and an open tip (`OpenTip`). The latter also has a human readable reason associated with each, and as such we could use our free text search over it.

Here are some nice queries that may
1. Query all proposals (with filtering, ordering & pagination), including awarded ones which are no longer in the state.
2. Query all open tips (with filtering, ordering & pagination), including completed ones no longer in state.
3. See what proposals a given account has proposed.
4. See what tips a given account has been involved in, as tip contributor or tip creator.

It probably makes sense to do this incrementally so that we at least have something to submit if time becomes an issue.

### Hosted Query Node

We should have a live query node which runs powers the API described above against the live Kusama blockchain. That way we can allow anyone to make queries against the live system by just pointing a hosted GraphQL playground at it, such as https://www.graphqlbin.com/.

## Repository

I suggest we keep everything in our monorepo, and specifically the query node folder

https://github.com/Joystream/joystream/tree/query_node/query-node/substrate-query-framework

We are going to have to show a live of a working node, and I suggest we add an `example` folder which holds the example query node source for the submission.

### README

The main framework readme should include the following

- Cover banner (as we have in our repos).
- (S4) Introductory 150 word description.
- Some salient initial examples of queries and responses.
- Motivation section explaining why exactly this is better than just talking to a full node.
- Link to to hosted Gitbook documentation.
- Link to a running Apollo playground client pointed at the example node.
- License information.

As the README is the primary "sales document" for now, we may need to go beyond this to sell the framework if its not suffiecntly clear from just the above. We can consult some other Substrate developers for feedback to make sure its clear.

## Documentation & Tutorial

We need reference documentation which explains what can be done, and how, and it should include a tutorial which takes the user from not having anything on their system, to deploying.
The tutorial may as well reuse how we built the example node.

I suggest we use a hosted GitBook instance for this, we are already using it for our Joystream handbook. It only requires writing Markdown, and changes can easily be deployed to the public by mirroring a documentation repo.

We can store this documentation in a new folder `documentation` in the framework folder of the monorepo.

## (S3) Video

This could be as easy as showing a screen capture of doing different queries in the playground against the live network. It would be really cool to actually submit a proposal or tip on the network, and then show it appear in a query result after that.

## Landing page

If we have sufficient time, it would be cool if we could have a slick standalone page, for example on `www.hydra.tech` which showed a really inviting presentation of the framework. It could for example have very concrete and powerful examples of what you can do, similar to what you for example see on the Prisma framework website: http://www.prisma.io

## Submission Document

We need a submission document which includes

- The team, and representative contact information.
- (S2) The challenge being participated in, beyond community choice.
- (S4) Project name.
- (S4) 150 word description.
- (S4) How the submission has been updated during the Submission Period.
- (S1) Link to repository.
- (S1) Link to documentation.
- (S1) Link to hosted Apollo playground.
- Link to a private demo video hosted somewhere.

## Tasks

Main idea behind the division of labour is to split the work, so that Metin tries to write the mapping and the schema in the example, and Dmitrii works on the technical writing and making any changes or bug fixes required to the framework as we discover problems based on Metiins progress. Given that Metin already is familiar with Rust, and Dmitrii has considerable training in technical and academic writing in English, I think this is the optimal allocation.

- Submission document: Dmitrii
- Branding: Bedeho
  - Logo
  - README cover illustration
- Example node: Metin (Dmitrii)
- Documentation: Dmitrii
- Video: Dmitrii
- Landing page (speculative): Bedeho

## Project Management

We just run everything from this Github project which we are already using, and schedule meetings ad-hoc as needed.

https://github.com/orgs/Joystream/projects/23

## Risks

- How well does our current framework, and reliance on Polkadotjs, work with version of Polkadtojs and Substrate used in Kusama?
- How reliable will the publicly running node be? if it goes does down regularly, perhaps during judging, then that will be a big problem. For example, will it be able to recover if the full node it is speaking to goes down? What if there is a scheduled runtime upgrade we are not aware of that break it in some way.

**Comment by dzhelezov** [comment]
> Here are some nice queries that may
> 
> Query all proposals (with filtering, ordering & pagination), including awarded ones which are no longer in the state.
> Query all open tips (with filtering, ordering & pagination), including completed ones no longer in state.
> See what proposals a given account has proposed.
> See what tips a given account has been involved in, as tip contributor or tip creator.

We don't currently support queries like `what was the state of X at block Y`, do we?

**Comment by dzhelezov** [comment]
Regarding the deployment:
- Do we use a hosted node or some publicly available Kusama endpoint?
- We need a server to host the query node + indexers anyway. I think an equivalent of AWS t2.medium should do
- It will take considerable time to process all the Kusama blocks even for very simple mappings, so we need to have the indexer up and running well in advance
- For quick 0->1 type deployments we need better support for docker/docker-compose and .env files

**Comment by bedeho** [comment]
> We don't currently support queries like `what was the state of X at block Y`, do we?

No, and I don't think we need this internally yet, so lets wait until someone complains, or we need it.

> Do we use a hosted node or some publicly available Kusama endpoint?

I guess the easiest is to use some public Kusama endpoint, for example whatever the hosted apps application uses.

> We need a server to host the query node + indexers anyway. I think an equivalent of AWS t2.medium should do

Sounds good, just let @bwhm know, and he will pay for it.

> It will take considerable time to process all the Kusama blocks even for very simple mappings, so we need to have the indexer up and running well in advance

Good point.

> For quick 0->1 type deployments we need better support for docker/docker-compose and .env files

Agreed.

**Comment by bedeho** [comment]
Done.
