### ISSUE TITLE
Council UI improvements - Show about field

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#881]
Currently when voting for council members, there is only a list of member names and stake information.
It would be nice to have the about field (which is where the applicants describe their desire to be a council member) be in the member list, voting list and applicant list.

You can access the about field by clicking the member's name, but this adds another interaction and it would be easier to see all the applicants about fields in one common space.

**Comment by bedeho** [comment]
This is being addressed here now

> Council candidacy has no information: #895
