### ISSUE TITLE
Content Directory Permissions Module Specification

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#92]
## Content directory

The content directory will store its class schemas and entities in the versioned object store.
It is responsible for controlling who has permission to perform various write operations to the store.
The permissions model is agnostic to the semantics of classes.

### Security Model

The directory will have two builtin administrative groups:

### Class Admins:
  Can create classes and schemas.
  Can create entities.
  Can delete entities
  Can update property values of any entity in the directory.
  Can set the protected properties of any class.
  Can create and manage user groups.

### Entity Admins (Curators):
  Can create and update any entity in the directory.
  Can delete entities.

### Publishers

For the rest of the platform users to have permission to create entities in the directory
there are two approaches we can take:

Option 1
A single group of publishers can be granted permission to create entities of a subset of classes.
Members have to gain membership into this group to be able to create entities.

Option 2
Each class will have a list of "creators" that can create entities. This list is managed by admins.

In general groups can either be stored as part of the module's state or using a trait
the module can check membership of an origin in individual groups. The latter is the preferred approach for Publishers and Curators and will make sense if we implement the new actor staking module.
The admin group can be managed with sudo.

The creator of an entity is allowed to edit its property values.

For every entity created the creator can choose to restrict who can reference it from another entity.
This is desirable for classes which serve as a collection, eg. podcast, playlists. example below:

```
Podcast (playlist) {
  title: string,
}

PodcastEntry {
  podcastId: Internal(EntityId), // Reference to Podcast
  track: External(ObjectId)
}
```

We want to limit who can associate an entity to be part of a collection. (This is required because we don't yet have a schema property type that is an Array. Hence a collection entity is not self contained)

### Protected properties

For each class admins can specify which properties are protected.
A protected property's value can only be set/modified by admins.
Only Optional parameters can be protected. So when publishers create entities they can leave the protected properties empty.

### Default property values

For each class admins can specify a default value for optional properties.

### Pseudocode

```rust
// Trait implemented by actors module or other user group management module
trait GroupMembership {
  fn is_member(accountId: AccountId) -> bool;
}

// module config trait
trait Trait {
  type Publishers: GroupMembership;
}

struct UserGroup {
  members: Vec<AccountId>
}

type DefaultPropertyValue = (u32, PropertyValue);

struct Class {
  // Who is allowed to create entities other than Admins and Curators
  // if we go with option 2
  creators: Vec<UserGroupId>,

  // index of properties who's values can only be set by admins
  protected_properties: Vec<u32>,

  // Default value to assign optional properties when entity is created
  default_property_values: Vec<DefaultPropertyValue>

  // References are protected
  protected_reference: bool,

  // If locked publishers are not permitted to create new entities
  locked: bool,
}

struct Entity {
  owner: AccountId,
  // A vector of accounts which are permitted to reference this entity from another entity.
  // If vector is empty, no restriction is applied.
  referrers: Vec<AccountId>,

  // Admins and curators can "mark" entities deleted. No new references to this entity should be allowed.
  deleted: bool,
}

// state
Admins: Vec<UserGroupId>
Curators: Vec<UserGroupId>

// publishers are permitted to create entities of this subset of classes (if option 1)
PublishableClasses: Vec<ClassId>

// For every class and entity created in the object store it will have a counter part in the content directory
ClassById : map ClassId => Class
EntityById : map EntityId => Entity

UserGroupById: map UserGroupId => UserGroup

//mapping from ContentDir Ids to Store Ids
StoreEntityIdByContentDirEntityId: EntityId => VersionedObjectStore::EntityId
StoreClassIdByContentDirClassId: ClassId => VersionObjectStore::ClassId
```

**Comment by bedeho** [comment]
Summarizing longer discussion we had here for now.

1. There may be room for generalizing the permissions associated with an `Entity` or `Class`, and perhaps an actor in general, and thereby avoid the three static permission categories of Admin, Curator and Publisher. This allows for greater flexibility and conceptual simplicity, by dropping a lot of of ad-hoc state like `creators`, `protected_properties`, `referrers`.

2. `PublishableClasses` should be normalized as a `bool` in the ´Class`.

3. The reference constraint approach may not be sufficiently expressive, as it lives on `Entities` rather than relationships. As an example one may want to allow anyone to add a podcast episode to their own playliast, but not as a new episode to an existing podcast. This requires capturing this either at the data module level, by doing 

```Rust
enum PropertyDataType {
...
  Internal (ClassId, bool),
...
}
```

or just doing it directly in this permissions module by having the `Entity` class have a  `destination_must_have_same_owner: Vec<int>` , where each index means that this fk property must have same owner.

4. drop `DefaultPropertyValue` concepts

**Comment by mnaamani** [comment]
```Rust
trait Trait {
    type Publishers;
    type Curators;
}

enum Principal {
  Anyone,
  System, // Root Origin
  Account(AccountId),
  Publishers, // any publisher
  Publisher(Publishers::Id),
  Curators, // any curator
  Curator(Curators::Id), // long lived role Id that is independent of what actor fills that role
  Owner, // refers to Class.owner, Entity.owner when used in ClassPermissions and EntityPermissions respectively
  EntityPublisher,// refers to the Entity.publisher can only be used in EntityPermissions
  //ClassOwner, // can be used in EntityPermissions to refer to the owner of the Class of the Entity
  //EntityOwner,
}

enum Owner {
  System, // Root Origin
  Account(AccountId)
}

// Before any class or entity exists we need a set of permissions about who can create classes
// and what default permissions a new class will inherit if not specified
struct RootPermissions {
  // group that can change global permissions - this includes changing the group itself
  // sudo implicitly is allowed to set this field
  change_permissions: Vec<Principal>
  // this group of users can be considered the "Schema Admins".
  // Only a subset of Who makes sense to use here
  create_classes: Vec<Principal>,
  // Who can set the default_class_permissions on the module
  change_default_class_permissions: Vec<Principal>,
}

struct ClassPermissions {
  // group that can change the permissions - this includes changing the group itself
  // sudo implicitly is allowed to set this field
  change_permissions: Vec<Principal>,

  change_owner: Vec<Principal>,
  // Who can add new properties and create new schemas for the class
  add_schemas: Vec<Principal>,
  // Who can set if entities can be created out of this class
  change_can_create_entities: Vec<Principal>,
  create_entities: Vec<Principal>,
  change_initial_entity_permissions: Vec<Principal>,
  change_internal_class_references_constraints: Vec<Principal>,
}

struct EntityPermissions {
  // group that can change the permissions - this includes changing the group itself
  // sudo implicitly is allowed to set this field
  change_permissions: Vec<Principal>,
  change_owner: Vec<Principal>,
  change_internal_class_references_constraints: Vec<Principal>,
  update: Vec<Principal>,
  delete: Vec<Principal>,
}

enum ClassPermissionType {
  Shared(ClassPermissionsId),
  Unique(ClassPermissions)
}

enum EntityPermissionType {
  Shared(EntityPermissionsId),
  Unique(EntityPermissions)
}

// Represents instance of a Class in the versioned store
struct Class {
  // account origin that created the class
  owner: Owner,
  class_permissions: ClassPermissionType,
  initial_entity_permissions: EntityPermissionType,
  //entities_share_permissions: bool,
  entities_can_be_created: bool,
  internal_class_references_with_same_owner_or_publisher_constraint: Vec<int>,
  updated_on: BlockNumber,
  //protected properties?
}

// Represents instance of an Entity in the versioned store
struct Entity {
  owner: Owner,
  publisher: Option<Who::Publisher>,
  curator: Option<Who::Curator>,
  entity_permissions: EntityPermissionType,
  // additive - to class level constraints
  internal_class_references_with_same_owner_or_publisher_constraint: Vec<int>,
  updated_on: BlockNumber,
}

// state
root_permissions: RootPermissions
default_class_permissions: ClassPermissions,

// sharing same Id as counterparts in versioned store
classes: map ClassId => Class
entities: map EntityId => Entity

sharedClassPermissions: map ClassPermissionsId => ClassPermissions
shareEntityPermissions: map EntityPermissionsId => EntityPermissions

nextClassPermissionsId: u64
nextEntityPermissionsId: u64
```

**Comment by mnaamani** [comment]
This notably missing from this spec is any sort of rate limiting or hard limits on creating entities, as well as any special write permissions of certain properties of a class (protected properties)

**Comment by bedeho** [comment]
- Remove `System` as `Principal`, and have all methods (which are all extrinsics), accept Root calls.

- `change_permissions` in `RootPermisisons` does not look safe, and hard to reason about clearly, lets drop?

- Perhaps drop `change_default_class_permissions`? Use of is not enforced in any way, its just a default that any application or user may chose not to respect.

- In light of the latter two points, perhaps just put `create_classes` in state? no need for `RootPermisssions`?

- Is it worth the complexity of having two different places for storing permissions? Feels cleaner to just drop the shared/unique distinction. It means the maps will be bigger, and resolving the permissions will possibly take more time for some objects, but runtime simplicty is so valuable I think. At least until other concerns have been proven to win out.

- I do not think it is safe to have to explicit types which only apply to class or entity under the same `Principal` concept. 

```Rust
Owner, // refers to Class.owner, Entity.owner when used in ClassPermissions and EntityPermissions respectively
EntityPublisher,// refers to the Entity.publisher can only be used in EntityPermissions
```

At the same time I wonder why we cannot just have the singular concept of `Owner`, and thus only one entry in `Principal`, and have it be interpreted the same way across both cases?

- I think all calls which requires someon to authetnicate as a `Principal` in the permissions system shuld require them to submit an index which will be used to look up the relevant `Vec<Prinicipal>` vector, and then make a singular call/check whether the given `AccountId` matches.

- What does `update` in `EntityPermissions` cover? is it changing any value under any schema? or even add a new schema entirely to an entity? If not the latter, then we need a permission for that. Perhaps its good to spearate editing from adding schema support even? Not sure.

- I think I advised alex to drop deletion for now, so I would at least comment it out to not cause confusion.
Deletion does not seem like the same as moderation, and it seems like it has on chain implications, which currently are not described.

- The following different prinicipal cases seem superflous to model in this module

```Rust
Publishers, // any publisher
Publisher(Publishers::Id),
Curators, // any curator
Curator(Curators::Id)
```

This module does not understand the distinction between these internally. For the purposes of this module it is more direct to just have a `ActorGroup(Id)`, which is then mapped on to concepts such as publishers or curators.

- The preciseness of the `Principal` and `Owner` types have different resolutions, which is a problem when any type of principal can in principle be the originator of something. E.g. lets say a `Curator` can create an entity. Does it make sense that the random Account which created that entity becomes the owner, and by virtue of that has some different set of access rights, when the underlying actor was only able to do so by virtue of being a `Curator`. It seems these two concepts shuold mirror each other to avoid the possibility of weird or insecure scenarios?

Its not trivial to resolve, e.g. when some is acting as `Principal.Anyone`, does that mean the owner shuold be anyone? so anyone can edit for example? I don't think so, Account still makes sense there. But for privilidged groups which have their own identifiers, like publishers, then it seems `Account` is wrong.


- The meaning of the following is unclear to me

```Rust
publisher: Option<Publisher::PublisherId>,
curator: Option<Curator::CuratorId>,
```

- The meaning of the following is unclear to me: `internal_class_references_with_same_owner_or_publisher_constraint`, `EntityPermissionsRelationshipToClass`.

**Comment by mnaamani** [comment]
A simpler design after discussions and review:

```Rust
//module trait
trait Trait {
    type GroupMembershipChecker : GroupMembershipChecker
}

trait GroupMembershipChecker {
   type GroupId;
   fn account_is_in_group(account: AccountId, group: Self::GroupId) -> bool;
}

enum BasePrincipal {
  System,
  Account(AccountId),
  GroupMember(GroupMembershipChecker:GroupId),
}

enum EntityPrincipal {
  Base(BasePrincipal)
  Owner
}


// Represents instance of a Class in the versioned store
struct ClassPermissions {
  // concrete permissions
  entity_permissions: EntityPermissions, // or just Vec<BasePrincipal>
  entities_can_be_created: bool,
  add_schemas: Vec<BasePrincipal>,
  create_entities: Vec<BasePrincipal>,
  can_only_be_ref_by: Vec<(ClassId, int)>

  // admins can only be set by root origin
  // admins can update all concrete permissions
  admins: Vec<BasePrincipal>,

  // Block where permissions were changed (including `admins`)
  last_permissions_update: BlockNumber
}

struct EntityPermissions {
  update: Vec<EntityPrincipal>,
  delete: Vec<EntitytPrincipal>,
}

// state
// this group of users can be considered the "Schema Admins".
// updated by Root Origin
create_classes: Vec<BasePrincipal>,


// sharing same Id as counterparts in versioned store
classPermissions: map ClassId => ClassPermissions
entityOwners: map EntityId => BasePrincipal
```

**Comment by bedeho** [comment]
This is super old now, closing, superceeded by 
https://github.com/Joystream/joystream/issues/175
