### ISSUE TITLE
Improve dev UX for query node

### ISSUE THREAD

**Issue by dzhelezov** [Joystream/joystream#924]
Currently, the set-up of the query node is unintuitive and hard to deploy on production. Here are some suggestions on how to improve

- Rename `cli` tool to a more meaningful name (e.g. `hydra`).
- Add scaffolding option to `cli`: by typing `cli new <graph name>`. This will create a directory structure for the indexer, graphql-server, mappers, an example input schema.
- Separate codegen and DB creation/migrations: the DB instance may not be available at the build time
- Add an option to wrap the indexer and the graphql-server into Docker containers 
- Warthog adds a `deploy` target by default for deploying the graphql server to Heroku. This looks like a neat feature, would be nice to integrate it. This will enable production-ready deployments within minutes.

**Comment by dzhelezov** [comment]
Renaming PR: https://github.com/Joystream/joystream/pull/933

**Comment by bedeho** [comment]
Done
