### ISSUE TITLE
Cleanup membershp module

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#93]
Both module storage and interface need to be cleaned up.

The storage and forum client modules need the old interface, and thus storage model, to work, so we have postponed.

1. Drop storage fields

```Rust

pub MemberIdsByRootAccountId get(member_ids_by_root_account_id) : map T::AccountId => Vec<T::MemberId>;

// Mapping of a controller account id to vector of member ids it controls
pub MemberIdsByControllerAccountId get(member_ids_by_controller_account_id) : map T::AccountId => Vec<T::MemberId>;
```

and all modules that depend on them.

2. No method shall identify members through accounts, but we can have checker methods (return `bool`) that can verify the validity of a provided account.

3. Change `Profile` to `Membership`, and storage field `MemberProfile` to `MembershipById`. Its far less confusing.

4. `MembersCreated` => `NextMemberId`

5. `Handles` => `MemberIdByHandle`

6. Drop `UserInfo`, does nothing.

7. Drop `Option` wrapper for around value types of maps, e.g. `MemberProfile`.

**Comment by iorveth** [comment]
Closed by https://github.com/Joystream/joystream/pull/490
