### ISSUE TITLE
Fix forum post reaction

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#948]
There is no way to have efficient thread deletion if we have reactions, at least as they are currently implemented.

```
/// Each account 's reaction to a post.
pub ReactionByPost get(reaction_by_post) config(): double_map T::PostId, blake2_256(T::ForumUserId) => T::PostReactionId;
```

This is because you would have to iterate over all posts in a thread and delete it from this map.

It's worth keeping in mind why we are even storing this in storage, which is that it should be possible for a user to _unreact_. 
I don't actually even see such an unreaction extrinsic at the moment, so we may not even be gaining the benefit of the extra complexity. So either we will have to sacrifice _unreaction_, and just allow users to submit reactions, and as many as they like, or we have to drop the feature entire. I think the former is more desirable.

**Comment by ondratra** [comment]
Does that mean we drop `reaction_by_post` from the storage and only dispatch an event about the reaction?

**Comment by bedeho** [comment]
Correct, of course, we check that the post actually exist, that the origin is a genuine user etc., all the normal checks, but we don't do anything in storage.

**Comment by iorveth** [comment]
Fixed by https://github.com/Joystream/joystream/pull/979
