### ISSUE TITLE
Bug: Account "swallows" tokens after being slashed from validator role

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#972]
A user in Telegram reported an issue where their balance was at 0 due to being slashed from the validator role. As the user had staked 100% of their tokens, they were unable to issue any transactions (like trying the unbonding command).

The amount that was bonded before slashing was above 100k.
I attempted to send the user tokens, but these tokens are "swallowed" into the "total" amount of tokens and the "transferable" amount of tokens stays at 0, thereby making it impossible for the user to perform any actions on the network. The staked amount stays at the same amount and is unaffected by the token transfer.

The user is also a council member with a few thousand tokens staked for that role.

I will update once I have more information but seems like a bug worth looking into as it prevents users from interacting on the network.

Note: I'm not certain these users are actually being slashed from the validator role or if they are just being "dropped" as a validator. This needs to be clarified.

I created a previous issue #915 regarding validator stability issues, this issue is unique as tokens are being "swallowed" by accounts after this happens.

Here is the address:
![image](https://user-images.githubusercontent.com/50830161/87859197-605eb500-c944-11ea-879b-9fe87627e2b3.png)

Here is the address after sending tokens:
![image](https://user-images.githubusercontent.com/50830161/87859199-66549600-c944-11ea-8085-dc29b9f099d4.png)

Address on the current testnet: 5FvPSXq863cQe7EoNVF5bnkirstPYB8KBGqwJkKJjFRRwq3K

**Comment by mochet** [comment]
Updated with account information and screenshots.

**Comment by traumschule** [comment]
good test case (Joystream/pioneer/pull/3894)
